Submitty/Submitty

site/app/controllers/admin/AdminGradeableController.php
Fixes #3852 
Users can normally be redirected to the navigation page after deleting the gradeable or clicking the quick link.
=> [Bugfix] Fix navigation page redirection

site/app/controllers/AuthenticationController.php, site/app/libraries/Core.php
Attempting to interact with the internal Submitty git server throws 500 errors.
Fixes 500 error when trying to interact with internal git server, as the endpoint required semester/course information for the endpoint.
Git clone/git pull/git push of created repo.
=> [Bugfix] Fix the vcs_login authentication endpoint

sbin/authentication.py
Addresses the discussion in https://github.com/Submitty/Submitty/pull/3864#issuecomment-502744130 .
=> [Refactor] Remove deprecated tests in authentication.py

site/app/templates/forum/ShowForumThreads.twig, site/app/views/forum/ForumThreadView.php
Closes #3779  
The following Discussion Forum view now uses Twig- 
`showForumThreads` 
Is this a breaking change? - None discovered yet.
How did you test - Proper working checked manually and by inspecting difference in HTML rendered before and after Twig template.
=> [Refactor] ShowForumThread uses Twig

site/app/templates/forum/CreatePost.twig
Fixes #3894 
Forum posts wrap around, and don't overflow or get clipped on the screen.
=> Set max width to forum posts

site/app/controllers/NavigationController.php, site/app/controllers/admin/AdminGradeableController.php, site/app/models/Button.php, site/app/templates/Navigation.twig, site/app/templates/navigation/CloseSubmissionWarning.twig, site/app/templates/navigation/CloseSubmissionsWarning.twig, site/app/views/NavigationView.php, site/public/js/server.js
Closes #3876
Added a quick button "Close Submissions Now".  Similar to other quick buttons, it changes the due date to the current time.  Has a popup as described in the issue it closes.
=> Close Submission Now Button

site/app/templates/GlobalHeader.twig, site/app/views/GlobalView.php, site/public/js/server.js
Adds `core->buildNewUrl`-like and `core->buildNewCourseUrl`-like functions in `server.js` to make router replacement easier.
=> [Feature] New URL builders in JS

site/public/js/simple-grading.js
=> Fixed not submitting numerics

site/app/controllers/AuthenticationController.php, site/app/controllers/student/SubmissionController.php, site/app/libraries/routers/WebRouter.php, site/public/index.php, site/tests/app/controllers/AuthenticationControllerTester.php, site/tests/app/controllers/submission/SubmissionControllerTester.php
`index.php` is logging `login`, `submission` and `logout`s.
The loggers are now working in controller methods.
=> [Refactor] Move logger to controller methods

site/app/controllers/AdminController.php, site/app/controllers/GlobalController.php, site/app/controllers/admin/ReportController.php, site/app/templates/admin/Report.twig, site/app/views/admin/ReportView.php
**Old:** 
- `/index.php?semester=s19&course=development&component=admin&page=reports`
- `/index.php?semester=s19&course=development&component=admin&page=reports&action=reportpage`
- `/index.php?semester=s19&course=development&component=admin&page=reports&action=summary`
- `/index.php?semester=s19&course=development&component=admin&page=reports&action=csv`
**New:** 
- `/s19/development/reports`
- `/s19/development/reports/summaries'`
- `/s19/development/reports/csv`
- Sidebar -> Grade Reports (As Instructor)
- Direct Access `/s19/development/reports` (As Student & Instructor)
- Clicking `Generate Grade Summaries` and `Generate CSV Report` Buttons (As Instructor)
I am prettifying all the URLs in Submitty! To make the review process easier, I am breaking the replacement work into several …
=> [Router] New URL for ReportController

.setup/bin/setup_sample_courses.py, .setup/data/random/StudentNote.txt, .setup/data/random/TANote.txt
Signed-off-by: fenn-cs <fenn25.fn@gmail.com>
Currently, Note to TA's and Students in the Rubrics section while creating or editing a gradeable are always blank. 
Fixes: #2171 
Generates random comments to supply as notes.
There's a file 'TAcomments.txt` that holds some example comments that are used randomly to generate TA comments there's no such file for student comments. Is it better to add such a file with a few comments or use `lipsum` (https://github.com/thanethomson/lipsum), possible for both TA and student comments eliminating the need for both files.
=> [Refactor:SampleData] Added sample TA/instructor notes for components

site/app/templates/GlobalHeader.twig, site/public/css/server.css, site/public/js/forum.js
Closes #3912
Made a skip to main content button that becomes visible to non-screen-reader users on focus.
=> Made skip nav

grading/python/submitty_router.py
Fixed a variable name that was not changed during a recent refactor of the autograding router.
=> [ Bugfix: Autograding] Fix Improper Variable Name in Autograding Router

site/public/js/ta-grading.js
Refers to a checkbox in #2680 
Added a user editable keyboard shortcut to edit rubrics
=> Made rubric edit shortcut

site/app/views/GlobalView.php, tests/e2e/base_testcase.py, tests/e2e/test_login.py
Closes #2169 
Edited title formatting to reflect page and course
=> Changed title scheme

site/app/views/admin/UsersView.php
=> [Bugfix] Fix missing CSRF token for grader page

site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
=> [Bugfix:InstructorUI] Duplicate line of text

site/app/controllers/GlobalController.php, site/app/controllers/student/RainbowGradesController.php
**Old:** 
- `/index.php?semester=s19&course=sample&component=student&page=rainbow`
**New:** 
- `/s19/sample/grades`
Sidebar entry (for courses that allow students to see rainbow grades).
=> [Router] New URL for RainbowGradesController

site/app/templates/grading/electronic/Status.twig
doesn't fix an issue, but fixes autograding graphs not showing up, adds buckets for histograms and ability to choose bucket size for histograms
tabs without data are disabled (ie if no autograding, autograding histogram tab is unclickable)
tested with every sample assignment available
=> fixes for graphs and ability to choose bucket size

site/app/templates/misc/Code.twig, site/app/views/MiscView.php
Fixed broken Codemirror on TA grading
=> Fixed css and js link in code.twig

site/app/templates/LateDaysTablePlugin.twig, site/app/views/LateDaysTableView.php, site/public/css/latedays.css, site/public/css/server.css, site/public/css/table.css
Should affect only the way LateDaysTablePlugin.twig is rendered
=> Mobile: Late Days Table

grading/load_config_json.cpp
Closes #3667
Adds files tagged as an executable in a compilation testcase to ```compilation_to_validation``` and ```compilation_to_runner```. This fixes an issue which caused only the default ```compilation_to_validation``` files (```.out``` and ```.class```) to be properly validated.
To ensure that executables are available to instructors in execution testcases, this PR adds any file tagged as an executable to the ```compilation_to_runner``` array. However, this means that if there are multiple compilation testcases, all resultant executables will be available to all execution testcases, regardless of the use of pre_commands or an instructor overridden ```compilation_to_runner``` array.
=> [Bugfix:Autograding] Automatically Copy And Validate Executables

grading/main_configure.cpp, site/app/models/gradeable/AutogradingConfig.php, site/app/templates/autograding/AutoResults.twig, site/app/templates/submission/homework/CurrentVersionBox.twig, site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/AutoGradingView.php, site/app/views/submission/HomeworkView.php, site/public/css/server.css
Closes #4046
PR included new functionality outlined in #4046
=> Notebook Upgrades

site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/views/AutoGradingView.php, site/app/views/submission/HomeworkView.php
=> [Bugfix:Autograding] fix typo in notebook variable

site/app/templates/HomePage.twig, site/public/css/homepage.css
Closes #4054 
Long course titles should wrap
=> [Bugfix:Mobile] Fixed long course title wrapping

site/app/templates/admin/users/GraderList.twig, site/app/templates/admin/users/StudentList.twig, site/app/templates/admin/users/UserForm.twig, site/app/views/admin/UsersView.php
Closes #4061 
Oops, I broke it (see issue above)... 
Should fix the edit user and New Student page
=> [Bugfix:Edit User] Fix the edit user/new user page

migration/migrator/migrations/system/20190712224228_email_config_permissions.py
(Probable?) Missing piece of migration from previous PR.
New system should spin up fine.
=> [Bugfix:Installation] php user needs read access to config/email.json

site/app/controllers/AdminController.php, site/app/controllers/GlobalController.php, site/app/controllers/admin/ConfigurationController.php, site/app/views/admin/ConfigurationView.php, site/public/js/course-settings.js
**Old:** 
- `/index.php?semester=s19&course=development&component=admin&page=configuration&action=view`
- `/index.php?semester=s19&course=development&component=admin&page=configuration&action=update`
**New:** 
- `/s19/development/config`
- `/s19/development/config/update` (POST)
- Tried to access the URL directly as a student.
- As instructor, went to the page from the sidebar and tried to update the settings.
=> [Router] New URL for ConfigurationController

site/public/css/global.css, site/public/js/ta-grading.js
Related to comment on #4060 
TA windows now default set on <main>
=> TA window fix 

site/app/controllers/AdminController.php, site/app/controllers/admin/WrapperController.php, site/app/libraries/routers/WebRouter.php, site/app/templates/admin/UploadWrapperForm.twig, site/app/views/admin/ConfigurationView.php, site/app/views/admin/WrapperView.php
**Old:** 
- `/index.php?semester=f19&course=sample&component=admin&page=wrapper&action=show_page`
- `/index.php?semester=f19&course=sample&component=admin&page=wrapper&action=process_upload_html`
- `/index.php?semester=f19&course=sample&component=admin&page=wrapper&action=delete_uploaded_html`
**New:** 
- `/f19/development/theme`
- `/f19/development/theme/upload`
- `/f19/development/theme/delete`
- Tried to access the URL directly as a student.
- As instructor, went to the page from the sidebar -> course settings and then tried uploading and deleting files.
=> [Refactor:Router] New URL for WrapperController

site/app/controllers/GlobalController.php, site/app/controllers/admin/LateController.php, site/app/views/admin/ExtensionsView.php, site/app/views/admin/LateDayView.php, site/public/js/server.js
**Old:** 
- `/index.php?semester=f19&course=sample&component=admin&page=late&action=view_late`
- `/index.php?semester=f19&course=sample&component=admin&page=late&action=view_extension`
- `/index.php?semester=f19&course=sample&component=admin&page=late&action=update_late`
- `/index.php?semester=f19&course=sample&component=admin&page=late&action=delete_late`
- `/index.php?semester=f19&course=sample&component=admin&page=late&action=update_extension`
- `/index.php?semester=f19&course=sample&component=admin&page=late&action=get_extension_details&g_id=open_homework`
**New:** 
- `/f19/development/late_days` GET
- `/f19/development/extensions` GET
- `/f19/development/late_days/update` POST ONLY
- `/f19/development/late_days/delete` POST ONLY
- `/f19/development/extensions/update` POST ONLY
- …
=> [Refactor:Router] New URL for LateController

site/app/controllers/AdminController.php, site/app/controllers/admin/EmailRoomSeatingController.php, site/app/templates/admin/EmailRoomSeating.twig, site/app/views/admin/ConfigurationView.php, site/app/views/admin/EmailRoomSeatingView.php
- GET `/f19/sample/email_room_seating` Email Room Seating Page
- POST `/f19/sample/email_room_seating/send` Send Email
Manually tested as a student and as an instructor. As an instructor, tested opening the course setting page , entering the email room seating page and sending the emails.
=> [Refactor:Router] New URL for EmailRoomSeatingController

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/install_system.sh, sbin/send_email.py
* set correct permissions on logs directories (& refactor/reorganize code)
* replace uses of exit() in send_email.py with sys.exit()
=> [Bugfix:System] Clean up permissions on logs directories

site/app/controllers/grading/SimpleGraderController.php, site/app/templates/grading/simple/Display.twig, site/app/views/NavigationView.php, site/app/views/grading/SimpleGraderView.php, site/public/js/simple-grading.js, site/tests/app/controllers/grading/SimpleGraderControllerTester.php
- GET `http://192.168.56.111/f19/sample/gradeable/grading_lab/grading?view=all` Grading Page
- GET `http://192.168.56.111/f19/sample/gradeable/grading_lab/grading/print?section=1&section_type=registration_section&sort=last` Printing Page for Lab
- POST `http://192.168.56.111/f19/sample/gradeable/grading_test/grading/csv` Uploading CSV
- POST `http://192.168.56.111/f19/sample/gradeable/grading_lab/grading` Saving Scores
Manually tested the following:
- Go to grading page, try different sort orders, and go to printing page (for lab) check if the ordering is correct.
- Try to upload CSV files for numeric gradeable.
- Try to grade both lab and numeric gradeables.
=> [Refactor:Router] New URL for SimpleGraderController

site/app/controllers/StudentController.php, site/app/controllers/pdf/PDFController.php, site/app/templates/autograding/TAResults.twig, site/app/templates/grading/electronic/SubmissionPanel.twig, site/app/views/AutoGradingView.php, site/app/views/PDFView.php, site/public/js/pdf/PDFInitToolbar.js
- GET `http://192.168.56.111/f19/sample/gradeable/open_homework/pdf?filename=something` Student PDF View
- POST `http://192.168.56.111/f19/sample/gradeable/open_homework/pdf/annotations` Grader Adding Annotations
- GET `http://192.168.56.111/f19/sample/gradeable/grading_test/grading/pdf` Grader PDF View
Manually tested the following:
- Grader: Read the PDF file in an embedded view and add annotations.
- Student: See the PDF after grading is released.
Unfortunately there may be conflicts with https://github.com/Submitty/Submitty/pull/4133. I'll resolve them after #4133 is merged.
=> [Refactor:Router] New URL for PDFController

site/app/controllers/AdminController.php, site/app/controllers/GlobalController.php, site/app/controllers/admin/UsersController.php, site/app/templates/admin/users/ClassListForm.twig, site/app/templates/admin/users/GraderList.twig, site/app/templates/admin/users/GraderListForm.twig, site/app/templates/admin/users/RotatingSectionsForm.twig, site/app/templates/admin/users/StudentList.twig, site/app/templates/admin/users/UserForm.twig, site/app/templates/course/CourseMaterials.twig, site/app/templates/grading/Images.twig, site/app/views/admin/UsersView.php, site/public/js/userform.js
- GET `http://192.168.56.111/f19/sample/users`
- (Ajax) GET `http://192.168.56.111/f19/sample/users/instructor`
- POST `http://192.168.56.111/f19/sample/users`
- POST `http://192.168.56.111/f19/sample/users/upload?list_type=classlist`
- GET `http://192.168.56.111/f19/sample/graders`
- POST `http://192.168.56.111/f19/sample/graders/assign_registration_sections`
- GET `http://192.168.56.111/f19/sample/sections`
- POST `http://192.168.56.111/f19/sample/registration`
- POST `http://192.168.56.111/f19/sample/rotating`
Manually tested the following:
- Student Page: add new students, edit existing ones, upload csv
- Grader Page: add new graders, edit existing ones, upload csv, assign reg sections
- Section Page: add/delete reg section, change current rotating sections
The grader editing form …
=> [Refactor:Router] New URL for UsersController

site/app/templates/forum/FilterForm.twig, site/app/templates/forum/ForumBar.twig, site/app/templates/forum/MergeThreadsForm.twig, site/app/templates/forum/ThreadPostForm.twig
Fixes #3976
All label missing errors removed in WAVE, except the ones introduced by JS libraries.
=> [VPAT:Forum] missing label warnings in WAVE

site/app/templates/EditNameForm.twig, site/app/templates/HomePage.twig, site/app/templates/generic/Popup.twig, site/app/views/HomePageView.php, site/public/css/server.css, site/public/js/homepage.js, site/public/js/server.js
Relates to #2566 
- Allows Edit Name Form and Change Password Form to be accessed from keyboard
- Focus automatically selects first input on these modals
- Moved from server.js to homepage.js
- Removed bad HTML that was used for styling - replaced with classes
=> Homepage Modal Keyboard Accessibility

migration/migrator/data/submitty_db.sql, migration/migrator/migrations/master/20190719144150_remove_email_recipient_column.py, site/app/libraries/database/DatabaseQueries.php, site/app/models/Email.php, site/app/models/NotificationFactory.php
Removes recipient column from email table
closes #4001
=> [Refactor:Emails] Remove recipient column

site/public/js/forum.js
Fixes #4158
On clicking a thread its background in the thread list gets changed to white. This helps understand which thread has been read.
=> [Forum: Bugix] Forum read threads marked white

site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig, site/public/css/admin-gradeable.css
Closes #2566 
On new gradeable or edit gradeable, the keyboard should now be able to access the tabs. I also changed the styling to be more representative of tabs rather than grading badges. 
Old Styling:
New Styling:
=> [VPAT:InstructorUI] Edit Gradeable Tab Styling

site/app/controllers/grading/ElectronicGraderController.php, site/app/controllers/student/SubmissionController.php, site/app/views/submission/HomeworkView.php
=> [Bugfix] Fixes TA grading status page error

site/app/controllers/AdminController.php, site/app/controllers/GlobalController.php, site/app/controllers/admin/GradeOverrideController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/SimpleGradeOverriddenUser.php, site/app/models/gradeable/Gradeable.php, site/app/models/gradeable/GradedGradeable.php, site/app/templates/admin/GradeOverride.twig, site/app/templates/grading/electronic/RubricPanel.twig, site/app/views/admin/GradeOverrideView.php, site/app/views/grading/ElectronicGraderView.php, site/public/js/server.js
- GET `/{_semester}/{_course}/grade_override`
- GET `/{_semester}/{_course}/grade_override/{gradeable_id}`
- POST `/{_semester}/{_course}/grade_override/{gradeable_id}/delete`
- POST `/{_semester}/{_course}/grade_override/{gradeable_id}/update`
Manually tested the following:
- See, update & delete grade override entries.
overriden -> overridden
=> [Refactor:Router] New URL for GradeOverrideController

site/app/controllers/forum/ForumController.php
Fixes #4251 
Forum threads get deleted.
=> Fix thread deletion

site/public/css/navigation.css, site/public/css/server.css
Closes #4215
Fixes the gradeables progress bar bug as described in #4215.
=> Fix gradeables progress bar

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20190731093007_self_notification_setting.py, site/app/controllers/NotificationController.php, site/app/controllers/student/GradeInquiryController.php, site/app/controllers/student/SubmissionController.php, site/app/controllers/student/TeamController.php, site/app/libraries/database/DatabaseQueries.php, site/app/libraries/database/PostgresqlDatabaseQueries.php, site/app/models/NotificationFactory.php, site/app/models/User.php, site/app/templates/NotificationSettings.twig, site/tests/app/models/UserTester.php
Some notifications and emails send a notification to the user how performed the action, some do not.
Now all notification and emails will send the notification and email for current user to the sender function and the function will decide whether to send it to the current user depending on whether or not they have the preference to receive notifications on actions they made. 
closes #4232
=> [Feature:Notification] Enable/Disable self notifications/emails

site/app/controllers/admin/LateController.php, site/app/templates/admin/LateDays.twig, site/app/views/LateDaysTableView.php, site/app/views/admin/LateDayView.php, site/public/css/latedays.css, site/public/css/latedaystableplugin.css, site/public/css/menu.css, site/public/css/table.css, site/public/js/server.js
The Late Days Allowed page (found on the sidebar) is now mobile friendly.
- Forms and table shrink with window size
- Notifications are set at a global header level
=> [Feature:MobileUI] Late Days Allowed

tests/e2e/base_testcase.py
The new breadcrumbs weren't reflected in the tests
=> [Bugfix:Tests] Fixed breadcrumb xpath in tests

bin/json_schemas/complete_config_schema.json, python_submitty_utils/submitty_utils/submitty_schema_validator.py
Due to some conflicts between my PR #3882  and @emaicus on PR #3610 .JSON schema does not validates solution container which was introduced in #3882 . Due to this reason schema_validation are failing.
=> [BUGFIX:Tests] Validate solution_containers in complete_config json

site/tests/BaseUnitTest.php, site/tests/app/libraries/routers/AccessControlTester.php
Closes #4191 
A sample test for access control is added by this PR.
This is in PR to see if the tests look reasonable. If so, tests for more endpoints will be added.
=> [Testing:Router] Access control tester

site/app/controllers/admin/ReportController.php
=> [Bugfix:InstructorUI] Fix csv generation

site/app/templates/course/CourseMaterials.twig, site/public/js/server.js
partial work for #4261 
There are currently only 2 options
There is a new button option to select tomorrow's date, so that when jumping from never to a recent time the materials are not momentarily exposed.
=> [Bugfix: Instructor UI] Added Tomorrow Button to Course Materials

site/app/controllers/MiscController.php, site/app/controllers/forum/ForumController.php, site/app/libraries/Output.php, site/public/js/forum.js, site/public/js/server.js
Closes #2362 
All JSON responses in Submitty now use JSend format.
Manually tested places changed.
=> [Refactor:JSON] JSend for all remaining JSON responses

site/app/controllers/HomePageController.php
Course creation endpoint doesn't check if the parameters required exist.
Add parameter check.
=> [Refactor:API] More parameter checking for course creation

site/app/controllers/admin/AdminGradeableController.php, site/public/js/admin-gradeable-updates.js
When attempting to edit information on the "rubric" tab of a test gradeable, an error occurs and information isn't saved.
Fixed error, instructors can now edit the rubric.
=> [Bugfix: Instructor UI] Fix bug stopping rubric editing

site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig, site/app/views/PDFView.php
forgot to add the token on the client
=> [Bugfix:StudentUI] actually fix: missing CSRF token on viewing PDFS

site/app/views/forum/ForumThreadView.php
No need to have this as part of the id.
=> [Bugfix:Forum] remove user from attachment id

autograder/autograder/autograding_utils.py, autograder/autograder/execution_environments/secure_execution_environment.py, autograder/autograder/packer_unpacker.py
Fixes a number of issues regarding grading from vcs checkout.
=> [Bugfix:Autograding] VCS paths in python autograding

site/app/templates/forum/ForumBar.twig, site/app/templates/forum/ShowCategories.twig, site/app/templates/forum/ShowForumThreads.twig, site/app/templates/forum/StatPage.twig, site/app/templates/forum/createThread.twig, site/app/templates/forum/searchResults.twig
Fixes #4330 
No unexpected comma error
=> [Bugfix: Forum] Remove unexpected javascript code

.flake8, .setup/submitty_sudoers, sbin/adduser.py, sbin/adduser_course.py, sbin/submitty_daemon_jobs/submitty_jobs/jobs.py, site/app/views/forum/ForumThreadView.php
=> [Refactor] Split adduser.py into two files

site/app/controllers/course/CourseMaterialsController.php, site/app/templates/course/CourseMaterials.twig, site/app/templates/course/SetFolderReleaseForm.twig, site/public/js/drag-and-drop.js, site/public/js/server.js
1. Updates course materials so that improper dates can no longer be entered.
2. Updates the date picker on the course material page so that changes are saved on close rather than on click.
=> [Bugfix:InstructorUI] Properly Handle Invalid Course Materials Dates

site/app/views/grading/ElectronicGraderView.php
Fixes #4357 
Works as before. Manually tested.
=> [Bugfix:InstructorUI] Fix broken version update button

site/app/templates/forum/CreatePost.twig, site/app/templates/forum/ShowForumThreads.twig, site/public/js/forum.js
Fixes #4353 
No Hide Replies / Show Replies button on the forum post list
=> [Feature:Forum] Remove HidePosts feature in Forum

site/app/controllers/admin/GradeOverrideController.php, site/app/templates/admin/GradeOverride.twig, site/public/css/gradeOverride.css
=> [Feature:InstructorUI] Revise Grade Override for clarity

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/install_system.sh
After API is operational, call the script to initialize the submitty_admin token.
=> [Bugfix:Installation] Initialize the submitty_admin token at end of install_system.sh

site/app/controllers/grading/ElectronicGraderController.php
Fixes #4378
@bmcutler I am outside and don't have Submitty environment with me right now. Please help test manually.
Future developers & reviewers, please listen when your IDE shouts `Variable $whatever might have not been defined`. :sweat_smile:
=> [Bugfix:TaGrading] Fix all access grading bug

.gitignore, .travis.yml, site/app/authentication/AbstractAuthentication.php, site/app/authentication/DatabaseAuthentication.php, site/app/authentication/PamAuthentication.php, site/app/exceptions/AuthenticationException.php, site/app/exceptions/AuthorizationException.php, site/app/exceptions/BadArgumentException.php, site/app/exceptions/BaseException.php, site/app/exceptions/ConfigException.php, site/app/exceptions/CurlException.php, site/app/exceptions/DatabaseException.php, site/app/exceptions/FileNotFoundException.php, site/app/exceptions/FileReadException.php, site/app/exceptions/FileWriteException.php, site/app/exceptions/IOException.php, site/app/exceptions/IniException.php, site/app/exceptions/MalformedDataException.php, site/app/exceptions/NotImplementedException.php, site/app/exceptions/OutputException.php, site/app/exceptions/ValidationException.php, site/composer.lock, site/tests/phpunit.xml, site/tests/ruleset.xml
We were only linting for correct syntax of the PHP code. We were not doing any proper checks to ensure a consistent style.
Adds linting through the [Submitty/submitty-php-codesniffer](https://github.com/Submitty/submitty-php-codesniffer) project (through PHPCS), added for just `app/authentication` and `app/exceptions` in this PR with future PRs adding more folders under full linting.
=> [Testing:Linting] Add proper style linting for subset of PHP code

.gitignore, .setup/INSTALL_SUBMITTY_HELPER_SITE.sh, .travis.yml, site/app/libraries/Core.php, site/app/libraries/response/JsonResponse.php, site/app/libraries/response/Response.php, site/tests/app/controllers/student/SubmissionControllerTester.php, site/tests/app/libraries/response/JsonResponseTester.php, site/tests/app/libraries/response/RedirectResponseTester.php, site/tests/app/libraries/response/ResponseTester.php, site/tests/app/libraries/response/WebResponseTester.php, site/tests/coveralls.yml
The various response classes are tested indirectly by other tests.
Adds direct tests of the response classes to ensure correct behavior.
=> [Testing:Response] Add class testing for different types of responses

site/app/libraries/database/DatabaseQueries.php, site/app/libraries/database/PostgresqlDatabaseQueries.php, site/app/views/submission/HomeworkView.php
This PR adds the function to query a user by a numeric id, works like the getUserByID function.
Adds an additional check to when bulk uploading by QR if the user_id is invalid will check against numeric_ids
=> [Database:Numeric Ids] Add DB query to get user by numeric id

site/app/templates/course/UploadCourseMaterialsForm.twig
=> [Bugfix:CourseUploads] Fix spelling of ammend to amend

site/public/js/server.js
This would reassign the `data` variable instead of checking for equality.
Checks for equality of the `data` variable.
=> [Bugfix:Lichen] Fix using assignment operator instead of equality operator

site/app/templates/forum/ThreadPostForm.twig, site/public/js/drag-and-drop.js
Fixes #4473 
When attempting to post in a thread after viewing a shorter thread, an error was raised in JS and the post would not be made.
The post gets made.
Refreshed the forum page when I had a thread open with two posts, then clicked on thread with more posts, and attempted to make a reply. Before this patch, error would be regularly thrown, with it, I could post.
=> [Bugfix:Forum] error when replying in thread after looking at shorter thread

more_autograding_examples/iclicker_upload/config/config.json, more_autograding_examples/iclicker_upload/config/custom_validation_code/grader.py
Now the iclicker autograding config validates the submitted clicker data: should be 8 digits and should not start with T24 (the model number).
=> [Feature:Autograding] Add autograding for iclicker gradeable

bin/read_iclicker_ids.py
update read_iclickers script to work with new notebook gradeable
=> [Bugfix:InstructorUI] update read_iclickers script

site/app/templates/Authentication.twig, site/app/templates/GlobalFooter.twig, site/app/templates/GlobalHeader.twig, site/app/templates/Notifications.twig, site/app/views/GlobalView.php, site/public/css/authentication.css, site/public/css/notifications.css
First of many PRs following John's emails.
Fixes:
- Stray `</main>`
- Missing `<!DOCTYPE html>`
- Non-unique page titles
- Authentication page missing form labels
- Notification page headers
Most of the remaining things will be tackled and spread out in later PRs, which will be more complex and farther reaching than this one.
=> [VPAT] General accessibility fixes

sbin/submitty_autograding_shipper.py
Fix errors when sshing from the shipper to the worker.
=> [Bugfix:Autograding] shipper worker timeout

site/app/templates/NotificationSettings.twig
Subscribe and unsubscribe to all notifications does not affect self notifications.
Subscribe and unsubscribe button now works as expected.
=> [Bugfix:Notifications] Subscribe and unsubscribe to all now include self notifications

site/tests/app/libraries/routers/AccessControlTester.php, site/tests/app/models/gradeable/LateDaysTester.php
Some parts of `AccessControl` did not have a test written for them.
Adds tests for all public interface of `AccessControl`. No functionality change on the class itself.
=> [Testing] Add direct tests against AccessControl

autograder/autograder/execution_environments/container_network.py
The Docker Python SDK was not properly closing unix sockets bound to containers and networks while autograding. This PR adds closes for these resources, preventing the slow buildup/leakage of file descriptors.
=> [Bugfix:Autograding] Fix Leaking File Descriptors

site/app/templates/admin/Extensions.twig, site/app/templates/course/SetFolderReleaseForm.twig, site/app/templates/course/UploadCourseMaterialsForm.twig
Quick-fixes for a few `label` and `aria-labelledby` accessibility errors.
Note that this does **not** correct accessibility issues involving jump menu ~~or misuse of HTML for styling~~ as such corrections could have an impact on the UI.
=> A Few Quick Accessibility Improvements

site/app/controllers/grading/ImagesController.php, site/app/libraries/DiffViewer.php, site/app/libraries/database/PostgresqlDatabase.php, site/app/models/forum/Forum.php, site/app/views/AutoGradingView.php, site/app/views/PDFView.php
First step in fixing stuff pointed out by phpstan for #4553:
```
------ ------------------------------------------------------------------------
Line   controllers/grading/ImagesController.php
------ ------------------------------------------------------------------------
7      Class app\models\User referenced with incorrect case: app\models\user.
20     Class app\models\User referenced with incorrect case: app\models\user.
20     Class app\models\User referenced with incorrect case: app\models\user.
20     Class app\models\User referenced with incorrect case: app\models\user.
28     Class app\models\User referenced with incorrect case: app\models\user.
33     Class app\models\User referenced with incorrect case: app\models\user.
40     Class app\models\User referenced with incorrect …
```
=> [Refactor] Fix some  static analysis errors

grading/TestCase.cpp, grading/TestCase.h, grading/dispatch.cpp, grading/dispatch.h, grading/main_validator.cpp
Provides the student username to python custom validation scripts. This allows instructors to customize autograding per student/student group.
=> [Feature:Autograding] Provide Student Username to Python Custom Validators

site/app/views/course/CourseMaterialsView.php, site/app/views/grading/ElectronicGraderView.php
Continued work on #4553 
Addresses the following errors
```
------ ----------------------------------------------------------------------------------------------------------
Line   views/course/CourseMaterialsView.php
------ ----------------------------------------------------------------------------------------------------------
25     Function app\views\course\add_files not found while trying to analyse it - autoloading is probably not
configured properly.
25     Inner named functions are not supported by PHPStan. Consider refactoring to an anonymous function, class
method, or a top-level-defined function. See issue #165 (https://github.com/phpstan/phpstan/issues/165)
for more details.
138    Function add_files not found.
------ …
```
=> [Refactor] Change inline functions to anonymous functions

site/app/controllers/admin/AdminGradeableController.php, site/app/controllers/admin/LateController.php, site/app/controllers/admin/PlagiarismController.php, site/app/controllers/grading/ElectronicGraderController.php, site/app/controllers/student/SubmissionController.php, site/app/libraries/FileUtils.php, site/app/libraries/database/DatabaseQueries.php, site/app/libraries/database/PostgresqlDatabaseQueries.php, site/app/models/AbstractModel.php, site/app/models/GradingOrder.php, site/app/models/gradeable/GradedGradeable.php, site/app/views/grading/ElectronicGraderView.php, site/tests/app/libraries/database/AbstractDatabaseQueriesTester.php, site/tests/app/libraries/database/PostgresqlDatabaseQueriesTester.php, site/tests/ruleset.xml
There were many violations of the PHPCS rule `Generic.Formatting.DisallowMultipleStatements.SameLine`.
The violations are fixed.
No code was actually changed, just re-styled.
=> [Refactor:PHPCS] Fix violations of Generic.Formatting.DisallowMultipleStatements.SameLine

site/app/controllers/OfficeHoursQueueController.php, site/app/controllers/admin/EmailRoomSeatingController.php, site/app/controllers/admin/PlagiarismController.php, site/app/controllers/course/CourseMaterialsController.php, site/app/controllers/forum/ForumController.php, site/app/controllers/forum/ForumController2.php, site/app/controllers/grading/ElectronicGraderController.php, site/app/controllers/pdf/PDFController.php, site/app/controllers/student/GradeInquiryController.php, site/app/libraries/DiffViewer.php, site/app/libraries/ExceptionHandler.php, site/app/libraries/FileUtils.php, site/app/libraries/GradingQueue.php, site/app/libraries/database/DatabaseQueries.php, site/app/libraries/database/PostgresqlDatabaseQueries.php, site/app/models/Config.php, site/app/models/Email.php, site/app/models/User.php, site/app/models/gradeable/AutoGradedVersion.php, site/app/models/gradeable/Component.php, site/app/models/gradeable/Gradeable.php, site/app/views/AutoGradingView.php, site/app/views/GlobalView.php, site/app/views/OfficeHoursQueueView.php, site/app/views/admin/PlagiarismView.php, site/app/views/course/CourseMaterialsView.php, site/app/views/forum/ForumThreadView.php, site/app/views/grading/ElectronicGraderView.php, site/tests/app/controllers/course/CourseMaterialsControllerTester.php, site/tests/ruleset.xml
Fixes all `Generic.WhiteSpace.ScopeIndent` style errors.
This rule helps ensure that we're consistently using 4 spaces per indent, and that things within blocks are properly indented to the appropriate action.
=> [Refactor:PHP] Fix Generic.WhiteSpace.ScopeIndent style errors

site/app/templates/GlobalHeader.twig
=> [Bugfix:UI] incorrect mascot duck filename

.setup/CONFIGURE_SUBMITTY.py, tests/e2e/test_forum.py
On a new install or after re-running `CONFIGURE_SUBMITTY.py`, `duck_special_effects` will not exist in the `submitty.json` config file, which is a result of #4666.
Adds a set value (`False`) to be written for `duck_special_effects` as part of `CONFIGURE_SUBMITTY.py`. Fixing things so that re-running `CONFIGURE_SUBMITTY.py` does not overwrite the previously used value is part of #4687. 
This also fixes the failing E2E test (#4683) that broke due to the output of a PHP Notice when running the test that threw off the layout of the page. Additionally, while fixing it, this also adds in a test that merging adds a "title" to the post as requested, and disregarded, in https://github.com/Submitty/Submitty/pull/4541#pullrequestreview-292991793.
=> [Bugfix:Duck] Provide default value if duck_special_effects is undefined

site/app/controllers/admin/GradeOverrideController.php, site/app/controllers/admin/PlagiarismController.php, site/app/controllers/admin/UsersController.php, site/app/controllers/forum/ForumController.php, site/app/controllers/forum/ForumController2.php, site/app/controllers/grading/ElectronicGraderController.php, site/app/controllers/student/SubmissionController.php, site/app/controllers/student/TeamController.php, site/app/libraries/database/ForumQueries.php, site/app/models/GradeableAutocheck.php, site/app/models/forum/Post.php, site/app/models/forum/Thread.php, site/app/models/gradeable/GradedComponent.php, site/app/views/admin/ExtensionsView.php, site/app/views/grading/ElectronicGraderView.php, site/tests/app/controllers/course/CourseMaterialsControllerTester.php, site/tests/ruleset.xml
Adds style rules that lines should not end with extraneous whitespace nor should there be whitespace between the last character of a line and the closing `;`.
=> [Refactor:PHP] Fix non-control structure Squiz.WhiteSpace style errors

site/composer.json, site/composer.lock
=> [DependencyDev:PHP] Update submitty/php-codesniffer to 2.2.1 in /site

site/app/controllers/admin/PlagiarismController.php, site/app/controllers/course/CourseMaterialsController.php, site/app/libraries/Core.php, site/app/libraries/DiffViewer.php, site/app/libraries/database/DatabaseFactory.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/GradingOrder.php, site/app/models/NotificationFactory.php, site/app/models/PDFGenerator.php, site/app/models/forum/Forum.php, site/app/models/forum/Thread.php, site/app/models/gradeable/GradedGradeable.php, site/app/views/forum/ForumThreadView.php, site/app/views/grading/ElectronicGraderView.php, site/tests/app/authentication/DatabaseAuthenticationTester.php, site/tests/app/controllers/course/CourseMaterialsControllerTester.php, site/tests/app/controllers/student/SubmissionControllerTester.php, site/tests/app/libraries/FileUtilsTester.php, site/tests/app/models/ConfigTester.php, site/tests/ruleset.xml
Fix the `PSR2.Methods.FunctionClosingBrace` style errors, which is that there should not be a newline at the end of a function.
=> [Refactor:PHP] Fix PSR2.Methods.FunctionClosingBrace style errors

site/app/controllers/grading/SimpleGraderController.php
Ran the phpcs which found a useless semicolon and then ran phpcbf and it fixed that file that had a useless semicolon.
There is no longer a semicolon
=> fixed semicolon

tests/e2e/test_grade_inquiry.py
No end to end tests to test the grade inquiry panel and box which have a lot of case dependent elements
Basic grade inquiry panel and box test that test the panel when there is normal submission, and no submission.
I will add more with future pull requests that fix bugs that I find while writing new tests and outstanding bugs.
These test are bypassed for Travis as the Travis instance does not have submissions information
These tests will fail if lakinh or bauchg's submissions or grade inquiries for grades_released_homework in sample course are edited. These tests use the default configuration for users lakinh and bauchg.
see #4626
=> [Testing:GradeInquiry] Grade inquiry panel and box e2e tests

site/app/controllers/admin/UsersController.php, site/app/libraries/database/DatabaseFactory.php, site/tests/ruleset.xml
=> [Refactor:PHP] Fix for Unreachable Code

site/app/controllers/admin/ReportController.php, site/app/libraries/Output.php, site/tests/ruleset.xml
Fixes the SlevomatCodingStandard.PHP.ShortList.LongListUsed.
=> [Refactor:PHP] Fix SlevomatCodingStandard.PHP.ShortList.LongListUsed style errors

bin/grading_done.py, sbin/submitty_autograding_shipper.py
Now this script will properly display how work is being spread across the worker machines.
=> [Feature:Autograding] Revise grading done for machines/capabilities

site/app/templates/EditNameForm.twig
modified:   site/app/templates/EditNameForm.twig
Fix accessibility label issue in user preferred name change form.
=> [VPAT] Label tag fix for user preferred name change form.

autograder/autograder/insert_database_version_data.py
Fixes #3222. The module string was out of date and still documented it as if the module should be run directly.
Updates the docstring to reflect the current usage of the script, largely just removing all discussion of it running it as a CLI script, and just the high level details of what it does.
=> [Refactor:Autograding] Fix module string for insert_database_version_data

site/public/js/drag-and-drop.js
Closes #4833 
Bug is now fixed and respective feature is working as per the expectation in the mentioned [issue](https://github.com/Submitty/Submitty/issues/4833)
=> [Bugfix:Submission] Inconsistent behaviour while uploading zip file

site/app/views/submission/TeamView.php
=> [Bugfix:Submission] added breadcrumb to team page

.setup/bin/versions.sh, site/app/views/admin/PlagiarismView.php, site/public/js/server.js
MIPS plagiarism detection is not available.
MIPS plagiarism detection is added as a choice.
This relies on the [MIPS tokenization merge request](https://github.com/Submitty/Lichen/pull/17) to use MIPS with Lichen.
=> [Feature: PlagiarismDetection] Add support for MIPS plagiarism detection

.setup/bin/versions.sh
=> Fix typo in version for Lichen

bin/make_generated_output.py
Adds un-imported package that was causing vagrant up to fail.
More complete bugfix incoming.
=> [System:Bugfix] Fix Vagrant Up

site/app/models/GradeableAutocheck.php
Fix PHP lint failures located in site/app/models/GradeableAutocheck.php
=> removing php lint bugs

site/app/libraries/FileUtils.php
One of the merged PRs had a style error.
Fixes the style error.
=> [Refactor:PHP] Fix style errors in FileUtils

site/app/templates/HomePage.twig, site/app/templates/Notifications.twig, site/app/templates/admin/PlagiarismHighlightingKey.twig, site/app/templates/admin/users/GraderList.twig, site/app/templates/admin/users/StudentList.twig, site/app/templates/admin/users/UserForm.twig, site/app/templates/autograding/AutoResults.twig, site/app/templates/autograding/TAResults.twig, site/app/templates/course/CourseMaterials.twig, site/app/templates/forum/CreatePost.twig, site/app/templates/forum/ShowCategories.twig, site/app/templates/forum/ShowForumThreads.twig, site/app/templates/forum/displayThreadList.twig, site/app/templates/grading/electronic/Details.twig, site/app/templates/grading/electronic/SubmissionPanel.twig, site/app/templates/grading/simple/Display.twig, site/app/templates/submission/homework/BulkUploadBox.twig, site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/admin/PlagiarismView.php, site/public/js/server.js, site/public/templates/grading/EditComponentHeader.twig, site/public/templates/grading/Mark.twig, site/public/templates/grading/SavingTools.twig
Icons have aria-hidden
Icons now dont have aria-hidden and all have aria-label
See this issue for a lot more details
closes #3730 
I fixed all the ones mentioned in the issue as well as a few more found using this regex `<i.*?aria-hidden=".*?".*?></i>`
However there were 4 icons in ShowForumThreads.twig that I could not figure out what to give them as a label so I did not change them.
=> [VPAT] Removed all aria-hidden on icons

.setup/bin/versions.sh
=> [Dependency:System] update SysadminTools version

.setup/bin/versions.sh
=> [Dependency:System] update Tutorial version

site/app/controllers/student/SubmissionController.php, site/app/libraries/database/DatabaseQueries.php, site/phpstan-baseline.neon
Fixes some incorrect type hinting (namely missing the null type as a possible return) and adds types where possible for a handful of functions.
=> [Documentation:PHP] Improve internal type hinting for DB query functions

site/app/templates/forum/ForumBar.twig, site/app/templates/forum/ThreadPostForm.twig
Fixes #4929 
The button was moved from the create thread page to the more dropdown on the discussion forum page
=> [Refactor:Forum]Moved edit category button

sbin/submitty_autograding_shipper.py
Updates the ```get_job``` function to use a ```with``` statement for lock acquisition rather than the ```lock.acquire``` and ```lock.release``` functions. 
Previously, if acquiring a job failed with an exception, the lock would never be released, causing all of autograding to hang until restarted. The with statement will cause the lock to be released in such cases.
=> [Bugfix:Autograding] Properly Acquire Lock in Get Job

site/app/controllers/admin/ConfigurationController.php, site/app/models/Config.php, site/app/templates/admin/Configuration.twig, site/app/templates/submission/homework/SubmitBox.twig, site/config/course_template.json, site/tests/app/controllers/admin/ConfigurationControllerTester.php, site/tests/app/models/ConfigTester.php, tests/e2e/test_submission.py
Closes #4837 
*Keep Previous Files uploaded* option is now removed and the previous files are now kept in bucket by default.
=> [Feature:Submission] keep previous files uploaded

site/app/templates/GlobalHeader.twig
There was a \<script> tag between the \<head> and \<body> tags
This PR moves the script up a few lines such that it is inside the \<head>
closes #4998
=> [VPAT] Moved a line of JS from between head and body to inside head

site/app/controllers/GlobalController.php, site/app/libraries/Output.php, site/app/views/GlobalView.php, site/app/views/HomePageView.php
The home page does not have a unique page title
closes #4997
This pr makes it so that a page can set its page title without adding a breadcrumb and then I just set a page title for the homepage
=> [VPAT] Added unique page title to homepage

site/app/templates/admin/Configuration.twig, site/app/templates/admin/Extensions.twig, site/app/templates/admin/LateDays.twig, site/app/templates/admin/RainbowCustomization.twig, site/app/templates/course/SetFolderReleaseForm.twig, site/app/templates/course/UploadCourseMaterialsForm.twig, site/app/templates/forum/MergeThreadsForm.twig, site/app/templates/forum/ShowCategories.twig, site/app/templates/forum/ThreadPostForm.twig, site/app/templates/grading/VersionChoice.twig, site/app/templates/grading/electronic/Status.twig, site/app/templates/grading/electronic/SubmissionPanel.twig, site/public/js/forum.js
The forum as well as the website in general have a lot of input fields that do not have any labels.
Closes #5041
Using WAVE I fixed every "Missing form label" error on the forum.
I also went around the website and fixed a bunch more missing form label errors I found on other pages.
=> [VPAT] Added missing labels to html forms

site/app/views/grading/ElectronicGraderView.php
Adds discussion grading component for teams:
Non team assignments are unaffected:
closes #5003
=> [Feature:Forum] Add teams for grading discussion assignment

site/public/css/admin-gradeable.css, site/public/css/bootstrap.css, site/public/css/colors.css, site/public/css/forum.css, site/public/css/global.css, site/public/css/input.css, site/public/css/links.css, site/public/css/menu.css, site/public/css/server.css, site/public/css/sidebar.css, site/public/js/drag-and-drop.js
closes #4460
I added `color: var(--text-black);` to body in global.css
I also took a look at multiple css files and switched a lot of colors that were based on `--default-black` to use `--text-black` as well as the same for the white version. While both are black, by making the colors based on the css variable used for text, it should be easier for a user to just switch that one variable and switch the color of text on the website while not messing with other colors on the website.
=> [VPAT] Added default font color to html body

site/app/templates/GlobalHeader.twig, site/app/templates/admin/Configuration.twig, site/app/templates/admin/GradeOverride.twig, site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig, site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig, site/app/templates/admin/users/RotatingSectionsForm.twig, site/app/templates/course/CourseMaterials.twig
modified:   site/app/templates/GlobalHeader.twig
modified:   site/app/templates/admin/Configuration.twig
modified:   site/app/templates/admin/GradeOverride.twig
modified:   site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
modified:   site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
modified:   site/app/templates/admin/users/RotatingSectionsForm.twig
modified:   site/app/templates/course/CourseMaterials.twig
In regards to web accessibility (WCAG 4.1.1) — While examining Submitty via W3C's HTML validator, I got the ball rolling by making corrections on some of the simpler errors I saw.
I will open more issues in batches.
=> Some quick HTML 5 Corrections

site/app/templates/forum/ForumBar.twig, site/app/templates/forum/ThreadPostForm.twig, site/public/css/server.css, site/public/js/forum.js, tests/e2e/test_forum.py
#5069
#4491
closes #5069
This also fixes some of the items from #4491 
"Input descendants of label must have matching id to for"
"Detached labels"
"Input cannot be descendant of \<a>"
I fixed everything I know how to fix in #4491 so if somebody else know how to fix anything else there please let me know.
=> [VPAT:Forum] labels and input descendants

site/app/templates/CreateCourseForm.twig, site/app/templates/GlobalHeader.twig, site/app/templates/admin/RainbowCustomization.twig, site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig, site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig, site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig, site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig, site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig, site/app/templates/admin/admin_gradeable/rubric/CheckpointsRubric.twig, site/app/templates/admin/admin_gradeable/rubric/ElectronicFileRubric.twig, site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig, site/app/templates/admin/users/RotatingSectionsForm.twig, site/app/templates/course/CourseMaterials.twig, site/app/templates/course/UploadCourseMaterialsForm.twig, site/app/templates/forum/EditPostForm.twig, site/app/templates/forum/ForumBar.twig, site/app/templates/forum/ShowCategories.twig, site/app/templates/forum/ShowForumThreads.twig, site/app/templates/forum/ThreadPostForm.twig, site/app/templates/grading/UploadImagesForm.twig, site/app/templates/grading/electronic/SubmissionPanel.twig, site/app/templates/misc/Code.twig, site/app/templates/submission/homework/BulkUploadBox.twig, site/app/templates/submission/homework/BulkUploadProgressBox.twig, site/app/templates/submission/homework/CurrentVersionBox.twig, site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/admin/PlagiarismView.php, site/public/templates/grading/Gradeable.twig
script tags have  type="text/javascript" on them however this is not needed
closes #5088
I removed  type="text/javascript" from all script tags
=> [VPAT] Removed text/javascript from all script tags 

site/app/templates/HomePage.twig
`<h3>` elements are in `<ul>` elements on the homepage, which fails W3 validation.
Closes #5089 
`<h3>` elements are no longer in `<ul>` elements on the homepage, passing W3 validation.
No noticeable visual changes (that I can see)
=> [VPAT:System] homepage <h3> and <ul>

site/app/templates/GlobalHeader.twig, site/app/templates/Navigation.twig, site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig, site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig, site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig, site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig, site/app/templates/course/DeleteCourseMaterialForm.twig, site/app/templates/navigation/CloseSubmissionsWarning.twig, site/app/templates/navigation/DeleteGradeableForm.twig, site/public/css/admin-gradeable.css, site/public/css/server.css, site/public/js/admin-gradeable-updates.js, site/public/js/server.js, site/public/templates/grading/EditComponent.twig, site/public/templates/grading/Mark.twig, tests/e2e/test_grade_inquiry.py, tests/e2e/test_sidebar.py
Using https://validator.w3.org/nu/#file there were a number of issues with the gradables and gradable settings pages.
issues with http://localhost:1501/s20/sample
issues with http://localhost:1501/s20/sample/gradeable/future_no_tas_homework/update
closes #5090
I solved pretty much every error that website listed.
Any box with the checkbox enabled in the image above should be fixed. I left a few things because they were warnings I do not think need fixing, or to change them would require a larger redesign and unless they turn out to be a problem later should not be a big deal.
Assuming this gets approved, I will move on to doing the same thing for other pages on the website.
I also did not solve any wave issues in this pr. I have a few PRs open that solve some of the wave issues and it is …
=> [VPAT:InstructorUI] Fixed most w3 validator issues on gradeables pages

site/app/templates/GlobalHeader.twig, site/public/css/sidebar.css, site/public/js/server.js
The page does not load when javascript is disabled
The page works when javascript is disabled
=> [Bugfix:UI] Fixed page not loading when javascript is disabled

site/public/js/plagiarism.js
We can receive a JS error when creating the list for the right viewer.  
This error should no longer occur.
=> [BugFix: Plagiarism] Fix append error

site/app/templates/NotificationSettings.twig
There are a lot of w3 validator errors, you can view the errors by saving the html of a rendered page and uploading it here. https://validator.w3.org/#validate_by_upload
See #5086 for more details
I fixed most of the errors that were found by the w3 validator.
How I would test:
Check that the page looks and acts exactly the same. This pr should not change look or functionality, for users.
You can also check, using the validator, that most issues on the page were solved. Note that some issues I did not fix for various reasons, I would just ignore the issues that were not fixed for now.
=> [VPAT] w3 errors on notifications and notification settings pages

site/app/templates/admin/RainbowCustomization.twig, site/app/templates/admin/Report.twig
There are a lot of w3 validator errors, you can view the errors by saving the html of a rendered page and uploading it here. https://validator.w3.org/#validate_by_upload
See #5086 for more details
This PR also closes #5136
I fixed most of the errors that were found by the w3 validator.
How I would test:
Check that the page looks and acts exactly the same. This pr should not change look or functionality, for users.
You can also check, using the validator, that most issues on the page were solved. Note that some issues I did not fix for various reasons, I would just ignore the issues that were not fixed for now.
=> [VPAT] w3 and Wave on Grade Reports and Rainbow Grades pages

site/app/templates/LateDaysTablePlugin.twig, site/app/templates/admin/Extensions.twig, site/app/templates/admin/GradeOverride.twig, site/app/templates/admin/LateDays.twig, site/app/templates/admin/users/RotatingSectionsForm.twig
There are a lot of w3 validator errors, you can view the errors by saving the html of a rendered page and uploading it here. https://validator.w3.org/#validate_by_upload
See #5086 for more details
I fixed most of the errors that were found by the w3 validator. This pr is for the late days page, extensions page, grade override page and rotation sections page.
How I would test:
Check that the page looks and acts exactly the same. This pr should not change look or functionality, for users.
You can also check, using the validator, that most issues on the page were solved. Note that some issues I did not fix for various reasons, I would just ignore the issues that were not fixed for now.
=> [VPAT] Fixed w3 errors on instructor related pages

site/app/templates/admin/Configuration.twig, site/app/templates/admin/UploadWrapperForm.twig, site/public/css/server.css
There are a lot of w3 validator errors, you can view the errors by saving the html of a rendered page and uploading it here. https://validator.w3.org/#validate_by_upload
See #5086 for more details
I fixed most of the errors that were found by the w3 validator.
How I would test:
Check that the page looks and acts exactly the same. This pr should not change look or functionality, for users.
You can also check, using the validator, that most issues on the page were solved. Note that some issues I did not fix for various reasons, I would just ignore the issues that were not fixed for now.
=> [VPAT] w3 errors on course settings page

site/public/js/pdf/PDFAnnotateEmbedded.js, site/public/js/pdf/PDFInitToolbar.js
See detailed description in this [issue](https://github.com/Submitty/Submitty/issues/5122#issue-574416623)
Closes #5122 
Now in the student view of the PDF , cookie values are ignored and its just shows the plain PDF without any rotation and zoom.
=> [Bugfix: PDFAnnotator] TA grading impacts student view

site/app/templates/HomePage.twig, site/app/templates/NotificationSettings.twig, site/app/templates/course/EditCourseMaterialsForm.twig, site/app/templates/forum/ShowCategories.twig, site/app/templates/forum/SplitPostForm.twig, site/app/templates/grading/simple/Display.twig, site/app/templates/grading/simple/StatisticsForm.twig, site/app/templates/navigation/CloseSubmissionsWarning.twig, site/app/templates/submission/homework/AutogradingResultsBox.twig, site/app/templates/submission/homework/CurrentVersionBox.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/admin/PlagiarismView.php, site/public/css/homepage.css, site/public/js/drag-and-drop.js
We recently merged a number of fixes for the w3 validator. However having them split across so many branches caused me to miss a few issues. Also a few new issues were added since then.
https://validator.w3.org/nu/#file
I went around to all the pages and fixed the few minor w3 validator errors I found.
I know I was told to split up my prs by page or by error fixed but that would have required like 10 more prs with 1 change each so this one larger pr is imo the better solution.
This hope with this and the other few w3 validator related prs open is that once they are merged I can merge a e2e test that will check for w3 validator errors going forward and we wont have to keep going back and fix them as people will fix them before any pr is merged. I have this code done, it is just waiting for …
=> [VPAT] Fixed minor w3 validator errors across a number of pages

site/app/libraries/database/DatabaseQueries.php, site/app/models/OfficeHoursQueueModel.php, site/app/templates/officeHoursQueue/CurrentQueue.twig
There was no way to tell if a student has been helped in the last 5 days, just if they were helped today or not
Students who have not been helped in the past 5 days will get a full star. If they have been helped in the last 5 days but not today they get a half star. Otherwise they get no star
=> [Feature:InstructorUI] icons for first time in office hours queue today vs. this week

site/app/models/SimpleLateUser.php, site/app/templates/admin/Extensions.twig, site/app/templates/grading/electronic/StudentInformationPanel.twig, site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/views/NavigationView.php, site/app/views/submission/HomeworkView.php
Closes #5170
Displays system timezone on due dates
=> [Feature:Submission] Timezones added to due dates

site/app/templates/forum/CreatePost.twig, site/public/css/forum.css
Some markdown does not format correctly on the discussion forum.
Fixes #4135 
Relevant markdown features now format correctly (bullets, tables).
Tested by making posts with different content in the markdown fields.
=> [Bugfix:Forum] Improve forum markdown

site/app/templates/admin/users/GraderList.twig, site/app/templates/admin/users/StudentList.twig, site/app/templates/admin/users/UserForm.twig, site/public/css/directory.css, site/public/css/userform.css
This pr fixes all the w3 validator errors on the Manage Students and Manage Graders pages.
https://validator.w3.org/nu/#file
The w3 validator errors for theses pages should be fixed.
This hope with this and the other few w3 validator related prs open is that once they are merged I can merge a e2e test that will check for w3 validator errors going forward and we wont have to keep going back and fix them as people will fix them before any pr is merged. I have this code done, it is just waiting for the rest of the errors to be fixed in this and the last few other open prs.
=> [VPAT] Fixed w3 validator and WAVE errors on Manage Students and Manage Graders pages

site/app/controllers/MiscController.php, site/app/templates/autograding/TAResults.twig, site/app/views/AutoGradingView.php
See detailed description here #5073 
Closes #5073 
Unannotated view of pdf files are fixed.
=> [Bugfix: PDFAnnotator] Student View of Unannotated PDF 

site/app/controllers/admin/UsersController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
Closes #4988 
Currently, here is the bug that can be replicated if you follow the steps in this sequence:
1. new course, rotating sections not yet prepared.
2. instructor creates a gradeable X, sets grader assignment to "limited access graders" and "all access grading". (Now behind the scenes that's like checking all boxes for all graders for all rotating sections, however there are no rotating sections.)
3. Later instructor creates rotating sections. (However existing gradeables that are all access don't get these sections checked for the limited access graders.)
4. Limited access grader attempts to grade gradeable X, but fails for access.
5. Instructor toggles "all access grading" to anything and then back to "all access"
6. Limited access graders can now grade.
Now, there is no bug so …
=> [Bugfix:InstructorUI] Rotating Sections and All Access Grading

site/app/templates/forum/ThreadPostForm.twig
No change in behavior, just spacing. Just lifting a part of #4329 that was unrelated to the rest of the PR that can be immediately applied.
=> [Refactor:JS] Fix spacing on ThreadPostForm

site/composer.json
Allows one to type `compose run (test | lint | static-analysis)` to run the relevant stuff we have.
=> [Feature:System] Add run scripts to composer for common operations

.travis.yml
Adds PHP 7.4 to the test matrix. This is the version that will come with Ubuntu 20.04 LTS.
=> [Testing:Travis] Add PHP 7.4 to tested versions

.travis.yml
This reverts commit 81976821b22b83cc7145043bca0cf2e049f72baf.
=> Revert "[Testing:Travis] Add PHP 7.4 to tested versions (#5212)"

grading/main_configure.cpp, more_autograding_examples/notebook_itempool/config/config.json, more_autograding_examples/notebook_itempool_random/config/config.json
Partial progress towards #5283 specifically:
* Clean up JSON example
* Make the global item_pool distinct by changing the per-item item_pool to from_pool
* Get the build script to validate the configuration and pass it to PHP-land
=> Update item_pool Notebook Syntax and Config Parsing

site/app/controllers/admin/UsersController.php, site/app/models/User.php, site/app/templates/admin/users/ClassListForm.twig, site/app/templates/admin/users/GraderList.twig, site/app/templates/admin/users/GraderListForm.twig
Currently, It is required to fill at least 7 columns (pref first and last name being the optional) for each row when uploading the graders' list. 
Closes #4917 
Now You have the option to just specify the user_id in the file to let auto-population fill other details. 
When using auto-population, the 'limited access grader' privilege is given to the user by default.
=> [Feature: InstructorUI] Allow supplying only user_id for uploading user (grader / class) list

CONTRIBUTING.md
The CONTRIBUTING.md file was a bit out of date, referencing GSoC 2018. Changed the header here to not be year specific, as well as updated some of the words on the description. Also added a couple more links to the opening statement to some other helpful pages, not just the "How to Contribute" one.
=> [Documentation] Update CONTRIBUTING.md

site/app/templates/admin/users/UserForm.twig, site/public/js/userform.js
Bug in manage users page. 
Closes #5232 and adds an alert popup for data loss while editing any student or grader from the pencil icon next to his row ( extends #4996 )
This bug is a result of #4996
=> [Bugfix:InstructorUI] Edit user/student bug

.setup/bin/versions.sh
=> [Feature:InstructorUI] Lichen version v20.05.00

.setup/bin/versions.sh, AUTHORS.md
=> [Documentation] Update AUTHORS.md file

.setup/INSTALL_SUBMITTY_HELPER.sh
Two lines used tabs and spaces for indentation, causing them to not visually match their neighbor lines.
Fixes the lines to just use spaces and so that they visually match their neighbor lines.
=> [Refactor:System] Fix wrong indentation in install submitty helper

tests/e2e/test_office_hours_queue.py, tests/e2e/test_sidebar.py
the office hours queue test is sometimes failing for no reason
also the helper functions are not part of the class
All functions have been moved into the class
I also added a few `self.wait_for_element(...)` to different functions which I think might fix the test failing every now and then. I cannot recreate the failure on my local machine however, I restarted the e2e test a few times on Travis and every time it passed so hopefully this fixes it.
I also made it so that when this test fails, the test_sidebar.py tests should not fail as well which was a problem before
=> [Testing:InstructorUI] Improved office hour queue tests

site/app/templates/GlobalHeader.twig, site/app/templates/admin/Extensions.twig, site/app/templates/admin/GradeOverride.twig, site/app/views/admin/GradeOverrideView.php, site/public/css/exceptionforms.css, site/public/css/gradeOverride.css, site/public/css/table.css, site/public/js/server.js
- Fixes the layout of the input boxes for both desktop and mobile screen view.
- Hides empty table and shows a message for current status.
- Adds overall mobile compatible screen for the grade override.
=> [UI: InstructorUI] Mobile view for grade-override

site/app/templates/grading/electronic/Details.twig, site/app/views/grading/ElectronicGraderView.php, site/public/css/details-2.css, site/public/css/details.css, site/public/js/details.js
- Adds card-based student detail on small screen devices(table row on desktop)
- Adds Collapsible panel for quickly acessing students across different sections
- Changes in empty table
- Fixed the layout of top buttons(export/import team, randomly re-assign sections)
- Adds overall compatibility across different screen sizes.
=> [UI:InstructorUI] Add small screen view for the TA index page

autograder/autograder/execution_environments/container_network.py
In the event that a docker container could not be created for testcase n  (for example because the image for the container does not exist on the worker), successfully created containers for testcase n would persist for testcase > n, causing testcase failure if a name collision occurred. This PR handles this problem by cleaning up any successfully created containers for a testcase in the case in which a single container creation fails.
=> [Bugfix:Autograding] Handle errors on docker container creation

site/app/templates/CreateCourseForm.twig, site/app/templates/GlobalFooter.twig, site/public/css/server.css, tests/e2e/accessibility_baseline.json
The new course page has a number of w3 validator and WAVE errors.
http://localhost:1501/home/courses/new
All the W3 validator and WAVE errors have been fixed
=> [VPAT:InstructorUI] new course page

site/app/templates/admin/DeleteConfigPopup.twig, site/app/templates/admin/RenameConfigPopup.twig, site/app/templates/admin/UploadConfigForm.twig, site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig, site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig, site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig, site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig, site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig, site/app/templates/admin/admin_gradeable/rubric/ElectronicFileRubric.twig, site/app/templates/course/UploadCourseMaterialsForm.twig, site/app/templates/grading/UploadImagesForm.twig, site/app/templates/submission/homework/PreviousSubmissionForm.twig, site/app/templates/submission/homework/SubmitBox.twig, site/public/css/server.css, site/public/templates/grading/EditComponent.twig, site/public/templates/grading/EditComponentHeader.twig, site/public/templates/grading/Mark.twig, site/public/templates/grading/SavingTools.twig, tests/e2e/accessibility_baseline.json, tests/e2e/test_accessibility.py
The edit gradable pages have a number of w3 validator and wave errors. You can view them by clicking on the pencil icon next to any gradable as well as the new gradable button which has some overlapping code
All the errors have been fixed.
=> [VPAT] Fixed all WAVE and W3 validator errors on the edit gradeable pages 

site/app/libraries/database/DatabaseQueries.php
lint fix in site/app/libraries/database/DatabaseQueries.php
=> [Bugfix:PHP] short array syntax

site/app/libraries/database/AbstractDatabase.php, site/app/libraries/database/DatabaseQueries.php, site/phpstan-baseline.neon
There was a handful of ignored typing errors in two files of `app/libraries/database`.
The type errors are fixed, and the ignores are removed for those files.
=> [Refactor:PHP] Fix static analysis issues in app/libraries/database

site/app/libraries/Core.php, site/app/libraries/response/JsonResponse.php, site/app/libraries/response/RedirectResponse.php, site/app/libraries/response/WebResponse.php, site/app/libraries/routers/WebRouter.php, site/phpstan-baseline.neon
Number of static analysis errors in the response / router code.
Fixes the static analysis errors. No change in overall functionality.
=> [Refactor:PHP] Fix static analysis errors in router/responses

site/app/controllers/admin/EmailRoomSeatingController.php, site/app/libraries/Core.php, site/app/models/Config.php, site/phpstan-baseline.neon, site/tests/app/controllers/admin/EmailRoomSeatingControllerTester.php
The EmailRoomSeatingController does not have any tests.
Adds tests to the EmailRoomSeatingController.
=> [Testing:PHP] Add tests for EmailRoomSeatingController

tests/e2e/test_forum.py
Current forum test cases don't support testing announcing or resolving threads.
The _test_basic_operations_thread_ tests marking a thread as resolved and making a thread an announcement beside creating and deleting threads.
=> [Testing:Forum] Announce & Resolve thread

.travis.yml
We were adding source lines for trusty (14.04) on Travis-CI, while being on bionic.
The sourcelines are updated to be for bionic.
=> [Testing:Travis] Update apt sourcelines to use bionic

site/app/templates/grading/electronic/Status.twig, site/app/views/grading/ElectronicGraderView.php
Data shown about grading stats is wrong on preview grading page.
Correct data is displayed for Instructor/Ta view
=> [Bug Fix: Stats] Correct Stats on Grading Index

site/app/templates/grading/electronic/Status.twig, site/app/views/grading/ElectronicGraderView.php
=> Percentage fix GI - Update

site/app/templates/grading/electronic/Status.twig, site/app/views/grading/ElectronicGraderView.php
Updates Work of Previous PR on stats on Status Page
=> Updates Work of Previous PR on stats on Status Page

site/app/models/User.php, site/phpstan-baseline.neon
There's an ignored phpstan error in the User model
Fixes the error in the User model
=> [Refactor:PHP] Fix phpstan errors on User model

site/tests/app/models/NotificationTester.php, site/tests/app/models/PostTester.php, site/tests/app/models/SimpleGradeOverriddenUserTester.php, site/tests/app/models/SimpleLateUserTester.php, site/tests/app/models/forum/PostTester.php
Adds testcases for Post model, SimpleGradeoVerridenUser, and SimplelateUser model. Partially solves #5495 .
=> [Testing:PHP] Add testcases for some PHP classes

site/app/templates/grading/electronic/Details.twig, site/app/views/grading/ElectronicGraderView.php
Updates the Peer Grading index to show correct Manual Scores (TA grading and Peer Grading) 
[Completes a missed edge case of previous PR]
=> [BugFix: TaGrading] Update Grading Score for Peer View

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/Status.twig, site/app/views/grading/ElectronicGraderView.php
=> Percentage fix : Update on Previous Work

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/Status.twig, site/app/views/grading/ElectronicGraderView.php
=> Lint Fix on Previous PR

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/Status.twig, site/app/views/grading/ElectronicGraderView.php
=> Percentage Fix update

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/Details.twig, site/app/views/grading/ElectronicGraderView.php, site/public/css/server.css
=> Add Fix for StopLights for Peer View (#5577)

migration/migrator/migrations/course/20200529001923_cgi_tmp_folder.py, site/app/controllers/admin/UsersController.php, site/app/templates/admin/users/GraderListForm.twig, site/cgi-bin/xlsx_to_csv.cgi
At present, a failed CSV or XLSX upload to add new students or graders only specifies which row an error occurs on. This does not give a clear indication of what went wrong and leaves the user confused. 
Also, XLSX file upload is broken. 
Closes #3629 #5588 
Now an errored CSV/XLSX document gives a clear error message along with the formating suggestions for the columns in which errors occurred. This helps users to debug that error easily. Also, the XLSX file upload issue is fixed now.
=> [Feature: Instructor UI] XLSX/CSV Grader and Student Upload Need Better Error Messages

site/app/controllers/student/SubmissionController.php, site/app/templates/autograding/AutoChecks.twig, site/app/templates/grading/VersionChoice.twig, site/app/templates/submission/homework/CurrentVersionBox.twig, site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/templates/submission/homework/TAResultsBox.twig, site/public/css/diff-viewer.css, site/public/css/forum.css, site/public/css/global.css, site/public/css/grade-inquiry.css, site/public/css/server.css, site/public/css/submitbox.css, tests/e2e/test_submission.py
Makes the submission page mobile-compatible with all the subsections with single or multiple dropzones, TA results, version selections, submitted-files-info-section, and grade inquiry posts.
- ~working on screen where we have more than 1 dropzone~ 
- Notebooks works well but @shailpatels is looking into some design changes/refactor for notebooks.
=> [UI:Submission] Mobile view for submission page

migration/migrator/migrations/course/20200529001923_cgi_tmp_folder.py
final edits to migration weren't tested
=> [Bugfix:System] Fix broken migration from PR 5133

site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig, site/public/js/admin-gradeable-updates.js
Gradeables cannot be editted (changes will not be saved)
Gradeables can be editted and changes will be saved. Randomization has been temporarily disabled
=> [TAGrading:Bugfix] Edit Gradeables Fix

site/public/css/server.css
=> [Bugfix: Autograding] Side by side display autograding diff results

.setup/bin/setup_sample_user_data.py
The `.setup/bin/setup_sample_user_data.py` script fails if there is a non-zip file in the `sample_data/user_photos` directory (like the common `.DS_Store` file on macOS).
The script now does a simple check that while iterating through the directory that the entry is not a directory and that it ends with a `.zip` before attempting to unzip it. While I could have used `zipfile.BadZipFile` exception, I decided not to as that exception is thrown if it's not a zip as well as for corrupted zips and I did not want to filter on exception strings for when appropriate to raise or not. 
While working with this file, I did a series of other refactorings to make it more robust (imo):
1. Use [`tempfile.TemporaryDirectory`](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) to …
=> [Bugfix:Vagrant] Fix setup user photos breaking on non-zip file

site/app/templates/grading/electronic/SubmissionPanel.twig, site/public/js/ta-grading.js
A grader cannot properly load a file submitted by the student as part of the gradeable via the submission panel
The grader can load the file as normal
=> [TAGrading:Bugfix] Graders cannot load files

bin/grading_done.py
grading_done.py patch -- required_capabilities is optional
=> [Bugfix:System] grading_done.py patch -- required_capabilities is optional

grading/execute.cpp
=> [Feature:Autograding] whitelist awk

.flake8, bin/grading_done.py
=> [Refactor:Autograding] lint grading_done.py

.codecov.yml, migration/migrator/main.py, migration/tests/test_handle_migration.py
=> [Bugfix:System] migrator crash on missing course db

site/app/templates/grading/electronic/SubmissionPanel.twig, site/public/css/electronic.css, site/public/css/ta-grading.css, site/public/js/pdf/PDFAnnotateEmbedded.js, site/public/js/pdf/PDFInitToolbar.js, site/public/js/ta-grading-rubric.js, site/public/js/ta-grading-v2.js, site/public/js/ta-grading.js
Closes #5758 
The New Ta grading page now shows the submitted files without throwing any error. 
Also, there are some UI adjustments like 
-fixing overflowing pdfs out of the submission box
-to let instructors easily pick and switch between pdf-tools, toolbar and the current saved status of pdf is always shown at the top
=> [Bugfix:TAGrading] new interface - view submitted files

site/public/js/notebook_builder/form-options-widget.js
Notebook builder doesn't check for potentially invalid filenames before saving the configuration json.
A new validation step has been added to ensure filenames entered into the notebook builder filename inputs do not contain `..`, spaces, or forward slashes.
=> [Feature:InstructorUI] Notebook builder check for bad filenames

.setup/distro_setup/ubuntu/18.04/setup_distro.sh, .travis.yml
=> [Testing:Travis] Fix python docker sdk dependency version on travis

.setup/bin/versions.sh, site/app/libraries/CodeMirrorUtils.php, site/public/js/code-mirror-utils.js
increase the row height in pixels to look better on Mac
add "clike" into languages list
=> [Bugfix:Submission] Notebook code mirror styling tweaks

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/travis/autograder.sh, .travis.yml, grading/execute.cpp, grading/seccomp_functions.cpp, grading/system_call_categories.cpp, grading/system_call_check.cpp, tests/integrationTests/tests/json/assignment_config/config.json
* Add the unix script command to the safelist
* Also rename 'whitelist' to 'safelist'
=> [Refactor:Autograding] add script to safelist

site/app/templates/admin/users/MoreExtensions.twig, site/app/templates/admin/users/UserForm.twig, site/app/templates/forum/CategoriesForm.twig, site/app/templates/generic/Popup.twig, site/app/templates/grading/electronic/RandomizeButtonWarning.twig
The only way to close an open popup is to click the close button (or tab until you are focused on it and press enter)
partial work for #5775
pressing the escape key when a popup is open will now also close the popup
=> [VPAT:System] esc key to close popups

site/app/controllers/admin/AdminGradeableController.php
Creating a gradeable that does not have/use an autograding config throws a notebook php error 
Performs check if a gradeable has an autograding config first
=> [Bugfix:InstructorUI] create new gradeable error

site/app/controllers/student/GradeInquiryController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/generic/Popup.twig, site/public/js/grade-inquiry.js
When a student creates a new grade inquiry the page is not updated to show the new post
Manually refreshes both the student view and ta view when a new grade inquiry is made
Also begins work on setting up web socket support for creating a new inquiry,
finish dynamically updating will be done later
=> [Bugfix:Submission] page update on grade inquiry post

.setup/bin/versions.sh, .setup/install_system.sh, grading/dispatch.cpp, grading/seccomp_functions.cpp, grading/system_call_categories.cpp, grading/system_call_check.cpp, site/app/controllers/MiscController.php
Upgrade DrMemory from v2.0.1 to v2.3.0.
Required modifications to system call filtering to handle additional system call used in the new version of DrMemory.
bugfix install_system.sh so it is again re-runnable on an installed system.
Combining with PR #5883
=> [Feature:Autograding] DrMemory v2.3.0 and additional system call

grading/execute.cpp, grading/seccomp_functions.cpp
This PR adds gdb to the allowed programs list and removes trailing whitespace from touched files. A future PR will finish figuring out the full allowed system calls list for gdb.
=> [Feature:Autograding] Added gdb to allowed programs list

site/app/controllers/GlobalController.php, site/app/controllers/HomePageController.php, site/app/controllers/MiscController.php, site/app/controllers/admin/ReportController.php, site/app/controllers/grading/ElectronicGraderController.php, site/app/controllers/student/SubmissionController.php, site/app/libraries/Access.php, site/app/libraries/ErrorMessages.php, site/app/models/RainbowCustomization.php, site/app/models/gradeable/Gradeable.php, site/app/models/gradeable/GradedGradeable.php, site/app/models/gradeable/TaGradedGradeable.php, site/app/models/notebook/Notebook.php, site/app/models/notebook/UserSpecificNotebook.php, site/app/views/AutoGradingView.php, site/app/views/MiscView.php, site/app/views/course/CourseMaterialsView.php, site/app/views/forum/ForumThreadView.php, site/app/views/grading/ElectronicGraderView.php, site/app/views/submission/RainbowGradesView.php, site/composer.json, site/composer.lock, site/tests/app/controllers/DockerInterfaceControllerTester.php
Fixes php lint errors caused by upgrading phpcs and the errors that snuck into master when travis was down
=> [Testing:Developer] Fixes php lint errors

site/public/css/electronic.css, site/public/js/ta-grading-rubric.js, site/public/js/ta-grading-v2.js
* Panels saving not working with a 3 panel layout when switching
* Up and down arrow keys not working in grading rubric
* TA grading full screen animation happens when going to each student
Works on #5971 
* Fixed panels being changed when switching students (with a 3 panel layout)
* Fixed up and down arrow keys
* Removed overall comment code for selection with up and down arrow keys
* Removed TA grading full screen animation
* Panels:
* Tested each of the panel layouts with a non-default panel in each spot.
* Arrow keys:
* Tested going up and down with the arrow keys in the grading rubric
* Full Screen:
* Tested by going to different students to make sure full screen animation didn't show (and that it still fullscreens)
Will be adding in the functionally to target all overall comments …
=> [Bugfix:TAGrading] Fixed some bugs in TA grading

.setup/bin/versions.sh
Update version of rainbow grades to parse rotating section which is now included in generate grade summaries.
=> [Feature:RainbowGrades] support rotating sections

site/app/controllers/grading/ElectronicGraderController.php, site/app/models/gradeable/AutoGradedVersion.php, site/app/views/submission/HomeworkView.php
Several edge cases are generating frog robots due to nulls not properly being checked
null checks have been added, fixing the frog robots
=> [Bugfix:TAGrading] handle null autograding

.github/workflows/submitty_ci_3.yml
Creates a new workflow that performs a full vagrant up. Currently, it must be run manually
=> [Feature:Testing] Add vagrant up workflow

.github/workflows/submitty_ci_3.yml
=> [Bugfix:Testing] Full vagrant up workflow hotfix

.github/workflows/main.yml
PHP unit failing due to bad env setting
=> [Bugfix:Testing] Fix PHPUnit xdebug coverage setting

AUTHORS.md
Update authors.md list with Fall 2020 developers
=> [Documentation:Developer] update authors.md

.github/dependabot.yml
The commit message stuff added in #6102 was clobbered by #6113 which was necessary to move to using the integrated GH dependabot from the older separate dependabot app.
Re-introduces the commit stuff from #6102.
=> [Testing:System] Update dependabot commit messages

site/app/views/HomePageView.php
The code as is was causing a static analysis failure in #6128.
This simplifies the code to consolidates the three assignment statements into one, which then allows phpstan to make concrete decisions about the member keys of the `$ranks[$i]` array.
=> [Refactor:Submission] Fix static analysis for view

migration/migrator/migrations/course/20210122142747_remove_poll_point_system.py, site/app/controllers/admin/ConfigurationController.php, site/app/models/Config.php, site/app/models/PollModel.php, site/app/templates/admin/Configuration.twig, site/tests/app/controllers/admin/ConfigurationControllerTester.php, site/tests/app/models/ConfigTester.php
Currently, there are configuration options for point amounts for correct and incorrect answers.
Those configuration options are removed and tests and interfaces are updated to reflect that.
=> [Feature:InstructorUI] Remove Poll Points Feature

.setup/bin/versions.sh
Update rainbow grades to support polls.
NOTE:  The local directory structure for running rainbow grades for a specific course has changed slightly to place the student grading files in a subdirectory, copying more of the directory structure from the server.
=> [Feature:RainbowGrades] version update for Submini polls

site/app/controllers/grading/SimpleGraderController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/admin/users/StudentList.twig, site/app/templates/grading/simple/Display.twig, site/app/views/grading/SimpleGraderView.php
Subsections cannot be seen when grading students.
Make subsections available to use when grading students. The sorting order has been changed to sort by subsection and then by whatever order is selected by the user. This will change in the future to select sorting by subsection as an option.
=> [Feature:TAGrading] Subsection for Grading

.github/workflows/pr_title.yml, .github/workflows/pr_title_tester.py
modify PR title tester to support additional modules originally grouped under InstructorUI:
SubminiPolls, HelpQueue, CourseMaterials, Plagiarism
=> [Refactor:Developer] update pr title validator

site/public/js/ta-grading.js
3 panel display doesn't work properly.
3 panel display works properly.
Tested before and after changes.
=> [Bugfix:TAGrading] Fix 3-panel display

site/app/views/grading/ElectronicGraderView.php
After changing the version that is being viewed for a student, using the arrows to switch students results in a bugsplat.
Using the arrows to switch students after changing the version that is being viewed on the current student no longer results in an error.
=> [Bugfix:TAGrading] Fix TAGrading version select bug

autograder/autograder/autograding_utils.py, bin/regrade.py
An uninitialized variable caused regraded vcs/git submissions to not copy the files from the checkout folder.
=> [Bugfix:Autograding] regrading vcs/git submissions

site/app/controllers/student/GradeInquiryController.php
variables are getting set to null for somereason
Adds if statement and returns nothing if post or submitter id is null in the $_POST variable
=> [Bugfix:TAGrading] Add null check

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/PanelSelectorModal.twig, site/public/js/panel-selector-modal.js, site/public/js/ta-grading.js
TA grading can have up to 3 panels.
TA grading can now have four panels.
=> [Feature:TAGrading] TA grading four panel

.github/workflows/submitty_ci.yml
This PR runs the integration tests in github actions
=> [Testing:Developer] Run integration tests in gh actions

site/cypress.json
Spacing in `cypress.json` file is not consistent.
Makes the spacing consistent.
=> [Refactor:Developer] Fix spacing in cypress.json

autograder/autograder/autograding_utils.py
Gathers docker containers for a user in one step rather than 2, adds better error handling for container removal.
=> [Bugfix:Autograding] Simplify Docker Container Cleanup

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/distro_setup/ubuntu/20.04/setup_distro.sh, .setup/install_system.sh, Vagrantfile, site/public/index.php
We currently do not test against the latest LTS release of Ubuntu (20.04), and it is known that there are some issues with running the site under PHP 7.4 (the default version of PHP under 20.04).
This creates a vagrant image to be used to test Submitty against 20.04. As part of this work, I am also removing any "non-critical" packages from the installation (e.g. perl, ocaml, java) as we increasingly leverage docker to handle stuff that utilizes non-core packages.
=> [Testing:Developer] Add Ubuntu 20.04 vagrant image

site/.eslintignore, site/.eslintrc.json, site/public/js/pdf/PDFAnnotateEmbedded.js
This file was being ignored by eslint and had bunches of eslint errors.
Fixes all the eslint errors in the file, and unignores it.
=> [Refactor:TAGrading] Fix eslint errors in PDFAnnotateEmbedded

site/tests/app/libraries/response/MultiResponseTester.php
The `convertToJsonResponse` method has not tests.
Tests have been added for the `convertToJsonResponse`. The file and class have also been renamed to reflect its scope.
=> [Testing:System] Add tests for MultiResponse method

site/app/controllers/GlobalController.php, site/app/controllers/admin/SqlToolboxController.php, site/app/libraries/Core.php, site/app/libraries/database/AbstractDatabase.php, site/app/libraries/database/QueryIdentifier.php, site/app/templates/admin/SqlToolbox.twig, site/app/views/admin/SqlToolboxView.php, site/public/css/server.css, site/public/css/sql-toolbox.css, site/public/js/sql-toolbox.js, site/tests/BaseUnitTest.php, site/tests/app/controllers/admin/SqlToolboxControllerTester.php, site/tests/app/libraries/database/QueryIdentifierTester.php, tests/e2e/test_accessibility.py, tests/e2e/test_sidebar.py
Closes #6258
It has been requested that we add some mechanism for instructors to be allowed to run select queries against their database to fetch information that we otherwise do not expose.
This adds a new page that allows instructors to run select queries against their course DB. We do not surface the password information for users here so we don't run the risk of leaking that info here, but otherwise, all information about the course and its users is readily available via SQL queries.
Protection wise, we ensure that the following holds true:
* The query is a select query
* There is at most one `;` and that it is at the end of the query
* We start a transaction and rollback after executing the query
There may still be ways to break out and break the DB for a given course, but I am …
=> [Feature:InstructorUI] Add SQL toolbox page

site/public/js/sql-toolbox.js
Currently the SQL Toolbox only displays the SELECT query result without any row number.
Closes #6372 
A new column was created in SQL Toolbox which contains the row number for each line.
=> [Feature:InstructorUI] Row Numbers in SQL Toolbox

LICENSE.md
Wow! It's mid of 2021 already!
=> [Documentation:Developer] Update LICENSE copyright year

site/app/libraries/Logger.php, site/phpstan-baseline.neon
The Logger library class ignores a handful of phpstan errors
This fixes all phpstan errors in the Logger class.
=> [Refactor:Developer] Fix phpstan errors in Logger

site/app/libraries/SessionManager.php, site/phpstan-baseline.neon
SessionManager has a couple ignored phpstan errors.
This fixes the phpstan errors in SessionManager.
=> [Refactor:Developer] Fix phpstan errors in SessionManager

.github/workflows/submitty_ci.yml, .setup/testing/setup_test_suite.sh, tests/integrationTests/lib.py
Currently the integration testing driver executes every test module sequentially, spending ~30mins on each run 
This pr implement parallel testing for integration testing, it is a apart of effort for #6390.
This reduces time for each execution down to ~15mins, a 2x speed up.
This patch enables integration test to be run parallelly on a test module level.
This patch has no impact on client code.
I've also cleaned up the script a bit as well, concurrency notes are put in for future maintainers where appropriate.
=> [Testing:Developer] Parallelize integration test suite

site/app/libraries/Output.php, site/phpstan-baseline.neon, site/tests/utils/NullOutput.php
The Output class has a handful of phpstan errors that were ignored.
This fixes the ignored phpstan errors.
=> [Refactor:Developer] Fix phpstan errors in Output

site/app/libraries/Core.php, site/phpstan-baseline.neon
The Core php library had a handful of phpstan errors.
This fixes all phpstan errors in Core.
=> [Refactor:Developer] Fix phpstan errors in Core

site/app/templates/admin/SqlToolbox.twig, site/public/js/sql-toolbox.js, site/public/mjs/sql-toolbox.js, site/tests/mjs/sql-toolbox.spec.js
Currently you can only view the data returned by the query. It can be difficult to extract this data to a different program.
Closes #6374 
There is now a Download CSV button which will download a CSV file of the data just ran by the query.
=> [Feature:InstructorUI] CSV Export of SQL Toolbox Data

site/app/controllers/admin/LateController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/admin/LateDays.twig
=> [Bugfix:InstructorUI] Revert 6426 late days add/overwrite

site/app/templates/admin/users/RotatingSectionsForm.twig
The typo in the first paragraph in the page is fixed. :)
=> [Bugfix:InstructorUI] Fix typo in Manage Sections Page

site/app/controllers/admin/PlagiarismController.php, site/app/templates/plagiarism/PlagiarismResult.twig, site/public/css/plagiarism.css, site/public/js/plagiarism.js
There are currently a number of issues with the plagiarism results page.  
This PR:
- fixes a parsing issue which caused an invalid state to occur when large percentage matches are present
- refactors the PHP and JS some to reduce code duplication and improve maintainability
- cleans up the UI
- loads the top match automatically instead of waiting for the instructor to select a student
Note: this is further work on a work-in-progress and is not final.  Known issues/future work is listed below.  
Known issues:
- match % doesn't display for user 2
- this is a nontrivial issue which will be fixed in a future PR
- clicking on highlighted text does not produce a dropdown as expected (currently no response)
- code is highly inefficient/takes a long time to load even small documents
=> [Refactor:Plagiarism] Plagiarism bug fixes and UI changes

site/app/controllers/admin/PlagiarismController.php, site/package-lock.json, site/package.json
Currently an error may occur in some cases when you try to save edits to a gradeable from the plagiarism detection homepage:
This PR fixes the bug by adding additional checks.
=> [Bugfix:Plagiarism] Fix plagiarism config edit bug

site/app/controllers/admin/PlagiarismController.php
It is currently possible to input invalid values for some fields when creating and editing a gradeable.  (for example: inputting -1 into the sequence length field)
Fixes a few bugs which could lead to an invalid plagiarism configuration
Fixes #6506
=> [Bugfix:Plagiarism] Plagiarism configuration error checking

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20210520121528_add_gradeable_time_data.py, site/app/controllers/student/SubmissionController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/gradeable/Gradeable.php, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/submission/HomeworkView.php, site/public/css/global.css, site/public/css/submitbox.css, site/public/js/submission-page.js, site/tests/app/controllers/student/SubmissionControllerTester.php, site/tests/app/models/gradeable/GradeableListTester.php
Currently gradeables will only show the due date. Additionally if a student is taking a timed gradeable, they must time themselves.
Closes #1865 
The gradeable page now has a timer built on page. There is a timer for a count down until the normal gradeable due date if it has a due date. If the gradeable has a timer autograder configuration, a timer will appear counting down until you should submit your gradeable.
This is still a WIP but reviews could be helpful
There will be a separate PR to move autograder config.json data for timer into DB
=> [Feature:Submission] Gradeable Timer

site/public/css/colors.css, site/public/css/notebook-builder.css, site/public/js/notebook_builder/widgets/markdown-widget.js, site/public/js/notebook_builder/widgets/short-answer-widget.js, site/public/js/notebook_builder/widgets/widget.js
* Labels are missing on short answer inputs
* Contrast is very low on itempool and form settings containers
* Short answer inputs don't change text theme to match site theme
* Hidden labels have been added to all short answer inputs
* Itempool and form settings containers have had their colors adjusted
* Short answer inputs use eclipse in light mode and monokai in dark/black mode
=> [VPAT:InstructorUI] Improve Notebook Builder Accessibility

.flake8, sbin/run_lichen_plagiarism.py
`sbin/run_lichen_plagiarism.py` is currently excluded from the Python linting.
This PR brings `sbin/run_lichen_plagiarism.py` into line with the requirements for the Python linter and removes it from the exclusion list.
=> [Refactor:System] Refactor run_lichen_plagiarism.py

sbin/run_lichen_plagiarism.py, sbin/submitty_daemon_jobs/submitty_jobs/jobs.py, site/app/controllers/admin/PlagiarismController.php, site/app/views/admin/PlagiarismView.php
PR #28 in the Lichen repository changes the location of the overall ranking file.  This is a followup PR in the Submitty repository to fix all of the changed paths.
=> [Bugfix:Plagiarism] Modify paths for Lichen ranking files

Vagrantfile
Ubuntu 18.04 is our primary development target.
Makes Ubuntu 20.04 our primary development target, which is what RPI is going to be moving towards presently. This will help test out any issues in the move to 20.04 before it gets deployed into production.
=> [Feature:Developer] Make ubuntu 20.04 our development target

site/app/controllers/admin/PlagiarismController.php, site/app/templates/plagiarism/Plagiarism.twig, site/public/css/plagiarism.css
It is not currently possible to view the run log from the plagiarism UI.  This means that instructors are unable to check how far the algorithm has made it when running on large groups of assignments and are unable to report any errors that may occur.
This PR adds a button which lets instructors view the run log.
Before:
After:
=> [Feature:Plagiarism] Add ability to view run log to UI

.setup/bin/versions.sh
This update parses and grades Submini polls where students are allowed to select multiple responses on polls.
=> [Dependency] Update RainbowGrades to v21.06.01

.setup/bin/versions.sh
refactor regex for student files
=> [Dependency] update Lichen version v21.06.01

site/tests/app/models/PollModelTester.php
There are no tests implemented for the PollModel.php file
Added a test file that tests each function in the poll model using three different poll examples.
Tested and debugged.
=> [Testing:SubminiPolls] Add unit test for poll model

site/app/views/submission/HomeworkView.php
closes #6195
limited access graders can now use the beta submit button to test submissions for future gradeables.
To test:
login as "grader" and use the beta submit button for a future gradeable.
=> [Bugfix:TAGrading] Beta gradeable permissions

site/app/templates/EmailStatusPage.twig, site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig, site/app/templates/admin/users/RotatingSectionsForm.twig
If you edit a gradeable in a course with no full access or limited access graders, the page will not load. The sections page does not load at all. The email status page also does not load.
There is now a check to see if the proper key exists in the array in the twig file now. There are also key checks for the sections page and email status page.
=> [Bugfix:InstructorUI] Fix Various Twig Files

.github/workflows/submitty_ci.yml, site/cypress/integration/courseMaterials.spec.js, site/cypress/support/index.js, site/package-lock.json, site/package.json
Currently the last test in course materials is flaky and attempts to fix it have not worked
The test will be skipped on CI but can be run locally 
The diff looks like a lot of changes because the test was wrapped in an if statement
=> [Testing:CourseMaterials] Skip flaky test on CI

migration/migrator/data/submitty_db.sql, migration/migrator/migrations/master/20210714135438_add_course_groups.py, sbin/create_course.sh, sbin/submitty_daemon_jobs/submitty_jobs/jobs.py, site/app/controllers/HomePageController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/CreateCourseForm.twig, site/cgi-bin/group_check.cgi
Right now when creating a new course through the website, you must pick a course to base from. This simply finds a group to give the new course.
Rather than ask for a course, the site just asks for the group directly which comes from a new table. This new table will also be used in plagiarism.
=> [Refactor:System] Stores Groups in Master DB

site/app/controllers/MiscController.php
Opening up a PDF in full panel (with annotation tools) does not work.
Opening up a PDF in full panel now works.
=> [Bugfix:TAGrading] Fix PDF annotation opening

site/cypress/integration/late_days_allowed.spec.js
There are currently no tests for the late days allowed page
This PR adds a few end-to-end tests to the late days allowed page to ensure that the basic functionality still works.  The test add, modify, and delete late days for a user.
=> [Testing:InstructorUI] Add tests for late days allowed

site/app/templates/admin/users/GraderList.twig, site/app/templates/admin/users/RegistrationSectionsForm.twig
There is a twig error when loading the graders page on a brand new course.
Variable is checked to exist before it's value is used and the page loads properly now.
=> [Bugfix:InstructorUI] Fix Graders Page Twig

site/app/templates/autograding/PeerResults.twig, site/app/templates/submission/homework/NoSubmissionBox.twig, site/app/views/submission/HomeworkView.php
closes #6842 
closes #6841 
pages load properly 
1 Log in as instructor
2 In the sample course on the gradeables page, click submit for "Grading Homework Team PDF" (or any other team gradeable)
3 See error/fix
4 Log in as bitdiddle (or any other user that has a grade available)
5 Go to the sample course, and then to the gradeables page
6 Click "VIEW GRADE" for "Released Peer PDF Homework"
7 See error/fix
=> [Bugfix:Submission] Various twig fixes

.setup/INSTALL_SUBMITTY_HELPER_BIN.sh
#6631 added set_allowed_minutes.py which needs to be run every time.
The permissions are set up in the install script.
=> [Bugfix:System] Set permission on set_allowed_minutes.py

site/app/controllers/pdf/PDFController.php, site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig, site/app/views/PDFView.php
Graders cannot download the annotated pdf of a student they are grading
Graders can download the annotated pdf on the annotation page
=> [Feature:TAGrading] Let Grader Download Annotated PDF

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/Details.twig
closes #6835 
All grading statistics are displayed correctly
To Test:
1. Make sure the maximum value on the histogram is always the real maximum overall score
2. make sure the "grade" buttons on the index page always display the correct score (if their is one)
=> [Bugfix:TAGrading] Fix incorrect grading statistics

migration/migrator/migrations/course/20210723135404_course_materials_link_to_db.py
revisions to the migration originally added in #6599
=> [Bugfix:CourseMaterials] catch migration directory exception

site/app/models/gradeable/GradedGradeable.php, site/app/templates/grading/electronic/Details.twig, site/app/views/grading/ElectronicGraderView.php
If you try to peer grade you will get Twig errors due to undefined functions.
The Twig errors are gone and the total score column is removed as that is not necessary.
=> [Bugfix:TAGrading] Peer Grading Twig Errors

site/cypress/integration/courseMaterials.spec.js
Revert "[Testing:CourseMaterials] Skip other flaky course materials test (#6870)"
This reverts commit 00b1ec5aa74012c80f2d682c174d5fae6e158d31.
=> Revert "[Testing:CourseMaterials] Skip other flaky course materials test (#6870)"

site/app/controllers/HomePageController.php, site/app/libraries/database/DatabaseQueries.php
If you go to the course creation page, you will only see current non-archived courses in your prior course codes.
All courses that you are in will be shown whether it is archived or not.
I made an archived course and saw it disappear from the page. After the fix it is showing correctly.
=> [Bugfix:System] Include Archived Courses in Course Codes

.setup/bin/versions.sh
https://github.com/Submitty/Lichen/releases/tag/v21.08.01
=> [Dependency] update Lichen v21.08.01

site/app/models/gradeable/Component.php, site/app/models/gradeable/Gradeable.php
Fixes a couple undefined indexes, that appear immediately after creating new gradeable.
=> [Bugfix:InstructorUI] undefined index errors on new gradeable

site/app/controllers/admin/AdminGradeableController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/gradeable/Gradeable.php, site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig, site/public/js/admin-gradeable-updates.js
In some cases when changing dates, the backend may try to save dates as null which is not allowed.
This will make sure no dates are null and also makes sure that the correct information is sent to the backend. When you turn on/off gradeable due date the submission due date field may not get sent which is now fixed.
=> [Bugfix:InstructorUI] Fix Null Date Issue

site/app/templates/LateDaysTablePlugin.twig
#7093 
UI loads correctly
Tested locally
=> [Bugfix:Submission] Fix late day loss UI

site/app/controllers/student/GradeInquiryController.php
Fixes #7290
Graders do not get any notifications for grade inquiry.
Graders should get notifications for grade inquiry now
=> [Bugfix:Notifications] Removed random array reset

sbin/create_term.sh
-------
At the moment the `create_term.sh` script tries to use the dates as required in the input of the script.
However, the script doesn't consider the datestyle setting the database may had.
Behaviour is the same, however now it's more specific as it converts the input date specifying the format.
It also avoids problems when systems may have a DD/MM/YYYY configuration and accepts it by mistake for some input dates.
This won't change any current usage to the people that uses this script unchanged. And it will also work for people with other locales (I'm not sure how postgresql sets that default, but I'm in Europe and MM/DD/YYYY is not the default).
This was tested as now it works on my system:
```bash
/usr/local/submitty/sbin/create_term.sh 05 fake22 06/21/2022 08/21/2022
```
```
ERROR: …
```
=> [Bugfix:System] Specify date format when creating terms

.github/workflows/submitty_ci.yml, site/.build.js, site/package-lock.json, site/package.json, site/ts/submission.ts, site/ts/utils/server.ts, site/tsconfig.json
Enabled strict checking for Typescript (and updated existing files to meet checking)
Allow use of variables/functions from other Javascript functions in Typescript functions
Added Twig type library
Fix .build.js not going into directories
=> [Refactor:Developer] Typescript config updates

site/public/css/polls.css
=> [Bugfix:SubminiPolls] Poll option color contrast

.setup/bin/versions.sh
=> [Dependency] update_lichen v22.02.00

site/ts/instructor-submission.ts
Using the `Make Submission for a Student` or `Bulk PDF Upload` buttons do not work and throw an error.
Fixes submit as student/bulk upload buttons; issue was caused when `submitty_ocr` feature flag is disabled.
Can test by disabling debug mode and the `submitty_ocr` feature flag (for debug, edit `config/database.json` at `/usr/local/submitty/config/database.json` and set `debugging_enabled` to false); make sure that the elements with ids `toggle-id-scan`/`use-ocr` do not exist on the submission page.
=> [Bugfix:Submission] Fix submit as student/bulk upload button

site/app/controllers/GlobalController.php, site/app/controllers/admin/PlagiarismController.php, site/app/templates/plagiarism/Plagiarism.twig, tests/e2e/test_sidebar.py
As per a discussion with @bmcutler a few weeks ago, Lichen/plagiarism is ready to be released to all instructors.
This PR removes the plagiarism feature flag.
=> [Feature:Plagiarism] Remove plagiarism feature flag

site/public/js/server.js
Closes #7796
Redirects to the home page
=> [Bugfix:TAGrading] Fix broken Home link in TA grading

.setup/install_submitty/install_site.sh, .setup/nginx/submitty.conf, site/app/libraries/socket/Client.php, site/socket/index.php
The PHP websocket server runs on a local port which is then proxied via NGINX.
The PHP websocket server now runs on a unix socket which gets proxied via NGINX.
Documentation PR: https://github.com/Submitty/submitty.github.io/pull/424
=> [SYSADMIN ACTION][SECURITY][Bugfix:System] Use UNIX Socket for Websockets

README_utm_arm.txt
=> [Feature:System] UTM ARM instructions update

site/cypress/integration/auth_token.spec.js
A Cypress test introduced in #7721 is currently failing on master.
This PR fixes the Cypress test so that it passes.
=> [Testing:Submission] Fix Cypress Test - Auth Tokens

site/app/templates/grading/electronic/NavigationBar.twig
Fixes #7280 
Buttons entirely clickable
=> [Bugfix:TAGrading] Nav buttons not entirely clickable

site/app/templates/AuthTokens.twig, site/app/templates/submission/Team.twig, site/app/templates/submission/homework/SubmitBox.twig, site/cypress/integration/auth_token.spec.js
"git auth token" -> "Authentication Token"
=> [Feature:Submission] Authentication Tokens text tweak

site/room_templates/Amos_Eaton/215.twig, site/room_templates/Amos_Eaton/216.twig
Update AE 215 and AE 216 assigned exam seating.
=> [Feature:InstructorUI] update AE 215 & 216 seating charts

site/app/controllers/admin/AdminGradeableController.php, site/app/models/gradeable/Gradeable.php, site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
Fixes #7731 
When a csv file with grader assigned to themselves is uploaded it is accepted from the backend.
And the observed bugs in the [issue comment](https://github.com/Submitty/Submitty/issues/7731#issuecomment-1142517610)
- When a csv file with self assigned graders are uploaded. The error message "Please note that student is not able to grade themselves" is given.
- Autocompleting input field is fixed to work as expected.
- Error message when a same user is chosen
- Error message when csv file with self graders uploaded
=> [Bugfix:InstructorUI] Peer graders grading themselves

README_utm_arm.txt
add note to checkout AnalysisToolsTS repo
=> [Bugfix:Developer] update README for utm/arm

.github/workflows/submitty_ci.yml, .setup/CONFIGURE_SUBMITTY.py, .setup/INSTALL_SUBMITTY_HELPER.sh, .setup/install_system.sh, .setup/testing/setup.sh, migration/migrator/migrations/course/20220531202108_grant_course_postgres_user.py, migration/migrator/migrations/master/20220531200652_add_course_postgres_user.py, sbin/create_course.sh, site/app/models/Config.php, site/tests/app/controllers/admin/ConfigurationControllerTester.php, site/tests/app/models/ConfigTester.php
Submitty has a single database user which is a postgres superuser. This is used for all queries on the site but it gives too much permission for features such as SQL toolbox.
A new postgres user was added that is strictly for courses and is limited to basic SQL commands on the public schema of each course database.
Sysadmin action documentation not complete yet. Will update PR once complete.
=> [SYSADMIN ACTION][SECURITY][Bugfix:System] Add Course User for Postgres

site/app/controllers/forum/ForumController.php
After https://github.com/Submitty/Submitty/pull/8032 the ability to edit posts was broken.
The functionality has been fixed and users can now edit their posts.
=> [Bugfix:Forum] Fix Editing Post

site/app/templates/forum/ThreadPostForm.twig, site/public/css/forum.css
The layout of the settings panel in the New thread  was irregular and confusing.
The new and improved layout has been added.
Solves #8098
=> [Bugfix:Forum] Fixed Settings layout in New thread 

site/.eslintignore, site/public/js/forum.js, site/public/js/latedays.js, site/public/js/rainbow-customization.js, site/public/js/system-update.js, site/public/js/user-profile.js
Many of Submitty's Javascript files are not checked by  `eslint`.  
This PR is the first of several upcoming PRs which improves our JS code style enforcement by removing files from the `eslint` ignored files list.  All of the changes in this PR are "safe" changes which should not affect functionality in any way.  Errors which could not be resolved automatically were ignored on a line-by-line basis.
The files which have been removed from the ignored list include:
`forum.js`
`latedays.js`
`rainbow-customization.js`
`system-update.js`
`user-profile.js`
Future PRs will be created to lint the notebook builder and TA grading JS files.
This is a very large PR which makes minor modifications to many common JS files.  Merge conflicts are likely, but should be easily resolved.  The best way to …
=> [Refactor:Developer] Fix code style for JS files

site/.eslintrc.json, site/cypress/integration/courseMaterials.spec.js, site/cypress/support/commands.js, site/cypress/support/utils.js, site/public/js/admin-team-form.js, site/public/js/calendar.js, site/public/js/confetti.js, site/public/js/docker_interface.js, site/public/js/email-status.js, site/public/js/extensions.js, site/public/js/forum.js, site/public/js/grade-inquiry.js, site/public/js/gradeable-notebook.js, site/public/js/latedays.js, site/public/js/rainbow-customization.js, site/public/js/stat-page.js, site/public/js/system-update.js, site/ts/activity-dashboard.js, site/ts/grade-report.js, site/ts/grader-submission.ts, site/ts/sql-toolbox.js, site/ts/twig/grading/electronic/StudentInformationPanel.ts, site/ts/utils/server.ts
The `space-before-blocks` `eslint` rule is not currently enabled.  We require a space before and after keywords via the `keyword-spacing` rule, but don't require that a space be placed before the opening curly brace of a block of code.
This PR adds the [`space-before-blocks`](https://eslint.org/docs/latest/rules/space-before-blocks) rule to our `eslint` configuration and updates the code to reflect these style requirements.
A documentation PR to update [this page](https://submitty.org/developer/software_and_system_design/coding_style_guide/javascript) will be forthcoming.
=> [Testing:Developer] Add space-before-blocks eslint rule

site/app/controllers/UserProfileController.php, site/app/models/DisplayImage.php, site/app/models/User.php
Any user can upload virtually unlimited profile photos.
In order to prevent resource abuse, a cap has been imposed on the number of profile photos a user can upload.
=> [SECURITY][Feature:Submission] Cap on number of profile photos

.setup/data/courses/development.yml, more_autograding_examples/c_malloc_not_allowed/config/config.json, more_autograding_examples/c_malloc_not_allowed/submissions/calloc.c, more_autograding_examples/c_malloc_not_allowed/submissions/compile_err.c, more_autograding_examples/c_malloc_not_allowed/submissions/malloc.c, more_autograding_examples/c_malloc_not_allowed/submissions/sqbrackets.c, tests/integrationTests/tests/c_malloc_not_allowed/__init__.py, tests/integrationTests/tests/c_malloc_not_allowed/validation/grade.calloc.txt, tests/integrationTests/tests/c_malloc_not_allowed/validation/grade.compile_err.txt, tests/integrationTests/tests/c_malloc_not_allowed/validation/grade.malloc.txt, tests/integrationTests/tests/c_malloc_not_allowed/validation/grade.sqbrackets.txt, tests/integrationTests/tests/c_malloc_not_allowed/validation/results.calloc.json, tests/integrationTests/tests/c_malloc_not_allowed/validation/results.compile_err.json, tests/integrationTests/tests/c_malloc_not_allowed/validation/results.malloc.json, tests/integrationTests/tests/c_malloc_not_allowed/validation/results.sqbrackets.json
No autograding examples with negative point test cases.
Closes https://github.com/Submitty/Submitty/issues/1324
Added `c_malloc_not_allowed` in `more_autograding_examples` which has three test cases with significant negative points that could cancel out the positive scores.
=> [Documentation:Autograding] Negative Points Example

site/app/controllers/OfficeHoursQueueController.php, site/app/templates/officeHoursQueue/QueueStatus.twig
A student can remove another student from an office hours queue and then that student can be present in two queues at the same time.
The issue has been fixed.
=> [SECURITY][Bugfix:HelpQueue] Switching between queues

bin/grading_done.py, bin/set_allowed_mins.py, sbin/submitty_daemon_jobs/submitty_jobs/submitty_ocr.py
A recent update to our Python linter, `flake8`, seems to have caused many of the recent CI jobs to fail.
Fixes the linting errors.
=> [Testing:Developer] Fix Python linting errors

autograder/autograder/autograding_utils.py, autograder/autograder/execution_environments/container_network.py, autograder/autograder/execution_environments/secure_execution_environment.py, autograder/autograder/testcase.py
The information in `container_log.txt` is confusing and not formatted very nicely.
The file was made to look neater and shows the time taken for container events.
=> [Feature:Autograding] Improvements to container_log.txt

sbin/saml_utils.php
Every time users are added with the saml_utils script it always tries to add all users. That means it also prints out that all users who are finally in the table were added when usually less were added.
Now only new users get added and counted in the final print. When validating there is a message that will print out if no errors were found.
=> [Feature:System] Provide more details in SAML script

site/app/templates/officeHoursQueue/QueueStatus.twig
The HTML in one of the twig files in invalid.
The HTML issue is fixed by handling a pair of div tags.
=> [Bugfix:HelpQueue] Fix for invalid HTML (div tags)

site/app/templates/officeHoursQueue/QueueHeader.twig
Text color is different in dark mode. 
Since the objective is to make text color same. Now, office hour text has same color in dark mode.
=> [UI/UX:HelpQueue] Office hour staff text color

.setup/distro_setup/ubuntu/20.04/setup_distro.sh, README_utm_arm.txt
I updated the README to clarify some of the steps for M1 Mac users.
=> [Documentation:Developer] Update UTM ARM instructions

site/app/templates/submission/homework/SubmitBox.twig, site/ts/grader-submission.ts
Closes #8338 
Currently there are submission mode and bulk upload processing progress box on notebook (and other non-bulk) gradeables for full access graders, which is unnecessary.
Remove the processing progress box on notebook (and other non-bulk) gradeables, and the submit for student option works for notebook now.
=> [Bugfix:Submission] Notebook unnecessary UI elements

site/app/controllers/pdf/PDFController.php, site/public/js/pdf/PDFInitToolbar.js
=> [SECURITY][Bugfix:TAGrading] pdf annotation

site/app/templates/officeHoursQueue/QueueHeader.twig, site/public/css/colors.css, site/public/css/officeHoursQueue.css
Text color is not the same in light mode as it is in dark mode.
Updated to have the same color text.
Used the CSS Inherit Keyword to inherit color from the parent.
=> [UI/UX:HelpQueue] Updated office hour queue button color

migration/migrator/data/course_tables.sql
Adds the new index on gradeable_component_data into course_tables.sql from PR #8550
=> [Refactor:System] Update course table setup 

site/app/libraries/database/DatabaseQueries.php
In many places in Submitty, there are n-length queries for allowed minutes override. These are unnecessary and cause slow downs.
These n-length queries have been reduced to a single query.
I tested that the gradeable timer updates properly and it does.
=> [Refactor:Submission] Allowed Minutes Override Refactor

Vagrantfile
increase vagrant boot timeout to 10 minutes
=> [Bugfix:Developer] increase vagrant boot timeout

site/app/controllers/MiscController.php, site/app/controllers/course/CourseMaterialsController.php, site/app/libraries/Access.php, site/tests/app/libraries/AccessTester.php
A bug exists where resolveDirPath can return and cause users to see files they shouldn't.
This bug is fixed and users can only access files they should be able to.
=> [SECURITY][Bugfix:System] Fix directory bug in resolveDirPath

README_utm_arm.txt
Update the shared directory mount instructions for UTM
=> [Bugfix:Developer] ARM/UTM mount shared directory 

AUTHORS.md, LICENSE.md
=> [Documentation:Developer] Update license year & authors

AUTHORS.md
=> [Documentation:Developer] Update authors

.setup/bin/versions.sh
update to RainbowGrades v23.02.00
=> [Dependency] RainbowGrades v23.02.00

.github/workflows/dependabot_title_fix.yml
This Action runs on every PR even if it's not by Dependabot, wasting time and compute power.
It checks if Dependabot is the actor and skips the check if it's not.
=> [Feature:Developer] Add filter to `dependabot_title_fix`

.setup/bin/versions.sh, .setup/install_system.sh, .setup/submitty_crontab
also closes #8778
replaced by documentation of manual logging configuration:
https://submitty.org/sysadmin/installation/system_customization#preferred-name-change-logging
=> [Dependency] SysadminTools v23.02.00

.setup/install_system.sh
Updated documentation on Submitty.org in order to include this final install message.
There were many 'Done exit 0' throughout the installation. It was confusing whether it had really ended or not.
Added a large success message so users installing submitty for the first time would be sure that the installation had completed.
Tested while remaking my VM in order to test Mac using QEMU for #8874.
=> [Documentation:System] Added a Installation Success message

site/app/libraries/database/DatabaseQueries.php
PHP error thrown when seeking team and there is no seek message in the database.
Resolves #8911 
Seek message query method returns null as expected when no message found in the database.
=> [Bugfix:Submission] PHP Error when seeking team

CONTRIBUTING.md, README.md, SUPPORT.md
update links to submitty.org for contributing, readme, and support
=> [Documentation:Developer] update contributing readme & support

site/app/templates/Navigation.twig
=> [Bugfix:InstructorUI] locked gradeable override message

site/app/templates/submission/homework/SubmitBox.twig
Fixes #9117 
The console will throw a jquery selector exception, when submitting in a gradeable.
No longer throws the exception in the console
=> [Bugfix:Submission] Removes jquery exception in gradeables

site/app/templates/admin/RainbowCustomization.twig, site/app/templates/admin/Report.twig
Just a simple modification requested 
No
Tested Locally
=> [UI/UX:InstructorUI] Remove Work in Progress

site/app/templates/EditPronounsForm.twig, site/app/templates/UserProfile.twig, site/app/templates/grading/Images.twig
Fixes #9182 
User-specified pronouns added to the "Student Photos" page.
=> [Feature:TAGrading] Add pronoun student photos page

site/app/views/MiscView.php
There is no convenient method to search for text in a single file when grading submissions.
Resolves #9211
CodeMirror search has been added to search for a given string or pattern in a file.
=> [Feature:TAGrading] Search in CodeMirror blocks

site/app/controllers/calendar/CalendarController.php
=> [Bugfix:System] lint bug from Calendar PR

AUTHORS.md
=> [Documentation:Developer] update author list

site/app/templates/submission/Team.twig, site/ts/team.js
There are some JS errors on the team management page when the user is not in a team.
The errors are fixed.
=> [Bugfix:Submission] JS Errors on No Team Page

site/cypress/e2e/autograding_status_1.spec.js
Cypress autograding status tests currently fail
They have been commented out to get CI to pass, will debug locally 
Related to #9459
=> [Testing:Developer] Comment cypress autograding_status test

tests/e2e/test_submission.py
Selenium submission tests fail
First part of commenting out failing selenium tests, so CI passes. 
related to #9459
=> [Testing:Developer] Comment out selenium submission tests

site/app/controllers/forum/ForumController.php
change empty() to strlen() ===0, so that the user can only write 0 and post
User can not only write 0 and post, error will pop up
User can only write 0 and post.
=> [Bugfix:Forum] allow user to only write 0 and post

.setup/bin/versions.sh
https://github.com/Submitty/AnalysisToolsTS/releases/tag/v23.06.01
=> [Dependency] update AnalysisToolsTS v23.06.01

site/app/templates/grading/simple/Display.twig, site/cypress/e2e/simple_grading.spec.js
Currently there are some simple grader tests that are written in selenium
Since we are moving away from selenium, the functionality of these tests has been re-written in cypress tests.
=> [Testing:Developer] Rewrite simple grader tests in cypress

.github/workflows/bump_repo.yml, bin/update_repo_version.py
Sub-repository versions are updated manually in the Submitty codebase.
Adds a workflow to update sub-repositories on each release.
=> [Feature:Developer] Automate version update for Submitty sub-repositories

.setup/INSTALL_SUBMITTY_HELPER.sh
Also check for the junit_test_runner directory before attempting installation
=> [Bugfix:System] javac / junit_test_runner directory

site/app/templates/UserProfile.twig
Fixes syntax error in HTML code.
=> [Bugfix:InstructorUI] Fix HTML Code

.github/workflows/localization_up.yml
Adds workflow to send release updates to the Localization repository.
=> [Feature:Developer] Send release updates to Localization

site/app/templates/UserProfile.twig
Adds lang key to profile page.
=> [UI/UX:System] Add key to profile page

.setup/install_system.sh
=> [Refactor:System] typo fix install_system.sh

site/app/libraries/database/DatabaseQueries.php
Reformat the existing query to improve readability.
=> [Refactor:Developer] Reformat query

site/app/libraries/database/DatabaseQueries.php
Was reviewing some stuff and came across this query. No change, just indentation.
=> [Refactor:Developer] PeerFeedback query reformat

site/app/models/GradingSection.php, site/app/models/gradeable/Gradeable.php, site/phpstan-baseline.neon
If the team grading page is loaded, all formed teams do not get rendered. Additionally, CI is failing on the pdfs cypress test.
Teams get loaded as expected now. CI should now be passing.
This was due to #9804
=> [Bugfix:TAGrading] Fix rendering teams

site/app/controllers/admin/UsersController.php
Depending on how a CSV is created, it may get parsed as a mime type of `text/csv` which is not currently allowed.
Both `text/plain` and `text/csv` are allowed mime types for submission of the CSV file.
Made a local CSV file and it now parses both types.
=> [Bugfix:InstructorUI] Fix Upload Students CSV

site/composer.json
Our new plan is to make composer script for PHP stuff then bash script (#9675) will call this composer script.
=> [Feature:Developer] Composer script

.github/ISSUE_TEMPLATE/feature_request.md
Issues created using the feature request template currently are not currently tagged properly.
Feature request issues are now tagged appropriately.
=> [Documentation:Developer] Automatically tag feature request issues

.setup/bin/sample_courses/models/__init__.py, .setup/bin/sample_courses/models/course/course_create.py, .setup/bin/sample_courses/models/course/course_create_gradeables.py, .setup/bin/sample_courses/models/course/course_data.py, .setup/bin/sample_courses/models/course/course_generate_utils.py, .setup/bin/sample_courses/models/course/course_utils.py, .setup/bin/sample_courses/models/gradeable.py, .setup/bin/sample_courses/utils/__init__.py, .setup/bin/sample_courses/utils/create_or_generate.py, .setup/bin/sample_courses/utils/dependent.py
Before the strings were using .format instead of f-strings
The program is more consistent with using f-strings
=> [Refactor:System] Changed to f strings in sample_courses

site/cypress/e2e/Cypress-UI/pronouns_change.spec.js
=> [Bugfix:Calendar] Fix pronouns cypress test

site/app/libraries/database/DatabaseQueries.php
Error in late day cache. The cache for the user was trying to be accessed without being created.
If the user doesn't exist in the cache, then the user gets added to the late day cache, otherwise it continues getting the late day cache.
=> [Bugfix:Submission] User not found in late day cache

site/.eslintrc.json, site/cypress/e2e/Cypress-Admin/courseMaterials.spec.js, site/cypress/e2e/Cypress-Feature/late_days_cache.spec.js, site/cypress/e2e/Cypress-Feature/polls.spec.js, site/cypress/e2e/Cypress-Gradeable/gradeable.spec.js, site/cypress/e2e/Cypress-Gradeable/gradeable_results.spec.js, site/cypress/e2e/Cypress-Gradeable/grading_stats.spec.js, site/cypress/e2e/Cypress-System/autograding_status_2.spec.js, site/cypress/e2e/Cypress-UI/navigation_page.spec.js, site/cypress/e2e/Cypress-UI/pronouns_change.spec.js, site/cypress/support/utils.js, site/public/js/admin-gradeable-updates.js, site/public/js/admin-team-form.js, site/public/js/calendar.js, site/public/js/confetti.js, site/public/js/directory.js, site/public/js/docker_interface.js, site/public/js/drag-and-drop.js, site/public/js/forum.js, site/public/js/grade-inquiry.js, site/public/js/gradeable-notebook.js, site/public/js/latedays.js, site/public/js/pdf/PDFAnnotateEmbedded.js, site/public/js/polls.js, site/public/js/rainbow-customization.js, site/public/js/stat-page.js, site/public/js/superuser-email.js, site/public/js/system-update.js, site/tests/ts/activity-dashboard.spec.js, site/ts/activity-dashboard.js
Currently our JS lint doesn't enforce spacing for commas, which can lead to unorganized looking code, when you have multiple different spacings in the same file.
Comma spacing has been added to the JS lint rules, no space before a comma, required space after comma.
[test,bad] -- error, needs space after comma
[test ,bad] -- error, needs space after comma, and no space before comma
[test , bad] -- error, needs no space before comma
[test, good] -- good
See [William's Comment](https://github.com/Submitty/Submitty/pull/9803#discussion_r1367910049) for more context.
=> [Feature:Developer] Enforce comma spacing rules with JSlint

site/public/js/forum.js
Closes #9966 . Currently, there is an error when trying to edit a post from the main forum page.
This fixes the error and allows users to edit posts from the main forum page.
=> [Bugfix:Forum] Fix edit post from main page

site/cypress.config.ts, site/cypress/e2e/Cypress-Gradeable/edit_gradeable.spec.js
There are 3 current bugs with cypress tests: 
Flakyness in edit-gradeable.spec.js
Removing screenrecorded videos when no tests where being run
Flakyness in Docker_ui.spec.js
This PR fixes the first 2 bugs.
=> [Bugfix:Developer] Fix flakyness of Cypress tests

site/app/controllers/admin/UsersController.php, site/app/templates/admin/users/StudentList.twig, site/app/templates/admin/users/ToggleManageStudentsColumns.twig, site/app/views/admin/UsersView.php, site/public/css/directory.css, site/public/js/manage-students.js
The columns in the Manage Students page is missing columns for additional data we have on students. The only way to view this information is to press the "Edit Student" button for each individual student.
There are five new column options in the Manage Students page when the Toggle Columns button is pressed. When checked off there will be a new column for the additional data showing the information for all students instead of one. The new options are turned off by default.
(Image is cut off, you can scroll left/right to see all the columns on the site.)
First task in #9848
=> [Feature:InstructorUI] New Toggle Column Options

README.md
Updated contact method to Zulip, as we've transitioned communication platforms.
=> [Documentation:Developer] Update contact: Slack to Zulip

site/app/templates/admin/Extensions.twig
fixes #10041
=> A new paragraph tag was added below the extension.
None.
=> [Bugfix:Submission] Added note to absence extension

migration/migrator/migrations/course/20231005130620_forum_attachment_names.py
I previously wrote a database migration that could have been vulnerable to SQL injection if an image file existed on the server with SQL injection in the name. when the migration was run. 
This formats the query so it's no longer vulnerable to injection.
=> [Bugfix:System] Fix vulnerability in database migration.

.github/workflows/vagrant_up.yaml
We used to use slack as our messaging system, but we have since moved to Zulip
The Slack notifications have been removed, and the task has been renamed to Zulip
=> [Feature:Developer] Remove slack message

site/app/views/calendar/CalendarView.php
Solved issue  #10207
The issue is generating because we are taking a value of first index of an array which is empty. So, I have added nested ternary block which will take that first element if the length of an array is greater than 0.
Now, because of the modification it is working fine
=> [Bugfix:Calendar] Check if array null in CalendarView.php

.github/bin/label_abandoned_prs.py
Closes #10211
The python script will now check for whether a PR has approving reviews and has not had a changes requested review after the last approving review. It will also remove the abandoned tag if the PR is considered to be approved.
Todo: Check if it passes yml checks?
No, as this can only possibly reduce the amount of PRs that are marked as abandoned as it increases the criteria.
Todo: need to figure out how to test this.
There's probably a better way but this is the only thing that comes to mind: https://github.com/nektos/act?tab=readme-ov-file
=> [Testing:Developer] Don't Abandon Approved PRs

python_submitty_utils/tests/test_dateutils.py
- dateutils.py is missing unit tests for some functions
- Code coverage of dateutils.py is improved from 73% to 100%
- ~~The number of lines changed is a lot but this because of running the formatter on the test file~~
=> [Testing:Calendar] Add unit tests for dateutils

python_submitty_utils/tests/test_dateutils.py, python_submitty_utils/tests/test_db_utils.py, python_submitty_utils/tests/test_string_utils.py, python_submitty_utils/tests/test_submitty_schema_validator.py, python_submitty_utils/tests/test_user.py
- Util test files have inconsistent formatting
- None of the test files are changed when running ~~the formatter~~ `black` formatter
- These changes branch off the changes from [this PR](https://github.com/Submitty/Submitty/pull/10297)
=> [Testing:Developer] Format utils tests

site/app/controllers/admin/NotebookBuilderController.php, site/public/js/notebook_builder/widgets/markdown-widget.js, site/public/js/notebook_builder/widgets/widget.js
Notebook builder is completely unable to be accessed whether no matter what upload configuration you choose. It should not be that way, and you should not be able to modify PROVIDED folder.
Notebook Builder cannot access the PROVIDED folder through edit, but is able to create a new notebook builder anywhere into the UPLOADED folder.
Linked to https://github.com/Submitty/Submitty/pull/5945
=> [Bugfix:InstructorUI] Cant use Notebook Builder in Gradeables

migration/migrator/migrations/course/20240205154116_add_poll_timer.py
=> [Bugfix:SubminiPolls] Down Migration Fix (Poll Timer)

site/app/controllers/pdf/PDFController.php
Refactors all of the https://github.com/routes to the new PHP8 Syntax of #[Route()] for all pdf folder files.
=> [Refactor:System] pdf controller file refactoring @routes

site/app/libraries/database/DatabaseQueries.php, site/tests/app/libraries/database/AbstractDatabaseTester.php
This is a simple refactor fix that will change all the rows[0] to row()
=> [Refactor:System] Refactor all rows[0] to row

.github/workflows/db_check.yml, .setup/CONFIGURE_SUBMITTY.py, .setup/install_system.sh, .setup/testing/setup.sh, migration/migrator/migrations/system/20240204234806_update_vcs_permission.py, site/app/controllers/student/SubmissionController.php, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/submission/HomeworkView.php
If a student is added to a course through the autofeed script and a VCS gradeable is created before they entered the course, that user will not have a VCS repo created for them. They will be prompted that they can clone on the submission page but any attempts to clone will fail.
The website will now check if the repo exists. If it doesn't then it will prompt the student to create the repo. Upon clicking the button, a job will be added to the daemon queue and will go create any missing repositories.
A new group was added for supporting this functionality.
=> [Feature:Submission] Student Git Repo Creation

AUTHORS.md
=> [Documentation:Developer] update authors list

site/public/js/ta-grading-rubric.js, site/public/js/ta-grading.js
1. When I have a component open and I've changed the marks then press the right arrow to move to the next student, it doesn't always save the changes I've made to the marks.
2. If the component has been graded by someone else and I open it, make changes it doesn't display that I am now the grader, it still shows that the original person is the grader.
1. added waitForAllAjaxToComplete function to ensure that saving is done before go to main page and go to prev/next student
2. update graded by and verified by on change
=> [Bugfix:TAGrading] Save grading changes

site/app/controllers/SelfRejoinController.php, site/app/controllers/calendar/CalendarController.php, site/app/controllers/grading/popup_refactor/RubricGraderController.php, site/app/entities/poll/Poll.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/gradeable/GradeableUtils.php, site/app/models/gradeable/LateDayInfo.php, site/app/models/gradeable/LateDays.php, site/app/templates/error/NoAccessCourse.twig, site/app/templates/forum/ThreadPostForm.twig, site/app/templates/polls/PollForm.twig, site/app/views/admin/LateDayView.php
There were some spelling errors. 
There are now fewer spelling errors.
=> [Bugfix:System] Fixed Spelling Issues

site/app/templates/officeHoursQueue/QueueStatsStudents.twig
Changes "Sutdent" to "Student".
=> [Bugfix:InstructorUI] Fix typo in OH Queue Stats

site/public/css/select-widgets.css
Timezone not displaying in dark mode
=> [Bugfix:InstructorUI] No dark mode for select2

.github/bin/label_abandoned_prs.py
This PR moves logic for computing the current time out of a loop to avoid running it more than necessary, and renames a variable (`string` -> `updated_at_string`).
=> [Bugfix:Developer] Refactor auto-tag script

site/app/templates/admin/SqlToolbox.twig
=> [VPAT:InstructorUI] Improve SQL toolbox accessibility

site/app/templates/grading/electronic/PDFAnnotationBar.twig, site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig, site/cypress/e2e/Cypress-UI/pdfs.spec.js
Closes #10531
Added the test for buttons - `save`, `clear`, `download`, `Show all Annotation`
Is that all four button visible or not 
Which of the button is present as instructor, ta , grader and student 
As Instructor , ta and grader 
As student
=> [Testing:Developer] Added remaining test button in pdf 

site/public/js/user-profile.js
In user profile scroll in background is still enable where there's a popup
See below:
https://github.com/Submitty/Submitty/assets/122962727/c254b8c2-bc43-442e-986c-871bd7526df1
Disabled scroll in background
=> [Bugfix:InstructorUI] Disable background scroll in Userprofile

site/app/templates/polls/AllPollsPageInstructor.twig
(unchanged)
Tested using WAVE.
=> [VPAT:InstructorUI] Improve instructor polls accessibility

site/app/templates/GlobalHeader.twig, site/app/views/GlobalView.php
fixes #10458 
No banner warn the unsynchronized time settings between server and browser.
If the difference between server time and browser time larger than 2 min, show the banner.
=> [Feature:Submission] Add warning for unaligned time setting

.github/FIRST_ISSUE_REPLY.md
Update text for automated reply to a new Submitty contributor's first issue post.
=> [Documentation:Developer] Revise message to first time contributor

.setup/install_system.sh
Adds an alias to the vagrant box that can recreate courses (not tested as I do not wish to vagrant destroy and vagrant up)
=> [Feature:Developer] Add recreating courses alias

site/app/templates/forum/CreatePost.twig, site/cypress/e2e/Cypress-Feature/forums.spec.js
Related to #10159
Instructor upduck got merged without cypress tests.
Cypress tests for instructor, ta, and student. Additionally tests removing upducks from a post. Also moved some functions around relative to the order they are being called.
=> [Testing:Forum] Instructor Upduck Cypress Test

site/public/js/office-hours-queue.js
#10551 had a bad merge conflict resolution, as it removed a function in the code instead of linting it. 
This function is re-added and linted properly.
=> [Bugfix:Developer] Re-add student history function

site/ts/grader-submission.ts
#10467 Bulk upload button passed eslint one month ago
Our rules changed since then, but our CI didn't check it again, and now it has contaminated our `main`.
Developers are suffering from poisoned `main`.
Only this massive bugfix change can cure us. Please review thoroughly
=> [Bugfix:InstructorUI] URGENT Bugfix Bulk upload

.setup/bin/versions.sh
https://github.com/Submitty/RainbowGrades/releases/tag/v24.07.00
=> [Dependency] Bump RainbowGrades to v24.07.00

site/app/templates/grading/electronic/Details.twig, site/cypress/e2e/Cypress-TAGrading/ta_grading_details.spec.js, site/public/js/details.js
Closes #10576 
There is a lot of extra code, and the Grade Inquiry Only button for grading is broken.
The grade inquiry function was being run when there was no display for students yet, so I moved it to the bottom. Additionally, some of the logic and code were extra and backwards so I changed them accordingly.
=> [Bugfix:TAGrading] Fix Grade Inquiry Toggle Button

autograder/autograder/packer_unpacker.py
=> [Bugfix:Autograding] URGENT fix for Autograding error 

site/app/controllers/GlobalController.php
https://github.com/Submitty/Submitty/pull/10805 was merged despite a failing lint check, causing all PRs to fail the php-lint check.
The linting errors have been resolved.
=> [Bugfix:Developer] Fix php lint errors on main

site/app/templates/autograding/TAResults.twig
Student's will see the feedback but not know how to get the submissions to a valid state. There will be documentation coming to give a list of instructions 
Extension of the merged PR #10774 
Related to Issue #10569 
Closes #10793
Wording can be subjected to change.
=> [UI/UX:Submission] Version Conflict Language for Students

.github/workflows/move_to_in_review.yml
Fixes failing automation by adding actions/checkout step.
=> [Bugfix:Developer] Fix move to In Review

site/app/templates/autograding/TAResults.twig, site/app/templates/functions/Badge.twig, site/app/templates/functions/TAResultsFunctions.twig, site/app/templates/submission/homework/CurrentVersionBox.twig, site/app/templates/submission/homework/TAResultsBox.twig, site/cypress/e2e/Cypress-Feature/student_version_conflict.spec.js, site/cypress/e2e/Cypress-Feature/viewing_version_conflict.spec.js
With the newly merged #10774  came a version conflict that was not tested.
Closes #10792 
Adds the aforementioned tests
=> [Testing:Submission] Cypress for Student Version Conflict 

site/app/controllers/AutogradingStatusController.php, site/app/controllers/GlobalController.php
Allow superuser access to AutogradingStatus page through sidebar or link.
Solves #10917
=> [Feature:InstructorUI] Superuser accesss to AutogradingStatus

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20240924125155_doctrine_primary_keys.py, site/app/entities/UserEntity.php, site/app/entities/forum/Category.php, site/app/entities/forum/Post.php, site/app/entities/forum/PostAttachment.php, site/app/entities/forum/PostHistory.php, site/app/entities/forum/StudentFavorite.php, site/app/entities/forum/Thread.php, site/app/entities/forum/ThreadAccess.php, site/app/repositories/forum/PostRepository.php, site/app/repositories/forum/ThreadRepository.php
This is part one of refactoring the forum rendering to use Doctrine. This contains the entities and repositories that will be necessary to render the forum with doctrine. It alone will not affect any forum behavior. Part 2 will come after this and contain changes to the controller, view, and frontend.
=> [Refactor:Forum] Create doctrine forum entities

site/public/js/ta-grading-rubric.js
This should work identically to the old behavior, but now will be far easier to read.
=> [Refactor:TAGrading] Start switching to async/await

site/app/templates/polls/ViewPoll.twig, site/public/js/polls.js
Fixes #10614 
There is a lot of JS code in the twig file that isn't a good coding practice since we can reformat this code and place it into the JS file where that code will be linted.
Placed the code in the JS file by making a function with a sub-function and running only the function in the twig, so the majority of the JS code gets linted.
To test, verify that no functionality was broken.
=> [Refactor:SubminiPolls] Refactor Poll JS code from Twig to JS

.setup/data/courses/development.yml, more_autograding_examples/rust_hello_world/config/config.json, more_autograding_examples/rust_hello_world/submissions/correct.rs, more_autograding_examples/rust_hello_world/submissions/incorrect.rs
Fixes #10896. 
Simple gradeable config that compiles Rust "Hello World" and runs.
Relies on Submitty/Dockerimages#46. Make sure to have "submitty/rust:latest" docker image installed on the default capability before attempting to run locally.
=> [Documentation:Autograding] Add Rust "Hello World" example.

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20241108162239_cascade_on_delete_gradeable.py, site/app/libraries/database/DatabaseQueries.php
Deleting a gradeable can possibly throw a frog robot due to peer grading not being deleted.
Deleting a gradeable will work successfully.
Testing requires editing the [canDelete](https://github.com/Submitty/Submitty/blob/3b9c945261a67cbc1a2b864a1404d0f56d48b2fa/site/app/models/gradeable/Gradeable.php#L1804) function to allow the deletion button to be shown in the UI.
=> [Bugfix:InstructorUI] Fix gradeable deletion

grading/allowed_autograding_commands_default.json, more_autograding_examples/jupyter_notebook_execution/config/config.json, more_autograding_examples/jupyter_notebook_execution/submissions/example.ipynb
This PR adds Jupyter to the list of allowed programs and adds a simple Jupyter notebook execution example.
=> [Documentation:Autograding] Add jupyter execution example

.setup/install_submitty/install_site.sh
submitty_install_site (and therefore submitty_install) will show a permission error upon installing.
The scripts will run without error.
=> [Bugfix:System] Fix vite building in submitty_install

.setup/install_submitty/install_site.sh
=> [Refactor:System] Fix vite esbuild executable perms

site/app/libraries/Core.php, site/app/libraries/FileUtils.php, site/app/libraries/Output.php, site/app/libraries/TokenManager.php, site/app/libraries/database/DatabaseQueries.php, site/app/libraries/routers/AccessControl.php, site/app/libraries/routers/Enabled.php, site/app/models/AbstractModel.php, site/tests/app/models/ConfigTester.php
Changes to newer PHP syntax. For example, ${variable} should be {$variable}
=> [Refactor:System] Finish Changing to new PHP Syntax

LICENSE.md
=> [Documentation:Developer] Update License 2025

site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
Fixes #11260 
This PR resolves a floating-point error where adding decimals (e.g., 0.1 + 0.2) incorrectly displays 0.30000000000004. 
The issue was fixed by rounding numbers to two decimal places using toFixed(2) and parsing the result back to a float.
=> [Bugfix:InstructorUI] Max Score Floating Point Add Fix

site/app/templates/admin/Configuration.twig, site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig, site/app/templates/error/NoAccessCourse.twig, site/cypress/e2e/Cypress-Feature/registration.spec.js
Currently the UI just says course_name (course_id) is available ...
Closes #11310
=> [Bugfix:InstructorUI] Fix Self Registration UI

.gitignore
Visual Studio files are not currently ignored.
Visual Studio files are ignored.
=> [Documentation:Developer] Add .vs to .gitignore

site/app/controllers/GlobalController.php
Main is broken right now due to an condition `elseif` condition after the `else` condition
Removes it
=> [Bugfix:System] Fix extra conditional

autograder/autograder/scheduler.py
We apparently have a race condition.  If the autograding queue file is partial/incomplete 
the autograding scheduler will fail to load the json object.    This error is logged to 
`/var/local/submitty/logs/autograding_stack_traces/CURRENTDATE.txt`
```
== Traceback (most recent call last):
==   File "/usr/local/submitty/autograder/autograder/scheduler.py", line 48, in _try_load_queue_object
==     self._queue_obj = json.load(f)
==   File "/usr/lib/python3.10/json/__init__.py", line 293, in load
==     return loads(fp.read(),
==   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
==     return _default_decoder.decode(s)
==   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
==     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
==   File …
```
=> [Bugfix:Autograding] skip queue files with json load error

site/app/controllers/GlobalController.php, site/public/js/banner.js, site/public/js/drag-and-drop.js
There is a routing issue where it tries to reload to a "banner" page or location when in the file BannerController.php, every route has "community_events" instead.
Also there is an airplane icon being used which doesn't fit so I changed it to a palette icon.
These are all the routes in bannercontroller.php for reference: 
1.     #[Route("/community_events")]
2.     #[Route("/community_event/upload", methods: ["POST"])]
3.     #[Route("/community_events/delete", methods: ["POST"])]
=> [Bugfix:CourseMaterials] Routing Issue and Icon Type

.github/PULL_REQUEST_TEMPLATE.md
Currently, the pull request template is very out of date / inaccuarte to what most devs use. I aimed to revise it to make it more useful to the developer
Added a new section about testing, removed the checkmarks, and reworded some aspects of it. Included some comments explaining what each section should contain.
=> [Bugfix:Developer] Revise Pull Request Template

site/ts/ta-grading-rubric.ts, site/ts/ta-grading.ts
Silent edit is always set to true
Silent edit is set to whatever the cookies said
=> [Bugfix:TAGrading] Fix Silent Edit Button

site/app/controllers/forum/ForumController.php, site/app/models/Notification.php, site/app/templates/Notifications.twig, site/public/css/email-status.css, site/public/css/notifications.css, site/tests/app/models/NotificationTester.php
Notifications shown on the notification page have a trimmed version of their original content within the database, but there is no length constraint at the database level. This can make some announcements unclear, as they'll cut off after 40 characters. 
Closes #11737.
No notification trimming occurs when inserting a new notification into the database. Additionally, for long notifications on the email status and notification pages, the output is more responsive across all viewports.
Before
After
Release an announcement as an instructor with a long title and notice the difference in the final content on the main branch relative to this branch.
Text trimming unit test cases have been removed.
N/A
=> [Bugfix:Notifications] Remove Notification Content Trimming
