site/app/controllers/MiscController.php
site/app/controllers/admin/AdminGradeableController.php
site/app/controllers/grading/ElectronicGraderController.php
site/app/controllers/grading/ImagesController.php
site/app/controllers/student/SubmissionController.php
site/app/libraries/Core.php
site/app/libraries/DiffViewer.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/Notification.php
site/app/models/User.php
site/app/models/gradeable/GradedComponent.php
site/app/models/gradeable/GradedComponentContainer.php
site/app/models/gradeable/GradedGradeable.php
site/app/views/AutoGradingView.php
site/app/views/admin/ExtensionsView.php
site/app/views/course/CourseMaterialsView.php
site/app/views/forum/ForumThreadView.php
site/app/views/submission/HomeworkView.php
site/tests/ruleset.xml

Fixes the `Generic.ControlStructures.InlineControlStructure` style errors which is that all control structures (if statements, for loops, etc.) must have braces around its body. This helps maintain the best readability and clarify of the code.

[Refactor:PHP] Fix Generic.ControlStructures.InlineControlStructure style errors

---

site/app/libraries/database/AbstractDatabase.php
site/app/models/gradeable/Gradeable.php
site/tests/ruleset.xml

Fixes `PSR12.Keywords.ShortFormKeywords` style errors, which is that you should never use the long form of a keyword (e.g. `boolean` instead of `bool`).

[Refactor:PHP] Fix PSR12.Keywords.ShortFormTypeKeywords style errors

---

site/app/controllers/admin/AdminGradeableController.php
site/app/libraries/ExceptionHandler.php
site/app/libraries/Logger.php
site/tests/ruleset.xml
site/tests/utils/NullOutput.php

Fixes the `Squiz.WhiteSpace.ScopeClosingBrace` which covers the following bit from PSR-12:
* The structure body MUST be indented once
* The body MUST be on the next line after the opening brace
* The closing brace MUST be on the next line after the body

[Refactor:PHP] Fix Squiz.WhiteSpace.ScopeClosingBrace style errors

---

site/app/controllers/admin/PlagiarismController.php
site/app/libraries/Core.php
site/app/libraries/DiffViewer.php
site/app/libraries/FileUtils.php
site/app/libraries/database/DatabaseQueries.php
site/app/libraries/database/PostgresqlDatabase.php
site/app/models/CourseMaterial.php
site/app/models/Notification.php
site/app/models/RainbowCustomization.php
site/app/models/forum/Forum.php
site/app/models/gradeable/AutoGradedGradeable.php
site/app/models/gradeable/GradedComponentContainer.php
site/app/models/gradeable/GradedGradeable.php
site/app/views/NavigationView.php
site/app/views/admin/PlagiarismView.php
site/app/views/forum/ForumThreadView.php
site/app/views/grading/ElectronicGraderView.php
site/tests/app/controllers/AuthenticationControllerTester.php
site/tests/ruleset.xml

Fixes the remaining control structure sniff errors, which include:
* SlevomatCodingStandard.Variables.UselessVariable.UselessVariable
* SlevomatCodingStandard.Variables.DuplicateAssignmentToVariable.DuplicateAssignment
This change removes variables that are created to be immediately returned in a return statement.

[Refactor:PHP] Fix for UselessVariable and DuplicateAssignment

---

sbin/submitty_autograding_shipper.py

On failure to prepare a job, the autograding shipper now waits 5 seconds before trying again instead of instantly retrying. This should help to slow down log build-up in cases of failed grading. Future revisions should be made to further fix this error.

[Bugfix:Autograding] Sleep on Prepare Job Failure

---

sbin/submitty_daemon_jobs/submitty_jobs/bulk_qr_split.py

The Bulk Upload QR splitter does not save the last split PDF it found and only saves the 
along with filename.
Fixes uses the wrong key to save the file, now correctly saves the split pdf and its page count & id

[BugFix:Bulk Upload] Fix last split PDF not getting saved

---

.setup/INSTALL_SUBMITTY_HELPER.sh
autograder/autograder/autograding_utils.py
autograder/autograder/grade_item.py
migration/migrator/migrations/system/20191113082100_move_stack_trace_logs.py
sbin/submitty_autograding_shipper.py
sbin/submitty_autograding_worker.py

1. Adds a migration which moves the stack trace logs from ```var/local/submitty/logs/autograding/stack_traces``` to ```var/local/submitty/logs/stack_traces```.
2. Appropriate down migration also added.
3. New stack trace log names are no longer prepended with ```stack_trace_```. 
4.  ~~On failure to prepare a job, the autograding shipper now waits 5 seconds before trying again instead of instantly retrying. This should help to slow down log build-up in cases of failed grading. Future revisions should be made to further fix this error.~~  ___Moving to another PR___

[Bugfix: Autograding] Move Stack Trace Logs

---

site/app/controllers/pdf/PDFController.php
site/app/views/AutoGradingView.php

PDFs that have underscores in them failed to load properly as the code expected only one underscore in the name, where everything before it was the PDF name and everything after it is the user_id.
Allows the PDF to have as many underscores as it wants.
There is still a bug that exists that if the user_id contains underscores, it will not properly attribute annotations to that user.

[Bugfix:PDFAnnotator] PDFs with underscores fail to load annotations

---

site/app/controllers/admin/ReportController.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/gradeable/GradedGradeable.php
site/app/models/gradeable/LateDays.php
site/phpstan-baseline.neon

Fixes #4755 
Generating the CSV grade report is very inefficiently, currently running over 7,000 queries for the sample course in Vagrant. For real courses at RPI, this count is most likely going over 30,000 queries, which causes the page to take a very long time and generally just time out (with its 700+ students).
Fixes the slowdown, reducing the above query count to a constant 6 (or so) queries for the basic use-case. This is achieved by getting the following information in one batch instead of one at a time per user per gradeable.
1. Get all late day updates for all students
2. Get if a grade override exists for all gradeables for all students
This saved information is then used throughout as needed without requiring any subsequent queries for more information. The downside is that …

[Refactor:GradeSummary] Greatly reduce number of run queries for csv generation

---

site/package-lock.json
site/package.json
site/public/js/pdf/PDFAnnotate.js
site/public/js/pdf/PDFAnnotateEmbedded.js

Fixes #4345 
When loading a PDF, would see a number of deprecation warnings.
Deprecation warnings are fixed, with `@submitty/pdf-annotate.js` and `pdfjs-dist` updated to take advantage of this.

[Bugfix:PDFAnnotate] Update annotator and fix deprecation warnings

---

.setup/CONFIGURE_SUBMITTY.py

The ```site_log_path```, which could more accurately be called the ```submitty_log_path```, was missing from worker machines, causing an error when autograding. This PR adds the ```site_log_path``` to workers.

[Bugfix:Autograding] Added site_log_path to Workers

---

site/app/templates/admin/LateDays.twig

On the ```Late Days Allowed``` page, there was a line that specified that an uploaded csv should be of the form ```student_id, YYYY-MM-DD, late_days```. However the ```LateController``` is actually looking for dates of the form ```MM-DD-YYYY```.

[DOCUMENTATION:Fix] Updated CSV Format Text on Late Days Allowed

---

sbin/submitty_autograding_shipper.py

This PR adds a mitigation to a race condition which was causing the shipper to errantly claim ```VCS_``` queue files in place of autograding queue files.
When claiming a job, a single locked shipper process checks out every repo corresponding with a ```VCS_``` queue file it can find, and then deletes those queue files.
This opens the door for a race condition, where, if a student submits a VCS gradable after all existing repos have started to be checked out, but before the thread gets an updated list of all files in the directory, it might accidentally claim a ```VCS_``` instead of an autograding queue file. When checking out many potentially large repos, there is a larger than expected window of time for such submissions to occur. This would also lead to the job being claimed twice, once …

[Bugfix:Autograding] Stop the Shipper from Claiming VCS Queue Files

---

site/public/css/admin-gradeable.css
site/public/css/colors.css

Closes #4836
Grey text (disabled tab labels near top) that is circled in blue is colored #888888 and has a contrast ratio of 3.54:1.
Contrast ratio is now 5.50: 1 .

[VPAT:Gradeable] Poor Contrast Ratio In New Gradeables View

---

site/app/controllers/MiscController.php

Fixes #4689 
When a student goes to download a zip, the zip is empty of all files, unless it's a bulk upload.
The zip will contain all submitted files, unless it's a bulk upload type, in which case it will only contain the PDFs. Additionally, I use the `mime_content_type` function to do a proper check of the file's content type based on file contents, and not `FileUtils::getContentType` which only does a content type check based on the extension.
This fixes a bug introduced in #4627, and encompasses the fix added in #4673.
This should not be a breaking change unless it was intentional that students were not able to download any files. Tested it with bulk uploads, regular submissions, and as TA in TA grading interface.

[Bugfix:Submission] Fix zip downloads being empty for students

---

site/app/templates/forum/displayThreadList.twig
site/app/views/forum/ForumThreadView.php
site/public/css/colors.css
site/public/css/forum.css
site/public/js/forum.js

The style for the unresolved/resolved icons were defined inline to the twig template.
The style definitions have been moved into two classes `.thread-resolved` and `.thread-unresolved` and the classes applied to the icons to get the appropriate color, size, and positioning. 
This is some prep work for a PR to simplify accomplishing #4720 without having to do a lot of inline style manipulation (versus just removing and applying classes).

[Refactor:Forum] Move inline unresolved/resolved icon style to css

---

site/app/templates/grading/electronic/Status.twig

Closes #4801 
The median showed on the histogram page is the middle bucket value, not the middle grade value. It was also not calculating median properly for an even number of values.
Median is calculated for the median value of all grades. Also calculates properly for medians of even and odd number of values.
Using the sample course, I changed all 5 / 10 grades to 0 / 10 except for one. The value shown in master was `5`, but with this change was 3.75 (due to even number of values where pivot point lies at middle of 3.5 and 4). Removing one 0 / 10 grade, and value then changed to 4 as expected.
The big rewrite here is that instead of doing a for loop of twig and doing repeated calls to JS method `.push()`, we can just use the [join …

[Bugfix:TAGrading] properly calculate median for grades

---

grading/load_config_json.cpp

As a result of output buffering, some ```STDOUT``` was lost in cases where the router was killed for time. This PR changes the default router to be invoked in unbuffered mode by default.

[Autograding:Bugfix] Start Router Unbuffered by Default

---

site/app/templates/grading/simple/Display.twig

Fixes #4633 
Hitting the "View Your Section" button would just reload the page for viewing all sections. Also fixes that clicking to sort a column when viewing all sections would sort, but take you back to viewing just your sections.
Hitting the "View Your Sections" button not takes you to view your sections. Column headers links now properly retains whether you're viewing all sections or your sections.
`{{ view }}` was not defined in thew View file, but boolean `{{ view_all }` is, so utilize ternary argument to set the right value for `view=` in the URL. I checked all usages of `{{ grading_url }}` to find where in the file might need fixing, which was just the button and the columns.

[Bugfix:TAGrading] View your section button on test/lab not working

---

site/app/controllers/HomePageController.php
site/app/libraries/Output.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/Course.php
site/app/views/HomePageView.php
site/phpstan-baseline.neon
site/tests/app/models/CourseTester.php

The HomePageView runs a number of SQL queries and made a number of calls to `$this->core`.
The query logic is moved to the controller and all calls to `$this->core` rewritten to use `$this->output` where possible and then passed in new variables where not able.
This cherry picks the idea of commit 7a2b920a0ed19bd23ae6e2311176ed544760f2a7 from #4576, but rewritten incorporating my comments as well as some other substantial changes to further clean-up the code there.
Make sure that the squash + merge message has `Co-authored-by: Matthew Ma <alphaintec@gmail.com>` in it after two blank lines from the previous text to ensure proper attribution in the commit log on master.

[Refactor:PHP] Remove usage of core from HomePageView

---

site/app/controllers/admin/UsersController.php

Closes #4620
On the admin UI when viewing students / TAs, it is impossible to remove the preferred name (either first or last). If the preferred name is set to the empty string, nothing changes, and no error is displayed.
An instructor can set the preferred name to empty string (effectively removing it).
Looks like the bug was introduced 2 years ago with #1477 for preferred first name an then carried over into preferred last name when that was added.

[Bugfix:InstructorUI] Allow setting preferred name to empty string

---

site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
site/app/templates/admin/admin_gradeable/AdminGradeableRubric.twig
site/app/templates/admin/admin_gradeable/rubric/CheckpointsRubric.twig
site/app/templates/admin/admin_gradeable/rubric/ElectronicFileRubric.twig
site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
site/public/css/server.css

Accessibility improvements in various views for Create/Edit Gradeables.
Fixes include
- Correcting contrast ratio — `#FF0000` changed to `#CC0000`.
- HTML `style="color:red"` -> CSS `color: var(--error-alert-dark-red);`
- Adding `<label>` tags where needed.
- Adding `aria-label` properties where descriptive text does not exist.

VPAT — Edit Gradeables Views

---

site/app/models/gradeable/Gradeable.php

Fixes #4493 
Null section does not show up when viewing all sections.
Null sections show up when viewing all sections. The code was failing because doing `$a[null]` is silently recasted as doing `$a['']` which then did not correspond to any section names pull from `getRegistrationSections` or `getRotatingSections`. This fixes it so that instead, we write `$a['NULL']` as that's the section name we want to show. Code was also cleaned up so that it was a bit less repetitive.

[Bugfix:TAGrading] View all does not show the null section

---

site/public/js/ta-grading.js

Fixes #4598
When grading an assignment that has a PDF in its submissions folder, clicking the "Open / Close Submissions" button will open the PDF file viewer. This is a bug as the PDF file viewer should only be opened when the user manually clicks on a PDF.
Clicking the "Open / Close Submissions" button will no longer cause the PDF file viewer to open in this case. Any PDF files in the submissions folder will now only be opened via manually clicking on the PDF, and the other files will open or close as expected.

[Bugfix:TAGrading] Fixed PDF viewer unintentionally opening

---

site/app/templates/GlobalHeader.twig
site/public/js/forum.js
site/public/js/server.js

The method for JS for defining error messages differed from that of the PHP code and there was no function for success message.
Adds function for success messages and updates the error message function to match the styling for the messages generated via PHP. Also creates a comment in both places mentioning the link.

[Refactor:JS] Update error/success messages to match PHP generated ones

---

site/app/models/Email.php
site/app/models/NotificationFactory.php

Emails for forum notifications dont contain a link to the post/comment. This is annoying because once you get an email you have to separately open submitty, click the forum, then find the post. By adding a directly link to the emails it makes it much easier for people to get to the post/comment.
Added a url at the bottom of emails
(This is what it looks like when I open one of the email logs in nano)

[BugFix:Emails] Added urls to forum and team gradeable emails

---

site/app/controllers/grading/SimpleGraderController.php
site/public/js/simple-grading.js
site/tests/app/controllers/grading/SimpleGraderControllerTester.php

Fixes #4638 
Fixes #4716 
When a user modifies a checkpoint in the Simple Grader interface, the Simple Grader frontend does not, after receiving a success response, validate that the Simple Grader backend correctly saved the updated score. This means that it is possible for the frontend to report a successful save even when the backend did not actually save anything. 
The Simple Grader backend, upon a successful save, now returns a JSON response containing the ids and new scores of the components it updated. The Simple Grader frontend, during a checkpoint update, validates that this response matches with the expected new scores. If they do not match, then the Simple Grader interface reports a save error to the user via setting the checkpoint red, and also logs an error message to the …

[Bugfix:TAGrading] Fixed Simple Grader not validating backend saves

---

site/app/templates/submission/homework/SubmitBox.twig

Closes #4392 
* [ #] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ #] Tests for the changes have been added/updated (if possible)
* [ #] Documentation has been updated/added if relevant
Currently, spellcheck and/or autocapitalization may be triggered for a student when typing code in a submitty notebook.
Ex:
"for (int i = 0; ..." => . "for (int I = 0; ..."
Or spell corrects:
"std::cout << x << std::endl;" => "std::count << x << std::end;"
Autocapitalization and spellcheck in the notebooks are permanently turned off.

[Bugfix:Notebooks] Turn off autocapitalization and spellcheck in submitty notebooks

---

bin/json_schemas/complete_config_schema.json
grading/load_config_json.cpp

Closes #3437
```move mouse``` was missing from the json schema.
```click and drag delta``` did not allow negative x or y values.

[Autograding:Bufgix] Fixed Missing/Incorrect Graphics Action Specifications

---

bin/build_homework_function.sh

When creating a new assignment, ```make_generated_output.py``` was being invoked before ```complete_config``` was written, causing a failure on first build.

[Autograding:Bufgix] Fix Assignment Build for Automated Output

---

site/app/controllers/admin/ConfigurationController.php

If a gradeable is set up to be used for exam seating (i.e. the `reports/seating/<g_id>` directory exists and `g_id` is a valid gradeable), but the gradeable TITLE is alphabetically first among all gradeable titles in the course, then it did not display. This was due to the "None" option always occupying position 0 in the resulting array.
This has been rectified by making the "None" option occupy position -1 which should never be occupied by the query/filtering of valid gradeable IDs.

[Bugfix:Instructor UI] Exam Seating Dropdown Dropping An Option

---

site/public/css/colors.css
site/public/css/global.css
site/public/css/server.css

closes  #4457
The error message that sometimes shows up at the top of the page had a low contrast see  #4457
I fixed the contrast to not be so low
It now looks like this
I tested it with the wave plugin. The old version gave an error and my fix removed that error.

[VPAT] Adds higher contrast to error message popup 

---

site/app/controllers/student/SubmissionController.php
site/tests/app/controllers/student/SubmissionControllerTester.php

The change version endpoint on submission controller used old method of doing redirect + json responses.
Updates it to use the new Response object, making it easier to test.
Requirement for #4840 to be merged.

[Refactor:Submission] Update change version endpoint to use Response

---

site/public/js/server.js

This aims to fix issue #3830 
The bug this aims to fix is, when a modal is created a user could tab navigate to elements outside of that modal. The fix is a general Javascript function located in server.js which grabs the last and first tab-able elements from the modal and loops back to the first element when tabbing out of the last element. 
This fix has been implemented to some simple modals in server.js but not all modals yet (wanted to get feedback first).
This can be tested in Upload Course Materials and Delete Course Materials in Course Materials

Only tab navigate within a modal

---

site/app/templates/forum/GeneratePostList.twig
site/app/templates/forum/ThreadPostForm.twig

There is no way for a user with just a keyboard to submit a post/comment on the discussion forum
In all the textboxes on the discussion forum pressing ctrl+enter will submit their post.
closes #3570
I tested on new posts, comments, and editing.

[VPAT:Forum] ctrl+enter for direct submission of post

---

site/app/libraries/NumberUtils.php
site/app/models/gradeable/Component.php
site/app/models/gradeable/Gradeable.php
site/app/models/gradeable/GradedComponent.php
site/app/models/gradeable/GradedComponentContainer.php
site/app/models/gradeable/Mark.php
site/app/views/AutoGradingView.php
site/phpstan-baseline.neon
site/tests/app/libraries/NumbersUtilsTester.php

Currently there is a floating point bug inside the points calculation, this behavior can be seen by setting the precision of points as 0.05 and total point value as 6, as soon as we focuses out of the points input it gets converted to  6.05 which shouldn't be the case as 6 can be the point value using 0.05 precision. 
The bug is removed and it closes #4890. It improves the algorithm such that it should now better handle a number of different precisions and values. Given a small enough precision, may still have some (slight) rounding bugs, but it's not clear if we're going to hit those cases in practical usage.
Currently working on developing test cases to check and verify the intended behavior.

[Bugfix] PHP code incorrectly rounds valid numbers

---

site/app/controllers/admin/UsersController.php

Uploading a CSV to either Manage Students or Manage Graders page causes an exception due to `$uploaded_data` being used instead of `$row`, leading to things like the new user ID being an array of information instead of the ID
Uploading a CSV correctly reflects the level/registration section and works for new users and updated users. No exceptions are thrown.
Tested in a VM with master, both with newly created users and then users with sections changed. Tested for both students and graders.

[Bugfix: InstructorUI] Fix CSV Upload "not a string" exception

---

.setup/install_system.sh

When running vagrant up for a fresh install it fails because 2 lines need to be https not http
You can see the problem if you run vagrant up or to see the problem more quickly run
`wget http://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar` and take a look at the output
The first time I run it with http and it fails, the second time I run the same command with https and it works
Vagrant up now works and does not crash
I tested this by running vagrant up and after my change it worked for me.

[Bugfix:Install] Switched http to https for maven.org

---

site/app/controllers/admin/UsersController.php

If uploading a CSV while using database for passwords, an error would be thrown due to referencing an undefined variable.
Corrects the code to use the right variable for referencing the values in a given row of the CSV for password.

[Bugfix:InstructorUI] Fix using invalid variable when uploading CSV with passwords

---

migration/migrator/migrations/course/20200118230033_rainbow_grades_permissions.py
sbin/create_course.sh

Add group write permissions to rainbowgrades directory
to allow the use of the RainbowGrades web UI.

[Bugfix:RainbowGrades] add group write perm to rainbowgrades dir

---

site/public/js/ta-grading-rubric.js
site/public/templates/grading/EditComponent.twig

Bug introduced in PR #4504 
When a regular, non zero points component is grade by count down, the default mark 0 message should be "Full Credit".

[Bugfix:TAGrading] default full credit mark message grade by count down

---

site/app/controllers/GlobalController.php
site/app/controllers/grading/ImagesController.php
site/app/views/grading/ImagesView.php

Will now search multiple common locations for student photos:
/var/local/submity/student_photos
/var/local/submity/student_photos/<CURRENT_TERM>
And it will also display the student photos to full/limited graders if these locations are non-empty
(previously it would not show student photos to graders if the course did not have course-specific photos)
closes #4936 
future work:  refactor code & consider searching the common locations for matches with students who are in the course.  (should not show if there are no matches).  but that could be unnecessarily expensive(?).

[Feature:InstructorUI] student photo common location improvements

---

site/app/controllers/admin/ConfigurationController.php
site/app/libraries/FileUtils.php
site/app/models/Config.php
site/phpstan-baseline.neon
site/tests/app/controllers/admin/ConfigurationControllerTester.php
site/tests/app/libraries/FileUtilsTester.php

If the config.json file is unwritable for whatever reason, the system will fail to write, but show the instructor a message that reads "Server error", with a JSON object indicating things were successful.
Now returns a JSON object properly indicating that there was an error writing the config to file.
Added unit tests for both the underlying utility functions and the controller itself. Also manually tested on the web page.

[Bugfix:InstructorUI] Fix server error response on saving unwritable config file

---

site/app/libraries/routers/WebRouter.php
site/tests/app/libraries/routers/WebRouterTester.php

Currently, if we get logged-out on a page with some query parameters we are asked to log in (`intended`) and then after successfully logging-in you will get redirected to the page but without query parameters. So query-parameter is not working within log-out events.
Closes #4556 
Now, If you get logged-out at any page which is having query-params, you will be redirected to the same old URL you are were initially at with correct params.

Logging in after attempting to view page with query string does not work

---

site/app/controllers/AbstractController.php
site/app/controllers/HomePageController.php
site/phpstan-baseline.neon

Fixes a handful of phpstan baseline errors for phpDoc `@param` elements that lacked a type

[Documentation:PHP] Add types to several @param tags missing them

---

site/app/views/forum/ForumThreadView.php

Addresses #4924
For forums with no threads, the more button displays sorting options that are not displayed properly and would serve no function.
If a forum for a class has no threads, the more button is removed.
If the last thread in a forum is "deleted" then the more button is considered removed
Tested on blank course with forum enabled and observed forum bar.
Then created a thread and deleted it and observed forum bar.
One edge case that remains unaddressed is if an instructor deletes all the threads in a course but wishes to see the deleted threads. In order to do so, an instructor would need to create a new dummy thread and then select the show deleted threads option in More.
@xprilion I was looking through the CSS for in the file …

[Bugfix: Discussion Forum] Removes sorting options for forum with no threads

---

site/app/libraries/ExceptionHandler.php

From #4955. In some cases, the stack trace for an exception would not contain args in some of the frames, causing an undefined index warning to be issued.
Checks that `$frame['args']` is set before attempting to access it. Does not fix the underlying issue causing the exception from the issue however, so leaving the issue open.

[Bugfix:PHP] Fix undefined variable warning in ExceptionHandler

---

site/app/models/gradeable/AutogradingConfig.php
site/app/templates/submission/homework/SubmitBox.twig
site/app/views/submission/HomeworkView.php
site/phpstan-baseline.neon

When a user tries to submit an assignment with more than one part there is no indication given to the user that whether this gradeable allows only one part for the submisison. This creates confusion for the user as submissions made to buckets other than the first non-empty part are ignored & evaluated as 0.
Closes #2726 
Now, a message is being displayed to the user while submitting an assignment,  based on the condition on value of `one_part_only` boolean value and the number of parts of the submission.

Display message to student if one_part_only is True in gradeable config

---

site/public/js/drag-and-drop.js

When pressing the "Clear" button on a submission, it clears it internally but doesn't show that clear to the user. This can stack, resulting in unusual behavior as shown below:
Pressing the "Clear" button on a submission now properly clears the table visually.
Tested by pressing the "Clear" button after adding files, making sure that it was disabled after and readding the same file and different files and clearing again.

[Bugfix:Submission] Fix clear not showing submission table clearing

---

site/app/templates/forum/ThreadPostForm.twig

On a small screen some text on the forum would overlap with a button
This text now moves to the next line instead of overlapping.
closes  #4861
Tested on Linux using Firefox

[Bugfix:Forum] Fix for overlaping text on the anonymous checkbox label

---

site/app/templates/GlobalHeader.twig
site/public/css/sidebar.css
site/public/js/server.js

issue 1: when you refersh the page the sidebar does not save its current state. So it would choose what to do based on the screen size not the variable in localstorage. (It used to do this I am not sure exactly when this broke but this PR should fix it)
issue 2: If the sidebar had to close on page load it would slowly close and the entire page would shake and move around every time you refreshed the page. This is because the sidebar starts off always open but there is js to close it if the page is skinny or if it should be closed based on local storage
The sidebar will keep the state it is set at even across page refreshes. The sidebar will start open/closed and never cause the page to move around when a page is first loaded.
Tested on Arch Linux with Firefox and Chrome
To see what I mean …

[Bugfix:Sidebar] Sidebar no longer changes shape when page loads

---

site/package.json

A bug was introduced in twigjs ```1.14.0``` which causes escaping an empty string to return ```[object Object]```. This affected rubric creation by replacing many defaults with ```[object Object]```. 
This PR reverts  us to twigjs version ```1.13.3``` the version we were previously using.

[Dependency:JS] Revert twigjs version which introduced a bug in TA grading

---

site/public/js/server.js

Something I noticed when I was looking at #4953 a bit ago, is that it was using the localStorage incorrectly from its spec, which will undoubtedly cause cross-browser issues, where some browsers may implement the localStorage as read-only, and some do not.
This fixes localStorage to follow the [defined API](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) using the `getItem` and `setItem` functions, instead of directly trying to access properties. I've also fixed the usage here where all values in the localStorage are strings and that passing in the straight booleans were being silently converted, which could lead to some confusion.
I removed the comment as the first part was incorrect (`!!"false" === true`, it's a very common JS pattern), and the second part seemed …

[Bugfix:UI] Fix incorrect usage of localStorage for sidebar

---

site/tests/app/authentication/PamAuthenticationTester.php

The tests issue warnings when running, but execute fine.
Warnings are fixed.

[Bugfix:Testing] Fix warnings issued from PamAuthenticationTester

---

site/package-lock.json

From #4972, the package.json file was updated, but not the package-lock.json file, which can lead to potential unexpected behavior then in package installation on production.
Updates the package-lock.json file to match the package.json on specified twig.js version.

[Dependency:JS] fix npm lock file for rollbacked twig package

---

.setup/bin/install_site_dev.sh

Running the submitty_install_site_dev.sh script would result in a cache directory that had the wrong owner, which when combined with debugging set to false would result in site errors when Twig attempted to cache a template.
Fixes the ownership problem on the cache directory so that Twig can operate as expected.

[Bugfix:Install] Fix cache directory having wrong owner for site_install_dev

---

site/app/views/forum/ForumThreadView.php
site/public/css/server.css

Threads posted by Instructor/TA/Mentor show up exactly the same in the thread list as a normal student post (unless they are an announcement in which case they have a star)
Threads in the thread list now have the yellow border if they were made by an Instructor/TA/Mentor which matches how they look when you actually open the thread.
This was talked about at a DS mentor meeting last semester because it is not always clear when an important thread is posted. Anyone who uses the forum knows that they yellow border on a reply means it was made by course staff so it seems to me that it makes sense to have the sidebar follow this same format.

[Feature:Forum] Instructor/TA/Mentor posts now are yellow in thread list

---

site/public/js/ta-grading-rubric.js

Currently verifying components individually works fine, but trying to 'verify all'  throws an error for component_id.
Closes #4987 
Verify-all is now working and doesn't give any error for component_id.

[BugFix: InstructorUI] Verify all broken

---

site/app/templates/course/CourseMaterials.twig
site/app/templates/grading/simple/Display.twig
site/app/templates/submission/homework/SubmitBox.twig
site/app/views/grading/SimpleGraderView.php
site/app/views/submission/HomeworkView.php

If a Gradeable assignment has instruction URL set then there is a link shown in the list of gradeable, but there is no such link given to the student on the submission page, which should be present.
A link has been added to the submission page to assist the students with the instructions for the specific gradeable.
Closes #4926

[Feature:Submission] assignment url on gradeable submission page

---

site/app/templates/OfficeHoursQueue.twig

When the office hours queue's history is very large the page will crash on some phones.
This pr limits the history to the most recent 25 people in the queue.
This is just a small pr to make sure that the queue does not crash. This PR does not fix any of the other smaller bugs that are less important, see #5001 
If that PR is merged this one does not have to be, however, this one is much smaller so it should be easier to review and merge before the Wednesday CS1 and DS labs.

[Bugfix:Queue] page crashes with lengthy queue history

---

site/app/models/gradeable/AutoGradedVersion.php

Closes #4386 
Previously when constructing a notebook gradeable only a single 'testcase_label' was allowed to reference a single 'testcase_ref'.
Duplicate 'testcase_label' may point to a single 'testcase_ref'.  This now allows multiple testcases to be tied to a single notebook input type.  For example both compilation tests and regular tests may reference a single 'testcase_ref'.
See #4386 for what changes are not addressed here and why.
Tests were done on the CPP crash_course gradeable.  I made multiple 'testcase_label's point to a single 'testcase_ref' and ensured the correct number of error messages made it into the browser window.

[Feature:Submission] Tie multiple 'testcase_label' to single 'testcase_ref'

---

site/public/css/global.css
site/public/css/server.css

ios buttons don't follow the css style and so they are extra small and look different. I believe this only happens for buttons inside forms.
This should make them ignore the built in css and therefore look the same as they do on computers and android phones
I did not test this. I dont have an iphone and so I have no way to test this. I found this fix here https://stackoverflow.com/questions/5449412/styling-input-buttons-for-ipad-and-iphone
and was hoping somebody with an iphone can test this for me.
I have been told this can also be tested on the ios simulator on an apple computer.

[Bugfix:UI] Fixes buttons not following css styling on ios

---

site/public/js/ta-grading-rubric.js

Closes #4729 
If we make any changes made in custom message for some mark or overall message and hit *cancel* there is prompt for the TA which lead to accidental loss of that message.  
Now if there is any changes made in the custom message of any mark or the overall component and you press *cancel* submitty will ask you for a confirmation.

[Bugfix:TAGrading] popup error when writing a custom message

---

site/public/css/server.css

This reverts commit 383baba1fc55790cf17312a1238e6c870b2b0e1b.
Revert "[Bugfix:UI] buttons not following css styling on ios (#4980)"
radio buttons were not displaying on mac Chrome, mac Safari or Linux Chrome (didn't test anything else)

Revert "[Bugfix:UI] buttons not following css styling on ios (#4980)"

---

site/app/templates/GlobalHeader.twig
site/public/js/server.js

The room seating picture has been shifted to be half off the page
The room seating chart now looks correct and back to how it always looked.
Tested on linux using firefox

[Bugfix:Sidebar] Fixed room seating pictures being shifted off the page

---

site/app/templates/forum/ForumBar.twig
site/app/views/forum/ForumThreadView.php
site/public/css/forum.css

Fixes #4924 and undoes ##4943.
Currently the more button is missing for Discussion Forums with no threads which makes it hard for instructors/graders to create category.
Overflow still technically is cut off for the more dropdown menu.
Overflow is now fixed for the forum bar.
Instructors and graders have access to the "edit categories" option from the more dropdown menu even for empty Discussion Forums.
Students looking at empty Discussion Forum do not access to the more dropdown

[Bugfix: Discussion Forum] Fixes more dropdown menu behavior for empty discussion forum

---

site/app/templates/forum/ThreadPostForm.twig
site/app/templates/submission/regrade/Discussion.twig
site/public/css/forum.css
site/public/js/forum.js

When selecting the markdown option it allows you to add code blocks and URLs to a discussion forum post.
In addition to the previous options, it now includes bold and italics
This should not break anything since its text in the discussion forum text box. Worst case if they mess with the spacing the markdown may not work as expected but by default, there are spaces inserted between so it would not be an issue unless they delete any of the preformatted inserted text

[Feature:Forum] Adds Markdown Templates

---

site/app/controllers/forum/ForumController.php

Students could see the http://192.168.56.111/s20/development/forum/categories page if they know the url. However anything they try and do on this page will fail to work, so this is not a huge deal.
This now does not allow students to view the page

[Bugfix:Forum] Fixed students being able to see the forum category page

---

site/public/css/server.css
site/public/css/ta-grading.css
site/public/js/gradeable.js
site/public/js/ta-grading-rubric.js
site/public/templates/grading/Component.twig
site/public/templates/grading/EditGradeable.twig
site/public/templates/grading/GradingGradeable.twig
site/public/templates/grading/PeerGradeable.twig

This PR:
1. Updates the color of peer grading related elements to ```standard-plum-purple``` per prior conversations.
2. Adds a border around peer components to help graders distinguish them from non-peer components.
3. Changes the color of discussion forum related UI elements from ```standard-plum-purple``` to ```standard-light-seafoam```
___

[UI:TAGrading] Updated Peer Panel and Component Colors

---

site/app/controllers/grading/ElectronicGraderController.php

The ```Manual Grading Total``` on the TA grading page was errantly being computed based only upon components graded by the currently logged in user. This PR fixes this issue by ensuring that TA grading total is instead totaled over all graders for non-peer gradeables.

[Bugfix:TAGrading] Fixed Manual Grading Total Display

---

site/app/templates/generic/Popup.twig
site/app/views/admin/PlagiarismView.php
site/public/css/server.css
site/public/js/directory.js
site/public/js/homepage.js
site/public/js/server.js
site/public/js/userform.js

Currently, in small browser windows, a lot of `popup modals`  like user-form  requires scrolling. As the position of modal buttons are fixed , it creates a impression as if there are no more fields (or content like in `upload classlist` and `upload graderlist`)
Closes #4203 
Now the modals are changed to have fluid footer and buttons i.e they are kept inside the scrolling section.

[Bugfix:UI] Modal Scrolling & "Modal Footer" w/ Close & Submit buttons

---

site/app/templates/forum/EditPostForm.twig
site/app/templates/forum/HistoryForm.twig

The forum has 2 models that load into the page with h tags but without a value. When you run WAVE it reports them as missing values which should never happen in a h tag.
Closes #5038
The h tags get filled in with javascript when the modal is loaded, however WAVE does not know this and therefore it reports them as empty. I fixed this by giving them a more generic default value that works for every post. Just like how it was before, that value will be overwritten with JavaScript with a more detailed value as soon as the modal is opened.
I did not include screenshots as the issue only happens when the elements are hidden so there is nothing I can show.

[VPAT] Fixed blank blank primary headers on the forum

---

site/app/controllers/forum/ForumController.php
site/app/libraries/Access.php
site/public/js/forum.js

There are 2 bugs with the forum. The first one is that users cannot view the page to modify categories because a normal get request does not contain a csrf token. This fix makes it so that to load the page you dont need the token, but to actually modify the categories you still need the token.
This is a bug introduced in a previous pr that attempted to limit students from viewing the page, but in the process limited anyone trying to view the page if they did not have a csrf token.
The second issue is that the eye button is visible in the history for a post even though when you click it there is nothing to reveal. This happens for limited access graders who cannot unhide somebody's real name.
The modify categories page now loads (only if you have access to modify the categories)
The eye …

[Bugfix:Forum] Fixed edit categories page not loading and remove eye icon when there is nothing to show 

---

site/app/templates/forum/CreatePost.twig
site/app/templates/forum/ForumBar.twig
site/app/templates/forum/MergeThreadsForm.twig
site/app/templates/forum/ShowCategories.twig
site/app/templates/forum/ThreadPostForm.twig
site/public/css/forum.css
tests/e2e/test_forum.py

Some parts of the forum had duplicate ids on html elements.
I removed all the duplicate ids
Closes #5040
I searched through all the files and I did not see any code that used the ids that I changed. So it should be safe to remove them all.

[VPAT:Forum] Removed duplicate ids on html element

---

site/app/controllers/pdf/PDFController.php
site/app/templates/autograding/TAResults.twig
site/app/views/PDFView.php

Fixes #5061  
Students would receive an error or blank window when attempting to view the annotated PDF.
Students can now view the annotated PDF, as well as click the original PDF button.
During testing, did notice the "Original" button for the PDF shows the annotated version. I am not sure when this last worked properly, given that it goes to the same URL as the annotated URL, can probably make a secondary issue for that.

[Bugfix:Submission] Fix viewing annotated PDFs on submission page

---

site/app/controllers/MiscController.php

Not able to view or annotate PDFs in the checkout directory or in a subfolder. This was broken by a bad master merge in #5033 that had reverted some key changes in #5016.
Can view and annotate PDFs that are in checkout folder or in a subfolder in submissions folder.

[Bugfix:TAGrading] Fix not being able to view/annotate PDFs

---

site/app/controllers/admin/ReportController.php
site/app/models/RainbowCustomization.php
site/app/templates/admin/RainbowCustomization.twig

Partially handles #4961
In the rainbow grades customization screen, the bucket count which is displayed is *always* the number of gradeables for which there is information in the database.
The count that is displayed for each gradeable will be one of the following:
1. The number of gradeables found in the database for that bucket
1. The value manually entered in this field by the user (or edited in the customization.json)
The value used will be the greater of these two values.  This was done so that when the bucket count is known ahead of time the instructor may enter that.  However other users may not know the value ahead of time and may instead just rerun the rainbow grades tool every time a new gradeable is created and the GUI tool will still work correctly in this case.
Tested by:
- …

[Bugfix:RainbowGrades] gradeable bucket count in GUI tool

---

site/app/models/RainbowCustomization.php
site/app/templates/admin/RainbowCustomization.twig
site/public/js/rainbow-customization.js

Partially handles #4961
When the rainbow grades web gui builds the customization.json file it doesn't include any information about the release time for each gradeable.
The web gui now captures the time for each gradeable when it should become visible to students.  This time was captured from the release time in the gradeable 'date' tab.  This information is passed forward to the customization.json file and recorded inside the ids array.
The timestamp is formatted by the [DateUtils format function](https://github.com/Submitty/Submitty/blob/204c9b550ca09db3c0c15ad9de4e01c0549afee5/site/app/libraries/DateUtils.php#L113-L123).  This format is YYYY-MM-DD 24H:MM:SS-Offset.

[Feature:RainbowGrades] Added 'release_date' field to customization.json

---

site/app/controllers/grading/ElectronicGraderController.php

Updated the ```ajaxGetGradedGradeable``` function to use ```getSubmitterById``` rather than ```getUserById```. ```getSubmitterById``` is preferred, as it is a wrapper for ```getUserById``` and ```getTeamById``` which works for either team or user ids.

[Bugfix:TAGrading] Stop TA Grading from Failing on Teams

---

.setup/apache/submitty.conf
.setup/bin/recreate_sample_courses.sh
.setup/distro_setup/ubuntu/bionic/setup_distro.sh
.setup/install_system.sh
Vagrantfile
site/tests/app/controllers/admin/ConfigurationControllerTester.php
tests/e2e/base_testcase.py

Submitty under vagrant is accessible via a IP address (e.g. http://192.168.56.111/) which is a historical remanent when this was necessary as we were running multiple components under different URLs (submission, vcs, cgi) as well as potentially multiple different distros.
Submitty would be accessible under localhost with a port specific to a given distro. This is set-up so that the same URL (e.g. http://localhost:1501) would be accessible both within and outside the VM so that all things continue to work as expected where some requests are from the host (e.g. from the user) and within the guest (e.g. requests to cgi-bin, submitty admin usage, etc.).
I tested that after doing a fresh `vagrant up`, I could:
* access the site and log in
* use git

[Feature:Vagrant] Set vagrant to use localhost to access site

---

site/app/controllers/admin/PlagiarismController.php

Submitty will crash on loading configuration page for new gradeables. 
This fix will prevent the crash.

[BugFix:Plagiarism] Fix exception when creating configuration for a new gradeable

---

site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig

Part 1 of #4988 (doesn't close the issue because there's a second part about limited access graders & all access grading errors)
Currently, there is no on page documentation for when all "access grading" or "registration section grading" radio buttons are selected on the edit rubric page under the "grader assignment" tab for instructors.
The descriptions were added under the radio buttons, and it is updated when a different access grader is selected from the dropdown menu.

[UI:InstructorUI] On page documentation for edit rubric page radio buttons

---

site/app/controllers/admin/AdminGradeableController.php
site/app/controllers/admin/AutogradingConfigController.php
site/app/templates/admin/UploadConfigForm.twig
site/app/views/admin/GradeableView.php

When an instructor is editing a gradeable, and uses the upload config option to upload the config.json & etc through the webpage, there is no way to go back to the edit gradeable page where he came from.
A link is shown on the config upload screen letting the instructor go back to the gradeable editing page on the exact same location from where he came from.
Closes issue #4619

[Feature:InstructorUI] link back from upload config page

---

site/app/libraries/Output.php
site/app/models/Breadcrumb.php
site/app/templates/GlobalHeader.twig
site/app/templates/forum/ShowForumThreads.twig
site/app/views/forum/ForumThreadView.php
site/public/css/forum.css
site/public/css/global.css
tests/e2e/test_sidebar.py

Currently the forum has a temporary hidden h1 heading but we would like to make the breadcrumb into the heading for the forum.
While the page looks exactly the same, on the forum, the breadcrumb that says "Discussion Forum" is now a h1 tag. Every other page still has the normal h1 tag in the main section of the page.
this solves one of the issues in #4491
See this specific comment for more details:
https://github.com/Submitty/Submitty/issues/4491#issuecomment-590667020

[VPAT:Forum] replace 'invisible' h1 with breadcrumb h1

---

site/app/templates/submission/homework/SubmitBox.twig
site/public/js/gradeable-notebook.js

Editing codebox answers and textbox answers are not setting the status of buttons ( `submit`, `clear`, `use most recent`) correctly. 
Closes #4422 
Editing codebox and textbox answers now set the status of all three buttons correctly.

[Bugfix:Submission] re-enable submit button after editing prior notebook answers

---

site/app/templates/officeHoursQueue/FilterQueues.twig
site/app/templates/officeHoursQueue/QueueFooter.twig
site/public/css/officeHoursQueue.css

There is no way to know if a student has joined the queue unless you are looking at the queue
Closes #5052
If the queue has nobody waiting (so everyone is being helped or the queue is just empty), and you enable notifications, then the page will send a browser notification letting you know when somebody joins. If the queue has people waiting and somebody else joins, no notification will be sent. So in a busy office hours with a full queue, no notifications will be send. However in a quiet office hours with a mostly empty queue, you will get a notification whenever somebody joins.
Because of how notifications work, you need to test them over https, however I dont know how to make Submitty use https on my vagrant install. I did find a workaround for chrome but not firefox. In chrome if you …

[Feature:InstructorUI] notification on student join an empty queue

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/models/gradeable/LateDayInfo.php
site/app/views/grading/ElectronicGraderView.php
site/public/css/ta-grading.css

Currently, if a student submits multiple times (i.e multiple versions) then by default the most recent version is set to be graded (student can, however, decides this and selects which version is to be graded by the grader). But Sometimes the student uploads the assignment in a late period even when s/he already has a good submission, this may lead to evaluation as zero. 
Closes #4891 
Provides a visual clue to the instructor that the student has one of their assignment submitted on time, if s/he has more than one good submissions then submitty suggests the most recent good submission to `rollback`. This helps to avoid any accidental misevaluation as the instructor can `"roll-back"` to that suggested version for grading.
Rollback is Available
No Good Submission Found.

[Feature:TAGrading] "Rollback Available" TA grading

---

site/app/templates/GlobalHeader.twig
site/public/js/server.js

There is a redundant link in the breadcrumbs
Closes #4075
This uses js to remove and add back the redundant link in the breadcrumbs. The reason for the redundant link was because there is the mobile and desktop version of the button. By removing from the page dom, whichever one was not being show in the first place, it solves the issue.

[VPAT] Removed redundant link in breadcrumbs

---

site/app/templates/submission/homework/SubmitBox.twig
site/app/views/submission/HomeworkView.php

1. Login as instructor
2. Go to sample course
3. Click on a team assignment
Added check for null `$graded_gradeable` object
Cleaned up twig code

[Bugfix:Submission] empty submitter error for instructor team submission

---

site/app/controllers/grading/ElectronicGraderController.php

Following error
FILE: ...mitty/Submitty/site/app/controllers/grading/ElectronicGraderController.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------------
1051 | ERROR | [ ] Expected "if (...) {\n"; found "if(...) {\n"
|       |     (SubmittyStandard.ControlStructures.StroustrupStructure.Found)
1051 | ERROR | [x] Expected 1 space(s) after IF keyword; 0 found
|       |     (Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
-------------------------------------------------------------------------------- …

[Bugfix:PHP] Lint error

---

site/app/libraries/database/DatabaseQueries.php

When timestamps are identical, the sorting of the discussion forum items is dependent on the order that the database returns the posts, which is not guaranteed to be the same. If this ordering happens to be poor, it causes posts to be placed above their parents.
Post ordering is now also sorted by post ID (given that there are identical timestamps), guaranteeing that children posts will always be under their parents.
Tested to make sure that discussion forum now orders posts correctly (using sample database, where there are identical timestamps for a few posts).

[Bugfix:Forum] sort forum posts with identical timestamps

---

site/app/libraries/database/DatabaseQueries.php
site/app/templates/forum/CreatePost.twig
site/app/templates/forum/GeneratePostList.twig
site/app/views/forum/ForumThreadView.php

There is a show history button even though there is no history to show
That button is no longer visible

[Feature:Forum] Hides show history button when there is no history to show.

---

site/app/templates/course/UploadCourseMaterialsForm.twig
site/app/templates/grading/electronic/RubricPanel.twig
site/app/templates/grading/electronic/SubmissionPanel.twig
site/public/templates/grading/Mark.twig

When you click a label next to a checkbox it should toggle that checkbox 
Closes #3592
Every label for a checkbox or radio box should toggle that box. 
Some pages dont have a label for a specific checkbox, for example the notifications settings page. So I did not do anything to that page. It does have labels but they dont correspond 1 to 1 to a specific checkbox so I think it should stay as is.
I used regex to find every checkbox and radio box and then I tested them all by hand to see if they work so I am pretty sure I tested every one on the entire website, meaning it is safe to fully close the issue.

[Feature:UI] Made all labels toggle checkbox/radio buttons when clicked

---

site/app/templates/admin/Report.twig
site/app/templates/forum/StatPage.twig
site/app/templates/forum/searchResults.twig
site/app/templates/grading/electronic/Details.twig
site/app/templates/grading/simple/Display.twig
site/app/templates/grading/simple/StatisticsForm.twig
site/app/templates/submission/Team.twig
site/app/templates/submission/homework/BulkUploadBox.twig
site/app/views/grading/ElectronicGraderView.php

The width attribute of \<table> is not supported in HTML5. Use CSS instead.
This is reported by the w3 validator as well as it is mentioned at the bottom of this page
https://www.w3schools.com/TAGs/att_table_width.asp
Switched all table widths to use css

[VPAT] Switched all table column widths to use css over html attributes

---

site/public/js/pdf/PDFInitToolbar.js

As described in issue #5138 if an instructor has made freeform comments on a pdf and then rotates that pdf, the comments are deleted (even if the instructor saves after making the comments and before rotating).
Rotating the pdf no longer deletes comments.
Closes #5138

[Bugfix:TAGrading] rotating PDF erased annotations

---

site/app/templates/grading/electronic/SubmissionPanel.twig

closes #5034 
The `+ / -` icon in the file list viewer changes to the opposite when opening a PDF (plus becomes minus, minus becomes plus) for annotation.
The icon will now be constant for PDF's, but continue its original behaviour for viewing other files.

[Bugfix:TAGrading] Fixed open close icon for PDF

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20200311135223_oh_queue_contact_info.py
site/app/controllers/OfficeHoursQueueController.php
site/app/controllers/admin/ConfigurationController.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/Config.php
site/app/models/OfficeHoursQueueModel.php
site/app/templates/admin/Configuration.twig
site/app/templates/officeHoursQueue/CurrentQueue.twig
site/app/templates/officeHoursQueue/QueueFooter.twig
site/app/templates/officeHoursQueue/QueueHeader.twig
site/config/course_template.json
site/tests/app/controllers/admin/ConfigurationControllerTester.php
site/tests/app/models/ConfigTester.php
tests/e2e/test_office_hours_queue.py

RPI has shut down the campus and we have no way to run office hours
I added a setting to the course settings page to enable the ability for students to add contact info to the office hours queue.
Once checked, students will not be required to add their contact info to join the office hours queue for that class.
Contact info is just a required textbox, so you can send an email, a url, or anything else.
For instructors/mentors/tas they will see this contact info under the student in the queue

[Feature:InstructorUI] Option to collect contact information for office hours queue

---

site/public/css/bootstrap.css
site/public/css/colors.css
site/public/css/server.css

Wave gives contrast errors on the red and green buttons
fixes #5142
I changed around the color red slightly to make it give a better contrast
I also made the text on green buttons black instead of white which fixes the contrast issue

[VPAT:InstructorUI] Fixed low contrast on red and green buttons as well as red notification icon

---

site/app/templates/grading/electronic/SubmissionPanel.twig

The `file-url` attribute, which is used in a couple of places, contains both the file url and `key_to_click` which is a class name.
~~This might be a fix for #5147.~~ Confirmed to fix #5147
The `key_to_click` string is moved to class and `file-url` just contains the file path string.

[Bugfix:TAGrading] file-url attribute having path and class name

---

sbin/submitty_daemon_jobs/submitty_jobs/bulk_upload_split.py
site/app/controllers/student/SubmissionController.php

* [X ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [X ] Tests for the changes have been added/updated (if possible)
* [ X ] Documentation has been updated/added if relevant
When the bulk upload process splits a pdf up, the pages are stored as images, on submitting split pdf images from other students can be placed in the wrong student's submission
Issue caused when multiple combined pdfs are uploaded at once, this would create 1 shared folder for all the processes to save images to. The previous incorrect regex would match images from multiple students since it was only looking at the split number and the page number, it now compares the split pdf filename to the original combined pdf filename along with the other information to …

[Bugfix:Submission] incorrect page images for bulk upload submissions

---

site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig

In a recent PR, the ```id``` attribute was removed from the configuration selection dropdown on the create/edit gradeable form. This created an error which stopped gradeables from successfully building when selected via the dropdown. This PR re-introdcues an ```id``` to fix the error.

[Bugfix:InstructorUI] Add id back to config selection dropdown

---

site/app/templates/generic/Popup.twig

Cannot press enter in text fields in popups.
Can now press enter in text fields in popups.
Tested enter in popups, made sure that the buttons in the popups could still be pressed with tab/enter.

[Bugfix:Forum] Fix enter inputs being eaten in popups

---

site/app/templates/GlobalHeader.twig
site/app/views/GlobalView.php
site/public/css/sidebar.css
site/public/js/server.js

Due to how the sidebar works it needs to have a style element inside the \<noscript> element.
This is an issue shown in the w3 validator https://validator.w3.org/nu/#file
The sidebar used to save its current state (open/closed) on the client and so when the page is rendered it was sent with the sidebar always open and the client would shut the sidebar if it should be closed.
This pr moves the variable that stores the last sidebar state from local storage to a cookie which the server can read and therefore send the sidebar already collapsed if it needs to be. Because of this change there now no longer needs to be a style element inside of the \<noscript> tag
This hope with this and the other few w3 validator related prs open is that once they are merged I can merge a e2e test that will …

[VPAT] Fixed w3 validator error by removing style element from noscript tag

---

site/app/controllers/admin/ReportController.php
site/app/models/RainbowCustomization.php
site/app/models/RainbowCustomizationJSON.php
site/app/templates/admin/RainbowCustomization.twig
site/public/js/rainbow-customization.js

Partially handles #4961
There is currently no way to modify the course wide 'benchmark_percent' field for the rainbow grades customization.json from the web ui.
This functionality has now been added.

[Feature:InstructorUI] benchmark percents input for Rainbow Grades UI

---

sbin/submitty_autograding_worker.py

Closes #5045
Stale results files in the ```autograding_DONE``` directory on worker machines were causing bad results to be returned in rare cases when the ```update_and_restart_workers``` script was run. To fix the issue, worker daemons now clean up any stale files in the ```autograding_DONE``` directory on restart.

[Bugfix:Autograding] empty autograding_DONE on worker restart

---

site/public/css/server.css

Previously, markdown links the "assignment_message" were rendered in blue, but the background is dark blue, nearly impossible to read.  Now they are white like the rest of the text.
Fixes #4419

[Bugfix:Submission] Make links in assignment message white

---

.setup/install_system.sh

Even though nullsmtpd is set to be enabled, for whatever reason inside the vagrant machines multiple people are experiencing it not running. 
Here is some other conversation on the topic https://github.com/Submitty/submitty.github.io/pull/203
This pr starts nullsmtpd whenever you ssh to the vagrant machine by adding it to the bashrc file. This ensures that it is always running when you want to develop code related to emails as long as your first ssh to the vagrant vm (which you will need to do anyway to view the output of the emails you are sending).
I tested this by running a fully vagrant destroy and vagrant up just to be sure.

[Bugfix:System] systemctl starts for services on vagrant ssh

---

site/app/controllers/admin/ConfigurationController.php
site/app/templates/officeHoursQueue/QueueHeader.twig
site/app/templates/submission/homework/SubmitBox.twig

you cannot use newlines and/or markdown on the upload message and office hours queue welcome message
closes  #1821
Both normal newlines as well as markdown now work on both messages
I know this issue was meant for @DefinitiveAbove but when looking into fixing something else I stumbled across this fix. I spoke with him and he had not started so we agreed I would just submit a pr for it.

[Bugfix:InstructorUI] Newlines now work in office hours queue and upload messages

---

.setup/install_submitty/install_site_dev.sh
.setup/install_submitty/install_site_prod.sh

Signed-off-by: Matthew Peveler <matt.peveler@gmail.com>
There was a chance that composer would use the source of a package, which would require doing a `git clone` instead of downloading.
Expressly sets the `--prefer-dist` flag when running `composer install`, so that we're always downloading tarballs instead of potentially doing git clones (which can be expensive).

[Feature:Install] Use prefer-dist flag for composer install

---

site/public/js/userform.js

The form modal opened by the `New Student` button keeps the data filled by the auto-completion feature even after hitting `Close` button 
Similarly, the `New Grader` form modal is storing the previous user's information.
The state of form is being reset on close event. Closes #4991

[Bugfix:InstructorUI] Add user modal does not clear on close

---

site/public/js/drag-and-drop.js

I believe this meets the requirements.
Fixes #5117 
When a student makes a submission that is late and within the number of allowed late days, but is not being charged any late days, it does not ask for permission first; the resource it is asking permission to use is already consumed.
I tested this manually on a local machine.

[Bugfix:Submission] unnecessary 0 late days message

---

site/app/libraries/Core.php
site/app/libraries/NotificationFactory.php
site/phpstan-baseline.neon

Lifts a refactor from #4329, moving NotificationFactory to a more appropriate place for it as it generates models, though it is not itself a model.

[Refactor:PHP] Move NotificationFactory to app/libraries namespace

---

site/app/models/User.php
site/tests/app/models/UserTester.php

In PHP 7.4, `password_get_info` function changed on what it returns when passing it an unhashed password. Instead of `algo` being `0`, it would now be `null`.
Fixes the regression on PHP 7.4 (tested locally), while retaining backwards compatibility with previous versions of PHP.
The unit tests here are sufficient to ensure correctness.

[Bugfix:User] Fix regression in PHP 7.4 when passing string to setPassword

---

.travis.yml

We were running the full E2E tests twice per PHP version, just changing the login method, which caused a lot of wasted time spinning up the environment, and such.
We create one E2E suite per PHP version, and just toggle the authentication method and re-run the test_login.py file, ensuring that both login methods work as expected, while only running the rest of the suite once (and only having to do the rest of VM setup once per version).

[Testing:Travis] Simplify and speed-up running the e2e matrix

---

site/app/templates/GlobalHeader.twig
site/app/templates/admin/UploadWrapperForm.twig
site/app/templates/grading/electronic/SubmissionPanel.twig
site/app/templates/misc/SourceSettings.twig
site/app/views/forum/ForumThreadView.php
site/public/css/admin-gradeable.css
site/public/css/colors.css
site/public/css/forum.css
site/public/css/global.css
site/public/css/server.css
site/public/css/sidebar.css
site/public/js/server.js
site/public/js/ta-grading.js

If an instructor uses custom css the dark mode may have broken some of their css.
The submitty logo may have become very large 
as well as if they use a light background, the sidebar buttons might be very hard to see when in dark mode
This also fixes an issue where when a user's device defaults them to dark theme (usually on phones with a system wide dark theme) the checkbox to choose the theme is inverted until they click it and refresh the page.
This fixes the issues listed above.

[Bugfix:InstructorUI] fix bugs in dark theme

---

site/tests/app/models/ConfigTester.php

`expectExceptionMessageRegExp` is deprecated in PHPUnit 8, and will be removed in PHPUnit 9.
Use the recommended `expectExceptionMessageMatches` method instead.

[Refactor:PHP] Switch off deprecated phpunit function

---

site/app/templates/forum/CreatePost.twig

Aphacker does not have a history and therefore split post does not appear.
Split post now appears for the aphacker post.

[Bugfix:Forum] Split post button w/o edit history

---

site/app/templates/grading/electronic/Status.twig

Currently, we can use only integer numbers as the bucket size.
Closes #5084 
Allows floating-point numbers to be used as the bucket size which can be helpful for gradeables with small range of numbers.

[TAGrading] Allow float number in bucket size

---

site/app/libraries/database/AbstractDatabase.php
site/app/libraries/database/DatabaseQueries.php
site/tests/app/libraries/database/AbstractDatabaseTester.php

When you want to add a bool or a date to a sql query, you have to convert it to the correct format first before adding it to the parameter array.
The code now auto converts bools and dates, when added to the parameter array, to the correct format
fixes #5211
I only made it auto convert bools and dates however, if there are other types that need to be converted that I do not know about let me know and I can add them.

[Feature:Developer] convert bools & dates to correct sql

---

.travis.yml

We currently use selenium 3.141.0 pypi release.
The selenium 4.0.0a5 has a number of nice improvements to it, fixing a handful of stability issues that we've seen on Travis.

[Testing:Travis] Use pre-release selenium 4.0.0 for E2E tests

---

site/app/libraries/FileUtils.php
site/app/libraries/Utils.php
site/app/models/gradeable/AutogradingConfig.php
site/app/models/gradeable/SubmissionCodeBox.php
site/app/templates/submission/homework/SubmitBox.twig
site/app/views/AutoGradingView.php
site/app/views/submission/HomeworkView.php
site/phpstan-baseline.neon
site/tests/app/libraries/FileUtilsTester.php
site/tests/app/libraries/UtilsTester.php

Closes #5256
The notebook codebox was not properly doing syntax coloring for most languages that we might support there. For example:
Gets syntax highlighting to work given a programming language that instructors might type in (e.g. `C++`).
For example:
Technically breaks using `clike` as a programming language, but given that we show the programming language to the student as a title on the textarea, I am not sure why an instructor would ever want to use that over `C++` or `Java` or whatever.

[Bugfix:Submission] Fix programming language coloring not working for notebooks

---

site/public/css/sidebar.css

When the sidebar is small, the page content overlaps with the sidebar making it hard to click the buttons 
closes #5269
Reverted a change so that the sidebar has a higher z-index so that it is always on top of the page content. This means that all clicks will click on the sidebar instead of the margin of the page content

[Bugfix:InstructorUI] Page content no longer overlaps with sidebar

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/views/grading/ElectronicGraderView.php

The status page for a peer student grader will show 1/1 100% if one student is peer graded, even if more need to be graded.
Fixes #5235. Now thes status page for stuent peer graders will show the proper number of graded students

[Bugfix:TAGrading] Peer Status Page fix

---

site/app/models/Notification.php

Typehint for notification model was incorrect, where it indicated it only returned string, but could return null as well. This is shown in #5267.
Fixes the typehint for the function, as well as adding typehints for a handful of other functions.

[Refactor:PHP] Fix function typehinting in Notification model

---

site/app/libraries/database/DatabaseQueries.php
site/app/views/NavigationView.php

Peer team rotating section assignments will produce a robot when a student tries to grade them.
Students can see all peer assignments in the navigation menu if they are assigned to grade one peer assignment
Fixes these errors: peer team rotatin section assignments can be graded properly, students can only see gradeables they are assigned to grade in the navigation menu.

[Bugfix:TAgrading] Peer grading team interface fixes

---

site/app/controllers/GlobalController.php
site/app/controllers/admin/PlagiarismController.php
site/app/controllers/grading/ElectronicGraderController.php
site/app/controllers/grading/ImagesController.php
site/tests/ruleset.xml

Fixes the following style errors:
- Squiz.PHP.NonExecutableCode.ReturnNotRequired (do not have a blank return at the end of a function)
- SlevomatCodingStandard.Namespaces.UseDoesNotStartWithBackslash.UseStartsWithBackslash (Do not do `use \Class\Name`, rather `use Class\Name` at top of file)
- SlevomatCodingStandard.Namespaces.UnusedUses.MismatchingCaseSensitivity (`Fileutils` != `FileUtils`)
- SlevomatCodingStandard.PHP.UselessSemicolon.UselessSemicolon (`print('test');;` would error on second semi-colon).
Tested locally via phpcs, and Travis as well will test it.

[Refactor:PHP] Fix a handful of code style errors

---

site/app/models/GradeableAutocheck.php
site/app/templates/autograding/AutoChecks.twig
site/public/js/server.js

Newlines were converted to ```<br/>```, but were then escaped and displayed in a gradeable autocheck message. Other html elements were escaped as well, but were  displayed in their escaped form.
Newlines are converted to ```<br/>```, and are then properly interpreted as html, allowing newlines to be added to autocheck messages. Other html elements are properly escaped and displayed.
Before:
After:

[Feature:Autograding] Allow newlines in autocheck messages

---

site/app/libraries/database/DatabaseQueries.php
site/app/models/gradeable/Gradeable.php

When a student tries to grade a team assignment with peer components with Rotation Sections, they will get a robot after clicking the team they want to grade
They will be able to grade the student as normal
Fixes #5278

[BugFix:TAGrading] Peer teams rotation sections fix

---

site/app/views/submission/HomeworkView.php
site/tests/ruleset.xml

Fixes all `Squiz.Arrays.ArrayBracketSpacing` style errors, which is that you should not write `$array[ 0 ];`, rather just `$array[0];`.

[Refactor:PHP] Fix ArrayBracketSpacing style errors

---

autograder/autograder/autograding_utils.py

This PR makes certain that the results json created by ```main_validator``` is utf-8 encoded by reading and re-writing the file during archival. Non utf-8 characters are stripped when reading the file.

[Bugfix:Autograding] Ensure results json is utf8 encoded

---

autograder/autograder/autograding_utils.py

This PR moves python custom validator output from ```results/``` to ```results/custom_validator_output```.
closes #5301

[Feature:Autograding] Move python custom validator output

---

site/public/css/admin-gradeable.css
site/public/templates/grading/EditGradeable.twig

Up until now, Peer grading has had a warning associated with the introduction of a new component. This PR removes this warning now that necessary peer grading features are in place.
The button color has been set to plum to match the peer grading UI throughout the system. Image included below.

[Feature:TAGrading] Remove warnings from peer grading

---

.travis.yml
site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
site/app/templates/grading/electronic/PeerPanel.twig
site/app/templates/grading/electronic/PeerResultsPanel.twig
site/app/templates/grading/electronic/RubricPanel.twig
site/public/templates/grading/OverallComment.twig

Travis is failing after merging #5154 due to changes from #5125 which inserted a usage of `<script type='text/javascript'>`.
Removes the `type='text/javascript'`  from the script tag as it's implied by default if the `type` is omitted. Also removes a `type='application/javascript'` as it's also unnecessary, though not necessarily a VPAT/W3C error.

[VPAT] Remove unnecessary type from script tags

---

site/app/models/gradeable/GradeableList.php

We use the `@` to suppress errors on this `uasort` as it would issue them when running under phpunit in PHP <7. 
Given that we're now PHP 7.2+ only, it's safe to remove, and makes our codebase a bit better as we should never be using the `@`.

[Refactor:PHP] Remove PHP 5.6 testing shim

---

site/app/templates/grading/SettingsForm.twig
site/app/templates/grading/simple/Display.twig
site/app/templates/grading/simple/StatisticsForm.twig
site/public/css/colors.css
site/public/templates/grading/settings/HotkeyList.twig

The numeric grading page had a large number of WAVE errors
http://localhost:1501/s20/sample/gradeable/future_tas_test/grading?view=all
This pr fixes all the wave errors

[VPAT] Fix wave errors on numeric grading page

---

site/app/templates/grading/simple/StatisticsForm.twig
site/app/views/grading/SimpleGraderView.php
site/public/css/server.css

In looking at #5314, there were a number of issues with how the tables were defined that while not a violation of WAVE/W3C, were still not good design. This was things like having each row in a table have its own `<tbody>` and defining a table with one row using `<th>`.
Better defines the HTML in a more logical fashion, such that the tables have one tbody that go around the entire data, and that the single row tables with just a header are now constructed using divs.
There was a bug in the filter such that it was not properly filtering out the null section (key, value pair is reversed for filter tag in Twig) and so there was an extra empty row at the bottom of the first table. This is fixed in this PR as well. Additionally, the array key for the null section is the empty string (`$a[null] …

[UI/UX:TAGrading] Improve styling for statistics table for simple gradeables

---

autograder/autograder/execution_environments/secure_execution_environment.py
autograder/autograder/packer_unpacker.py
bin/make_generated_output.py

After a recent change a number of new files were being copied in while autograding (e.g. ```user_assignment_access.json```).  However, autograding crashed when these files did not exist, as is the case when generating random input/and expected output files. 
This PR adds logic so that a crash does not occur when these files do not exist.

[Bugfix:Autograding] Fix random input/output

---

SECURITY.md

The form listing our details about security / vulnerability was named `VULNERABILITY_DISCLOSURE_POLICY.md`, which GitHub does not pick up in the "Security" tab.
Renames the file to `SECURITY.md` which will appear under the Security tab. Additionally, cleans up the language a bit for what we care about as it was a bit overly narrow as we've grown.

[Documentation] Rename vulnerability policy to SECURITY.md

---

site/tests/BaseUnitTest.php
site/tests/app/controllers/admin/GradeOverrideControllerTester.php
site/tests/app/models/ConfigTester.php

4 tests used a deprecate phpunit function `expectExceptionMessageRegExp` which will be removed in a future version of phpunit. 1 test did not assert anything.
Updates the 4 functions to use `expectExceptionMessageMatches` which is not deprecated and adds proper asserts to the one test.

[Testing] Fix phpunit warnings for 4 tests

---

.travis.yml

Download for Clang 6.0.0 is failing as the site is returning a 503 error (true for attempting to manually download it as well).
Test using this version of clang is disabled for now.

[Testing:Travis] Disable clang 6.0.0 tests for now

---

site/public/css/server.css

When going to the login page under dark mode, the password input box had a white background with white text color, making it kind of hard to use.
Password input box has a dark background.
I moved the place where the background for certain inputs was defined to the same place as the text color was defined. Given that each of these input types here are all text inputs (with special behavior), it's not clear why there was this differentiation, though there might have been a set reason for it.

[UI/UX] Fix password field having white background in dark mode

---

tests/e2e/base_testcase.py
tests/e2e/test_forum.py
tests/e2e/test_grade_inquiry.py
tests/e2e/test_login.py
tests/e2e/test_navigation_page_non_student.py
tests/e2e/test_navigation_page_student.py
tests/e2e/test_office_hours_queue.py
tests/e2e/test_sidebar.py
tests/e2e/test_simple_grader.py
tests/e2e/test_submission.py

The `find_element_by_*` and `find_elements_by_*` functions were deprecated in selenium 4. These methods were shortcuts over the `find_element` and `find_elements` methods.
This PR removes them in-favor of the supported and recommended method.

[Testing] Refactor e2e tests to not use deprecated functions

---

site/app/templates/forum/MergeThreadsForm.twig
site/public/js/drag-and-drop.js
site/public/js/grade-inquiry.js
site/public/js/plagiarism.js

Usage of positionals (e.g. `:first`, `:eq`, `:last`) in jQuery selectors is deprecated in jQuery 3.x, and will be removed in jQuery 4.
Uses the built-in jQuery positional functions instead that provide same behavior in our cases, while also being faster to execute, and not being deprecated.

[Refactor:JS] Remove usage of deprecated jQuery positional selectors

---

site/app/templates/forum/ThreadPostForm.twig
site/public/js/grade-inquiry.js

jQuery.trim is deprecated in jQuery 3.5.0, as [`String.prototype.trim`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) exists and is supported basically everywhere.
Use `String.prototype.trim` instead of `jQuery.trim`.

[Refactor:JS] Remove usage of deprecated jQuery.trim

---

tests/e2e/base_testcase.py

Travis-Ci has been flaky where it fairly consistently fails the E2E test suite due to Chrome crashing.
This attempts to fix that by setting the `--no-sandbox` flag which makes it run a bit leaner, and to use a for loop around intitalizing the the driver to attempt a few times before finally surfacing the exception thrown, where hopefully on a second (or third or...) try, Chrome will successfully start up.

[Testing:E2E] Attempt to start Chrome several times before throwing exception

---

site/app/templates/forum/CreatePost.twig

Split post button can show up for students, who do not have access to it (it prints an error when pressing it) 
Split post button no longer shows up for students
Tested by logging into a user with permission and a user without permission, and comparing before and after making changes.

[Bugfix:Forum] Stop split post button from showing up when it shouldn't

---

site/app/views/forum/ForumThreadView.php

Fixes #5334
Search results have overlap between `Back To Threads` and `Create Thread` button
Buttons are now properly spaced

[Bugfix: Discussion Forum] Fixes button overlap for search results

---

sbin/create_term.sh

Fixing the error-message when using create_term.sh with not exactly 4 arguments because the stated correct usage was incorrect.
Fixes #5360

[Bugfix:System] Fix program name in help message of create_term.sh

---

.setup/install_submitty/install_site_dev.sh
.setup/install_submitty/install_site_prod.sh
LICENSE-THIRD-PARTY.md
site/app/controllers/admin/AdminGradeableController.php
site/package-lock.json
site/package.json

jquery-ui-timepicker-addon was an older timepicker plugin we used to use before flatpickr.
Removes the timepicker dependency as it's no longer used anywhere.

[Refactor:System] Remove unused jquery-timepicker plugin

---

site/app/controllers/pdf/PDFController.php

A peer grader cannot view a pdf submitted by a peer they are assigned to grade (get a permissions error)
The peer grader can view the pdf. Closes #5234

[Bugfix:TAGrading] peer grader pdf permissions fix

---

site/app/models/Team.php
site/app/templates/grading/electronic/Details.twig

Closes #5331 
Currently, on the Grade Details page of a team assignment (go to grade --> grading index) the order in which Team Members are listed sometimes don't match the order of their corresponding Viewed Grade checkmarks which are ordered by username.
Now the team member names should be listed based on lexicographical order of the members' usernames.
I wasn't able to recreate the bug on my VM. I tried changing the legal and preferred names of Alyssa P Hacker to be Zalyssa P Zhacker and she still appeared to be listed first (as she should be by her username aphacker). In addition, I made it so that Alyssa did not create the team (Rachel Crona did), and Alyssa is still listed first.

[BugFix:TAGrading] Team Gradeable Viewed Grade Checkmarks

---

site/public/css/gradeable-notebook.css

Closes #4381
Some issues relating to notebook gradeable formatting outlined in #4381
Notebook gradeable CSS has been cleaned up a bit to add vertical space where it is needed.  Instructors shouldn't need to add 'alignment' spaces when constructing multi-line code multiple choice options.
Tested using Lesson 1 and Lesson 3 of the CPP crash course.

Fix notebook markdown rendering issues

---

site/app/templates/GlobalHeader.twig
site/app/templates/HomePage.twig
site/app/templates/NotificationSettings.twig
site/app/templates/autograding/AutoResults.twig
site/public/css/bootstrap.css
site/public/css/colors.css
site/public/css/fileinput.css
site/public/css/forum.css
site/public/css/homepage.css
site/public/css/notifications.css
site/public/css/server.css
site/public/css/ta-grading.css
site/public/js/server.js

There are a number of issues with dark mode.
Based on user feedback I switched the check-boxes to enable dark mode to a dropdown.
The dropdown has a number of options including allowing Submitty to follow the device theme. (This mostly shows up on phones where they are light theme for half the day and dark theme at night)
I also removed a number of shadows across the the website (only in dark mode) which looks a lot better overall.
This is what it used to look like
White buttons are no longer white and are instead a less bright color
Text at the top of the office hours queue is now white on blue instead of black on blue which was hard to read

[UI/UX] Improved a number of pages when in dark mode

---

site/app/controllers/admin/ReportController.php
site/app/templates/admin/Report.twig
site/app/views/admin/ReportView.php
site/public/css/grade-report.css

Currenlty the page layout breaks on smaller screen devices...
Added responsiveness and now the page looks like this
Involves a little code refactoring also as I scrapped out the table layout plus inline styling in the report page and created a different CSS file for styling.

[UI:Mobile] Add mobile screen view for the grade-report page 

---

site/app/templates/admin/RainbowCustomization.twig
tests/e2e/accessibility_baseline.json
tests/e2e/test_accessibility.py

There is one large test that checks every page on Submitty for accessibility errors. This can make it hard to debug an issue.
fixes #5304 
This pr splits each page into its own subtest
I also simplified the accessibility_baseline.json as well as what the program actually outputs when it finds an error
I also fixed one very minor issue in RainbowCustomization.twig which was breaking this test
Here is an example of what the new output looks like. Note how the url is part of the test, as well as it lists what the error is, the html that caused the error, and the type of error. The test also provides links at the bottom which can help with debugging the error.

[Testing:InstructorUI] Split accessibility test into subtests

---

site/app/controllers/AuthenticationController.php
site/public/index.php

Submitty has the chance of redirecting users to other domains when they log in.
Submitty could be put into an iframe to trick users into giving their passwords to another website
Redirects now always check that the url they are redirecting to on login comes from submitty's domain
The Submitty login page will no longer work in an iframe
fixes #5265
fixes #5264
To test:
Log out of submitty 
make an html file with the content of this issue #5264 
the page should not work
then go to this url http://localhost:1501/authentication/login?old=https://duck.com and log in
it should not redirect to duck.com and just go to the main submitty homepage

 [Bugfix:InstructorUI] Stops submitty from being used in iframe and stops external domain redirects on login

---

site/public/index.php

Because of how files are viewed when grading a student, they use iframes which were disabled in #5375 
This makes it so that iframes can be used on the same origin meaning that the iframs to view student files will now work again

[Bugfix:TAGrading] Fix bug where graders cannot view a students files

---

site/app/templates/HomePage.twig
site/app/templates/admin/Configuration.twig
site/app/templates/admin/Extensions.twig
site/app/templates/admin/users/StudentList.twig
site/app/templates/forum/StatPage.twig
site/app/templates/forum/ThreadPostForm.twig
site/app/templates/submission/Team.twig
site/app/views/admin/PlagiarismView.php
site/app/views/grading/ElectronicGraderView.php
site/public/js/extensions.js
site/public/js/homepage.js
tests/e2e/accessibility_baseline.json
tests/e2e/test_accessibility.py

There a still some wave errors on the website
The goal of this PR is to get rid of some of the last remaining WAVE errors.
Sorry that there is really no organization to this PR and it is from a bunch of different pages. I thought it was better to do it all in this pr than make a ton of small ones.
My goal is that after this pr, there will be no wave errors on the website and and the only wave alerts will be `Skipped heading level` and `Noscript element` which as far as I can tell, are fine. If they are not fine we are going to have to go back and fix them.
There are some slight caveats to this claim that there are no more WAVE errors:
1) #5435 should deal with all device dependent event handlers so I did not remove them here
2) I am still working on a large number of changes for the …

[VPAT] Fixed a number of WAVE errors across the website

---

site/app/templates/forum/SplitPostForm.twig
site/app/templates/forum/ThreadPostForm.twig
site/app/templates/generic/Popup.twig
site/public/js/directory.js
site/public/js/forum.js
site/public/js/server.js
site/public/js/simple-grading.js
site/public/js/ta-grading-keymap.js
site/public/js/userform.js

On many modals when you use tab to move among elements, you can escape the modal and tab on elements behind the modal on the main page
fixes #3830
when you press tab from the last element in a modal instead of cycling to the page behind the modal, it will move the focus back to the first item
I also made it so that the captureTabInModal() function runs automatically as long as a modal is generated with Popup.twig (which as far as I can tell they all are)
This will mean going forward no extra work should need to be done when making a new modal.
There is still one situation captureTabInModal() will need to be run manually. If a modal disables the submit button for any reason, the function must be run every time the state of the submit button is changed. (so both when it is disabled as well …

[VPAT] Stop tabbing from escaping modals

---

site/app/templates/officeHoursQueue/CurrentQueue.twig

If the info put into the contact info box is too large, the office hours queue page will expand sideways to fit it
(it keeps on going to the right)
The contact info will now wrap to a new line when too long

[Bugfix:InstructorUI] Office Hours Queue contact info will now wrap to the next line when too long

---

sbin/send_email.py

Fixes #5402 
The send email script would construct the mail client (which requires the username / password, etc.) before checking if email was enabled. The script would crash on setting up the mail client as email was not configured as it's not enabled.
Check to see if email is enabled before doing any other email related steps (create DB connection, etc.). Secondly, if we have no emails to send, do not bother setting up the email client.

[Bugfix:System] Do not construct mail client if email disabled

---

site/app/templates/generic/Popup.twig

Every popup made using the popup.twig file would cause 2 WAVE `Device dependent event handler` errors. 
I do not believe either of theses onclick attributes even has a use anything anymore, they are just there from old code and currently do nothing. So I just removed them. For whoever tests this, if you are able to find a change in page functionality by removing them please let me know but I dont think there is any.

[VPAT] Removed device dependent event handlers from popups

---

sbin/submitty_autograding_shipper.py

The debug print statement "no available job" was switched to a log statement in a recent PR #4745.  This is cluttering the logs, switch back to simple print statement that only appears when manually running this script.

[Bugfix:Autograding] don't log "no available job"

---

site/app/templates/course/UploadCourseMaterialsForm.twig
site/app/templates/grading/UploadImagesForm.twig

You cannot use the file input boxes in modals when just tabbing. see #5446
fixes #5446
you are now able to tab to file input boxes and if you press enter it will open the file input box
The issue before was that the file input is hidden and what the user clicks on is actually a label for that input. However, the captureInModal() function only detects visible inputs because otherwise you would get stuff like the csrf token. The best solution I could think of was just to make that label able to be tabbed to in the 2 places I found it on the website. This allows the captureInModal() function to detect it.

[VAPT] Tabbing now works for file input in modals

---

site/public/js/ta-grading-rubric.js

On the instructor rubric page, if an instructor clicks on the link to view all students who recieved a given mark, the link will direct to the instructor rubric page (the link is broken)
Fixes #5261. The who got what mark links work as intended

[Bugfix:TAGrading] "who got this mark" links

---

autograder/autograder/execution_environments/container_network.py
autograder/autograder/execution_environments/rlimit_utils.py

Closes #5428 
Docker container creation fails for assignments which set an `RLIMIT` to the submitty specific macro `RLIM_INFINITY`. 
`RLIM_INFINITY` is now respected when grading via docker.
*  Docker containers are not limited by default. As a result, not setting a `ulimit` on a container where `RLIM_INFINITY` has been requested should be roughly equivalent to setting the value to `18446744073709551615` as in the Submitty `C++` grading code.
*  This PR also fixes two calls to the non-existent function `self.log` that snuck into `container_network`.

[Bugfix:Autograding] Handle RLIM_INFINITY when limiting docker containers

---

Vagrantfile

Someone using VMWare will probably end up with a VM with different amount of RAM / CPUs than VirtualBox, which may lead to subtle differences / bugs that we do not want to worry about.
Minimally set the memory and cpu for vmware to match VirtualBox. This does not imply we are offering official support of using VMWare to develop at this time, just doing the minimum though of keeping the two consistent, and this setting has been consistent now for years.

[Feature:Vagrant] Set memsize and cpus for VMWare to match VirtualBox

---

.setup/bin/versions.sh
grading/execute.cpp
grading/load_config_json.cpp

This PR:
1. Adds a ```dispatched_actions.txt``` file per container (or one for a jailed sandbox) when autograding. This file contains the timestamped dispatcher actions taken against the student's code.
2. Changes timestamping from ```%m/%d/%y %T``` to ```%Y/%m/%d %T``` to allow simple  lexicographical sorting.
For discussion: right now there are three "signals" that an instructor can send to a student process, "stop," "start," and "kill." Internally, these are represented by the strings ```SUBMITTY_SIGNAL:STOP```, ```SUBMITTY_SIGNAL:START```, and ```SUBMITTY_SIGNAL:KILL```. Additionally, there is a ```SUBMITTY_SIGNAL:FINALMESSAGE```, which is always the last message sent by the dispatcher.
In its current state, this PR exposes these strings to the student/instructor, as it adds them to …

[Feature:Autograding] Log dispatched actions for a submission

---

site/app/views/submission/HomeworkView.php

Closes #5224 
The number of overall points available was improperly displayed when a gradeable had visible hidden testcases (hidden testcases weren't taken into account).
Overall total points available are now properly displayed.

[Bugfix:Submission] Fix available total display for hidden testcases

---

site/app/controllers/DockerInterfaceController.php
site/app/controllers/OfficeHoursQueueController.php
site/app/controllers/grading/ElectronicGraderController.php
site/app/controllers/student/SubmissionController.php
site/app/libraries/Core.php
site/app/libraries/ErrorMessages.php
site/app/libraries/Utils.php
site/app/libraries/database/DatabaseQueries.php
site/app/libraries/routers/AccessControl.php
site/app/libraries/routers/FeatureFlag.php
site/app/models/Breadcrumb.php
site/app/models/Button.php
site/app/models/Config.php
site/app/models/Course.php
site/app/models/CourseMaterial.php
site/app/models/OfficeHoursQueueModel.php
site/app/models/Team.php
site/app/models/notebook/Notebook.php
site/app/models/notebook/UserSpecificNotebook.php
site/app/views/NavigationView.php
site/app/views/forum/ForumThreadView.php
site/app/views/submission/HomeworkView.php
site/app/views/submission/TeamView.php
site/tests/app/controllers/course/CourseMaterialsControllerTester.php
site/tests/ruleset.xml

We were not linting for the style of doc comments with regards to the alignment. This has lead to a number of doc comments that have inconsistent styling.
All PHP doc comments have been updated to use the same styling, which is the standard of how to do doc comments across languages, namely:
```php
/**
* function desc
* @param string foo
*/
function bar(foo);
```
where the `*` of each line aligns with the first `*` of the opening comment. Additionally, I've activated the `Squiz.Commenting.DocCommentAlignment` rules to enforce this style.

[Refactor:PHP] Fix styling of doc comments to be proper

---

site/app/templates/notebook/Notebook.twig

For cells that had the `random_order` option enabled, a `1` would appear above it. This represents the boolean true for `random_order`, and looks like it was used for debugging from #5380.
The `1` no longer appears.

[Bugfix:Notebook] Remove stray 1 above randomized cells

---

site/app/controllers/NotificationController.php
site/app/controllers/admin/ConfigurationController.php
site/app/controllers/forum/ForumController2.php
site/app/controllers/grading/ElectronicGraderController.php
site/app/libraries/DiffViewer.php
site/app/libraries/database/DatabaseQueries.php
site/app/libraries/database/PostgresqlDatabase.php
site/app/models/Config.php
site/tests/ruleset.xml

Number of places used useless ternary operators. They are roughly of the form `$var === true ? true : false`, where keeping just the condition gives the same effect.
Removes the useless ternary operators, and adds a lint rule to prevent them.

[Refactor:PHP] Remove useless ternary operators

---

site/app/controllers/admin/AdminGradeableController.php
site/app/libraries/database/DatabaseQueries.php

Selecting "Should grade inquiries be associated with a specific component of the rubric?" does not work on Gradeable creation. It does work on updating a Gradeable.
The option works on gradeable creation.

[Bugfix:InstructorUI] Fix not being able to set regrade per component on gradeable creation

---

site/app/libraries/routers/FeatureFlag.php
site/tests/app/libraries/routers/FeatureFlagTester.php

The FeatureFlag annotation class did not have any direct tests.
Adds direct testing of the FeatureFlag class.

[Testing:PHP] Add tests for FeatureFlag class

---

site/tests/app/libraries/UtilsTester.php

The Docker UI caused a changed to the formatBytes to properly display docker image sizes that were human-readable,
in order to get it merged quickly the test was not added in that PR.
Adds test for optional parameter.

[Testing:PHP] Add tests for optional round parameter in Utils::formatBytes

---

site/public/js/rainbow-customization.js

Fixes an issue on the rainbow grades webUI page where users saw ```Status: TypeError: $(...).find(...)[0] is undefined``` when attempting to save their selections.

[Bugfix:InstructorUI] RG WebUI bugfix

---

.setup/travis/check_wip.py
.travis.yml

PRs that are marked as drafts, but do not have the `[WIP]` tag still go through the entire PR build process. This check was added back before GitHub supported pull requests drafts.
Fails PR builds if they are marked as drafts or WIP.

[Testing:Travis] Do not complete full build pipeline for draft PRs

---

site/app/libraries/CascadingIterator.php
site/phpstan-baseline.neon

There was an ignored phpstan static analysis error in CascadingIterator. This error was renamed in a recent phpstan version causing #5504 to fail.
The static analysis error is fixed. Once merged, #5504 should pass.

[Refactor:PHP] Fix static analysis error in CascadingIterator

---

site/app/libraries/NumberUtils.php
site/app/templates/notebook/Notebook.twig
site/app/views/submission/HomeworkView.php
site/tests/app/libraries/NumbersUtilsTester.php

NumberUtils included two non-static functions, to be used within a twig template within a class instantiation of NumberUtils. One of the functions also just returns the array keys of an array.
Gets rid of the array keys function in favor of the builtin [`keys`](https://twig.symfony.com/doc/3.x/filters/keys.html) filter. The other function was made static, and then uses an anonymous class instantation to pass it into twig to allow it to be used the same as before. Tests were also added for the function.
We should be trying to create and use PHP models to pass into the templates, and not passing in arrays of scalar values wherever possible, so that we might have a `notebook.getCells()` method that returns a `Cell` model, and then internal to that model, it would call NumberUtils.

[Refactor:PHP] getRandomIndices now static method

---

site/app/models/Config.php
site/tests/app/libraries/DateUtilsTester.php

Couple of the functions added in #5400, #5473 did not have tests. Some of the tests added in #5473 could be simplified using data providers (https://submitty.org/developer/testing/php_unit_tests#parameterized-php-unit-tests).
All functions are now tested, and use data providers as makes sense, namely condensing the four testcases in #5473.

[Testing:PHP] Simplify and add tests to DateUtilsTester

---

python_submitty_utils/submitty_utils/dateutils.py
python_submitty_utils/tests/test_dateutils.py

The dateutils.parse_datetime function is documented as handling a string of the format "2018-10-23", but attempting to do so would throw an exception. This is due to #1232 breaking the regex to recognize that format.
Fixes the function to allow that style of date. It also expands allowed formats to allow "2018-10-23 10:23:20" again (without timezone), but will attach the local timezone to it.

[Bugfix:SubmittyUtils] Fix parse_datetime not handling dates and times without timezone

---

site/public/js/pdf/PDFInitToolbar.js

The pdf Annotation toolbar will not load properly when a pdf is selected to annotation
The pdf Annotation toolbar loads as expected

[Bugfix:TAGrading] PDF annotation toolbar fix

---

.flake8

Increase flake8's `max-line-length` from 88 characters to 100.

[Feature:Developer] Increase python linter's max-line-length to 100 characters

---

site/tests/app/models/NotificationTester.php

Adds testscases for Notifcation model and partially solves #5495 
I faced problem finding out the dateTimeFormat for 'notification' and it is used `getNotifyTime` method as `$this->core->getConfig()->getDateTimeFormat()->getFormat('notification')`. Although I have used this format 'n/d g:i A' and it worked.

[Testing:Notification] Add testcases for Notification model

---

python_submitty_utils/tests/data/complete_configs/choice_of_language.json
python_submitty_utils/tests/data/complete_configs/cpp_hidden_tests.json
python_submitty_utils/tests/data/complete_configs/minimal_code_editing.json
python_submitty_utils/tests/data/complete_configs/notebook_basic.json
python_submitty_utils/tests/data/complete_configs/notebook_itempool_random.json
python_submitty_utils/tests/data/complete_configs/python_multipart_static_analysis.json
python_submitty_utils/tests/data/complete_configs/tutorial_10_java_coverage.json
python_submitty_utils/tests/data/complete_configs/tutorial_12_system_calls.json
python_submitty_utils/tests/data/complete_configs/tutorial_16_docker_network_python.json
python_submitty_utils/tests/test_submitty_schema_validator.py

We do not perform unit tests for the schema validator within submitty_utils python package, doing it indirectly within the integration test suite.
Adds some basic testing of the schema validation function. Currently, we do not do any validation of docker networks as our own tutorial for it fails validation (see #5531).

[Testing:SubmittyUtils] Add testcases for schema validation

---

.travis.yml

A long while ago (3-4+ years ago?), we used pylint (and pylint_runner) to partially lint parts of the codebase. We have since moved to flake8.
Removes the unused pylint_runner dependency as we do not need it anymore.

[Testing:Travis] Remove unused pylint_runner pip dependency

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/templates/grading/electronic/Details.twig
site/public/css/server.css

"Stoplights" for non-peer components from peers on the grading index page can be viewed by students
"Stoplights" for non-peer components from peers on the grading index page are hidden to students.

[BugFix:TAGrading] Add Fix for StopLights for Peer View

---

site/app/controllers/MiscController.php
site/app/templates/grading/electronic/SubmissionPanel.twig
site/public/js/server.js

Attempting to click "Download Zip" of a student's submission causes the server to throw an exception. This is due to a missing `is_anon` parameter on the download_zip route.
The download zip button works as expected. #5412 added a new required parameter, `is_anon`, to the download_zip path (though implementation was such that most of the links except for the one instance where `is_anon == true` were broken). #5241 reverted the JS function to no longer use the `is_anon` parameter in the JS code, but not in the controller, which then caused exception to be thrown. The `is_anon` parameter is re-added, though at the end of the parameter list instead of the middle as most usages of the function do not use it.
I made version non-optional as it's always provided (or should be) to the method, and …

[Bugfix:TAGrading] download submission zip

---

site/app/libraries/response/MultiResponse.php

The methods are used, and without any indication within the codebase they should be ignored (though https://submitty.org/developer/router#what-is-the-responseinterface-object-is-it-required discusses what to return). #5206 discusses the rationale for this.
Adds a `@deprecated` tag to these functions, with an expectation that they will be removed from the codebase in follow-up PRs.
@shailpatels Since there's the push to have two pages on the subject, please update https://submitty.org/developer/development_instructions/router-response#the-multiresponse-object and following sections to fit this defined behavior

[Refactor:Router] Mark MultiResponse::only* deprecated

---

site/app/models/gradeable/Gradeable.php

Received reports of gradeable code not working when using VCS gradeables.
Added check to test if $this->core->getUser() returns null and then sets time zone appropriately before continuing.

[Bugfix:Submission] Datetime fix when using VCS gradeable

---

bin/make_generated_output.py
python_submitty_utils/submitty_utils/dateutils.py
python_submitty_utils/tests/test_dateutils.py
sbin/submitty_autograding_shipper.py
sbin/submitty_autograding_worker.py

When using `submitty_utils.dateutils.write_submitty_date`, there were a couple things that were inconsistent on usage.
1. If you passed in an invalid type, it would print an error to console, and then return the value. This could lead to poor behavior if we have a poor type to enter into the system and have things crash later in a different subsystem of autograding.
2. There was an extra space between the milliseconds and timezone as opposed to when we do not have the milliseconds (e.g. `.1234 -0400` vs `.1234-0400`). Given that we (and everyone else?) use the non-space variant elsewhere throughout the codebase, I removed the space.
3. The optional parameter to add milliseconds to the written out datetime string was named `microseconds`. This renames it to actually match what you're …

[Refactor:SubmittyUtils] Cleanup dateutils.write_submitty_date to be more consistent

---

site/app/models/notebook/Notebook.php

If an instructor creates and builds a notebook gradeable that has no inputs (for example all cells were markdown) then a PHP Warning is shown when viewing the submission page.
Resolved this issue.

[Bugfix:Submission] Fix uninitialized notebook object property

---

site/app/models/notebook/UserSpecificNotebook.php

Closes #5597
If an instructor creates an notebook itempool gradeable but doesn't define a `testcases` array inside each `item` block then the build process completes successfully but PHP throws an error when attempting to view the submission page for the gradeable.
The PHP error have been resolved.
Tested by removing `testcases` fields from some itempool items in the development course 'notebook itempool' gradeable, rebuilding and testing.

[Bugfix:Submission] Fix PHP error on no testcase for itempool item

---

tests/git_test.sh

The git test hardcodes `s20` in the expected output. It now fails as July 1st marks the start of `f20` for generated courses.
The git test now uses a dynamically generated semester for the output, so that it does not fail when the semester rolls over to the next one.

[Testing:Git] Fix hardcoded semester for git test

---

.setup/bin/partial_reset.py
.setup/bin/recreate_sample_courses.sh

`.setup/bin/partial_reset.py` was failing when it was attempting to clean-up the log folders, due to changes in #5423
Updates the script to use the new log folder setup, which is that instead of each individual log folder (e.g. `autograding`, `site_error`), we just symlink the parent directory (`/var/local/submitty/log`) and let `INSTALL_SUBMITTY_HELPER.sh` handle creation of the individual log folders.

[Bugfix:Vagrant] Update partial_reset for new log folder setup

---

.setup/bin/recreate_sample_courses.sh

There was no way to set similar no submissions behavior on using this script as when doing vagrant up.
Can now use the `--no_submissions` flag when running `recreate_sample_coures.sh` which will trigger no submissions to be made when generating the courses. This mirrors the flag named that's used within the `setup_sample_courses.py` script and so decided to go with that as opposed to using a variable similar to how `vagrant up` operates.

[Feature:Vagrant] Add no_submissions flag to recreate_sample_courses

---

site/app/templates/submission/homework/SubmitBox.twig
site/app/views/submission/HomeworkView.php

If a file gets uploaded, its label will be displayed twice on the file submission zone even though it was only ever uploaded once.
Prevents `addLabel` function from getting called accidentally from notebook rendering code
fixes #5614

[Bugfix:Submission] Prevent file submission dropzones from showing labels twice

---

site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
site/public/js/admin-gradeable-updates.js

Randomization feature causes error at functionalities which require listening to change of events (input, select, textarea)
Fixes the error by adding required listeners and adds back randomization feature to peer grading.

[Bugfix:TAGrading] peer randomization works again

---

bin/build_homework_function.sh

Running make_generated_output.py is run before we validate the make exit code, making the if statement a bit misleading on what's failing. The statement was introduced in #4335 above the make line, and then moved directly below it in #4867.
Running `make_generated_output.py` is now done after we check the make exit code to ensure that we're not attempting to generate output for a homework which we could not build the config of.

[Bugfix:Autograding] Run make_generated_output after validating make exit code

---

.setup/INSTALL_SUBMITTY_HELPER.sh

During the installation process, the installer attempts to chgrp and chown the git repository folder for Submitty. This is to ensure that the folder has the proper permissions so that it can be copied over to the worker machines. However, on Vagrant, this step does not actually do anything to permissions or owner as the repository folder is a shared one. Additionally, in certain cases, this was causing hangs and failures on running the script for people.
This makes it so that the chgrp / chown will only happen on non-vagrant installations (as determined by existence of the `.vagrant` folder at the top-level of the repository.

[Bugfix:Vagrant] Do not chmod/chgrp on shared directory

---

.setup/CONFIGURE_SUBMITTY.py
bin/generate_repos.py
migration/migrator/db.py
migration/migrator/migrations/system/20200701122138_database_port.py
migration/tests/test_db.py
python_submitty_utils/submitty_utils/db_utils.py
python_submitty_utils/tests/test_db_utils.py
sbin/adduser.py
sbin/adduser_course.py
sbin/create_course.sh
sbin/create_term.sh
site/app/libraries/database/PostgresqlDatabase.php
site/app/models/Config.php
site/tests/app/controllers/admin/ConfigurationControllerTester.php
site/tests/app/libraries/database/PostgresqlDatabaseTester.php
site/tests/app/models/ConfigTester.php

It is not possible to use a non-standard port for postgres when using a TCP connection.
If not using the unix socket, CONFIGURE will now ask for a port to be specified (defaulting to 5432, postgresql's default) and it will be used for all connections when we use TCP host (e.g. localhost, ip address, etc.)

[Feature:System] Allow port for database connection

---

.setup/INSTALL_SUBMITTY_HELPER.sh
Vagrantfile
sbin/shipper_utils/update_and_install_workers.py

Numerous developers reported hangs while "updating workers" on a "vagrant up".
It was unclear what step was hanging or failing.
But a likely culprit was pulling docker images to the primary machine.
Now the output to the updating workers script should be unbuffered.
Also, some print statements are adjusted to make clear that docker images on the primary machine are also being updated.

[Refactor:System] unbuffer vagrant output when updating workers

---

site/app/templates/grading/electronic/Status.twig

closes #5663 
Peer graders will be reviewing the materials submitted by their peers, and the process of peer grading may reveal the identity of the student. There are no reminders for limited access graders or peer graders.
Adds a reminder to both limited access and peer graders of their role as a reviewer.

[UI/UX: TAGrading] Show Peer Grading Reminders 

---

migration/migrator/db.py
migration/tests/test_db.py

#5616 introduced having the ability to set database port. As part of this, a migration was created to add this new field to the `database.json` file. However, if someone with an existing Submitty installation was not using a unix socket for migrator, it would cause migrator to crash before it was able to update that file with the new database port field.
This sets it so that if `database_port` is not set, it will use the default one for postgresql (5432) to run the migrations. Given that the only conditions in which this field should not be set and Submitty functions prior to #5616 when using something like `localhost` was that postgresql must be on the default port, this should work fine.
All other usages of port should not need this as they are only used after the migrator has run.

[Bugfix:Migrator] Use default postgres port to connect if config is missing port

---

site/app/templates/grading/electronic/Status.twig

closes #5663 
Peer graders will be reviewing the materials submitted by their peers, and the process of peer grading may reveal the identity of the student. Limited access graders and peer graders are not reminded on their roles as reviewer.
Adds a reminder to both limited access and peer graders of their role as a reviewer.

[UI/UX: TAGrading] Show Peer Grading Reminders

---

site/public/css/gradeable-notebook.css

The html label for notebook multiple choice inputs occupies 100% width of the parent container.  You can activate the checkbox/radio button accidentally by clicking far right of where there is text.
Styling has been changed so that the html label is only as wide as the text inside of it, making it much harder to accidentally activate the checkbox/radio button.

[Bugfix:Submission] Notebook multiple choice clickable area

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20200712221345_fix_queue_timezones.py
site/app/libraries/database/DatabaseQueries.php

The office hours queue does not store timezones with the times
The times for the office hours queue comes from the sql database time
All office hours queue times now store a timezone as well
The times in the office hours queue not correctly get times based on the submitty config file so that the sql database time should not matter anymore 
Fixes office hours queue parts of #2808
Closes  #4702

[Bugfix:InstructorUI] Fixed timezone issues on office hours queue

---

site/app/libraries/routers/WebRouter.php

The prior behavior here was that if we attempted to load a route, but it did not allow us to load a course, but was not one of our "top level" routes, we would redirect to the home page. Due to it being that the course path started at `/{_semester}/{_course}`, it meant we had to iterate each top-level controller individually to catch for them, due to how the routing might fall through in certain cases.
Given that courses are now sequestered under the unique `/courses/{_semester}/{_course}`, we can simplify this check to just check on if `_semester` and `_course` are set meaning we attempted to load a course that did not exist, while not worrying about colliding with our top-level routes. This then simplifies adding new top-level routes (like in #5337 or #5353) as it will no longer require …

[Refactor:Router] Simplify check for invalid course redirect

---

.setup/bin/partial_reset.py
.setup/install_system.sh
.setup/vagrant/setup_vagrant.sh
Vagrantfile

We were symlinking the log folder of Submitty to be under the shared directory. This made it easy to access the folders during development on the host machine. It had the increasingly adverse effect that it would cause services to fail on a `vagrant up` on a halted VM due to processes attempting to access the folders before the shared folder was mounted. Given that only a very few people actually utilized this feature, the services failing is more a con than a pro.
Removes the symlink, which should remove the point of failure for services.

[Feature:Vagrant] Remove symlinked log folder

---

bin/generate_repos.py
sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
site/app/controllers/admin/AdminGradeableController.php

Fixes #5702.
Previously, the code would only work for automatically generating gradeables if the name was the gradeable_id. Even if an instructor were to specify their own name for the folder, it would still just create folders using the gradeable_id. Additionally, repos were always being created, even if the gradeable specified it was using GitHub repos.
This fixes it so that it will now properly use the gradeable_id for the first option, and whatever the instructor types in for the second option. It will also no longer create repos if the GitHub options are selected.
Tested both options, and that they created the repositories as expected.

[Bugfix:VCS] Fix auto repo generation for arbitrary name

---

.setup/bin/recreate_sample_courses.sh

Prior change to this script commented out to the call to `partial_reset.py` as it was done during testing, but that it was not un-uncommented out after I was done testing.
Removes the comment, and so `partial_reset.py` is now properly run again as part of the `recreate_sample_sources.sh` script.

[Bugfix:Vagrant] Call partial reset as part of recreate sample courses

---

site/app/templates/admin/UploadConfigForm.twig

The macro-block is called recursively, so the container for the nested calls must be a list instead of a div.
Fixes #5613

[Bugfix:InstructorUI] Fix HTML for Autograding Config

---

migration/migrator/main.py
migration/tests/test_handle_migration.py

Signed-off-by: Matthew Peveler <matt.peveler@gmail.com>
Closes #5728 
If the database or courses directory were not found, it would print out a warning message, but keep running. This meant that `.setup/INSTALL_SUBMITTY_HELPER.sh` would then proceed as normal, which would put us into a potentially buggy / undefined state.
More explicitly cause the migrator to crash if it cannot find the database. There should never be a point where the database does not exist under normal circumstances, even on fresh install.

[Bugfix:Migrator] Exit with failure if DB not found

---

.setup/install_system.sh

Alternative patch to fix issue pointed out in #5742 
The courses directory `/var/local/submitty/courses` does not exist on the first time `INSTALL_SUBMITTY_HELPER.sh` is run, which in turn causes the migrator to crash with an error due to it missing after the changes in #5735.
This creates the directory as part of `install_system.sh` before the helper is called for the first time. This will then allow the migrator to operate as expected, performing no action as there are no semesters or courses. Additionally, this does still leave in place the error condition in place.

[Bugfix:System] Create courses directory missing for migrator on install

---

site/app/controllers/MiscController.php
site/app/templates/grading/electronic/SubmissionPanel.twig

This PR:
1. Makes the `Download Zip File` button accessible to peer graders on the TA grading page
2. Renames downloaded zip files to include version downloaded rather than timestamp downloaded
3. Anonymizes the name of zip files downloaded by peers: `{gradeable_id}_{anon_id}_{version}.zip`

[Feature:TAGrading] Allow peer graders to download submission zip files

---

site/app/controllers/grading/ElectronicGraderController.php
site/phpstan-baseline.neon

When grading a student, the next, prev, next ungraded and prev ungraded buttons will redirect to the grade detail page.
The next, prev, next ungraded and prev ungraded buttons will redirect to the proper student

[TAGrading:Bugfix] Navigation buttons to prev/next student fixed

---

site/.eslintignore
site/app/templates/notebook/Notebook.twig

On the notebook submission page if there is more than one codebox with 'rows' set then they break.
Corrected issue where javascript variable tries to be redefined.

[Bugfix:Submission] Notebook codebox hotfix

---

bin/json_schemas/complete_config_schema.json
grading/main_configure.cpp
more_autograding_examples/notebook_itempool_random/config/config.json
site/app/models/notebook/Notebook.php
site/app/models/notebook/UserSpecificNotebook.php

Currently, if there are multiple items that are available in `from_pool`, hashing is done to pick one of these questions.
Also, there is an unhandled `undefined key error` case ( for 'type' ) which is popping out on some gradeable.
Closes #5647 
Fixes undefined index error. 
Adds support for optional field `user_item_map`.  This object contains a mapping of usernames to the index of items present in the `from_pool` array. 
```
"user_item_map": {
"<username_0> : <index_0>,
"<username_1> : <index_1>....
},
```
Users in this mapping will only be shown item corresponding to the mentioned index next to their username and no hash-based randomization will be done for them.
These ensure instructors can proofread all the question before exam... see #5647 for more info
Added this key in …

[Feature:Notebook] item_pool map student to problem

---

grading/main_configure.cpp

Configuration json found in the course build directory do not contain an `item_name` for notebook item pools.
This field has been added when building item pools.

[Bugfix:Autograding] add item_name to build config

---

site/app/controllers/MiscController.php
site/app/controllers/pdf/PDFController.php
site/app/templates/grading/electronic/SubmissionPanel.twig

closes #5774
File paths containing the anon_id are not being properly substituted for the file path containing the user id in all cases. This leads files not being able to be downloaded/opened properly in some cases
Files can be opened/downloaded as normal

[TAGrading: Bugfix] Anon_id and download file fix

---

site/app/templates/grading/electronic/NavigationBar.twig
site/app/templates/grading/electronic/NavigationBarV2.twig
site/public/js/ta-grading-v2.js
site/public/js/ta-grading.js

Fixes #5190- If a TA is grading a component and clicks on the home button to go to the main page, none of the changes are fixed, unlike the next and previous buttons.
The home page button now behaves like the next and previous buttons and saves the components before redirecting
Create complex gradable components and make sure they save
Used windows with chrome and firefox

[Bugfix:TAGrading] save components before redirecting to main grading page

---

site/app/exceptions/NotebookException.php
site/app/models/notebook/UserSpecificNotebook.php
site/app/views/submission/HomeworkView.php

When the notebook submission page loads much of the relevant information is collected from the gradeable's complete_config json.
The PHP code has been rolled over to have this information instead collected from the build config json.
- Itempool notebooks will need to be rebuilt.  If you access the gradeable without rebuilding you should see an error message with instructions.
- Please test all different kinds of notebook gradeables to make sure they still behave the same way as before this change.

[Bugfix:Submission] use build config not complete config

---

site/public/css/gradeable-notebook.css

Notebook headers for MCQ/MSQ are collapsing on Safari.
Closes #5811 
Fixes Notebook header or MCQ/MSQ collapsing on Safari

[Bugfix: Notebook] Notebook header collapsing on Safari

---

.setup/bin/versions.sh

To handle average & stddev of zero length arrays.

[Bugfix:InstructorUI] update RainbowGrades version

---

sbin/submitty_daemon_jobs/submitty_jobs/__init__.py
sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
site/app/libraries/database/DatabaseQueries.php

Previously, when an instructor makes a new course, only the instructor user is added.  The verified admin user is missing, which caused an error on the course settings page, when it attempted to check if the admin user had access for automatic rainbow grades processing.  NOTE:  The missing admin user was a separate known inconvenience.
Now the admin user (if it exists) will be added to the new course automatically.  AND we will properly handle the admin user not being in the course when we offer the option for rainbow grades nightly runs.

[Bugfix:InstructorUI] verified admin user not in course

---

site/app/templates/notebook/Notebook.twig
site/public/css/gradeable-notebook.css

When rendering notebook cells on the submission page text takes up the full width of page.
Short-answer, multiple-choice, and markdown cells are now limited to a maximum width of 700px.  Text wider than that will wrap onto a new line.  Images are excluded, so they may appear at a width greater than 700px.

[UI/UX:Submission] Set max-width for rendering notebook cells on submission page

---

site/app/templates/submission/Team.twig

A student is able to seek for a team even after the team lock date.
A student wont have access to the team seeking button or the team seeking table if the lock is set. Only users will full access grading have access to the seeking table.
Creating a team gradeable, locking the team creation, and observing the behavior for different users

[Bugfix:Submission] check for lock for team seeking button and table

---

site/public/css/gradeable-notebook.css

Codeboxes on the notebook gradeable submission page may not be manually resized by the user.
Codeboxes may now be manually resized by the user by grabbing the bottom right corner and dragging, just like a `<textarea>`.

[UI/UX:Submission] Allow codeboxes to be manually resized

---

site/app/templates/grading/electronic/NotebookPanel.twig
site/app/templates/submission/homework/SubmitBox.twig

#5681 introduced a bug when displaying a twig template was changed to use the `with include` syntax causing auto-grading messages not being properly sent over to the template
Auto grading messages after a notebook has been graded are now properly rendered both on student notebook view and the new grading screen panel.

[Bugfix:Submission] display notebook autograding messages

---

site/public/css/notebook-builder.css
site/public/js/code-mirror-utils.js
site/public/js/notebook_builder/short-answer-widget.js

When an input box is displayed in a notebook builder short answer widget it still follows the old paradigm of having either an html input, a textarea, or a codemirror.
It has been updated to reflect the new paradigm which is using codemirror for all short answer inputs.  Instructors using the notebook builder short answer widget should now see exactly how the input box will be rendered to students on the submission page.

[Refactor:InstructorUI] codemirror inputs in notebook builder

---

site/app/models/gradeable/GradeableList.php

The gradeables are ordered by submission due date and the tie breaker is gradeable id
Now the tie breaker will be the gradeable title so it looks better for the user. If for some reason the titles are the same, it will fall back on the id.
Created gradeables with the same submission date and different titles and ids.

[Bugfix:UI/UX] gradeable ordering - date then alpha

---

site/.eslintrc.json

https://github.com/Submitty/submitty.github.io/pull/284
Eslinting now checks to make sure block statements (if, while, for) use curly braces even if the block is only one line 
e.g:
```
if ( foo )
bar():
```
is no longer allowed.

[Testing:JS] Add curly rule to eslint rule set

---

site/app/controllers/OfficeHoursQueueController.php
site/app/libraries/socket/Server.php
site/public/js/websocket.js

If the socket server is down for any reason, some pages as office hours queue produce an unwanted behavior that users should handle manually.
Users' actions are completed successfully as they should but they get a notice message that the server socket is down and the page won't dynamically load.
In order to test this you have to stop the websocket server so it doesn't accept connections running `systemctl stop submitty_websocket_server` on your vagrant machine.

[Bugfix:System] detect websocket server is down

---

site/package.json

The command to run eslint auto fix was not passing the `--fix` paramater when calling `eslint` so it wasn't doing anything
`npm run lint:fix` correctly begins the eslint run script

[Bugfix:Testing] Fix Eslint lint:fix script not actually running fix

---

site/app/views/grading/ElectronicGraderView.php

If an instructor/full access grader goes to grade a gradeable which has only peer components, you get the following error: 
You do not get the above error

[Bugfix: TAGrading] Peer grading stats divide by 0

---

site/app/controllers/grading/SimpleGraderController.php
site/app/templates/grading/simple/Display.twig
site/app/views/grading/SimpleGraderView.php
site/public/js/simple-grading.js

Simple grading (checkpoints / numeric) is accessed by multiple graders simultaneously but doesn't refresh upon changes so graders can't see the latest page updates.
Integrating websockets in simple grading will allow changes to any checkpoint/numeric-input to take place concurrently on all open graders pages (windows) so they can see the latest updates in real time.

[Feature:TAGrading] websockets for checkpoint & numeric

---

site/app/templates/grading/electronic/RandomizeButtonWarning.twig
site/public/css/details.css

Crash is due to a refactor in #5778 which moved to having a generic popup template and having specific popup templates extend the generic - code cannot be outside the scope of a block if the template is extending another template.
Closes #5876 
Visually behavior is correct. I'm not sure if this is the best approach, I added the style to an existing block instead of defining a new block in the `generic/Popup.twig` . It does mean jamming a `<style>` tag in a div, which may technically not be valid HTML (though I imagine all browsers will support it - my limiting testing seemed to work).

Fix Twig Error On Team Grading Index

---

.setup/INSTALL_SUBMITTY_HELPER.sh
.setup/apache/submitty.conf
.setup/install_system.sh
.setup/nginx/submitty.conf
.travis.yml
Vagrantfile
migration/migrator/migrations/system/20200911180000_ngnix_setup.py
site/public/js/websocket.js
tests/e2e/base_testcase.py

Updates submitty to use `nginx` to handle websocket requests. Requires sysadmin action on production servers, or a fresh `vagrant up` for development machines. 
For use on a production system, a sysadmin must:
1. Install this code,  which includes a migration will install `nginx`.
2. Remove the default `nginx` site, `/etc/nginx/sites-available/default`, if desired.
3. Copy the default nginx `submitty.conf` file from `{SUBMITTY_REPO}/.setup/submitty.conf` to `/etc/nginx/sites-available`.
4. If desired, update `submitty.conf` to use ssl (example configuration below)
5. Create a symlink for `submitty.conf` from `sites-available` to `sites-enabled` 
`ln -s /etc/nginx/sites-available/submitty.conf /etc/nginx/sites-enabled/submitty.conf`
6. If migrating from a previous version of submitty, …

[SYSADMIN ACTION][Feature:System] nginx to process websocket requests

---

site/public/js/websocket.js

Increased the websocket reconnect interval from exactly 5 seconds to 10-20 seconds. This should help to decrease load when the webserver is unresponsive.

[Bugfix:Notifications] Increase websocket reconnect interval

---

site/app/templates/generic/Popup.twig

A debug print statement was introduced to master recently which triggers on every keystroke on many pages of the system. This PR removes that statement.

[Bugfix:Developer] Remove debug print statement which was triggered on every keystroke

---

site/app/templates/notebook/Notebook.twig
site/public/css/notebook-builder.css
site/public/js/notebook_builder/widgets/short-answer-widget.js

Closes #5885
Codemirror boxes used on the notebook gradeable submission page and notebook builder will not wrap text, instead they will show a horizontal scroll bar.
- Large style codemirror boxes in these two areas have been changed so that if they are collecting plain text, long sentences will now automatically wrap to the next line instead of creating a horizontal scroll bar.
- When collecting code there will NOT be wrapping.
- Inside notebook builder adding wrapping required setting a fixed width of 1000px on the element containing the codemirror.  This may be a small visual change for some users.

[Bugfix:Submission] Make codemirror wrap for plain text inputs

---

.setup/install_system.sh
migration/migrator/migrations/system/20200911180000_ngnix_setup.py

When installing nginx on our production servers using `apt-get install nginx`, we found that the command yielded differing results across machines. Upon further investigation, it seems that installing `nginx` chooses one of four different installation candidates based on OS, `nginx-core`, `nginx-full`, `nginx-light` and `nginx-extras`. This PR moves us to be explicit about the version that we want, `nginx-full`.
This PR has been tested, and it __does not__ modify or remove existing nginx submitty configurations. This PR may require the installer to run `systemctl restart nginx` and `systemctl restart submitty_websocket_server`.

[Bugfix:System] Specify nginx-full on installation

---

.setup/INSTALL_SUBMITTY_HELPER.sh
.setup/install_system.sh
.setup/travis/setup.sh

Previously, when running `INSTALL_SUBMITTY.sh`, web services (e.g. apache, nginx, php) did not restart unless the `restart_web` option was specified. This PR updates the system so that web services are restarted by default, and adds the `skip_web_restart` option to avoid restarting web services.

[Feature:System] Restart web servers by default when installing

---

site/app/templates/polls/AllPollsPageStudent.twig
site/app/templates/polls/PollPageStudent.twig

Under some circumstances, an incorrect null check causes a student's view of polls to show that they have not submitted a response in either the answer column showing "No Response" or the answer column erroneously labelled "Answer" as opposed to "Edit Answer."
Now both the answer column and the answer column will update correctly if the student has already responded to the poll.

[Bugfix: InstructorUI] Fix student view of polls not showing answer correctly

---

bin/json_schemas/complete_config_schema.json
grading/main_configure.cpp
more_autograding_examples/notebook_time_limit/config/config.json
site/app/controllers/student/SubmissionController.php
site/app/models/gradeable/AutogradingConfig.php
site/app/templates/submission/homework/LoadMessagePage.twig
site/app/views/NavigationView.php
site/socket/index.php

When opening a gradeable, it always immediately opens the gradeable.
When opening a gradeable with the "load_gradeable_message" option in the autograding configuration for that gradeable, it will first redirect the user to a confirmation page with the contents of "message" (under "load_gradeable_message") displayed on the screen (with markdown). The user can then opt to either continue to the gradeable or can go back to the main gradeable page (or can select any of the options on the sidebar). If the option "first_time_only" (under "load_gradeable_message") is selected, then after an entry is found in the database for user access to the gradeable, the message will no longer show.
The "load_gradeable_message" page does not trigger a page access for the gradeable.
Tested by making sure that …

[Feature:Submission] Message page before gradeable

---

site/app/controllers/admin/ReportController.php

If a course only has team-based assignments, clicking Generate Grade Summaries from the reports page will cause a crash. This is due to two reasons:
* The inner loop uses `$current_user` instead of `$u`, and `$current_user` is not the variable being iterated over, so this results in trying to invoke a method of NULL
* The `saveUserToFile` function expects an extra argument (polls), so the $per_user_callback closure passed into the call to `generateReportInternal()` expects 4 arguments. However the invocation in `generateReportInternal()` did not pass in this extra argument (`$all_polls`) so there would be an argument number mismatch even if the above point was addressed.
Courses containing gradeables that are all team gradeables do not cause an exception to be generated, and the …

[Bugfix:InstructorUI] Generate Grade Summaries Crashes On Team-Only Course

---

site/app/controllers/admin/AdminGradeableController.php
site/public/js/admin-gradeable-updates.js

Closes #5733 
On the 'Submissions/Autograding' tab of the edit gradeables page a small box indicates the build status of the gradeable.  If a gradeable is successfully build it will show `Build Status: Gradeable build complete` even if the schema validator gave warnings.
If the schema validator generated warnings during the gradeable build process the message will now show `Build Status: Gradeable built with warnings`.

[Feature:InstructorUI] Communicate schema warnings to webUI

---

site/app/templates/submission/homework/SubmitBox.twig
site/app/views/submission/HomeworkView.php
site/public/css/submitbox.css

Closes #5888 
When a user navigates to the submission page for a gradeable they will see the due date formatted for their local time zone.  Despite including a time zone identifier this was still confusing for some users.
On the submission page, if a user has their timezone set differently than the server timezone, they will see the due date formatted in both their local time and the servers time.
If a user has their timezone set to the same timezone as the server, they will see no changes on this page.

[Feature:Submission] Show due dates in user/server timezone on submission page

---

site/public/js/forum.js

In the forum, if you type some text into a reply box, and the contents of the box are autosaved, and later you decide to clear out the text of that box, the old contents of the box will be shown the next time the page loads as the autosave data for that text box is not overwritten (due to a check to avoid polluting `localStorage` with a bunch of empty text box data).
When a forum reply box's data is about to be saved, if the reply box is empty, then its autosave data will be cleared from `localStorage` and a refresh will result in the reply box staying empty as intended.
Tested on Chrome.

[BugFix:Forum] Clear autosave data for empty forum reply boxes

---

.setup/INSTALL_SUBMITTY_HELPER.sh
site/app/controllers/OfficeHoursQueueController.php
site/app/libraries/Logger.php

Closes #5454 
Upon queue open, close, empty, or creation, a message is logged to /var/local/submitty/logs/office_hours_queue/file.log
A new file is created each day, like how existing logs work.
Each time a queue does an action, a line is written containing:
Timestamp | Course Semester | Course Name | Queue Name | {OPENED | CLOSED | EMPTIED | CREATED} | User Agent

[Feature: InstructorUI] Adding logging for office hours queue

---

site/app/templates/submission/homework/AutogradingResultsBox.twig

There exists a minor race condition in "grading finished" detection for gradeables which becomes much more common on slow I/O setups that incorrectly causes the grading results page to display a "Something went wrong when grading this submission." message.
When the "Something went wrong when grading this submission." message occurs, we reload the page up to three times. If after three reloads the message is still visible, then assume something is in fact wrong with the submission and give up.
If Submitty is being run on a machine with fast I/O, this behavior can be tricky to reproduce. One way to simulate this behavior is to add delays after the modify the `GradingQueue::reloadQueue()` in `site/app/libraries/GradingQueue.php` (look for the `usleep` calls):
```php
/**
* Forces the queue …
```

[Bugfix:Submission] Reload up to 3 times on "Something went wrong"

---

site/app/templates/forum/StatPage.twig

On the Stats page, on clicking the **"Expand"** button, the posts were not displayed, instead it would display errors in the console. There was a tiny error in the `forum.js` file wherein a line was accessing the `thread_titles` variable as if it were a _key-value array_, whereas it was a _numerically indexed array_.
Fixes #5810 . On clicking the "Expand" button, the user's posts don't show up, instead errors are displayed on the browser's console.
On clicking the "Expand" button, the user's posts are displayed.

[Bugfix:Forum] View posts by users fixed on stats page

---

site/app/controllers/student/TeamController.php
site/tests/app/controllers/student/TeamControllerTester.php

On team invite, the RCSID must be all lower case and must not have spaces around the input.
Results in errors like this:
Cleans the input so now the issue in the screenshot shouldn't occur.
Would lookup `shomsj` that exists; instead of `Shomsj` that doesn't.
_Is this a breaking change?_
Nope
_How did you test_
`./site/tests/app/controllers/student/TeamControllerTester.php`

[Bugfix:Submission] Clean invite rcsid on team invite

---

site/app/templates/submission/homework/LoadMessagePage.twig

Leave all formatting to the markdown string configured by the instructor.

[UI/UX:Submission] Remove h1 from notebook load message

---

site/public/css/server.css

Sequence diagrams sizes were never explicitly set. A previous change caused them to be rendered at very small scales. This PR explicitly sets sequence diagram sizes to 100% of their container's width.

[Bugfix:Submission] Resize Sequence Diagrams

---

autograder/submitty_autograding_shipper.py
more_autograding_examples/notebook_time_limit/config/custom_validation_code/timelimit.py

If a student never accesses a gradeable page, but an instructor makes the submission for them,
there will be no information in the access log, and the .user_assignment_access.json for that
submission will be an empty array.
Previously this was crashing autograding, and jobs were getting stuck in the queue.
Now we gracefully ignore this situation in autograding.
Our sample autograder for the timelimit (which uses the access log) now also checks for this situation.
Currently the student with no access receives no penalty for time.  (This decision may need to be 
revisited/revised.)
Fixes #5935

[Bugfix:Autograding] empty gradeable access log

---

.setup/install_system.sh

On repeated calls to `install_system`, `php-fpm/pool.d/submitty.conf`, `apache2/suexec/www-data`, and `nginx/sites-available/submitty.conf` were being reset to their default state. This PR prevents this clobbering from happening.
I am opening this PR as a draft because  are a number of `sed` operations which are taken against `php/${PHP_VERSION}/fpm/php.ini` to replace default values with higher/submitty recommended ones. Because this is basically doing find/replace on low default values to increase them, I did not add special handling of the seds (e.g. do not perform them if a `fpm/php.ini` already exists). However, one of the sed operations does wipe out the `disable_functions` list and replace it with Submitty defaults.

[Bugfix:System] Stop install system from clobbering submitty conf files

---

site/app/libraries/database/DatabaseQueries.php
site/app/templates/grading/electronic/Status.twig

Fixes the status page of ungraded gradeables. The problem would arise when `averageScore` is a null value, since there were no entries to fetch, JavaScript would emit an error. Fixed this by modifying the database query and then including another check while constructing the `SimpleStat` model.
Fixes #5562 . Currently, an error shows up on the console.
No error is shown in the console.

[Bugfix:TAGrading] status page in ungraded gradeables

---

site/app/templates/officeHoursQueue/QueueHeader.twig
site/app/templates/officeHoursQueue/QueueStatus.twig

Every time an instructor/TA makes a change to a queue (Helps/Finishes Helping/Removes), the student sees an additional "View Queue Stats" button:
The student only sees one "View Queue Stats" button no matter how many times the instructor/TA interacts with the queue.

[Bugfix:InstructorUI] Fix "View Queue Stats" Button

---

site/public/css/officeHoursQueue.css

The box for putting in contact info is currently quite small, and it doesn't fit a Webex meeting link:
The box is now big enough to fit both a group meeting link for labs and a personal room meeting link for office hours:

[UI/UX: InstructorUI] Increase size of contact info box for office hours queue

---

site/public/index.php
site/public/js/drag-and-drop.js

PR https://github.com/Submitty/Submitty/pull/5950 introduced a bug where the office hours queue would say "request type not supported" when the queue would dynamically update if a student entered/left.
This was because pr 5950 forced ajax requests to receive JSON responses back, but the office hours queue was using ajax to grab the new html and updating the dom via javascript, preventing a full page refresh. There were no checks of the response type so whatever was sent back was displayed to the user.
Since developers might be interested in receiving raw HTML from a controller in scenarios like this the router will
will now by default send back whatever the controller that was called returned. If the client wants to enforce a JSON request they can set the "accepts" headers to "text/json". …

[Bugfix:OfficeHours] Fix updating queue dynamically 

---

site/app/templates/admin/RainbowCustomization.twig

Fixes #5908 . After reordering items while customising rainbow grades, horizontal lines would get accumulated, since each `<hr>` tag was in its own `<li>` tag, not linked to its "parent" `<li>` tag. Solved this problem by removing the `<hr>` tag altogether and giving each `<li>` tag a top-border.
The `<hr>` tags don't get accumulated anymore.

[Bugfix:RainbowGrades] Fixes the accumulation of horizontal lines after reordering items while customising Rainbow Grades

---

site/app/models/CourseMaterial.php

Students may access course materials prior to the course materials release date, provided they obtain a url to the file.
This behavior has been corrected and students may no longer access course materials that haven't yet been released.
This bug was the result of PHP being unable to correctly parse the release time string into a DateTime object.  When this condition occurs instead of throwing an exception the DateTime library will simply return `false`.  The `false` was then used in a comparison causing `true` to always be returned.
The parsing bug has been resolved.  Additionally the return type is now checked so that if a parsing error occurs an exception is now thrown.

[Bugfix:InstructorUI] Prevent access to course materials before they are released

---

site/app/models/CourseMaterial.php
site/app/templates/course/CourseMaterials.twig

When working with course materials as an instructor, there is a file option to 'Hide from students'.  In testing this option didn't appear to do anything.
This behavior has been corrected so that when this option is selected the file will not be visible to students (but will still be accessible via a link, as described in the options documentation).

[Bugfix:InstructorUI] Course materials fix hide from students option

---

.setup/install_system.sh

CGI scripts are not able to run after an initial vagrant up. This will prevent users from logging in to the sample system since it's based on pam authentication. The existing suexec config file is not updated if it already exists, this prevents apache from executing any cgi script since it thinks the docroot is located somewhere else.
Apache was most likely creating default files before the install_system script could copy the correct versions over.
Removes the `-n` flags so the install_system will clobber the submitty.conf and suexec/www-data with whatever is on the host system.
This should make sure those files are correct on initial up.
If you have this issue you might be able to skip a vagrant destroy/up with the following commands:
```bash
cp …
```

[Bugfix:System] Fix install_system for initial vagrant up

---

.travis.yml

Travis currently failing due to a race condition on nginx, this manually creates the file ahead of a nginx restart

[Bugfix:Travis] Fix travis nginx race condition issue

---

site/app/libraries/Output.php
site/app/templates/officeHoursQueue/AnnouncementMsg.twig
site/app/templates/officeHoursQueue/QueueHeader.twig
site/public/css/markdown.css
site/public/css/server.css

Partially #5884 
The styling of rendered markdown is inconsistent across submitty.
This PR introduces a global level `markdown.css` file and starts implementing styling rules.  The PR also has applied these rules to the office hours queue welcome message (pictured below) and office hours queue announcements (not pictured).
This is only the first of several PRs to standardize the look of markdown across submitty.

[Refactor:UI] Standardize markdown for office hours queue

---

site/app/templates/polls/NewPollPage.twig

One bullet of #5912 --  when an instructors submits edits or a new poll and there is a part that is an invalid setup, it will simply kick the instructor back to the all polls page, and discard their changes.
If there's an invalid polls setup (for either editing or creating new polls), there is now front-end error checking that will disable the submit button and add an error message above the submit button.
Yet to do -- test on  Firefox to see if on "change" detects typing in the textboxes -- I had only developed on Safari and tested on Chrome.

[UI/UX:Submission] Invalid Polls Setup

---

site/app/controllers/admin/NotebookBuilderController.php
site/app/libraries/FileUtils.php
site/app/models/Config.php
site/public/js/notebook_builder/notebook-builder-utils.js
site/public/js/notebook_builder/widgets/form-options-widget.js
site/tests/app/models/ConfigTester.php

There is currently an issue with notebook builder not being able to correctly save/edit files in our production environment.
This PR adds additional error checking any time a notebook builder file is saved / edited / uploaded.  Error messages are now more verbose which will hopefully allow us to perform a more thorough debugging.
Tested by changing file permissions/ownership.  I used a PHP debugger to pause script execution, allowing me to manually change settings after file generation but before error checks ran.

[Feature:InstructorUI] Add additional notebook builder error checking

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/views/grading/ElectronicGraderView.php

In ElectronicGraderController and ElectronicGraderViewer, there are some situations variables are not being checked to be not null before functions are called on them. This leads to some errors in niche cases.
The variables are being checked as not null. This prevents the edge case errors

[TAGrading: Bugfix] Null values not being checked in EGC and EGV

---

site/app/templates/functions/AutogradingActions.twig

When instructors configure a gradable with dispatcher or graphics actions, they have the option to set `publish_actions` to `true`, thereby providing students with a human-readable test procedure on the submission page. 
This PR fixes a bug with this display, which was causing trailing newlines to be displayed as whitespace.

[Bugfix:Submission] Display newlines and trim trailing spaces in view test procedures

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/SimpleStat.php
site/app/templates/grading/electronic/Status.twig

#5975 (and #1650)- There are currently no stats for graders for a given gradeable
Every gradeable now has a grader breakdown for each component (count, average, and stdev).
Created a new gradeable with different graders and matched the results with my expected output

[Feature:TAGrading] Grader stats breakdown

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20201012030252_omit_files.py
site/app/controllers/admin/AdminGradeableController.php
site/app/libraries/Access.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/gradeable/Gradeable.php
site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
site/app/views/grading/ElectronicGraderView.php
site/public/js/admin-gradeable-updates.js

A peer grader can see all of the files a student submitted
On the peer matrix tab while creating/editting a gradeable, an instructor can enter wildcards. Filenames that match the attached wildcards will not be shown to the student (but will be shown instructors, Full and limited access TAs)

[TAGrading: Feature] Allow instructors to exempt files from peer view

---

site/app/templates/submission/homework/LoadMessagePage.twig
site/app/templates/submission/homework/SubmitBox.twig

Partially #5884 
Gradeable assignment messages and gradeable load messages do not inherit markdown styling rules from the new standard set of markdown styling rules.
Markdown rendered for these two spots in submitty now will be styled according to the recently implemented markdown.css.
Assignment message screenshot:

[Refactor:UI] Standardize markdown for gradeable assignment/load message

---

site/app/templates/notebook/Notebook.twig
site/public/css/gradeable-notebook.css

Partially #5884 
Notebook gradeables have the ability to render markdown in several different areas.  This markdown doesn't use the recently implemented markdown.css.
Updated the notebook gradeable submission page so that markdown areas now use markdown.css.

[Refactor:UI] Standardize markdown for notebook gradeables

---

autograder/autograder/autograding_utils.py
autograder/autograder/execution_environments/container_network.py
autograder/autograder/grade_item.py

At present if an error occurs as the result of a failed docker operation (e.g, container creation), any hanging containers are not cleaned up. This means that subsequent testcases fail due to docker name collisions.
This PR adds container cleanup before testcases are run, intermediately between each testcase, and after execution has finished.

[Bugfix:Autograding] Stop subsequent testcase failure on docker errors

---

site/app/models/notebook/UserSpecificNotebook.php
site/app/templates/notebook/Notebook.twig
site/public/js/ta-grading-v2.js

When grading inside of the new TA grading interface, when a grader goes to a different student, the scroll position in the notebook resets.
Fixes #5976 
When grading inside of the new TA grading interface, when a grader goes to a different student, the scroll position in the notebook goes to the same content section from the previous one (if it is a random item pool item, it will go to the top of that item as a whole).
Tested by going through each section and going between students to make sure it went to the correct content section in the notebook.

[Feature:TAGrading] Keep notebook scroll position in TA grading page

---

site/app/controllers/MiscController.php
site/app/models/CourseMaterial.php
site/app/templates/course/CourseMaterials.twig
site/app/views/course/CourseMaterialsView.php

There is no ability to restrict access to course materials on a user-by-user basis.
This PR begins to implement this behavior.  A user interface for this feature will be added in a later PR.
To test simply add a 'user_allow_list' array to a desired file in the `course_materials_file_data.json` as illustrated below.
**Note:** Using the instructor facing website interface of course materials to edit any files will likely clobber custom made edits to `course_materials_file_data.json`. 
Adding a 'user_allow_list' to a file will restrict access and visibility of that file to *only* those users in the allow list, or users that have a higher access level than students (for example instructors).

[Feature:InstructorUI] Restrict access to course materials by user

---

site/app/templates/notebook/Notebook.twig
site/public/js/ta-grading-v2.js

If you quickly spam paste right after a CodeMirror box is clicked, you can sometimes paste data into the box.
If the notebook panel was not in your layout and you add it to your layout, the CodeMirror boxes will be blank until it is clicked on.
Works on #5971 
CodeMirror boxes should now be fully readonly in grader view.
CodeMirror box data will now be refreshed on adding the notebook panel into your layout.
Tested before and after making changes to make sure issue was fixed.
Tested CodeMirror boxes in a notebook_itempool_random gradeable to make sure they still worked.

[Bugfix:TAGrading] Fix CodeMirror bugs

---

site/app/controllers/grading/ElectronicGraderController.php

Changing the version of student code to be graded from the TA grading page results in a "frog robot" error. This was caused by the TA grading page improperly always assuming that grading was blind.
The error should now be resolved.

[Bugfix:TAGrading] Fix version changes on the TA grading page

---

site/app/controllers/MiscController.php

If an instructor uses wildcards to designate files hidden to peer graders, the peer graders can download the files using the Download Zip files button
The Download Zip files now only includes files which the peer has access to (will not allow for hidden files)

[TAGrading:Bugfix] Download Zip Downloading Hidden Peer Files

---

site/app/controllers/AbstractController.php

The possibility of a null anon-id is leading to frog robots in edge cases
A null check should prevent these frog robots, but a null anon-id will still prevent the user from seeing the page

[TAGrading:Bugfix] Frog Robot Quick Fix

---

site/app/controllers/admin/LateController.php
site/public/js/latedays.js

Late days added on the "late days allowed" page are stored with hours/minutes/seconds precision. However, when an entry is deleted, it is deleted with month/day/year precision, resulting in failed deletions.
Deletion now allows "seconds" precision.
Per a conversation with @bmcutler, the intended behavior for this interface is actually for all portions to use "days" precision. However, at present, that would require a migration/more complicated refactor. This PR restores full functionality to the late days allowed page, while leaving future work per issue #6053

[Bugfix:InstructorUI] Allow late days allowed entries to be deleted

---

site/app/templates/polls/AllPollsPageInstructor.twig

There is no easy way for the instructor to see the total number of responses per poll from the main poll page.
There is now a column for responses that displays the total number of responses per poll.
The spacing of columns for the main poll page has also been slightly changed to _hopefully_ be prettier :)

[Feature:InstructorUI] Display responses per poll

---

site/app/templates/grading/electronic/ta_status/StatusAutogradingHistogram.twig
site/app/templates/grading/electronic/ta_status/StatusOverallHistogram.twig

When a TA or instructor looks at stats on the histogram tabs and clicks on the "Submit Bucket Size" button, it results in an "Invalid CSRF Token" error
The bucket size now changes without the error
Not a breaking change, the type for the button was removed in order to prevent a page refresh

[Bugfix:TAGrading] Histogram Bucket Size Bug

---

site/app/templates/grading/electronic/ta_status/StatusData.twig

#6083 (and originally #5979) has a broken closing `</p>` tag for showing the statistic. The page displays correctly only because browsers are being forgiving for the invalid HTML and automatically inserting the closing `</p>` tags appropriately, but this behavior is browser specific and not guaranteed.
Uses the appropriate closing `</p>` tag.

[Bugfix:TAGrading] Fix invalid closing p tag

---

.github/workflows/main.yml

The GH action uses [xdebug](https://xdebug.org/) profiler to handle calculating the code coverage statistics for the PHP unit tests. Due to the large amount of test doubles / mocks we use in the codebase, with the way xdebug tracks that info, it drags down running the test suite quite a bit.
This PR switches from xdebug to [pcov](https://github.com/krakjoe/pcov) library. While xdebug is still the best tool in profiling PHP code in general and analysis and has been around for a 10+yrs, but it brings in a lot of tooling and such to just do code coverage. pcov on the other hand is a much newer (~1yr old?) smaller library that's focused just on code coverage statistics, allowing it to run in a much smaller fraction of time, like in our case 10m44s -> 58s.
In the `shivammathur/setup-php` …

[Testing] Move to pcov for coverage in GH action

---

.flake8
.github/workflows/pr_title.yml
.github/workflows/pr_title_tester.py

The regex for PR titles added in #6099 is a bit too strict for dependabot which regularly generates titles that are between 50-70 characters long. This issue is shown in the failing on titles for recent dependabot PRs, like #6103.
Adjusts the regex so that the `[Dependency]` and `[DevDependency]` tag allow for up-to 70 characters in the title (to accommodate for our longest dependency title `@fortawesome/fontawesome-free`.
It does not look like dependabot surfaces ability to generate a shortened message (dropping say the `in /site` bit for us). We could maybe look into an action to deal with automatic PR title rewriting, but my feeling from discussion in #6099 is we would like to avoid that except as a last resort.

[Testing:System] Fix regex for PR titles for dependabot

---

.dependabot/config.yml

Dependabot currently uses a prefix of `chore(dep)` or `chore(dev-dep)` for new PRs. This will fail the PR check added in #6099.
This PR aims to prefix the to use `[Dependency]` and `[DevDevendency]`. This should hopefully get us PRs that pass the validation in #6099.
Documentation for the config file can be found [here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates). Most of the file was automatically generated from the dependabot website, with my addition being the `commit-message` bit. I suspect we may have issues where it'll generate PRs with a semi-colon between the prefix and the scope, and so may need to go upstream in that case.
Testing was done by validating the schema through [dependabot's online …

[Feature:Developer] Add dependabot configuration file

---

.github/dependabot.yml

Dependabot PR titles are currently `[Development](deps): ...` where we want to remove the `(deps)` part.
This removes the `(dep)` part. While the documentation is poor on what the `includes` parameter does, listing:
> include: "scope" specifies that any prefix is followed by a list of the dependencies updated in the commit.
Looking at the source code seems to confirm that removing this should remove the `(deps)` part of the message.

[Testing:System] Remove scope from dependabot message

---

.github/dependabot.yml

Digging into the code of dependabot, namely [this section](https://github.com/dependabot/dependabot-core/blob/e566a102b15eb7876271914b07234f22b58177a0/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L81-L89):
```ruby
def prefix_from_explicitly_provided_details
prefix = explicitly_provided_prefix_string
return if prefix.empty?
prefix += "(#{scope})" if commit_message_options[:include_scope]
prefix += ":" if prefix.match?(/[A-Za-z0-9\)\]]\Z/)
prefix += " " unless prefix.end_with?(" ")
prefix
end
```
it looks like that if the specified prefix matches the regex, it will append a `:` to the message, which would then fail our PR title tester.
Appends a space which should mean that the `:` will not be appended as the regex will fail, and then the following line will also not fire …

[Testing:System] Remove semicolon from dependabot message

---

Vagrantfile

When you run `vagrant up` without having the vbguest plugin installed, it prints a short error message about missing it. On hitting it, I knew I needed to do `vagrant plugin install`, but could never remember if it was `vagrant plugin install vbguest` or `vagrant plugin install vagrant-vbguest`, necessitating looking into the docs to get the proper install line.
This includes the install line in the error output to give an immediate actionable step for a developer. This install line has been stable ever since we added this plugin years back, and so this does not introduce any maintenance overhead to keep it up-to-date.

[Documentation:Developer] Add install line to plugin error message

---

site/app/controllers/student/SubmissionController.php

Fixes #5995
When uploading certain Microsoft Office files, the submission controller identifies these as zip files, which, while *technically* true, is not intended behavior. This happens because the submission controller exclusively uses the MIME type of the file to determine whether it is a ZIP file or not, 
The submission controller now checks if the file extension is zip *in addition to* inspecting the MIME type of the file. This way, a user can be confident in knowing that their upload will only be expanded if it is a valid zip file with the zip extension.
Exporting a docx from Docs, a pptx from Slides, or an xlsx from Sheets will reliably trigger this bug.
This is an artifact of an [upstream bug](https://bugs.astron.com/view.php?id=46) in `libmagic`, part of the `file` utility, …

[Bugfix:Submission] Don't extract Microsoft Office files as zip

---

site/app/libraries/database/DatabaseRowIterator.php

The `next` function in the DatabaseIterator class was returning values, even though the interface that it implements specifies that `next` should return `void`. This is now constituted as a bug properly by phpstan in #6128.
Removes the return statements, making the function now properly return `void`. No consumer of this iterator makes use of calling next to get a value (instead relying on `foreach` loops) which properly uses the `current` function to fetch the value.

[Refactor:System] Fix type signature for DB iter

---

site/app/controllers/grading/ElectronicGraderController.php

Undefined variable when attempting to save all component pages at once. I am somewhat guessing this is a dead code path.
The used variable is now defined. Given the usage on like 2100 of `$pages[$component->getId()]`, this gives credence that this is the right change.

[Bugfix:InstructorUI] Undefined var on saving component pages

---

.setup/install_system.sh

Running a fresh `vagrant up` was failing as the `http://lvm.org/git/*` endpoints are no longer available. These endpoints were a mirror of the sub-directories of the main llvm-project which were meant to only be available as long as it took for the transition from SVN to git (started in 2018).
Transitions to the clone to use the current home of the project, https://github.com/llvm/llvm-project. I also pinned the clone to use the latest minor release (7.1.0) of the project for when it was originally added, which was when 7.0.0rc1 was released, as I am not certain the tools are being tested against newer versions of clang, and so might of broken on 8+.

[Bugfix:System] Fix building clang for static analysis

---

site/app/controllers/PollController.php
site/app/templates/admin/Configuration.twig

Currently, Submini/polling is locked behind a feature flag, making it a non-standard feature harder for instructors to use.
Now, the feature flag is removed since all required features (main polling features and the ability to access the response data) have been developed.

[Feature:InstructorUI] Remove feature flag from Submini/Polls

---

site/app/views/course/CourseMaterialsView.php

Adds workaround for extra null check if the release date is null for whatever reason,
will need to investigate further what could cause it to be null in first place

[Bugfix:InstructorUI] null release date for course materials

---

site/app/templates/grading/electronic/SubmissionPanel.twig
site/public/js/ta-grading.js

Some JS code was using the twig replacement syntax  e.g: `{{ foo }}` which caused file loading and pdf editing to break
Additional issue for notebook gradeables where the openFile function was calling the wrong function due to a name collision
Twig variables now get passed correctly from the server to the JS files

[Bugfix:TAGrading] view submitted/checkout files

---

autograder/autograder/grade_item.py

Properly set the `is_vcs` boolean when constructing testcase objects.

[Bugfix:Autograding] copy files from checkout folder

---

.setup/distro_setup/setup_distro.sh

We attempt to install the latest version of pip for python2. The latest version is no longer compatible with python2 and so leads to issues.
Given we no longer use python2 for anything within Submitty itself, no real reason to bother installing pip2.

[Feature:System] Remove pip2 installation

---

site/app/templates/grading/electronic/SubmissionPanel.twig
site/public/js/ta-grading.js

PR #6158 introduced a bug where a JS function name was changed for opening PDF files, originally they were the only type of file that could be opened in a full panel (to support the PDF editor). However, that feature had been expanded to any file when the new ta grading interface was built, as a result, non pdf files would break when viewed in full panel mode.
The function has been renamed to reflect its real behavior and all instances have been updated. PDFs and all other files can now be viewed in full panel mode

[Bugfix:TAGrading] Expand file in full panel mode

---

autograder/autograder/packer_unpacker.py
autograder/submitty_autograding_shipper.py
site/app/models/gradeable/AutoGradedVersion.php
site/app/templates/submission/homework/CurrentVersionResults.twig
site/app/views/submission/HomeworkView.php

Currently, no information is given by Submitty as to which worker machine has graded a gradeable. This can make debugging worker setups with many different worker hardware configurations difficult, as sometimes bugs may manifest on one worker but not another (e.g. a graphics assignment being graded differently on different workers due to worker hardware).
A gradeable's version information box now displays the name of the worker that graded that specific version alongside other information such as queue wait time, first access timestamp, etc. There are three different output cases:
* Output in most cases:
* Output on a graded version which does not have associated worker machine information (e.g., it was graded before this information was added to the stored queue file):
* Output on a …

[UI/UX:Submission] Show graded version worker information

---

site/app/controllers/PollController.php
site/app/templates/polls/NewPollPage.twig

Closes #6177
Currently, polls are able to be submitted if there are no correct responses.
Now, each poll is required to have at least 1 correct response.

[Bugfix:SubminiPolls] Add Correct Response Requirement

---

site/app/controllers/GlobalController.php

Currently, Submini Polls are just labelled as "Polls". This lacks crucial branding.
Now, we are using the properly branded name "Submini Polls". This will help Submini Polls in its mission to overtake iClickers forever.

[Feature:SubminiPolls] Update sidebar to reflect new name

---

site/app/controllers/course/CourseMaterialsController.php

__Urgency: 3__
__Impact: 2__
In cases where a course material download was cancelled, the resultant temporary zip file was left abandoned in the `/tmp` directory. This PR adds the deletion of the zip file as a callback/shutdown function, preventing the issue.

[Bugfix:CourseMaterials] Handle failed course materials downloads

---

site/app/views/grading/ElectronicGraderView.php

Selecting a previous version in the information panel in TA grading shows the latest version in the notebook panel.
Fixes #6221 
Selecting a previous version in the information panel shows the selected version in the notebook panel.

[Bugfix:TAGrading] Fix notebook panel display version

---

Vagrantfile

We had previously been using the private network `192.168.56.111` to access Submitty, however, we had previously consolidated to just using `localhost:port` instead of the IP address. It was intended to then phase out these IP addresses over time.
The IP address has actually been broken for a while and totally unusable, so safe to just remove seeing as how no one has complained about it.
Docs PR: Submitty/submitty.github.io#320

[Refactor:System] Remove unused network vagrant setting

---

README.md

README had build icon from Travis, which we no longer use.
README has build icon for GitHub actions.

[Documentation:Developer] Update build status icon in README

---

site/app/templates/submission/homework/AutogradingResultsBox.twig

JQuery syntax was broken from a missing `$` causing broken JS syntax throwing an exception on the homework 
results page in the autograding section
Add `$` back so JQuery selector works again

[Bugfix:Submission] Show autograding incentive message

---

.github/workflows/submitty_ci.yml
.setup/testing/setup.sh
tests/e2e/test_forum.py

e2e tests were running against database auth on gh actions
e2e tests are now running against PAM, a separate step has been added to test logging in with database auth 
For some reason testing infinite scroll always crashes due to a websocket python error with a broken pipe. This test has been removed for now

[Testing:Developer] Run e2e tests with PAM auth

---

autograder/autograder/execution_environments/container_network.py

This PR makes docker api timeouts explicit and adds  handling for a broader class of container creation errors.

[Bugfix:Autograding] Make docker api timeouts explicit

---

autograder/autograder/autograding_utils.py
autograder/autograder/execution_environments/container_network.py
autograder/autograder/grade_item.py

Moves the `cleanup_stale_containers` function to use the `docker` package for python, hopefully making it less flaky.

[Bugfix:Autograding] Properly clean up stale containers

---

autograder/autograder/autograding_utils.py

A recent PR introduced a typo when removing stale docker networks. This PR patches that bug.

[Bugfix:Autograding] Fix broken docker network removal

---

site/cypress/integration/login.spec.js
site/cypress/support/commands.js

Cypress is supposed to clear each session between tests however sometimes a test fails because the user is still logged in between tests.
Group tests by whether a user is supposed to successfully login or not and now explicitly log out of Submitty after each test that can log in.

[Testing:Developer] Make cypress login tests less flaky

---

.setup/install_system.sh

The port for apache to open up was hard-coded to `1501` for Vagrant. This makes it not possible to use a different port for a different VM box.
Replaces the hard-coded port with one that is set via environment variable within the `setup_distro.sh` script.

[Bugfix:Developer] Remove hardcoded port for apache conf

---

.github/workflows/submitty_ci.yml
.setup/install_system.sh

Sqlalchemy changed behavior around how the `engine.has_table` function worked. This in-turn broke how the migrator was functioning.
Sets an upper-cap on the version of sqlalchemy that Submitty will install so that nobody is blocking as investigate how we might move off the `engine.has_table` function in a way that is backwards compatible.

[Bugfix:System] Pin sqlalchemy version

---

migration/migrator/main.py
migration/tests/test_handle_migration.py
migration/tests/test_status.py

Related to #6210.
Right now, if we have issues connecting to the master database, we throw a generic looking exception message. This makes it harder to debug as it's unclear if it couldn't find the database, user does not have access, etc.
The exception message from sqlachemy is printed out to the user. This will contain appropriate error message such as `password authentication failed for "submitty_dbuser"`and the like to make it easier to debug.

[Feature:System] Improve migrator DB error output

---

.github/workflows/pr_title_check.yml

I changed the primary branch of the `pr-title-action` repository from `master` to `main`. This broke the workflow here as it still referred to master.
It now points at main.

[Testing:Developer] Fix PR title workflow using wrong branch

---

.setup/distro_setup/setup_distro.sh
.setup/distro_setup/ubuntu/18.04/setup_distro.sh
.setup/install_system.sh

Right now, as part of the installation process, we install the latest version of `pip`. While this is nice from the standpoint of having the latest and greatest, it's not so great in that it often falls behind in version anyway as upgrading through `pip` itself is a greater burden than using the mechanisms of `apt-get`.
This replaces the installation of `pip` from the pip website to use `python3-pip` instead. As we also do not do anything with python2 anymore, we do not have to worry about collisions here within the base installation.
This is not a breaking change per-se, but may warrant writing a release doc to indicate this change, as well as how one could apply this to an existing machine:
```
sudo python3 -m pip uninstall pip
sudo apt-get install python3-pip
```

[Feature:System] Move python-pip to be managed by apt-get

---

migration/migrator/data/course_tables.sql

PR #6180 did not modify the `course_tables.sql` file for the addition of its new column. This meant that new installations of Submitty would be missing the column, causing a crash on trying to use online polls.
This adds the column to our dump so that new installations will work properly for it.

[Bugfix:System] Add missing column to sql dump

---

Vagrantfile

The `ubuntu-20.04` autostarts on `vagrant up` that causes an error on port collisions for websockets between the two boxes.
`ubuntu-20.04` no longer auto-starts.

[Bugfix:Developer] Do not autostart ubuntu-20.04

---

site/app/controllers/PollController.php
site/app/templates/polls/NewPollPage.twig
site/app/views/PollView.php

Closes #6254
The edit poll form did not have a good way to preserve the previously saved image. Instructors would always have to re-upload their image every time they edited the form.
This adds a new checkbox to the edit poll form that if checked, will keep the previously saved image (if no new image is uploaded at the same time).
This PR also prints out the current image filepath. I debated having it actually show the image, as well as if we should print out some message in the case where you edit a poll without an image. I went with this for simplicity, but I welcome suggestions.
No currently uploaded image:
Previously uploaded image exists:

[Feature:SubminiPolls] Add checkbox to keep edit image

---

autograder/autograder/grade_item.py

Autograding code was errantly calling `config.log_message` rather than `config.logger.log_message`

[Bugfix:Autograding] Error when logging bad notebook objects

---

site/app/controllers/GlobalController.php
site/app/models/NavButton.php
site/tests/app/models/ButtonTester.php
site/tests/app/models/NavButtonTester.php

The `GlobalController` creates a bunch of instances of the `Button` model to set-up the left sidebar. For each instance that is created, there is some amount of boilerplate, namely that each have the same class, and that the id is usually `nav-sidebar-${title}`.
This adds a new `NavButton` model that removes a bit of boilerplate on the `Button` model as it was used in the `GlobalController` for setting up the sidebar.

[Refactor:Developer] Add simpler NavButton model

---

.setup/distro_setup/ubuntu/18.04/setup_distro.sh

Installing on Ubuntu 18.04 was failing as a couple of python dependencies relied on a much newer version of pip than what is available in the package repository. This started to happen as a result of moving to using the package repository in #6282, as well as that we do not constrain the versions of the pip packages we install.
This fixes the installation script by pinning back the version of packages to ones installable by the version of pip on 18.04, as well as installing an additional dependency as needed for onnx. Ubuntu 18.04 can now be installed upon, as tested by doing `vagrant up` with the default image.

[Bugfix:System] Fix Ubuntu 18.04 installation

---

site/app/controllers/admin/LateController.php

Closes #6313
The CSV upload feature only gives back a generic error message on failing to validate and parse the CSV. This leads to instructor confusion when they may have a slight typo somewhere within the CSV.
This improves the error feedback to give a more informative error, both on what went wrong (e.g. could not find the user id) as well as the line number it happened on. This should allow for more actionable feedback to instructors when something goes wrong.

[Bugfix:InstructorUI] Improve error feedback for invalid CSV

---

site/public/js/ta-grading-rubric.js

Fixes #6247
When an ungraded component is open, the cancel button does not work, and it throws an exception on attempting to use it.
The cancel button is fixed. It now properly exits out of the ungraded component, leaving it ungraded. Additionally, if the custom mark has any text in it, it will also show a confirmation on discarding changes, similar for how it works for graded components.
On viewing the diff, it's suggested to hit the cog icon to hide whitespace changes.

[Bugfix:TAGrading] Fix canceling ungraded component

---

site/app/templates/officeHoursQueue/QueueFooter.twig

Fixes #6349 
On loading the Office Hours queue page as a student, there are two possible JS errors that are thrown. The first is the one mentioned in the above issue. The second is building a binding to the notification alert on/off button. Both of these errors are a result of the elements not existing for students.
Wraps the code with a twig if statement such that the code is only triggered for a grader. This isn't necessarily the cleanest solution, which would be breaking the JS into its own file and only loading what is needed for a student vs grader, but quickest to fix the bug, and have the page cleanly load.

[Bugfix:HelpQueue] Fix JS error on opening page as student

---

site/public/js/sql-toolbox.js

If the query does not return any results, then nothing is shown to the user at all. This can lead to confusion on if the page worked at all, or otherwise.
The page will now show a new message if the returned result set is empty:

[Bugfix:InstructorUI] Show message for empty results

---

site/composer.json
site/composer.lock

The `doctrine/cache` dependency is unused, but specified in the `composer.json` file. With #6371 bumping it to a new major version with no changelog, I dug into it and it turns out, `doctrine/cache` has been deprecated, and suggested that developers remove dependency on it if possible. Looking into Submitty and why we had it, it looks like it was included as part of #3743 and used in an earlier iteration of it, but was then dropped from usage as the PR evolved, and went unused.
Removes the dependency as it's not used anywhere and none of our other dependencies directly depend on it.

[Dependency] Remove unused doctrine/cache dependency

---

.setup/install_submitty/install_site.sh

npm@7 modifies the package-lock.json file on installation by default, even if it's just modifying the last-modified timestamp on the file. This messes up the installer such that it would then always detect a change in the package-lock.json file, and so always run `npm install` and then always do the full chmod / chown process over the directories, which is a bit costly on time.
We add the `--no-save` flag to `npm install` which changes its behavior to never modify the package-lock.json file on installation. This avoids the issue above so that the `package-lock.json` file should always match what was copied in from the git repo, and avoid the unnecessary and timely npm install / chmod / chown steps if they're not necessary.

[Bugfix:System] Do not write package-lock on install

---

site/app/templates/admin/users/GraderList.twig

The category row in the table does not span all the columns when there are no graders in a category.
The row now extends to the 8th column well.

[UI/UX:InstructorUI] Fix row header on Manage Graders page

---

migration/migrator/migrations/course/20210513192238_polls_directory_bugfix.py
migration/migrator/migrations/system/20210513192238_polls_directory_bugfix.py
sbin/create_course.sh

PR #6180 included a migration to add the uploads/polls directory for existing courses, but missed adding this directory for new courses (and new installations).

[Bugfix:SubminiPolls] polls dir for new course/install

---

site/public/css/electronic.css
site/public/js/ta-grading.js

An extra margin is added when the TA grading interface is split into two panes.
Fixes the gap around the edges of the grading interface when split into two panes.
Fixes #6398

[UI/UX:TAGrading] Fix spacing issue between panels

---

more_autograding_examples/iclicker_upload/config/config.json

Closes #6285
The iclicker_upload config was failing validation, due to the `actual_file` field that was under the `testcases` object.
The `actual_file` field was removed here as it did not belong. This field is only needed in the validators section (where it is present) and has no effect being placed at this top level.
Tested by compiling the configuration and running the complete config against our schema validator. It failed validation before this change and then passed after it.

[Bugfix:InstructorUI] Remove field from iclicker config

---

.editorconfig
.github/workflows/submitty_ci.yml
.gitignore
.setup/install_submitty/install_site.sh
site/.babelrc.json
site/.eslintrc.json
site/app/libraries/Output.php
site/app/templates/GlobalFooter.twig
site/app/templates/admin/SqlToolbox.twig
site/app/views/GlobalView.php
site/app/views/admin/SqlToolboxView.php
site/jest.config.js
site/package-lock.json
site/package.json
site/phpstan-baseline.neon
site/public/mjs/server.js
site/public/mjs/sql-toolbox.js
site/tests/app/libraries/OutputTester.php
site/tests/mjs/server.spec.js
site/tests/mjs/setupTests.js
site/tests/mjs/sql-toolbox.spec.js
site/tests/mjs/utils.js

All of our JS usage is done as old-style scripts, where they're included in the page and populate the global scope, and being called directly. While this works, it is not easily testable and includes the necessity of inserting eslint directives in each file to declare globals and what is exported, which is a frustrating experience compared to "modern" JS.
This provides a proof-of-concept for #6404, using the new SQL Toolbox page as the testbed for it. This page was converted to use JS modules. As part of this, I also include tests for these new modules to demonstrate how that would work as well. These module files are stored in the `mjs` directory (I had wanted to use the `.mjs` extension as well, but TypeScript / VSCode does not support intellicode for it), and are loaded at the end of …

[Refactor:InstructorUI] Convert sql toolbox to use mjs

---

site/app/libraries/Utils.php
site/phpstan-baseline.neon
site/tests/app/libraries/UtilsTester.php

The Utilss library class hand a handful of phpstan errors that were ignored.
This fixes the phpstan errors in the file. Additionally, `stripStringFromArray` was not used anywhere in the codebase so it was removed.

[Refactor:Developer] Fix phpstan errors in Utils

---

site/app/templates/polls/NewPollPage.twig

In the instructor's Edit Poll/New Poll page, the "up", "down" and "delete" buttons for the responses wrap around when the width of the page is decreased. 
The text field adjusts to the width of the page and the buttons always stay on the same row to the right of the response in the Edit Poll page.

[UI/UX:SubminiPolls] Fix Icons wrapping in Edit Poll

---

site/app/controllers/admin/PlagiarismController.php

Currently, if you enter a gradeable on the plagiarism detection interface and select User 1, an error pops up saying that the file cannot be found.
This change fixes a typo which resulted in the page not being displayed properly.

[Bugfix:Plagiarism] Fix plagiarism not displaying files

---

site/app/templates/polls/AllPollsPageInstructor.twig
site/app/templates/polls/AllPollsPageStudent.twig
site/public/css/server.css

Addresses issue https://github.com/Submitty/Submitty/issues/6036
The student view has the titles centered, while the instructor's are left justified. The titles in the instructor's page are forced to wrap earlier than necessary around the "edit" and "delete" icons.
Titles have been left-aligned and the widths of the columns have been adjusted. The titles in the instructor's page no longer wrap around unnecessarily.

[UI/UX:SubminiPolls] Improve summary page UI

---

site/app/templates/officeHoursQueue/QueueFooter.twig

Any time an announcement is updated, all student currently viewing the queue page have some of their page elements deleted.
The announcement is updated without deleting anything.
Fixes #6448 
Tested on Chrome and Firefox

[Bugfix:HelpQueue] Fix changing announcement breaking student page

---

site/public/css/forum.css

Fixes #5874
Currently, there are no borders on discussion forum posts/threads in dark mode.
Light gray borders have been added to each unimportant post in dark mode.

[UI/UX:Forum] Fix forum post border in dark mode

---

site/app/templates/grading/electronic/StudentInformationPanel.twig
site/app/templates/grading/electronic/SubmissionPanel.twig
site/public/css/electronic.css

The "student info" and "student submission/result browser" panels in the TA Grading interface are missing some padding, and the buttons in the submission panel overlap when they are force to wrap around
Padding added to the panels in the TA Grading interface. Works in all configurations of the page

[UI/UX:TAGrading] Add padding to TA grading panels

---

site/public/css/electronic.css
site/public/js/resizable-panels.js

The drag bars between panes in the TA grading interface currently blur when hovered over.  The animation is slow and looks strange.
This PR changes the animation to make the drag bars change in size.  The animation is faster and more subtle but also clearly indicates to the user that they are able to be dragged.

[UI/UX:TAGrading] Adjust hover animation for drag bars

---

site/app/templates/forum/ForumBar.twig
site/app/templates/forum/showFullThreadsPage.twig
site/app/views/forum/ForumThreadView.php

Fixes #6049.
This change makes the "Edit Categories" menu option link to the correct page when viewing the wide forum view and prevents that menu option from opening new tabs on all views.  In addition, Bootstrap separators were fixed to be compatible with Bootstrap 2 and now display properly.

[Bugfix:Forum] Fix edit categories button bug

---

site/app/templates/polls/NewPollPage.twig

Addresses comment in https://github.com/Submitty/Submitty/issues/6036
The "set release date" field in the instructor's New Poll/Edit Poll page shows a dropdown over the calendar popup that makes it impossible to interact with the calendar.
The dropdown for autocomplete is disabled.
Tested on Windows/Chrome,Firefox

[Bugfix:SubminiPolls] Turn off Autocomplete for Poll Date

---

site/app/templates/polls/NewPollPage.twig
site/public/css/polls.css

Fixes #6444
Makes the border around buttons on the edit polls UI turn white in dark mode.  This update also switches the arrows to proper icons.

[UI/UX:SubminiPolls] Fix poll edit buttons in dark mode

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20210521144614_remove_course_sessions.py

For a number of years the sessions table in the course database has been empty.  
This critical data is instead stored in a similarly named table in the master database.  
This PR removes this empty, legacy table.

[Refactor:System] remove sessions table from course DB

---

site/public/js/ta-grading-rubric.js

When in dark mode and clicking on the points input box the background color will change to white. The text is also white so it isn't possible to see how many points is actually in that box.
Fixes #6478 
Now the JavaScript sets the CSS defined background color for an input box which will look correct in light or dark mode.

[UI/UX:InstructorUI] Fix rubric points input background color

---

site/app/libraries/database/DatabaseQueries.php
site/app/models/PollModel.php

The future polls section shows the polls with the furthest out poll at the top and the closest poll at the bottom.
The future polls are now in ascending order with the closest poll appearing first.
I tested by making a ton of poles with different dates and it works perfectly.
I had to comment out @method array getAnswers() in the poll model because it was saying getAnswers was already defined.
It had no effect on anything but it got rid of the error

[Bugfix:SubminiPolls] past polls now in ascending order

---

site/app/views/admin/PlagiarismView.php

When viewing a gradeable in Lichen, the breadcrumb path does not update to reflect the current location.  This also means that there are no ways to get back to the previous page via the UI.
This update adds an additional location in the breadcrumb path to make it easier to get back to the previous page.

[UI/UX:Plagiarism] Add gradeable name to breadcrumb path

---

site/app/templates/notebook/Notebook.twig

Fixes #6485 
Currently, short answer fields in notebook gradeables don't change their text's theme based on the site's theme. This leads to low contrast black text on dark backgrounds.
The text now uses Eclipse theme for light mode, and Monokai for dark/black mode.

[UI/UX:Submission] Fix low contrast short answer fields

---

.setup/distro_setup/ubuntu/20.04/setup_distro.sh

Java 8 was missing from the install for Ubuntu 20.04.
Java 8 is present. Given that we still want this for local testing purposes for the integration suite, re-adding this here.

[Bugfix:System] Add missing java8 to ubuntu-20.04

---

site/public/css/sql-toolbox.css

Closes https://github.com/Submitty/Submitty/issues/6373
The horizontal scroll bar fits to the box container that surrounds the output table instead of the scroll bar fitting to the whole page. 
Screenshot (cut because the page is long):

[UI/UX:InstructorUI] Add scrollbar to SQL toolbox table

---

site/app/views/grading/ElectronicGraderView.php
site/public/css/electronic.css
site/public/js/ta-grading.js

Fixes #6368
Currently when someone opens the ta grading page for the first time, a blank grey panel is displayed with no instructions.
This could be confusing to first time users.
Now there is a message displayed that tells users to click on the buttons above to get a panel to display. I wasn't able to get the message to display in multiple panels but first time users will only have 1 panel displayed anyway. The message appears and disappears based on if the user has an active panel or not.
Although it the message won't display in every panel, Barb told me to go ahead with this PR and then if someone else thinks they can tackle it later, they can.

[Feature:TAGrading] display message if no panel is selected

---

site/app/controllers/calendar/CalendarController.php
site/app/models/CalendarInfo.php
site/app/models/gradeable/GradeableList.php
site/app/models/gradeable/GradeableUtils.php
site/app/views/NavigationView.php
site/public/css/calendar.css
site/public/js/calendar.js

* [✅] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [✅] Tests for the changes have been added/updated (if possible)
* [✅] Documentation has been updated/added if relevant
Color of items on calendar is based on the due time and the actual time of user (open/due/graded).
Color of items on calendar is now showing the actual status of the submission, submit/resubmit/late submit/team lock/grades released but not viewed/etc.
Some refactors on `NavigationView` that getting submission buttons function and getting team buttons function are now static.
Some refactors on `GradeableList` that getting the section a gradeable belongs is static
A new utility class `GradeableUtils` is created that will handle loading gradeables information from …

[Bugfix:Submission] Show actual submission status on calendar

---

site/app/controllers/admin/AdminGradeableController.php
site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig

When creating a checkpoint or numeric gradeable, once you go into Grader Assignment there is an option to set Limited Access graders as blinded or unblinded. No matter which option you pick it never gets a value set.
Closes #6231 
Only electronic gradeables should be able to have this option so for a checkpoint or numeric gradeable this option is never shown the the instructor.

[Bugfix:InstructorUI] Fix Anonymized Option Gradeables

---

site/app/controllers/admin/PlagiarismController.php
site/app/libraries/database/DatabaseQueries.php
site/app/templates/plagiarism/Plagiarism.twig
site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
site/app/views/admin/PlagiarismView.php
site/public/css/plagiarism.css

Closes #2618
This pull request:
- Changes the interface of the Lichen homepage to feature a table with more distinct rows
- Adds the due date under each gradeable on the Lichen homepage
- Sorts the gradeables on the Lichen homepage by due date
- Adds the due date for each gradeable on the gradeable configuration page
- Sorts the list in the gradeable configuration page by due date
Before:
After:

[UI/UX:Plagiarism] Make due date more visible

---

site/app/controllers/admin/LateController.php
site/app/libraries/database/DatabaseQueries.php
site/app/templates/admin/LateDays.twig

When attempting to add late days to a student, the current behavior is to overwrite the number of late days with the number of late days entered.
This update clarifies that the number of late days is the number of *additional* late days and fixes the bug which resulted in the late days being overwritten each time.
Fixes #6377

[Bugfix:InstructorUI] Add late days instead of overwriting

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20210521231204_team_id_constraint.py

Closes #2371 
There was already a unique key constraint between user_id and g_id in the gradeable_data table, but not between team_id and g_id, which means we could have multiple grades for a team despite only allowingone grade per individual.

[Bugfix:TAGrading] Add unique constraint to gradeable_data

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/templates/grading/electronic/Details.twig
site/app/views/grading/ElectronicGraderView.php
site/public/js/details.js

If a TA enables anonymous mode for a gradeable and then leaves the page, when they come back anonymous mode if off again. Anonymous mode is determined in the url eg. (anon_mode=1 or anon_mode=0).
A cookie is set when a TA enables anonymous mode so anonymous mode will always be turned on for that gradeable until they turn it off. The url is no longer used to convey information about anonymous mode.
I tested by  messing around with the gradeables in the sample course and toggling anonymous mode on and off. It worked for every assignment.

[Bugfix:TAGrading] Added cookie to remember anonymous mode

---

migration/migrator/migrations/course/20210521231204_team_id_constraint.py

The migration to add the unique constraint to gradeable_data has an issue where the `DROP CONSTRAINT` would error out if `g_id_gd_team_id_unique` did not exist.
We use a `IF EXISTS` to guard on the constraint drop so that the migration will not error if it does not exist.

[Bugfix:System] Add guard on constraint drop

---

site/app/templates/forum/ShowCategories.twig
site/public/css/forum.css

- Header is not centered
- "Edit, delete" buttons are impossible to see in dark mode
- When a new category is created, the "edit" button does not work
- Centered header
- Color scheme changed to make the text  and icons easy to see in all color themes, even when editing the category name
- Page refreshes when a new category is added and all functionalities work; repetitive code removed
- Added padding to the bottom of the page

[UI/UX:Forum] Manage Categories Page UI Improvements

---

site/public/css/electronic.css
site/public/templates/grading/OverallComment.twig

When typing a long comment in the 'overall comment' section of the TA grading rubric, the comment box autogrows on keyup which causes a glitch that makes it nearly impossible to see what you are typing when you reach a 12-15 line comment.
https://user-images.githubusercontent.com/66340271/119516555-d9891e80-bd44-11eb-8b6c-652c86f626ce.mp4
Now the box just grows when you need a new line so there are no glitches and no matter how long of a comment it is, you will always be able to see what you're typing.
fixes #3633 
https://user-images.githubusercontent.com/66340271/119519187-3980c480-bd47-11eb-8519-403580c834e2.mp4
After a lot of tweaks the best fix turned out to be changing onkeyup to onkeydown. 
This change works perfectly on chrome, perfect on edge but is slightly glitchy on Firefox. …

[Bugfix:TAGrading] fixed autogrow

---

site/app/templates/NotificationSettings.twig
site/public/js/forum.js
site/public/js/server.js

Fixes #6526
Currently, alerts from the grade override page, forum, and notification settings page are unable to be closed and have improper styling.
The alerts have been updated to match the behavior and styling of alerts on the rest of the site.

[Bugfix:InstructorUI] Fix Alerts Unable to be Closed

---

.github/workflows/vagrant_up.yaml
Vagrantfile

The vagrant up CI job is failing due to some issue mounting the shared directory.
This may be related to some botched operation by vbguest when run in the context of the CI. To help here, I am adding a flag to the vagrantfile to allow skipping ensuring that vbguest is installed, and then using that in CI to skip it as well.

[Testing:Developer] Skip vbguest in CI

---

site/public/css/bootstrap.css
site/public/css/colors.css
site/public/css/officeHoursQueue.css
site/public/css/server.css

Fixes #6512 
Contrast issues currently exist in the following places:
* _(DARK MODE)_ Hotkey Settings menu found on the Grade page of a Lab (checkpoint) gradeable.
* _(DARK MODE)_ Office Hours Announcement
* _(DARK MODE)_ Closing X button on any alert-error or alert-success (ex. Go to Late Days page as instructor and submit data to see).
* The ```--standard-dark-gray``` color is broken
* _(DARK MODE)_ Hotkey Settings Menu contrast is fixed.
* _(DARK MODE)_ Office Hours Announcement contrast has been improved to a 7:1 ratio
* Closing X button color now matches alert type (red for errors, green for success) in all site themes
* The ```--standard-dark-gray``` color is fixed. Some places that previously used this color incorrectly had their colors changed to the actual color they were …

[UI/UX:InstructorUI] Collection of Contrast Fixes

---

site/app/views/grading/ElectronicGraderView.php
site/public/css/electronic.css

Fixes #6397 
Keeps the error message banner aligned in the middle for all views options. Header panel is also aligned now.
Also made the banner automatically size to fit the content, and also adding padding to the banner.
Automatically sizing the banner to fit the content

[UI/UX:InstructorUI] Off-Center Error Banner

---

site/public/js/ta-grading.js

Fixes #6509 
Checking the auto open checkbox on the TA Grading page has no effect when moving between students.
The auto open checkbox now works and reopens folders that were open on the previous student.

[Bugfix:TAGrading] Fix auto open button not working

---

site/app/templates/grading/electronic/SubmissionPanel.twig
site/public/js/ta-grading.js

Fixes #4525 
It was possible to produce a bug where when viewing the files submitted by a student in a gradeable, the frame for the file only shows half of a line.  The bug is also not fixable on the client's side without reloading the page or editing the html elements. The steps to produce this is the following:
1. Go to the grading interface as a TA for a student
2. Open the files panel in any panel viewing mode
3. Open the Submissions folder
4. Click the Open/Close Submissions button
5. Open the Submissions folder again
6. Each file is now displayed with only half a line of display
The bug is fixed and following the above steps does not automatically open the files when you open the submissions folder a second time.
When you open the Submissions folder a second time:
When you open each …

[Bugfix:TAGrading] Submission file half line bug

---

site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
site/public/css/plagiarism.css

Fixes #6508 
Entering invalid inputs (Threshold and Sequence length) in the plagiarism configuration screen doesn't register the inputs as invalid or change their background color. You just receive an alert that at least one of them is invalid when you submit the form.
* Inputs (Threshold and Sequence Length) will now be marked as invalid and have their background color changed. 
* A tooltip will appear under the field with the invalid input when trying to submit.
* Colors are contrast-friendly on all site themes

[Bugfix:Plagiarism] Display Plagiarism Config Invalid Inputs

---

site/app/libraries/database/DatabaseQueries.php

If you log in as an instructor and go to office hours queue => view queue stats => view student specific stats, the page doesn't load and throws an ugly error.
The page loads properly

[Bugfix:HelpQueue] individual queue usage stats page

---

site/public/css/admin-gradeable.css

Fixes #6503 
Currently, the Download Zip button text on the grading page is black.
The text now adapts to the site theme.

[UI/UX:TAGrading] Fix Zip Button Contrast in Dark Mode

---

site/app/templates/GlobalHeader.twig
site/public/css/global.css
tests/e2e/test_sidebar.py

This update changes the breadcrumb separator to a proper icon instead of the original ">" character.  This update also adds the .centered-icon class to the global CSS file since centering FA icons is a common task which I don't believe has been added elsewhere in the CSS thus far.
The ">" character is currently inserted between locations in the breadcrumb path.
Inserts a small angle between locations in the breadcrumb path.  The icon looks somewhat cleaner than a text-based navigation cue.

[UI/UX:System] Improve Breadcrumb UI

---

site/public/js/server.js

Images in TA grading under "Submissions and Results Browser" and "Notebook" panels (+student notebook) that are from openFrame (file submission) are full size; large images will result in scroll bars.
Fixes #6383 
Images now have a max width of the parent container (no more horizontal bars)

[Bugfix:TAGrading] Notebook image width scaling

---

site/app/templates/forum/CreatePost.twig
site/app/templates/forum/RenderPost.twig
site/public/css/forum.css

Partially #5884 
Forum posts do not inherit markdown styling rules from the new standard set of markdown styling rules.
Forum posts inherit markdown styling rules from the new standard set of markdown styling rules.

[Bugfix:Forum] Standardize styling for markdown posts

---

site/app/templates/polls/AllPollsPageInstructor.twig
site/app/templates/polls/AllPollsPageStudent.twig
site/public/css/polls.css
site/public/js/polls-dropdown.js

The chevrons on the polls page are hard to see in dark mode.
Fixes #6452

[UI/UX:SubminiPolls] Make chevrons more visible in dark mode

---

site/public/css/admin-gradeable.css
site/public/css/userform.css
site/public/js/admin-gradeable-updates.js

Fixes #6499 
Same solution as #6454 
Currently, the contrast for invalid fields on the instructor create/edit gradeable page has poor contrast.
- Contrast is improved.
- Invalid fields are now marked with invalid selector to improve accessibility.
- Fixes a bug introduced in #6454 where dark mode styling was applied in light mode.

[UI/UX:InstructorUI] Fix Invalid Contrast on Admin Gradeable

---

sbin/run_lichen_plagiarism.py

Currently, an error occurs in the lichen run log when re-running plagiarism detection on an existing gradeable.  The gradeable disappears from the list of configured gradeables but is unable to be reconfigured.  From the client side, it appears to simply disappear altogether.  This is due to an error in `sbin/run_lichen_plagiarism.py` which causes some files to be deleted and some to not be deleted.
The code currently has logic which attempts to not rehash files when re-running a gradeable.  This logic is partially broken and incomplete.
This PR removes unnecessary, buggy, logic from `sbin/run_lichen_plagiarism.py`.  When re-running plagiarism, the code now hashes and concatenates all of the submissions again, all the time.  Concatenating and hashing take less than 2% of the total running …

[Bugfix:Plagiarism] Fix bug when re-running plagiarism

---

site/app/templates/forum/ForumBar.twig
site/public/js/forum.js

Fixes #6445 
Currently, the Attachments dropdown button in discussion forum threads can only be used to open all attachments.
The Attachments drop down button toggles between showing and hiding all attachments. It keeps track of whether it has shown or hidden all last time, so if all are hidden and one is individually shown, then pressing the toggle will show all, not hide one and show the others.
When testing this PR, specifically try combinations such as showing/hiding all and then individually toggling an attachment and make sure they never get unlinked (clicking the Attachments button shows some and hides others, etc).

[Bugfix:Forum] Fix Attachment Button not Toggling 

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/templates/grading/electronic/NavigationBar.twig
site/app/views/grading/ElectronicGraderView.php
site/public/css/electronic.css
site/public/js/ta-grading.js

Currently if a TA, peer or instructor is grading an assignment the only place they can see the name of the person or team they are grading is in the student info tab. For peers however, the student info tab is not available (by design) so they might have no way of knowing who they are grading. 
Now as long as blind grading and anonymous mode are disabled, the name/names of the student or team being graded will be displayed on the TA Grading navigation bar. For peer grading, if single or double blind grading are enabled by the instructor, the name will not be displayed. We made a design choice to make the name go away if the user chooses a panel layout where there is a full left column because it shrinks the nav bar by 50% and there is no longer room for the names to be displayed.
While …

[Feature:TAGrading] display name of student being graded

---

site/app/views/grading/ElectronicGraderView.php

Currently If an instructor configures a peer gradeable to be an unblinded or single blinded grading assignment, when a TA is on the student details page of the grading interface and they click enable anonymous mode, the format of the page changes but the names are still displayed instead of hashes.
Anonymous mode works as expected for all peer gradeables.
How to test:
On master,
As an instructor configure or edit a peer gradeable to be unblind or single blind
log in as a TA and switch toggle anonymous mode.
See error
On peer-anon-bug branch,
As an instructor configure or edit a peer gradeable to be unblind or single blind
log in as a TA and switch toggle anonymous mode.
See results

[Bugfix:TAGrading] fixed anonymous mode for peer gradeables

---

site/app/templates/Navigation.twig
site/public/css/navigation.css

The "no assignments posted" message that is displayed in the Gradeables page when there are no available gradeables is missing some padding
Padding is added, and the message is now aligned with the "Gradeables" title.

[UI/UX:InstructorUI] "no assignments posted" Message Style

---

site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
site/public/css/admin-gradeable.css
site/public/css/server.css

Closes #6239
When creating a gradeable, on the "Submissions/Autograding" tab, no drop-down list with options for the gradable configuration is shown. No arrow is displayed either.
The bug is now fixed such that the drop-down and the arrow are accessible on both Firefox and Chrome. Switched from datalist to custom CSS classes to ensure it behaves as intended on Firefox. As such the UI will be slightly different from the previous version. For example, the option is now highlighted by blue when you hover over it.
Drop-down menu

[UI/UX:InstructorUI] No option gradeable config

---

site/app/templates/autograding/AutoChecks.twig

Visualize whitespace button appears on all AutoChecks with output (on actual).
Fixes #6182 
Visualize whitespace button only appears on AutoChecks with a type of "text" on actual.

[Bugfix:Submission] Visualize whitespace only on text

---

site/app/templates/grading/electronic/GradingPanelHeader.twig
site/app/templates/grading/electronic/RubricPanel.twig
site/app/views/grading/ElectronicGraderView.php
site/public/css/electronic.css
site/public/js/gradeable.js
site/public/js/ta-grading-rubric.js

Fixes #6366
Currently when peer grading is enabled for a gradable and there are both student components and ta components, a peer grader is able to see both the student components and the ta components in the solution/ta notes panel. In addition, peer graders have access to the grading inquiry panel through the grading inquiry button at the top. In the rubric panel, the peer grader and ta also sees both comments to the students and ta's.
The peer graders no longer sees the grading inquiry button, comments in the grading rubric panel now shows to different user groups accordingly. The peer graders also no longer sees ta components in the  solution/ta notes panel.
In TA's point of view 
where TA only is a TA component
In the peer grader's point of view for the same gradeable
I tested by …

[Bugfix:TAGrading] Peer grading ta and student notes shown

---

site/app/templates/forum/displayThreadList.twig
site/public/css/colors.css
site/public/css/forum.css
site/public/css/notebook-builder.css
site/public/css/rainbow-customization.css
site/public/css/server.css

Fixes #6543 
Currently, in dark mode new/unread posts/threads are marked by a background color that is barely different from the main site background color.
* The viewed-content color has been adjusted to give better contrast in dark mode

[VPAT:Forum] Improve New Post Background in Dark Mode

---

site/app/templates/grading/electronic/Details.twig
site/app/templates/grading/electronic/NavigationBar.twig
site/public/css/electronic.css
site/public/js/ta-grading.js

1. On the details page, The autograding & grading column are left justified in anon mode but centered in non-anon mode.
2. In 2 column mode, in non-anon mode, the layout seems to leave room for the student name (so the first row of buttons isn't center, it's got extra space on the left side
3. Team/student names were still displaying in 2 column mode if you enabled full screen mode.
1. On the details page, The autograding & grading column are now always centered.
2.In 2 column mode, the navbar is always centered.
3. Student/team names are never displayed in 2 column mode, regardless of full screen mode.
There were other issues with centering/spacing not mentioned in the issue that this PR is linked too. In order to fix all of the centering issues the only fix was to make the names appear …

[Bugfix:TAGrading] fixed Anon mode bugs

---

.setup/distro_setup/setup_distro.sh

The `setup_distro.sh` script, as it's sourced by `install_system.sh`, was overwriting the value of `CURRENT_DIR` that's set in the latter, which would lead to surprising behavior on trying to use it.
This fixes this collision by giving the variable a new name within the `setup_distro.sh` script, and also adding a note about the potential of this collision. While a better strategy would be to move away from sourcing these files, we do currently utilize a number of variables set here and in the specific distro file during installation.

[Bugfix:System] Fix variable collision in install script

---

.setup/install_system.sh
.setup/pip/system_requirements.txt

There was a bug introduced in #6399 where an invalid version of onnxruntime was used for Ubuntu 18.04 and an improper path was used for referencing the pip requirements file.
This PR fixes the path reference to the pip requirements file, as well as pins `onnxruntime` to a version that is supported on Ubuntu 18.04 and 20.04. Newer versions look to require something that's not available out of the box on 18.04, but did not look too deeply into this. On dropping support for Ubuntu 18.04, we can look to upgrade the dependency.
Manually ran the `vagrant up` action to ensure this fixes things: https://github.com/Submitty/Submitty/actions/runs/922053172

[Bugfix:System] Fix pip install on vagrant up

---

site/app/templates/plagiarism/Plagiarism.twig
site/public/css/plagiarism.css

In the Plagiarism  Results page, if no gradeables have been configured, a table with one row containing the column headers is displayed with no additional explanation.
If there is no information to display yet, the table is not created

[UI/UX:Plagiarism] Add "No Content" Message

---

site/app/controllers/admin/UsersController.php

Fixes #6587 
The warning would occur on trying to delete a registration section for a course that had no course materials. This is due to the course materials JSON file missing as it gets generated on the first time a course material is added.
Adds a file existence check around the course materials file, checking if it exists before attempting to open and read from it.

[Bugfix:InstructorUI] Fix warning on deleting reg section

---

site/app/templates/grading/electronic/SubmissionPanel.twig
site/app/templates/misc/Code.twig
site/public/js/server.js
site/public/js/ta-grading.js

Viewing a file using the full panel icon does not work.
When a file is rapidly clicked twice (so it finishes loading while the iframe for the file is closed), the height is very small when opened back up. 
When using the Open/Close Submissions/Results buttons, instead of opening and closing all of them it inverts the open and closed state for the most part.
Viewing a file using the full panel icon now works.
When a file is rapidly clicked twice, an observer observes the iframe until it is opened up again to properly resize it.
When using the Open/Close Submissions/Results buttons, it fully opens/closes the child items.

[Bugfix:TAGrading] Fix full panel view and file view height

---

site/app/views/admin/ReportView.php

Currently, in dark mode, the text in most table cells is white. This makes some cells very hard or impossible to read.
The text in the cells is always black (since the other colors of the rainbow grades summary don't change, neither should the text).

[UI/UX:InstructorUI] Fix contrast on Gradebook in Dark Mode

---

site/app/views/admin/PlagiarismView.php

Fixes issue mentioned in https://github.com/Submitty/Submitty/issues/6568
The data depends on the timestamp of a file whose location has been changed due to refactoring of Lichen.
The columns now display the right information.

[Bugfix:Plagiarism] Fix N/A Columns in Summary Table

---

.github/workflows/vagrant_up.yaml

If one job in the vagrant CI fails, the other job will be immediately killed. Usually one of the builds failing is due to spurious Ubuntu mirror problems than anything, and would still be useful to have the other job run to completion so we have a signal of "the CI failed, but it was just one job, and so probably just spurious error".
Do not fail fast the CI build, so that if one build fails, the other will keep on going until success or failure on its own.

[Testing:Developer] Do not fail fast vagrant CI

---

site/app/controllers/admin/PlagiarismController.php

It is currently possible to trigger an assertion failure in `compare_matches.cpp` from the UI by setting a sequence length of 1.
This PR changes the minimum allowable sequence length to 2 to bring the PHP into alignment with the C++ backend.
Fixes part of #6568

[Bugfix:Plagiarism] Fix sequence length error checking

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20210608141409_late_day_date.py
site/app/controllers/admin/LateController.php
site/app/models/DateTimeFormat.php
site/app/models/SimpleLateUser.php
site/app/templates/admin/LateDays.twig
site/tests/app/models/SimpleLateUserTester.php

Currently late days are stored with a full timestamp.
Closes #6053
Late days are now only stored with a date. The precision down to the second is not needed for late days.
This does change all timestamps for late days into a date by casting it.

[Bugfix:InstructorUI] Change Late Day Timestamps to Dates

---

site/app/templates/admin/PlagiarismHighlightingKey.twig
site/public/css/plagiarism.css

Fixes #6610 
There are no borders behind the icons in the plagiarism highlighting key, making white invisible on light mode.
There are now text shadows on light mode to help differentiate the icons from the background

[UI/UX:InstructorUI] Add borders to Plagiarism Highlight Key

---

site/public/js/forum.js

Fixes #6613 
When submitting a post or creating a thread on the discussion forum, you can create multiple duplicate posts/threads by clicking the submit button multiple times before the page reloads.
The Submit Reply and Publish Thread buttons will now be disabled after being clicked on once, so that the form can't be submitted multiple times.

[Bugfix:Forum] Prevent spamming duplicate posts

---

.github/PULL_REQUEST_TEMPLATE.md

As discussed in https://github.com/Submitty/Lichen/pull/35, since we now have a github action for the "PR Title Check", this manual check is not necessary anymore.
The Lichen PR was meant to add a PR template to the repo, and for consistency, the manual title check is removed in the main Submitty repo as well.

[Documentation:Developer] Remove PR title check in template

---

bin/json_schemas/complete_config_schema.json
python_submitty_utils/tests/data/complete_configs/tutorial_14_tkinter.json
python_submitty_utils/tests/data/complete_configs/tutorial_15_glfw.json

Fixes #6287
The `tutorial/14_tkinter` and `tutorial/15_gfwl` schemas are failing validation where the it's not failing a matching action block for the `move mouse` and `click and drag` actions.
The schemas now pass validation. The `click and drag` action block mandated that a number of properties are required, though the description and usage of these properties mark them as optional (defaulting to 0 if not present). The `move mouse` block was incorrectly set-up such that it used the word `action` several times instead of the appropriate property names.
Complete configs for the two failing tutorials have been added here and are used to validate the validator behavior.

[Bugfix:Autograding] Fix schema validation for mouse actions

---

bin/json_schemas/complete_config_schema.json
grading/load_config_json.cpp

Closes #6286
The `test_notes_upload*` autograding examples were failing config validation due to the presence of a `pattern` field at the top level of a testcase instead of just contained within the `pre_commands` section, for example:
```json
{
"containers": [
{
"commands": [
"mv test_template.pdf student_test_template.pdf",
"pdflatex blank_page.tex",
"python3 separate_pages.py 2",
"pdflatex test_template.tex"
],
"container_image": "submitty/autograding-default:latest",
"container_name": "container0",
"number_of_ports": 1,
"outgoing_connections": [],
"server": false
}
],
"details": "",
"dispatcher_actions": [],
"extra_credit": false,
"hidden": false,
"pattern": "",
"points": 1,
"pre_commands": [
{
"command": "cp",
"destination": ".",
"option": "-R",
"pattern": null,
"source": …
```

[Bugfix:Autograding] Fix pattern default in config

---

migration/migrator/migrations/course/20210608141409_late_day_date.py

Currently when the migration for #6603 is run, if duplicate dates exist the migration will fail.
Now before all the timestamps are casted to dates they will be checked for duplicates. Any duplicates will be deleted leaving only the last late day timestamp in that day.

[Bugfix:InstructorUI] Delete Duplicate Timestamp Dates

---

site/app/templates/forum/ForumBar.twig
site/public/css/bootstrap.css
site/public/css/server.css

Fixes #6618
Currently, the bootstrap dropdown-menu class is partially implemented in `server.css`, and has been modified greatly so it is difficult to use in other areas (can't just simply use dropdown-menu class like bootstrap docs suggests).
Dropdown related classes have been added to `bootstrap.css` and Submitty specific overrides have been specified in `server.css`. The only place previously using this class (More dropdown on discussion forum) has been adjusted to use the proper layout. 
Now, following [this simple format](https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropdowns), dropdown menus can easily be added.
Also, there is now support for split buttons and [split button dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropd …

[Refactor:Forum] Add proper bootstrap dropdown support

---

site/app/controllers/admin/PlagiarismController.php
site/app/views/admin/PlagiarismView.php

Viewing the results of a plagiarism detection run on a team gradeable induces errors which are not dealt with gracefully. The plagiarism backend attempts to grab the first and last name that correspond to the the student_id from the Lichen output files, so when the id correspond to a team instead of a student, the page breaks.
The backend was modified to not query the student first and last name for team gradeables, and for now, the dropdown menu displaying the top matched submissions does not display the names of the students in the teams, but only the team id.

[Bugfix:Plagiarism] Fix plagiarism view results for teams

---

site/app/controllers/admin/PlagiarismController.php
site/app/views/admin/PlagiarismView.php

Currently, if an error occurs while running Lichen which results in a rankings file not being generated, gradeables will disappear from the plagiarism UI and it is impossible to delete , edit, or otherwise access the configuration.  The only way to fix this issue is to manually delete the buggy output files via the command line and create a new configuration via the UI.  This behavior is due to the Plagiarism Controller looking for a rankings file instead of a configuration file to determine which rows to display in the summary table.
This PR changes the means of determining rows to display in the summary table such that it now depends upon the existence of a configuration file.  This allows users to properly view the erroneous run log and delete or edit configured gradeables as …

[Bugfix:Plagiarism] Fix disappearing gradeables bug

---

site/public/js/ta-grading-rubric.js

Right now, clicking on other grader's comments will produce a submitty page rather than their comment.
Closes #6647
Their comment is shown with markdown rendered.

[Bugfix:TAGrading] Fix Viewing Other Comments

---

site/app/controllers/MiscController.php

Closes #5266 
Prevents loading of a SVG+XML file while TAGrading

[SECURITY][Bugfix:TAGrading] Prevent loading of SVG+XML files

---

site/app/templates/functions/Badge.twig

Fixes #4631 
Currently, components that have only penalty points will not have their badge shown even if the student has earned the penalty points. For a rubric like this:
The result is this on the student's end:
Badges from penalty only components now show if the student has earned the penalty points. All other badges remain the same.

[Bugfix:Submission] Fix Penalty Badges Not Showing

---

site/app/templates/forum/GeneratePostList.twig
site/app/templates/forum/ThreadPostForm.twig
site/app/templates/misc/AccessibilityMessage.twig
site/app/templates/misc/MarkdownArea.twig
site/public/css/server.css

Closes #5776 
* Reply boxes on the discussion forum are missing the "Press TAB to indent. Press ESC to advance from textarea" text.
* Navigating backwards (shift tab) from the bottom of the post list (reply box) there is no invisible button to go back to the first post.
* All areas that are using `misc/MarkdownArea.twig` have tabbing enabled in their textarea as well as the text "Press TAB to indent. Press ESC to advance from textarea" included above them.
* A new template `misc/AccessibilityMessage.twig` has been created to hold this text.
* Navigating backwards (only backwards!) from a reply box will show an invisible button to skip to the first post in the post list. Also, this button has been added after the reply box as well by tabbing twice.

[UI/UX:Forum] Improve forum keyboard navigation

---

site/app/controllers/admin/PlagiarismController.php
site/app/templates/plagiarism/Plagiarism.twig

The plagiarism main page currently refreshes every 5 seconds when waiting for a run to finish.  This can be annoying to instructors who are trying to view the run log or interact with the page in other ways.
This PR makes the page only refresh when all of the outstanding runs are complete.  JS runs behind the scenes to check for changes and reload as appropriate.

[Bugfix:Plagiarism] Fix reloading issue

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/libraries/database/DatabaseQueries.php
site/app/models/GradingOrder.php
site/public/js/ta-grading-keymap.js
site/public/js/ta-grading.js

No prev/next inquiry option for switching between students in TA grading.
Closes #4765 
Prev/next inquiry and active inquiry options added for switching between students in TA grading.
If a component is open, the prev/next student for inquiries is found based on the component id (searches for unlinked regrade requests and regrade requests with the specified component id). Otherwise, it will just find the prev/next student with a grade inquiry.
Refactored filtering to make it easier to add more filters in the future.

[Feature:TAGrading] Prev/next student by (active) inquiry

---

.github/workflows/vagrant_up.yaml
Vagrantfile

Currently we use the vbguest plugin in vagrant. This is no longer necessary and creating issues while installing Ubuntu 20.04.
This PR removes the check for requiring vbguest.
To test make sure you remove vbguest from your system.
This can be done by doing: `vagrant plugin uninstall vagrant-vbguest`
Docs will also be updated to remove the step saying this is a requirement.

[Dependency] Remove vbguest

---

site/app/controllers/admin/PlagiarismController.php
site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
site/app/views/admin/PlagiarismView.php
site/public/css/plagiarism.css

There is no functional backend to the "ignored submissions" option in the configuration form for the plagiarism detection tool.
Instructors can specify which users to ignore when running the plagiarism matching algorithm.
The users in each category are queried from the database to compile a list of user id's, which is then written into the `config.json` of the gradeable.
This PR is related to, but independent from the Lichen PR https://github.com/Submitty/Lichen/pull/37, since the "ignore_submissions" field exists in the config.json in the current Submitty master branch. This PR writes user id's to ignore into that field in the config, and everything works normally if nothing is written into it.

[Feature:Plagiarism] Plagiarism ignore submissions

---

site/cypress.json

The localhost development port number changed moving to Ubuntu 20 and Cypress tries to connect to 1501 instead of 1511 when the development ide is launched
Port number is fixed

[Bugfix:Developer] Fix localhost port for cypress

---

autograder/autograder/packer_unpacker.py

Currently if a student submits a git repo with a dangling symlink, 
the autograding copy directory tree code will infinite loop and fill up /tmp.
ignore danling symlinks in this copy tree

[Bugfix:Autograding] ignore dangling symlinks & add logging

---

site/app/templates/EditSecondaryEmailForm.twig
site/app/templates/UserProfile.twig
site/public/css/user-profile.css
site/public/js/user-profile.js
tests/e2e/test_my_profile.py

Right now there are links for editing preferred names and secondary emails. These will start to wrap as screen size shrinks.
finishes most of the tasks for #6670 
Closes #6553 
Now there are buttons next to names and the second email address fields to edit these. These have also moved away from a tags to instead use button tags. The two names buttons and two secondary email buttons do the same thing respectively.

[Bugfix:System] Secondary Email Profile Changes

---

site/app/templates/submission/homework/CurrentVersionBox.twig
site/app/views/submission/HomeworkView.php

Currently a non-clear message is shown before a student decides to change their version on Submitty.
Closes #5262 
Now a clearer message is shown after TA grading has begun to warn them their grade will be set to a zero.

[UI/UX:Submission] Make Version Conflict State Clearer

---

site/public/js/pdf/PDFInitToolbar.js

Closes #5348
On mobile, if you switch to the pencil tool and then back to the cursor, you will be unable to scroll. This makes your only option of scrolling to use the eraser tool which can be inconvenient.
* The cursor tool always allows scrolling of the page.
* Black is selected as the pen color in the toolbar the first time you go on the page (as opposed to a transparent box if ```localStorage.main_color``` is empty)
I believe this closes #5348 since the rest of the interface seems to work well on mobile.
Tested on iPad Pro with Apple Pencil

[Bugfix:TAGrading] Fix Mobile Scrolling on PDF Edit

---

site/public/js/pdf/PDFAnnotateEmbedded.js

Fixes #4599 
Currently, on the pdf annotating interface, the pen/text size cannot be changed with the pen tool selected.
Also, any other inputs even in other tabs of the ta grading interface are disabled when the pen is selected.
The pen/text size can be adjusted with the pen tool selected, and all other inputs can be used with the pen tool selected.

[Bugfix:TAGrading] Allow pen/text resize with pen tool

---

site/cypress/integration/login.spec.js
site/cypress/support/utils.js

Right now Cypress tests have a hard-coded semester/year string.
Cypress generates the string every time it's run so when the next semester code starts the tests pass without needed a change on this.

[Testing:System] Update Cypress Access Check

---

site/app/libraries/Core.php

Right now a Forum model gets created in Core. This Forum model is never used anywhere else in the code.
The Forum model creation is now commented out in Core. All associated code will be left as another refactor of the forum may come soon.

[Bugfix:Forum] Remove Forum from Core

---

site/app/libraries/database/DatabaseQueries.php

The `getUsersNotFullyGraded()` function in `DatabaseQueries.php` is not currently parameterized, meaning that it may be vulnerable to SQL Injection.
This PR parameterizes the `getUsersNotFullyGraded()` function.

[SECURITY][Bugfix:TAGrading] Parameterize insecure query

---

site/app/libraries/Core.php

We are not setting Doctrine debug mode.
This fixes setting the Doctrine debug mode to be based on the debug flag. This mode sets what cache is used by default, where under debug the cache is `ArrayCache` vs `AcpuCache`. The latter is good in production where the entity code cache is stable and not changing often vs the former. This is especially true as we may look to configure more of the recommended settings to tune doctrine performance.
This PR also fixes a path problem when doing a mapping lookup, but does not currently affect anything.

[Bugfix:Developer] Fix setting debug mode for doctrine

---

site/app/templates/polls/ViewPollResults.twig

The include for the `Markdown.twig` template was missing its extension. This would cause an exception to be thrown on trying to view the poll results.
The template is properly referenced, and an exception is no longer raised.

[Bugfix:SubminiPolls] Fix invalid markdown template include

---

site/app/templates/submission/homework/LoadMessagePage.twig

If a gradeable had a message attached to it, it would cause an exception to be thrown as it attempted to include a template that does not exist. This was because the template was missing its file extension in the include line.
Adds the missing extension in the include line, getting the page to work as expected and avoid exception being thrown.

[Bugfix:Submission] Fix markdown include on submission page

---

.flake8
autograder/autograder/autograding_utils.py

The only remaining file in Issue #5556 which hasn't been linted is `autograder/autograder/autograding_utils.py`.
This PR lints `autograder/autograder/autograding_utils.py`.  In the interest of reducing the total number of changes, the errors E501 (line length) and F841 (unused variables) were left ignored.  Due to the nature of this file, it may be counterproductive to attempt to fit every line within the line length restriction.  F841 can be mostly resolved by properly handling errors in `try...except` blocks and by deleting a handful of unused variables.
Fixes #5556

[Refactor:Autograding] Lint autograding directory

---

site/public/js/system-update.js

Fixes #6712 
Currently, "undefined" appears in many spots on the release notes.
The "undefined" strings have been removed.

[Bugfix:System] Fix Undefined Error on Release Notes

---

.github/workflows/submitty_ci.yml

In the move from Travis-CI to GitHub CI, we lost the check on PHP syntax. While phpstan or phpcs will usually error out on syntax, this error can be mangled with other errors, making it not obvious why this happens, or where exactly within the file it happens.
This re-adds the syntax check as a stage of the php-lint workflow. This should help with understanding when the test suite fails on syntax.

[Testing:Developer] Syntax check php files in CI

---

site/public/css/electronic.css
site/public/js/ta-grading-rubric.js
site/public/templates/grading/GradingComponent.twig

closes #6694
I had to disable the default arrows and add custom ones that don't glitch when the rubric refreshes and updates scores. 
NOTE:
to test:
first on master, mash the up arrow when trying to give someone a custom mark and see error
Now try on new branch

[Bugfix:TAGrading] Custom mark arrows

---

site/public/js/server.js

closes #6291
Downloading the zip file happens in a new tab and is asynchronous so the submitty page is not effected. The new tab auto closes when the download is complete.
To test:
Use the "download zip file button" on the TA grading interface.

[Bugfix:TAGrading] Submission download

---

site/app/controllers/MiscController.php
site/app/libraries/FileUtils.php
site/tests/app/libraries/FileUtilsTester.php

Right now symlinks can cause issues when downloading a zip file of a VCS gradeable. Symlinks can also be used to view their targeting directories in the TA grading file browser.
Symlinks are now skipped if they appear in the VCS checkout folder. Symlinks are also skipped in the FileUtils getAllFiles function to avoid attempting to follow symlinks from the TA page.

[SECURITY][Bugfix:TAGrading] Don't load or zip symlinks

---

site/public/css/activity-dashboard.css

When the window becomes too narrow, the table display changes but it's hard to tell what column the data belongs to. Empty entry also results in thin empty lines.
The mobile version of the table now has the name of the column on the left.

[UI/UX:InstructorUI] Mobile-fy student activity dashboard

---

site/public/js/admin-team-form.js

Pressing the enter key while editing team members will start deleting the top team members. These buttons are assumed of type submit which is why the enter key can trigger them.
The enter button would submit the form rather than deleting members. The buttons are all of type button except for the true submit button.

[Bugfix:InstructorUI] Prevent Enter Key Removing Team Members

---

site/app/templates/grading/electronic/NavigationBar.twig
site/app/views/grading/ElectronicGraderView.php
site/public/css/electronic.css
site/public/js/ta-grading.js

Fixes #6368 
Currently, when there are empty panels when grading, a message telling the user to choose one from above only displays if the user is in single panel mode. All other modes don't show this message.
---
---
Now all panel layouts have this functionality
---
---
Also, a small fix was made to the header to stop the buttons from overlapping the student/team name on small screens.

[Bugfix:TAGrading] Add Panel Message for All Empty Panels

---

site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
site/app/templates/grading/electronic/Details.twig
site/app/views/grading/ElectronicGraderView.php

closes #6020
closes #5924 
All wildcard / file names entered in the input box are saved and displayed correctly.
- As an instructor, edit a peer gradeable
- Go to the peer matrix panel
- Attempt to enter file names with spaces or wildcards with spaces in the "Enter any Wildcards..." box
- save and reload
- see error
if you get a twig error "gradeable does not exist" when trying to get to the student index while logged in as a peer grader,
comment out lines 609-626 in app/templates/grading/electronic/details.twig. The total column for peer grading has been broken for a while but the recent changes to twig settings makes it so errors are thrown. There is another open PR that will fix this so just ignore it for now.
Since the error had to do with spaces, I made sure that the matching …

[Bugfix:InstructorUI] Hidden file errors

---

site/cypress/integration/courseMaterials.spec.js

The last test in the course materials cypress tests is flaky and often fails waiting for a page load.
This may be from a long test running and cypress slowing down the CI Job by recording everything
Force reload and add a wait to try and avoid getting stuck on a page

[Testing:CourseMaterials] Fix flaky test

---

site/app/templates/misc/MarkdownArea.twig
site/app/views/MarkdownView.php

closes #6736 
Adding markdown to a notebook using the notebook builder works as expected.
1. As instructor, make a notebook gradeable and use the notebook builder
2. try to add mark down and click save

[Bugfix:InstructorUI] Fix markdown editor for NB builder

---

site/public/js/ta-grading.js

When there is an additional banner (such as the `No Submission` banner) in TA grading, the height of the panel container is not correct.
The height of the panel container now factors in the height of all siblings of the panel container.

[Bugfix:TAGrading] Fix panel container height w/banner

---

.setup/bin/partial_reset.py
.setup/bin/reset_system.py
.setup/bin/setup_sample_courses.py
.setup/pip/system_requirements.txt
.setup/vagrant/setup_vagrant.sh

The `PyYAML` dependency we have is stuck on an older version as it's being installed from the package store due to a dependency on `netplan.io`. This is the only python dependency we have that is like that.
Moves to `ruamel.yaml` which we can install and maintain normally through pip like other dependencies. It is also the slightly better maintained library at the moment as it supports the YAML 1.2 spec, and is a bit faster on parsing than PyYAML.

[Dependency] replace pyyaml with ruamel.yaml

---

site/composer.json
site/composer.lock

The composer dependency lists are not in alphabetical order. This makes it annoying to scan through for a specific named dependency.
The dependency list is alphabetized, with a config flag added to keep it such.

[Refactor:Developer] Alphabetize composer dep list

---

site/public/js/ta-grading-rubric.js
site/public/templates/grading/OverallComment.twig

Currently, when viewing other grader's comments on the rubric panel, the first paragraph gets interpreted as code and is put all on one line.
The markdown looks as expected. Also, other user's comments are loaded when the page loads to hopefully eliminate having to wait for the markdown to render the first time you open the comment.

[Bugfix:TAGrading] Fix Markdown on Overall Comments

---

site/app/libraries/Access.php

A peer grader can do a url hack to download files that are hidden from them.
Hidden files are now totally protected from people without access to them.
Shail, follow the same steps you were using before

[Bugfix:TAGrading] Prevent hidden file url hack

---

site/app/templates/admin/RainbowCustomization.twig

The rainbow grades customization page has a few twig errors on page load.
Array keys are checked before using the keys to prevent the twig errors.

[Bugfix:InstructorUI] Fix Rainbow Grades Customization Twig

---

tests/e2e/base_testcase.py

If you try to run selenium tests on Ubuntu 20.04, they will all error out due to the wrong port number in the URL.
The correct port, 1511, is set in the base testcase for all selenium tests.

[Bugfix:Developer] Fix port in Selenium e2e tests

---

site/cypress/integration/login.spec.js

The Cypress login tests currently depend upon the sample course having a fixed configuration.  This can cause issues such as the issues exhibited by https://github.com/Submitty/Submitty/pull/6721.
This PR makes a slight modification to the path used to verify that the user is logged in by checking to see that the instructor has access to the course config page.

[Testing:Developer] Use constant url for cypress login tests

---

site/app/views/submission/HomeworkView.php

closes #6759
$display_version was not being set for VCS gradeables so $viewing_inactive_version was being set to true no matter what.
Submissions for VCS gradeables work as expected
To test:
Configure a VCS gradeable and make submissions

[Bugfix:Submission] VCS submission bug fix

---

.github/workflows/submitty_ci.yml

The `css-lint` CI job was not required for the e2e job, though all other jobs were.
Adds `css-lint` as a required job of the e2e job.

[Testing:Developer] Mark css-lint required for e2e tests

---

site/app/templates/forum/RenderPost.twig
site/app/templates/forum/ThreadPostForm.twig
site/public/css/forum.css
site/public/js/forum.js

Fixes #6750 
* Forum posts without markdown ignore newlines
* Some forum posts are missing line wrapping 
* The markdown toggle setting was not being saved properly
* Newlines on all posts are rendered properly
* Line wrapping occurs on all posts
* Markdown toggle setting is saved
* This setting is saved every time you toggle the button, whether you post or not
* All markdown toggles will toggle collectively

[Bugfix:Forum] Fix using markdown in forums

---

.setup/bin/setup_sample_courses.py

Right now, in the sample course, teams are generated with an incremental number ID per gradeable. There is a check in the setup_sample_courses script to make sure no duplicated IDs. This still produces a different set of IDs compared to what production would generate where the number ID is incremental across the entire course.
The setup script uses a similar method to the site code to generate the numeric IDs to model a production environment better. The numeric IDs are now always unique per course.
Below is a Vagrant Up workflow run on this branch to show that it works on a full vagrant up.
https://github.com/Submitty/Submitty/actions/runs/1045366739

[Bugfix:Developer] Fix generation of sample team IDs

---

.github/workflows/dependabot_title_fix.yml

Any new PR for a dev dependency comes with the prefix `[DevDependency]:` that needs to be fixed by a human so that it'll pass CI title check workflow.
Adds a CI action to automatically update the PR title in the above case so that a human won't have to go in and rename the PR title manually.

[Feature:Developer] Add workflow to fix dependabot PR titles

---

site/app/controllers/pdf/PDFController.php

Annotations are currently saved and loaded using the URL encoded file path.
Annotations are now saved and loaded using the original file path.
If any annotations were made during the period that the URL encoded file path was used for saving/loading, they will no longer be used.

[Bugfix:TAGrading] Fix old annotations not showing

---

migration/migrator/migrations/master/20210714135438_add_course_groups.py

Catches an exception that was thrown in an archived course with stale user/group information.

[Bugfix:CourseMaterials] exception in add_course_groups migration

---

site/app/templates/submission/homework/SubmitBox.twig

When submitting a VCS assignment with a GitHub user name and repo id, the git user id is never passed into the proper functions and instead your user id is set to equal your repo id and your repo id is set to undefined.
The user id is passed in and both variables are set properly
To test:
1. First on master, configure a VCS assignment
2. attempt to submit, fill out id and repo fields, click submit, see that when it reloads the inputs aren't correct
3. repeat on new branch

[Bugfix:Submission] Fix VCS git-user-id not set

---

.setup/CONFIGURE_SUBMITTY.py
.setup/distro_setup/ubuntu/18.04/setup_distro.sh
.setup/distro_setup/ubuntu/20.04/setup_distro.sh
.setup/install_system.sh
.setup/nginx/submitty.conf
Vagrantfile
site/app/models/Config.php
site/app/templates/GlobalHeader.twig
site/app/views/GlobalView.php
site/public/js/server.js
site/public/js/websocket.js
site/tests/app/models/ConfigTester.php

The websocket port within Submitty is hardcoded in the code to use `8443`. This caused collisions if trying to use Ubuntu 18.04 and 20.04 VMs at the same time (let alone additional worker machines).
This reworks the code to allow the websocket to be set to arbitrary values, being set within the `/usr/local/submitty/config/submitty.json` file, and then that's read in when loading the page. If the value is not set, it'll falback to the default value of `8443` like before. 
Documentation for this will be done as part of #6813.

[Feature:System] Remove hardcoding of websocket port

---

site/app/controllers/course/CourseMaterialsController.php
site/public/js/server.js

closes #6229 
Course materials zip download now uses the ZipStream library 
To test:
As instructor upload folders to course materials
As student download the folders

[Refactor:CourseMaterials] Use ZipStream for bulk downloading

---

site/public/css/plagiarism.css
site/public/js/resizable-panels.js

The hover animation for the drag bar on the plagiarism interface currently uses a blur effect on hover to indicate that it can be dragged.  This is different from the behavior on the TA Grading Interface which causes the drag bar to increase in size to indicate that it is draggable.
This PR makes a slight modification to the way the drag bar on the plagiarism results page works to bring it in line with the TA Grading Interface.
https://user-images.githubusercontent.com/16820599/127198309-976758dc-05bc-448c-b075-40485d3504c7.mov
It would be nice if all of the drag bars could share more code.  Unfortunately, differences between the styling on the pages which use the resizable panels means that code sharing is somewhat impractical.

[Bugfix:Plagiarism] Adjust animation for plagiarism drag bar

---

site/app/templates/officeHoursQueue/CurrentQueue.twig
site/app/templates/officeHoursQueue/QueueFilter.twig
site/app/templates/officeHoursQueue/QueueFooter.twig
site/app/templates/officeHoursQueue/QueueHistory.twig
site/app/templates/officeHoursQueue/QueueStatus.twig

The URLs for dealing with queues that utilize the queue code does not properly encode the queue code within the URL. Because the queue codes could have any character, this can lead to invalid / broken HTML. An example would be the queue code `Foo Bar` would end up with the URL `/office_hours_queue/Foo Bar/empty` where the space character is unencoded, and illegal (though browsers seem to handle it alright). This was also being marked as an error for accessibility.
The queue code is now properly encoded when used within the URL. The above example would be `/office_hours_queue/Foo%20/empty`. No changes are necessary to the controller as the `$_GET` parameter are automatically url decoded.

[Bugfix:HelpQueue] Encode queue codes within URLs

---

site/app/templates/forum/ForumBar.twig
site/app/templates/forum/showFullThreadsPage.twig
site/public/css/forum.css

Fixes #6629 
The Create Thread button is overlapping other items when the forum is empty.
The Create Thread button doesn't overlap anything.

[Bugfix:Forum] Fix Button Alignment in Empty Forum

---

site/app/templates/plagiarism/DeletePlagiarismResultsAndConfig.twig
site/app/templates/plagiarism/PlagiarismConfigurationForm.twig

After clicking the "submit form" or "delete" buttons for the first time for plagiarism configurations, the user is still able to click on those buttons in an attempt to create another daemon job to create/edit/delete the config, which results in errors caught by php.
The buttons are disabled after clicked once, to indicate that the request is being processed and to prevent further unnecessary errors.

[Bugfix:Plagiarism] Disable submit buttons after clicked

---

site/app/templates/plagiarism/Plagiarism.twig

When viewing the run log to see the progress for a given run, the only way to refresh the log is to close and re-open the log.  This can be annoying for instructors who are monitoring the progress of a slow run.
This PR adds automatic refreshing to the run log so that it's possible to monitor the progress of a run without having to close and re-open the run log.  In addition, the scroll position will remain stuck to the bottom of the log after refreshing unless the user scrolls away.

[Feature:Plagiarism] Refresh run log while open

---

site/app/controllers/admin/PlagiarismController.php
site/app/libraries/database/DatabaseQueries.php
site/app/templates/plagiarism/Plagiarism.twig
site/app/templates/plagiarism/PlagiarismConfigurationForm.twig

PR https://github.com/Submitty/Submitty/pull/6777 introduced new functionality to Lichen/plagiarism.  After discussion, a few improvements were suggested.  This PR is a follow-up PR which makes a few tweaks to the UI and makes a change to the permissions checking requested in https://github.com/Submitty/Submitty/pull/6777.
In full, this PR:
- Adds error-checking to prevent the current gradeable from being compared with itself and for duplicate values entered for that field in the form
- Changes the wording/descriptive text of the other gradeables subheading
- Excludes courses with the group "root" from being used as the source for other gradeables, regardless of the group attached to the current course
- Adds links to submitty.org documentation where appropriate 
Before:
After:

[Refactor:Plagiarism] Improve other gradeables UI

---

site/app/controllers/MiscController.php

Currently there is some unnecessary code in MiscController.php that could potentially be causing problems with downloads via ZipStream and also appears to be creating files on the server.
unnecessary code has been ripped out.
To Test:
1. From the ta grading interface, use the download submissions button and make sure the download finishes properly.
2. From the submission interface, submit a few files and then use the download all files button

[Refactor:Submission] Fix ZipStream implementation

---

site/app/templates/grading/electronic/Details.twig

If you are grading an individual assignment and are in anonymous mode, the grade buttons do not show.
The grade buttons are now shown.

[Bugfix:TAGrading] Fix Grade Button in Anonymous Mode

---

site/app/templates/grading/electronic/SubmissionPanel.twig

Open/close buttons in submission panel do not work as expected (toggles files from previous state each open/close cycle).
Fixes #6806 
Open/close buttons in submission panel work as expected.

[Bugfix:TAGrading] Fix open/close submissions buttons

---

.github/workflows/submitty_ci.yml

Right now the setup.sh for testing sets the timezone for the site as America/New_York while the rest of the e2e testing suite has no set timezone. This creates a conflict in timezones when storing/viewing data.
The database (postgres) and testing machine are both set to America/New_York in the e2e test. This is needed for #6824 to pass.
This has been tested in #6824 and has been proven to work during a time where a conflict would happen.
An alternative solution to this would be to remove the specified timezone from the setup.sh and have all of the timezones align to their automatic timezone.

[Testing:System] Specify Timezone in e2e Test

---

site/app/templates/plagiarism/PlagiarismConfigurationForm.twig

When editing a plagiarism configuration, the next php error appears in the console:
The error is fixed.

[Bugfix:Plagiarism] Fix prior gradables select on edit form

---

site/app/libraries/Access.php

If a symlink somehow got onto the server, our Access.php will let users open the symlink.
If the file is detected to be a symlink, we will always deny access to it.

[Bugfix:System] Deny website file access via symlink

---

site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig

If grade inquiries are enabled and you go to create a gradeable you will get a Twig error.
The page loads fine when grade inquiries are enabled.

[Bugfix:InstructorUI] New Gradeable Twig Error

---

site/app/controllers/grading/ElectronicGraderController.php
site/app/libraries/Access.php
site/app/templates/grading/electronic/ta_status/StatusBase.twig
site/app/views/grading/ElectronicGraderView.php

If you are a peer or limited access grader when grading a team gradeable, the bullet list says you can manage teams. Full access graders cannot manage teams.
Closes #6858 
Full access graders can now manage teams. Only if you are an instructor or full access graders can you see the bullet option to manage teams. Team names with a single quote were able to break the edit button from working which is now fixed as well.

[Bugfix:TAGrading] Team Gradeable Revisions

---

.github/dependabot.yml

The `directory` field for the pip dependencies points at the file names, and not the containing directory. This probably prevents dependabot from working properly given it expects to be given a directory [per their docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory).
Fixes the dependabot field to point at the directory. Unfortunately, there's not a way to differentiate between stuff coming out of `vagrant` versus `system`, and so for now that'll have to be handled manually. A GH action could be made to fix it.

[Bugfix:Developer] Fix directory path for pip

---

site/app/libraries/database/DatabaseQueries.php
site/app/templates/polls/ViewPollResults.twig

Fixes #6868 
If you edit a poll and re-arrange the responses, then the poll results would display incorrectly. This was because we were using the `option_id` for the response in graphing for plotly. An example would be a poll with three options (`Yes`, `No`, `Maybe`) where after poll creation and people have put in responses, we switch the ordering of `Yes` and `No`. This means that `Yes` would have `{option_id: 0, order_id: 1}` and `No` would have `{option_id: 1, order_id: 0}`.
After filling out the responses for a number of students, we might have the following data we were plugging into the graph:
```
tick_text = {
0: "No"
1: "Yes"
2: "Maybe"
};
tick_val = {
0: 1
1: 0
2: 2
};
y_data = {
0: 1
1: 3
2: 1
}
```
where plotly would sort itself on the `tick_val` under the hood, but then break …

[Bugfix:SubminiPolls] Fix results chart for edited polls

---

sbin/create_course.sh

The `sbin/create_course.sh` script currently creates `<course_path>/lichen/provided_code` and `<course_path>/lichen/config` when setting up the directories for a course. Those directories are remnants of the old directory structure Lichen used to have, and they are not used anymore. All the directories used for every Lichen run are created when necessary in `Lichen/bin/process_all.sh`.
The unused directories are not created anymore.

[Bugfix:Plagiarism] Remove creation of lichen subdirs

---

site/app/templates/forum/createThread.twig
site/app/views/forum/ForumThreadView.php

Fixes #6750
When creating a new thread, the markdown option is always initially set to disabled. 
Also, when switching between threads, the markdown toggle doesn't have the correct value until the page is refreshed.
The markdown toggle persists on the create thread page as well as switching between threads.

[Bugfix:Forum] Fix Markdown Toggle not Persisting

---

site/app/templates/grading/electronic/SubmissionPanel.twig

At some screen widths, it is currently possible for one or both of the words "auto open" to wrap to a different line from the associated checkbox.  See screenshot.
The checkbox and text now wrap as a single unit and will always be on the same line.  See screenshot.

[Bugfix:TAGrading] Fix auto open text wrapping

---

.setup/pip/system_requirements.txt

`vagrant up` is failing for Ubuntu 18.04 due to a new version of `onnx` being released, which `onnxruntime` (which we do pin) depends on.
Pins the version of `onnx` to install to one that'll work on Ubuntu 18.04.
Testing this via the `Vagrant Up` GH action: https://github.com/Submitty/Submitty/actions/runs/1097417549

[Dependency] Pin onnx to 1.9.0 for Ubuntu 18.04 support

---

site/app/templates/admin/Docker.twig

Closes #6904
If the machine does not have a capability that another machine has, there is no empty cell displayed for that capability and all of the capabilities check marks are rendered together making it impossible to interpret the information.
The empty cells are displayed properly.
To test, you can edit `autograding_workers.json` in `/usr/local/submitty/config` folder on your vm to have a second machine.

[UI/UX:Autograding] Fixed empty cell problem

---

site/public/js/plagiarism.js

It is currently possible to click a mark on the left panel which highlights a matching region (or several) in red but impossible to do the reverse and click a mark on the right panel.  In addition, when clicking on a user in the matching users popup, the mark which was clicked is not highlighted after the colors refresh and it may be difficult for the instructor to find it.
This PR addresses both of the above issues.  It is now possible to click regions on either the right or left pane with proper highlighting, and the UI will now automatically highlight the clicked region after the colors reload when clicking a user in the matching users popup.

[Feature:Plagiarism] Add ability to click on right panel mark

---

site/cypress/integration/courseMaterials.spec.js

The course materials Cypress tests have been failing on GitHub Actions with regularity since being added but work locally.  Several attempts have been made to fix them and have failed.  The flakiness of these tests has led to a potentially dangerous lack of caution when merging pull requests with failing tests because the frequency is so high.
This PR is a (hopefully) temporary fix to disable the failing course materials tests on GitHub Actions until they can be fixed permanently.

[Testing:CourseMaterials] Disable failing  Cypress tests in CI

---

.setup/bin/setup_sample_courses.py

`setup_sample_courses.py` was erroring out for me due to the new plagarisism course not having the `eg_has_due_date` or `eg_has_release_date` keys for any of the electronic gradeables.
This modifies the setup script to allow these fields to be optional and defaulting to true if they're omitted. This is inline with the vast majority of how we use this particular field in the various course yml files.

[Bugfix:Developer] Fix KeyError in setup script

---

autograder/autograder/autograding_utils.py
autograder/autograder/grade_item.py

PR #5969 made the due date / submission deadline optional, but this breaks the computation of lateness within the autograding shipper/worker
Correctly parse / handle lack of due date.

[Bugfix:Autograding] parse no due date / submission deadline

---

site/app/templates/plagiarism/PlagiarismResult.twig
site/public/css/plagiarism.css
site/public/js/plagiarism.js

Currently, it is sometimes hard to tell whether the plagiarism results page has loaded fully.  An attempt was made to visually indicate that the data is loading by clearing the code boxes immediately and repopulating them when the data has loaded but it's not ideal. 
This PR introduces loading indicators which cover editors when they are loading data to make it explicitly clear when the data has finished loading.
https://user-images.githubusercontent.com/16820599/128772925-784b300a-8b1c-4e73-911c-50d1aa6cfe30.mov

[Feature:Plagiarism] Add loading indicators

---

site/public/css/admin-gradeable.css

The text color for downloading a zip for assigned teams/students on the TA grading stats page is black in light mode, making it difficult to read.
The text color for downloading a zip for assigned teams/students on the TA grading stats page changes depending on if the user is in light or dark mode.

[Bugfix:TAGrading] Fix text color for download button

---

site/app/views/NavigationView.php

If there is an assignment without a due date that has no TA grading it will still say grade.
Now it is changed to view submissions if it does not have TA grading turned on.

[Bugfix:TAGrading] Change Grade to View Submissions

---

site/app/controllers/admin/PlagiarismController.php

It is currently possible to cause a PHP error when re-running a plagiarism configuration.  This error is caused by Lichen deleting the old results while PHP is attempting to read the ranking files while displaying the main page.  This error sometimes happens and sometimes doesn't, depending on how fast Lichen deletes the files.
This PR fixes the error described above by first checking to see if a job is in the Lichen queue before checking to see if ranking files exist.  This also fixes an occasional issue observed where the number of students is listed as N/A while Lichen is running instead of putting a "running" or "in queue" notice on the table row.

[Bugfix:Plagiarism] Fix PHP error on re-run

---

site/app/models/gradeable/GradeableList.php

Gradeables that have no due date still have a hidden due date which is being used to calculate how the gradeables are sorted.
Closes #6938
All gradeables without a due date will float to the top and get sorted by their submission open date while preserving the sorting of gradeables with due dates.

[Bugfix:Submission] Sort Gradeables Without Due Date

---

site/app/controllers/admin/PlagiarismController.php
site/app/libraries/database/DatabaseQueries.php
site/app/views/submission/HomeworkView.php

Currently, loading the plagiarism results page takes a substantial amount of time.  Most of this time is not spent loading what should be the most expensive parts of the page, but rather making repeated database queries to determine the first and last name associated with each submission.
This PR combines the repeated database queries into a single query.  In testing, this more than halved the overall page load time for a gradeable with 75 submissions with results.  In the case of a large class of 300 students, each making 5-10 submissions, the load time improvements could be even greater than the ones observed in testing.

[Refactor:Plagiarism] Reduce plag. results page load time

---

site/app/templates/misc/MarkdownArea.twig
site/public/templates/grading/OverallComment.twig
site/public/templates/misc/MarkdownArea.twig

Fixes #6856 
Currently, when using the rubric panel on TA Grading to enter an overall comment on Firefox, if you are using a layout that makes this window small (such as 4 panel layout), then every time you type in the box, it shakes.
The box doesn't shake. However, Firefox does automatically scroll to focus to the line you are typing in. I tried various workarounds to fix this but ultimately they would be very hacky and figured it would be best to let the browser continue its default behavior.

[Bugfix:TAGrading] Fix Shaky Overall Comments on Firefox

---

autograder/submitty_autograding_shipper.py

Assignments with no due date that have no autograding (can be short circuited) were hitting an bug trying to calculate the number of seconds late parsing a due date = None.
When due date is none, late seconds is set to zero correctly, allowing short circuiting again.
Also a log message was moved to a more appropriate location.

[Bugfix:Autograding] short circuit gradeable with no due date

---

site/app/libraries/database/DatabaseQueries.php

Fixes #6939 
Currently, on the student activity dashboard, the Gradeable Submission Date column shows the oldest submission date instead of the latest.
The Gradeable Submission Date column now shows the most recent submission date.

[Bugfix:InstructorUI] Fix Gradeable Submission Date in SAD

---

site/public/css/electronic.css

Fixes #6952 
A vertical scrollbar appears by the student name / team members in the grading interface, even if there is no content to scroll to.
The scrollbar only shows up when necessary.
I only was able to test this on Mac which has some differences when displaying scrollbars, it would be good if someone with Windows can test this.

[UI/UX:TAGrading] Show Team/Student Scrollbar When Needed

---

site/app/controllers/course/CourseMaterialsController.php

If you edit any field of a course material link it will give you an error that there is already a link with that title in that directory.
The link title shouldn't be tried to be updated unless it is actually changed now so this error would not happen except in cases where it is supposed to.

[Bugfix:CourseMaterials] Fix Editing External Links

---

site/app/libraries/database/QueryIdentifier.php
site/tests/app/libraries/database/QueryIdentifierTester.php

A fatal error is raised within the `QueryIdentifier` if it is given a CTE with an invalid trailing comma.
This fixes the library so that it does not raise a fatal error, and instead more gracefully returns the query type as "unknown", similar to what it'll do for other types of invalid queries.

[Bugfix:InstructorUI] sql toolbox - invalid CTE queries

---

site/app/templates/officeHoursQueue/CurrentQueue.twig
site/app/templates/officeHoursQueue/QueueFooter.twig
site/app/templates/officeHoursQueue/QueueHistory.twig

The office hours queue page currently includes an ID column which contains clickable icons which reveal the users's ID.  
This PR updates the arrangement of the ID column such that the clickable icon appears in the name column.  See attached screen recordings:
Before:
https://user-images.githubusercontent.com/16820599/130450930-fe5d6ea6-aa05-4572-afbf-8fb84e98cde8.mov
After:
https://user-images.githubusercontent.com/16820599/130450966-20445bb6-70e9-411b-9c57-f492052b59c1.mov
Closes https://github.com/Submitty/Submitty/issues/6831

[Refactor:HelpQueue] Rearrange OH queue columns

---

grading/CMakeLists.txt
grading/Sample_CMakeLists.txt

Currently, we build C++ executables for autograding on the server, and execute these programs on worker machines and inside of docker containers.  If the gcc library versions on the worker machine and/or within the docker container are not compatible, this is problematic.
By staticly linking the libraries, this should facilitate execution on a wider range of machines.

[Feature:Autograding] Use static libraries for autograding

---

site/app/controllers/MiscController.php

If you try and open a course material from the old URL (old URL is with directory and path rather than ID), you will get a Type error.
Revision for PR #6960
You can now access course materials from their old URLs in case someone has bookmarked them.

[Bugfix:CourseMaterials] Fix URL Error

---

site/app/controllers/DockerInterfaceController.php
site/app/templates/admin/Docker.twig
site/app/views/admin/DockerView.php
site/tests/app/controllers/DockerInterfaceControllerTester.php

Closes #6955
Currently, the page tries to cross reference the cgi results and the json files to make sure the results matches up before displaying the images. However, since only the primary machines run the cgi script, the images that do not exist on the primary machine is not displayed on the page.
Removed all usage and dependency on the cgi script. This means the table for images to capabilities will lose some columns, however, this can be fixed in the future by logging the docker information onto the log from the worker machine. This will be the first step toward a more scalable solution as the number of worker machines increases.
#6961 Should be merged before this PR

[Bugfix:Autograding] Remove CGI for Docker UI

---

site/app/models/gradeable/Gradeable.php

All gradeables will now show the exam gradeable timer and progress bar due to an automatic 0 being set rather than null for the amount of minutes.
The amount of minutes will default to null so the exam timer and progress bar will only show when they are supposed to.

[Bugfix:Submission] Fix Gradeable Timer Display

---

site/app/views/submission/HomeworkView.php

Currently, a banner saying that submissions are no longer being accepted is showing to instructors when the gradeable is in the future category.
Closes #6984
This banner will not show in this category anymore due to the extra date check.

[Bugfix:Submission] Remove Future Closed Submission Banner

---

site/app/controllers/admin/AdminGradeableController.php
site/app/models/gradeable/Gradeable.php

Courses that have grade inquiries enabled on gradeables will produce a date validation error when trying to load the gradeables page.
The error is now gone and date validation is handled properly for grade inquiries.

[Bugfix:System] Fix Grade Inquiry Date Validation

---

site/app/libraries/socket/Server.php

The Server.php socket manager closes an extra socket for an unknown reason. This causes CI to fail in #6817 when deleting other queues.
The code closing the socket has been removed.

[Bugfix:System] Remove unnecessary system socket closes

---

site/app/libraries/Output.php
site/public/css/markdown.css

Currently, tables aren't rendered in markdown
Tables now work as expected in markdown

[Bugfix:Forum] Add Table Support for Markdown

---

site/public/css/gradeable-notebook.css

Fixes #7019 
Currently the margin on multi-line multiple choice options in notebooks is not sufficient
The margin has been increased

[UI/UX:Submission] Add Margin to Multiple Choice

---

site/app/models/gradeable/Gradeable.php

If you try to change the team lock date on a team gradeable, the value will not always change. This is due to that date being coerced.
The team lock date will not be coerced if this is a team assignment.

[Bugfix:InstructorUI] Fix Team Lock Date Coercion

---

site/composer.json
site/composer.lock

We use the `doctrine/cache` library as part of some internal bits of doctrine. Doctrine requires adding a cache library of some sort on installation, but it can use several. `doctrine/cache` is also deprecated, and it is suggested that one move to a different cache library.
As #7042 added `symfony/cache` as a dependency, which is another library that `doctrine` can use under the hood. As such, we can drop the deprecated `doctrine/cache` altogether, and just rely on the supported `symfony/cache`.

[Refactor:System] Remove doctrine/cache dependency

---

.setup/INSTALL_SUBMITTY_HELPER.sh

There are quite a few developers here that use PHPStorm rather than the code watcher script. PHPStorm will copy the files directly into the site folder while vagrant will copy the changes into the GIT repo on the VM. The rsync command only finds differences between site folder and GIT repo site folder which will always be equivalent with PHPStorm and therefore never update. This causes composer, npm, and permissions to never get updated when using submitty_install.
There is a new new runtime flag "clean quick" which will do a much shorter version of the submitty_install clean. This would delete most files in site but not all like vendor or node modules to reduce install time. This would be run by PHPStorm users when they switch branches, encounter permission issues, or install a new …

[Feature:Developer] Add new flag for quick clean on install

---

bin/set_allowed_mins.py

If a non-sudo unix user wanted to rebuild the gradeables in the course, the script would fail since they can't access the database password.
Closes #6982
There is an extra check to see if the user can access the file. If not and they are trying to build a gradeable with allowed minutes, a warning will appear. Warning message put below:
WARNING: You do not have access to set allowed minutes from CLI. Please use website to set that.

[Bugfix:System] Add Warning Message to Build

---

site/app/templates/GlobalHeader.twig
site/app/views/GlobalView.php
site/public/js/websocket.js

Currently the only way to tell that your browser did not connect to the web socket server is by looking in the Javascript console. There is also an error in the websocket.js file that I fixed in this PR. When the socket tries to reconnect it does to with a page name of the full URL rather than the actual page name it initially tried to connect with.
Closes #7018 
If there was a connection failure, a message will appear saying that the websocket server is not working right now and to contact sysadmin. If while on the same page instance the connection opens back up then the message will go away and continue as expected. Now the socket will reconnect with the appropriate page name rather than the URL.

[Feature:System] Add web socket failure banner message

---

site/app/views/forum/ForumThreadView.php

Addresses #5964
Students will now be able to see thread numbers

[Feature:Forum] Adding thread numbers for students

---

site/app/views/grading/ElectronicGraderView.php

Currently, in a bulk upload gradeable, if a student has more than just a pdf submitted, a frog robot appears when trying to enter their grading page.
The grading page can now be accessed like normal, and a yellow color was given to the warning message/background.
Fixes #7069

[Bugfix:TAGrading] Fix Bulk Upload Grading With Other Files

---

site/public/css/officeHoursQueue.css

Fixes #7008
Breadcrumbs on the office hours queue page are the wrong color for dark modes
Breadcrumbs correctly inherit text color from external-breadcrumb class

[Bugfix:HelpQueue] Breadcrumb showing incorrect text color

---

site/app/templates/forum/ThreadPostForm.twig
site/app/templates/misc/MarkdownArea.twig
site/public/js/forum.js
site/public/js/server.js

Fixes #7003 and Fixes #7035
Currently, toggling out of markdown while markdown preview is on will leave the text unable to be edited, because it is still in preview mode. Additionally, if you cancel the edit popup while in preview mode and open the edit menu for a different message, the markdown preview for the previous message will be shown.
Now, when you toggle out of markdown the preview button will be toggled if it is currently in preview mode. Additionally, if you cancel the edit window while in preview mode, you will also be taken out of preview mode before canceling, ensuring that when you reopen an edit popup you will be in edit mode. This also follows the behavior of the update post button.

[Bugfix:Forum] Fix edit post markdown preview

---

site/app/models/gradeable/LateDays.php

The late day events are ran through based on timestamp. They are used in order to create late day information. The null check isn't being applied to the elements properly. All events should have timestamps, so it did not introduce any bugs as of yet.
The null check is applies correctly within usort ($e1 and $e2)
Not a breaking change, the bug wasn't necessarily an issue to begin with.

[Bugfix:TAGrading] Fix usort for late day events

---

.setup/CONFIGURE_SUBMITTY.py

Closes #7038 
Right now, when running `CONFIGURE_SUBMITTY.py` and disabling email, a `NameError` will get thrown. This is because the `EMAIL_INTERNAL_DOMAIN` is only set within the `if` branch, and not the `else` branch.
The `EMAIL_INTERNAL_DOMAIN` is now defined similar to the other email variables in the `else` branch, so the crash is avoided.

[Bugfix:System] Fix configure crash on disabling email

---

README.md

The current contact page link only brings you to the overview page on the submitty docs, while this page does have a separate link to the contact page there, someone may miss it 
Contact link directly links to contact page

[UI/UX:Developer] Fix Contact link on README 

---

site/app/templates/plagiarism/PlagiarismResult.twig
site/public/js/plagiarism.js

Currently, it is difficult for instructors to report bugs in the plagiarism results page due to confidentiality matters, primarily involving the association of code/plagiarism results with specific names.
This pull request introduces a new "anonymous mode" feature to the plagiarism results interface which allows the instructor to toggle between showing names and random hashes.
This is not meant to be a completely anonymous mode such as is the case for blinded grading.  Since instructors can always turn this off, we only care about the visual display of data being anonymized so that instructors can more freely share screenshots and/or show students accused of cheating the evidence against them with fewer confidentiality concerns.

[Feature:Plagiarism] Plagiarism anonymous mode

---

site/app/templates/grading/electronic/Details.twig
site/app/views/grading/ElectronicGraderView.php
site/public/css/details.css

There is no banner on the TA grading index.
Closes #7065 
A banner will appear on the TA grading index to clarify certain cases to help make it more clear of what graders need to grade.
When instructors/full access graders are viewing all students but they have at least one assigned section, they will get the message: `Notice: You are assigned to grade a subset of students for this gradeable, but you are currently viewing all students. Select "View Your Sections" to see only your sections.`
When instructors/full access graders are viewing their own sections but they have no assigned sections, they will get the message: `Notice: You are not assigned to grade any students for this gradeable. Select "View All" to see the whole class.`
When graders who are not instructors/full access graders …

[Bugfix:TAGrading] Clarify sections in grading index

---

site/app/libraries/database/DatabaseQueries.php

Closes #7029
Currently "Grader Assignment" tab, when matching TAs to rotating sections, currently displays instructors, graders, TA's legal names
- ![before](https://user-images.githubusercontent.com/43322572/133503614-c629e8da-e6cf-4898-924a-95f1f2796cf4.png)
Displays instructors, graders, TA's preferred names
- ![after](https://user-images.githubusercontent.com/43322572/133503628-0d23acf4-e9c9-49e1-8ff4-6f94c1004607.png)
- checked that the only files that use the result of this `getGradersByUserType()` function are `AdminGradeableController.php` → `AdminGradeableGraders.twig`, so I won't be changing display names elsewhere

[Bugfix:InstructorUI] Preferred Names in Grader Assignment Tab

---

site/public/js/solution-ta-notes.js

Fixes #7121 
Fixed a typo in an error toast message displayed in the Solutions/Notes tab of the Gradeable page, when logged in as an instructor or TA
No testing was necessary as this is a mere typo fix.

[Bugfix:InstructorUI] Fixed Typo on Toast Message

---

site/public/js/forum.js

Currently on firefox the expiration date picker does not show up due to an issue with date.parse not working with "-"  in the date
The new behavior replaces the "-" with "/". This is only a temporary fix when issue #6415 is implemented this will also be fixed.

[Bugfix:Forum] Missing expiration datepicker fix

---

site/app/templates/polls/ViewPollResults.twig

Newlines in poll answers break the histogram as described in #7106.
Removes newlines from poll histogram labels to prevent JS syntax errors when rendering the histogram.
Fixes #7106

[Bugfix:SubminiPolls] Fix newlines in poll histograms

---

site/public/css/markdown.css

#6998 added support for tables in markdown.  Unfortunately, a small portion of the CSS included in that PR applies to all `<td>` elements site-wide which leads to tables having thicker borders as shown below:
Fixes the runaway CSS selector.

[UI/UX:System] BugFix runaway markdown table borders

---

autograder/submitty_autograding_shipper.py

For assignment submission by git, if a student has a file in their repo, 
named simply 'main' there is an ambiguity when checking out the student's work.
The error causes a file named "failed_to_determine_version_on_specifed_branch.txt" 
to be included in the checkout folder.  
The initial autograding apparently proceeds normally, but if the assignment is batch
regraded, there are significant problems and the score is zero.
The change resolves the ambiguity, now repos with a main file autograde fine.

[Bugfix:Submission] git submission file/branch ambiguity

---

site/app/controllers/OfficeHoursQueueController.php
site/app/libraries/socket/Client.php
site/app/libraries/socket/Server.php

Looking at the PHP code to figure out what could be the root cause the reported warning messages about undefined index reference when closing the socket, found there was a number of opportunities to simplify the code, strengthen types, etc. Behavior should be largely unchanged, with the exception of some improved error handling around authentication.
Should fix this error reported by @bmcutler:

[Refactor:System] Simplify the PHP websocket code

---

site/app/templates/admin/Configuration.twig

The current text on the "Initial Allowed Late Days" section of the course settings page currently reads: Number of allowed late days given to each student when they are added to the course.  Additional late days can be granted (e.g., as incentives) using the "Late Days Allowed" form.
This text is confusing because the number for all students can be changed at any time, not just when students are added to the course.
Changed the text to read: Base number of late days given to all students at the start of the course. Additional late days can be granted (e.g., as incentives) using the "Late Days Allowed" form.

[UI/UX:InstructorUI] Update late day text on settings page

---

site/app/templates/notebook/Notebook.twig
site/app/templates/submission/homework/SubmitBox.twig
site/app/views/grading/ElectronicGraderView.php

Certain missing twig variables prevent notebook gradeables from being rendered on the student and grader view
Variables are passed in correctly

[Bugfix:Submission] Fix notebook views

---

site/app/templates/officeHoursQueue/QueueStats.twig

The header row for the "This Week's Data" table doesn't show up on the office hours queue stats page:
The header shows up correctly

[Bugfix:HelpQueue] Fix stats page table header

---

site/app/templates/navigation/RoomSeating.twig
site/public/css/navigation.css

closes #7125 
The table is clearly visible in light and dark mode
To test:
I couldn't figure out how to actually upload a seating chart so I just edited a few lines in Navigation.twig and Roomseating.twig to get the table to show up

[Bugfix:Submission] Fix seating chart in dark mode

---

site/app/templates/grading/electronic/Details.twig

closes #7133 
The Default/Random order buttons now say "Switch to Default Order" and "Switch to Random Order"

[Refactor:TAGrading] fix vague Grading sorting order button

---

site/app/templates/plagiarism/PlagiarismConfigurationForm.twig

On the plagiarism configuration page, the dropdown for tokenization per language has an item only for C++.
As requested, the dropdown item has been update to display the text `C/C++`, as the tokenization used for C++ supports C as well.

[Feature:Plagiarism] Add C as supported language

---

site/app/templates/polls/ViewPollResults.twig

HTML special characters are currently doubly-escaped in the title of the poll results histogram which leads to the issue described in #7098.
This PR fixes #7098 by safely un-encoding the title of the poll before passing it to the plotting library which encodes it again.  Care was taken to mitigate possible opportunities for XSS vulnerabilities by using `DOMParser().parseFromString` to decode the string after Twig renders it without sacrificing usability.

[Bugfix:SubminiPolls] Fix doubly-escaped HTML in hist title

---

migration/migrator/data/course_tables.sql
migration/migrator/data/submitty_db.sql
migration/migrator/dumper.py
migration/migrator/main.py
migration/tests/test_dump.py
migration/tests/test_dumper.py

The DB dump in #6966 introduced syntax in the DB dumps that did not work on postgresql 10, which is used by Ubuntu 18.04. This new syntax is a new default setting (`default_table_access_method`) and then an alternative term (`FUNCTION` instead of `PROCEDURE`).
The `SET` for default arg of `default_table_access_method` has been removed and we now now use `PROCEDURE` for dumps. This is done automatically as part of migrator, and tests added for it. There's no change in behavior of how the dumps work between postgresql 10 or postgresql 12 (Ubuntu 20.04).

[Bugfix:System] Fix db dumps to work on postgresql 10

---

.setup/distro_setup/ubuntu/18.04/setup_distro.sh

We run two `pip install` lines in setup_distro for Ubuntu 18.04. These packages are then "re-installed" when we run `pip install` over `.setup/pip/system_requirements.txt`, rendering these unnecessary.
Remove these unnecessary installs, and we just rely on the single definition of them in `system_requirements.txt`.

[Refactor:System] Remove pip installs from setup_distro

---

site/app/templates/submission/homework/SubmitBox.twig
site/app/views/submission/HomeworkView.php
site/public/js/server.js

There has been some confusion about the disabled submit button, when not viewing the most recent version of a gradeable. Currently if not viewing the most recent submission the submit button text changes to "Switch to most recent version to make a submission" and is disabled. Clicking it does not actually switch to the most recent version which is what was causing confusion.
The submit button now always says submit but is disabled when not viewing the most recent submission, there is also a tooltip that says "switch to most recent version to submit". When the button is disabled, there is another button beside it that allows the user to easily switch to their most recent submission.

[Feature:Submission] Add Switch to Most Recent button

---

.github/workflows/submitty_ci.yml

Whenever we setup python for a github actions job, each job has its python version set locally instead of reading from an env variable 
Created python version variable to make changing it in all places easier

[Testing:System] Move Python versions to env variable

---

.setup/CONFIGURE_SUBMITTY.py
.setup/INSTALL_SUBMITTY_HELPER.sh

Part of #4011
In early versions of Submitty, we relied on the environment variables being set in `/usr/local/submitty/.setup/INSTALL_SUBMITTY.sh` script to be then read during execution of `.setup/INSTALL_SUBMITTY_HELPER.sh`. Eventually, we migrated over to having configuration JSON files in `/usr/local/submitty/config`, and that `.setup/INSTALL_SUBMITTY_HELPER.sh` started to reading in those variables directly as we found we needed to wait till after the migrator was run for a number of them (as migrator could affect them). At this point, the environment variables we wrote into that original install script are all largely unused except for `${WORKER}`.
The `${WORKER}` env var is ported over into `.setup/INSTALL_SUBMITTY_HELPER.sh` and read in from the configuration json files. The …

[Refactor:System] Remove env vars from INSTALL_SUBMITTY.sh

---

site/app/views/submission/HomeworkView.php

Currently if a user clicks on  a team gradeable, but aren't on a team the following frog robot occurs.
The issue is because if someone isn't on a team, $graded_gradeable is null 
I added a null check for $graded_gradeable, the most recent url is set to null if graded_gradeable is null which isn't a problem because you can't submit to a team gradeable without being on a team anyways so the button would never be used with a null url.

[Bugfix:Submission] Fix switch to most recent button error

---

site/app/controllers/admin/AdminGradeableController.php
site/app/models/gradeable/Gradeable.php

Peer component creation does not work on rubric configuration page in "Edit Gradeable" page.
Peer component creation works on rubric configuration page in "Edit Gradeable" page.

[Bugfix:TAGrading] Fix peer component creation

---

site/phpstan-baseline.neon
site/phpstan.neon

We are using phpstan level 3 to analyze our codebase. We have only one remaining phpstan error of that level that's ignored.
Increases the phpstan level to 4 for analyzing the codebase. Per the [rule docs](https://phpstan.org/user-guide/rule-levels), this adds checking for:
> basic dead code checking - always false instanceof and other type checks, dead else branches, unreachable code after return; etc.
All new phpstan errors that were found on this level are added to our baseline to be eliminated in future PRs.

[Testing:Developer] Increase phpstan analyze level

---

site/app/libraries/database/DatabaseQueries.php

Currently the database query for identifying a student's name on the leaderboard will return an empty string if the student has never set a preferred name.
This change updates the database query to ignore empty strings in the user's preferred name, therefore falling back to the user's base name if they did not set a preferred one.

[Bugfix:Submission] Ignore empty preferred names

---

site/public/js/code-mirror-utils.js

Currently, lines aren't wrapping properly on notebook gradeable inputs. In inputs with regular text (not code), the text should be wrapping, but it is not.
The short answer inputs on notebooks will have wrapping enabled when no language is specified (plaintext). Otherwise, if a language is specified, there will be no line wrapping.

[Bugfix:Submission] Fix Line Wrapping on Notebook Inputs

---

site/app/libraries/database/DatabaseQueries.php
site/app/models/OfficeHoursQueueModel.php
site/app/templates/officeHoursQueue/QueueStatus.twig

Currently, if there is only 1 open queue and a student is in that queue, the option to switch queues still displays even though there are no other open queues to switch into.
The form doesn't display if there is only 1 open queue, unless the queue that is open is not the queue the student is in. For example It could be the case that the student is in queue A, but we close that queue and open queue B.  They should be able to switch to queue B, even if there is only 1 queue option.

[Bugfix:HelpQueue] Don't show switching if no queue is open

---

.setup/CONFIGURE_SUBMITTY.py

Closes #7331 
When worker pair is not enabled for vagrant, we pass in `--worker-pair 0` to the configure script, where the `0` gets parsed as a string, and thus evaluates to a truthy string. This causes worker-pair to be enabled, when it should not be.
This PR implements a custom action parser so that we convert the string argument that's passed for `worker-pair` to a boolean value, such that `0` or `false` strings will give us a false value for `--worker-pair` and `1` or `true` (or any other string) will evaluate to boolean true.

[Bugfix:System] Fix parsing worker-pair arg

---

site/public/templates/grading/GradingComponent.twig

Currently peer graders can still see the option to add custom marks however when they try to use them they get a permission error.
Peer graders don't have the option to use custom marks.

[Bugfix:TAGrading] Hide custom marks from peer graders

---

migration/migrator/data/course_tables.sql
migration/migrator/migrations/course/20211011122951_plagiarism_rebrand.py
site/app/controllers/admin/PlagiarismController.php
site/app/entities/plagiarism/PlagiarismConfig.php
site/app/libraries/plagiarism/PlagiarismUtils.php
site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
site/public/css/plagiarism.css

All places in the code base refer to the number of tokens that make up a hash as `sequence length` and many places refer to `other gradeables` as `prior term gradeables`.
The term `sequence length` is now referred to as `hash size`, and `prior term gradeables` are referred to as `other gradeables`. All previous references to the old names have been changed for consistency. Related PR's were all other repositories to update these terms: https://github.com/Submitty/Lichen/pull/64, https://github.com/Submitty/submitty.github.io/pull/380, https://github.com/Submitty/LichenTestData/pull/5.
No changes in the behavior of any program/script, except for two parameters in the `config.json` that were renamed:
- "sequence_length" is now "hash_size"
- "prior_term_gradeables" is now "other_gradeables", …

[Refactor:Plagiarism] Rebranding Lichen

---

.editorconfig

Twig files were not covered in our editorconfig to set a default indent size.
Twig files are now set as having four spaces, similar to other files.

[Feature:Developer] Set indent size for twig in editorconfig

---

site/app/templates/AutogradingStatus.twig
site/cypress/integration/autograding_status_1.spec.js
site/public/js/autograding-status.js

Currently, the tables in autograding status page have a lot of 0s which may overwhelm users.
Fixes #7145
The values of the tables are checked and are omitted where it makes sense within the page.
Example of the new changes below:

[UI/UX:InstructorUI] Omit values of 0

---

.gitignore
site/app/libraries/database/DatabaseUtils.php
site/tests/app/libraries/database/DatabaseUtilsTester.php

A PHP error currently occurs in some cases when Doctrine queries with DateTime objects are run in debug mode.  This behavior was likely introduced in https://github.com/Submitty/Submitty/pull/7295.
Resolves issue by formatting DateTime objects appropriately before displaying.  In addition, this PR fixes a secondary issue where the `$params` parameter in `formatQuery()` is null and thus unable to be iterated over.

[Bugfix:Developer] Fix Doctrine debug mode type issues

---

site/public/templates/grading/OverallComment.twig

Viewing the overall comment of other users renders the Submitty homepage inside of the box.
Works on #7369 
Viewing the overall comment of other users properly shows the overall comment.

[Bugfix:TAGrading] Fix other overall comments preview

---

site/app/templates/forum/CreatePost.twig
site/app/templates/forum/displayThreadList.twig
site/public/css/forum.css
tests/e2e/test_forum.py

Currently the borders on the pins are missing for the instructors and the tooltips have not been updated to say gold pins are expiring soon.
The boarder has been fixed, the tooltip text has been updated, and the bookmark color has been changed to red.

[Bugfix:Forum] Fixing CSS issues on pin borders 
