- modules/tokens.cpp
In some cases (such as for hw02 from last semester for cutler for cout/cerr), this file will produce an invalid JSON as there are no actual tokens found meaning the trailing "]" would never be printed.
Additionally, remove the trailing comma so you don't have to do that in the client code.
> Fix Tokens producing invalid JSON in some cases

- grading/execute.cpp
Used a temporary variable so that the my_char_args const, neccessary for later execv call, wasn't being ignored and casted away.
Please check this to make sure it works, I can't test it because the grading code doesn't work.
> Fixme fixes

- public/controller/data_functions.php
- public/controller/homework.php
- public/index.php
- public/resources/badge.css
- public/view/filecontent_display.php
- public/view/homework.php
Created a pop-up viewer for submitted files. 
To use this feature, go to the class.json file for any course, add a new variable labeled "files_to_view" in an assignment, and then assign it to an array of wildcard patterns that matches the files you want others to view. Sorry if my wording is a bit off, here's an example:
````
"assignments": [
{
"assignment_id":"hw1",
"assignment_name":"Homework 1",
"released":false,
"ta_grade_released":false,
"files_to_view":[ "*.cpp" , "*.txt" ]
},
````
So in this example, only files that end with .txt or .cpp can be displayed with its contents. Under "Submitted Files" box, a button called "View" should appear to the right of the file name.
> Content display

- public/index.php
If we get to else, then we know !isset($_SERVER['PHP_AUTH_USER']) == true from the first if statement failing.
> Remove redundent if branch

- TAGradingServer/account/account-new-rubric.php
- TAGradingServer/account/iframe/account-new-rubric.php
All files loaded from the server to be displayed to the user should be run through htmlentities to prevent any injected scripting code meant to inject the graders.
> fix potential XSS attack

- TAGradingServer/account/ajax/account-labs.php
- TAGradingServer/account/ajax/account-other.php
- TAGradingServer/account/ajax/account-tests.php
- TAGradingServer/account/ajax/admin-csv-report.php
- TAGradingServer/account/ajax/admin-hw-report.php
- TAGradingServer/account/ajax/admin-labs.php
- TAGradingServer/account/ajax/admin-other.php
- TAGradingServer/account/ajax/admin-rubrics.php
- TAGradingServer/account/ajax/admin-tests.php
- TAGradingServer/account/submit/account-rubric.php
- TAGradingServer/account/submit/admin-classlist.php
- TAGradingServer/account/submit/admin-config.php
- TAGradingServer/account/submit/admin-grade-summaries.php
- TAGradingServer/account/submit/admin-grading-sections.php
- TAGradingServer/account/submit/admin-rubric.php
- public/controller/update.php
- public/controller/upload.php
Change suggested by Toshi.
!= casts to same type and might lead to unexpected results.
> replace != with !== in csrf checks

- .setup/install_system.sh
- Vagrantfile
This allows a user to use psql or pgAdmin3 on their host to connect to the VM's postgresql server allowing for easier time running queries/modifying tables/etc than having to do everything through an ssh session.
> allow for a host to connect to guest postgresql server

- Vagrantfile
This then allows the hwphp user (who is part of the vagrant group) to write to the files in /usr/local/submitty/GIT_REPO_submitty/.vagrant/*_logs folders which are created as symlinks within the installation script for vagrant.
> Allow group writing of files into directories in shared vagrant folder

- .setup/install_system.sh
- .setup/vagrant/reset_system.py
- Vagrantfile
This allows for if you want to test something in the install_setup.sh script, you don't need to do a full ```vagrant up``` and ```vagrant destroy``` sequence as we don't need to reinstall all packages and such through this.
Running it would be:
1. If vagrant box is halted: ```vagrant up --provision```
2. If vagrant box is running: ```vagrant reload --provision```
> create method for reprovisioning vagrant box without doing up/destroy

- site/app/models/GradeableTestcase.php
- site/app/views/GlobalView.php
- site/app/views/submission/HomeworkView.php
- site/public/css/server.css
> Badge Fixes

- TAGradingServer/account/index.php
Was looking for the incorrect column from grading_rotating table. Pointed it to the correct column. I think this will clear up the issue where TA were incorrectly told that they were finished grading when they weren't.
> Rotating Sections Exception

- TAGradingServer/account/submit/admin-rotating-sections.php
Right now, we can the `ceil(number_of_students / number_of_sections)` which can lead to the problem that all students are assigned to number of sections less than what was assigned (ex case: 4 students, 3 sections).
> Fix issue of some assigned rotating sections being empty

- LICENSE-THIRD-PARTY.md
- LICENSE.md
Provides a centralized list of licenses for third-parties based on discussion from #772. It seems like some of our libraries (CodeMirror) does not provide any sort of license terms in the header of their JS files so we'd have to make reference to it in this fashion if we wanted to use https://cdnjs.com
> Update submitty license terms as well as provide list of third party licenses

- TAGradingServer/account/admin-gradeable.php
- TAGradingServer/account/submit/admin-gradeable.php
- site/app/controllers/NavigationController.php
- site/app/models/GradeableList.php
- site/app/views/NavigationView.php
- tests/e2e/test_navigation_page_non_student.py
Closes #707 
Gradeables must be in only one category, and that there is a new beta test category for gradeables that are future, but viewable by TAs.
Also fix bug on creating electronic gradeable that doesn't use TA grading throwing datetime exception.
Fixes bug on creating/editing gradeable when there are no rotating section in a course
> Spring Prep work

- site/app/controllers/AuthenticationController.php
- site/app/libraries/Logger.php
- site/app/views/submission/HomeworkView.php
- site/public/index.php
- tests/e2e/test_login.py
- tests/unitTests/app/libraries/ExceptionHandlerTester.php
- tests/unitTests/app/libraries/LoggerTester.php
Closes #848. 
I use the " | " as a seperator character (as the timestamp as a ":" in it which would make grepping that much harder).
Example log:
> 10:26:51 01/19/2017 | student | 192.168.56.1 | logout | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> 10:28:13 01/19/2017 | student | 192.168.56.1 | login | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> 11:29:12 01/19/2017 | student | 192.168.56.1 | submission:cpp_custom | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> Activity Log

- site/app/libraries/database/DatabaseQueriesPostgresql.php
The function `getGradedUserCountByRotatingSections` should reference rotating sections, not registration sections.
> Fix referencing wrong field name

- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/GradeableAutocheck.php
- site/app/models/GradeableVersion.php
- site/app/views/grading/ElectronicGraderView.php
This fixes the following bugs with the new index and summary page:
1) Properly display the list of graders for each section (index page)
2) Properly display students in rotating sections for an assignment (summary page)
The new summary page can be gotten to directly by appending the following:
`&component=grading&page=electronic&action=summary&gradeable_id=open_homework`
to any URL that utilizes the main URL (and not the old hwgrading). Change `gradeable_id` to whatever gradeable you have.
> fix bugs with new summary page

- .travis.yml
- grading/CMakeLists.txt
- grading/Sample_CMakeLists.txt
- grading/main_compile.cpp
When a gradeable provides multiple drop zones, but students are instructed to submit files to only one part, this commit enforces the "only one part" requirement by remove files from all but the first non empty part (files are removed only from the tmp compilation directory, not the archived submission directory)
> enforce submissions to have files submitted in only one part

- .setup/install_system.sh
Having it enabled requires potentially having to restart php7.0-fpm after creating courses (or tearing down/creating) as the config.ini file's existance (or lack thereof) was getting cached and then not being found properly. We don't need the efficiency gains from the OPCache on vagrant for development, so we do want it enabled for production server (though maybe mention somewhere that if you're getting a missing file error on the config.ini file, you need to restart php7.0-fpm).
> Disable OPCache for vagrant

- .travis.yml
- composer_55.json
Closes #1053.
Removes support for PHP 5.5. We will no longer run any Travis test suites against PHP 5.5 and will start using features available in PHP 5.6 in the code base. PHP 5.6 is currently supported at this time.
> drop PHP 5.5 support

- .travis.yml
Travis upgraded their 14.04 image today and moved from Python 2.7.12 and 3.5.1 to 2.7.13 and 3.5.2. I had previously hardcoded those versions into the `.travis.yml` file hence why it suddenly started breaking. I replaced that with a regex that grabs the version of `python2` and `python3` programs and uses that in the places where the version was needed so that when they move from 2.7.13 to 2.7.14+ or from 3.5.3 to 3.5+, we won't have to go back and fix it.
Closes #1083
> Fix Travis build and make it more resilient to future python version changes

- .setup/INSTALL_SUBMITTY_HELPER.sh
I've added a small helper script, `build.sh`, to Submitty/AnalysisTools. This script will either install the binary releases of the specified version or will build the tools from source if no version (or the version `latest`) is specified.
> Use release binaries for analysis tools by default

- site/app/models/Gradeable.php
- tests/unitTests/BaseUnitTest.php
Someone inserted the same `@method` twice in the header of Gradeable and it was causing all tests that mocked that object to just issue a warning, but not necessarily complete. Fixed that and prevented the issue of multiple `@method`s from happening again.
> Fix PHPUnit issuing warnings for some number of tests

- site/app/libraries/database/DatabaseQueriesPostgresql.php
Closes #1152 
Fixed bug in which the highest version of a team assignment is always zero, causing every new submission to be treated as version 1. The problem was in the last join in the SQL query in getGradeables(), which calculates the highest version.
> Fixed team assignment version numbering bug

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/install_system.sh
- bin/grade_item.py
- bin/insert_database_version_data.py
- bin/write_grade_history.py
eliminated a few subprocess.call between python scripts (now just function calls).
removed some command line argument parsing flexibility (that wasn't being used anyway).  Question:  Is there any reason to keep it (it needs repair)?  For future testing?  
Question:  Should the clutter of small python scripts be combined?  (submitty_grading_scheduler.py, grade_item.py, write_grade_history.py, insert_database_version_data.py)  Either in a single file or in a subfolder?   What's "pythonic"?  The current file structure is an artifact of development, not conscious design.
> Cleanup subprocess calls & adjust autograding daemon

- site/app/controllers/admin/UsersController.php
- site/app/views/admin/UsersView.php
Uploading a classlist now accepts null in the registration section column of the csv. Instructors must put the word "null" (not case sensitive) in the column, not leave it blank.
Closes #1294
> Allow students to be placed in null section when uploading classlist

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
- site/public/js/ta-grading.js
The TA page now uses the cookies to save the last opened items. The checkbox for saving is defiantly out of place but I figured we should change that when we decide on the order of the icons.
I don't know if we want to closee #1238 since only half of it is technically finished. 
Also I misspelled "close" on purpose so GitHub doesn't auto close it.
> TA page cookies now save last opened componet, testcases, and folders.

- .setup/bin/setup_sample_courses.py
- more_autograding_examples/paragraph_textboxes/config/config.json
- site/app/controllers/admin/AdminGradeableController.php
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/Gradeable.php
- site/app/models/GradeableComponent.php
- site/app/views/admin/AdminGradeableView.php
- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/HomeworkView.php
- site/data/course_tables.sql
- site/public/js/drag-and-drop.js
- site/public/js/ta-grading-mark.js
- site/public/js/ta-grading.js
- tests/unitTests/app/models/GradeableComponentTester.php
- Closes #1261. 
- New "page" variable for gradeable components.
- In create/edit gradeable, the instructor specifies whether the gradeable is a PDF with pages assigned to components. If yes, the instructor also specifies who assigns pages (instructor or student).
- If instructor assigns the pages, for each component there is input for the page number.
- If student, on the homework submission page there are text boxes in the format 
question title: [number input]
for them to submit. Values cannot be left blank or less than 1.
- On TA grading, when a component that has a page is selected the PDF will reload to the corresponding page. 
- The PDF chosen is the first PDF that appears under the "submissions" folder for that version. If there are no PDFs, no opening of folders/files or …
> Adding "page" to gradeable component for PDFs

- site/app/views/NavigationView.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
- site/public/js/ta-grading.js
- see title
- not sure how to set the permissions to set a TA to see grading since those permissions are set in the TA section of the rubric which doesn't show up in this use case. Leaving it be for now
- the changes to the navigation page is just the removal of an if-else block and then a fix to the indentation
closes #1357
> allow instructors to see hw grading pages even with no manual grading set

- site/public/js/server.js
This should fix it. I think before we were updating the color and score after putting it in an array to save. If full points were given, then it would appear to not save upon refresh.
closes #1428
> Fix check off all checkpoints at once

- .travis.yml
Primarily, it seems that they now require using pyenv to set the python version (instead of adding python3 to the path) as well as  Travis now setting _JAVA_OPTIONS (which we have to unset).
> Fix Travis-CI failures due to recent updates to their Trusty image

- site/app/controllers/admin/UsersController.php
- site/app/models/Course.php
- site/app/views/HomePageView.php
- site/app/views/admin/UsersView.php
- site/public/js/server.js
Closes #1417 
Usernames are now checked to only contain lowercase alpha characters, underscore and hyphen. No spaces. This is checked when uploading a grader list or class list csv or when creating a user manually through the new student form.
Closes #1423 
There is now a 6th column expected in the grader/class list csv when the course uses database passwords. No restrictions on the format of the passwords but it can not be left blank. There is also an optional column (6th or 7th depending on if database passwords are used) for preferred first name.
Closes #1425 
Leading and trailing spaces are trimmed off of user_id, first name, last name, email, preferred first name when uploading users via csv or the new user form. Spaces are allowed within names, not in user_id or email.
> Upload User List bug fixes

- site/app/views/HomePageView.php
Fixed an issue which was causing course buttons to overflow when the homepage was resized. 
Allowed slightly more scaling before "About You" and "Courses" sections wrap.
> Fixed Issue with Homepage Button Wrapping

- .travis.yml
No idea why Travis all of a sudden removed several python versions (including 3.6). Added code to try and use 3.6, but fallback to 3.5 if that's unavailable.
> Travis-CI removed Python 3.6, use 3.6 now

- site/app/controllers/MiscController.php
- site/app/views/MiscView.php
- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/HomeworkView.php
Closes #1447 
No syntax highlighting will be enabled when viewing files with a MIME type of "text/plain" in the submissions and results browser on the TA grading page.
> No syntax highlighting on text/plain MIME type files

- site/app/views/grading/ElectronicGraderView.php
A bug got introduced somewhere along the line causing instructor team editing to attempt to create a new team for one of the team members rather than editing their current one. Small fix.
> Instructor Team Editing Bug Fix

- site/app/controllers/admin/UsersController.php
Closes #1441 
Allowed the preferred name field to be blank on the create/edit user form
Closes #1474 
Added in an error check when creating a new user to make sure you are not using an existing user ID.
> Make preferred name optional, prevent creating new user with existing ID

- bin/grade_item.py
- site/app/libraries/DiffViewer.php
- site/app/models/GradeSummary.php
- site/app/models/HWReport.php
Archiving of files from autograding was buggy.
Autograding log files were incomplete (copied before they were done).
Now we display .jpg images (previously only .png) to the students and graders.
Late days on hw reports are buggy, comment them out until they are debugged.
> Archiving files / displaying .jpg / (temporarily) comment out broken late days

- site/app/controllers/MiscController.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading.js
example being a file with a '#' in it.
Closes #1459
> fix bug where couldn't display files that had htmlentities in it

- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/GradeSummary.php
- site/app/models/HWReport.php
This should (hopefully) fix the memory overflow when trying to generate the grade summaries. If that is not the case, you can continue to shrink the size of `$size_of_user_id_chunks` (and `$size_of_gradeable_id_chunks` as necessary) to hit a happy medium for now.
> implement ability to send chunk of users to generate late day model

- site/app/models/HWReport.php
- site/app/models/LateDaysCalculation.php
We were saving and copying around huge arrays within these functions, without actually ever needing to reference the arrays more than once.
I've rewritten this so that we don't pass around these heavy arrays as well as try and clean up the ResultSet of our queries as we go through it (as we only need to go through them once for parsing).
Caveat: haven't really tested this as I'm not 100% what the expected result should be when run against sample.
> Improve memory usage within late day calculations

- site/app/controllers/student/SubmissionController.php
- tests/unitTests/app/controllers/submission/SubmissionControllerTester.php
Adds a better error message for when a student tries to upload way too large (or way too many) files that kills the `$_POST` superglobal.
Closes #1514
> add check for empty post request

- site/public/js/ta-grading.js
[ partially addresses ] #1493, the tiles no longer hide behind the header when advancing or returning to a student using the arrow buttons. Should revisit if there is a better location to where the grading_toolbar should be put.
> Fixes TA grading tiles hiding behind header

- site/app/controllers/MiscController.php
As per the spec on content-disposition, on the filename attribute, single-quotes are thought to be part of the actual filename, and not act as boundaries except on Chrome, where they're stripped (see [relevant bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=179825)).
This should fix it so that all browsers now download the file with its name as-is.
Closes #1538
> fix single quotes being used on filenames

- site/app/controllers/HomePageController.php
- site/app/controllers/admin/UsersController.php
- site/app/models/User.php
Pull Request for #1562: Preferred Name Doesn't Allow Dashes
* Consolidates user entry/upload validations to User.php model as suggested by @MasterOdin.
* Preferred Name, entered by user (HomePageController), now uses regex in User.php model.
* Same regex check as user_firstname and user_lastname.
* This permits hyphen/dash in Preferred Name.  Also permits apostrophe, backquote, and period.
* Fix XSS attack vectors when displaying validation errors.
> Preferred firstname validation

- site/public/js/ta-grading.js
Fixes the broken(unclickable) breadcrumbs and also TA panels don't hide under the header when changing to a new student. 
Tested on:
Linux: Chrome, Firefox
Mac:   Chrome, Firefox, Safari
> Fixes #1493 and clickable breadcrumbs

- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/TeamView.php
Addresses Issue #1563
This change updates the last places in the php code where a student's legal name is being displayed rather than their preferred name. To the best of my knowledge, this has been addressed everywhere in the main Submitty system.
> Display Student Preferred Name Throughout the System

- site/app/models/Gradeable.php
- site/app/views/grading/ElectronicGraderView.php
Addresses #1485
On the grading index page, if an assignment was only partially graded, the system was classifying it as experiencing a version conflict. This fix adds a function to evaluate whether a submission is actually in a version conflict or if it is just partially ungraded. If it is partially ungraded, the text "Not Fully Graded" is displayed instead of "Version Conflict." It would be trivial to change the text to something else (line 591 of ElectronicGraderView).
> Fix Errant "Version Conflict" Message When a Submission is not Fully Graded

- site/app/controllers/HomePageController.php
- site/app/controllers/admin/UsersController.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/User.php
This should fix it where it's possible for a user to have `null` or `""` be set as their password (either directly in the DB as well as taking the password_hash of `null` `""`.
> fix bug where password could be set to something impossible to use

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/grading/ElectronicGraderView.php
Closes #1534
Improves loading time when iterating to the next student from the TA grading page. 
Fixed the TA grading page's next button so that when you're on the last student in your assigned section, and you press the "go to next student", it takes you back to the index page, or the status page. 
Fixed the TA grading page's next button so that it does not work on sections that are not assigned to you.
> Decrease load time when grading successive students

- site/app/controllers/student/SubmissionController.php
- site/app/libraries/DiffViewer.php
- site/app/libraries/Output.php
- site/app/libraries/Utils.php
- site/app/models/Gradeable.php
- site/app/models/GradeableTestcase.php
- site/app/views/AutoGradingView.php
- site/app/views/submission/HomeworkView.php
- tests/unitTests/app/libraries/DiffViewerTester.php
This should improve the memory usage of the homework page in two ways:
1. Don't buffer the output of all testcases into memory at once. Instead, we echo the output as we go per testcase which should incur a smaller footprint
2. Build the DiffViewer's output the first time we use a function that requires it, and destroy it after we're done with it.
I've tested this and it appears to work for normal testcases in the sample course on Vagrant, but I did not test it on a testcase that was previously causing memory errors or hangs.
> add way to disable output buffer and echo output more immediately

- grading/execute.cpp
Otherwise the default will be based on the total system specs and will use too many threads by default when grading many assignments in parallel.
This should probably be instructor configurable in the future.
> Set environment variable for default desired threads for OpenMP

- .travis.yml
For future reference, an error of:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: missing or invalid 'entry.level'
(Session info: chrome=63.0.3239.84)
(Driver info: chromedriver=2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3),platform=Linux 4.4.0-93-generic x86_64)
```
or 
```
ConnectionRefusedError: [Errno 111] Connection refused
```
or
```
http.client.RemoteDisconnected: Remote end closed connection without response
```
across all tests (or some mix of those errors across all tests) means that we've hit a version mismatch of Chrome and the associated chromedriver. Bumping the version of chromedriver should be all that is needed to fix this.
> Fix travis breaking on E2E tests

- .setup/update_database.py
The current update_database.py script assumes terms are named either f## or s## and only looks in those subdirectories of /var/local/submitty/courses to find existing courses to upgrade.  On our site, we used "autumn17" for our last term and will use "winter18" this term as we are a quarter-based school.
This change scans all subdirectories of /var/local/submitty/courses (which represent terms) for all of their subdirectories (which represent courses) and then runs the upgrade queries on those course databases.
> update_dabase.py script modification

- site/app/libraries/DiffViewer.php
- site/app/views/AutoGradingView.php
Added a fix which stops the homework grading page from loading over-long student output files.
> Fixed homework grading page hanging on over-long files

- site/app/libraries/DiffViewer.php
I was errantly using the size of the student's actual output file to determine whether or not the expected file was readable. 
This update makes it so that if the expected file is smaller than an upper-bound, the whole file is read, otherwise, the file is read up to the size limit.
> Fixed expected file size comparison

- site/app/libraries/database/DatabaseQueries.php
- site/app/views/HomePageView.php
* Instructors (group 1) may always see their courses
* All others may only see their active courses (status 1).
* This is filtered in SQL when DB is queried.
Previously it was possible that a student associated with the same course in multiple semesters may not be listed as the correct rank for a course.  e.g. a student in a previous semester who is a TA later on may still be listed as a "student" under the course they are a grader.  This was caused by the rank search only checking course, although a class is distinct by course **and** semester.  The DB query has been fixed.
> Status flag

- RainbowGrades/MakefileHelper
- RainbowGrades/iclicker.cpp
- RainbowGrades/iclicker.h
- RainbowGrades/main.cpp
- RainbowGrades/output.cpp
- RainbowGrades/parsexml.py
Addresses #1513 and #1660. This will change the `"iclicker":` syntax in customization.json slightly. After the pull request goes through I can update the documentation accordingly.
Changes:
* Multiple iClicker files can be associated with the same question in a given lecture. Currently the column numbers must match. A long-term goal would be an iClicker parsing overhaul and changing customization.json to also have the user specify which question a file/column was contributing to.
* The XML->CSV script now runs using Python 3 explicitly, and uses /usr/bin/env to figure out the right place to look
* The output in individual summaries that only makes sense to print when the `"earned_late_days"` field is present in customization.json will now only print when the field is present and not …
> iClicker Rainbow Grades Multifile Support / Misc. Improvements

- .setup/distro_setup/debian/setup_distro.sh
- .setup/distro_setup/ubuntu/setup_distro.sh
- Vagrantfile
Instead of having to manually configure the network adapters which at best was error-prone and would randomly break depending on your version of VirtualBox and Vagrant. As we only need the two IP addresses now (as we don't have a separate endpoint for submission, grading, cgi, etc.), we should be fine doing this.
I propose this instead of #1667
> Allow vagrant to setup private networks

- site/app/controllers/forum/ForumController.php
- site/app/views/forum/ForumThreadView.php
Per our discussion with Professor Kuzmin on Wednesday, Full-Access graders now have the ability to delete threads/posts (in addition to instructors).
> Allow Full Access Graders to delete posts/threads

- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
- site/public/css/server.css
This addresses the issue of uncovering anonymous posters not being intuitive by creating a button next to the delete post red X. It also shows full name and user id information for people who posted regularly. Please refer to the images attached below:
**Regular Post:**
**Anon Post:**
Partial resolve of #1678.
> Forum full display name

- site/app/views/grading/ElectronicGraderView.php
closes #1594, where team names consisted of list of user IDs, not full names
> TA Grading Team Name Fix

- .setup/install_system.sh
- .travis.yml
The psycopg2 library is phasing out binaries from the primary pypi package and requiring people to build from source if using it as some people (not us) were having issues with the bundled version of libssl. We need to switch to their new binary only pypi package going forward, though this only requires changing the pypi package we install and no other changes.
See: http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/
> Replace psycopg2 with psycopg2-binary

- grading/execute.cpp
- grading/execute_limits.cpp
Set up mpi for use in Parallel. This only required adding mpi to the list of enabled system programs and increasing the max RLIMIT_FSIZE from 100mb to 400mb.
> Enabled MPI on Submitty

- .setup/Dockerfile
To use:
```
git pull
vagrant ssh
sudo su
rm -rf /tmp/docker
mkdir /tmp/docker
cp /usr/local/submitty/GIT_CHECKOUT_Submitty/.setup/Dockerfile /tmp/docker
cp -R /usr/local/submitty/drmemory /tmp/docker
cp -R /usr/local/submitty/SubmittyAnalysisTools /tmp/docker
cd /tmp/docker
su hwcron
docker build -t ubuntu:custom .
```
You should then have a docker image. To initially test:
```
$ docker run ubuntu:custom /bin/ls -la /usr/local/submitty
total 16
drwxr-xr-x 1 root root 4096 Feb 17 11:29 .
drwxr-xr-x 1 root root 4096 Feb 14 17:39 ..
drwxr-xr-x 2 root root 4096 Feb 17 11:29 SubmittyAnalysisTools
drwxr-xr-x 9 root root 4096 Feb 17 11:29 drmemory
```
> Fix dockerfile missing folder /usr/local/submitty

- .setup/update_database.py
- site/app/controllers/forum/ForumController.php
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
We have discussed a few things in the last couple of days and some of the fixes for those are included in this PR. Including:
- Thread list scroll bar saving location on refresh (this is animated and can be changed to be slower, faster, or not animated)
- Full name and user_id clickable for ta & instructor forum view should be fixed. I can't re-create the issue that was mentioned but I believe my fix addresses the error
- There was an error where htmlentities would display in the thread_list for titles of threads 
- Text area size change for create thread as it seemed to overflow in some cases 
- A fix for making files with spaces being able to be displayed, this doesn't effect ones that already have been uploaded with a space in the file name, but rather future uploads. To fix …
> Small Forum Tweaks

- .setup/INSTALL_SUBMITTY_HELPER.sh
- bin/grade_item.py
- bin/killall.py
Testing it:
In one terminal:
```
$ vagrant ssh
vagrant@vagrant:~$ sudo su
root@vagrant:/home/vagrant# su untrusted00
untrusted00@vagrant:/home/vagrant$ python -c "import time; time.sleep(1000)"
root@vagrant:/home/vagrant#
```
and in another terminal:
```
$ vagrant ssh
vagrant@vagrant:~$ sudo su
root@vagrant:/home/vagrant# cd /usr/local/submitty/GIT_CHECKOUT_Submitty/bin/
root@vagrant:/usr/local/submitty/bin# su untrusted00
untrusted00@vagrant:/usr/local/submitty/bin$ ./killall.py
root@vagrant:/usr/local/submitty/bin#
```
The long running python script as well as both bash shells will be killed.
----
Still need to hook this up to the grade_item.py script.
> Add killall script for user who runs it

- site/app/models/AdminGradeable.php
The initial size is now set to 2 when creating new gradeable. fixes #1762 @MasterOdin
> Initially default size of team is 2

- site/public/js/drag-and-drop.js
Fixed a bug that was causing the next user to not actually be in focus after a successful bulk upload. (A div was being selected rather than its child text element).
> Fix "move to next element" after successful bulk upload

- .setup/update_database.py
- site/app/controllers/MiscController.php
- site/app/controllers/forum/ForumController.php
- site/app/controllers/student/SubmissionController.php
- site/app/views/forum/ForumThreadView.php
- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/HomeworkView.php
- site/public/js/drag-and-drop.js
This should resolve the issue of a user inputting a poor filename, and not renaming or having issues displaying the poorly named file. All filenames are also preserved. Refer to the screenshots below.
Collaborated with @shailpatels to complete this PR.
*.pdf also works. Tested frame_buggy.cpp to ensure that it doesn't break with normal file names.
> Resolves issue with poor file name uploads

- .travis.yml
- site/app/views/forum/ForumThreadView.php
This PR resolves the issue when a post is made with multiple links that the first link that is found while parsing replaces the others when displaying the post to the user.
> Fix multiple links in a post

- grading/execute.cpp
Note: value doesn't matter, but it the HOME environment variable must be set.
> Set a HOME environment variable needed by Haskell compiler

- .setup/INSTALL_SUBMITTY_HELPER.sh
We went in a different direction and this is a legacy reference to the original implementation which is no longer necessary and is just clutter.
> Remove unnecessary lines for clang dockerfile

- .setup/Dockerfile
- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/bin/partial_reset.py
- .setup/update_database.py
- .setup/vagrant/sites-available/submitty.conf
- site/app/controllers/admin/ReportController.php
- site/app/libraries/FileUtils.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/Gradeable.php
- site/app/models/LateDaysCalculation.php
- site/data/course_tables.sql
This greatly simplifies the generate grading summaries page such that it only needs to iterate through gradeable models to generate the JSON file for each student.
Initial testing of this shows that it can generate ~740 students in sub-60 seconds compared to the current code which throws a 500 error (and then runs for several more minutes).
> Fix memory/time usage for grading summaries

- site/app/controllers/NavigationController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/Output.php
- site/app/views/GlobalView.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/index.php
This makes it so that any internal JS/CSS files added to the Output class (which all should be) will be given a timestamp of when the file was last modified which will cause it the cache for any of these files to be refreshed anytime the site is re-installed.
> Improve handling of forcing refresh of JS/CSS files when updating site

- site/app/controllers/MiscController.php
Fix for version control system zip downloads. The actual submission files were not in the zip.
New zip folder should contain two top directories each containing a folder for each student. One directory should contain the students actual submissions and the other should contain submission info. 
Will need to be tested on live server due to a lack of ability to test VCS on local machine.
> Vcs zip fix

- TAGradingServer/models/ElectronicGradeable.php
- TAGradingServer/models/LateDaysCalculation.php
- TAGradingServer/toolbox/configs/master_template.php
- TAGradingServer/toolbox/functions.php
- site/app/models/LateDaysCalculation.php
`SUBMISSION_GRACE_PERIOD` and ` __SUBMISSION_GRACE_PERIOD_SECONDS__` don't seem to change the submission behavior at all, and can be removed to avoid further confusion. 
When an assignment is submitted shortly after the official due date, a javascript alert warns the student that they will be charged one late day, but no late days are actually charged.
After removing these lines, the same behavior occurs:
> Remove Unnecessary References to Grace Period

- .setup/install_system.sh
This is necessary to get repo grading to work via local checkout as all repos are owned `root:www-data`.
> Added hwcron to the www-data group

- site/app/views/AutoGradingView.php
Prevents limited access graders from displaying on the TA/Instructor grade view.
Instead of a grader name, it'll just be blank - this shouldn't be an issue when the verify grader feature is implemented.
Fixes #1908
> Hide limited access graders

- site/app/controllers/admin/ReportController.php
- site/app/models/GradeableComponent.php
Example of homework:
```
{
"id": "closed_homework",
"name": "Closed Homework",
"grade_released_date": "9998-12-31 23:59:59 -0500",
"autograding_score": 0,
"tagrading_score": 11,
"score": 11,
"status": "Good",
"days_late": 0,
"components": [
{
"title": "Read Me",
"comment": "",
"score": 1,
"default_score": 2,
"upper_clamp": 2,
"lower_clamp": 0,
"marks": [
{
"points": "-1",
"note": "Minor errors in Read Me"
}
]
},
{
"title": "Coding Style",
"comment": "",
"score": 5,
"default_score": 5,
"upper_clamp": 5,
"lower_clamp": 0,
"marks": [
{
"points": "0",
"note": "Full Credit"
}
]
},
{
"title": "Documentation",
"comment": "",
"score": 5,
"default_score": 5,
"upper_clamp": 5,
"lower_clamp": 0,
"marks": [
{
"points": "0",
"note": "Full Credit"
}
]
},
{
"title": "Extra Credit",
"comment": "", …
```
> Add additional fields to grade summary output and fix score always being 0

- site/app/controllers/admin/ReportController.php
- site/app/models/GradeableComponentMark.php
This will show as the final mark in the the list of marks for a component.
For non-electronic gradeables, it'll then either show the score or a comment depending on if its a text field or not.
> Fix custom mark not displaying properly in grading summary output

- .setup/install_system.sh
- Vagrantfile
This will make it when you `vagrant ssh`, you'll be logged in as root. The if statement is necessary around the new `config.ssh.*` lines as otherwise it'll break running `vagrant up`.
After merging this, you'll need to do `vagrant up --provision` to setup the SSH details.
> vagrant ssh as root by default

- bin/submitty_autograding_shipper.py
- site/app/controllers/grading/ElectronicGraderController.php
Should fix error which was causing TAs to report that the "grade next student" and ">" and "<" do not work anymore.
A typo was causing the buttons to always iterate over registration sections.
> Fix issue with grade next student not working

- site/app/views/forum/ForumThreadView.php
This PR addresses the issue with the recent PR for categories. This resolves the issue of throwing an error as a result of data trying to be accessed when there is no data to be accessed.
> Fix bugs with no threads

- site/app/controllers/grading/ElectronicGraderController.php
When grading team assignments, teams were being iterated over by team_id. Fixed to sort first by section (registration or rotating) then by team leader id to match the index page.
> Fixed Iteration Order when Grading Teams

- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
This PR closes #1940, which notices that if a user posts as anonymous their visible name is displayed in the search results.
> Fix usernames displaying on search when anonymous

- site/app/libraries/Logger.php
- site/app/libraries/Utils.php
- site/public/index.php
- tests/unitTests/app/libraries/LoggerTester.php
Implements the latter part of #1937 in adding a unique identifier cookie for a user (if it doesn't exist) and writes that cookie to a log file within the access logs. The cookie should last indefinitely (depending on user's settings) for a given browser.
Added a TODO for later once we fold composer.json into the site folder and we can start to use third-party packages easier.
> Add unique cookie identifier to site access logs

- site/app/views/GlobalView.php
- site/public/js/server.js
This makes it easier to reference the "global" JS variables in any JS script operating on the page as if desired, you can just pull it from `document.body.dataset`. Note, the naming scheme done by dataset is to convert any the data string such that it strips the `data-` and then converts the remainder to camelCase (dropping any - and uppercasing the following letter).
> Use window onload function to set global JS variables

- site/app/views/GlobalView.php
- site/app/views/admin/ReportView.php
deprecated now that students see TA grading details directly from database and grade summaries contains more details.
> Remove Generate Homework Reports from UI

- site/public/js/drag-and-drop.js
- site/public/js/server.js
Closes #1993 
An error in variable scopes was causing submissions to fail (submitting to the wrong url) with an obscure error.  Now, the `buildUrl` method is fixed to not leak any data into the global variables.
In addition to the contents of #1993 there were a few other places where variable scope was global instead of local, so now the variables that really should be local are now.
> Improved variable scopes to fix assignment submission

- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/views/submission/HomeworkView.php
It appears we had this set to 5 hours!?!?! when perhaps it was supposed to be 5 minutes.
Anyway, we agreed that the grace period should be 0.
When issue #1865 is complete, there will be no excuse for late submission.
If the instructor wishes to have a small grace period, they can adjust the deadline, but that exact date will be displayed to the students.
> Remove late submission grace period

- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
- site/public/js/ta-grading.js
Will close #1492. Included as well is some cleanup to the TA grader JS: there were some long `onclick` functions that are now broken up into functions that can be used from other places.
Here is a list of shortcuts so far,
* A: autograding module
* G: grading rubric module
* O: file browser module
* S: student info module
* R: reset module positions
* Left Arrow: prev student
* Right Arrow: next student
* Up Arrow: prev component
* Down Arrow: next component
* 1 - 9: select/deselect rubric mark (of currently open component)
> TA Grading Keyboard shortcuts

- .travis.yml
This will only run the full shebang on pushes to master and pull requests
> Don't run full travis matrix on all pushes

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
Bug introduced by #1984 as the chmod done when installing the site will cause certain PHP scripts to no longer be writeable by hwphp which will cause Composer to fail to run on secondary updating.
> fix permissions problems for composer

- site/public/js/ta-grading.js
Closes #2011 and lets us have the ability to assign hotkey shortcuts such as "Shift ArrowUp"
> Adding modifier support for keycodes, preventing firing with modifiers

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/grading/ElectronicGraderView.php
Closes #1842 with a basic label that queries the db for non-null grade view dates.
> "Number of students who have viewed their grade" label

- bin/build_homework_function.sh
- bin/make_assignments_txt_file.py
- sbin/build_config_upload.py
- site/app/controllers/admin/AdminGradeableController.php
Should fix permissions errors and allow all instructors in course & hwcron to run BUILD_XX.sh
new options:
BUILD_XX.sh --clean
(will delete all files associated with building all gradeables, then re-build all from scratch)
BUILD_XX.sh --clean --no_build
(will delete all files associated with building all gradeables)
BUILD_XX.sh hw1 hw3 --clean
(will delete files associated with specified gradeables & re-build them)
BUILD_XX.sh hw1 hw3
(re-builds the specified gradeables, should be a bit faster than the --clean version)
And every call to BUILD_XX.sh will search for gradeables that have been recently deleted (config/form/form_XX.json no longer exists), and run clean on those deleted gradeables.
Note that calling:
BUILD_XX.sh --no_build
Will only search for deleted gradeables (should run …
> improve permissions for build_course & add '--clean' option

- site/app/views/grading/ElectronicGraderView.php
- site/public/css/ta-grading.css
Closes #1451. Ended up being a simple CSS fix.
> Fixed wacky file list on Firefox on macOS

- site/public/css/server.css
This image does not exist, so it shouldn't be in the style sheet.  Since it doesn't exist, it causes an error on every page that uses server.css (all of the pages).  Now its gone...
I don't think there are any adverse effects of this, but someone else should try this out briefly before merging.
> Removed 'down_arrow.png' from styling

- site/app/templates/admin/Extensions.twig
- site/app/templates/admin/LateDays.twig
Twig needed a `|raw` to not escape some json data
> Fix autocomplete results being escaped and breaking things

- migration/migrator.py
Fix for build break in 9ba562103d7f7df4c09b7eef308d46d0ecfaaed6 where I messed up the ordering of the migrator environments. This is what I get for not waiting for Travis to finish for a "simple fix" that I tested against an already stood-up environment (bug was that --initial for system relies on master already being run for the migrations_system table to be created for us to record the system migrations in).
> Fix ordering having system before master for migrations

- .setup/update_database.py
- migration/migrations/course/20180618210747_forum_category_colors.py
PR #2135 mistakenly edited update_database.py (deprecated after early June 2018)
Instead these changes are placed in a database migration script.
> [BUGFIX] DB migration for PR #2135 forum category colors

- .setup/install_system.sh
Adds the ability to trigger xdebug profiling from web.
Currently writes profile outputs to `${SUBMITTY_REPOSITORY}/.vagrant/Ubuntu/profiler`
> Allow remote xdebug profiling

- site/app/controllers/grading/ElectronicGraderController.php
Current version is some variable about which version is being viewed, active version is the real "have they submitted" check.
> Fix grading checking current version instead of active version

- site/app/controllers/admin/LateController.php
- site/app/templates/admin/Extensions.twig
- site/app/templates/admin/users/MoreExtensions.twig
- site/public/js/server.js
As discussed in the meeting, I added a popup for when adding an extension to team assignments.  Now, if the instructor decides to grant an extension to a student who's in a team, a popup will appear and ask if the same extension should be granted to other members. If the instructor chooses "No", then only the student selected will be granted the extension. (This extension will carry on even if he switches teams).
Closes #1725
> Added popup for extension view (For teams)

- site/app/controllers/student/SubmissionController.php
- site/app/views/submission/HomeworkView.php
Gives full access graders permissions to upload for students, bulk upload, and upload split items.
Gives limited access graders permissions to bulk upload and upload split items.
Interfaces for each group changed accordingly so that they can see their options.
closes #1724
> Let Full Access/Limited Graders upload for students

- site/app/controllers/grading/ElectronicGraderController.php
It was only letting you grade if there was no submission, instead of the inverse.
> Fix no submission check being backwards

- site/app/controllers/grading/ElectronicGraderController.php
Somehow the reordering PR reverted the variable name change, but this should fix it.
> Fixes autograding

- .setup/CONFIGURE_SUBMITTY.py
Fixed a problem which caused CONFIGURE to fail when switching from worker to primary mode.
> Fixed Configure script to allow switching between worker and primary mode

- site/app/controllers/admin/AdminGradeableController.php
- site/app/models/gradeable/Gradeable.php
This changes are unrelated to any of the other PR's, so I'm putting them in their own, small PR...
I added helper methods in the new `Gradeable` class for getting the number of text/numeric components for `NUMERIC_TEXT` gradeables so the user doesn't need to count them every time.  Additionally, I added helper methods to check if the gradeable is (student) pdf upload and integrated them into the Admin Gradeable controller
Lastly, The Gradeable class lazy loads its teams instead of just its `anyTeams` status, which will be useful in the `ElectronicGraderController`.
> Misc helper methods in new Gradeable model

- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/gradeable/TaGradedGradeable.php
These two parameters had cases when they could be null, but PHP type enforcement doesn't allow null values, so these would throw errors even though the functions were designed to handle the case when they were null.
> New Gradeable model parameter fixes

- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- .setup/distro_setup/ubuntu/xenial/setup_distro.sh
- .setup/install_system.sh
As it turns out, due to the installation order of python2 pip followed by python3 pip, `pip` was symlinked to `pip3` and so the change in #2387 to change `pip install clang` to `pip2 install clang` broke things in unexpected fashion.
Given that installation of `python-clang-#.#` installed the bindings anyway, it was redundant to try and install a second set for python2.
> Remove pip2 install clang installation line

- site/app/libraries/database/PostgresqlDatabaseQueries.php
Apparently this is never used, but the syntax error keeps showing up in PhpStorm
> Fix SQL Syntax Error in getGradingSectionsByUserId

- site/app/models/gradeable/Gradeable.php
That's twig's job. It can handle it. It's a strong, independent templating engine that don't need no pre-escaped variables.
> Don't escape instructions url for the database

- .setup/php-fpm/pool.d/submitty.conf
This now matches the default value of proxy workers we've setup within Apache.
If this fixes things for students, we will have to add to the sysadmin installation instructions details about tuning these values (at least say that they should look at them, and link them to a resource that better explains what it means).
```
sudo cp /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/php-fpm/pool.d/submitty.conf /etc/php/#.#/fpm/pool.d/
sudo service php#.#-fpm restart
```
where `#.#` is either 7.0 (Ubuntu 16.04) or 7.2 (Ubuntu 18.04)
> Bump up value of pm.max_children of PHP-FPM conf

- site/app/templates/grading/electronic/Details.twig
For gradeables with no manual grading, the index page of all students no longer has buttons that say "Grade", but rather "View"
closes #2414
> Changed manual grading page to say "View" instead of "Grade"

- site/app/models/gradeable/Gradeable.php
If the build file does not exist, then `file_get_contents` will emit a warning, which is undesirable.  To mitigate this, we check for the file's existence before trying to read its contents.
> Checking for build errors makes sure build file exists

- site/app/controllers/NavigationController.php
Getting `GradedGradeable`s from the database checks first that the requested array of `Gradeable`s isn't blank and throws an exception if it is.  The nav page was not checking that the array of `Gradeable`s it was passing wasn't blank before requesting the `GradedGradeables`.  Now it properly does this check.
> Fixed blank course throwing nav page exception

- site/app/authentication/DatabaseAuthentication.php
- site/app/authentication/PamAuthentication.php
- site/app/exceptions/CurlException.php
- site/app/libraries/Core.php
- site/app/libraries/Utils.php
- site/tests/BaseUnitTest.php
- site/tests/app/authentication/DatabaseAuthenticationTester.php
- site/tests/app/authentication/PamAuthenticationTester.php
A bug was introduced where the tmp files that pam had created were not being properly cleaned up. Fixed that bug, and then added full test suite for the two authentication methods so that we don't have that bug again.
> Fix bug with cleaning up after PAM and add tests

- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- .setup/distro_setup/ubuntu/xenial/setup_distro.sh
Webupd8 hasn't updated their java package yet and it's causing vagrant to fail. This is a janky (but hopefully functional) fix for that.
> Java 8 Package Fix

- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/gradeable/AutoGradedGradeable.php
- site/app/models/gradeable/GradedGradeable.php
- site/app/views/NavigationView.php
If a student has submissions for a gradeable, but no active version, the database method constructing the `GradedGradeable` will fail.  To remediate this, the `GradedGradeable` always has an `AutoGradedGradeable` even if there are no versions (empty array) and no active version (active version set to 0).  Going on the assumption that there will always be this instance also simplifies use of this class.
> Fixed nav page exception with cancelled submission

- site/app/controllers/AuthenticationController.php
Login page no longer crashes when given an invalid password.
closes #2436
> Fixed error on wrong login password

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/Access.php
- site/app/templates/admin/users/GraderList.twig
- site/app/templates/grading/electronic/Status.twig
Couple quick things
Fixes the no View All for Full access grader with no sections bug ( closes #2484 )
Instructors do not display "All" for sections by default in graders tab
Instructors will be in View All mode by default on the Grading Details Page
> Quick fix for various View All things

- site/app/controllers/admin/AdminGradeableController.php
The gradeable config actually gets rebuilt on due date changes now.  Second, if the course is archived and the files/folders are not writable, there is no longer a warning emitted from `file_put_contents` and the error message properly gets sent back to the client.
> Fixed gradeable build handling and unwritable file handling

- .setup/bin/setup_sample_courses.py
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/server.js
Add rotating sections to teams in the sample data.
~~Remaining is making the instructor create team button on the grading page default to the rotating section of the student.~~
closes #2359 and closes #2345
> Sample data team rotating sections

- site/app/libraries/Output.php
(see #2362).  All json routes manually create the response structure to comply with our modified JSend response structure, which means many of these routes don't actually comply to the spec.  These additional methods in Output construct the response from the required and optional parameters for each response type.  Moving forward, these should be used instead of `Output::renderJson`.
> Jsend output methods

- site/app/controllers/admin/AdminGradeableController.php
The check that the build queue file and form config file used to determine if the file was available for writing was incomplete.  It would considered the "no file exists" case to be a "can't write to file" case.  Now, the `is_writable` method is used in conjunction with `file_exists` to allow writing in the "no file exists" case.
> Fixed Create Gradeable 'Build queue entry failed'

- site/app/models/GradeableComponentMark.php
- site/public/templates/grading/Mark.twig
In the old model, marks were url encoded before saved to the database.  The new model saves the original text in the database, so I updated the old gradeable to do the same.  The string escaping is now done in the view layer (twig.js in this case)
This should actually fix the issues @KCony has with mark names being url encoded.  Any existing names will need to be fixed, but the grading interface won't break the names anymore.
> Removed Mark Note Url Encoding from Model and put in View

- site/app/models/gradeable/TaGradedGradeable.php
The `TaGradedGradeable` doesn't initialize its `graded_component_containers` well.  It relies on being constructed from the postgres db query correctly, but in the case that no grades exist and the instance is generated as a blank, then the containers array isn't initialized.  This adds code to construct blank component containers.
> Fixed TA lab grading always failing

- .setup/install_system.sh
I was getting the following error when trying to do a vagrant up (caused the vagrant install to crash as the correct user groups weren't being created): 
`grep: ]: No such file or directory
[: missing ]`
These changes allow me to install completely.
> install_system.sh tweaks

- .setup/install_system.sh
- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
Closes: #2493
Allows instructors & full access graders to view email address of thread author.
> Forum Thread: Show author email address

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
Closes #2540
The `getGradedGradeables` query treats blank arrays as blank arrays instead of the same as nulls, so if the request used/team lists are blank arrays, they are truly treated as blank arrays and no data is retrieved.  Similar behavior is also in `getGradeableConfigs`.
> Gradeable model queries handle blank arrays more intuitively

- site/app/controllers/grading/ImagesController.php
- site/app/views/NavigationView.php
- site/app/views/grading/ImagesView.php
Closes #2508 
Upload button changes in the above issue. Added a breadcrumb for student photos. Fixed some permissions preventing students from getting into instructor link of student photos as well as full-access graders and limited-access grader when appropriate (no student photos).
> Upload Images Part 2

- site/app/libraries/Access.php
Looks like self::ALLOW_SELF_GRADEABLE was not overriding self::CHECK_GRADING_SECTION_GRADER and if you weren't in your own section you couldn't see your own checks.
> Fix mentors not being able to see their own autochecks

- site/app/models/gradeable/Gradeable.php
- site/app/models/gradeable/TaGradedGradeable.php
- site/app/views/NavigationView.php
There was a `just_regraded` field added to the `Gradeable` class (both versions).  I do not know what the plans are for this variable, but it doesn't belong in the `gradeable\Gradeable` class.  As described in the class-doc, this class is only for the configuration of a gradeable.
It appears like this variable is being used to notify the user if they have new regrade messages, but this should be done using a notification system shared (at least somewhat) with the forum, et al.  Since notifications need to be per-user, not per submitter, it probably should not be in the GradedGradeable model either.
> Removed out-of-place code from new model

- site/app/templates/admin/admin_gradeable/rubric/ElectronicFileRubric.twig
A simple, front-end only fix for #2571 on the edit gradeable page.  The instructor cannot edit the No Credit or Full Credit mark in the interface (point value or title).  It also appears uneditable.
> Edit gradeable electronic rubric can't edit no/full credit mark

- site/app/models/gradeable/GradeableList.php
The `GradeableList` was still using the date getters from the old model when sorting.  This updates the names of the date getters to match the new model.  This was causing the order `beta` and `open` gradeables appeared to not match the nav page before the refactor.
> Fixed nav page Gradeable order

- site/app/views/grading/ElectronicGraderView.php
The graded questions column on the electronic gradeable summary page no longer shows if there is no TA grading.
closes #2559
> Only show graded questions if there is TA Grading

- site/app/controllers/student/SubmissionController.php
Closes #2600.
Graded gradeable count was beging checked against 0 instead of 1, so this error would be thrown for any instructor-submitted assignment.
> Fixed Inconsistent teams error on submission page

- site/app/libraries/database/DatabaseQueries.php
Modified version of #2588 that shouldn't error when ordering by rotating section (int) and not registration section (varchar).
Fixes #2597
> Fix ordering on status page

- migration/data/course_tables.sql
- migration/migrations/course/20180730032400_regrade_request_teams.py
- site/app/libraries/database/DatabaseQueries.php
Closes #2370.
Added a migration to allow the `regrade_requests` table to support teams as well as users (symmetric to how `gradeable_data` supports teams/users).  Also updated the database queries that access these fields.
The  motivation behind this is to associate a regrade request with a submitter, so it can be associated with a `GradedGradeable` in a way symmetric to how the rest of the new model functions.
Tested: migrate->rollback->migrate without any errors.
The regrade request ecosystem seems to also be working as before
> Regrade requests table supports teams

- site/app/controllers/MiscController.php
Closes #2630 
This is a temporary fix to close the loophole where any limited access grader can delete files from the server until the `Access` class handles these permissions.
> Fix grader file permissions

- site/app/templates/Navigation.twig
Currently if you use custom html in the banner on the nav page it shows up escaped. So this will fix that.
> Fix nav page custom banner not being raw

- site/app/controllers/admin/ConfigurationController.php
- site/app/templates/admin/Configuration.twig
The course settings page was not allowed to accept a blank course name previously, but now it will.
Also, it is displaying the proper value for the course name instead of the displayed course name (which was causing it to display the course code for courses with blank names).
closes #2637
> Course settings page allows blank course name

- .setup/install_system.sh
On Vagrant 16.04 was getting an error due to grep returning 1 when results are empty, and then a syntax error on the `CREATE DATABASE` in the event that the `submitty` DB didn't yet exist.
This patches both those things; not sure what happens on live or 18.04
> Install script fix

- site/public/js/ta-grading-mark.js
Closes #2677
I'm not sure why this error started happening, but these couple of line fixes appear to make grading and editing work as before.  The problem was that the selector used to check if a component was open was the `tbody` not the `table` and the `table` is what had the `display: none` style that was being checked against.  The custom mark issue is that the makeup of the custom mark cell may have been changed and `me.parentElement` did not evaluate to the `tr` element as expected, rather it evaluated to one of the other nested elements inside of the `td` that the custom mark message is in.
> Fixed TA grading mark saving and custom mark errors

- site/app/controllers/admin/AdminGradeableController.php
- site/app/models/gradeable/Gradeable.php
Closes #2704
Fixes the error with null dates being stringified when the shouldn't have been. (#2704)
If the 'student submit' setting was changed to 'yes', the dates will fail validation if the late days extend after the grades released date, but not immediately.  It will fail the next time its loaded from the database, which will make the gradeable uneditable.  This fix just requires the due date + late days to be before the release date regardless of if students can submit.  We may want to change this behavior in the future, but this is important to fix now.
> Misc Gradeable Date Fixes

- .setup/INSTALL_SUBMITTY_HELPER_BIN.sh
- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
With #2421 being merged, the variables these two scripts were checking for are now always defined in Vagrant. This fixes it by checking for a different variable that isn't always set.
> Fix INSTALL_SUBMITTY_HELPER scripts not setting variables in Vagrant

- .setup/INSTALL_SUBMITTY_HELPER.sh
- site/app/authentication/PamAuthentication.php
- site/app/libraries/Core.php
- site/cgi-bin/pam_check.cgi
- site/tests/app/authentication/PamAuthenticationTester.php
This removes the need for writing user credentials to a file to do the PAM check which improves the overall security model, while simplifying the directory structure/permissions/needs.
> Use POST request to check pam authentication

- .setup/install_system.sh
Adds aliases for convenience for Vagrant:
* install_submitty_site - Runs just SUBMITTY_INSTALL_HELPER_SITE.sh
* install_submitty_bin - Runs just SUBMITTY_INSTALL_HELPER_BIN.sh
* submitty_code_watcher - Runs the code_watcher.py
> Add three new convenience aliases

- site/public/css/diff-viewer.css
An extra `float: left` was causing the lines to float right when your resolution was too small. Closes #2194
> Fix diff viewer indenting

- site/config/course_template.ini
We moved from using hidden_details.database_name to database_details.dbname in #1359 and left the original in as we moved the system over to using the new field in subsequent PRs. Given that those subsequent PRs have been since merged and this field is no longer ever used anywhere, we should just remove it from the `course_settings.ini` since having it both is potentially confusing.
> Remove deprecated database_name field from course settings

- .setup/INSTALL_SUBMITTY_HELPER_BIN.sh
Creation/installation of these two scripts belong in the primary "SUBMITTY_INSTALL_HELPER" as at least the case of the second one, it requires running the "fillin_variables" function which I didn't want to fully import for these smaller quick scripts, but I at least don't want the permissions to break when just running them one-off. I do dislike that I've duplicated the chown/chmod from the primary script to here, though I'm not sure what the better solution might be.
> Fix permissions on scripts when running just the HELPER_BIN

- grading/load_config_json.cpp
- sbin/autograder/grade_item_main_runner.py
- tests/integrationTests/tests/c_failure_messages/validation/results.json_does_not_compile
- tests/integrationTests/tests/choice_of_language/validation/results.json_c
- tests/integrationTests/tests/choice_of_language/validation/results.json_cpp
- tests/integrationTests/tests/choice_of_language/validation/results.json_python2
- tests/integrationTests/tests/choice_of_language/validation/results.json_python3
- tests/integrationTests/tests/cpp_simple_lab/validation/compile_error_results.json
- tests/integrationTests/tests/json/assignment_config/config.json
- tests/integrationTests/tests/json/validation/results.json
closes #2749 
Makes it more clear to students which file they are looking at in their results. 
Also makes port assignment deterministic when grading networked programs, allowing prints involving port numbers to be diffed.
> Update Descriptions for Automatic Validators to be More Specific and Make Port Assignment Deterministic

- tests/integrationTests/tests/tutorial_16_docker_network_python/__init__.py
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/correct_grade.txt
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/correct_results.json
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/incorrect_grade.txt
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/incorrect_results.json
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/infinite_response_grade.txt
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/infinite_response_results.json
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/large_response_grade.txt
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/large_response_results.json
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/syntax_error_grade.txt
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/syntax_error_results.json
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/udp_correct_grade.txt
- tests/integrationTests/tests/tutorial_16_docker_network_python/validation/udp_correct_results.json
This PR adds the skeleton of a integration test of Tutorial 16. 
However, it will be unable to run until lib.py executes the docker network creation code found in grade_item_main_runner.py. This work is tabled for now, but should be pursued in the future per #2757
> Began Work on Docker Network Integration Test

- bin/build_homework_function.sh
- bin/grading_done.py
- sbin/autograder/packer_unpacker.py
- sbin/submitty_autograding_shipper.py
- site/app/views/submission/HomeworkView.php
* When we fail to pack up a job (missing files), make sure we don't leave stuff behind in /tmp (we were filling it up)
* If we fail to pack up a job, just remove that job from the queue (it was spinning attempting to regrade and filling the log with duplicate errors)
* Don't error when an instructor without a team accesses the submission page
* Add to the list of permissions changes so that multiple users can run build autograding for a course without permissions errors
> Multiple small but important bug fixes

- site/app/libraries/DateUtils.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/gradeable/AutoGradedVersion.php
- site/app/models/gradeable/Gradeable.php
- site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig
The default php date parsing method does not accept years > 9999, so this new method accepts years with 5 digits, but is stricter.  It accepts the format the database returns and the format from the Edit Gradeable interface.  For good measure, I changed 'infinity' to be towards the beginning of the year 9999 so this is less of a potential issue in the future for code that doesn't use this date parsing method.
The method requires years, months, days, hours, minutes, seconds, and optional sub-second and time zone.
> Date parsing for new gradeable accepts years > 9999

- site/app/controllers/admin/AdminGradeableController.php
- site/app/libraries/DateUtils.php
- site/app/models/gradeable/Gradeable.php
- site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig
This removes the date-time picker from the edit gradeable page since it was not handling time zones very well (very poorly actually) and, among other things, was causing very frustrating behavior to the user.
We need to investigate other date-time picker options that _do_ handle time zones (and daylight savings time) well.
> Remove datepicker from Edit Gradeable page

- site/app/models/gradeable/Gradeable.php
the team lock date was being validated in sequence with the other date properties when it wouldn't be appropriate to do that.  This was forcing the `team_lock_date` to be between the `grade_released_date` and the `regrade_request_date`.  Now, this date won't be influenced by any other dates.
> Fixed 'Team Lock Date' Not setting propertly

- site/app/controllers/AuthenticationController.php
Fixes allowing instructor to checkout anyone's repos. The authentication process should be tied more into the Access library that Glen wrote at some point for better checking of "is this something you're allowed to see based on having to grade it?", but this at least keeps the functionality equivalent to what it was last semester.
I think the next step for this is to create proper unit testing of all conditions and then go from there for using the access class.
> Fix checking out another's repo using grading permissions

- grading/execute.cpp
Better logic to detect incorrect number of .py files on the python command line
> [Bugfix] Better python multiple file warning

- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
- site/app/templates/autograding/AutoChecks.twig
- site/app/views/AutoGradingView.php
fixes #2736 
This was broken a while ago, we stopped printing the autochecks that did not have an actual file.
This also tweaks the create/edit gradeable page.
> Display autochecks even if they lack an actual file

- .setup/bin/update_repos.sh
- .setup/install_system.sh
- .setup/travis/autograder.sh
- Vagrantfile
- grading/main_validator.cpp
- grading/seccomp_functions.cpp
- migration/migrations/system/20180829105219_update_drmemory.py
- tests/integrationTests/tests/c_failure_messages/validation/results.json_does_not_compile
- tests/integrationTests/tests/choice_of_language/validation/results.json_c
- tests/integrationTests/tests/choice_of_language/validation/results.json_cpp
- tests/integrationTests/tests/choice_of_language/validation/results.json_python2
- tests/integrationTests/tests/choice_of_language/validation/results.json_python3
- tests/integrationTests/tests/cpp_simple_lab/validation/compile_error_results.json
- tests/integrationTests/tests/cpp_simple_lab/validation/warning_results.json
- tests/integrationTests/tests/json/validation/results.json
- tests/integrationTests/tests/tutorial_09_java_testing/validation/does_not_compile_results.json
fixes #2528 
adds more to the system call whitelist for clang++ and sort
modifies the message for compilation errors/warnings
updates dr memory version for ubuntu 18.04
updates tutorial examples (for test case isolation & other minor tweaks)
> [Bugfix] system calls for clang++/sort & drmemory update on Ubuntu 18.04

- grading/load_config_json.cpp
- sbin/autograder/grade_item_main_runner.py
Closes #2750
Adds the ```use_router``` boolean to the instructor configuration file globally and per testcase. If ```use_router``` is false, all containers are added a single network, the router is not injected, and messages are not logged. ```use_router``` is true by default.
> Routerless Mode

- site/app/controllers/forum/ForumController.php
- site/app/templates/submission/homework/SubmitBox.twig
- site/app/views/NavigationView.php
- site/app/views/forum/ForumThreadView.php
- site/app/views/submission/HomeworkView.php
Ugly, but it 
Fixes #2762 and fixes #2786 
However I'm not at all sure what it does when the dates for an assignment cross a daylight savings change.
Core problem seems to be that the database(s) have their timezone set to UTC.
See discussion in #2786
> Debug timezone for open/due/etc action buttons & forum

- migration/data/course_tables.sql
- migration/migrations/course/20180904185348_max_date_constraint.py
- site/app/controllers/admin/AdminGradeableController.php
- site/app/libraries/DateUtils.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
Closes #2772, #2771
Added constraints to the database so that the maximum date allowed is March 1, 9999.  In PHP, these dates will be clamped (no error / warning) to be at most February 1, 9999 so that we can still load the dates if the db dates are later than the soft limit.  I figure when we redo the date-picker, we can tell the user this is invalid then or not let them do it at all.  The error message now for the date being too large appears similarly to how the other date errors are displayed (red background + tooltip)
> Added Gradeable Date Constraints to DB/PHP

- sbin/autograder/grade_item_main_runner.py
closes #2728
Container's now use an untrusted user instead of root.
Docker containers now begin with no network rather than default bridge. 
In networking assignments, networks are now created with the --internal flag.
> Use Untrusted When Docker Grading (and other security tweaks)

- .setup/bin/update_repos.sh
- grading/execute.cpp
- grading/execute.h
- grading/load_config_json.cpp
- sbin/autograder/grade_item.py
- sbin/autograder/grade_item_main_runner.py
This pull request allows professors to specify networks such that a single node listens on only a single port, on which it receives all of its messages. 
To this end, the PR adds the ```single_port_per_container``` boolean to the config.json both globally and per networked testcase.
This feature does not yet work with the router.
This PR also:
* fixes an issue with dispatcher actions that was causing main runner to crash.
* Allows compilation testcases to specify a container_image.
> Allow Professors to Specify Network with Many to One Connections

- site/app/views/submission/HomeworkView.php
Fixes autograding scores in the drop-down menu for versions. Previously the array wasn't sorted correctly and versions would show a score for a different submission.
fixes #2785
fixes #2416
> Fix autograding score for version list

- site/app/controllers/admin/AdminGradeableController.php
If the config repository is blank, php would attempt to traverse the entire course file structure since `<course-dir>/<repo-dir>` evaluated to `<course-dir>/`, which may be what is causing out-of-memory errors.  Now, this operation will only occur if there is a non-blank config repo name.
> Blank Config Repository won't traverse entire course directory

- site/app/views/AutoGradingView.php
Small bugfix when finding the precision, gets rid of this error that appeared in some sample submissions.
fixes #2828
> Fix count function trying to read a nonarray

- site/public/js/ta-grading-rubric.js
Closes #2822 
If the grader opens and closes the component without changing any of the assigned marks or the custom mark point value / text, the grader for that component will not be overwritten to the logged-in user.  This is achieved on the client-side by not saving the graded component unless changes are made.
> Component Grader only overwritten if changes are made

- site/app/templates/grading/electronic/RubricPanel.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-rubric.js
Closes #2845
When a component is closed, the gradeable version that the grader is looking at gets saved into the graded component.  This prevents the 'Version Conflict' Issue on the grading list view and the submission page.
> Correct gradeable version set when components are saved

- grading/load_config_json.cpp
- sbin/autograder/grade_item_main_runner.py
___This pull request is accompanied by another in the tutorial repo.___
This PR changes knownhosts files from comma delimited csv to space delimited text files. As a result, the ```container_name``` variable for a container is now constrained to not include spaces.
Knownhost files now take the form:
```
sender recipient port_number
```
When ```single_port_per_container``` is specified in the assignment configuration, knownhost files are shortened to the form:
```
recipient port_number
```
In a future PR, all knownhost files will be moved to the simplified form, and an ```overlay.txt``` file will be specified, which will define which nodes on the network can communicate.
> Knownhosts Refactor

- site/app/controllers/AuthenticationController.php
- site/app/libraries/Output.php
- site/tests/BaseUnitTest.php
- site/tests/app/controllers/AuthenticationControllerTester.php
Adds the following tests of the VCS login method:
* Test not having a user_id (error)
* Test not having a password (error)
* Test not having a gradeable id (error)
* Test not having a fourth ID paramter (error)
* Test the course not loading (error)
* Test authentication failed (fail)
* Test user not in course (fail)
* Test user having grading success (success)
* Test null gradeable and different fourth id from first id (fail)
* Test null gradeable and same fourth id as first id (success)
* Test team gradeable and user not in team (fail)
* Test team gradeable and user in team (success)
> Add test suite for VCS login method

- site/app/libraries/Output.php
- site/app/models/Breadcrumb.php
- site/app/templates/GlobalHeader.twig
- site/public/index.php
- site/tests/app/models/BreadcrumbTester.php
Changes:
* Get rid of the unused `$top` variable on Breadcrumb items
* Rename the `$icon` variable to `$external_url` to better capture what it does (adds an external link)
* Simplify having external links on breadcrumbs by allowing specifying both internal and external urls
Previously to have an "external" following an "internal" breadcrumb, you'd have to define the normal breadcrumb and then define an "external" breadcrumb with a blank title, link, and a specific flag. This change allows you to define a breadcrumb that has an either/or internal or external link and then show the title with a link and if you specify an external url, then the external link icon will appear after that breadcrumb.
This also adds testcases for this model as well for functionality
> Simplify and add tests for the breadcrumb model

- migration/data/course_tables.sql
- migration/migrations/course/20180919150904_remove_instruction_url_limit.py
Closes #2856 
Since the instruction URL had a maximum length (255 characters), longer urls (especially those with url-encoded characters) would go beyond this limit and would cause a database exception to be thrown.  This PR adds a migration to remove this hard limit.
> Removed length limit for instruction URL

- site/app/controllers/admin/ConfigurationController.php
- site/app/models/Config.php
Fixed course settings not saving.  There is a function that was removed from `Config` and its usages were not updated.
> Course settings save again

- site/app/models/GradingSection.php
- site/app/models/gradeable/Gradeable.php
Changes the way that grading sections are grabbed so that the null registration section is displayed after clicking view all.
closes #2818
> Displaying null section for view all

- site/app/views/NavigationView.php
Minor fix for the room templates display: the page will opt for not displaying a room template instead of crashing when trying to display it anyways.
This still requires that the output sent to {$COURSE_DIR}/reports/seating/{$GRADEABLE_ID}/{$USER_ID}.json have "building" and "name" entries corresponding to a valid room template in the repository in order to properly display, but it just shouldn't crash if it isn't there.
> Room templates bugfix

- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/public/js/ta-grading-rubric.js
- site/public/js/ta-grading.js
Somehow the features got lost. I think it's due to the major JS rewrite. Currently, the feature is still clunky and only works with upload.pdf. Also I don't think the components themselves specify which file the page belongs to. 
I also made sure that when a PDF is zoomed in, the scrolling scales with it. However, the behavior might be different with different resolution.
> PDF scroll to page number

- site/app/templates/submission/regrade/Discussion.twig
- site/public/css/server.css
The request regrade box in the TA screen will force the post content to wrap instead of adding a horizontal scroll bar.
Fixes #2862
> Make long request regrades wrap instead of scrolling

- site/app/templates/GlobalFooter.twig
Changed file:
site/app/templates/GlobalFooter.twig
Layout tables should not have a header.
> VPAT -- Global Footer

- site/app/templates/Navigation.twig
Changed file:
site/app/templates/Navigation.twig
`<label>` tags are intended for control elements.
This is the initial view after logging in (shows available gradeables).
> VPAT -- Default view

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/Access.php
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/ConflictMarks.twig
- site/public/templates/grading/GradingComponent.twig
Part of #2853
Previsouly, the 'publish' setting could only be edited in rubric tab of the edit gradeable page, but that restriction has been lifted.  Any grader can edit the 'publish' setting of any mark (except the first mark).  
Additionally, the mark conflict popup has been modified to expose the 'publish' values for the marks.  Overall this reduces complexity of the code and removes a few possible weird corner cases.
> Mark 'publish' can be edited in the grading interface (by any grader)

- site/app/templates/autograding/TAResultsNew.twig
Closes #2851
The custom mark was being displayed whenever the total score of the component is nonzero (i.e. full credit or no credit) instead of if the custom mark score is nonzero.
> Fixed display of custom mark for student view of ta grading

- site/public/js/gradeable.js
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/GradingComponentHeader.twig
- site/public/templates/grading/GradingGradeable.twig
Closes #2910
This completes the logic that switches whether the conflict message appears or not on a component in the electronic TA grading interface.
> Fix TA Grading Interface Per-Component Version Conflict Message

- site/public/js/gradeable.js
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/GradingComponent.twig
- site/public/templates/grading/GradingGradeable.twig
When opening a component for the first time as a full access grader or above, clicking a mark to grade would cause the 'verify' button to appear.  Now, the 'verify' button won't show up unless another grader has already graded the component (as it should).
> 'Verify' button won't show up before closing component on first grade

- site/public/css/ta-grading.css
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/Mark.twig
part of #2853 
Marks that are 'published' get highlighted in the ta grading interface.  I think I chose a fairly inoffensive color, but I'm not attached to it.
> Published marks get highlighted in TA grading interface

- site/app/templates/autograding/TAResultsNew.twig
This makes the view pdf with feedback box disappear whenever there is no pdf
> Fixes empty pdf-view box

- site/app/libraries/database/PostgresqlDatabaseQueries.php
Fixes sql query to only get regrade requests specific to that gradeable.
Originally the sql query would try and get all regrade_requests made by a student instead of looking for a specific request. After a student has made 1 request, the query would then grab that request and attach it to every single gradeable for that student. Then submitty would think a regrade already existed for that gradeable and would prevent a student from ever opening another request.
This should prevent that first request (and any others) from showing up where they don't belong.
I don't think any data was lost while this bug was open, probably just got misplaced somewhere...
Fixes #2900
> Fix regrade request not being gradeable specific 

- site/public/css/server.css
- site/public/css/ta-grading.css
- site/public/js/gradeable.js
- site/public/js/ta-grading-rubric.js
- site/public/js/ta-grading.js
- site/public/templates/grading/Component.twig
- site/public/templates/grading/Functions.twig
- site/public/templates/grading/GradingComponent.twig
- site/public/templates/grading/GradingComponentHeader.twig
- site/public/templates/grading/Mark.twig
- site/public/templates/grading/TotalScoreBox.twig
Mostly minor changes, including:
- Starting mark indexes from zero
- Fix typing mark numbers that don't exist (closes #2873)
- Fix badge colors not being consistent with #2145 
- General style improvements with mark rows including borders and number sizing
More grader ui stuff to come later as I work my way around the new codebase
> Grader ui cleanup + consistency

- site/app/models/GradeableComponent.php
- site/app/models/gradeable/GradedComponent.php
This address the issue that @holzbh was experiencing with generating grade summaries showing incorrect scores for ungraded components.  Now, the logic that determines the grade for a component in both the new and the old model accounts for the count-down case properly, so a component must either have a mark assigned to it, or a custom mark to have a non-zero score.
> Ungraded Count-Down Component Has 0 Points

- site/app/templates/autograding/AutoResults.twig
- site/app/views/AutoGradingView.php
The autograding hidden point values were displaying after ta grading was done, now they are only displaying after ta grades are released.
closes #2947
> Autograding hidden cases display when grades release

- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/models/Notification.php
- site/app/templates/Notifications.twig
- site/public/css/bootstrap.css
This PR addresses: 
- If there is a thread/post that is deleted the corresponding notifications for this component is also deleted (this includes all notifications where this post is a parent, and notifications where this post is a reply). 
- The notification to the user that is generated when their thread/post is deleted no longer is a link to the deleted thread.
- Fixes forum label visual display overlapping with post preview content
Visual explanation:
User gets two replies:
One of the replies to the user is deleted:
The thread/post of the user is deleted:
Closes #2787.
> Deleted component notification fixes

- site/app/models/GradeableComponent.php
- site/app/models/gradeable/GradedComponent.php
Count down components with a custom mark will not have any common marks.  The custom mark may have a 0.0 score to indicate full credit, but it will have text.  The recently-changed logic would show the student that they received 0 points for the component instead of full credit.  This PR changes the logic to look at the custom mark text instead of the score.
> Ungraded count-down component checks comment instead of score

- site/app/templates/autograding/TAResults.twig
- site/app/templates/autograding/TAResultsNew.twig
- site/public/css/server.css
- site/public/templates/grading/GradingComponent.twig
- Closes #2504 
- Fixes an issue where the point values were being wrapped on every char if the mark was too long
- Fixes ta/student comment not having newlines when displayed
> Mark text wrapping + alignment

- site/app/controllers/HomePageController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/models/Course.php
- site/tests/app/models/CourseTester.php
This also simplifies the loadDisplayName function to just use the stored reference to $Core to get the Submitty path instead of having it be passed in which was redundant.
> Create testcases for Course model

- site/app/views/submission/HomeworkView.php
Closes #2914 
This is an artifact of when the old gradeable model was being used for regrade requests and it didn't support team regrade requests.
I tested the entire lifecycle of a gradeable with regrade requests and teams and it all seems to work as expected.  However, until #2970 gets merged,  the `Grade` button on the `Details` page for the team that has a regrade request doesn't turn into `REGRADE`.  It still displays the score as if no regrade request existed.
> Removed artificial restriction on team regrade requests

- site/app/templates/grading/electronic/PDFAnnotationBar.twig
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFInitToolbar.js
This fixes the problem discovered by @holzbh, where if you zoom in, the annotation won't save. Also fixed the zoom indicator so it's correct on start.
> Fix zooming not saving problem

- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/public/css/ta-grading.css
This makes the directory view of submission panel takes up 100% of the space, so the sliding mechanism works correctly.
> Fix problem if sliding panel is too big 

- .setup/INSTALL_SUBMITTY_HELPER.sh
#3010 reminded me that I had agreed to do this ages ago (sorry Barb).
This should better future-proof of us on whatever PHP version we're running for restarting the FPM service.
> Use variable PHP version to restart FPM

- site/public/css/ta-grading.css
- site/public/js/ta-grading-rubric.js
Closes #2678 
The 'checked' state of the custom mark will continue to update automatically based on the presence or absence of text in the 'message' input.  
If you try to check the custom mark without any text in the 'message' input, the 'message' input will turn red and get a on-hover tooltip that prompts the user that they need a non-blank message.  
Additionally, if the custom mark does have 'message' text, but the grader unchecks the custom mark, they will be prompted to confirm their decision to delete the custom mark since the message / point value will be lost when the component is saved.
> Custom Mark Improvements

- site/app/controllers/student/SubmissionController.php
- site/app/templates/autograding/AutoResults.twig
- site/app/views/AutoGradingView.php
- site/app/views/submission/HomeworkView.php
- site/tests/app/controllers/submission/SubmissionControllerTester.php
Closes #2994 
The hidden test cases are only visible for the version that the TA graded.
Graded version:
Other Version:
> Hidden testcases only visible for graded version

- site/app/controllers/MiscController.php
- site/app/libraries/Access.php
Was passing an AutoGradedVersion (object) to a function that was expecting an integer
> Fix "download all files" when students can only download active version

- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
The missing bracket caused crashed in Safari, but didn't raise an error in the chrome dev console. Adding the bracket fixes the issue in Safari, and allows me to create gradables without an issue.
closes #3028
> Fix New Gradable in Safari

- site/app/controllers/student/TeamController.php
- site/app/templates/grading/electronic/Details.twig
- site/app/templates/submission/Team.twig
- site/app/views/submission/TeamView.php
Students can no longer invite students who are in the null section.
This PR also removes the autofill search for invite usernames so students will need to know the 
exact user_id before inviting people.
If a student tries to add a user in a null section they will receive an error saying "cannot invite {user_id}"
closes #3060
> Prevent Students from adding students in null section

- site/app/controllers/forum/ForumController.php
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
PR includes:
- Helps prevent double form submission by disabling button when form is submitted. 
- The return json object for forum function will ensure json_encoding which should prevent the javascript from failing to decode in some cases. 
- Add extra padding to version history popup
- Users can now delete their own threads/posts without having to be a ta/instructor
> Better handling for double posts

- site/app/views/GlobalView.php
Check if current state is in debug mode and don't send to twig template if this is the case.
> prevent queries from loading if not in debug mode

- site/app/libraries/MultiIterator.php
Closes #3072
There was a bug in the `MultiIterator` that didn't seek to the next valid iterator _after_ next, so the iterator was terminating before any of the team gradeables were loaded.
> Fixed team and non-team gradeables not returning together

- site/app/controllers/student/SubmissionController.php
This solves the issue that some instructors were having when choosing the scanned exam preset.  the preset set the 'view after grades' field to true, but when permission checks were being done to determine if a user can view the submission page, checks for 'grader' status were being done improperly.
> Instructors can bulk upload 'view after grades'

- site/app/controllers/student/TeamController.php
Addresses part of #3085 
This only closes the title part of the issue.  It does not solve the multi-team users or the feature requests.
It looks like there was a not-equals that should have been an equals in the cancellation logic.
> Fixed team invitation cancelling

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/controllers/student/SubmissionController.php
- site/app/templates/autograding/AutoResults.twig
- site/app/templates/grading/electronic/AutogradingPanel.twig
- site/app/views/AutoGradingView.php
Fixes regressive bug where graders could view hidden test case details in the submission page.  The 'Details' button no longer shows up and the testcase no longer appears clickable.
> Graders cannot view hidden testcase details from submission page

- site/app/models/gradeable/Gradeable.php
If any gradeable is a team assignemnt with `has due date` set to false, the nav page to fail to load for anyone accessing the course(Frog robot).  This fixes the improper handling of null values and types and prevents the crash.
> Team Gradeables without a due date won't crash the nav page

- site/app/templates/submission/regrade/Discussion.twig
When a grader changes a student's grade and then goes and responds to a regrade request, any changes to the grade will now be saved.
closes #3016
> Save grading info when responding to a regrade request

- site/app/controllers/MiscController.php
- site/app/controllers/pdf/PDFController.php
fixes #3096. Should fixes the problem with all html entities. I tested it with all the keyboard special characters, all of them works except for '/', which the issue says we can forbid.
> HTML decodes filename

- site/app/controllers/pdf/PDFController.php
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/app/views/PDFView.php
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/ta-grading-rubric.js
This will be changed in the future, but right now a variable is being passed all over the place and it's messy. Because I first need to make an async request to get the PDF grading page, then I need to wait for the PDF.js to render, it's a whole mess :(. But this PR should fix the scrolling problem. After test grading is finished I'll refactor Submissionpanel.twig which will make the code much cleaner. I tested it with multiple pdfs, and they all seem to work. But someone else should test it also.
> Scrolling fix for pdf grading

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
Fixes bug where "# of students who viewed" stat counted NULL section
Fixes bug where "Autograding statistics" counted all versions, not just active_version
Fix #2841 and Fix #3105
> TA Grading stats bug fixes

- site/app/controllers/admin/ReportController.php
Fixes #3112 
If the gradeable doesn't have student submission enabled or doesn't have a due date, then late days don't make sense.  This fix makes the late day calculation in the reports controller more consistent with the late day calculation in the Gradeable model.  This inconsistency will be resolved when the reports controller uses the new gradeable model (in progress).
> No Due Date / Not Student Submit can't have 'bad' status in reports/summaries

- site/app/templates/submission/homework/BulkUploadBox.twig
This (might) help the submit & delete buttons on production from throwing an alert even though the action went through fine.
closes #2957
> Bulk upload "submit" & "delete" buttons fix

- site/app/controllers/NavigationController.php
- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/models/Notification.php
This PR closes #3108, which will mark unseen notifications as viewed when viewing the corresponding thread.
> Clears related notifications if thread is viewed

- site/app/controllers/GlobalController.php
- site/app/controllers/admin/PlagiarismController.php
- site/app/templates/admin/PlagiarismHighlightingKey.twig
- site/app/views/admin/PlagiarismView.php
I have included some screenshots below. To maximize the space of the matching code, I made a popup for the highlighting key.
> Plagiarism view fixed height

- site/app/controllers/admin/AdminGradeableController.php
- site/public/js/admin-gradeable-updates.js
Closes #3100 
There are two things: first, the rebuild is only triggered by the button press or the config file change (as requested).  The noteworthy removal is that changes to dates (even the due date) will not trigger a rebuild.
The other change was to the client-side.  There were some premature requests sent to the server for updates that were just rebounds of the data loaded into the page causing the gradeable to be rebuilt on page load.  These events are now filtered out before being sent to the server.
> Reduce frequency of rebuild gradeable

- site/app/models/gradeable/LateDayInfo.php
- site/app/templates/LateDaysTablePlugin.twig
Changes "Maximum number of late days allowed for this assignment" column to display the number of late days allowed for _the gradeable_ , instead of the maximum number of late days a _given student_ can spend on the assignment. 
Fixes #3162
> Change "Max. late days allowed" column in late days table

- site/app/models/User.php
- site/app/views/submission/HomeworkView.php
It looks like the crashes were caused by rendering the late day message when an instructor isn't on a team. I've added a check to avoid this in the special case that the user is an instructor and is not on a team.
fixes #3168
> Add special case for instructor not on team

- site/app/views/submission/HomeworkView.php
This PR will always show the grade inquiry discussion if an inquiry has been made on time before
Fixes #3199
> Allow students access to grade inquiries if they made one before the deadline

- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
Creates a log file in `/_course_/lichen/logs/_gradeable_/lichen_job_output.txt` so that multiple plagiarism jobs can run and output logs independently.
> Isolating lichen log output per gradeable

- site/app/controllers/student/SubmissionController.php
- site/app/templates/submission/homework/BulkUploadBox.twig
Fixes team bulk uploads.
A check had been added which wouldn't allow a submission if the specified students were not on a team. The intended functionality is to generate a team this case rather than to fail. The new changes restore this functionality. Also fixed a bug in the submission twig which was causing teams to be improperly saved.
> Fix Team Bulk Uploads

- .setup/distro_setup/debian/jessie/setup_distro.sh
- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- .setup/distro_setup/ubuntu/xenial/setup_distro.sh
This is something that exists within the repos for the distro and doesn't require us adding a PPA and shouldn't break for some time every time there's a new security update.
> Use OpenJDK instead of Oracle JDK for Java 8

- site/app/templates/forum/ForumBar.twig
- site/app/views/forum/ForumThreadView.php
The current thread id number was not being passed in when rendering the forum bar which made the 3 change display buttons default to a thread id of "undefined" and the page would then reload to the default top forum post instead of keeping the user on the current forum post.
I had already made a pull request which I closed because it had an error due to the current thread id variable not always existing, this one however fixes that issue.
This fixes half of issue #3218 however I don't have a fix for the other half, so I don't want this to automatically closed that issue. If this gets merged, I can put a comment on that issue to let people know what still needs to be fixed.
> [Bugfix] Fixed the forum bar, change display, buttons 

- grading/execute.cpp
The mouse now moves to the origin before centering at the start of windowed grading. This should help graphics programs determine its initial position.
> Windowed Grading Fix

- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
Previously, the install script installed netplan.io=0.40.1~18.04.3
However, this version has been removed from the Ubuntu repositories, as
the latest version is now 0.40.1~18.04.4
(see https://packages.ubuntu.com/bionic/netplan.io)
This allows setup_distro.sh to succeed when provisioning a new VM
> Install netplan.io=0.40.1~18.04.4 in setup_distro.sh

- site/app/libraries/database/PostgresqlDatabaseQueries.php
If there is a team gradeable without any teams yet, the query will return a single row with null user data (since it `LEFT JOIN` users).  Now, it does a normal `JOIN` on either users or teams. to prevent this empty row.
This empty row was causing the reports controller to crash since it assumed there would be valid team data for a team graded gradeable.
> Fixed join strategy on Graded Gradeable query for team gradeables

- site/app/templates/course/CourseMaterials.twig
This commit removes the 'onclick' handler from the 'Pop up the file in a
new window' button on the Course Materials page. By using the
'target=_blank' attribute, the link will be opened in a new tab, just as
the event handler currently does.
By directly specifying an 'href', rather than opening the link from
JavaScript, the browser is able to provide the usual link context menu
options (copy link, open in new window, etc)
> Implement course materials 'Pop up' button with pure HTML

- site/app/templates/course/CourseMaterials.twig
Closes #3193 
The `file-viewer` class is now case insensitive so that files with `PDF` extension is treated the same as `pdf`.
Before:
After:
> Fix course material extensions

- .setup/INSTALL_SUBMITTY_HELPER.sh
- grading/load_config_json.cpp
- more_autograding_examples/test_notes_upload/config/config.json
- more_autograding_examples/test_notes_upload/config/test_input/separate_pages.py
- more_autograding_examples/test_notes_upload_3page/config/config.json
- more_autograding_examples/test_notes_upload_3page/config/test_input/separate_pages.py
- sbin/shipper_utils/systemctl_wrapper.py
- sbin/shipper_utils/update_and_install_workers.py
Don't use strict checking to allow more test notes pages to be accepted by the reader (such as duplicate dictionary entries at a byte). Not sure if this will allow some bad things through, documentation wasn't very specific.
Tested and it seems like [make_all.py](https://github.com/Submitty/InstructorTools/blob/master/QR_TestMaker/make_all.py) doesn't need the option. Might still add it since it will leave the input a little more flexible if the tool is adapted for sources other than through the script introduced in #3254
> Make Test Notes Upload configs More Tolerant of PDFs

- site/app/views/forum/ForumThreadView.php
The icons for unresolved thread(), resolved thread(), announcement() on the scrollbar now have tooltips.
Tooltips were also added to the Make Announcement in a forum post and change depending on if the thread is an announcement.
> Added Forum Tooltips

- site/app/controllers/admin/ReportController.php
Closes #3274
If the gradeable is a team assignment, the `team_members` field in the gradeable output will contain the members of the user's team.  If the user was not on a team for that gradeable, then they are the only member on the team.
Note: The `team_members` list contains all members of the team (including the `this` user)
> Gradeable report contains team members

- .setup/INSTALL_SUBMITTY_HELPER.sh
- sbin/autograder/grade_item.py
- sbin/autograder/grade_item_main_runner.py
- sbin/autograder/grade_items_logging.py
- sbin/submitty_autograding_shipper.py
- sbin/submitty_autograding_worker.py
Adds logging for various stack traces created by errors caught during autograding.
Should be reviewed, as it was difficult to force good code coverage while testing.
Will likely require tuning as we decide which errors do and do not need to be logged by the system.
> Log Autograding Exceptions

- .setup/travis/autograder.sh
I've been seeing some amount of build errors on Travis-CI due to network hiccups when fetching things from Github. This will cause those commands to now be retried up to 3 times to hopefully make things a bit more robust and see less failures.
> Use travis_retry for getting external dependencies for Travis-CI

- site/app/libraries/database/PostgresqlDatabaseQueries.php
There is an issue with sorting by user or team id.  Since a gradeable will only be one or the other, we define 'team_id' to have no order affect on users and 'user_id' have no affect on teams.
This fixes a database exception being thrown when trying to grade team gradeables.
> Fix grading team gradeables

- site/app/templates/Navigation.twig
- site/app/views/NavigationView.php
Navigation view updates to work with userid.json files which are generated by Rainbow Grades as of Submitty/RainbowGrades#3 when the "Display Custom Message" option is selected for a course in Course Settings.
The table-in-a-table code looks kind of ugly, but it's what was being posted as raw HTML from Rainbow Grades before so I just copied it verbatim. Open to styling changes. We might want to discuss if this should serve a more generic purpose, like allowing per-student messages to uploaded in the JSON through a new field? I'm not sure how much use we expect this feature to see, for now I just focused on migrating the existing behavior (formerly done through userid_message.html files).
> Custom Messages / RainbowGrades Compatibility

- site/app/controllers/admin/AdminGradeableController.php
Changing the VCS subdirectory for a gradeable will put the gradeable in the build queue (and update the form .json file) similar to how changing the autograding config will.  @bmcutler  is this what you were looking for?
> VCS subdirectory will rebuild gradeable

- .setup/bin/versions.sh
- grading/load_config_json.cpp
- sbin/autograder/grade_item.py
Closes #3255
Added global ```container_options``` object to the autograding configuration json. Within, default values for ```container_image```, ```use_router```, and ```single_port_per_container``` may be specified.  
Changed the global flag ```docker_enabled``` to be a new string ```autograding_method```, which can currently be specified as ```docker``` or ```jailed sandbox```. If ```autograding_method``` is not set, ```jailed sandbox``` is used by default. If an assignment built before this pull request is graded, ```jailed sandbox``` is assumed.
> Add Global Container Defaults to Assignment Configuration

- site/app/models/Config.php
- site/app/templates/GlobalHeader.twig
- site/app/views/GlobalView.php
- site/public/css/server.css
- site/tests/app/models/ConfigTester.php
Closes #1415.
You can add a `system_message` to the `config/submitty.json` file that it will show on every page of the system. If the field is missing or blank, then it's not shown. I'm not sure where we want to surface configuration of this (do we want to add a new page on explanation of the config files on submitty.org?).
> Add ability to show system message

- site/app/views/grading/ElectronicGraderView.php
- site/public/css/server.css
If a limited access grader gets verified  the details page now shows a half green half yellow stoplight 
closes #3289
> Grader stoplights for verifiers  

- grading/execute.cpp
- grading/load_config_json.cpp
- grading/load_config_json.h
- grading/myersDiff.cpp
- grading/window_utils.cpp
- grading/window_utils.h
Closes #3248 
* Adds validation of graphics action syntax to ```load_config_json.cpp```
* **Changes the default screenshot name from #.png to screenshot_#.png**
* Moves some amount of error checking out of ```window_utils.cpp``` and into ```load_config_json.cpp```
* Allows users to name screenshot files using the ```name``` field.
* Fixes a bug which caused the imagediff to crash when either the expected or actual file didn't exist.
* Sets the stage for GIF capture.
> Validate Graphics Actions

- grading/execute.cpp
- grading/load_config_json.cpp
- grading/load_config_json.h
- grading/myersDiff.cpp
- grading/window_utils.cpp
- grading/window_utils.h
- site/app/libraries/Utils.php
Closes #1096
Requires and contains PR #3295
* Adds the ```gif``` graphics action, which creates a GIF of the running student application.
* Allows users to configure gifs using the following arguments:
* ```seconds```: __required__. The duration of the gif in seconds.
* ```name```: a custom output name for the gif. By default it is gif_#, where # is the gif's order in the testcase.
* ```frames_per_second```: The number of images per second displayed in the gif. Defaults to 10. Maximum value is 30. Gif display rate on Submitty roughly synchronizes to the fps chosen.
* ```preserve_individual_frames```: If true, saves the images used to create the gif. Defaults to false.
An example gif specification is as follows:
```
{
"action" : "gif",
"seconds" : 5,
"name" : "custom_gif_name", …
```
> Add gif Graphics Action

- site/app/controllers/student/SubmissionController.php
Bulk upload was failing due to an improper check, which assumed that ```FileUtils::writeJsonFile``` returned true on failure.
This PR should fix the issue and re-enable bulk upload.
> Fix Bulk Uploads

- sbin/autograder/grade_items_logging.py
- sbin/submitty_autograding_shipper.py
*  Removes a line which was logging an expected file not found error.
*  Stops grading from throwing an exception when unable to gain a lock on the log file.
* We should briefly discuss how we want to handle cases where we can't gain a lock on the log file. We aren't blocking, so an exception is thrown when a lock is unavailable. We are not properly handling this exception throughout the system. This PR catches and ignores the exception.
> Fix Excess Autograder Logging

- grading/load_config_json.cpp
- sbin/autograder/grade_item_main_runner.py
To facilitate database grading, we now allow docker containers to be specified using the new ```server``` field. If a container is a server, it is understood that it will have no commands, and rather persists for the entirety of a testcase. In this way, an instructor can create a container which holds a database, but runs no commands. Other containers then connect to the server with their queries.
Of note: in order to allow postgres to initialize, the container holding a database can't be invoked as the untrusted user. @MasterOdin , what are your thoughts?
> Add Support for "Server" Containers on a Network

- more_autograding_examples/test_notes_upload/config/config.json
There was a syntax error in `test_notes_upload/config/config.json` due to a string missing delimiters. I've made a separate copy of the config and tested on live, and it seems to work as expected with this quick fix done.
> Test Notes Upload Config Syntax

- site/public/css/server.css
Fixes #2312 
Color of link is changed `#4078C0` to `#405E90`
This changes color contrast ratio from 4.1 to 5.93
Before:-
After:-
> Contrast Error in Global footer view

- site/app/templates/GlobalHeader.twig
- site/public/css/server.css
- site/public/js/server.js
Fixes #2729 
Remove rebundant link in side bar.the <a> showing icon is removed and `button.getTitle()`  is wrapped in span tag which is made  `Display : none`  on pressing sidebar when side bar is opened.
Icon are made large  when side bar is closed. This will increase accessibility of the button
> Remove redundant link in sidebar

- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
Partially addresses  #2896 -- will leave this issue open.
Before :-
After :-
`Fieldset` is given to `radio` button which answer `"what is the type of gradeable "`. With legend as `"what is the type of gradeable "` .This changes are done in `AdminGradeableCreate.twig`  
Legend `"How should graders be assigned to grade this item?"`  is given to fieldset in `AdminGradeableGraders.twig`
> Radio Button Grouping

- site/public/css/ta-grading.css
- site/public/templates/grading/Gradeable.twig
- site/public/templates/grading/SavingTools.twig
Closes #3308 
I'm able to reproduce the saving problem on FireFox, but only when closing the page (it saves fine when clicking another link on the page).  I added a "save" button  that just closes the component.  This appears in both edit and grade mode because the saving problem appears in both modes (in FF at least).  I restyled the 'save' and 'cancel' buttons to have the same style as all of the other buttons on the site to stay consistent.  It looks something like this:
It looks like it is possible to stall the page exit long enough for the request to complete on all browsers by popping up the 'unsaved changes' alert, but this popup is very annoying when you don't need it and it isn't trivial to figure out if it is necessary.  It should be looked into, however.
> Added a 'save' button to the component

- bin/grading_done.py
- bin/regrade.py
- sbin/autograder/grade_item.py
- sbin/autograder/grade_item_main_runner.py
- sbin/autograder/packer_unpacker.py
- sbin/build_config_upload.py
- sbin/count_autograding_logs.py
- sbin/run_lichen_plagiarism.py
- sbin/submitty_autograding_shipper.py
Closes #2392.
The gist of it is that the [glob](https://docs.python.org/3/library/glob.html) adds some functionality to support the `**` notation only in 3.5+, while [pathlib](https://docs.python.org/3/library/pathlib.html) supports it in 3.4+, and so to overcome that, I made a glob module under submitty_utils. By switching, we can now drop the `submitty_utils.glob` module. The only difference between the two is that the pathlib glob always returns a generator (glob.glob returns a list, glob.iglob returns a generator) and that all of the returned paths from pathlib are `Path` objects (and so have to be converted to strings for our normal usage onward).
I've created issue #3277 to replace the remaining usages of the the actual [glob](https://docs.python.org/3/library/glob.html) module.
> Move from submitty_utils.glob to Path.glob

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/distro_setup/ubuntu/rpi.sh
- .setup/install_system.sh
- migration/migrations/system/20180619110916_lichen_package_installation.py
- migration/migrations/system/20181028021533_qr_codes.py
- migration/migrations/system/20190306102812_python_permissions.py
Submitty sets the permissions on the global Python module installation directory. While this might have been necessary at one point, it's no longer and we should leave the permissions set to the normal default.
This PR contains a migration to reset the permissions on the folder back to what they are on a normal system and then removes any trace of Submitty changing the permissions on those folders.
> Leave permissions on python package folder alone

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/distro_setup/ubuntu/rpi.sh
- .setup/install_system.sh
- sbin/autograder/grade_item.py
- sbin/submitty_autograding_shipper.py
Turns out we have to write permissions of python packages always due to default umask and fix some syntax errors I introduced in prior PR
> Fix some bugs introduced by other PRs

- site/app/authentication/PamAuthentication.php
- site/app/templates/Authentication.twig
- site/cgi-bin/pam_check.cgi
- site/tests/app/authentication/PamAuthenticationTester.php
Fixes #3353 
Fatal error is given when password  is empty provided USER_ID is not empty and points at a real user id. This problem can be easily solved by providing required attribute to both of `Password` and `User_id` and ensuring that they're filled in and non-blank on the front-end as well as make sure backend handles the case where the fields could be blank, returning a failed authentication attempt instead of throwing an error.
> Error Handling on Login Page

- tests/e2e/test_submission.py
The styling on the submission page changed since the last time these were run, so had to update some of the xpath stuff.
Tests are still disabled on Travis.
> Fix running submission e2e tests locally

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/GradingOrder.php
- site/app/models/GradingSection.php
Part 1 of improved grade order, this includes the GradingOrder model and should have no interface changes (I'm splitting those into a later PR so they can happen over time). 
New things:
- Grading now skips "no submission" students (closes #3192)
- Order on details page should match order of grading (closes #3245)
> Better grading order: New model / Order fixes

- site/public/css/server.css
The sidebar icons move to the side when the sidebar is opened. Ideally they should remain at the same place. This PR fixes this issue.
It has been tested on both latest versions of Firefox and Chrome.
Before:
After:
> Fixed sidebar icon positions

- site/app/views/admin/PlagiarismView.php
There are two warnings in the Plagiarism Detection mainpage.
They appear because [PHP 7.2 changes its behavior](https://wiki.php.net/rfc/counting_non_countables) when evaluating `count(null)`. Although this change is backward compatible, to avoid possible future bugs resulted from `count(null)`, I added a default value for null.
```
( ! ) Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/submitty/site/app/views/admin/PlagiarismView.php on line 329
--
1 | 0.0013 | 455432 | {main}( ) | .../index.php:0
2 | 0.1720 | 3342520 | app\controllers\AdminController->run( ) | .../index.php:238
3 | 0.1744 | 3683264 | app\controllers\admin\PlagiarismController->run( ) | .../AdminController.php:58
4 | 0.1745 | 3683680 | …
```
> Handle null in count() function

- site/app/templates/GlobalFooter.twig
- site/app/templates/HomePage.twig
- site/app/templates/LateDaysTablePlugin.twig
- site/app/templates/admin/Report.twig
- site/public/css/server.css
addresses a portion of #2936 
According to  this issue there are mainly two types of `Tables` :
1) `Layout tables`
2) `Data tables`
According to me data tables are present in following code :
1) `site/app/templates/GlobalFooter.twig`
2) `site/app/templates/LateDaysTablePlugin.twig`
And `Layout Tables` are as follows :- 
1) `site/app/templates/HomePage.twig`
2) `site/app/templates/admin/Report.twig`
Thead and caption is given to `site/app/templates/GlobalFooter.twig`.
> Customizable theme using layout tables

- site/app/templates/autograding/AutoResults.twig
- site/public/js/server.js
Added loading message to testcase output since it loads the entire image at once.  This makes the design more responsive, especially for large output files.  Loading messages are similar to the TA grading loading messages.  I just made the text the same style as the old `Details` text, but it would be easy enough to make them look like buttons if we want.
> Added loading message to testcases

- site/app/libraries/database/DatabaseQueries.php
This makes the list of posts in forum stat page clearer.
Before:
After:
> Show posts in ascending order in statistics page

- site/app/templates/admin/Extensions.twig
- site/public/js/server.js
1. In late days' page, if you add one entry, the trash bin icon will not be displayed before refreshing.
Before fix (the trash bin icon doesn't show up):
After (the trash bin immediately shows as soon as the entry is entered):
2. In extensions' page, I think there is a typo. Because the list below consists of gradeables instead of rubrics. It is changed to "Select Gradeable" in the pr.
> Fix minor bugs in Late Days' page and Extensions' page

- .setup/distro_setup/setup_distro.sh
In case you re-run `setup_distro.sh` after the umask default is updated, this could make the `chmod +rx` line to fail with it complaining:
`/etc/update-motd.d/00-header: new permissions are rw-r--r-x, not rw-r--r--`
> [Bugfix] Explicitly set the Vagrant MotD file permissions

- site/app/controllers/grading/ElectronicGraderController.php
- site/public/js/ta-grading-rubric-conflict.js
- site/public/js/ta-grading-rubric.js
Closes #3411
Previously, the `publish` setting on a mark was only being set at save-time and not at add-time.  Now, when a mark is added the publish setting will be saved.
> Fixed "Publish" setting on new marks

- grading/load_config_json.cpp
Fixes mouse movement actions. Mouse movement actions can now be specified with the action string ```move```, ```move mouse```, or ```mouse move```.
> Graphics Action Mouse Movement Fix

- site/app/templates/autograding/TAResultsNew.twig
- site/public/css/ta-grading.css
- site/public/js/server.js
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/EditComponent.twig
- site/public/templates/grading/GradingComponent.twig
- site/public/templates/grading/Mark.twig
- site/public/templates/grading/OverallComment.twig
Fixed issues in original PR causing the no credit / full credit mark to not change when the count up / count down buttons are pressed.  This was due forgetting to change a `input` to a `textarea` tag in one of the JS functions.  I have combed through similar kinds of statements and found no other occurrences of that error.
> Better Multi-Line Support for TA Grading

- .setup/INSTALL_SUBMITTY_HELPER.sh
This fixes a bug where on the first time running INSTALL_SUBMITTY.sh, jq would throw some amount of errors as version.json had not yet been created, as it's created by `track_git_version.py`.
> Run script to generate version.json before trying to read it

- site/app/templates/GlobalHeader.twig
- site/app/templates/NotificationsSettings.twig
- site/public/js/drag-and-drop.js
- site/public/js/server.js
There are several places where the `fa-times-circle` is used incorrectly for success messages.
This PR replaces the incorrectly used `fa-times-circle` to `fa-check-circle`
For example:
The following is the incorrect version of the message:
Which after correction results in:
Currently due to hard coded `fa-times-circle` in `GlobalHeader.twig` the messages for success do not show `fa-check-circle` for example: successful login.
I am working on adding an if condition based on `message.type` for the same
> [Bugfix] Changed fa-times-circle to a fa-check-circle in success messages

- site/tests/app/models/gradeable/GradeableListTester.php
This PR:
- Adds tests for gradeables without submission due dates.
- Refactors the code a little bit by following TODO
- Increases code coverage
> Add tests for gradeables without due dates

- site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
In "New Gradeable" page, if I enter the gradeable title first, and then enter the gradeable id, the title that appears on the top of the page does not change.
This is fixed by binding the function `onTitleChange` to the change event of `g_id` too so that the title on the top changes when `g_id` changes.
> Update the new gradeable header as the ID changes

- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
> [Bugfix] Remove extra > on id line for create gradeable form

- site/app/controllers/admin/UsersController.php
- site/app/templates/admin/users/RotatingSectionsForm.twig
Closes #2366 
This pull request adds another option for clearing all rotating section assignments, in other words, this option makes all the assigned rotating sections of students/teams NULL.
> Option for Clearing All Rotating Section Assignments

- site/app/controllers/forum/ForumController.php
Happen to find a typo in a variable name.
announcment -> announcement
> Fix typo: announcment -> announcement

- site/app/views/forum/ForumThreadView.php
This PR fixes the problem that, after clicking "Show Deleted Threads", the text of the button remains unchanged.
The expected text of the button should be "Hide Deleted Threads" like the "Hide Merged Threads" button next to it.
Before:
After:
> Fix const text of "Show Deleted Threads" button

- site/app/templates/grading/electronic/Details.twig
- site/public/css/server.css
Fixes #2690 
Legend are added to `site/app/templates/grading/electronic/Details.twig`
> Add stoplight legends to grade details page

- site/cgi-bin/pdf_check.cgi
Closes #2417 
This change makes bulk uploaded pdf page numbers displayed in order.
Before:
<pdf_name>_0.pdf
<pdf_name>_100.pdf
<pdf_name>_101.pdf
After:
<pdf_name>_000.pdf
<pdf_name>_001.pdf
<pdf_name>_002.pdf
> [Bugfix] Display bulk uploaded pdf pages in order

- site/app/libraries/database/DatabaseQueries.php
Closes #3418 
These changes are made so that only electronic gradeables with `eg_scanned_exam=FALSE` will be selected. 
In the new sql command, `g_gradeable_type=0` is removed from `where` because only electronic gradeables remain after `JOIN` operation.
> Exclude scanned exams from extension menu

- sbin/autograder/grade_item.py
- sbin/autograder/write_grade_history.py
- tests/e2e/test_submission.py
Closes #3309 
This problem occurs because the `revision` is written to `result.json` instead of `history.json` while the submission box reads from `history.json`
After:
> Show git commit hash

- site/app/templates/grading/electronic/SubmissionPanel.twig
Seems like the jquery line was appending to the wrong DOM element. Tested on linux chrome and firefox.
> [Bugfix] Fix scrolling for full view in grading portal

- site/app/libraries/database/DatabaseQueries.php
close #3131.
Solved the buggy information of "has viewed" for grading detail. It is because in the database of gradeable_data, the team assignment doesn't have a user_id, just a team_id. Therefore, the "has viewed" is buggy for team assignment.
> Solved the buggy information of "has viewed" for grading detail

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds templates that are shown to users when opening new issues or PRs. When opening an issue, they are prompted to select if they are opening a bug report or a feature request and are then shown the appropriate template (or can select "other" and have a blank slate). All PRs are shown the single template. This should help to make sure our issues are standalone, easier for outsiders to pick up and work on (or if we come back a year later), and hopefully easier to parse/read.
See https://help.github.com/en/articles/about-issue-and-pull-request-templates#issue-templates for description of how this works.
> Add templates for issues and pull requests

- site/public/js/server.js
> [Bugfix] Fix awkward rendering of CodeMirror on the discussion forum

- migration/migrator/data/course_tables.sql
- migration/migrator/data/submitty_db.sql
- migration/migrator/migrations/course/20190401101720_user_instructor_updated_fields.py
- migration/migrator/migrations/master/20190401101811_trigger_update_user_instructor_updated.py
Fix #3511 
`user_updated` and `instructor_updated` fields are added to course DB's user table and trigger functions updated accordingly.  Now `user_updated` and `instructor_updated` data can be read from course DB and written back to master DB without corrupting user data (provided that data was originally sync'd in the first place, which it should be).
> DB schema fix for possible preferred name data corruption

- site/app/libraries/Utils.php
- site/app/views/submission/HomeworkView.php
Uses student id as a key instead of indexing through list of students, 
should fix the students having previous submissions when they didn't have any
and showing students who did have prev submissions not having any.
credit to @goldschmidt for coming up with the fix.
> Bulk Upload autofill fix

- site/app/views/NavigationView.php
Closes #3530 
* The submit button was shown in red(danger) colour after submission due date even if the gradable has no autograding points and the student had already made submission.
* The submit button will be shown in default colour if the gradable has no autograding points after the due date is over and a submission is made.
* I manually tested by changing the deadlines of tasks using instructor account.
* The cases include,
* Checking colour change for Late Submit button for gradables with no autograding points.
* Case where a student makes submission after the due date, and the colour of the submit button will become default after at least one submission is made for the question.
> [Bugfix] Show Late Submit button in default colour for gradeables with no autograding points

- site/app/templates/grading/electronic/SubmissionPanel.twig
Closes #3533 
Current behavior can be observed by uploading a PDF with symbols in the file name as a student (ex. "hw#4.pdf", "!@#$%^&*().pdf"), and attempting to open the PDF pop-out window as a TA/Grader- the pop-out will display a PHP error because url parameters are not being set properly.
This PR url escapes parameters before the pop-out is created, fixing the issue.
Grepping though the grading directory, this is the only function that seems to have an issue where url parameters need to be escaped before opening in a pop-out view.
> [Bugfix] Add escapes to electronic grading interface

- site/app/controllers/grading/ElectronicGraderController.php
For debugging purposes in the past, the default case for the` ElectronicGraderController` would throw an exception.  That should not be the case, so the default case will show the status page.
> Default case for electronic grader controller won't throw exception

- .github/PULL_REQUEST_TEMPLATE.md
The current PR template uses the phrase 'using the "Fixes #<number>" syntax' which makes it seem to contributors like we only want that syntax (see https://github.com/Submitty/Submitty/pull/3578#issuecomment-483859959) while the Closes #<number> syntax is equally fine (and accomplishes the same thing).
Clarifies that you can use either one to hopefully avoid this type of bikeshedding going forward.
> Clarify PR template on good syntax for issue referencing

- .travis.yml
Fixes #3563
Right now, we have a static version of chromedriver that we need to manually update every time a new version is released and google-chrome on Travis is updated.
This makes it so that the appropriate version of the ChromeDriver is gotten automatically for our version of google chrome (based on algorithm given at https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection?pli=1) so that we should never have to update the .travis.yml file to increment this again.
Tested by letting Travis run and passing all e2e tests which require chromedriver to be working
> [Bugfix] Automatically determine and get appropriate chromedriver version for Travis

- site/app/views/forum/ForumThreadView.php
Fixes #3552
Currently limited access graders can view the stats page
Button to the stats page is not rendered if the user is not a full access grader or instructor.
If the a limited access grader/student tries to access the stats page via url then they are redirected to the forum.
> Prevents limited access graders from accessing stats page

- sbin/send_email.py
fixes #3581 
Tested by recreating error and then encoding the email string and making sure emails containing special characters were sent.
> Fixing Errors Caused by Special Characters in Emails 

- grading/seccomp_functions.cpp
programs with memory errors get terminated for a bad system call
> [Bugfix] add missing system call when drmemory has errors

- site/app/libraries/Output.php
Currently all JS files must live under `site/public/js/`, even if it's third-party code that should live elsewhere for better/cleaner organization of what's stuff we develop and stuff that is coming from elsewhere.
This makes it match how addInternalCss works and allows for referencing scripts under other places (like `site/public/vendor`).
* Not a breaking change.
* Tested by navigating around the site to see if any JS was broken.
> Add optional folder argument to addInternalJs

- site/app/controllers/grading/ElectronicGraderController.php
Closes #3579 
Able to save component after removing all grades, after grading has been done once. 
https://www.loom.com/share/bf3f00cb278f43bebdfebd25f799b2ce
The error was happening due to `$graded_component = null;` at Line 1304. Once the variable was set to null, it is no longer having the method  `$graded_component->isMarksModified()` on Line 1312 of ElectronicGradingController.php 
Moving the latter block of code inside an `else` block makes sure the unset Verified portion is not called for a blank grading. It is not needed in case the grading is completely removed since the graded component itself is being deleted and all its associated information alongwith.
Is this a breaking change? - No
How did you test - there is no specific e2e test for this, so the testing was manual. 
Steps …
> [Bugfix] Saving grading component after removing all grades

- migration/migrator/data/course_tables.sql
- migration/migrator/migrations/course/20190402220151_viewed_responses_update.py
The current DB before running #3268 to add a primary key could have duplicate rows in this table. 
This ensures we first de-duplicate the table before we add the new primary key (or else this migration will fail).
> [Bugfix] Remove duplicate rows from viewed_responses before adding primary key

- README.md
The width attribute for the logo was not being respected by GH and it was sizing it at max-size, which was a bit much as it would take up most of a screen.
Fixes the width to be what we had set it to be way back when we originally added it to the README, and so that you can now see some amount of content underneath it with it still on the screen.
> [Docs] Fix size of logo in README to be more reasonable

- site/app/views/forum/ForumThreadView.php
As a result of the most recent PR, the tooltips changed on the discussion forum when viewing full navbars.
Defaults to normal html tooltips rather than the bootstrap dependency. Fix for the meantime till refactor.
> Fix sidebar hover on discussion forum

- .setup/install_system.sh
Closes #3598 
Postgresql will use UTC any timestamp gotten via current_time instead of relying on the system time (which is ET).
Tested by doing `vagrant destroy` followed by `vagrant up` and then doing `SELECT current_time` in postgresql within Vagrant to see what the timezone it returned was.
Prior to change:
```
$ NO_SUBMISSIONS=1 vagrant up
$ vagrant ssh
root@vagrant:/usr/local/submitty# psql -U submitty_dbuser -d submitty_s19_sample
Password for user submitty_dbuser:
psql (10.7 (Ubuntu 10.7-0ubuntu0.18.04.1))
Type "help" for help.
submitty_s19_sample=# SELECT current_time;
current_time
--------------------
16:35:00.518627-04
(1 row)
```
And after the change:
```
$ NO_SUBMISSIONS=1 vagrant up
$ vagrant ssh
root@vagrant:/usr/local/submitty# psql -U submitty_dbuser -d submitty
Password …
```
> [Vagrant] Set timezone of postgresql DB to UTC

- site/app/templates/admin/Configuration.twig
The course settings page is missing the button for sending seating assignment emails. For some reason this was lost during merge when we reverted the original branch. 
The button now appears when a seating assignment is selected.
> [Bugfix] Adding 'Send Seating Assignment Email' button

- site/app/views/grading/ElectronicGraderView.php
Reply box is currently being displayed. A new parameter was introduced in #3268.
Reply box shouldn't be displayed here.
> Fix param list for generatePostList for TA grading

- .setup/distro_setup/debian/jessie/setup_distro.sh
- .setup/distro_setup/ubuntu/xenial/setup_distro.sh
- Vagrantfile
Officially drops support for Ubuntu 16.04 (xenial) and Debian 8 (jessie) from things that we claim we support (leaving only Ubuntu 18.04 currently). This would allow us to also look at using newer versions of the core languages of PHP and Python through the project as we no longer support these older distros.
This also removes these distros from the Vagrantfile as we will no longer test Submitty against them.
> Add deprecation warnings to top of old distros

- site/public/css/server.css
Fixes #3604
Deleted post shows normal background of white color.This was happening because `viewed_post` was overriding CSS of `deleted` 
`viewed_post` now will not override CSS for `deleted`
> [Bugfix] Fix deleted posts not having gray background

- site/app/libraries/Output.php
This sets a default timezone to use within Twig when trying to display any \DateTime objects. This isn't really added to fix any bugs, but is still probably best practice to just ensure the timezone that Twig might use is the same as the rest of the Submitty php code, which does not use the value in php.ini, but rather one we set ourselves.
See https://twig.symfony.com/doc/2.x/filters/date.html#timezone for documentation on this
> Set default timezone for displaying dates in Twig

- grading/dispatch.cpp
Don't require the jvm_memory flag to be set for the errorIfNotEmpty check for the STDERR output when java code is run.
> jvm_memory flag not set for manually added stderr validation check

- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
Reserved URL chars in prefix/suffix of a qr code do not get cut off
fixes #3564
After moving from a web request to the submitty job system, reserved  URL chars were not getting decoded completely, this fixes that, allowing URLs to be used like before.
> [BugFix] Make QR split upload handle special chars in prefix

- site/app/templates/GlobalHeader.twig
- site/app/templates/Navigation.twig
- site/app/views/NavigationView.php
Fix for areas specifically reported in issue #2311 (possibly closes)
This PR adds/adjusts `aria-label` properties so that 
1. WAVE does not report an "empty link" accessibility error over those hrefs wrapped around a font awesome icon without additional text.
2. Makes the purpose of a couple links better understood.  Note that my screen reader actually _spelled out_ letter per letter, "submitty.org".  Therefore I use "submitty dot org" to have it properly spoken as words.
> VPAT — fix for "empty link" errors.

- .flake8
- .gitattributes
- .setup/install_system.sh
`vagrant up` fails on fresh build as `install_system.sh` still refers to the deleted setcsvfields.py
Allows `vagrant up` to work as expected.
> [Refactor] Remove references to setcsvfields.py

- site/public/css/ta-grading.css
Closes #3501  
Very simple fix : set a maximum height to the comment span, break the long text on overflow and add a scrollbar on overflow to y axis.
https://www.useloom.com/share/bb46f4df0aac4c31a7c866bccd9d0b9a
> Fixed overflow of Overall Comment

- .gitignore
- .travis.yml
- site/app/controllers/GlobalController.php
- site/app/models/AbstractModel.php
- site/composer.json
- site/composer.lock
- site/tests/app/controllers/submission/SubmissionControllerTester.php
- site/tests/app/libraries/AccessTester.php
- site/tests/app/libraries/FileUtilsTester.php
- site/tests/app/libraries/GradingQueueTester.php
- site/tests/app/libraries/LoggerTester.php
- site/tests/app/libraries/database/AbstractDatabaseQueriesTester.php
- site/tests/app/models/ConfigTester.php
- site/tests/app/models/UserTester.php
Currently, we use Travis to test the codebase on versions of languages that we no longer support (see #3625).
Have Travis only test PHP 7.2+ and Python 3.6+ in-line with the minimum version of the two languages available on Ubuntu 18.04
> [Travis] Move to test PHP 7.2+ and Python 3.6+

- site/public/templates/grading/EditComponent.twig
The system requires the user to click exactly on the checkbox to interact with it.
Now the user can check the checkbox by clicking the words next to the checkbox (including the checkbox itself).
This relates to issue #3592.
> Labels added to "Grade by Count Up" and "Grade by Count Down" icons

- .setup/install_system.sh
- .setup/travis/apache.conf
- .setup/vagrant/sites-available/submitty.conf
- migration/migrator/migrations/system/20190510232333_apache_rewrite.py
- site/app/libraries/Core.php
- site/app/libraries/Router.php
- site/app/templates/GlobalHeader.twig
- site/public/index.php
- site/tests/app/libraries/RouterTester.php
- tests/e2e/test_access.py
Closes #933 
This adds in a basic router that can utilize mod_rewrite within apache to allow us to access pages using both `/index.php?semester={$semester}&course={$course}` or `/{$semester}/{$course}`. 
This is fully backwards compatible with the existing setup such that people can go to either the existing URL scheme, or use the new one. Looking forward, we can use the router to pop off pieces to get `$_REQUEST['component']`, `$_REQUEST['action']`, etc.
This is somewhat necessary before tackling a simple setup for some REST endpoints for #300.
> Implement simple router for semester/course

- .setup/CONFIGURE_SUBMITTY.py
Fixes #3156 
Before, the CONFIGURE_SUBMITTY.py script would prompt the user for a timezone, but only write the given time zone to the INSTALL_SUBMITTY.sh script; it would use the default time zone for submitty_conf.json
Now, when running CONFIGURE_SUBMITTY.py, entering a custom time zone will correctly implement the time zone into both the INSTALL_SUBMITTY.sh script _and_ submitty_conf.json.
Tested using Vagrant; first ran CONFIGURE_SUBMITTY.py from GIT_CHECKOUT inside the VM, provided a custom time zone, and checked the two files after completion; submitty_conf.json had the incorrect time zone. Ran same tests again after making changes, and submitty_conf.json contained the correct time zone.
> Fixed ignored timezone for json in CONFIGURE_SUBMITTY.py

- sbin/send_email.py
Moves the email configuration out of database.json and into email.json.   Closes #3430.
Also fixes the log filenames to have leading zeros on the month & date.
> [Bugfix & Refactor] Email configuration & log location

- autograder/autograder/packer_unpacker.py
- bin/regrade.py
- sbin/submitty_autograding_shipper.py
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/GradingQueue.php
- site/tests/app/controllers/submission/SubmissionControllerTester.php
Creates a new type of autograding queue file, prefixed with "VCS__".  These files should be handled ASAP (by the next available shipper), to perform the checkout of files.  Then the task becomes a normal queue file (it only cuts in line to do the checkout, then it goes to the back of the line for autograding).  
Benefits:  The file checkout will only occur once.  And this eliminates the potential git commit timestamp + batch regrade 'exploit' to sneak additional work into an earlier submission.
Closes #3690 
Also...  only does a shallow / depth=1 clone of the repo (less filespace wasted on potentially lengthy edit history).   This closes #1886.  Note:  now that we're doing the checkout more promptly (and only once) the timestamp is less important.  Github repos seem to have an error when …
> Perform VCS checkout at submission time (not grading time)

- sbin/authentication.py
- site/app/controllers/AuthenticationController.php
- site/app/libraries/Core.php
- site/tests/app/controllers/AuthenticationControllerTester.php
The VCS Login method used for Git used core->authenticate() which checks the authentication as well as creating a session and a cookie. Given that we never use the session or cookie again, this is a useless step.
Uses the AuthenticationMethod::authenticate() directly which just does the validation, and does not create a new session or cookie.
> Use Authentication::authenticate directly for VCS Login

- site/app/libraries/ExceptionHandler.php
- site/tests/app/authentication/PamAuthenticationTester.php
- site/tests/app/libraries/CoreTester.php
- site/tests/app/libraries/DiffViewerTester.php
- site/tests/app/libraries/ExceptionHandlerTester.php
- site/tests/app/libraries/IniParserTester.php
- site/tests/app/libraries/database/AbstractDatabaseTester.php
- site/tests/app/libraries/database/DatabaseFactoryTester.php
- site/tests/app/libraries/database/SqliteDatabaseTester.php
- site/tests/app/models/ConfigTester.php
Fixes #3670
Uses the non-deprecated syntax for testing exceptions in PHPUnit
> [Refactor] Fix PHPUnit warnings for test suite

- .setup/distro_setup/setup_distro.sh
Addresses an inconsistency in the "setup_distro.sh" script, which has information on various accounts and their purposes in the VM environment. (https://submitty.org/developer/vm_install_using_vagrant, step 11)
Some of the listed accounts either did not exist or were categorized incorrectly.
The script now has information that matches the table in step 11 on the aforementioned page. Clarifies the role and existence of each account.
NOTE: The system user "root" does not have the password "vagrant". Tested by logging in as another user, then back into root. Likewise, the system user "postgres" does not have the password "postgres", tested the same way (can access from root without password, but not from any other account)
NOTE: There is no database user "postgres" despite various …
> Updated account information in distro setup script

- migration/migrator/loader.py
- migration/test/test_loader.py
Fixes #3661
We ignore files that don't start with a number or end with `.py` as we (safely) assume that these files are not ones which house valid python migration files, and are most likely ones created by an editor (such as emacs).
Only load files in the migrations folders that start with a number and end with `.py` and that have an underscore between the starting numbers and some more text before the `.py`.
> [Bugfix] Ignore migration files not starting with numbers and ending with py

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
The map files are not accessible for the minified vendor files due to permission error.
Can access the map files
> [Bugfix] Chmod site/public *.map files to 444 instead of 440

- site/app/controllers/grading/ImagesController.php
- site/app/templates/grading/Images.twig
- site/app/views/grading/ImagesView.php
* [N/A] Tests for the changes have been added/updated (if possible)
* [N/A] Documentation has been updated/added if relevant
Closes #3704 .
Supports png/jpg/jpeg.
Tested using student.png, student.jpeg, instructor.png, and instructor.jpg - started with just the pngs, then with everything uploaded, then deleted the pngs. Behavior was as expected - when there's only one image for a given user it's used, but if there's multiple images, it's whatever order the filesystem chooses to iterate in.
As a side note, since this seemed to be geared towards specifically .png previously, I kept the extensions limited, but I think file extension checking might be pointless since we also extract the content type and look for `image/...` types. I could change that in this PR if we want.
> Student Photos Supports More Extensions

- site/app/libraries/Output.php
Uses the old deprecated PSR-0 style class names for Twig
Uses the new(-ish) supported PSR-4 namespace class names for Twig
> [Refactor] Use PSR-4 namespaces for Twig classes

- site/app/controllers/grading/ImagesController.php
- site/app/libraries/Output.php
- site/app/templates/grading/Images.twig
- site/app/views/grading/ImagesView.php
From #3712, the change to not buffer things meant that drag-and-drop.js was not being properly loaded for the page, which caused the upload to break.
drag-and-drop.js is properly imported. I've also added a new Twig function to allow us to in-place base64_encode image paths so that we don't have to construct a potentially huge array in the View before going to Twig to display the images. Lowers the amount of memory PHP should use per process slightly, though does not appear to fix the underlying problem of potentially to show huge images.
> [Bugfix] Fix upload for student images and efficiency improvements

- migration/migrator/main.py
- migration/test/test_handle_migration.py
- migration/test/test_status.py
Closes #3525. The args Namespace used to be mutated throughout the run of Migrator. This made it hard to check that function calls of the Migrator had the right arguments as we could only ever check it for the last argument call.
Creates a deepcopy on any loop that uses the base args Namespace object. This makes it possible to test that we are properly calling functions with the right arguments, allowing for testing of multiple courses.
> [Refactor] Do not mutate args Namespace within migrator

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/distro_setup/ubuntu/rpi.sh
- .setup/install_system.sh
Some sequence of calling installation scripts & customization resulted in several java_tools .jar files missing the other read bit.  These (somewhat redundant) permissions changes should ensure this doesn't happen again.
> [Bugfix] installation &  java_tools permissions

- site/app/templates/submission/homework/SubmitBox.twig
- site/public/css/server.css
- site/public/js/drag-and-drop.js
Closes #3155
Previously when using the tab key to navigate through items on the page file submission boxes were passed over, making it impossible for keyboard only users to submit files.
File submission boxes can now receive focus when using the tab key.  When a file submission box has focus and the enter key is pressed the file selector appears.
Mostly tested with Development -> Choice Of Language and also with other development grades that utilize a single file submission box.
> Made file submission box VPAT compliant

- site/app/views/submission/HomeworkView.php
In cases where there is no graded gradeable, ```updateNotebook``` was being called on null causing page failure. This patch fixes the issue with a null check.
> Notebook Hotfix

- grading/execute.cpp
1. Adds php to the list of allowed programs when grading within a docker container. 
2. Fixes a bug which caused ```execute.cpp``` to be unable to detect whether or not it was being run in a container.
> Allow PHP Assignments When Grading in a Docker Container

- sbin/shipper_utils/systemctl_wrapper.py
- sbin/shipper_utils/update_and_install_workers.py
- sbin/submitty_autograding_shipper.py
Closes #3684 
Adds reasonable timeouts to all paramiko worker machine interactions made by Submitty.
Not tested locally.
> Add Timeouts to Worker Machine Interactions

- site/app/templates/submission/homework/BulkUploadBox.twig
Before you had to press the submit button to assign a split pdf to a student 
The behavior now matches team bulk uploads in that hitting enter will attempt to assign 
the split pdf to the student and move to the next file to assign.
I didn't realize this was how bulk uploads behaved before the refactor but it should be good
this fixes the request by Konstantin in the submitty developer email list
> Assign split items on enter (for non-team bulk uploads)

- migration/migrator/data/submitty_db.sql
- migration/migrator/migrations/master/20190526013255_add_api_key.py
Partially addresses #300. Currently, we do not have an API key for each user, which makes it hard to revoke a user's token from the server side. In this case, if a malicious user steals other people's tokens, he/she can impersonate other users at his/her will before the tokens expire, which is not the desired behavior.
An API key is generated for each user, and it gets updated automatically when their password is changed. The key will be later used for authentication via JWT, where it is put inside the "payload" part and the server checks it against the database for every request that requires authentication.
> Add the api_key column to users table

- site/app/libraries/Utils.php
Signed-off-by: fenn-cs <fenn25.fn@gmail.com>
As in #3765, All students (both regular & dropped) are listed twice -- as both a regular student and in the NULL section. 
Fixes: #3765
Show students exactly ones in the dropdown.
- I added a `removeStudentWithId()` function which I could use to achieve the same results but did not use it since it's not efficient to add null students in the array before removing them, so students are only added to their respective arrays no need for removal, however, I contemplating if the `removeStudentWithId()` can be useful in the Utils?
_Moved  ` $students_full[] = $student_entry; ` into NOT NULL condition_
https://github.com/Submitty/Submitty/blob/263fcda4bc45e6076b9a15505ed83b759dae603d/site/app/libraries/Utils.php#L246-L256
_other changes are just …
> [Extensions] update absence drop down lists to show students only once

- site/app/models/Config.php
HTML entities are being encoded twice, for the "upload_message" field. 
Fixes #3513
HTML entities are being encoded once by twig.
Manuel testing indicates that this is not a breaking change.
> [Fix] Remove duplicate HTML encoding for submission/upload message

- site/app/models/gradeable/AutogradingConfig.php
The model referenced non-existent models twice in use statements and the last was pointless (as it belonged to the same namespace).
Removed three use statements that weren't doing anything.
Renamed references to `GradeableTestcase` to appropriate `AutogradingTestcase`
> [Refactor] Fix broken use statements in AutogradingConfig

- site/app/libraries/Utils.php
Small bugfix, when the autofill data was getting prepared it would be returned before the previous submissions were appended to it. 
Fixes #3797
> Fix previous submissions not showing in autofill

- site/app/controllers/NavigationController.php
- site/app/libraries/routers/ApiRouter.php
- site/app/libraries/routers/WebRouter.php
- site/public/index.php
- site/tests/BaseUnitTest.php
- site/tests/app/libraries/routers/ClassicRouterTester.php
- site/tests/app/libraries/routers/WebRouterTester.php
This branch is based on branch `symfony_router`. Will do a rebase once #3743 is merged.
Partially addresses #3740.
Correct me if I am wrong:
This PR will be mainly testing `$this->loginCheck();` - to ensure that the router is working and correctly directs users to go to the login page, no_access page, etc. I don't think we need to test all routes because (1) the testing file would be crazily big, (2) routes are automatically generated from annotations, there is no need to worry about the correctness of that.
Next PR would be about removing the authentication part of the classic router, modifying `buildUrl` related to authentication & adding e2e tests to make sure everything is working as expected.
> [WIP] Test Enhancement for Symfony Router

- site/app/libraries/TokenManager.php
- site/public/index.php
- site/tests/app/libraries/TokenManagerTester.php
Fixes #3713 .
1. Let the TokenManager throw AuthenticationException, which is more informative than the original RuntimeException.
2. Let `index.php` only catches AuthenticationException. If the AuthenticationException is caught, which means the token is invalid, clear the cookie. If there are other exceptions, display the default exception page.
> [Bugfix] Only catch exceptions for JWT parsing for cookie session

- site/app/controllers/MiscController.php
- site/app/templates/course/CourseMaterials.twig
- site/public/js/server.js
Closes #3746 .
In the course material page, instructors and students are able to download zips made of files in a directory.
Instructor downloading the `bin` folder:
Student downloading the `bin` folder:
> [Feature] Download Zips in Course Material Page

- site/app/templates/forum/StatPage.twig
- site/app/views/forum/ForumThreadView.php
Closes #3806 
The following Discussion Forum view now uses Twig- 
`statPage` 
Is this a breaking change? - None discovered yet.
How did you test - Proper working checked manually and by inspecting difference in HTML rendered before and after Twig template.
> [Refactor] Stats page uses Twig

- site/app/controllers/student/SubmissionController.php
- site/public/js/drag-and-drop.js
- site/tests/app/controllers/submission/SubmissionControllerTester.php
Partially addresses #2362 .
Submission Controller now returns JSend format JSON only.
When reading the code of submission controller, I feel that this controller is way too big and complicated. Might need further refactor besides changing JSON format.
> [Refactor] Refactor Submission Controller JSON Responses

- site/app/templates/submission/homework/BulkUploadBox.twig
- site/app/templates/submission/homework/BulkUploadProgressBox.twig
- site/app/templates/submission/homework/SubmitBox.twig
- site/public/js/drag-and-drop.js
When the dialog box for previous submissions appears the focus would still be behind the modal object.
Now the modal object radio boxes are focused on. The user can use tab to focus on the next radio buttons, then the close/submit buttons. Escaping the box will return focus to the next submission to assign. Pressing escape will now exit the modal container.
Pressing enter on a team submission will bring it to the next box unless its the very last in the row, then it'll attempt to submit the team gradeable.
fixes #3791
> Fix tab / enter navigation on bulk upload labeling

- site/app/libraries/routers/WebRouter.php
- site/tests/BaseUnitTest.php
- site/tests/app/libraries/routers/WebRouterTester.php
Controllers rely on `$_GET` to get query parameters.
Let the router pass `$_GET` parameters to controllers.
New tests are added to ensure that the user does not have control over the router by through weird queries.
> [Feature] Enable Router to Pass _GET Params to Controllers

- site/app/controllers/admin/UsersController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/templates/admin/users/RotatingSectionsForm.twig
- site/app/templates/grading/electronic/Details.twig
- site/app/templates/grading/electronic/RandomizeButtonWarning.twig
- site/app/templates/grading/electronic/Status.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/server.js
Closes #2367 
Pull request includes a new button that randomly re-assigns teams to rotating sections.  (For more information see issue closed).  It does not affect student rotating section for the course, and does not affect students that are not on a team yet.  The button will only appear for instructors and only on gradeables that are team assignments graded by rotating section.  If the gradable is open to grading, a popup will warn instructors and require additional confirmation.
Warning Popup:
Fixed a divide by zero exception caused by the "remove all students from rotating sections" option of Manage sections.  However, this option still causes information on the status page for gradeables that are set to be graded by rotating section to be incorrect/nonsense, so a warning banner was …
> Add option to re-assign team rotating sections

- site/public/js/server.js
A temporary patch for #3839, but still needs more debugging to ensure visuals match between student & instructor/grader
An additional condition has been added, to see if any category checkboxes are checked in the create thread page.
Is this a breaking change? - None
How did you test: Checked by trying to create a thread for all types of users, with and without categories selected.
> Fix unable to post thread by student

- site/app/authentication/AbstractAuthentication.php
- site/app/authentication/PamAuthentication.php
- site/composer.json
- site/composer.lock
Closes #1868, addresses PHP part of #318
Adds PHP linter [phpcs](https://github.com/squizlabs/PHP_CodeSniffer) to the project, but does not yet make it mandatory (too many files don't fit it yet). Will work through the files that are not under any sort of flux fixing them and then moving on to the ones being actively working on (working with the "owners") so that everything is (more or less) being linted before fully enabling it.
Documentation on the PHP coding standard has been improved as part of Submitty/submitty.github.io#99.
I've started with fixing the files under `site/app/authentication`.
This is not a breaking change and does not affect the current CI pipeline.
> [CodeStyle] Integrate submitty/php-codesniffer for PHP code style

- .travis.yml
Travis does not actually install the composer dependencies as part of the build, relying on the existence of the composer cache from earlier steps.
Does an explicit composer install (which will pull in from the cache if it exists) to ensure the dependencies exist and are installed.
> [Travis] Add missing composer install line

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
- .setup/submitty_crontab
- migration/migrator/migrations/system/20190617114139_crontab.py
We install the one crontab to a user's crontab. This does throw several errors on the initial installation as the crontab does not yet exist (shown in the failing of Travis for #3863). The user crontab file is also not ideal to be used for automation.
Uses the `/etc/cron.d` interface to add a crontab which is the more standardized way to add crontabs through an installer/automation, at least across several major Linux distros (I checked Ubuntu, Debian, CentOS, and Fedora).
This is a proper solution to issue #3256 (fixing the problems with #3650) in that it's easy to see the user who runs a given cron job (as it's part of the line), their schedule, etc. and it's all in one place in-case we also ever want to add some root specific tasks (like DB backing up or something) to the core system. …
> [Feature] Add dedicated submitty crontab file to repo

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
- site/public/js/pdf/PDFAnnotateEmbedded.js
Closes #3857. PDFs generated with cmaps currently do not load properly.
PDFs will load properly and should be completely readable.
Uploaded a PDF generated with cmaps for grading, opened the pdf-annotation window before applying this fix (got a `Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked")` message. Enabled this patch, warning went away as well as the PDF loading fine.
> [Bugfix] Load compressed cmaps for PDF.js viewer

- .setup/bin/setup_sample_courses.py
Signed-off-by: fenn-cs <fenn25.fn@gmail.com.
In the sample submissions generated by `.setup/bin/setup_sample_courses.py`, no submissions are marked as canceled. All students either have no submission or has an active submission.
Fixes: #2467
`setup_sample_courses.py` would now mark a few submissions as canceled.
The submissions marked as canceled are not defined in a fixed way, rather active_head 0 which represents a canceled_submission has been added to the list that is used to randomly determine the state of a submission.
I set the probability of a submission to be set as canceled, 3 times lower than the probability of other possibilities just so we don't have too many canceled submissions.
> added active head 0 (cancelled submission, to activelist of active heads

- site/app/controllers/AuthenticationController.php
- site/app/libraries/Core.php
- site/app/libraries/routers/WebRouter.php
- site/app/views/AuthenticationView.php
- tests/e2e/test_login.py
Fixes #3843 . Our `ClassicRouter` has a feature that, after a successful login, redirects users to the page that they tried to visit but previously failed due to access control. This feature has been implemented in the `WebRouter`. However, a bug exists that you cannot be redirected if you go to `/authentication/login` directly and try to log in.
Instead of passing the URL to redirect to in the URL like `/authentication/login/{old}`, the old URL to redirect to is passed in GET parameters like `/authentication/login?old={old}`, which looks more natural. When `$old` is empty, go to the homepage as the default page, and the router will take care of it if the user did not successfully log in.
> Use GET params for redirection

- site/app/controllers/grading/SimpleGraderController.php
- site/tests/app/controllers/grading/SimpleGraderControllerTester.php
Partially addresses #2362 .
Simple Grader Controller now uses our JSend format functions. The controller itself has been returning JSend format JSON all the time. This PR just switches to using `renderJsonFail` and `renderJsonSuccess` for easier future maintenance.
`$action` is removed because it is not used in the code.
> [Refactor] Refactor Simple Grader Controller JSON Responses

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
The `INSTALL_SUBMITTY_HELPER*.sh` scripts currently contain some number of errors and is setup such that it will run through regardless of any errors. This makes it hard to catch things that break (such as a `composer install` or `npm install` line) which in-turn break the site.
Closes #2340 as all parts will now be done.
Fixes any outstanding errors on the `INSTALL_SUBMITTY_HELPER*.sh` scripts and enables the `set -e` flag at the top of the script. The parts were the script uses/captures the exit code of the script is surrounded by a `set +e`/`set -e` pair to prevent that breaking, with a note about this at the top of the script.
Added the `set -e` flag to the top of the script and ran the script repeatedly fixing each error in turn that I encountered.
> [Refactor] Fix errors in INSTALL_SUBMITTY_HELPER and use set -e

- site/app/controllers/admin/AdminGradeableController.php
- site/app/controllers/admin/EmailRoomSeatingController.php
- site/app/controllers/grading/ElectronicGraderController.php
`$this->core->buildUrl()`, `$this->core->buildUrl([])` and `$this->core->buildUrl(array())` used to mean "url for the navigation page". However, after we roll out the new router, they are no longer used and they will redirect to wrong places.
Replaced them with `$this->core->buildNewCourseUrl()`.
> [Bugfix] Fix broken redirection caused by buildUrl

- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
The `add_permissions_recursive` function here would only iterate over the final set of `dirs` and `files` returned by `os.walk` instead of every one.
Puts the for loops inside the `os.walk` function so that each set of `dirs` and `files` are iterated through.
> [Bugfix] Fix semantic error in BulkUpload chmod function

- site/app/controllers/admin/LateController.php
Fixes #3449 
`Invalid Student ID` Error is shown when student selected is not from the course. 
1. Go to `Late Days Allowed` in Development
2. Try to insert late days for ta2(ta2 is not in Development but in Sample)
3.  `Invalid Student ID` error should be shown
> [BUGFIX] Improve student validation for late days allowed

- site/app/controllers/admin/GradeableController.php
- site/app/controllers/admin/UsersController.php
- site/app/templates/admin/UploadConfigForm.twig
- site/public/js/server.js
Partially addresses #2362
`UsersController` and `GradeableController` now use our JSend format functions.
To build an API, it is important to ensure that all JSON responses are consistent throughout the whole project.
The current status of #2362 is that after this PR and #3862 are merged, there will only be `ForumController` and `MiscController` that use non-standard JSON functions. I do not plan to work on that currently considering that Anu is editing forum things and Shail is working on bulk upload. 
For the rest of JSON returning functions, their responses are consistent now.
> [Refactor] Refactor User & Gradeable Controller JSON Responses

- site/tests/app/libraries/routers/WebRouterTester.php
Current `WebRouterTester` uses a `for` loop to test various URLs.
Use PHPUnit's [Data Providers](https://phpunit.readthedocs.io/en/8.2/writing-tests-for-phpunit.html#data-providers) instead, which is a more standard way to provide arguments.
> [PHPUnit Tests] Use data provider in WebRouterTester

- .setup/bin/setup_sample_courses.py
The links to courses in the error page are using old-style URLs.
Change to new-style URL.
Run `sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh` to make it update. The error page can be accessed by going to `http://192.168.56.111/index.php?semester=s19&course=development&component=admin` as a student.
> [Bugfix] Update URL for sample courses

- site/app/views/forum/ForumThreadView.php
Categories do not show up in the thread editing form.
Now categories are displayed correctly like before
.
> [Bugfix] Display categories when editing forum threads

- site/public/js/server.js
Fixes #3515 . Presently both error message(Message shown in red) and success message(Message shown in green) fade in just 5 seconds.
As discussed with @bmcutler and @emaicus success message for 5 seconds is good but for alert message it should be for time upto which they are not able to solve the error
It will remain till instructor(student) want to remove it.  
Videos:-
> [Bugfix] Stop fading of error messages

- site/app/templates/submission/homework/BulkUploadBox.twig
- site/public/js/drag-and-drop.js
Fixes #3849
`displaySubmissionMessage` now accepts a JSON response,
the alert message for success and fail are built more clearly now
Success messages will delete themselfs after 5 seconds, errors will stay on screen until deleted. (for bulk upload messages only)
> [Bugfix] Fix status messages for bulk uploads

- site/app/templates/grading/electronic/Status.twig
Closes #3688 
Now the  histograms should display properly!
> This *should* fix the null error for the total score histogram and autograding score histogram

- grading/load_config_json.cpp
The assert is evaluated such that it applies the `!` operator then does the `>` comparison which might give unintended consequence.
Fixes the assert to be clearer in what its testing, mainly that the "commands" array should be empty.
This should not be a breaking change and the previous behavior is maintained. An example of what's currently being evaluated can be seen [here](https://repl.it/repls/PurpleParallelPlane).
> [Refactor] Fix assert that commands array should be empty for server

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
Closes #3846 
Correct teams in section 1 and 4 (notice the highlighted student)
What displays for grader with access to rotating section 1 only:
Teams are no longer deconstructed when a grader is not assigned to grade their section.
See issue closed for more detailed explanation.
> Team Rotating Sections bug fix

- site/app/controllers/MiscController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/controllers/grading/ImagesController.php
- site/app/controllers/grading/SimpleGraderController.php
- site/app/controllers/student/SubmissionController.php
- site/app/controllers/student/TeamController.php
- site/app/views/course/CourseMaterialsView.php
There are some number of redirects to `$core->getConfig()->getSiteUrl()` which is set to `index.php?semester=<semester>&course=<course>` which is no longer a valid endpoint of the system.
Replaces the redirects to use `$core->buildNewCourseUrl()` instead which properly returns the endpoint of `/<semester>/<course>`.
Discovered by @emaicus when he went to the submission page for "Closed Team Homework" when not on a team.
> [Bugfix] Replace redirects to siteUrl() with buildNewCourseUrl()

- site/app/controllers/MiscController.php
- site/app/controllers/course/CourseMaterialsController.php
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/Output.php
- site/app/templates/course/CourseMaterials.twig
- site/app/views/course/CourseMaterialsView.php
- site/public/js/drag-and-drop.js
- site/public/js/server.js
Some course material related functions are scattered in MiscController and SubmissionController. This makes it hard to add routes to the course material part and make other controllers filled with too many functions.
- Gathers all functions concerned to CourseMaterialsController.
- Removes unused method (the deletion function in the original CourseMaterialsController) and unused variables.
- Modifies all links concerned.
Tested by manually going through all "actions".
`uploadResultMessage` is shared by `SubmissionController` and `CourseMaterialsController`, so I put it in `Output.php`. It looks like what we would like the API to be, but in the future, we will move to a more implicit way in `index.php` (or the main router).
> [Refactor] Gather Course Material Functions

- sbin/submitty_autograding_shipper.py
* Respects the enabled variable when installing the ```autograding_workers.json```  to other machines.
* Has an appropriate timeout when installing the ```autograding_workers.json``` to other machines.
> [Bugfix] Shipper Startup Updates

- .setup/travis/autograder.sh
Travis has been failing often with issues downloading from maven central. 
This replaces the links with ones using google storage.
> [Travis] Use google storage mirror for maven downloads

- site/app/models/Config.php
- site/app/views/NavigationView.php
- site/public/index.php
- site/tests/app/models/ConfigTester.php
Some links contain `index.php?` which are no longer used.
Removed `getHomepageUrl`.
When time is appropriate, we will remove `getSiteUrl` too.
> [Refactor] Remove homepage URL

- site/app/templates/submission/homework/BulkUploadBox.twig
Fixed error that caused the assignment submission to think students always had more than
1 submission and then attempt to handle a second submission even though it should have been first which prevented anyone from assigning students.
> [BugFix] Fix bulk upload assignment for first submission

- site/app/controllers/admin/ReportController.php
- site/public/index.php
Partially addresses #3711 
We can now POST to `/api/{_semester}/{_course}/reports/summaries` to generate rainbow grades.
The extra two lines is a workaround to make api work in pages that require course info.
Reason: I found that `core->loadUser` relies on `isCourseLoaded` to be true to load course users instead of submitty users. Therefore, if we do not load user before the authentication part (which is currently in `index.php` for backward compatibility and it may be in the router in the future), the user that we are to load is a submitty user without course access info.
So my plan is:
- After #3929 is merged, create API endpoint to get courses.
- Write a script that looks like this:
```
courses = post_with_jwt("/api/courses")
for course in courses: …
```
> [API] Endpoint for rainbow grade generation

- site/app/templates/admin/Configuration.twig
Fixes #3801 .
Previously any javascript content in course full name will run because of `|raw` 
Removing `|raw` will stop javascript running
> Remove |raw in course setting page

- site/app/views/NavigationView.php
- site/app/views/submission/HomeworkView.php
Changes assignment deadlines to use AM/PM for student facing assignments
This changes the dates on the buttons on the navigation page to use AM/PM
and also the submission page for gradeables.
Fixes #3313
> [UI] Switch to AM/PM on assignment deadlines

- sbin/shipper_utils/systemctl_wrapper.py
- sbin/shipper_utils/update_and_install_workers.py
When a machine has enabled=false, skip attempt to restart worker & rsync new Submitty code
> [Bugfix:Installation] skip worker installation when enabled=false

- site/public/js/server.js
Editing a team on the grading details index page shows the autofill behind the modal
modal no longer appears on top of autofill list
fixes #3686
> [Bugfix:InstructorUI] Fix autofill list showing behind modal on edit team form

- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
- site/app/controllers/student/SubmissionController.php
- site/app/templates/submission/homework/BulkUploadBox.twig
- site/app/views/submission/HomeworkView.php
- site/public/js/drag-and-drop.js
The bulkupload job in jobs.py corrects the file permissions of split paths after the entire job is done. If an instructor tries to submit or delete a split pdf before the permissions are corrected it'll throw an error. 
If a file processed 1 split pdf and an instructor submitted or deleted it right away, the controller would check if there were anymore pdfs since the job only processed 1 there would be none and Submitty would wrongly think this is the last pdf being assigned and delete the entire split folder which would cause the job to error and die. I removed this check for now but a better method to delete the split folder when everything is done is still needed.
Since the JSON file containing all the decoded information could be read before a job writes to it we need to check if the …
> [Bugfix] More bulk assign fixes

- site/composer.lock
This reverts commit 3bd63e4d2238b4d24e19cac136ad1a5021741f60.
PHPUnit 8.2.4 added a regression in that `$this->assertStringStartsWith` will fail if the prefix is just the string `"0"`, which was causing transient failures if the LoggerTests were run in the first 10 seconds of a minute due  to [this line](https://github.com/Submitty/Submitty/blob/d43bb2643b3681b3095aa114aa707425f86a4bce/site/tests/app/libraries/LoggerTester.php#L152).
Rollback to PHPUnit 8.2.3 which didn't have this change until a new version is released.
PR submitted to PHPUnit (https://github.com/sebastianbergmann/phpunit/pull/3747) to fix the bug.
> Revert "[Dependency] Bump phpunit/phpunit from 8.2.3 to 8.2.4 in /site (#3992)"

- site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig
Forces the date textareas to update in order to validate and save the dates entered by pressing the buttons on the flatpicker calender in the gradeable edit pages.
(Also changed the end of time value  to be 1998 I think comparing dates with the actual end of time was causing JS math issues and would always say fail to save)
> Fix 'now' and 'end of time' datepicker buttons from not saving on gradeable dates

- site/app/templates/GlobalHeader.twig
There are some places that return multiple errors and they are separated by `\n`. When rendering them in the front end, we should use `<br />` instead.
https://github.com/Submitty/Submitty/blob/d43bb2643b3681b3095aa114aa707425f86a4bce/site/app/controllers/student/SubmissionController.php#L500-L503
Newlines are displayed correctly.
Thank @xprilion for pointing this out.
> [Bugfix] nl2br for session messages

- .travis.yml
Python linting check is failing as @Fenn-CS reports in https://github.com/Submitty/Submitty/pull/4017#issuecomment-508965481 .
Temporarily force `pydocstyle==3.0.0` during `pip3 install`. This fixes the error.
Opened an issue at GitLab. Let's wait for https://gitlab.com/pycqa/flake8-docstrings/issues/36 being resolved.
> [Bugfix] Fix Travis CI Python lint error

- site/app/templates/autograding/AutoResults.twig
- site/app/templates/autograding/TAResults.twig
- site/app/views/AutoGradingView.php
Minor bugfix, the method to check if a gradeable was autograding only was broken previouslly 
as a result confetti would not display :(
Fixed logic : now autograding, ta grading, and total all can launch confetti if any are perfect or higher
Also fixed the bug where if a gradeable is autograding only the top level badge would display as "Autograding subtotal" instead of just "Total"
> Fix Badge title and confetti on Autograding only gradeables

- site/app/views/ErrorView.php
Closes #4020. The page was using a method that was removed in #3945 
Uses `getBaseUrl()` which returns the URL we want (due to the router work).
> [Bugfix:UI] Use getBaseUrl instead of getHomepageUrl

- site/app/controllers/admin/AdminGradeableController.php
Closes #2212
Currently the default ta-visible date when a gradeable is created is the day before (at midnight), so newly created gradeables are visible to TAs until the instructor modifies the dates.
Now the default ta-visible date is in the future (at midnight tonight), so it will not be visible while an instructor is creating the gradeable.
> Change default for new gradeable release to TAs

- .setup/CONFIGURE_SUBMITTY.py
- migration/migrator/migrations/system/20190708100715_add_worker_to_submitty_config.py
Closes #3671
1. Adds a boolean to ```submitty.json``` which specifies whether or not the machine is primary or a worker.
2. Adds a migration to add the boolean in existing installs. In new installs, the boolean is added by ```CONFIGURE_SUBMITTY.py```.
3. Fixes a bug which was making it impossible to install new worker machines.
> Add Worker Machine Boolean to Submitty Configuration JSON

- site/app/controllers/HomePageController.php
- site/app/controllers/NavigationController.php
- site/app/libraries/response/JsonResponse.php
- site/app/libraries/response/RedirectResponse.php
- site/app/libraries/response/Response.php
- site/app/libraries/routers/WebRouter.php
- site/app/templates/grading/electronic/Status.twig
- site/public/index.php
- site/tests/app/libraries/routers/WebRouterTester.php
To display error messages, sometimes WebRouter has to `die` immediately.
Now API returns nice error JSON messages as `Response`.
Also added:
- `RedirectResponse`
- CSRF Token Check
> [Refactor:Router] Remove usage of "die" in WebRouter

- site/app/templates/submission/Team.twig
- site/app/views/submission/TeamView.php
For some reason whenever I try and action with a team it throws me back to the course list page and gives an error saying invalid CSRF token.
Tried with send invite, cancel invite, and accept invite which are all html forms, I'm assuming the access controller is validating CSRF tokens in between or the router has changed somewhere and the expected tokens are not being sent with the requst.
This adds them to each form and seems to fix, @zjxiaohan  can you double check this isn't happening anywhere else, my guess is that this is caused by the changes the teamController using the new router. Let me know if theres a better fix for this if you have seen this issue before.
> Fix team actions causing 'invalid csrf token error'

- site/app/libraries/Core.php
If a new course with new group is added, but php-fpm is not restarted, 
the configuration file will be unaccessible.  Enhancing this error message 
will save time & frustration when this step is accidentally skipped.
> [Documentation:Installation] Enhance error message for new course group

- migration/migrator/data/submitty_db.sql
- migration/migrator/migrations/master/20190702161356_user_access_level.py
modified:   migration/migrator/data/submitty_db.sql
new file:   migration/migrator/migrations/master/20190702161356_user_access_level.py
New column users.user_access_level.  INTEGER, NOT NULL, DEFAULT 3.
New check constraint users.user_access_level_check (value is between 1 and 3).
EDITED:  first part of work for #3975
> [Feature] Master Database Update For User Access Level

- grading/dispatch.cpp
- more_autograding_examples/image_diff_mirror/config/config.json
- more_autograding_examples/image_diff_mirror/submissions/main.cpp
Closes #3438
1. Updates the image diff validation type so that it fails gracefully if images are of a different size. 
2. Updates the ```image diff mirror``` gradable in development to fix bugs and make it simpler.
> [Bugfix:Autograding] Image Diff Fails Gracefully on Different Sized Images

- site/app/controllers/admin/AdminGradeableController.php
- site/app/templates/admin/Configuration.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
- site/public/css/admin-gradeable.css
- Repository configs are now sorted alphabetically on the dropdown menu.
- There is now a warning if the current path is invalid (when a path is manually typed, or a file selected from the dropdown is renamed/moved).
- Multiple repositories can be entered in "course settings" separated by commas.  Warnings will be displayed if any are parsed incorrectly.  Repositories are labeled (123...) in the dropdown and in warnings.
- The way the repositories are parsed for config.json files was changed.  Now uses a breadth first search so that it does not check files in folders deeper than the config.json, and folders searched are counted instead of files encountered.
> [Feature:InstructorUI] Course autograding config repo changes

- site/app/libraries/database/DatabaseQueries.php
Query has a useless ALIAS attached to the form clause in it which was causing the syntax highlighting in the file to break for me when using VSCode + an extension (which I've also now stopped using) as I no longer need it. Bug had already been filed for it as well on this particular behavior.
Removes the pointless alias, no change in overall behavior.
Does not actually change anything about how the code works.
> [Refactor] Remove unnecessary alias from database query

- site/app/controllers/MiscController.php
- site/app/models/CourseMaterial.php
Closes #1921
Students could access course materials even if the materials had not yet been released, provided the student knew the URL to the resource.
Only instructors may view or download unreleased course materials.  Even if a student knows the url to a resource, they may no longer view or download it until it has been released.
Tested manually by uploaded files and attempting to view/download course material files logged in as a student in a separate browser.
> Prevent students from accessing course materials prior to release

- .setup/bin/setup_sample_courses.py
- .setup/data/users/instructor.yml
- .setup/data/users/superuser.yml
Implements superuser for Vagrant and updates needed setup code for user_access_level.  
Related to #3975 
- Update setup_sample_courses.py
- Added code for user_access_level column.  Default is 3.
- Fixed bug in user_group assert range check.
- user_group and user_access_level assert checks now give meaningful error messages.
- New user:  _superuser.yml_, user_access_level is 1, not enrolled in any courses.
- Update user: _instructor.yml_, user_access_level is 2.
> [Feature:Vagrant] Superuser for Vagrant

- more_autograding_examples/cpp_simple_lab/config/config.json
- more_autograding_examples/iclicker_upload/config/config.json
- more_autograding_examples/left_right_exam_seating/config/config.json
- more_autograding_examples/pdf_exam/config/config.json
- more_autograding_examples/test_notes_upload/config/config.json
- more_autograding_examples/test_notes_upload_3page/config/config.json
- more_autograding_examples/upload_only/config/config.json
Closes #4086. 
Some number of sample gradeables had html newlines (`<br>` or `<br/>`) which were no longer working as we've switched to markdown with no HTML allowed for the messages.
This updates the sample gradeables to use the appropriate markdown construct to get the newlines.
> [SampleData] Replace <br> in assignment messages with markdown newlines

- site/app/libraries/routers/WebRouter.php
- site/tests/app/libraries/routers/WebRouterTester.php
Currently, if we go to some POST only places using browser which sends GET requests, a `MethodNotAllowedException` will be thrown. Although it is very rare a case if users do not come up with URLs by themselves, it is better if we could handle it gracefully.
It is now  redirected to login/home page like the case where the route is not found.
> [Router] Let Router Catch MethodNotAllowedException

- sbin/send_email.py
An email error message with a single quote character was not correctly stored in the database.
> [Bugfix:Email] Handle error string with single quote

- site/app/templates/submission/homework/SubmitBox.twig
Closes #4095 
Clicking a multiple choice input label inside a notebook page would incorrectly select the first input in the fieldset instead of the corresponding input.
Clicking the label now correctly clicks the corresponding input.
Tested manually
> Notebook multiple choice selection fix

- site/app/controllers/MiscController.php
Relates to #1921 and #4071
Only instructor/admin level users may view unreleased files.  This had unintended consequences as now limited access graders were unable to view files they needed to grade, or see unreleased course materials.
Anyone with limited access grader or greater permissions may view submission files, and also view unreleased course materials.
Tested by logging into as 'grader', 'student', and 'instructor' inside vagrant VM to test which users could access which files.
> Fix file access for limited access graders and greater

- site/app/templates/forum/ShowCategories.twig
- site/app/views/forum/ForumThreadView.php
- site/public/js/forum.js
Fixes #4094. The manage categories page was attempting to call functions that were not defined on the page. Result of #3905.
Loads forum.js for this page, adding the necessary JS functions to the global scope. Fixes an additional bug in that it was impossible to re-order categories as the csrf_token wasn't being passed in the POST request.
I was able to:
1. Create a category
2. Reorder categories
3. Delete an empty category
4. See error message when attempting to delete in-use category (as expected)
> [Bugfix:Forum] Fix managing forum categories

- site/app/templates/grading/simple/Display.twig
* [ x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
fixes #864
currently, the boxes are just white with gray zeros before scores are changed/scored by a professor
unchanged boxes are a light blue, when the default score is changed the box changes to white to indicate that action has been taken (stays if the page is refreshed or reentered :))
tested by changing scores/refreshing on test and other professor scored gradeables
> [Feature:TAgrading] numeric/text boxes change color

- site/app/templates/Notifications.twig
- site/app/templates/forum/ForumBar.twig
- site/app/templates/forum/GeneratePostList.twig
- site/public/js/forum.js
- When post display options are clicked, ie. hierarchical, alphabetical, on reload the top most thread would be loaded because on an ajax call as changing the thread only the post list would change and the 'more' buttons would not be updated of the current thread.
- When a post display list item is clicked the changeDisplayOption function looks for a data element to get the current thread. 
A deleted thread/post notification should be 'deleted' by clicking the mark as seen check mark on the right hand side.
closes #3218
> [Bugfix:Forum] Minor forum bugs

- site/app/libraries/Output.php
Adds the the Twig DebugExtension if the debug environment is set to true, this will allow the dump function in twig files for development
> [Feature:Developer] twig debug extension on developer environments

- sbin/send_email.py
If the send_email script is slow or hangs for more than a minute, it is possible 
it is still running when the cron job kicks off the next instance.   We could end up 
sending duplicate copies of the same email, or worse.
At the start, the script checks to see if another send_email.py program is running 
and if so, exits immediately.
> [Bugfix:System] Check for duplicate copy of send_email.py script

- site/app/controllers/GlobalController.php
- site/app/controllers/NotificationController.php
- site/app/templates/NotificationSettings.twig
- site/app/templates/Notifications.twig
- site/app/views/NotificationView.php
- GET `/f19/sample/notifications` Notification Page
- GET `/f19/sample/notifications?show_all=true` All Notifications Page
- GET `/f19/sample/notifications/1` View Notification nid=1 and Mark as Seen
- GET `/f19/sample/notifications/1?seen=1` View Notification nid=1
- GET `/f19/sample/notifications/1/seen` Mark Notification nid=1 as seen
- GET `/f19/sample/notifications/seen` Mark All as Seen
- GET `/f19/sample/notifications/settings` Notification Settings Page
- POST `/f19/sample/notifications/settings` Notification Settings Update
Manually tested all the routes above, including view unseen notifications, view all notifications, mark all as seen, mark single one as seen, view single notification, see settings page and update settings.
> [Refactor:Router] New URL for NotificationController

- site/app/templates/course/SetFolderReleaseForm.twig
- site/public/js/drag-and-drop.js
Fixes #4069 .
Works as before. Pops up a dialog asking if you want to replace the file.
This bug exists because the `confirm` function in `SetFolderReleaseForm.twig` overrides the default JavaScript `confirm` function. Please confirm that my changes are correct @thef1stofhername .
> [Bugfix:InstructorUI] Allow uploading duplicate course material files

- site/app/libraries/routers/WebRouter.php
- site/public/js/server.js
Our current router relies on the ordering of GET parameters regardless of their names, which may be problematic.
For example, `http://192.168.56.111/f19/sample/course_materials/modify_timestamp?newdatatime=456&filenames=123` will let `app\controllers\course\CourseMaterialsController->modifyCourseMaterialsFileTimeStamp('456', '123')` be called although `123` should be the first parameter (`filenames`) by definition.
The router now takes parameter names into consideration.
I did a check for all existing routes and it looks ok, but we need to pay more attention to get parameters in the future in case there are naming inconsistencies between function parameters & GET parameters.
Not sure how to write unit test for this.
> [Refactor:Router] Forced ordering of arguments

- site/app/controllers/AdminController.php
- site/app/controllers/admin/AdminGradeableController.php
- site/app/controllers/admin/AutogradingConfigController.php
- site/app/controllers/admin/GradeableConfigController.php
- site/app/templates/admin/DeleteConfigPopup.twig
- site/app/templates/admin/RenameConfigPopup.twig
- site/app/templates/admin/UploadConfigForm.twig
- site/app/views/admin/GradeableView.php
**Old:** 
- `/index.php?semester=f19&course=sample&component=admin&page=gradeable&action=upload_config`
- `/index.php?semester=f19&course=sample&component=admin&page=gradeable&action=process_upload_config`
- `/index.php?semester=f19&course=sample&component=admin&page=gradeable&action=delete_config&config=something`
- `/index.php?semester=f19&course=sample&component=admin&page=gradeable&action=rename_config`
- `/index.php?semester=f19&course=sample&component=admin&page=gradeable&action=check_being_used?config=something`
**New:** 
- `/f19/sample/gradeable_config` GET
- `/f19/sample/gradeable_config/upload` POST ONLY
- `/f19/sample/gradeable_config/delete` POST ONLY
- `/f19/sample/gradeable_config/rename` POST ONLY
- `/f19/sample/gradeable_config/usage?config_path=somepath` GET
- Tried to …
> [Refactor:Router] New URL for GradeableController

- site/app/templates/admin/Configuration.twig
Fixed missing `<label>` error in configuration view.
> VPAT fix missing label error in configuration.twig

- site/app/controllers/student/GradeInquiryController.php
- site/app/controllers/student/RegradeController.php
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/response/JsonResponse.php
- site/app/templates/submission/regrade/Discussion.twig
- site/app/views/NavigationView.php
- site/app/views/submission/HomeworkView.php
- tests/e2e/test_login.py
SubmissionController is such a monster that I feel very stressful editing it.
Separate code regarding regrading from SubmissionController, and add some routes.
New URLs:
- `/{_semester}/{_course}/gradeable/{gradeable_id}/regrade/new` POST ONLY
- `/{_semester}/{_course}/gradeable/{gradeable_id}/regrade/post` POST ONLY
- `/{_semester}/{_course}/gradeable/{gradeable_id}/regrade/toggle_status` POST ONLY
Also changed the URL for a single gradeable from `/{_semester}/{_course}/student/{gradeable_id}` to `/{_semester}/{_course}/gradeable/{gradeable_id}`.
Manually tested:
- Opening a grade inquiry
- Close it and reopen it from instructor's side and from student's side
- Make posts as a student and as an instructor
> [Refactor:Controller&Router] Separate GradeInquiryController from SubmissionController

- site/app/views/grading/ElectronicGraderView.php
> [Bugfix] Removing warning on undefined individual_viewed_percent

- site/app/templates/admin/users/UserForm.twig
- site/app/views/admin/UsersView.php
- site/public/css/studentlist.css
- site/public/css/userform.css
Closes #4143 
Used to look like this
Now looks like this
The CSS was previously bound to studentlist, now it's modular so we can use it on both pages
> [Bugfix:InstructorUI] Moved edit user css to its own page

- site/app/controllers/admin/LateController.php
- site/app/views/admin/LateDayView.php
Fixes #4165 
`http://192.168.56.111/f19/sample/late_days` now displays correctly.
This bug is from an incorrect conflict resolve in https://github.com/Submitty/Submitty/pull/4114
> [Bugfix:InstructorUI] error on late days page

- .setup/bin/track_git_version.py
- site/app/libraries/Core.php
- site/app/models/Config.php
- site/app/templates/GlobalFooter.twig
- site/app/views/GlobalView.php
At installation, we store the latest git tag & short commit in config/version.json
Then this information can be displayed in the footer.  The commit hash is displayed when the user hovers over the tag.
We assume all tags are valid releases on the master branch of Submitty (this may not be true and then this will result in a broken link).
Note also that the commit may not match the tagged commit (there may be additional commits).  And further, it may not be a publicly available commit.
> [Feature:Installation] latest github release/tag & commit in footer

- site/tests/app/models/ConfigTester.php
ConfigTester.php is missing a version file causing all config tests to fail.
A version.json is created in ConfigTester.php
> [Bugfix:Tests] Created a version file in config tester

- site/app/controllers/admin/ReportController.php
Closes #1657
When clicking the generate grade summaries button a green popup will report that they were successfully generated in all cases (even if they failed).
A red error pop up will be displayed if grade summaries cannot be created.
Tested manually
> [Bugfix:RainbowGrades] ensure directory is writable

- site/app/controllers/admin/ReportController.php
- site/app/templates/admin/Report.twig
- site/app/views/admin/ReportView.php
Partially Addresses #1372
Instructors have no way of knowing the last time grade summaries were generated
A timestamp is now displayed below the generated grade summaries button.  When the button is clicked, it changes to 'Running...' to alert the user that a process is running server-side.
Tested manually
> [Feature:RainbowGrades] last timestamp for generate grade summaries

- site/app/controllers/NotificationController.php
- site/app/controllers/forum/ForumController.php
- site/app/controllers/student/GradeInquiryController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/models/Notification.php
We currently store URL parts in the notification metadata, which is not compatible with the new URL because we use the old way of assembling them.
Notification metadata store URL directly.
Tested manually by making announcements & posts.
It is a breaking change - all old notifications will be unavailable. I am not sure if we need a migration, or, gracefully handling this (the code may be a bit dirty as there are database queries).
@bmcutler once said (long time ago) it's okay just let students complain and they will forget. What do you think now?
> [Refactor:Notification] Let notification metadata store URLs

- site/app/libraries/Core.php
- site/app/libraries/database/DatabaseQueries.php
Partially addresses https://github.com/Submitty/Submitty/issues/4189.
Automatically refreshes `api_key` before generation token each time, thus invalidating previous tokens the user requested.
> [Refactor:API] One token for one user

- site/app/controllers/MiscController.php
- site/app/templates/submission/homework/CurrentVersionResults.twig
- site/public/js/server.js
Closes #4177
If an instructor goes to the submission page for a gradeable and clicks the button to download all files, then the 'results' directory is included.
When downloading the zip through submission page, only the submissions folder is included.  (Students and instructors now get the same zip file from this page)
Tested manually. I've ensured this PR doesn't make any changes to the functionality of the download zip button on the TA grading interface.
> Zip contents now vary based on the origin of the request

- site/app/controllers/GlobalController.php
- site/app/templates/GlobalHeader.twig
Makes it a little more clear so you don't accidentally log out if you're looking for the menu
New:
> [Feature:UITweak] Changed logout button to power button

- site/app/templates/grading/AdminTeamForm.twig
- site/app/templates/grading/electronic/Details.twig
- site/public/css/colors.css
- site/public/css/server.css
- site/public/js/server.js
Closes #4163
Users with no team don't show up at all on the details page, seems to be a new bug.
The dropdown menu appears behind the modal when edit team is clicked for a user with No Team.
The behavior when an invalid user_id is entered is inconvenient. 
- Fixed bug that stops users with no team from being displayed
- Added check for team history section of the modal in case no history data is available
- Made dropdown menu appear in the modal rather than behind for teamless users
- If an invalid user_id is entered, the background of the textbox will turn red and the submit button is disabled
- Previously if a textbox to add a new user is selected, pressing the enter key will click the "delete" button for a user on the team.  The enter key now submits the form instead (unless the submit …
> [Bugfix:InstructorUI] Edit teams modal improvement

- site/app/templates/Notifications.twig
- site/app/views/NotificationView.php
- site/public/css/notifications.css
- site/public/css/server.css
The notifications setting page will be addressed in a future PR after some unrelated changes are made to it.
- Revamped table caption to be h2 header
- Switched from table html to `display: table` css
- Buttons collapse on smaller screens
- Changed "mark as seen" icon to open envelope
- On mobile, time of notification shrinks and grays
- "Mark as seen" button now fits wider standardization of icon button palettes
Should look something like this:
> [Refactor:Mobile] Mobile for main notifications page

- site/app/templates/forum/StatPage.twig
Stats page links to threads are broken
The links are fixed.
Saw this in the meeting notes. It is a router bug :sweat_smile:
> [Bugfix] Fix broken forum stats URL

- site/app/templates/LateDaysTablePlugin.twig
- site/public/css/latedays.css
- site/public/css/table.css
Some global CSS rules had messed up the appearance of this page, so I fixed them and redid the desktop view. I also redid latedays.css to be mobile first in rendering (media queries only trigger desktop rules).
Old:
New:
> [Feature:UITweak] Redid desktop view of MyLateDays

- site/app/libraries/routers/WebRouter.php
Closes #4220 
The bug is fixed.
The function call isn't loading default values, which caused this error.
I am wondering what 'grade next student' would behave normally? It looks that it simply goes to the "details" page even I checked out an old revision. Should it go to the grading page though? @bmcutler
> [Bugfix: Router] Router GET param should load default values

- site/app/templates/submission/homework/BulkUploadBox.twig
- site/public/js/drag-and-drop.js
Fixes bulk uploads losing focus after a bit.
The error messages popping up were caused by duplicate requests being sent and when it would fail
it would try and re-enable the submission box that it thought failed. But because the submission had
actually succeeded, it would error and lose focus. 
Clears messages on page load 
Fixes #4185
> [Bugfix:BulkUploads] Bulk upload focus

- site/app/templates/forum/MergeThreadsForm.twig
Merge thread modal is sometimes not clear in why there are no threads available to be merged.
If there is no available threads for merging this yellow warning will appearing and the merge button will be disabled:
If there are available threads for merging:
closes #4145
> [UI/UX:Forum] Merge thread warnings and text

- site/app/controllers/student/GradeInquiryController.php
- site/app/controllers/student/SubmissionController.php
- If a team with a single member makes a submission and tries to send a notification to other team members an exception is thrown as there are no other team members
- If a student submits a grade inquiry and a limited access grader graded the assignment an exception is thrown as there is no recipients
- No notifications are sent on a one person team submission
- All full access graders are sent a notification about the grade inquiry event if there is no full access grader who verified the limited access grader's grading
> [Bugfix:Notifications] Fixed one person team submission and limited grader grader inquiry

- site/app/templates/NotificationSettings.twig
- site/app/views/NotificationView.php
- site/public/css/notifications.css
#4123
Added buttons for users to quickly select all/deselect all/reset to the default notifications
> [Feature:NotificationSettings]

- site/app/controllers/admin/LateController.php
The latedays extension page now expects and checks for y-m-d format
> [Bugfix:instructor ui] fix expected date format on latedays extension

- site/public/css/navigation.css
PRs #4239 and #4229 had a conflict where the buttons were laid out vertically, on the gradeables page. This should fix it.
> [BugFix: Student UI] Fixed error where gradeable buttons were vertical

- site/public/css/configuration.css
Certain browsers should no longer display rows at grossly large sizes Tested on:
Android:
Firefox 68
Chrome 75
Ubuntu:
Firefox 68.
Chrome 75
Mojave:
Safari 11
> [Bugfix:InstructorUI] Course Settings rows fixed on webkit browsers

- site/tests/app/libraries/routers/WebRouterTester.php
- site/tests/bootstrap.php
Previously we load annotations in `WebRouterTester.php`. In that case, when running `WebRouterTester.php` individually, it errors. That wastes time.
Load annotations in `bootstrap.php`.
I am actually not sure how that fails when run individually (the error message says test not found), but as I am working on `AccessControlTester` I find it wasting me too much time to always run the entire test suite, and modifying these code works.
> [Refactor:Tests] Load annotations in bootstrap.php

- Vagrantfile
Vagrant for Ubuntu 18.04 setups up private network on 192.168.56.111 and 192.168.56.112. The second URL was originally for what we used for Git, but that's since been folded into the first URL. All it does now is redirect to the first URL, so no need to have it.
Only create virtual network on 192.168.56.111 for Ubuntu 18.04. 192.168.56.112 will no longer work.
Not a breaking change, tested with vagrant halt/up.
> [Refactor:Vagrant] Remove unused private network IP

- site/app/templates/GlobalHeader.twig
- site/public/css/global.css
- site/public/css/menu.css
Closes #4262
Before:
- Breadcrumbs would scroll if they got too long
- If an external link was attached to the last breadcrumb, it wouldn't display properly on mobile
Now:
- Breadcrumbs wrap
- External links and the text are properly displayed
Expected behavior:
> [Bugfix:UI] Breadcrumb bar wrapping & link

- autograder/autograder/grade_item.py
Fixes an error which is currently breaking autograding in vagrant. After a recent PR, the ```submitty_daemon``` user was left without write permissions at validation time. As a result ```main_validator``` was unable to write ```grade.txt``` or ```results.json```. This change restores write permissions after execution of student code is completed.
> [Bugfix: Autograding] Fix Autograding Permissions

- site/app/libraries/Output.php
Gets the instance of Output (from inside the instance of Output) from the core to execute the function.
Just use the current Output instance that we're inside of
> [Refactor] Get rid of unnecessary call to core->getOutput in Output class

- .travis.yml
Travis had `pydocstyle==3.0.0` due to bug introduced shown in https://gitlab.com/pycqa/flake8-docstrings/issues/36.
Don't force `pydocstyle` to be `3.0.0` as the bug was fixed.
There was a conflict before but recently a new release has fixed the problem. See https://github.com/Submitty/Submitty/pull/4018.
This PR should be merged **after passing Travis CI**.
> [Testing:Travis] Remove version restrictions on pydocstyle

- site/app/views/forum/ForumThreadView.php
> [Bugfix:Forum] Fix empty forum warnings

- site/public/js/forum.js
Closes #4287 
forum.js was directly creating new forums on `Array.prototype` which was messing up usages of `for ... of ...` on Arrays in other parts of the JavaScript if they didn't guard against `ownProperty`, which I don't believe most places do in the code base do (nor should they).
Uses `Object.defineProperty` to add functions to the prototype so that they're not enumerable and will not show up normally in any `for ... of ...` loops elsewhere. An additional guard was placed around these to prevent duplicate definition as `forums.js` was imported twice in some places.
This is also a bugfix for the PDF Annotator where it was throwing an error as it used a `for ... of ...` syntax to iterate through an array and which was including these two functions (causing the annotator to not load).
> [Bugfix] Do not directly assign to Array.prototype

- site/public/js/admin-gradeable-updates.js
A recent change renamed a function called when building a course using the site, but did not update the function calls. This PR fixes this bug.
> [Bugfix] Fix Error When Building Course

- site/app/controllers/AuthenticationController.php
- site/app/libraries/Core.php
Partially addresses #4189
`POST /api/token/invalidate` with `user_id` and `password`.
If a success message is returned, you will (computationally) no longer have any valid token.
> [Feature:API] Add endpoint for token invalidation

- autograder/.coveragerc
- python_submitty_utils/.coveragerc
Signed-off-by: fenn-cs <fenn25.fn@gmail.com>
No `.coveragerc` files available in `autograder` folder and `python_submitty_utils` hence certain files may not be ignored during consideration for coverage reports.
Fixes: #4305 
`coveragerc` files for each folder.
> [Testing] added coveragerc file for autograder and python_submitty_utils test suites

- site/app/views/PDFView.php
adds missing csrf token when viewing pdfs
> [Bugfix:StudentUI] missing CSRF token on viewing PDFS

- site/app/templates/autograding/TAResults.twig
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
Could not open the PDF annotate tool in the grading interface as it would throw a JS error about the csrfToken variable already being defined.
Fixes not being able to open PDF annotate tool in the grader interface. The ability to open the PDF annotate tool on the submission page remains fixed from @shailpatels' earlier fixes.
This replicates behavior for how `csrfToken` is defined on non-popup pages in that doing `var csrfToken` in the code is equivalent to `window['csrfToken']`, and that setting `window['csrfToken']` implicitly sets `var csrfToken`.
> [Bugfix:PDFAnnotate] Fix setting csrfToken for embedded PDF annotate

- autograder/autograder/autograding_utils.py
This PR fixes a bug which caused random output to be improperly archived for networked gradeables.
> [Bugfix:Autograding] Random Output Archive Networked Gradeables

- site/app/controllers/admin/AdminGradeableController.php
- site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
- site/app/templates/grading/electronic/Status.twig
- site/public/css/server.css
If an instructor selects All Access Grading or Rotating Section on the edit gradeable page, a warning will appear if no students are in any non-null section. (Similar banner shows on the status page of gradeables under these conditions)
> [Feature:InstructorUI] rotating section warning on edit gradeable

- site/public/index.php
If an exception is thrown in `$core->loadMasterDatabase()`, `$core->loadAuthentication()` or `$core->getOutput()->loadTwig()`, the system would just output a generic exception screen with no information and not log the exceptions anywhere, making it hard for a sysadmin/developer to be able to take action to fix the problem. An example might be if they supplied the wrong DB credentials, or if they misconfigured the authentication behavior, etc.
Makes it so any exceptions from these functions are properly handled/logged as appropriate.
Tested it by adding a `throw new \Exception('test');` to top of `$core->loadMasterDatabase()` and observed the behavior before this patch and after this patch. Not a breaking change.
> [Bugfix] Set site exception and log handling immediately after loading config

- site/app/templates/grading/electronic/Details.twig
Closes #4308
Shows green check, red x, or mix of white/green checks (team assignments) for all students.
Does not show anything for students who have no submission or cancelled submission.
> [InstructorUI] Who viewed grade on no submission

- site/app/controllers/course/CourseMaterialsController.php
- site/app/templates/course/UploadCourseMaterialsForm.twig
- site/app/views/course/CourseMaterialsView.php
- site/public/js/drag-and-drop.js
Closes #4261 
Currently, you cannot set the release time of the newly uploaded course materials as you upload them. The delete function also doesn't remove data from the json, especially for single files and folders with many subdirectories. This is related to a bug where if you deleted something and reuploaded, the old date would still be there, which is problematic as if you had chosen to release it at a date in the near future, deleted, and reuploaded after that date, it would be instantly released. I just don't think an issue was made for that.
Now, there is an option to set the release time of course materials as you upload them, with the date/time set to the year 9999 by default. So with this and my other PR, no only will you have the tomorrow button option, you have the ability to …
> [Feature:Instructor UI] specify datetime on course material upload

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/bin/setup_sample_courses.py
`INSTALL_SUBMITTY_HELPER.sh` and `setup_sample_courses.py` still deal with `current_courses.php` which we removed in https://github.com/Submitty/Submitty/pull/3955
Removed those references.
> [Refactor:Installation] Remove current courses' index

- site/app/models/NotificationFactory.php
Fixes a bug which caused team assignment upload to throw an error when a notification was errantly sent to a user object rather than a user id.
> [Bugfix: Submission] Fix Error When Uploading Team Assignments

- site/app/libraries/routers/WebRouter.php
- site/tests/BaseUnitTest.php
- site/tests/app/libraries/routers/WebRouterTester.php
Closes https://github.com/Submitty/Submitty/issues/4189
Only faculty or superuser can access API endpoints. Students can still get a token, but they cannot go anywhere with it.
> [API] Restrict student access to API

- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/public/js/forum.js
"Old" browsers will throw an error when interacting with the forums and PDF annotator due to the use of the `catch {` idiom in JS, which is only available in newer browers (e.g. Firefox 58+).
Adds an error argument to all catches that did not have one to fix the regression for older browsers. Did not actually formally test as Firefox is totally broken on my machine due to macOS Catalina beta.
Fixes #4342
> [Bugfix] Do not use empty catch statements in JS

- site/app/templates/admin/Configuration.twig
- site/app/templates/admin/GradeOverride.twig
- site/app/templates/admin/Report.twig
- site/app/templates/admin/UploadWrapperForm.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
- site/app/templates/grading/UploadImagesForm.twig
- site/app/templates/submission/homework/SubmitBox.twig
- site/public/css/input.css
- site/public/css/server.css
Closes #4238 
The help icons disappeared
The help icons are back. I greped and found/fixed every instance
Can be tested by visiting each page rendered by the twig and looking for icons
> [Bugfix:InstructorUI] Help Icons are back

- .travis.yml
`pydocstyle` is specified in the Travis-CI configuration. This was necessary as it was broken after a new version of it was released that broke `flake8-docstrings`. We added the specific version in #4018 and then resolved in #4279.
Given that we're installing any version of pydocstyle, there's no need to specify it anymore as it's pulled in automatically as part of `flake8-docstrings`.
> [Testing:Travis] Remove pydocstyle dependency declaration

- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFInitToolbar.js
Fixes #3675.
Currently, whenever a PDF is opened for grading, the `site/public/js/pdf/*` scripts are all included, even if included previously. Some variables were declared at the top of the script with `let`, which caused a redeclaration error to be thrown.
Uses `var` for these variables which uses a concept of `hoisting` for the declarations so that they are in consequence only initialized once. This is probably not the ideal way of handling this, and can be refactored as part of a larger effort to also fix the various deprecation warnings on that page (#4345).
> [Bugfix:PDFAnnotator] Fix not being able to open a second PDF when grading

- site/app/controllers/HomePageController.php
- site/app/controllers/admin/ReportController.php
- site/app/controllers/admin/UsersController.php
- site/app/templates/ChangePasswordForm.twig
- site/app/templates/CreateCourseForm.twig
- site/app/templates/EditNameForm.twig
- site/app/views/HomePageView.php
- site/app/views/admin/ReportView.php
- site/public/js/rainbow-customization.js
- site/public/js/userform.js
- site/tests/app/libraries/routers/WebRouterTester.php
Closes #4160 
As Preston suggested:
`/home/change_password` -> `/current_user/change_password`
`/home/change_username` -> `/current_user/change_username`
For correct semantics.
`/home/courses/{user_id}` -> `/home/courses?user_id=whatever`
Change some params to query string so that there are no conflicts. (Didn't change `gradeable_version` or `nid` as discussed in #4160 because they are numbers - no conflicts)
`/{_semester}/{_course}/users/{user_id}` -> `/{_semester}/{_course}/users/details?user_id=whatever`
For correct categorization:
`/{_semester}/{_course}/rainbow_grades_customization` -> `/{_semester}/{_course}/reports/rainbow_grades_customization`
`/{_semester}/{_course}/auto_rg_status` -> `/{_semester}/{_course}/reports/rainbow_grades_status`
> [Refactor:Router] Minor URL changes

- site/app/templates/autograding/TAResults.twig
- site/app/templates/submission/regrade/Discussion.twig
Adds a scroll to posts when the open regrade inquiry button is clicked. Also hides the button. If there are posts when the page loads the button will not appear and the div will be present.
> Grade Inquiry UI Tweaks

- .setup/install_system.sh
Closes #3497. If someone is using `vagrant-proxyconf`, then doing `vagrant up` will fail when it attempts to build Docker as docker does not have access to the proxy settings.
Sets the docker configuration file under Vagrant to reflect the proxy settings per the Docker documentation (https://docs.docker.com/network/proxy/).
> [Bugfix:Vagrant] Set proxy for Docker during vagrant up under vagrant-proxyconf

- site/app/controllers/admin/UsersController.php
Fixes #4367 
It works as normal.
This bug is from #4225 . In the past we decide if a user is in a course or not by calling `loadUser` to load it from the **course db**. However, after #4225, the **master db** info is loaded too. That makes `loadUser($user_id) === null` fail to work when the user exists in the **master db** but not in **course db**.
The changes are made so that we don't check if user exists - frontend knows it and prevents regular instructors from doing so. If malicious instructors try to directly send a POST, it will fail when the user is inserted as `user_id` is a primary key.
> [Bugfix:InstructorUI] web GUI for adding existing student

- site/app/templates/grading/electronic/Status.twig
Going to status page for gradeable with no submissions or anything gives following JS error:
Checks the existence of the JS variable before attempting to click on it.
> [Bugfix:InstructorUI] Fix JS error when viewing empty status page

- site/public/css/menu.css
If the instructors adds custom sidebar links that are lengthy, they would overlap the page content...
Now they wrap:
> [Bugfix:Sidebar] wrap sidebar titles when lengthy

- site/app/libraries/Core.php
- site/app/models/NotificationFactory.php
NotificationFactory had the wrong namespace for where it was located.
Correct the namespace to match the other files under `app/models`.
> [Refactor] Set proper namespace for NotificationFactory

- site/app/libraries/Core.php
- site/app/models/Config.php
- site/app/models/gradeable/GradeableList.php
- site/tests/app/models/gradeable/GradeableListTester.php
For the test, we would mock almost everything except the GradeableList itself, causing some amount of slowdown per test.
Only mock the database layer while having concrete instantiations of everything else. Speeds up running the tests of this file by about 40-50 seconds.
> [Testing:Refactor] Remove mocks as possible from GradeableListTester

- site/app/controllers/student/SubmissionController.php
- site/tests/app/controllers/student/SubmissionControllerTester.php
Closes #4356
The SubmissionControllerTester currently uses the deprecated `run()` function on the controller which only exists for the tester itself.
Replaces all usages of the `run()` method with calling the specific controller method (similar to how the Router works) and removes the now completely obsolete run function.
> [Testing:Refactor] Refactor SubmissionControllerTester to not use run()

- site/app/controllers/student/SubmissionController.php
- site/app/libraries/Core.php
- site/app/models/gradeable/Gradeable.php
- site/tests/BaseUnitTest.php
- site/tests/app/controllers/student/SubmissionControllerTester.php
- site/tests/app/models/gradeable/GradeableListTester.php
- site/tests/utils/NullOutput.php
Similar to #4411 
The SubmissionControllerTester used a lot of mock objects which are expensive to create.
Remove mocks for actual concrete implementations as possible. Running the test suite decreased from 5.5 minutes to ~2.5 minutes.
> [Testing:Refactor] Remove much of the mocks from SubmissionControllerTester

- site/app/models/gradeable/GradeableList.php
- site/tests/app/models/gradeable/GradeableListTester.php
Fixes #4379 
Once a student makes a submission for a gradeable with no due date, the gradeable is moved to the "past due" category.
The gradeable for students, stays in the "open" category until the grades released date. Then it gets moved to the "grades available category"
To test, I created an autograding gradeable with no due date and made a submission as a student to observe the behavior. I then changed the grades released date as an instructor to see the gradeable move into the "grades available" category.
@KevinMackenzie I noticed [here](https://github.com/Submitty/Submitty/blob/4470a7f188a42ce0f5d4a3f31d6e6fe5dc399ceb/site/app/models/gradeable/GradeableList.php#L87) that there was a check for a student submission on gradeables with no due date. Was the original intention to create …
> [Bugfix:Navigation] Fixes gradeable category behavior for gradeables with no due date

- site/app/models/gradeable/GradedGradeable.php
- site/app/models/gradeable/LateDayInfo.php
- site/app/templates/LateDaysTablePlugin.twig
- site/app/views/LateDaysTableView.php
Late day table does not include information of grade inquiry history for the student
closes #2336 
Late day table now shows how many grade inquiries there are per gradeable pending or resolved
> [Feature: GradeInquiry] Added count of grade inquiries to lateday table

- site/app/templates/submission/homework/SubmitBox.twig
Closes #4391
Notebook short answer textareas would have an extra 16 white spaces in them.
Notebook short answer textareas now start off completely empty unless the instructor specifies an initial value.
Tested with Development->Paragraph Textboxes and also with the C++ crash course gradeable.
> [Bugfix:Submission] Notebook short answer whitespace

- site/app/templates/grading/electronic/PDFAnnotationBar.twig
Closes #4277 
The allowed minimum size of the pen in the UI was 1.
Can now set the minimum size of the pen to be 0.1.
Below shows the pen at 0.1, 0.5, 1, 1.5, 2, 2.5, and 3 width:
This patch is in conjunction with the [v2.1.0](https://github.com/Submitty/pdf-annotate.js/releases/tag/2.1.0) release of Submitty/pdf-annotate.js which added the capacity to have a pen with non-integer size to it. Prior to that release, the pen was always converted to an integer.
> [Feature:PDFAnnotator] Allow minimum size of pen to be 0.1

- site/tests/utils/NullOutput.php
Some typehints got added to `site/app/libraries/Output.php` for two functions that NullOutput did not have. Have updated `NullOutput` to have those type hints.
> [Testing:Bugfix] Add missing type hints for NullOutput

- site/app/controllers/course/CourseMaterialsController.php
When an instructor uploads materials using the upload form they are not initially written to the course_materials_file_data.json as a result if an instructor selects the date to 'now' they wont actually be released.
Seen in CV and networking today (not sure if open issue)
On upload write all files (including zips) to the json file with their upload dates
CourseMaterialsTester doesn't exist yet, I'll add tests for it in a separate PR
> [Bugfix:CourseMaterials] incomplete data in course_materials_file_data.json

- site/composer.json
- site/composer.lock
php-ds set not installed with composer install causing the test suit to fail locally
php-ds is installed on composer install
> [Dependency] Add php-ds as a composer requirement for if ext-ds not installed

- .travis.yml
- site/tests/app/libraries/response/RedirectResponseTester.php
- site/tests/app/libraries/response/ResponseTester.php
Travis uses xdebug for unit testing so as to be able to generate code coverage. This however slows things down a lot as xdebug has to be initialized and loaded and it's a rather heavy debugger.
Uses the [pcov](https://github.com/krakjoe/pcov) which is substantially faster (going from ~13-14 minutes to < 1min).
The redirect tests are weaked by this, but the performance gain is too much to worry about it.
> [Testing:Travis] Switch to pcov instead of xdebug for php code coverage

- site/tests/app/libraries/DateUtilsTester.php
`DateUtilsTester::testGetServerTime` was failing when the time was in early morning as we use format `G` which is 24 hour time without the leading zero. I misread the docs assuming it was `H`.
Fixes the regex to properly take account of the the `0-9` hours.
> [Testing:Bugfix] Fix error in regex in testGetServerTime

- site/app/templates/forum/ShowForumThreads.twig
- site/app/templates/forum/createThread.twig
I'm not really sure what the original intention of this line was as it looks to be attempting to use the `.submit(eventData, handler)` usage of jQuery, but then doesn't actually use it as `eventData`. However, this depends on the browser supporting the `window.event` which FF historically hasn't and if a flag is not set to true, still doesn't which will cause a ReferenceError to be thrown.
Get rid of the unused/undefined `event` variable in the `.submit()` function as jQuery already handles passing the event to the handler in all cases for all browsers and as it breaks FF as noted above.
To replicate on Firefox, go to `about:config` in the browser bar and set `dom.window.event.enabled` to be `false`. On submission of a forum post, you'll then see an error (`ReferenceError: event is not …
> [Bugfix:Forum] Remove undefined event variable from jQuery submit function call

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
Currently, PHP-FPM is only reloaded/restarted if using `./INSTALL_SUBMITTY.sh restart_web` or through `systemctl`/`service`. This makes changing certain things (like adding `DS\Set` (#4352)) require sysadmin action.
Always reload PHP-FPM before we remove the `index.html` placeholder. This is a graceful operation so should not affect any other PHP site running on a server and is done for Submitty while we're not serving any PHP files to people. Removes some potential amount of sysadmin action and inline with discussions surrounding the larger meta-issue of #4011.
> [Feature:Installation] Always reload PHP-FPM on site installation

- .setup/bin/update_repos.sh
- .setup/bin/versions.sh
This variable is unused as we switched to using `npm` to manage the pdf-annotator (and other JS dependencies) some time ago. Removing it so as to not be confusing.
@bmcutler I held off deleting the repo entirely in-case someone was actually using it, but I'm not sure anyone was and so is probably safe to delete if so desired.
> [Refactor:Installation] Remove unused PDFAnnotator version variable and do not grab its repo

- site/app/templates/admin/Configuration.twig
Fixes #4451. Would see an alert when attempting to toggle the checkbox for "Visible only to instructor?".
Can now toggle the checkbox for that setting without seeing the alert. The relevant setting in `/var/local/submitty/courses/<semester>/<course>/config/config.json` is updated properly.
> [Bugfix:InstructorUI] Fix being able to set visible only to instructors for seating chart

- grading/python/submitty_router.py
The router was leaving '_Actual' designations on the end the receiving side of messages when creating sequence diagrams. This caused sequence diagrams to be malformed. This PR removes the '_Actual' from sequence diagrams.
> [Bugfix:Autograding] Fix Sequence Diagrams with New Router

- site/app/templates/submission/homework/SubmitBox.twig
If a student had a previous student and an instructor wanted to make a submission for that student through the submissions interface Submitty would always create a new version  without asking the user what to do.
Displays the popup menu and handles previous submission options again
closes #4476
> [Bugfix : BulkUploads] Make submission for student handles previous submissions again

- site/app/views/submission/HomeworkView.php
If a student is granted an extension the late day banner will warn they will be charged a late day when in reality they won't
Now uses number of extensions to display to the student how many late days they'll be charged 
closes #4483
> [Bugfix:LateDays] Factor in number of extensions in showing lateday banner

- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
* [#] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [#] Tests for the changes have been added/updated (if possible)
* [#] Documentation has been updated/added if relevant
Server crashes when creating a new gradable and you set the template to a type and then revert back to none.  
The template feature has been removed from gradables.
The feature is stale and is not used by anyone right now so it has been commented out for starters.
I reloaded submitty virtually after the change was made and saw that nothing had been broken.
Closes  #4477
> [Bugfix:Gradeables] Removal of template feature from gradables

- site/public/js/ta-grading-rubric.js
Fixes #4368 
PDF page jump links used to not work when the PDF was zoomed. Now they do.
> [Bugfix:TAGrading] pdf autoscroll with zoom level != 100%

- grading/seccomp_functions.cpp
Fixes an error which caused seccomp to abort when using ```clang++``` to compile in containers using the ```submitty/clang``` image.
> [Bugfix:Autograding] Loosen Seccomp on C++ Compilation

- grading/execute.cpp
Programming Languages at RPI would like to the use the Oz and GHC stacks for evaluating assignments. While `ghc` itself was whitelisted, `cabal` and `stack` were not which are used for package installation and such for the `ghc`.
Whitelists programs from compiling and running `oz` assignments and whitelists `cabal` and `stack` for GHC, per their request.
> [Feature:AutoGrading] whitelist oz & haskell

- site/app/models/GradeableAutocheck.php
The autograding page's ```DiffViewer``` will only display an expected file if it resides in the ```test_output``` or ```random_output``` directories.
The ```DiffViewer``` is capable of displaying an expected file anywhere within the ```details``` directory.
> [Feature:Autograding] expected files not in standard locations

- grading/python/submitty_router.py
The network grading router was misconfiguring the endpoint of discovered udp connections, causing them to be errantly returned to sender. This PR fixes this issue.
> [Bugfix:Autograding] Router UDP Redirection

- tests/e2e/base_testcase.py
- tests/e2e/test_forum.py
Partial hack for #4511. Currently, tests may fail sporadically as the time it takes to process the completed jQuery.ajax call may extend time it takes for `wait_after_ajax` and some next line of code to complete.
Adds hack for getting the failing tests to pass more reliable, but should be replaced with a more concrete and permanent solution that will not fail on this race condition, regardless of AJAX response time.
> [Testing:Bugfix] Add brief wait after jQuery.active reports 0 for ajax

- site/public/js/drag-and-drop.js
Noticed while fixing #4530, that in some cases the AJAX call would fail, a message would alert saying to check JS console, but nothing would be printed.
Adds a print to the JS console for two JSON.parse cases that would explicitly tell users to look at the JS console in case of failure.
Not breaking, tested while fixing #4530.
> [Bugfix] drag-and-drop would not print JSON.parse error to console in some cases

- autograder/autograder/execution_environments/container_network.py
- autograder/autograder/execution_environments/rlimit_utils.py
Currently the default `RLIMIT_HEAP` is set to 1 GB.  This is problematic for instructors who wish to use larger custom images for their testcase since the docker container fails to startup if insufficient stack/heap memory is provided.
If instructors specify custom resource limits, defaults do not get populated. (Ex: Instructor only specifies `CPU`, default for `STACK` and `DATA` are not filled)
When an image is specified, the size of that image is taken into account to set `RLIMIT_DATA`. Currently it takes the size of the image and adds our default 1GB of heap that we provide to students. 
Default stack size is extended to 100MB, for some containers, having insufficient stack size may cause a failure in startup.
If an instructor specifies rlimits but excludes one of `CPU, STACK, DATA`, …
> [Bugfix:Autograding] Adjusts rlimit heap size to scale with container image

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/views/AutoGradingView.php
- site/app/views/LateDaysTableView.php
- site/tests/app/libraries/AccessTester.php
Empty file got re-introduced at some point
Removes the file, and all remaining references to it.
No, not breaking, file was empty and not used beyond for a handful of `use` lines which did not execute.
> [Refactor] Remove empty, unused, old Gradeable model

- site/app/libraries/Utils.php
- site/tests/app/libraries/UtilsTester.php
`Utils::getAutoFillData` did not have any tests to ensure its correct behavior.
Added four tests, testing combination of flags, as well as if there are duplicates in the data.
The behavior of the function changes slightly here in the case of duplicate users where if the duplicate user was in the null section, then it would end up with an entry in both full and null lists, and the returned JSON string would be an object instead of a list.
It now more consistently handles duplicate users and always returns a JSON list. However, if there are duplicate users but one has a registration section and the other does not, the user will show up twice, though this should never happen in practice.
Removes the unused/needed `Utils:: removeStudentWithId` function.
> [Testing] Add tests for Utils::getAutoFillData

- site/public/js/ta-grading-rubric.js
Fixes #4523 
Urls for students in the Mark Statistics box did not point at the right user_id (they all pointed at the user_id of the currently viewed student).
Urls now point at the appropriate student, as well as updating the JavaScript here to be a bit more "future-proof" if the URL structure or order of params changes in the future.
Tested by following the steps to reproduce in the issue, once to see the bug, and then after installing this patch to see if it was fixed. This is only place this function/code is used.
[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/keys), [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), and [array destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScrip …
> [Bugfix:TaGrading] Fix links to point at appropriate user_ids for Mark Statistics

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/views/AutoGradingView.php
- site/app/views/LateDaysTableView.php
- site/tests/app/libraries/AccessTester.php
Oh no! Something irrecoverable has happened...
Reverting this PR.  It 
When I go here:  (also for other gradeables)
http://192.168.56.111/f19/sample/gradeable/grading_homework/grading/status
I get this frog robot.
TypeError (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/PostgresqlDatabaseQueries.php (Line 1612) by:
public function getActiveVersions(Gradeable\Gradeable $gradeable, array $submitter_ids) {
Message:
Argument 1 passed to app\libraries\database\PostgresqlDatabaseQueries::getActiveVersions() must be an instance of app\libraries\database\Gradeable\Gradeable, instance of app\models\gradeable\Gradeable given, called in /usr/local/submitty/site/app/models/GradingOrder.php on line 100
Stack Trace:
#0 /usr/local/submitty/site/app/models/GradingOrder.php(100): …
> Revert "[Refactor] Remove empty, unused, old Gradeable model (#4532)"

- autograder/autograder/execution_environments/container_network.py
The socket used to process dispatcher actions was not being properly disposed of, leading to errors.
> [Bugfix:Autograding] Cleanup after Dispatcher Actions

- .setup/bin/setup_sample_courses.py
- site/app/controllers/student/SubmissionController.php
- site/app/views/grading/ImagesView.php
- tests/e2e/test_sidebar.py
Fixes #4542
Messed up fixing the file merge conflicts in a previous PR that was unrelated to student images.
Fixes viewing the student images page. I have modified `setup_sample_courses.py` to also extract one of the zips of fake student photos into the photos directory for the sample course.
To test that this page loads with images (and other pages load minimally), I've added three basic E2E tests that clicks each link in the sidebar as a student, TA, and instructor and checks that the header of the page matches an expected value.
> [Bugfix:StudentPhotos] Fix call to removed FileUtils function

- site/public/css/pdf/pdf_embedded.css
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFInitToolbar.js
- site/public/js/ta-grading-rubric.js
Closes #4528 
Previously zoom buttons on TA embedded PDFs would change by 100%, now it changes by 10% per click.
Attempted to fix a bug where zoom levels weren't working on all machines. I wasn't able to reproduce this on linux firefox, linux chrome, or windows firefox, but I slimmed some questionable code so hopefully it works now.
> Finer pdf zoom, fixed pdf autoscroll

- site/app/views/grading/ElectronicGraderView.php
closes #4527 
if grade inquiry per component is not enabled and a grade inquiry was made for a component spotlight still shows grade inquiry
fixes left over bug from #4534
>  [BugFix:GradeInquiry] fixed spotlight would turn red for component on non grade inquiry per component

- site/composer.json
- site/composer.lock
- site/tests/bootstrap.php
- site/tests/constants.php
- site/tests/ruleset.xml
Right now, we only test `site/app/authentication` and `site/app/exceptions` for style with the original thought of going directory at a time to clean up the other spots.
Cleaning up by directory is troublesome as there's a lot of errors with each directory, making such a cleanup not exactly super feasible, especially in balancing with other PRs and such. Additionally, for every PR merged in the meantime, it's that much potential work to fix things. Instead, I've moved the list to be the all rules that currently result in an error, with the expectation of cleaning up a rule at a time across the entire codebase. Many of these are automatically fixable by `phpcbf` which should help speed things along, though will be doing them one PR at a time to both make it easier to spot check the changes …
> [Testing:Style] Move PHPCS from testing certain files to testing certain rules

- site/app/templates/course/UploadCourseMaterialsForm.twig
- site/app/templates/forum/ThreadPostForm.twig
- site/app/templates/grading/UploadImagesForm.twig
- site/app/templates/submission/homework/SubmitBox.twig
- site/public/js/drag-and-drop.js
Id for drag & drop file submission changed to meet our standard of using a hyphen instead of 
an underscore, updated all instances and matching JS code.
Also fixes course material bug where the id was changed but not the JS preventing course materials
Effects all drag& drop file submission parts
tested forum, course materials, student images, hw submission
fixes #4565
> [Bufix:Submission] Renamed instances of input_file to input-file  

- site/app/templates/grading/VersionChoice.twig
- tests/e2e/test_submission.py
E2E tests for the version of submissions (changing version and cancelling version) were commented out due to Travis failing in a non-obvious way.
Rewrites the test to use a more portable method (`selenium.webdriver.support.ui.Select`) that resolves the issues having with xpath and the `ActionChain`
> [Testing:Bugfix] Fix failing submission version select e2e tests

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
Continued work for #4553 
This file had the following issues:
```
------ ------------------------------------------------------------------------------------------------------------
Line   libraries/database/DatabaseQueries.php
------ ------------------------------------------------------------------------------------------------------------
1652   Parameter $gradeable of method app\libraries\database\DatabaseQueries::getSubmittersWhoGotMarkBySection()
has invalid typehint type app\models\Gradeable.
1700   Parameter $mark of method app\libraries\database\DatabaseQueries::insertGradeableComponentMarkData() has
invalid typehint type app\models\GradeableComponentMark.
1707   Parameter $component of method app\libraries\database\DatabaseQueries::createNewGradeableComponent() has
invalid …
```
> [Refactor] Fix static analysis errors in DatabaseQueries

- tests/e2e/base_testcase.py
- tests/e2e/test_forum.py
Fixes #4511
Added the method `waif_for_element()` which explicitly waits for an element to be present/visible in the DOM (a good indicator besides waiting for spinners/loaders). Using this method right after `wait_for_ajax` may help to determine a completed ajax request/response.
Also, since the method is written to be used generically, and since there are some test steps which explicitly wait for the presence of elements, this method can be used instead to keep the code DRY.
Tested by running the `test_forum_merge_thread` scenario, and the `test_forum` suite locally, at least 5 times.
> [Testing] Add generic method that waits for element to be present/visible

- site/app/controllers/MiscController.php
- site/app/controllers/course/CourseMaterialsController.php
- site/app/controllers/grading/ImagesController.php
- site/app/controllers/student/SubmissionController.php
- site/tests/BaseUnitTest.php
- site/tests/app/controllers/MiscControllerTester.php
- site/tests/app/controllers/course/CourseMaterialsControllerTester.php
- site/tests/app/controllers/student/SubmissionControllerTester.php
We used `Core::isTesting()` function to avoid dealing with some PHP builtin functions.
Replaced the usage of that shim function with the usage of php-mock and mocked the builtins instead, allowing for a bit cleaner code. `Core::redirect()` still relies on it (as it calls `die()`) and php-mock throws an error when attempting to mock `die`, so that remains (for now). Removes the usage of `isTesting` from a handful of production code spots.
This is purely a testing refactor. For the changes to production, the `isTesting()` function already always returned false, and so removing it has no effect on how it functioned.
> [Testing:Refactor] Remove Core::isTesting shim and use php-mock instead

- site/app/views/submission/HomeworkView.php
Continues work for #4553
Fixes the following phpstan error:
```
------ -------------------------------------------------------------------------------------------------------
Line   views/submission/HomeworkView.php
------ -------------------------------------------------------------------------------------------------------
98     Method app\views\submission\HomeworkView::renderTAResultsBox() invoked with 3 parameters, 2 required.
------ -------------------------------------------------------------------------------------------------------
```
The change was introduced in #4133 where it looks like the intermediary commit 3fc6cc652dafc1e71dd1b87bfaf90b1722269efd added it, and then 2616eb747c99f565a87baa76ec824a2ce7616734 removed that change to the function, but did not update the caller. …
> [Refactor:PHPStan] Remove extra passed parameters from HomeworkView:renderTAResultsBox call

- site/app/models/RainbowCustomization.php
- site/app/models/RainbowCustomizationJSON.php
Continues work for #4553 
These files had the following errors:
```
------ --------------------------------------------------------------------------------------
Line   models/RainbowCustomization.php
------ --------------------------------------------------------------------------------------
46     app\models\RainbowCustomization::__construct() does not call parent constructor from
app\models\AbstractModel.
------ --------------------------------------------------------------------------------------
------ ------------------------------------------------------------------------------------------
Line   models/RainbowCustomizationJSON.php
------ ------------------------------------------------------------------------------------------
42 …
```
> [Refactor:PHPStan] Fix not calling parent::__construct() for RainbowGrades models

- site/public/css/global.css
When on screens with a width of over 541px (when on a computer/laptop) the top half of the footer would be covered by the "wrapper" div above it. This means the user could not click on the top half of the button/links in the footer. 
Note how the "wrapper" div covers up part of the footer and so you cannot click on the footer buttons where it overlaps.
You can now click on any part of the footer
I could not find a reason why this css was there in the first place so I just removed it but there may be a reason I did not see.
> [Bugfix] Could not click upper half of items in footer

- site/app/templates/grading/electronic/SubmissionPanel.twig
Closes #4560
Now you can scroll in the Submissions and Results Browser in TA grading UI.
> [Bugfix:GradingUI] Fix submissions and results browser not scrolling

- site/app/models/gradeable/AutoGradedVersion.php
Fixes #4571 
The drop-zone for multi-part assignments would only populate with the first file of previous submissions.
All previous files should now populate the drop-zone.
> [Bugfix] Fix only adding one previous file

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
- .travis.yml
- site/composer.json
- site/composer.lock
- site/phpstan.neon
- site/tests/phpstan/ModelClassExtension.php
- site/tests/phpstan/ModelClassExtensionTester.php
- site/tests/phpunit.xml
Closes #4553 
We currently do not use phpstan in our CI pipeline.
Adds phpstan to the composer.json file and activates it in Travis as part of our regular continuous integration testing.
> [Testing] add phpstan to travis lint stage

- autograder/autograder/execution_environments/container_network.py
If there were multiple containers, pre-commands were not properly copying files into the requested directories.
A longer discussion should be had about how to exclude specific containers when performing pre-commands.
> [Bugfix:Autograding] Multi-Container Pre-Commands

- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/ta-grading.js
Could not open PDFs (or any file) in the inline "File Viewer" in the TA Grading interface.
Fixes the bug, allowing PDFs (and other files) to be inlined, while also not breaking being able to scroll the browser/results window. The file viewer is draggable anywhere except for within the open file display itself and for the expanded options menu for the PDF (that has the pen size and text size), can discuss if that's alright, but I think this probably covers things well enough for now.
There remains a bug that when the pen is selected, you cannot drag the box, and various elements of the UI will not properly work until the pen is deselected, but that is separate issue from this, and was pre-existing (and has been) for some time.
1. open all folders and check I could scroll (I could)
1. Open …
> [Bugfix:TAGrading] fix not being able to open PDFs

- site/app/controllers/admin/UsersController.php
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/database/PostgresqlDatabase.php
- site/app/models/GradingOrder.php
- site/tests/app/libraries/routers/AccessControlTester.php
- site/tests/ruleset.xml
Re-adds the `Generic.WhiteSpace.IncrementDecrementSpacing` sniff rules, disallowing `++ $i` or `$i ++`. All violations of it are fixed, along with some other violations still ignored in the immediately surrounding code.
> [Refactor:PHP] Fix Generic.WhiteSpace.IncrementDecrementSpacing style errors

- site/public/index.php
The current API endpoints do not support `application/json` content-type, which is the standard for using APIs with clients. Currently, if a request is sent using `application/json`, the `$_POST` global will be empty.
If using the `/api` endpoint and the `content-type` header is set to `application/json`, then we read in off `php://input` to set the `$_POST` global, which is the only way to get access to it. Does not affect regular usage of the site.
> [Feature] Add support for application/json requests

- site/app/controllers/HomePageController.php
- site/app/controllers/NotificationController.php
- site/app/controllers/admin/EmailRoomSeatingController.php
- site/app/controllers/admin/PlagiarismController.php
- site/app/controllers/forum/ForumController.php
- site/app/controllers/forum/ForumController2.php
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/User.php
- site/app/models/gradeable/Gradeable.php
- site/app/views/MiscView.php
- site/app/views/NavigationView.php
- site/app/views/forum/ForumThreadView.php
- site/tests/app/controllers/student/TeamControllerTester.php
- site/tests/ruleset.xml
Fixes the following two rule violations:
* Generic.WhiteSpace.DisallowTabIndent.TabsUsed
* Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed
Converts any used tabs into spaces. Enforces rules through Travis and PHPCS.
> [Refactor:PHP] Fix Generic.WhiteSpace.DisallowTabIndent style errors

- site/public/js/ta-grading.js
Cannot click to enter text or change the number for custom mark
Allows you to deal with custom marks, without breaking the prior series of fixes on the UI.
Tested same series of functionality as #4597, with the addition of:
1. adding custom mark
1. saving component
1. opening component and removing custom mark
1. saving
1. clicking "Edit Rubric" and adding new marks
1. click on new marks
1. saving
1. changing submission version
1. cancelling submission
> [Bugfix:TAGradingUI] Fix not being able to click on custom marks

- site/app/views/forum/ForumThreadView.php
- site/tests/app/exceptions/testException.php
- site/tests/ruleset.xml
Codebase allowed for the following two violations:
* Generic.NamingConventions.ConstructorName.OldStyle (prefer `__construct` over `className`)
* Generic.PHP.ForbiddenFunctions.FoundWithAlternative (prefer to not use function alias' like count instead of sizeof)
Errors are fixed, and rules committed to prevent them happening again.
> [Refactor:PHP] Fix using old constructor and alternative function style errors

- site/app/controllers/MiscController.php
- site/app/views/AutoGradingView.php
PDF pages that get converted to images are shown to students
Restrict students to only see the split pdf instead of a list of images
images no longer shown,
download file function uploaded
download submission zip updated
> [Bugfix:Bulkuploads] Prevent scanned images from being shown to students

- site/app/libraries/database/PostgresqlDatabaseQueries.php
When there is no grade inquiries that are tied to a component the Manually Graded Component Averages tab does not shows.
Manually Graded Component Averages tab now shows.
> [BugFix:GradeInquiry] Manually Graded Component Averages tab now show

- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
Fixes #4431 
When a poster creates a new post/thread, the new thread in the thread list or the new post will be highlighted as if the poster did not read their own post/thread.
The poster will not see their new post/thread highlighted but others will still be able to.
Tested by creating new posts/threads and viewing them between different users.
> [Bugfix:Forum] Fixed unread highlight seen by poster for new post/thread.

- site/app/templates/forum/CreatePost.twig
- site/app/views/forum/ForumThreadView.php
Currently uses a for loop in the twig template to print out the classes. Requires classes to have spaces in their name to prevent any issues.
Uses the [twig join filter](https://twig.symfony.com/doc/2.x/filters/join.html) which is cleaner and less possibility of any issues with spacing in class names.
> [Refactor:Forum] Use join twig filter for post classes array

- site/app/controllers/student/TeamController.php
- site/app/templates/Notifications.twig
The URL that gets created for team invite notification points to the team gradeable, however you can only see team gradeables if you are on a team and the only users who can get team invites are users not on teams. 
The URL now points to the manage team page where the invited user can accept/reject invitations
fixes #4648
> [Bugfix:Notifications] Fix broken team invitation URL notification

- site/app/controllers/grading/SimpleGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
Fixes #4454 
If a student had an empty string set for their preferred first or last name, then the ordering for that name would be broken with that student always at the top.
Students are now appropriately sorted if they have a null or empty string set for the preferred name (as the empty string is set to null for purposes of our ordering). This also fixes a bug in the code where any order by clause with more than two words separated by spaces would cause an error and have everything after the second space truncated.
Set a student's preferred first and last name to an empty string, observe the broken ordering on simple grading page. Applied fix, ordering was fixed.
Due to #4620, have to go through the DB to do this, running `UPDATE users SET …
> [Bugfix:TAGrading] Fix broken ordering of first/last name for grading

- site/app/controllers/student/SubmissionController.php
- site/app/templates/submission/homework/SubmitBox.twig
- site/app/views/submission/HomeworkView.php
- site/public/js/drag-and-drop.js
Inproper checking of uploaded files would lead to incorrect/vague error messages and
Files sizes larger than the POST or max_filesize_limit would causes a crash and get no response giving a vague error message.
Better error handling for file uploads by using `validateUploadedFiles` on the server side for large/incorrect file types. 
The client now checks for this and gives a correct message before it attempts to upload.
> [BugFix:BulkUpload] Fixed error handling for large files on Bulk Upload

- site/tests/app/controllers/course/CourseMaterialsControllerTester.php
Course materials tester does not have any tests for when an instructor wants to specify 
and additional path on top of the course materials uploads path.
Adds a small test to upload a file to a requested path
I tried adding the @runinseperate process annotation but got an error from PHPUnit saying cannot serialize closure? So I left it out for now
> [Testing:CourseMaterials] Adds a test for uploading with a requested path

- sbin/submitty_daemon_jobs/submitty_jobs/bulk_qr_split.py
The previous method of increasing contrast missed a couple of QRs causing them to be stitched together.  
Replaced method with one better suited specifically for black and white exams during the preprocessing step.
ReSubmitty all sample pdfs in more autograding examples
> [Feature:BulkUploads] Better contrasting method for QR bulk upload

- site/app/templates/autograding/AutoResults.twig
- site/app/templates/submission/homework/CurrentVersionResults.twig
- site/public/js/confetti.js
The previous method of checking if the submission box could be parsed or not in `confetti.js` wasn't correct and would think the box was always there. Notebook gradeables do not show this info and confetti.js would crash trying to parse it.  
Fixed parsing and hides the submission box for notebook gradeables.
closes #4464
> [Bugfix:Confetti] Fix Confetti for notebook gradeables & 1 Test case only

- site/app/controllers/MiscController.php
- site/app/controllers/admin/PlagiarismController.php
- site/app/controllers/admin/ReportController.php
- site/app/controllers/forum/ForumController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/models/GradingOrder.php
- site/app/models/OfficeHoursQueueStudent.php
- site/app/models/RainbowCustomizationJSON.php
- site/app/models/gradeable/AutogradingConfig.php
- site/app/views/grading/ElectronicGraderView.php
- site/tests/app/controllers/student/SubmissionControllerTester.php
- site/tests/ruleset.xml
Fixes all instances of the `Squiz.Operators.ValidLogicalOperators` style errors. This sniff prevents the usage of the `and` and `or` logical comparators, mandating only usage of `&&` and `||`. The two are not equivalent, and have different operator precedence, which can introduce subtle bugs from surprising behavior, hence most people (including us going forward) forbid usage of the former and only allow the latter.
A demonstrative case of why the former are bad:
```php
$a = true and false;
var_dump($a); // true
$a = true && false;
var_dump($a); // false
```
this is because the `and` operator has a lower precedence than the `=` operator, which I'm not sure anyone really expects or wants.
> [Refactor:PHP] Fix Squiz.Operators.ValidLogicalOperators style errors

- site/app/controllers/MiscController.php
* [ x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ x] Tests for the changes have been added/updated (if possible)
* [ x] Documentation has been updated/added if relevant
The "download zip file" button, when grading, downloads a zip file but it is completely empty
The zip file now actually has all the student's files in it
> [Bugfix:TAGrading] download zip of files for one student

- site/app/controllers/MiscController.php
- site/app/views/PDFView.php
closes #4516
When grading exams if a pdf is open on the page, you cannot reorder the rubric marks.
You can now reorder the rubric marks even if a pdf is open.
The reason for this issue was that when we load in the pdf, it loads in jquery however jquery was already on the page before that. Having 2 jquerys breaks jquery-ui which causes the rubric marks to no longer work.
I left the file in a comment because I am worried it was added for some real reason such as a page does not have jquery and this is the only spot that it is loaded in for that page. However I can just remove it if that is better.
> [Bugfix:TAGrading] rearrange marks when viewing a pdf file

- grading/load_config_json.cpp
At present, if ```use_router``` is set to ```true```, a router is pulled in even for single container testcases (e.g. a ```FileCheck``` or ```Compilation``` testcase). This PR stops a router from being added for such testcases at assignment build time, and further disallows manually pulling in a router for testcases which involve only a single container.
> [Bugfix:Autograding] Don't Pull in a Router for Single Container Testcases

- autograder/autograder/execution_environments/container_network.py
When running student code using a docker container, meta-output from ```main_runner.cpp``` was not being logged in ```runner_log.txt```. This PR fixes that problem, and also makes certain that, when running a networked gradeable, output from different containers is not interleaved within the ```runner_log.txt``` file (i.e. each container's output is logged to the file in a single, cohesive chunk).
> [Bugfix:Autograding] Add Output to Runner Log

- site/app/controllers/grading/ElectronicGraderController.php
closes #4557
There is a crash when going to  http://192.168.56.111/f19/sample/gradeable/open_homework/grading/grade
See #4557 for more details
The page will now redirect to http://192.168.56.111/f19/sample/gradeable/open_homework/grading/details instead
When you click on the normal grading index button the url you go to ends with `?view=all`, however currently the redirect is set up to go to http://192.168.56.111/f19/sample/gradeable/open_homework/grading/details and leave out `?view=all`
Is this difference intentional? Otherwise I can fix it by changing /home/eli/documents/Submitty/site/app/controllers/grading/ElectronicGraderController.php line 855 to `$this->core->redirect($this->core->buildCourseUrl(['gradeable', $gradeable_id, 'grading', 'details'])."?view=all");`
> [Bugfix: Grading] fixed crash when going to .../grading/grade without any parameters

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
This reverts commit 7b1fa6777ef5ea8ca5f44095a3e4ab6ff0eb6e09.
As it caused the error below when we attempt to edit an existing gradeable:
===========
app\exceptions\NotImplementedException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php (Line 1385) by:
throw new NotImplementedException();
Message:
This is not implemented yet.
Stack Trace:
#0 /usr/local/submitty/site/app/controllers/admin/AdminGradeableController.php(108): app\libraries\database\DatabaseQueries->getGradeablesRotatingGraderHistory('foo')
#1 /usr/local/submitty/site/app/controllers/admin/AdminGradeableController.php(29): app\controllers\admin\AdminGradeableController->editPage(app\models\gradeable\Gradeable, 'f19', 'blank', 0)
#2 unknown file(unknown line): …
> Revert "[Bugfix:TAGrading] team grading statistics (#4672)"

- site/app/controllers/forum/ForumController.php
- site/app/libraries/GradeableType.php
- site/app/libraries/database/ForumQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/libraries/routers/AnnotatedRouteLoader.php
- site/app/models/CourseMaterial.php
- site/app/models/RainbowCustomization.php
- site/app/models/RainbowCustomizationJSON.php
- site/tests/app/exceptions/ConfigExceptionTester.php
- site/tests/ruleset.xml
- site/tests/utils/NullOutput.php
Fixes the `Generic.Classes.OpeningBraceSameLine` style errors, which is that the class line is the only thing on it, and that it ends with a ` {`.
> [Refactor:PHP] Fix Generic.Classes.OpeningBraceSameLine style errors

- site/app/libraries/Utils.php
- site/tests/ruleset.xml
Fixes `PSR2.ControlStructures.SwitchDeclaration` style errors, which is that `case` must be on its own line, the next line must be indented (unless it's another `case` statement), and block should have a `break` or `return` to end it.
> [Refactor:PHP] Fix PSR2.ControlStructures.SwitchDeclaration style errors

- site/app/controllers/student/TeamController.php
When a new team member joins a team, the existing members get notified of this,
like before the url being constructed was broken and would bounce people to the
course list page 
Correct URL is being used, this should be the last URL from the 
team controller sending the wrong link.
> [Bugfix:Notifications] Fix new team member notification link

- site/app/views/GlobalView.php
- site/app/views/HomePageView.php
- site/app/views/admin/PlagiarismView.php
- site/tests/ruleset.xml
Fixes the `PEAR.Functions.ValidDefaultValue` style errors, which is that any functions with default values must have the default values at the end of the definition. The functions that violated this behavior never relied on the default arguments.
> [Refactor:PHP] Fix PEAR.Functions.ValidDefaultValue style errors

- site/app/libraries/response/Response.php
- site/app/libraries/routers/WebRouter.php
- site/app/models/User.php
- site/tests/ruleset.xml
Fixes the `PSR2.Methods.MethodDeclaration.StaticBeforeVisibility` style errors. Means that all function definitions must have visibility before the `static` keyword.
> [Refactor:PHP] Fix PSR2.Methods.MethodDeclaration.StaticBeforeVisibility style errors

- site/app/controllers/GlobalController.php
- site/app/controllers/OfficeHoursQueueController.php
- site/app/controllers/admin/EmailRoomSeatingController.php
- site/app/controllers/admin/PlagiarismController.php
- site/app/controllers/admin/WrapperController.php
- site/app/controllers/forum/ForumController2.php
- site/app/controllers/student/LateDaysTableController.php
- site/app/controllers/student/SubmissionController.php
- site/app/libraries/ForumUtils.php
- site/app/libraries/Utils.php
- site/app/libraries/database/ForumQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/libraries/database/SqliteDatabase.php
- site/app/libraries/routers/AccessControl.php
- site/app/libraries/routers/AnnotatedRouteLoader.php
- site/app/models/AbstractModel.php
- site/app/models/Breadcrumb.php
- site/app/models/Button.php
- site/app/models/Course.php
- site/app/models/Email.php
- site/app/models/SimpleGradeOverriddenUser.php
- site/app/models/forum/Forum.php
- site/app/models/forum/Post.php
- site/app/models/forum/Thread.php
- site/app/views/forum/ForumThreadView.php
- site/tests/app/controllers/course/CourseMaterialsControllerTester.php
- site/tests/app/controllers/student/SubmissionControllerTester.php
- site/tests/app/libraries/LoggerTester.php
- site/tests/ruleset.xml
Fixes the `PSR2.Classes` and `PSR12.Classes` style errors, which is that the closing brace for a class must come immediately after the last line of the body (no empty lines between them), class properties should have visibility before `static` keyword, and that all class instantiations must have the `()`, even if there are no arguments to the constructor.
> [Refactor:PHP] Fix PSR(?:12|2).Classes style errors

- .travis.yml
The codebase was using flake8-docstrings to enforce that docstrings were getting written for functions.
flake8-docstrings is no longer used for enforcing any sort of existence of docstrings for python code. Developers would either just add the file to be ignored, or just find the easiest solution to fix why it would complain, without really bothering to learn what it was checking for, nor giving meaningful docstring comments.
> [Testing:Python] Drop usage of flake8-docstrings

- site/app/controllers/admin/UsersController.php
- site/app/controllers/forum/ForumController.php
- site/app/controllers/forum/ForumController2.php
- site/tests/ruleset.xml
Fixes the remaining `Squiz.ControlStructures` style errors, which was for `for` and `foreach` loops, namely for us that there should be a single space between the arguments of the `for` loop.
> [Refactor:PHP] Fix Squiz.ControlStructures style errors

- site/app/libraries/DiffViewer.php
- site/tests/app/libraries/database/SqliteDatabaseTester.php
- site/tests/ruleset.xml
Fixes `Squiz.Scope.MethodScope.Missing` style errors, which is that all methods must have the visibility for it defined (instead of just relying on the default public).
> [Refactor:PHP] Fix Squiz.Scope.MethodScope.Missing style errors

- site/app/controllers/admin/PlagiarismController.php
- site/app/controllers/admin/ReportController.php
- site/app/controllers/admin/UsersController.php
- site/app/controllers/forum/ForumController.php
- site/app/controllers/forum/ForumController2.php
- site/app/libraries/Access.php
- site/app/libraries/DiffViewer.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/models/GradingSection.php
- site/app/models/RainbowCustomization.php
- site/app/models/RainbowCustomizationJSON.php
- site/app/models/forum/Post.php
- site/app/models/gradeable/Gradeable.php
- site/app/views/forum/ForumThreadView.php
- site/tests/ruleset.xml
Fixes the `Generic.Formatting.SpaceAfterCast` style errors which is that there must be a single space between a cast the argument it acts on:
```
$a = (int) $value;
```
> [Refactor:PHP] Fix Generic.Formatting.SpaceAfterCast style errors

- site/app/templates/course/UploadCourseMaterialsForm.twig
Solves #4711
Looks like someone added an eventhandler for clicking on the upload box that open the file explorer. This is extraneous because the input box is of a class that automatically opens the file explorer when clicked on
> removing double click
