Submitty/Submitty

- grading/validator.cpp
Remove trailing comma. Haven't tested though.
> Fix submission.json validity issues

- modules/clean.cpp
- modules/clean.h
- modules/diffNaive.cpp
I had to delete the old documentation branch because I had cloned from master before and needed to clone from develop instead.  I also made some adjustments to the formatting of clean.h, clean.cpp, and diffNaive.cpp, so hopefully they look more uniform now.
> Added comments back to clean.h and adjusted formatting for other files

- AUTHORS.md
- modules/STRutil.h
- modules/clean.cpp
- modules/clean.h
- modules/diffNaive.cpp
- modules/difference.cpp
- modules/difference.h
- modules/metaData.h
- modules/modules.h
- modules/myersDiff.cpp
- modules/myersDiff.h
- modules/runDiff.h
- modules/testResults.h
- modules/textMasking.cpp
- modules/textMasking.h
- modules/tokenSearch.cpp
- modules/tokenSearch.h
- modules/tokens.cpp
- modules/tokens.h
I moved the contributors to a file called 'AUTHORS.md' which is now referrenced in all the headers of modules.  Hopefully this works.  If changing any of the documentation for other files, please use the same style for headers.  Please let me know if there's any other changes I should make to the header.
> Added a new file and adjusted headers

- public/view/homework.php
Clean up display as well such that adding new things to the display is easier (as just need to append to $field_text and it'll handle adding spaces between them automatically via the implode). Easier to change spacing as well as it was uniform before as well.
> Only display points on submission if points > 0 (#78)

- modules/difference.cpp
- modules/difference.h
- modules/testResults.h
Sorry about the number of commits.  I tried to do a rebase and it didn't really work and got an extra two commits.
> Updated documentation for function and file headers

- modules/tokenSearch.cpp
- modules/tokenSearch.h
Just as a note, I wasn't sure how some of the functions for token searching are different, so I simply put it as a different way of searching for tokens.  Please let me know the proper description for them if you know or edit it yourself.  Also I hope the documentation I just added is good.  Let me know if I need to fix anything.
> Quick documentation on token searching

- public/controller/data_functions.php
- public/controller/homework.php
- public/view/homework.php
Fixed: Add link to assignment description in config #46
> Assignment link

- public/controller/data_functions.php
- public/controller/homework.php
- public/view/homework.php
Added to viewer/homework.php to include a description box if the prof……essor wants to add a description also added description_for_assignment function to data functions and added variable assignment_description to controller/homework.php
> Add Description Box

- grading/execute.cpp
- public/index.php
- public/view/homework.php
Fixes 905bd363c4986c43bc63e8fb41faff870d648310
Change my_char_args to temp_args as my_char_args has not been declared yet.
> Fix the grading variable name bug that prevented compilation

- public/index.php
- public/view/homework.php
Fixes 8db919c47f619eafd0c07d8d2a3a78c1612a8cce
Moves the location of the logout button to homework.php to avoid duplicate headers, removes it (for now) as there is no associated functionality, and reverts the incorrect commit of local php login code
> Fix logout button bug

- Docs/sample_apache_config
Line 1: Missing left side carat in Apache conf file is fixed
> Correct syntax error

- CONFIGURE.sh
- Docs/sample_bin/new.svnuser.pl
- Docs/sample_bin/rcsonly.pl
- bin/INSTALL_template.sh
for generating user account and Apache configuration
> Added rcsonly.pl and new.svnuser.pl

- grading/difference.cpp
- grading/json.hpp
- grading/main_configure.cpp
- grading/main_validator.cpp
- grading/tokens.cpp
> Updated JSON output to use nlohmann/json

- TAGradingServer/account/ajax/admin-csv-report.php
- TAGradingServer/account/ajax/admin-hw-report.php
See a speed increase of ~3x in generating this as well
> Fix bug in homework reports for late days and performance improvements

- TAGradingServer/account/admin-orphans.php
Otherwise page throws an exception and page doesn't function properly (and messes up links leaving the page)
> Fix orphans page using old DB references

- TAGradingServer/account/submit/admin-classlist.php
Fixed bug discussed over the weekend.
> Issues 239/240

- .gitattributes
Repo is normally cloned from Master, so I need this merged for testing EOL encoding when cloning the repo in Windows.
> EOL Normalization

- TAGradingServer/account/admin-tests.php
- TAGradingServer/account/ajax/admin-tests.php
- TAGradingServer/account/submit/admin-classlist.php
- TAGradingServer/footer.php
> Implement upload of grades for tests/quizzes/exams

- TAGradingServer/account/submit/admin-classlist.php
Small token change corrects bug.
> FIX class list upload where student section is reassigned

- grading/Sample_CMakeLists.txt
- grading/error_message.cpp
Removed a newline in a string in error_message.cpp.
Added error_messages.h to CMakeList.
> Fixed linker errors

- .setup/install_system.sh
Explicitly set the path where Dr. Memory was being extracted and changed the link to reflect it
> Explicitly set the path where Dr. Memory was being extracted

- public/controller/controller_functions.php
Redirects to an error page when users entered invalid semesters and courses.
Related to #310 
@MasterOdin @bmcutler
> Added error messages for invalid semesters and courses

- public/drag-and-drop/drag_and_drop.js
- public/view/homework.php
I believe this fixed the folder check for most cases (please test and break it).
Also fixed a null reference error caused by the mispositioning of a tag in the html.
#387 @MasterOdin @bmcutler
> Fixed folder check on drag and drop

- grading/default_config.h
- public/controller/data_functions.php
- public/controller/upload.php
- public/drag-and-drop/drag_and_drop.js
- public/view/homework.php
- sample_files/sample_assignment_config/cpp_cats/config.h
- sample_files/sample_assignment_config/cpp_memory_debugging/config.h
- sample_files/sample_assignment_config/csci1200_hw1_text_justification/config.h
- sample_files/sample_assignment_config/csci4210_fork_assignment/config.h
- sample_files/sample_assignment_config/python_buggy_output/config.h
- sample_files/sample_assignment_config/python_simple_homework/config.h
- tests/integrationTests/tests/cpp_cats/__init__.py
- tests/integrationTests/tests/cpp_memory_debugging/__init__.py
- tests/integrationTests/tests/linehighlight_test/__init__.py
1. Put files under the version folder if num_parts == 1.
2. Fixed check of max file size. #383 
3. Fixed cancel submission button. #389 
4. Small changes of the submission page:
- Removed "Delete All" buttons in each drop zone.
- Added a "Start New" button, which empties all buckets.
- Added a button "Get Version X files" when in highest version.
- A "Start from Version X" if current version is not the highest jumps to the highest version.
5. Added comments and cleaned out old code.
> Drag and drop improvements and small issue fixes

- public/controller/data_functions.php
- public/controller/homework.php
- public/controller/upload.php
- public/view/homework.php
1. Code now gets num_parts and part_names from assignment config.
2. Changed error messages for assignment being late, within/exceed max late days allowed.
#394 #61
> Fixed multi part and other improvements

- TAGradingServer/account/account-rubric.php
- TAGradingServer/account/iframe/file-display.php
- TAGradingServer/toolbox/functions.php
- public/controller/data_functions.php
- public/view/homework.php
Inline pdf and/or image display feature added. 
Submission page improved.
#400
> PDF/Image display & Submission Page Styling & Bug Fixes

- TAGradingServer/account/iframe/file-display.php
> TA grading page file display security

- public/drag-and-drop/drag_and_drop.js
- public/view/homework.php
1. Fixed selecting same file after deletion.
2. Fixed diff-viewer display on submission side.
#424 @MasterOdin
> bug fix for adding same file(s) using file browser after deleting

- .setup/install_system.sh
- TAGradingServer/account/submit/admin-classlist.php
- TAGradingServer/toolbox/functions.php
- bin/create_course.sh
- site/app/models/Config.php
- site/cgi-bin/xlsx_to_csv.cgi
Also fixes INSTALL.sh clean breaking the 104 url by switching the location of the config.ini file for the course
> Fix uploading xlsx spreadsheet to TAGradingServer

- Vagrantfile
> Fix time drift bug on Vagrant VM

- site/app/controllers/student/SubmissionController.php
- site/app/models/Gradeable.php
- site/app/views/submission/HomeworkView.php
- site/public/css/diff-viewer.css
- site/public/js/drag-and-drop.js
This finishes up the remaining points in #462 and should make things increasingly more functional for the semester.
> Finish remaining issues from #462

- site/app/views/GlobalView.php
- site/public/css/server.css
PR this now since I don't think I'll finish the grading drafts for a while yet
> Fix styling of logo

- .setup/add_sample_courses.py
- TAGradingServer/toolbox/functions.php
- site/app/controllers/student/SubmissionController.php
- site/app/exceptions/AuthenticationException.php
- site/app/exceptions/BaseException.php
- site/app/libraries/Core.php
- site/app/models/Gradeable.php
- site/app/models/GradeableList.php
- site/app/models/User.php
- site/app/views/GlobalView.php
- site/app/views/NavigationView.php
- site/app/views/admin/ConfigurationView.php
- site/app/views/submission/HomeworkView.php
- site/data/tables.sql
- site/public/css/server.css
Changes:
- Fixes #494 (all badges are same width and all titles start at same point regardless of badge existence)
- Fixes #496 (disable buttons for gradeables without config json, show error message when attempting to view submission page for these gradeables)
- Doesn't show grading button for students on gradeable list page
- Doesn't show edit button to non-admins on gradeable list page
- Doesn't show future gradeables to non-admin users
- Locks TAGradingServer pages to only be accessible to non-student users
- Wrap exceptions thrown anywhere in authentication process to be AuthenticationException so passwords are scrubbed
- Don't generate class.json file anymore when building sample courses
> Submission side improvements

- TAGradingServer/account/admin-gradeable.php
- TAGradingServer/account/admin-single-user-review.php
- TAGradingServer/account/admin-students.php
- TAGradingServer/account/admin-users.php
- grading/TestCase.cpp
- sample_files/sample_assignment_config/cpp_custom/custom_grader_code/grader.cpp
- site/app/libraries/Core.php
This should resolve all the orange "notice" boxes on the left side of the screen (#553)
> Fix searching for an unknown user (resolves notices pointed out in #553)

- TAGradingServer/account/ajax/admin-csv-report.php
- site/app/views/NavigationView.php
Export all grades to a CSV. Even grades for assignments which grading strat date has not yet passed. Empty grade defaults to 0. Fixes #575 Also comment out "Import from JSON". There is an issue with the ajax request going to the url of the ta grading site.
> Export all grades to CSV

- TAGradingServer/account/admin-gradeable.php
Support up to 1000 pts on rubric, mimic grading side for with incrementing points. Fixes #547
> Support 1000 pts on create a gradeable page

- bin/build_homework_function.sh
- bin/make_assignments_txt_file.py
- grading/main_configure.cpp
- site/app/views/GlobalView.php
Also, reduce output of build course script
and log cmake and make output.
> Build course permissions errors

- TAGradingServer/account/submit/admin-gradeable.php
Fixed issue where creating an electronic gradeable was attempting to insert instructions url which no longer exists.
> Fixed issue creating new electronic gradeable

- TAGradingServer/account/admin-single-user-review.php
> Fix undefined variable

- TAGradingServer/account/ajax/admin-hw-report.php
- site/app/controllers/StudentController.php
- site/app/controllers/student/RainbowGradesController.php
- site/app/views/NavigationView.php
- site/app/views/submission/RainbowGradesView.php
> add rainbow grades page and fix generate homework reports

- .setup/INSTALL_SUBMITTY_template.sh
- .travis.yml
- TAGradingServer/account/account-checkpoints-gradeable.php
- TAGradingServer/account/account-numerictext-gradeable.php
- TAGradingServer/account/account-rubric.php
- TAGradingServer/account/account-summary.php
- TAGradingServer/account/account-tests.php
- TAGradingServer/account/admin-latedays-exceptions.php
- TAGradingServer/account/ajax/account-checkpoints-gradeable.php
- TAGradingServer/account/ajax/account-numerictext-gradeable.php
- TAGradingServer/account/ajax/admin-hw-report.php
- TAGradingServer/account/index.php
- TAGradingServer/account/submit/account-rubric.php
- TAGradingServer/account/submit/admin-classlist.php
- TAGradingServer/lib/ExceptionHandler.php
- TAGradingServer/models/ElectronicGradeable.php
- TAGradingServer/models/User.php
- TAGradingServer/toolbox/functions.php
- bin/get_active_versions.py
- tests/unitTests/app/libraries/LoggerTester.php
> Hack to get grading to work for active versions and grader_id

- .setup/install_system.sh
- .setup/travis/setup.sh
- .setup/vagrant/db_inserts.sql
- .setup/vagrant/reset_system.py
- TAGradingServer/account/account-checkpoints-gradeable.php
- TAGradingServer/account/account-numerictext-gradeable.php
- TAGradingServer/account/account-summary.php
- TAGradingServer/account/admin-gradeable.php
- TAGradingServer/account/ajax/admin-hw-report.php
- TAGradingServer/account/index.php
- TAGradingServer/account/submit/admin-grade-summaries.php
- TAGradingServer/account/submit/admin-gradeable.php
- TAGradingServer/models/ElectronicGradeable.php
- site/app/views/NavigationView.php
Labels of date dependencies, some improved hide/show on create gradeables form.
> Fix gradeables2

- TAGradingServer/account/account-checkpoints-gradeable.php
- TAGradingServer/account/account-numerictext-gradeable.php
- TAGradingServer/account/account-summary.php
- TAGradingServer/account/account-tests.php
- TAGradingServer/account/admin-latedays-exceptions.php
- TAGradingServer/account/admin-latedays.php
- TAGradingServer/account/admin-students.php
- TAGradingServer/account/admin-users.php
- TAGradingServer/account/submit/admin-classlist.php
Closes #675
Also moves the box on the pages up 60px as it was a ton of wasted space and who wants that.
> Add scrollbar to pages missing them and don't add to late days table on student CSV upload

- TAGradingServer/account/index.php
Fixed issue where panel visibility button had inconsisten glow if reset when panels were hidden. Fixed issue causing panel positions to not persist.
Closes #691
> Minor bug fixes for Ta grading ui

- .setup/add_sample_courses.py
- TAGradingServer/account/account-summary.php
- TAGradingServer/models/ElectronicGradeable.php
- site/app/views/NavigationView.php
> Improve summary page for gradeables

- site/public/js/server.js
As it's not fully supported in Safari and people don't upgrade
> don't use let in javascript

- TAGradingServer/account/account-summary.php
- TAGradingServer/account/index.php
- TAGradingServer/account/submit/account-rubric.php
> Adds in scroll bar on index page for instructors and autoscroll on summary page to student

- TAGradingServer/account/account-rubric.php
- TAGradingServer/models/ElectronicGradeable.php
Fixed displaying original grader in the grading rubric.
closes #647
> Display original grader

- TAGradingServer/account/account-checkpoints-gradeable.php
- TAGradingServer/account/account-numerictext-gradeable.php
also doesn't allow for wrapping of user names.
Fixes the first two parts of #678, third part left for later commit
> put section_id next to every row for lab and test input

- TAGradingServer/account/admin-gradeable.php
Allow instructors to create new gradeables using existing gradeables as templates. Closes #743
> Gradeable templates

- TAGradingServer/account/admin-gradeable.php
Export the right graders to json based on the selected user groups on the create/edit gradeable form. closes #669
> Export to JSON user group fixes

- TAGradingServer/account/account-rubric.php
- TAGradingServer/account/admin-gradeable.php
Prevent TAs from submitting grades if no rubric items exist. Closes #681
> Prevent TAs from submitting grades if no rubric items exist

- TAGradingServer/account/index.php
> Added check for cookies being = "undefined"

- TAGradingServer/account/index.php
The hot key for opening the file viewer, 'f', causes some issues when attempting to search a file, ctrl+f. I changed the hot key to 'o'.
> Changed hotkey for opening file viewer

- TAGradingServer/account/admin-latedays-exceptions.php
- TAGradingServer/account/index.php
Removed user group restrictions on late day exceptions.
> Exceptions user group

- .setup/install_system.sh
- .setup/travis/autograder.sh
> stop using sourceforge for emma

- site/app/controllers/admin/ConfigurationController.php
- site/app/models/Config.php
- site/app/views/admin/ConfigurationView.php
- site/app/views/submission/HomeworkView.php
- site/config/course_template.ini
Keep files from previous submission in the upload box or not can now be set in course settings
#596
> Keep previous files or not

- site/app/controllers/admin/ConfigurationController.php
- site/app/models/Config.php
- site/app/views/admin/ConfigurationView.php
- site/config/course_template.ini
- site/public/index.php
> Add course homepage to breadcrumb navigation

- grading/TestCase.cpp
- grading/TestCase.h
- grading/default_config.h
- grading/main_configure.cpp
- site/app/models/Gradeable.php
- site/public/js/drag-and-drop.js
- tests/integrationTests/tests/python_simple_homework/validation/results.json_buggy
- tests/integrationTests/tests/python_simple_homework/validation/results.json_buggy2
- tests/integrationTests/tests/python_simple_homework/validation/results.json_correct
- tests/integrationTests/tests/python_simple_homework/validation/results.json_infinite_loop_time_cutoff
- tests/integrationTests/tests/python_simple_homework/validation/results.json_infinite_loop_too_much_output
- tests/integrationTests/tests/python_simple_homework/validation/results.json_syntax_error
- tests/integrationTests/tests/python_simple_homework/validation/results_grade.txt_buggy
- tests/integrationTests/tests/python_simple_homework/validation/results_grade.txt_buggy2
- tests/integrationTests/tests/python_simple_homework/validation/results_grade.txt_correct
- tests/integrationTests/tests/python_simple_homework/validation/results_grade.txt_infinite_loop_time_cutoff
- tests/integrationTests/tests/python_simple_homework/validation/results_grade.txt_infinite_loop_too_much_output
- tests/integrationTests/tests/python_simple_homework/validation/results_grade.txt_syntax_error
> fix max num submissions value

- site/data/tables.sql
Added a column to keep track of when a student viewed their grade for a particular version of a gradeable
> Added student viewed date to electronic_gradeable_data

- site/data/tables.sql
Removed the extra viewed column from electronic_gradeable_version
> Removed extra viewed column

- RainbowGrades/main.cpp
- RainbowGrades/output.cpp
> fix stddev calculation (don't just add)

- RainbowGrades/constants_and_globals.h
- RainbowGrades/main.cpp
- RainbowGrades/output.cpp
> hide late days when a course does not use them

- site/app/controllers/student/SubmissionController.php
- tests/unitTests/app/controllers/submission/SubmissionControllerTester.php
> Fix two disabled tests

- TAGradingServer/account/admin-grader-list.php
modified:   TAGradingServer/account/admin-grader-list.php
Fix for Issue #837.
> Changes to be committed:

- TAGradingServer/account/account-summary.php
- TAGradingServer/account/index.php
- TAGradingServer/account/submit/account-rubric.php
- site/app/views/grading/ElectronicGraderView.php
Linked to @JerameyATyler version of homework index page
> Account summary

- bin/grade_students.sh
This should fix the issue where you might see "0 / 20" on a submission view while seeing all components having grades.
> Get rid of queue file after doing all other steps

- grading/CMakeLists.txt
- grading/PacmanGrader.cpp
- grading/PacmanGrader.h
- grading/TestCase.cpp
http://ai.berkeley.edu/project_instructions.html
> add grader for PacMan assignments

- grading/execute.cpp
- sample_files/sample_assignment_config/paragraph_textboxes/config.json
- site/app/models/Gradeable.php
- site/app/views/NavigationView.php
- site/app/views/submission/HomeworkView.php
- tests/e2e/test_navigation_page_student.py
> navigation page: change labels & fix dates

- .setup/data/users.yml
- .setup/vagrant/db_inserts.sql
- RainbowGrades/main.cpp
- RainbowGrades/output.cpp
- TAGradingServer/account/account-summary.php
- grading/execute.cpp
Fix for incorrect summations, missing denominators, and missing gradeable when no gradeable component is present.
> Fix for issues on index page

- TAGradingServer/account/account-summary.php
- TAGradingServer/account/ajax/account-summary.php
Split each section into subsections to get around POST size limits. (This is not a permanent fix).
> Fixed issues on index page

- TAGradingServer/account/admin-latedays-exceptions.php
- TAGradingServer/account/admin-latedays.php
> Fix csv upload

- .travis.yml
- site/app/authentication/PamAuthentication.php
- site/app/libraries/Core.php
- site/app/libraries/Database.php
- tests/e2e/base_testcase.py
> Fix failing PHP 7 tests

- TAGradingServer/account/account-rubric.php
- TAGradingServer/account/iframe/test-pane.php
- TAGradingServer/lib/DiffViewer.php
- TAGradingServer/toolbox/include/custom/css/diff-viewer.css
- TAGradingServer/toolbox/include/custom/css/reset.css
- TAGradingServer/toolbox/include/custom/js/diff-viewer.js
- site/app/libraries/DiffViewer.php
- tests/testData/diffs/diff_test_01/output_actual.txt
- tests/testData/diffs/diff_test_01/output_expected.txt
- tests/testData/diffs/diff_test_02/output_actual.txt
- tests/testData/diffs/diff_test_02/output_expected.txt
- tests/testData/diffs/diff_test_03/output_actual.txt
- tests/testData/diffs/diff_test_03/output_expected.txt
- tests/testData/diffs/diff_test_04/output_actual.txt
- tests/testData/diffs/diff_test_04/output_expected.txt
Added a second check for iframe size less than 10 px.
> Fix for diff viewer for FireFox

- TAGradingServer/toolbox/functions.php
This allows for putting a
`ta_base_url` inside the `/var/local/submitty/courses/s17/csci1200/config/config.ini` (or whatever the exact path is) under the `hidden_details` section.
> fix for DS url

- site/app/views/grading/SimpleGraderView.php
> Show lab printout link on new interface

- site/app/models/GradeableComponent.php
- site/app/models/GradeableDb.php
- site/app/views/grading/ElectronicGraderView.php
> Fix negative value answers affecting TA grading

- Docs/nightly_db_backup/db_backup.py
- Docs/nightly_db_backup/readme.txt
Python conversion of the nightly DB dump script used at RPI dept. of
computer science.
> Nightly Database Dump

- TAGradingServer/models/GradeSummary.php
> export grade_released_date to grade summaries

- LICENSE.md
- README.md
> edit README

- .setup/CONFIGURE_SUBMITTY.sh
- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/install_system.sh
- .setup/travis/setup.sh
- TAGradingServer/account/admin-gradeable.php
- TAGradingServer/account/submit/admin-gradeable.php
- bin/grade_students.sh
Closes #1056.
It should not be possible to set a gradeable to be done by SVN/Repository and remove all of the configuration details in install_system.sh trying to partially setup SVN.
Also closes #1034 as I cleaned up the SVN stuff from install_system.sh.
> remove svn

- site/app/models/Gradeable.php
> Fix bug where specified order of components after edit isn't respected

- site/app/controllers/grading/SimpleGraderController.php
- site/app/models/Gradeable.php
- site/app/models/GradeableComponent.php
- site/app/views/grading/SimpleGraderView.php
This fixes the broken function references that were found during today's meeting.
> Fix merge break on numeric/checkpoint form

- site/app/models/Gradeable.php
> Fix issue where you could not view components with 't' or 'f' as comment

- site/app/controllers/AdminController.php
A case was missing a break in master.
> Missing a break

- .setup/vagrant/pg_hba.conf
- site/app/models/User.php
Fix bug introduced where registration section was always either section 1 or null.
> Fix bug with registration sections not being displayed properly

- .setup/data/courses/sample.yml
- .setup/data/courses/tutorial.yml
Added 3 new tutorial assignments. These deal with cmake, tkinter (python gui), and GLFW (graphics) respectively.
> Added Tutorial Assignments 13-15

- site/app/libraries/database/DatabaseQueriesPostgresql.php
> Fix DatabaseQueriesPostgresql.php

- .setup/data/courses/development.yml
- grading/execute.cpp
- more_autograding_examples/choice_of_language/config/config.json
- more_autograding_examples/choice_of_language/config/test_output/output.txt
- more_autograding_examples/choice_of_language/submissions/c.c
- more_autograding_examples/choice_of_language/submissions/cpp.cpp
- more_autograding_examples/choice_of_language/submissions/python2.py
- more_autograding_examples/choice_of_language/submissions/python3.py
- more_autograding_examples/cpp_provided_code/config/config.json
- more_autograding_examples/cpp_provided_code/config/test_code/main.cpp
- more_autograding_examples/cpp_provided_code/config/test_output/output.txt
- more_autograding_examples/cpp_provided_code/submissions/student.cpp
- more_autograding_examples/cpp_provided_code/submissions/student.h
- tests/integrationTests/tests/choice_of_language/__init__.py
- tests/integrationTests/tests/choice_of_language/validation/results.json_c
- tests/integrationTests/tests/choice_of_language/validation/results.json_cpp
- tests/integrationTests/tests/choice_of_language/validation/results.json_python2
- tests/integrationTests/tests/choice_of_language/validation/results.json_python3
- tests/integrationTests/tests/choice_of_language/validation/results_grade.txt_c
- tests/integrationTests/tests/choice_of_language/validation/results_grade.txt_cpp
- tests/integrationTests/tests/choice_of_language/validation/results_grade.txt_python2
- tests/integrationTests/tests/choice_of_language/validation/results_grade.txt_python3
- tests/integrationTests/tests/cpp_provided_code/__init__.py
- tests/integrationTests/tests/cpp_provided_code/validation/results.json_solution
- tests/integrationTests/tests/cpp_provided_code/validation/results_grade.txt_solution
- tests/integrationTests/tests/tutorial_03_multipart/__init__.py
Closes #1136 
checks off one item for #763
> New example configs: choice of language & provided code

- RainbowGrades/main.cpp
Change required for Rainbow Grades to function as of #1080
> Rainbow Grades now uses single score field

- site/app/controllers/student/TeamController.php
> Fix invalid reference in TeamController when loading GradeablesList model

- .setup/bin/setup_sample_courses.py
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/controllers/grading/SimpleGraderController.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/libraries/database/IDatabaseQueries.php
- site/app/models/GradeSummary.php
- site/app/models/Gradeable.php
- site/app/models/HWReport.php
- site/app/models/LateDaysCalculation.php
- site/app/views/grading/ElectronicGraderView.php
- site/data/tables.sql
> Clean up late days

- .setup/travis/autograder.sh
- tests/integrationTests/tests/python_multipart_static_analysis/__init__.py
Gotta remember to change both .setup/INSTALL_SUBMITTY_HELPER.sh 
and also .setup/travis/autograder.sh
> Debug travis static analysis

- site/public/js/server.js
Grading all components of lab simultaneously by pushing the user id was broken, is now fixed
> Fixed grading all components of lab simultaneously

- .setup/bin/setup_sample_courses.py
- .setup/data/courses/blank.yml
Added support for `gradeables` field not being in course YAML files.
Added a new course "blank" for development/testing purposes that contains no gradeables by default.
> Added empty course for testing

- .setup/bin/setup_sample_courses.py
- .setup/data/users.yml
- .setup/data/users/browna.yml
- .setup/data/users/developer.yml
- .setup/data/users/grader.yml
- .setup/data/users/instructor.yml
- .setup/data/users/joness.yml
- .setup/data/users/manne.yml
- .setup/data/users/pearsr.yml
- .setup/data/users/smithj.yml
- .setup/data/users/student.yml
- .setup/data/users/ta.yml
- .setup/data/users/ta2.yml
- .setup/data/users/ta3.yml
- site/app/controllers/admin/AdminGradeableController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/Gradeable.php
- site/app/models/User.php
- site/app/views/admin/AdminGradeableView.php
- site/data/course_tables.sql
- tests/unitTests/app/models/UserTester.php
can create and edit gradeable and insert into database, nothing else is implemented yet
> Initial peer grading implementation

- grading/TestCase.cpp
- grading/TestCase.h
- grading/main_validator.cpp
- more_autograding_examples/cpp_simple_lab/config/config.json
- tests/integrationTests/tests/cpp_simple_lab/validation/compile_error_results.json
- tests/integrationTests/tests/cpp_simple_lab/validation/extra_credit_results.json
> Option to hide execute_logfile.txt

- .setup/INSTALL_SUBMITTY_HELPER.sh
- tests/integrationTests/tests/tutorial_06_loop_types/__init__.py
- tests/integrationTests/tests/tutorial_06_loop_types/validation/grade.txt_buggy
- tests/integrationTests/tests/tutorial_06_loop_types/validation/grade.txt_solution
- tests/integrationTests/tests/tutorial_06_loop_types/validation/results.json_buggy
- tests/integrationTests/tests/tutorial_06_loop_types/validation/results.json_solution
- tests/integrationTests/tests/tutorial_07_loop_depth/__init__.py
- tests/integrationTests/tests/tutorial_07_loop_depth/validation/grade.txt_buggy
- tests/integrationTests/tests/tutorial_07_loop_depth/validation/grade.txt_solution
- tests/integrationTests/tests/tutorial_07_loop_depth/validation/results.json_buggy
- tests/integrationTests/tests/tutorial_07_loop_depth/validation/results.json_solution
> Update version of AnalysisTools to v0.2.4, re-enable tutorial_06 and tutorial_07 tests

- .setup/bin/reupload_old_assignments.py
- grading/execute.cpp
- grading/window_utils.cpp
- grading/window_utils.h
Closes #1239 
Closes #1115
Performed extensive testing on Actions/Graphics/Image Diffing.
Found and fixed an error in window detection which caused the program to sometimes attempt to give input to the wrong window. 
Added support for special keys (e.g. enter, shift, etc.) and multikey combos (e.g. ctrl+alt+del) to actions.
Found and fixed a permissions bug in the reupload_old_assignments script.
> Fixed Window Detection in Graphics Programs

- .setup/bin/setup_sample_courses.py
- .setup/install_system.sh
- grading/system_call_categories.cpp
> Quick Debian fixes

- site/app/controllers/student/SubmissionController.php
- site/app/libraries/database/AbstractDatabaseQueries.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/HWReport.php
- site/app/models/LateDaysCalculation.php
- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/HomeworkView.php
- tests/unitTests/app/controllers/submission/SubmissionControllerTester.php
> Show extensions to students

- site/app/controllers/MiscController.php
> Fixed students on teams being unable to download assignments

- site/app/controllers/grading/ElectronicGraderController.php
> TA Progress Bar Now Correct

- site/app/views/admin/AdminGradeableView.php
- site/app/views/grading/ElectronicGraderView.php
Fixed all the issues addressed in #1318.
Actually the one removed the extra credit and penalty icons is in my other pull request by accident.
Resolves #1318
> Mark Functionality Improvement

- site/app/models/GradeableAutocheck.php
> Ensure diff viewer highlights the correct lines

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/install_system.sh
- .setup/travis/autograder.sh
- bin/insert_database_version_data.py
- bin/submitty_grading_scheduler.py
- grading/TestCase.cpp
- grading/TestCase.h
- python_submitty_utils/setup.py
- python_submitty_utils/submitty_utils/dateutils.py
* tweaks to installation of python_submitty_utils (ok to ignore error message for python2)
* try / catch around database connection that was failing in insert_database_version_data.py
* default resource limits for submitty_count
> Misc autograding improvements

- .setup/bin/partial_reset.py
- .setup/bin/setup_sample_courses.py
- .setup/install_system.sh
- tests/integrationTests/tests/tutorial_05_cpp_static_analysis/__init__.py
closes #1198..
(also unrelated update to an autograding test case)
> install_system.sh reads hsdbu password from config file

- .setup/bin/reupload_old_assignments.py
closes #1321 
Reupload courses now copies user assignment settings and timestamps, and sets the database version properly.
> Fix for reupload of old courses

- site/app/controllers/admin/ConfigurationController.php
- site/app/models/Config.php
- site/config/course_template.ini
Takes the new course configuration stuff to support #1349 into a separate pull request to add it into the system so that we can rebuild courses sooner and then seamlessly merge #1349 in and not require any course rebuilding.
> Add new course config stuff

- bin/insert_database_version_data.py
- site/data/course_tables.sql
EDITED [ First part of ... #1363   @jbarthelmess  will finish ]
Haven't tested this as I don't have time to do anymore till tomorrow, but should be relatively easy for someone to fix any potential issues.
> Add flag in database to indicate if autograding has been completed

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/AbstractDatabaseQueries.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/GradeableComponent.php
- site/app/models/GradeableComponentMark.php
- site/app/views/admin/AdminGradeableView.php
- site/public/js/ta-grading-mark.js
- fixed problems with overwriting grades by different graders
- restricted create edit gradeable page, so that a gradeable cannot be both a team assignment and peer grading.  This should close #1249  for now, may want to open it again if we decide to support having both in the future
> fixed bugs with overwriting graders & disallow team + peer grading (for now)

- site/app/controllers/admin/AdminGradeableController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/Gradeable.php
- site/app/models/HWReport.php
- site/app/views/admin/AdminGradeableView.php
- site/app/views/grading/ElectronicGraderView.php
there is now an added component that tracks the percentage of completed peer grading
> background component tracking peer grading completion

- site/app/models/Gradeable.php
- site/app/models/GradeableComponent.php
- site/app/views/grading/ElectronicGraderView.php
small fixes include rounding number of graded students, disable rubric for not active submissions, and probably others I don't recall.
> Fix indentation, add comments, small fixes

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/AbstractDatabaseQueries.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/Gradeable.php
- site/app/models/GradeableComponent.php
- site/app/models/GradeableComponentMark.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
grades are now saved correctly
saving custom score and comment works
js for showing who graded works
> Fix the way grades are saved and js for grader

- site/app/views/admin/AdminGradeableView.php
They are buggy and need to be fixed
> Comment out moving/deleting questions and peer grading

- site/app/views/HomePageView.php
- site/app/views/NavigationView.php
> view submissions option for non ta graded submissions

- site/app/models/AdminGradeable.php
> Fix default to having an empty question

- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
closes #1446 (autograding+tagrading total correction on details page)
closes #1426 (labeling assigned/enrolled registration/rotating)
> Wording changes

- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/User.php
@jbarthelmess not sure why the anon_id wasn't working in the update, I didn't have time to debug, I just removed it again.
Please test this & debug.
> php syntax error, and error with anon_id (unclear)

- site/app/views/admin/AdminGradeableView.php
> page numbers for update when pdf is switched and show for edits

- site/app/views/admin/AdminGradeableView.php
I did not reword the message because I don't know of a better way to say it.
resolves #1455
> Makes it caution warning only appears when there are marks in the question

- site/app/controllers/admin/UsersController.php
This allows you to "add a user" where you fill in the user_id and other course specific things (section, group, etc.) and it'll add the person to that course, using the name, password, etc. that is stored in the global DB.
> Add ability to put user_id to add new user to course

- site/app/views/grading/ElectronicGraderView.php
> fixes general comment not saving

- TAGradingServer/account/account-rubric.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/server.js
- site/public/js/ta-grading-mark.js
> Increased PDF Height

- TAGradingServer/toolbox/include/custom/css/diff-viewer.css
- TAGradingServer/toolbox/include/custom/js/diff-viewer.js
- site/public/css/diff-viewer.css
- site/public/js/diff-viewer.js
> Fixed the alignment of the line_number elements in code outputs.

- site/app/views/grading/ElectronicGraderView.php
Made the marks button slightly bigger and added a beautifully colored next student button.
> Added bigger marks and next student buttons

- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading.js
> Expand all + Close all for auto grading

- bin/authentication.py
- bin/generate_repos.py
- bin/grade_item.py
- site/app/controllers/student/SubmissionController.php
- site/app/views/admin/AdminGradeableView.php
- site/app/views/submission/TeamView.php
Closes #1422 
Implemented generation of repositories for teams in generate_repos.py.
authentication.py will allow any member of the team, instructor or full access grader to clone the team repository.
The team repository URL is displayed on the team management page.
> VCS Team Assignments

- .travis.yml
- site/app/libraries/database/AbstractDatabaseQueries.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/User.php
I'm not fully happy with how this works, but I'll raise a task for next semester on improving this design when we have a bit more flexibility with DB changes.
I'm also using this to kill PHP 5.6 support so we can take advantage of a more secure random function available only in PHP 7 and there's really no reason not to use PHP 5.6 over PHP 7.
> set anon_id if null when we try and get it

- site/cgi-bin/pdf_check.cgi
Used to help debug permissions, etc. errors
> Error messages for bulk upload

- site/app/controllers/grading/SimpleGraderController.php
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/views/grading/SimpleGraderView.php
Fixed lab printing to work with correct section type (rotating vs registration). 
Fixed printing to work with sorting code.
Note that  changes were made to two functions in DatabasePostgresql to make sorting easier. Both changes involved adding a new parameter which was given a default value to avoid introducing bugs.
> Fixed Lab Printing

- site/app/controllers/grading/ElectronicGraderController.php
Added Breadcrumbs according to #1505. The notes for breadcrumbs on the grading view did not say how to handle team submissions, so I just used commas to separate all the user ids.
> Added Breadcrumbs

- site/app/views/HomePageView.php
Fixes duplicate names in course views
> Fixes display name error

- RainbowGrades/main.cpp
- RainbowGrades/table.cpp
- RainbowGrades/table.h
- site/app/libraries/database/DatabaseQueriesPostgresql.php
- site/app/models/HWReport.php
- site/app/models/LateDaysCalculation.php
Fixes #1539  -- don't generate hw reports for non electronic gradeables
Fixes #1466  -- late days were totally wrong
> Fix HW Reports & Late Day Calculations

- site/app/models/LateDaysCalculation.php
Unsetting the variable defined as a member of an array does not delete the element from the array. You need to explicitly unset the array element.
```
php > $a = [0, 1, 2];
php > $count = count($a);
php > for ($i = 0; $i < $count; $i++) {
php {     $b = $a[$i];
php {     unset($b);
php { }
php > var_dump($a);
php shell code:1:
array(3) {
[0] =>
int(0)
[1] =>
int(1)
[2] =>
int(2)
}
```
I also fixed up the weird whitespace that was in the file.
> fix unset not actually doing anything

- site/app/controllers/HomePageController.php
- site/app/models/User.php
> Name validation

- site/app/controllers/AdminController.php
- site/app/controllers/admin/LateController.php
- site/app/controllers/admin/PlagiarismController.php
- site/app/controllers/admin/UsersController.php
- site/public/css/ta-grading.css
- site/public/js/ta-grading.js
This should close up #1505 and #1572
> Breadcrumbs Fixes

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/models/Gradeable.php
- site/app/models/GradeableComponent.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
The done button now automatically updates the version conflict for gradeable component.
> Added version updates

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/views/grading/ElectronicGraderView.php
Added submitted percentage statistics and breakdown of avg/stddev/count for auto-graded components.
fix #1611
> Added new statistics

- site/public/css/ta-grading.css
- site/public/js/ta-grading.js
This fixes the draggable toolbar hiding behind the panels when dragged over. It now pushes to the top every time something is moved.
> Resolves draggable toolbar hiding behind panels

- site/app/views/grading/ElectronicGraderView.php
Removed TA comment scroll bar - replaced with auto resizing.
> TA Grading Scroll Bar Fix

- site/public/js/server.js
- site/public/js/ta-grading-mark.js
> HTML is escaped on the TA grading page

- site/app/views/admin/AdminGradeableView.php
> Publish will no longer appear for full and no credit

- site/app/views/grading/ElectronicGraderView.php
> Fixed the column in the student details page

- bin/read_iclicker_ids.py
- grading/execute.cpp
- more_autograding_examples/iclicker_upload/config/config.json
- more_autograding_examples/test_notes_upload/config/config.json
- more_autograding_examples/test_notes_upload_3page/config/config.json
instructions for replacement iclicker
> Clicker tweak2

- site/app/views/grading/ElectronicGraderView.php
- site/public/css/ta-grading.css
Marks that are considered published are now marked royal blue on the TA grading page.
Resolves #1631
> Publish marks are marked blue

- .setup/update_database.py
- site/data/course_tables.sql
- site/data/submitty_db.sql
> consistent timestamps (issue #1553)

- .setup/data/courses/sample.yml
- .setup/distro_setup/ubuntu/setup_distro.sh
- site/app/controllers/admin/ReportController.php
> FIx buggy csv generation for gradeables w/o tagrading

- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
Notifies the user that they are uploading a file that isn't allowed. Preserves the users post when the error is thrown so they don't have to re-type the post (although with 2 extra new lines). Resolves #1676
> Creates error warning for uploading files on forum

- site/app/controllers/student/SubmissionController.php
- site/app/views/submission/HomeworkView.php
Fixes #1672
It is now possible for a professor to bulk upload for a team by entering the name of a student on the team.
> Fix team pdf uploads

- site/app/controllers/forum/ForumController.php
- site/app/libraries/Utils.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
This PR includes the following:
- TA/Instructor being able to mark a posted thread as an announcement
- Multiple attachments for posts (Including error checking for limit of 5 images)
- Thread list color updating when a new post is added to that thread (becomes not viewed again)
- Transaction block for creating a thread (will not create a thread if there is an exception thrown in posts but will still display the robot ascii error page)
Partially resolves some of #1678
> Forum Enhancements

- site/app/libraries/database/DatabaseQueries.php
File changed:
site/app/libraries/database/DatabaseQueries.php
manual_registration flag should not block setting a user to NULL
rotating section.
closes #1683
> Rotating Sections Bug

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
> Fixed ta stats page

- site/app/controllers/MiscController.php
- site/app/views/admin/AdminGradeableView.php
- site/app/views/admin/UsersView.php
add error messages to help understand file display failure.
> add error messages to file check

- grading/execute.cpp
(later need to add soot install...   #1694)
> add soot jar paths

- site/app/controllers/student/SubmissionController.php
- site/app/views/NavigationView.php
- site/app/views/submission/HomeworkView.php
Closes #1671
Fixes bug where instructor couldn't submit to group assignments unless they are already in at least one group.
> Allows instructors to submit to group assignment

- site/app/views/submission/HomeworkView.php
> Condense unnecessarily nested if statement

- site/app/libraries/database/DatabaseQueries.php
Fixes for setup rotating sections page.
> Rotating sections

- RainbowGrades/output.cpp
- RainbowGrades/zone.cpp
> Handle zones without specific row & seat assignments

- site/app/libraries/database/DatabaseQueries.php
Fixed a semantic error which caused improper sections to load on the status page.
> Status Page Section Fix

- site/app/views/grading/ElectronicGraderView.php
Changed percentage to the floor instead of round
> Fixed 259 / 260 students submitted being reported as 100%

- site/app/views/forum/ForumThreadView.php
- site/public/css/server.css
Made the original post in a thread stand out more by encompassing the title and removing margins
Made text in TA nav bar clearer
> Slight stylistic improvements

- site/app/views/forum/ForumThreadView.php
- site/public/css/server.css
Move title element inside first post, fixing multi-line titles causing the title to overflow the post container
Made remove post button position absolute to the post it's in
> Fix style issues on forum

- site/app/views/grading/ElectronicGraderView.php
Changed the percentage graded to go out to one decimal point. 259/260 => (99.6%)
> Fix percentage 1617

- site/app/views/AuthenticationView.php
> modified AuthenticationView to gain autofocus on username field

- site/data/course_tables.sql
> Remove unnecessary attachment constraint from course db schema

- AUTHORS.md
- CONTRIBUTING.md
- SUPPORT.md
This pull request is to add appropriate files to the repository as illustrated [here](https://help.github.com/articles/helping-people-contribute-to-your-project/).
I also fixed a small issue in `AUTHORS.md` (kramdown)
> WIP: Added Docs

- grading/execute.cpp
Updated the mpicc and mpirun commands to use mpich 3.2.
> Update to using mpich 3.2

- site/app/controllers/forum/ForumController.php
- site/app/views/forum/ForumThreadView.php
- site/public/css/server.css
- site/public/js/server.js
This PR is a partial resolve of #1678. It includes being able to add code and links into posts. Also included are some changes that increase user ability when creating their posts, users can now tab when inside of the text area and also the text areas dynamically resize based on the length of the content contained. It also cleans up html entities being partially displayed in the thread list.
> Forum: Links and Code implementation

- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
This resolves the issue resulting from a user have special characters in their name and the instructor/ta not being able to view their full name via their anon button. Also includes the fix for the scrollbar not using animation.
Tested with:
> Fix anonymous TA/Instructor button

- .setup/data/courses/sample.yml
The open team homework in the sample course has been updated to use a more interesting config.
> updated open team homework for SIGCSE

- .setup/CONFIGURE_SUBMITTY.py
- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/install_system.sh
- .setup/travis/setup.sh
- bin/grade_item.py
- site/app/controllers/admin/ConfigurationController.php
- site/app/models/AdminGradeable.php
- site/app/models/Config.php
- site/app/views/admin/AdminGradeableView.php
- site/app/views/admin/ConfigurationView.php
- site/app/views/submission/HomeworkView.php
- site/app/views/submission/TeamView.php
- site/config/course_template.ini
- site/config/master_template.ini
The basic gist of this work is that we now properly use vcs_base_url to help construct VCS urls/paths. We use it to try and stitch together the full path from vcs_base_url and vcs_subdirectory (assuming that vcs_subdirectory isn't an absolute path or a URL).
Currently, setting up usage of git for a private user is messy and not really extendable (yet) to having a "git" user per course.
> Initial work for better integrating git

- .setup/vagrant/setup_vagrant.sh
- .travis.yml
- Vagrantfile
* Modified `Vagrantfile` to check if `vagrant-vbguest` is installed before running `vagrant up`. This should reduce the number of questions involving first time setup.
* Modified `.travis.yml` to speed up builds.
> Minor Improvements

- RainbowGrades/MakefileHelper
This avoid recompiling the C++ binary after changing the configuration file.
> Improve dependency graph of the makefile for RainbowGrades.

- site/app/views/forum/ForumThreadView.php
Fixes not encoding title of thread when displaying.
> Fix title not being sanitized before displaying

- junit_test_runner/TestRunner.java
The purpose is to allow running JUnit tests not only for the packages
which end with ".test" and to only run tests on classes whose names end
with "Test". Quick and ugly but have to get it working tonight...
> Updated TestRunner.java.

- bin/grade_item.py
- site/app/views/submission/HomeworkView.php
Closes : #1626 
Commit hash on submission page
> Show commit hash for git assignments

- site/app/controllers/forum/ForumController.php
- site/app/views/forum/ForumThreadView.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/server.js
This PR fixes an error regarding output of the General Comment section on the TA grading page.
For the Forum, this includes a change to file error checking. Now the system will alert the user automatically if there is a problem with the files that they are uploading (whether it be too many or bad file type). With the old system you would have to submit the post before getting feedback on the files you uploaded. This solution is better as there is no need to save the user input to repopulate the text fields on the redirect back when the error is generated. The error checking is still preserved server side as well to ensure the user doesn't try to bypass the client side check.
> TA Comment fix and Forum enhancement

- site/app/views/forum/ForumThreadView.php
Thanks to @scopeInfinity for pointing this out and providing a solution. Encodes attribute portion of outputted link tag.
> Discussion forum url attribute fix

- .setup/update_database.py
- site/app/controllers/student/TeamController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/submission/TeamView.php
- site/data/course_tables.sql
Closes #1790 
following is video link for my deployment have seek team/partner feature
https://drive.google.com/file/d/15vV4xBwZFe2qE3bzCqWDR22pq0uqeUvc/view?usp=sharing
> add seeking team/partner feature for team assignments

- site/app/controllers/admin/LateController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/views/admin/LateDayView.php
- site/public/js/server.js
Closes  #1848 
Task
- Added delete entry option
- '0' allowed as late date entry
Before deletion
After deleting entry for user `kovaco`
PSQL
> Fixed #1848: Late days allows entries deletion

- .setup/install_system.sh
- .setup/travis/autograder.sh
The previous paths were failing some amount. These are also way cleaner.
> Update download paths for JUnit and Hamcrest

- .setup/CONFIGURE_SUBMITTY.py
A quick fix which prevents the autograding workers json from being deleted when configure submitty is called.
> Stop Autograding Workers JSON from being Overwritten

- site/app/controllers/MiscController.php
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
Where clicking from one mark to another didn't save the previous ones. Also fixed visual glitch with Firefox where mark checkbox would wrap upwards. Also fixed visual issue where current points on opened mark wouldn't display correctly.
> Fixed small mark issues 

- site/app/views/AutoGradingView.php
Hidden points now used in the total score denominator.
> Fixed Total Points Calculation

- site/app/views/grading/ElectronicGraderView.php
> Bugfix: show assigned graders on electronic gradeable grading summary page

- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
Fixes bug where going to next student without closing the mark wouldn't save it.
Fix #1931
> Mark bug fix

- site/app/views/grading/ElectronicGraderView.php
> remove go to next student button

- site/app/views/grading/ElectronicGraderView.php
Had the wrong functions connected to the buttons, but the right functions for the keys. Kind of interesting how that happened.
> Fix the grading buttons showing the wrong panels

- .setup/data/users/developer.yml
- .setup/update_database.py
- site/app/models/User.php
- site/app/views/GlobalView.php
- site/data/course_tables.sql
- site/data/submitty_db.sql
- site/public/css/server.css
- site/public/js/server.js
- site/tests/app/models/UserTester.php
The group is no longer necessary. The only thing it was controlling is now just shown/not-shown based on whether or not Debug mode is on (or not).
Closes #2006
> Remove developer group from Submitty

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
Gets rid of the unnecessary pushd/popd as we can just set the working directory via flag
> Simplify composer install line in helper

- site/app/controllers/admin/UsersController.php
- site/app/views/admin/UsersView.php
> Fix section lists on create/edit user form

- site/app/views/NavigationView.php
> Don't show delete button to non-admins users

- .setup/distro_setup/debian/setup_distro.sh
- .setup/distro_setup/ubuntu/setup_distro.sh
> Install SQLite driver for PHP for Vagrant

- site/app/templates/forum/EditPostForm.twig
- site/app/templates/forum/MergeThreadsForm.twig
- site/app/templates/grading/electronic/NewMarkForm.twig
- site/app/templates/grading/simple/StatisticsForm.twig
- site/app/templates/navigation/DeleteGradeableForm.twig
- site/app/views/NavigationView.php
- site/app/views/forum/ForumThreadView.php
- site/app/views/grading/ElectronicGraderView.php
- site/app/views/grading/SimpleGraderView.php
Including,
- New Mark
- Delete Gradeable
- Numeric/Checkpoint statistics
- Edit forum post
- Merge threads
> Twig all the dialogs

- .setup/CONFIGURE_SUBMITTY.py
- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/INSTALL_SUBMITTY_HELPER_BIN.sh
- .setup/bin/partial_reset.py
- .setup/bin/setup_sample_courses.py
- .setup/bin/update_repos.py
- .setup/common/common_env.sh
- .setup/data/courses.yml
- .setup/install_system.sh
- .setup/travis/autograder.sh
- .setup/travis/setup_test_suite.sh
- .setup/vagrant/setup_vagrant.sh
- .travis.yml
- Docs/sample_bin/admin_scripts_setup
- Vagrantfile
- migration/migrator.py
- sbin/anonymize_autograding_logs.py
- sbin/count_autograding_logs.py
- sbin/replay_experiment_script.sh
- site/app/libraries/Core.php
The developer must have the Submitty/Submitty repository checked out.
We assume this path is  <SOMETHING>/GIT_SUBMITTY
This folder is shared.
If the developer also has Submitty/Lichen (named <SOMETHING>/GIT_LICHEN)
If the developer also has Submitty/AnalysisTools (named <SOMETHING>/GIT_ANALYSIS_TOOLS)
If the developer also has Submitty/Tutorial (named <SOMETHING>/GIT_TUTORIAL)
These additional folders will also be shared.
We can discuss the naming conventions.
> Share additional repos between host & vagrant

- site/app/templates/grading/electronic/Status.twig
- site/app/views/grading/ElectronicGraderView.php
Need to make sure this works both for team and non-team assignments in as many cases as possible.
> Twig grading status page

- site/app/templates/grading/electronic/ErrorMessage.twig
- site/app/templates/grading/electronic/NavigationBar.twig
- site/app/templates/grading/electronic/RubricPanel.twig
- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading.js
These are the only ones that are immediately twiggable. The others have pending PRs or use other views that need to be twigged first.
This is going to merge conflict pretty badly with #2097 so that should be merged first if possible.
> Twig some of the grading rubric panels

- site/app/controllers/grading/ElectronicGraderController.php
- `$return_url` being used before defined
- `addErrorMEssage`
- Using `$this` in a static function
- `addOneMark` trying to use variables it doesn't have
> Fix a few errors in ElectronicGraderController

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/travis/autograder.sh
Require Lichen version v.18.06.00 (minimum)
> Lichen repo version & Lichen installation

- .setup/bin/setup_sample_courses.py
- .setup/data/courses/tutorial.yml
> Teamless people can no longer submit & Optimize # versions

- .setup/update_database.py
- migration/migrator.py
> Fix update_database.py marking all migrations as being done, not just initial

- site/app/controllers/admin/AdminGradeableController.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
- site/app/templates/admin/admin_gradeable/rubric/ElectronicFileRubric.twig
The pdf pages option is still buggy, it does not save the boolean or the instructor specified page numbers.
But I've fixed the crash error below:
@KevinMackenzie please fix the saving error.
---------------
BadMethodCallException (Code: 0) thrown in /usr/local/submitty/site/app/models/AbstractModel.php (Line 147) by:
throw new \BadMethodCallException('Call to undefined method '.__CLASS__.'::'.$name.'()');
Message:
Call to undefined method app\models\AbstractModel::setPdfPage()
Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/PostgresqlDatabaseQueries.php(739): app\models\AbstractModel->__call('setPdfPage', Array)
#1 /usr/local/submitty/site/app/controllers/admin/AdminGradeableController.php(118): app\libraries\database\PostgresqlDatabaseQueries->getGradeableInfo('quiz02', …
> TA grading PdfPage crash & failure to save

- .setup/update_database.py
BUGFIX: Deleted wrong two lines from update_database.py in PR #2199
> BUGFIX: Deleted wrong two lines from update_database.py in PR #2199

- site/public/js/ta-grading-mark.js
Closes #2071 
After a mark is added, the marks will be saved.
> Save Added Marks on popup close

- site/app/controllers/admin/AdminGradeableController.php
- site/app/models/AdminGradeable.php
> Fix broken quick links

- site/app/templates/grading/electronic/Details.twig
> Display Full Names of Students Without Teams on Teams Details Page

- .setup/bin/code_watcher.py
- site/app/templates/forum/ThreadPostForm.twig
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
Issue: #2201 
- Dynamic size of the reply box according to text and tabs working within _textarea_
- CodeWatcher Bug Fix
> Forum Reply Box Enhancements

- site/app/templates/grading/simple/Display.twig
- site/app/views/grading/SimpleGraderView.php
Looks like the twig PR made the registration/rotating section PR confused and it filled the code full of syntax errors. This should fix that.
> Fix bad merge of simple grader view

- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
Closes : #2227 (Replying to Deleted Forum Posts)
> Forum, Handle Dangling Posts on Creation

- site/public/js/ta-grading-mark.js
Now TA Grade will not clamp at 0, and the total grade will clamp at 0.
Closes #2155
> Fixes clamping

- site/app/controllers/student/SubmissionController.php
- site/tests/BaseUnitTest.php
- site/tests/app/controllers/submission/SubmissionControllerTester.php
Adds permissions checks to prevent students from editing things they shouldn't.
closes #2222
> Closes submission permissions loopholes

- site/app/templates/grading/electronic/SubmissionPanel.twig
> Fixing Submission Panel popup links

- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- Vagrantfile
Closes #2115 
When this gets merged, everyone should delete their vagrant machine and then merge or else they'll be left with an orphan VM that they have to open VirtualBox to delete.
> [WIP] Add Ubuntu 18.04 (bionic) install target

- .setup/bin/setup_sample_courses.py
Added random sample data for lab and tests.
* No grades for future/beta
* Less grades for closed
* More grades for grades available
* One (random) section with no grades
closes #2167
> Sample Data for Simple Gradeables

- site/app/libraries/database/DatabaseQueries.php
On turning on show deleted thread
Don't show merged thread in display thread list else it raises an exception on `getFirstPostForThread()`
> Forum: Bug Fix for show deleted thread

- site/app/templates/Navigation.twig
- tests/e2e/base_testcase.py
- tests/e2e/test_simple_grader.py
Added selenium test cases for those cases outlined in #2173 :
* Rotating and Registration header checks
* Section ordering check
Also:
* Added functionality to BaseTestCase
* Created template for writing templates for simple grader test cases
* Slight changes to nav page to make locating buttons easier
closes #2173
> Basic E2E Test Cases for SimpleGrader

- Vagrantfile
> Fix ubuntu 18.04 spinning up on default vagrant up

- site/app/templates/Authentication.twig
Changes to be committed:
modified:   site/app/templates/Authentication.twig
Corrected label for "Stay Logged In" checkbox.
> VPAT authentication view (label quickfix)

- site/app/views/submission/HomeworkView.php
> Late day extension fix

- .setup/apache/submitty.conf
- .setup/apache/submitty_http.conf
- .setup/distro_setup/debian/jessie/setup_distro.sh
- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- .setup/distro_setup/ubuntu/xenial/setup_distro.sh
- .setup/install_system.sh
- .setup/php7.0-fpm/pool.d/submitty.conf
- .setup/vagrant/sites-available/submitty.conf
This reverts commit ccf5fb7988f5f7309020b52ef2c0d8a7745fce7e.
> Revert "Finish up initial work for Ubuntu 18.04 support (#2292)"

- migration/migrations/course/20180704185837_lichen_photos_directory_owner.py
- migration/migrations/system/20180703000000_change_system_user_names.py
- site/app/controllers/admin/ConfigurationController.php
- site/app/models/Config.php
- site/app/templates/admin/Configuration.twig
- site/app/views/admin/AdminGradeableView.php
- site/config/course_template.ini
Also redo directory ownership in the case that the system user name change migration is out of order.
> Rename private_repository variable (& set default value)

- .setup/bin/partial_reset.py
- .setup/bin/setup_sample_courses.py
> Patch partial reset

- .setup/bin/recreate_sample_courses.sh
- .setup/data/users/grader.yml
- .setup/data/users/grader2.yml
The sample `grader` user now has two grading sections. Also I've added another grader, `grader2` who has nobody to grade so we can test that as well.
Also added bonus is a recreate_sample_course.py that runs partial_reset and setup_sample_course automatically, for convenience.
Closes #2302
> Sample grader sections

- site/public/js/ta-grading.js
> Fixed hotkeys not finding the right checkbox

- .setup/data/courses/development.yml
- .setup/data/courses/sample.yml
Very minor change to make the lives of those looking for a specific gradeable in the coure yml files easier.
> Reordered sample course yml files to make easier to read

- site/app/libraries/FileUtils.php
This was causing errors in the image uploads
> Fixed missing $ in FileUtils

- site/app/templates/grading/electronic/NavigationBar.twig
- site/app/templates/grading/electronic/RubricPanel.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/ta-grading-mark.js
- site/public/js/ta-grading.js
Closes #2377
This discussion summerizes the issue and changes https://github.com/Submitty/Submitty/issues/2377
> No manual grading panel bug

- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/Gradeable.php
- site/app/models/GradingSection.php
- site/app/models/Team.php
- site/app/templates/grading/electronic/Details.twig
- site/app/views/NavigationView.php
- site/app/views/grading/ElectronicGraderView.php
Part 1 of probably 2 on #2272
- Add GradingSection model to clean up section checks
- Moving nav page progress bar code into the model (and make it work for teams)
- Add list of `User`s to `Team`s
- Move team history loading into model
- Move page number calculation into model
> Move logic into model

- .setup/travis/autograder.sh
- .setup/travis/before_install.sh
- .setup/travis/setup.sh
- .setup/travis/setup_test_suite.sh
- .travis.yml
This will cause Travis to fail earlier if any of its specific scripts raise an error (making the bash scripts act the same as commands run straight in the .travis.yml file.
> Add set flag to travis bash scripts

- .setup/install_system.sh
Closes #2125, can expand list of variables set as we feel necessary.
> Add convenience variables for vagrant ssh

- .setup/bin/recreate_sample_courses.sh
Otherwise it tries to keep going and causes a bunch of confusion
> Abort recreate_sample_courses.sh if any command fails

- migration/migrations/course/20180718124004_course_materials_directory.py
Forgot to do this in #2433 
closes #2465
> Add migration for course materials directory

- site/app/libraries/Access.php
- site/app/views/NavigationView.php
And make sure TA has access to view submissions
> Add view submissions buttons to nav page for ta

- site/app/controllers/HomePageController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/templates/HomePage.twig
- site/app/views/HomePageView.php
Changes how archived courses are displayed by making a new "Your Archived Courses" section under the "Your Courses" section on the homepage.
Also, changed the ordering of courses when retrieving from the database.
closes #2413
> Change display of archived courses for instructor

- site/app/models/gradeable/AutoGradedTestcase.php
- site/app/models/gradeable/AutoGradedVersion.php
- site/app/models/gradeable/AutoGradedVersionHistory.php
- site/app/models/gradeable/AutogradingConfig.php
- site/app/models/gradeable/Component.php
- site/app/models/gradeable/Gradeable.php
- site/app/models/gradeable/GradedComponent.php
- site/app/models/gradeable/GradedGradeable.php
- site/app/models/gradeable/SubmissionTextBox.php
- site/app/models/gradeable/TaGradedGradeable.php
Accumulated helper methods for the new Gradeable model.  Most of these were in the old model and needed to be put somewhere in the new model.  Other helper methods extract code out of existing methods and puts them in better places.  These changes should not affect how any existing functions behave.
> Misc helper methods for new Gradeable Model

- .setup/travis/before_install.sh
- .travis.yml
Travis has switched to using pyenv for setting the python version and such and so we no longer need to do some amount of the path stuff we were doing to set that path manually within $PATH.
> Simplify the path manipulations within Travis

- site/app/templates/GlobalHeader.twig
- site/public/css/server.css
Makes it so that the header breadcrumbs no longer automatically go underneath the submitty logo when there is not enough space on the line
closes #2491
> Fix header divs stacking

- site/app/controllers/admin/UsersController.php
No longer fails to add user when they already exist on the master database.
closes #2503
> Fixed user exists bug and added new success messages

- .setup/bin/setup_sample_courses.py
- .travis.yml
And use this flag on Travis where we never use the submissions to save a couple minutes in build time.
> Add no_submissions flag to setup_sample_coures to skip making submissions

- site/app/controllers/admin/AdminGradeableController.php
- site/app/models/Button.php
- site/app/templates/Navigation.twig
- site/app/views/NavigationView.php
- site/public/css/server.css
Makes the nav page "Open to XXX" buttons smaller and their text smaller. 
Also adds both success and error messages that pop up in response to the buttons being pressed indicating whether or not they were successful.
closes #2463
> Change look and response of "Open to XXX" buttons on nav page

- site/app/controllers/admin/AdminGradeableController.php
- site/app/templates/grading/electronic/Details.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/css/server.css
Replaces text on electronic grader details page with buttons colored based on who has graded them.
implements some functionality for #2441 
~~Still need to fix the buttons linebreaking~~
> Electronic grader display page grade buttons

- site/app/controllers/student/SubmissionController.php
- site/app/models/Gradeable.php
- site/app/models/gradeable/Gradeable.php
- site/app/models/gradeable/TaGradedGradeable.php
- site/app/templates/admin/Configuration.twig
- site/app/templates/grading/electronic/RegradePanel.twig
- site/app/views/NavigationView.php
- site/public/js/ta-grading.js
> Regrade minor improvements

- site/public/js/ta-grading-mark.js
> Fix marks showing wrong index on add/delete

- site/app/templates/admin/users/MoreExtensions.twig
- site/app/templates/forum/CategoriesForm.twig
- site/app/templates/forum/FilterForm.twig
- site/app/templates/forum/ThreadPostForm.twig
- site/app/templates/generic/Popup.twig
- site/app/templates/submission/homework/PreviousSubmissionForm.twig
- site/app/templates/submission/homework/SubmitBox.twig
- site/public/css/server.css
- site/public/js/drag-and-drop.js
- site/public/js/server.js
- Clicking the background will now close the popup (if it has a close button), Closes #2501
- Previous Version form was in fact a jQuery dialog and not a popup, Closes #2252
- Consistent placement of primary action button in the corner
- Make the buttons wider so they are all the same width
> Popup fixes and changes

- site/public/css/server.css
Removes the sidescroll from the page.
closes #2534
> Removed sidescroll

- site/public/js/ta-grading-mark.js
- site/public/templates/grading/Mark.twig
They were broken with the update for mark check numbers. Also now the numbers reorder correctly. Closes #2552
> Fix reordering marks

- site/app/models/Button.php
- site/app/templates/GlobalFooter.twig
- site/app/templates/Navigation.twig
- site/app/views/NavigationView.php
- site/tests/app/models/ButtonTester.php
Adds accessibility to font awesome links by adding aria-* attributes.
addresses #2311
> VPAT Empty link error

- site/public/js/ta-grading-mark.js
- site/public/js/ta-grading.js
- site/public/templates/grading/Mark.twig
Closes #2563 
Please don't merge before Travis
> Grading disabled in edit mode

- site/app/controllers/MiscController.php
Half of the code was using $_GET and the other half $_REQUEST. This caused some inconsistent behavior.
> Fix misc controller using GET variables in a POST request

- site/app/libraries/database/DatabaseQueries.php
ordering was:
1
10
2
3
now it's fixed.
closes #2481
> Fixed ordering on status page

- site/app/views/admin/PlagiarismView.php
> Plagiarism mainpage queue and running status

- site/app/controllers/MiscController.php
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/pdf-annotate.js
Now multiple graders can grade the same document.
> Multiple graders for PDF annotations

- site/app/controllers/student/SubmissionController.php
- site/app/templates/submission/homework/SubmitBox.twig
- site/app/views/submission/HomeworkView.php
- site/tests/app/controllers/submission/SubmissionControllerTester.php
Limited access graders can no longer bulk upload, and the grader upload interface and unit tests have been updated accordingly.
closes #2587
> Removed limited access grader bulk upload

- site/app/views/admin/PlagiarismView.php
> add top match and highest match percentage to lichen

- .gitignore
- site/app/controllers/grading/ElectronicGraderController.php
- site/app/controllers/student/PDFController.php
- site/app/models/PDFGenerator.php
- site/app/templates/autograding/TAResults.twig
- site/app/templates/autograding/TAResultsNew.twig
- site/app/templates/grading/electronic/PDFAnnotationBar.twig
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/app/views/AutoGradingView.php
- site/app/views/PDFView.php
- site/app/views/submission/HomeworkView.php
- site/composer.json
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFStudentView.js
Now zoom and rotation are saved in local storage.
> Added rotation and bug fixes

- .setup/CONFIGURE_SUBMITTY.py
- .setup/install_system.sh
(And allow for re-run of install_system.sh)
os.rename does not work if the files are on different partitions
clarify that submitty_dbuser does not need to be a full linux user, but is just a postgres role
> Debugging the installation on production machine

- migration/migrations/course/20180730152916_grades_due_date.py
Forgot to push this commit before merging #2613
> [BugFix] Drop constraint if exists (fixing #2613) 

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/templates/grading/electronic/PDFAnnotationBar.twig
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/public/css/pdf/toolbar_embedded.css
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/pdf-annotate.js
This change complements the changes in the pdf-annotate.js repo. Fixes bunch of bugs. However, this still uses the old method of building the other repo, but it works.
EDIT: Eraser is also included in this PR since it's kind of related.
> multiple graders fix and eraser

- site/app/views/LateDaysTableView.php
Addresses #2666
But leaving that open because there's a big todo in this code.
> Hide gradeables you aren't allowed to see in the late days view

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .travis.yml
This better follows the current best practices of the python ecosystem
> Use pip to install local package instead of setup.py

- more_autograding_examples/left_right_exam_seating/config/config.json
- more_autograding_examples/pdf_exam/config/config.json
- more_autograding_examples/upload_only/config/config.json
- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
- site/app/controllers/admin/AdminGradeableController.php
- site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
Fixes #2681 (wasn't doing a --clean)
handles most of #2682 (UI improvements), but let's leave this open for more feedback/discussion
> Force clean gradeable rebuild, UI improvements

- .setup/bin/update_repos.sh
- sbin/autograder/grade_item_main_runner.py
This PR splits the knownhosts.csv into knownhosts_tcp.csv and knownhosts_udp.csv.
Changes to the default router are incoming in another PR.
> Enable UDP Connections When Grading Networked Programs

- .setup/Dockerfile
- .setup/install_system.sh
- grading/CMakeLists.txt
- grading/Sample_CMakeLists.txt
- grading/main_compile.cpp
- site/app/templates/GlobalFooter.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
- site/app/views/submission/HomeworkView.php
--network=host flag on docker build may be necessary for systems with a firewall
removing boost from grading code is necessary for ubuntu 18.04
update footer date
Also fix some team git stuff, and clean up the git instructor onsite docs
> Debug docker

- site/app/templates/error/UnbuiltGradeable.twig
- site/app/views/submission/HomeworkView.php
Closes #2770 
The function that displayed this 'unbuilt gradeable' message on the submit page has been updated to use the new gradeable model's function names.
> Fixed unbuilt gradeable message on submission page

- migration/migrations/course/20180827142903_course_materials_permissions.py
> fix permissions on course_materials uploads directory

- site/app/views/forum/ForumThreadView.php
> Forum: Thread status cookie bug fix

- site/app/templates/error/NoAccessCourse.twig
- tests/e2e/test_login.py
> Minor Grammar Revision to Error

- site/app/controllers/forum/ForumController.php
- site/app/templates/forum/EditPostForm.twig
- site/app/templates/forum/ThreadPostForm.twig
- site/public/js/server.js
> Forum various fixes

- site/app/controllers/grading/ElectronicGraderController.php
Closes #2819 
This was commented out in the big PR overhauling this interface and didn't get un-commented
> Readded Ta grading popup

- .setup/INSTALL_SUBMITTY_HELPER.sh
Removes a few lines that were causing worker installation to fail.
> Worker Installation Fix

- site/app/controllers/student/PDFController.php
- site/app/templates/autograding/TAResultsNew.twig
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/app/views/AutoGradingView.php
- site/app/views/PDFView.php
- site/public/js/pdf/PDFStudentView.js
Now, only PDFs with annotations will show up in the TA result box (Student can still download other files in the Auto result box). Also there are some bug fixes and performance improvements.
> Pdf student UI improvement and bug fixes

- site/public/js/ta-grading-rubric.js
Closes #2807 
When pressing the 'add new component' button, the open components will be saved and the newly added component will be opened.
> Add New Component saves opened components

- site/app/controllers/student/SubmissionController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
- site/app/models/gradeable/Gradeable.php
- site/app/models/gradeable/GradedGradeable.php
- site/app/models/gradeable/RegradeRequest.php
- site/app/templates/grading/electronic/RegradePanel.twig
- site/app/templates/submission/homework/RegradeBox.twig
- site/app/templates/submission/regrade/Discussion.twig
- site/app/views/NavigationView.php
- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/HomeworkView.php
- site/public/js/server.js
The homework / submission view and the electronic grader view now use the new gradeable model for displaying regrade requests.  The controller layer for handling regrade request requests also uses the new model. This also closes #2335
> Regrade requests use new model in Student and Grader view

- site/app/views/grading/SimpleGraderView.php
Fixed issue where View All and View Your Sections wouldn't work with SimpleGraderViews
Code was copied from the functioning ElectronicGraderView.
fixes part of #2818
> Fixes "View All"/"View Your Sections" issue

- site/app/views/forum/ForumThreadView.php
> Fixes forum chronological bug

- site/app/controllers/GlobalController.php
- site/app/controllers/admin/WrapperController.php
- site/app/templates/admin/UploadWrapperForm.twig
- site/public/css/server.css
Closes #2804 and also adds the ability to upload sidebar.json directly from the Customize Website Theme page.
> Fix sidebar links not expanding vertically

- site/app/controllers/MiscController.php
- site/app/libraries/Access.php
- site/app/models/gradeable/AutoGradedGradeable.php
Happens because the controller doesn't pass which version to download, but having a version number is required.
> Fix "download all files" throwing an error

- site/public/js/ta-grading-rubric.js
Re-addresses the problem of grader theft and accounts properly for cases of ungraded components.
> Proper fix for preventing grader theft

- .setup/INSTALL_SUBMITTY_HELPER.sh
- bin/calculate_extensions.cpp
> Add helper program to calculate early submission incentive extensions

- .travis.yml
Closes #2409
An example failing build that starts with [WIP]: https://travis-ci.org/Submitty/Submitty/jobs/428672315
> Add WIP job for Travis-CI for PRs

- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
Uses regex to determine code blocks in posts.
> More robust [code] parsing

- site/app/controllers/forum/ForumController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
Closes #2795. Adds a resolve button to the thread which teaching staff and original creator can see.
> Resolve thread button

- .setup/distro_setup/ubuntu/rpi.sh
- grading/seccomp_functions.cpp
- more_autograding_examples/test_notes_upload/config/config.json
update allowed system calls for /bin/mv on 18.04
& update installation for pdflatex 
& debug config for test case isolation
> Fix test notes page upload

- site/app/controllers/grading/SimpleGraderController.php
- site/app/views/grading/SimpleGraderView.php
The print lab page was not sorting, now it is sorting based on the way the grading page linking to it was sorted.
closes #2878
> Created default sort option for the print lab page

- grading/TestCase.h
- grading/main_validator.cpp
- more_autograding_examples/cpp_cats/config/config.json
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_allCorrect
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_columnSpacingOff
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_extraLinesAtEnd
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_extraSpacesAtEnd
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_frontSpacingOff
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_lineOrderOff
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_spacingOff
- tests/integrationTests/tests/cpp_cats/validation/grade.txt_spellingOff
- tests/integrationTests/tests/cpp_cats/validation/results.json_allCorrect
- tests/integrationTests/tests/cpp_cats/validation/results.json_columnSpacingOff
- tests/integrationTests/tests/cpp_cats/validation/results.json_extraLinesAtEnd
- tests/integrationTests/tests/cpp_cats/validation/results.json_extraSpacesAtEnd
- tests/integrationTests/tests/cpp_cats/validation/results.json_frontSpacingOff
- tests/integrationTests/tests/cpp_cats/validation/results.json_lineOrderOff
- tests/integrationTests/tests/cpp_cats/validation/results.json_spacingOff
- tests/integrationTests/tests/cpp_cats/validation/results.json_spellingOff
> Add partial_credit  = false option for autograding

- site/app/templates/ChangePasswordForm.twig
- site/app/templates/EditNameForm.twig
Changed files:
site/app/templates/ChangePasswordForm.twig
site/app/templates/EditNameForm.twig
Adjustments for `<label>` and `<aria-label>`
> VPAT -- Homepage

- site/app/templates/admin/users/ClassListForm.twig
- site/app/templates/admin/users/DownloadForm.twig
- site/app/templates/admin/users/StudentList.twig
- site/app/templates/admin/users/UserForm.twig
Changed files:
site/app/templates/admin/users/ClassListForm.twig
site/app/templates/admin/users/DownloadForm.twig
site/app/templates/admin/users/StudentList.twig
site/app/templates/admin/users/UserForm.twig
Adjustments for `<label>` and `<aria-label>`
> VPAT -- Manage Students

- site/app/templates/admin/users/RotatingSectionsForm.twig
Changed file:
site/app/templates/admin/users/RotatingSectionsForm.twig
This form covers both registration sections and rotating sections.
Adjustments for `<label>` and `<fieldset>`/`<legend>`
> VPAT -- Manage Sections

- site/app/templates/admin/users/GraderList.twig
- site/app/templates/admin/users/GraderListForm.twig
Changed files:
site/app/templates/admin/users/GraderList.twig
site/app/templates/admin/users/GraderListForm.twig
Adjustments for `<aria-label>`
> VPAT -- Manage Graders

- site/public/css/server.css
This PR fixes a minor bug caused by my last branch PR #2899 where the forum would have extra overflow for longer posts. 
This should fix that and also still make long request regrades still wrap in the grader view.
> Fix overflow issue on forum

- site/app/controllers/grading/SimpleGraderController.php
Also supports user_preferred_lastname per #2740
> Sort by user_preferred_firstname if available

- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/GradingComponentHeader.twig
- site/public/templates/grading/GradingGradeable.twig
Added proper undefined checks for the graded component and fixed default values assigned to the `graded_version`
> Fixed 'version conflict' message showing when it shouldn't

- site/app/templates/admin/Configuration.twig
- site/app/templates/admin/UploadWrapperForm.twig
VPAT adjustments for Course Configuration pages.
> VPAT -- Course Configuration

- site/app/templates/admin/Extensions.twig
VPAT adjustments with `<label>`, `Submit` button, data table (note that a `<caption>` is expected, even when the caption is empty), and `aria-labelledby` for file upload control.
> VPAT -- excused absences

- site/app/templates/admin/LateDays.twig
VPAT adjustments for `<label>`, `Submit` button, data table (note that a `<caption>` is expected, even when empty), `aria-label`, and `aria-labelledby`.
> VPAT -- late days

- site/app/controllers/MiscController.php
- site/app/controllers/pdf/PDFController.php
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFInitToolbar.js
This is quite a big problem. Right now, team assignments using the pdf annotator does not work at all. This PR should fix that. These changes make the code really ugly, so another refactor will be coming up shortly that will support teams better.
closes #2903
> PDF annotation and viewing now supports teams

- site/app/libraries/Access.php
- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/app/views/submission/HomeworkView.php
They were being treated as instructor-only uploads. Closes #2941
> Fix full access graders not having access to pdf covers

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
For team rotating assignments, graders were not displaying for sections you were not assigned to grade. Now they are.
closes #2875
> Displaying graders for team rotating

- site/cgi-bin/pdf_check.cgi
Credit to RPISEC for pointing this out to us.
> Fix path bug in pdf_check.cgi

- site/app/controllers/admin/AdminGradeableController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/templates/admin/admin_gradeable/AdminGradeableGraders.twig
> Use full name on grader assignment page

- site/app/views/grading/ElectronicGraderView.php
- site/app/views/submission/HomeworkView.php
Graders will be able to open the regrade request box whenever regrades are allowed in a gradeable and course. They can also start the discussion also now.
Closes #2933
> Allow TAs/Instructors to open a regrade request discussion with students

- site/app/controllers/student/TeamController.php
- site/app/templates/submission/Team.twig
- site/app/views/submission/TeamView.php
Part of #2317 
This converts the team creation / management page to use the new gradeable model.  This is one of the more trivial conversions.
> Team controller uses new gradeable model

- site/app/controllers/admin/GradeableController.php
Part of #2317
updates the gradeable config upload page to use the new model.  This is a fairly trivial conversion.
> Gradeable config upload page uses new gradeable model

- site/app/controllers/MiscController.php
- site/app/templates/misc/Code.twig
- site/app/views/MiscView.php
Should format CodeMirror blocks better in the TA Grading portal.
Closes #2874 
Closes #2921
> Should fix the inconsistent code display

- more_autograding_examples/test_notes_upload/config/config.json
- more_autograding_examples/test_notes_upload/config/test_input/test_template.tex
was broken by test case isolation changes
> [Bugfix] test notes page autograding

- site/app/controllers/MiscController.php
Some functions were using the wrong path variable and bypassing access permission checks. Also encodePDF just wasn't checking anything at all.
> Fix misc controller file path inconsistency

- site/app/models/gradeable/AutoGradedVersion.php
- site/app/views/grading/ElectronicGraderView.php
Fixed bug where results folder for autograding and VCS checkout folder were not showing in submission panel.
Fix #2995
> Submission panel results bug

- site/app/templates/EditNameForm.twig
- site/app/views/HomePageView.php
> Added default values to change preferred name

- site/app/models/gradeable/AutoGradedVersionHistory.php
- site/app/templates/submission/homework/CurrentVersionResults.twig
- site/app/views/submission/HomeworkView.php
Uses the timestamp from the history.json file.
closes #2981
> Possible fix for submission timestamps

- site/app/templates/admin/Configuration.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
- site/app/templates/grading/electronic/AutogradingPanel.twig
- site/app/templates/grading/electronic/NavigationBar.twig
- site/app/templates/grading/electronic/Status.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/css/admin-gradeable.css
- site/public/css/server.css
- site/public/templates/grading/TotalScoreBox.twig
Updated a few different points on UI.
> Small UI Tweaks

- .setup/INSTALL_SUBMITTY_HELPER.sh
- grading/load_config_json.cpp
- grading/python/submitty_router.py
- sbin/autograder/grade_item_main_runner.py
Closes #3037 
Adds default router to the system. Automatically pulls it in if ```use_router``` is enabled but a router container has not been specified. Does not pull in if a router is specified but no code is included.
> Add default Router

- site/app/controllers/pdf/PDFController.php
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/app/templates/grading/electronic/SubmissionPanel.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/css/pdf/pdf_embedded.css
- site/public/css/pdf/pdf_viewer.css
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFInitToolbar.js
Tested with multiple pdfs, now saving and zoom with not interfere among pdfs. Also refactored some of the CSS
> Fixed zoom and save problem with multiple pdfs

- site/public/css/diff-viewer.css
> Monospace issue

- site/app/controllers/admin/UsersController.php
- site/app/templates/admin/users/RotatingSectionsForm.twig
> added feature so rotating sections can exclude registration sections

- site/public/css/server.css
> fix the height of the forum

- .setup/INSTALL_SUBMITTY_HELPER.sh
> Fix permissions for autograding

- site/app/templates/course/CourseMaterials.twig
No longer open pdfs and other files in that weird pdf window thing
#closes #3002
> Course Materials open in new tab by deafault

- bin/build_homework_function.sh
> [Bugfix] Autograding build: fix permissions on cmake or make failure

- site/app/models/gradeable/AutoGradedVersion.php
- site/app/templates/forum/MergeThreadsForm.twig
- tests/e2e/test_forum.py
And a missing return statement (might fix a NaN)
> Change button text 'submit'->'merge thread'

- site/cgi-bin/pdf_check_qr.cgi
> [WIP] QR Codes 2.0

- site/app/templates/grading/electronic/Details.twig
> Fixed line wrapping bug

- site/public/js/pdf/PDFAnnotateEmbedded.js
Now it will let you scroll pdf without having to wait for the entire test to render.
> fixed can't scroll vertical problem

- sbin/autograder/grade_item.py
- sbin/autograder/grade_item_main_runner.py
- sbin/submitty_autograding_worker.py
Validation container is no longer created before compilation.
> Limit scope of validation container.

- site/app/models/Gradeable.php
Fixed the bug in the "My late days" table unsubmitted status #3106 . Just a small change. 
close #3106.
> Fixed bug in "My late days" table unsubmitted status

- site/public/js/ta-grading-rubric.js
- site/public/js/ta-grading.js
> Scroll components to be visible on change student

- .setup/distro_setup/setup_distro.sh
- .setup/distro_setup/ubuntu/rpi.sh
This makes pip available for the extra package setup scripts
> Install pip after running setup_distro

- site/app/libraries/database/DatabaseQueries.php
This sorts the status by date, so it should fix the calculation with earn/loss lateday.
> Fixed sorting for late day status for table

- AUTHORS.md
- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
Credit for bug report to Matt Raneri
> Replace subprocess.call with remove/rmtree in Lichen code

- .setup/bin/versions.sh
- site/app/controllers/admin/PlagiarismController.php
- site/app/views/admin/PlagiarismView.php
Changes all occurrences of `regrex` -> `regex` in the plagiarism controller and view. This is to be merged prior to the `regex_concat` branch in the Lichen repo.
> Converts regrex -> regex in plagiarism controller/view

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
Completely didn't work for rotating sections. Not sure how it broke so badly I feel like I was re-writing some things there but it's fixed now.
Fix #3150
> Fixed "who got this mark" queries

- .setup/INSTALL_SUBMITTY_HELPER.sh
- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
There was an apt package that had a bug, but the default vagrant install doesn't have the updated version. So, this fixes that.
> Fix networking on vagrant machines

- site/app/models/Gradeable.php
- site/app/templates/grading/electronic/Details.twig
- site/app/views/grading/ElectronicGraderView.php
- site/public/js/server.js
- Show pending invitation on the main view.
- Show pending invitation and Add “Accept” button on the Edit interface (Also change the UI a little bit).
Closes #3085
> Show pending invitation for instructor

- .gitignore
- site/composer.json
- site/composer.lock
Adds a composer.lock file for Submitty
> Add composer lock file for Submitty

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
Fixing request from MasterOdin
> Small syntax change

- AUTHORS.md
Hi, I want to update my name on the vulnerability recognition list
> Update my name in AUTHORS.md

- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
This PR fixes the display icon for pinning a thread.
> Fix discussion forum thumbtack display

- grading/execute.cpp
- grading/window_utils.cpp
- grading/window_utils.h
1.  Actions in graphics applications now fail gracefully if a window does not exist, and are retried until testcase timeout or success.    
2.  Mouse movement no longer hangs when the mouse is moved zero pixels.
3.  A default delay of 1/10th of a second has been added between window detection time and the first action. This allows ```wmctrl``` time to accurately detect a window's starting location.  
4.  In appropriate assignments, an instructor delay should no longer be necessary as the first action of a testcase.
> Graphics Grading Performance Improvements

- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- migration/migrations/course/20190123000000_seating_permissions.py
- sbin/create_course.sh
* move a 'apt-get update'
* fix group write permissions on uploads/seating
> [bugfix] vagrant install script update & uploads/seating permissions

- site/cgi-bin/pdf_check_qr.cgi
This PR fixes the page count after using bulk qr code and also handles when one or more files don't contain any qr codes
> QR Bulk upload improvements

- site/app/controllers/student/SubmissionController.php
- site/public/js/drag-and-drop.js
Makes it clearer to instructors what's happening in #3208.
> Add message to indicate max number of uploaded files when uploading student photos

- more_autograding_examples/test_notes_upload/config/config.json
- more_autograding_examples/test_notes_upload/config/test_input/blank_page.tex
- more_autograding_examples/test_notes_upload/config/test_input/separate_pages.py
- more_autograding_examples/test_notes_upload/config/test_input/test_template.tex
- more_autograding_examples/test_notes_upload_3page/config/config.json
- more_autograding_examples/test_notes_upload_3page/config/test_input/blank_page.tex
- more_autograding_examples/test_notes_upload_3page/config/test_input/separate_pages.py
- more_autograding_examples/test_notes_upload_3page/config/test_input/test_template.tex
Allow students to upload pdf with fewer than the maximum number of allowed pages
and tweak wording
> Student-Uploaded Notes for Exams

- grading/myersDiff.cpp
Fixes a parsing error which caused image diff to fail for very similar images.
> Image Diff Precision Update

- site/app/templates/GlobalHeader.twig
- site/public/css/server.css
> Add warning to user if JavaScript is disabled

- site/app/views/submission/HomeworkView.php
Added missing null check for regrade request, which caused page to crash
> Fixed instructor accessing submit page without team

- .setup/bin/update_codemirror.sh
- LICENSE-THIRD-PARTY.md
- grading/execute.cpp
- site/app/views/admin/PlagiarismView.php
- site/public/css/iframe/codemirror.css
- site/public/css/iframe/eclipse.css
- site/public/css/server.css
- site/public/js/iframe/clike.js
- site/public/js/iframe/codemirror.js
- site/public/js/iframe/python.js
- site/public/js/iframe/shell.js
- site/public/js/server.js
This PR updates to the newest version of CodeMirror (Discussion forum and TA grading page both still seem to work with the new version).
> CodeMirror update

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/views/grading/ElectronicGraderView.php
> re-add permission check to verify graders

- sbin/autograder/grade_item_main_runner.py
> [HACK] Hardcode display environment variable

- sbin/submitty_autograding_shipper.py
> Fix syntax error in autograder shipper

- bin/grading_done.py
> Fix syntax error in grading_done

- .setup/distro_setup/debian/jessie/setup_distro.sh
- .setup/distro_setup/setup_distro.sh
- .setup/distro_setup/ubuntu/bionic/setup_distro.sh
- .setup/distro_setup/ubuntu/xenial/setup_distro.sh
> Improve Vagrant MotD to better adjust for different distros

- site/app/templates/autograding/TAResultsNew.twig
- site/public/css/ta-grading.css
- site/public/js/server.js
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/EditComponent.twig
- site/public/templates/grading/GradingComponent.twig
- site/public/templates/grading/Mark.twig
- site/public/templates/grading/OverallComment.twig
part of #2680
Added multiline support for mark titles and improved multiline support for custom marks, overall comments, TA note, and Student note.
> Better multi-line support for TA Grading

- site/app/models/gradeable/Component.php
- site/public/js/ta-grading-rubric.js
- site/public/templates/grading/Component.twig
Closes #1055 
This is my first PR, so any feedback would be greatly appreciated 😄 
When the instructor tries to edit the rubric, the points box will turn red if an invalid point value is entered and the point value is not saved. This should prevent rubrics that lead to the issue above from being created.
> [Bugfix] Make sure points is multiple of precision

- site/app/controllers/GlobalController.php
- site/app/templates/GlobalHeader.twig
- site/app/views/GlobalView.php
- site/app/views/admin/PlagiarismView.php
- site/app/views/forum/ForumThreadView.php
- site/public/css/server.css
**Chrome:**
**Firefox:**
**Safari:**
> Fix overflow of sidebar in full height views

- .setup/bin/input_forum_data.py
Previously the databases were hard coded and this program would crash. It now generates the current semester and takes the courses from within that semester.
> Fix forum population script for any semester

- bin/grading_done.py
now shows stats on the different worker machines...
> Revise grading_done script

- site/app/controllers/grading/ElectronicGraderController.php
Added missing null check to late day info fetch to get late status for gradeable in grading page.
> Added null check to late day status fetch

- site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
> [BugFix] Add missing show() in onChangeNavTab

- site/app/controllers/admin/AdminGradeableController.php
- site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
Removed css inclusion cdn  which caused overriding and shifted js/css inclusion to controller, Closes #3380
> [Bugfix] Fixed CSS overriding on new gradeable page

- .setup/bootstrap.sh
Closes #2233
Documentation updated for this at Submitty/submitty.github.io#63
> Add bootstrap script for easily installing Submitty

- site/app/models/Config.php
- site/tests/app/models/ConfigTester.php
> [Bugfix] Use cgi_url from config file if non-empty else build from base_url

- migration/migrator/migrations/system/20190324065300_cgi_url.py
Should be merged with PR #3397.
> Default CGI Migration

- site/app/controllers/admin/AdminGradeableController.php
- site/app/views/grading/ElectronicGraderView.php
This PR fixes an issue where an exception was being thrown when users weren't selecting to have a discussion component in their gradeable.
> Fix discussion gradeables

- site/app/views/forum/ForumThreadView.php
This resolves the issue that prevented a user from unpinning a thread. ~Haven't tested when viewing in grading portal. Will test that after dinner and update this thread.~
> Fix pinning as favorite feature on discussion forum

- site/app/views/forum/ForumThreadView.php
Closes #3510 
The changes were correct in https://github.com/Submitty/Submitty/commit/eb59f91c1452481afc1a1d442c09ce0a597a6639, but was somehow partially changed in later commits, leading to the error.
Thank @Fenn-CS for pointing it out.
> Fix undefined variable $show_deleted_thread_title

- site/app/controllers/grading/ElectronicGraderController.php
- site/app/libraries/database/DatabaseQueries.php
- site/app/libraries/database/PostgresqlDatabaseQueries.php
Fix problem where the "auto-grading total" counted incorrectly
Also fixed an undocumented problem where for a limited-access grader, the "percent of viewed grades" counted all the sections and was like 300%
> [small] Gradeable statistics page fix

- site/app/controllers/forum/ForumController.php
Closes #3554 
No ineffective code is contained in the file. Thorough testing did not break anywhere. Ran e2e tests for Forum.
Is this a breaking change? - No.
How did you test - E2E tests in /usr/local/submitty/tests
> [Refactor] Remove unused code from ForumController.php

- site/app/views/forum/ForumThreadView.php
Closes #3549
Ineffective code has been removed without any changes in the working observed. Also ran all e2e tests to check for errors, none reported.
Documentation update for installation of ChromeDriver on Linux in _docs/developer/end_to_end_tests.md
Is this a breaking change? - No.
How did you test - all E2E tests in /usr/local/submitty/tests/
> Removed ineffective code from ForumThreadView.php

- site/app/views/forum/ForumThreadView.php
> Place forum modals on-top of whole page

- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
Addresses #3592 on (index.php?semester=s19&course=blank&component=admin&page=admin_gradeable&action=view_gradeable_page)
Text box labels on new gradeable page are now clickable.
Tested using Vagrant and Virtual Box
> Added clickable labels #3592

- migration/test/test_cli.py
- migration/test/test_config.py
- migration/test/test_create.py
- migration/test/test_db.py
- migration/test/test_init.py
- migration/test/test_loader.py
- migration/test/test_main.py
- migration/test/test_migrate_environment_down.py
- migration/test/test_migrate_environment_up.py
- migration/test/test_print_status.py
Fixes an issue of running the unittest for some classes directly
> [Testing] Fix running the unittest suite on individual files of migrator

- site/public/css/server.css
Sidebar highlights are dull, lifeless, and gray. They make the students ponder existence to an extent greater than a CS class should.
Sidebar highlights are now super exciting and sure to improve morale due to their exquisite color!
This is very important and should be merged immediately
> Add extremely important colored line to highlighted page in sidebar

- site/app/views/grading/ElectronicGraderView.php
Fixes #3654 
Doesn't throw exception on electronic grading view
> [Bugfix] Fix missing FileUtils reference

- .setup/vagrant/sites-available/submitty.conf
Fixes #3443 
Git under vagrant got broken in some prior update such that git pushes/pulls would throw a 403 error. This fixes git to work again requiring authorization for the actions (clone, pull, push). I've also added documentation across the configuration so as to explain what each piece is doing, and also ordering the blocks in the order that they will get merged to determine the end permissions result.
I plan to make a separate PR later on (with even more documentation on each section) to address the conf files under `.setup/apache/` to help sysadmins set things up, but getting this in to allow for testing of #3305.
> Update and cleanup vagrant apache configuration

- autograder/autograder/packer_unpacker.py
- site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
- site/app/templates/submission/homework/SubmitBox.twig
Students can now specify the username and repository name and submit all files from a public GitHub repository.  Closes #1747
Also includes some UI tweaks on the related pages.
Support still needed for private GitHub repositories...   open issue #2741
> Allows Submission by Public GitHub repository (finally)

- .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
- site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig
- site/app/templates/grading/electronic/PDFAnnotationFullPage.twig
- site/app/templates/misc/Code.twig
- site/package-lock.json
- site/package.json
- site/public/js/pdf/PDFAnnotate.js
- site/public/js/pdf/PDFAnnotateEmbedded.js
- site/public/js/pdf/PDFInitToolbar.js
Uses an old buggy version of the pdf-annotate.js tool
Uses the newest version of the tool, as well as making it a NPM dependency to handle versioning. The newest version also relies on the latest version of PDF.js dependency, so updated it as well (superseding work done in #3645.
> Update pdf-annotate.js to newest version

- README.md
@bmcutler mentioned that we're phasing out submitty@cs.rpi.edu.
Point users to our website where we have the various methods to contact us.
> Update contact us block in README

- site/app/templates/Authentication.twig
Created the ability to click the text next to the checkbox on the login page, so user does not only have to click inside the box.
> [UI Tweak] clickable text 'stay logged in'

- site/app/templates/forum/CategoriesForm.twig
- site/app/views/forum/ForumThreadView.php
- site/public/js/server.js
Editing/deleting a category and making an announcement do not work.
> Fix categories and announcement access issues

- autograder/test/__init__.py
- autograder/test/test_write_grade_history.py
Adds a test for the autograder.write_grade_history module to ensure that it works as we currently expect it to. This is the first of a series of PRs that should be written over the summer to test out the python autograder functionality.
> [Testing] Add testcase for autograder.write_grade_history

- migration/migrator/migrations/course/20190603141524_bulk_upload_permissions.py
- sbin/create_course.sh
- sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
The default permissions on the split_pdf folder were wrong.
> [Bugfix] Bulk upload folder permissions

- site/app/libraries/TokenManager.php
Some functions are deprecated after updating lcobucci/jwt from 3.2.5 to 3.3.1 in https://github.com/Submitty/Submitty/commit/c688f7a1562a42144fb64168acdf5a6f58d399f4.
Deprecated functions are replaced with new ones.
> Replace deprecated methods in TokenManager

- site/app/templates/submission/homework/SubmitBox.twig
Correct a bug related to file submission box width introduced in #3794
> [Bugfix] Correct file submission box width bug

- site/app/templates/forum/createThread.twig
- site/app/templates/forum/searchResults.twig
- site/app/views/forum/ForumThreadView.php
Closes #3742 
The following use Twig templates - 
1. [x] CreateThread
2. [x] SearchResult
5. [x] DisplayThreadList - #3771 
6. [x] CreatePost - #3774 
3. [x] ShowForumThreads - #3780 
4. [x] GeneratePostList - #3774 
7. [x] StatPage - #3807 
Is this a breaking change? - None discovered yet.
How did you test - Not yet tested, only proper working checked manually. 
(This is a continuation to #3763 which was closed for shifting branch to Submitty repo, some previous conversation there.)
> [Refactor] ForumThreadView - CreateThread and SearchResult refactor to use Twig

- site/app/controllers/admin/LateController.php
- site/public/js/server.js
Partially addresses #2362 .
Late Controller now returns JSend format JSON only.
Tested manually to check if extensions & late days are working.
> [Refactor] Refactor Late Controller JSON Responses

- migration/migrator/migrations/course/20190611034600_add_instructor_solution_directory.py
Add a migration to create the ```instructor_solution``` directory in a course directory if it does not exist. The lack of this directory is causing assignment builds to fail on production.
> [Bugfix] Added Migration to Create instructor_solution Directory if Nonexistent

- .setup/distro_setup/ubuntu/rpi.sh
Needed to be change to bionic to find package
> update mono install for 18.04

- site/app/templates/Notifications.twig
Closes #3840 
Some links to the notification component are replaced with correct ones.
> [Bugfix] Fix several notification-related links

- .setup/distro_setup/ubuntu/rpi.sh
Updated to version 2.3.0 only available up to Ubuntu 16.04 currently.
> update dafny version

- site/app/templates/grading/simple/Display.twig
- site/app/templates/grading/simple/StudentSearch.twig
- site/app/views/grading/SimpleGraderView.php
- site/public/css/simple-grading.css
- site/public/js/simple-grading.js
- site/public/js/ta-grading-keymap.js
- tests/e2e/test_simple_grader.py
Closes #3161
- Changed DOM order of elements
- Added tabindex to ```Display.twig```
- Slimmed ```simple-grading.js```
- Added options parameter to ```ta-grading-keymap.js```
>  Reorganized TA grading for better VPAT and UX 
