site/app/templates/submission/homework/BulkUploadBox.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/submission/HomeworkView.php, site/ts/submission.ts
If an instructor uploads a normal submission file and then switches to either bulk or submit for student mode, the 
the previous submission needs to be deleted every time.
Files submitted on normal submission are auto removed when switching modes and restored when switching back to normal submission mode.
Note: Since there is no distinction between files submitted for a student, bulk upload and normal submission - previous files are no only shown for normal submission. Unsure if this is ideal behavior or if displaying previous files is needed for each mode @bmcutler ?
The display also shows a warning banner when changing modes:
closes #7190
=> [Bugfix:Submission] Upload bulk/student with previous files

site/public/css/server.css
Currently, the layout of the markdown area throughout the site is strange in the Overall Comments section of the TA Grading Rubric page (as well as other places on the site like the forum)
The layout looks correct.
This issue was caused by [this commit](https://github.com/Submitty/Submitty/commit/8b94c95d05acac91bc5ad4b78ff0001549aabb71) by dependabot, specifically this section 
At least in Mac Chrome, `width: available` is ignored by the browser and causes this strange layout. @williamjallen Any ideas on this? Will dependabot keep trying to make this change?
=> [UI/UX:TAGrading] Fix Markdown Layout in Overall Comments

autograder/autograder/insert_database_version_data.py, autograder/submitty_autograding_shipper.py, sbin/send_email.py
A recent issue caused Python linting to begin failing on master.  After some digging, I was unable to determine the original source of the issue and have simply addressed the errors in this PR.  
Example of a PR with failing CI: https://github.com/Submitty/Submitty/runs/4351911193?check_suite_focus=true
The most recent commit to Submitty (all checks succeeded): https://github.com/Submitty/Submitty/pull/7385/checks
Fixes linting.
=> [Bugfix:Developer] Fix Python Linting

Vagrantfile
On some windows systems, during vagrant up the machine times out before connecting.
Timeout value is extended from the default value 10 to 20 to allow additional time for the machine to connect.
=> [Feature:System] Increase vagrant ssh timeout value

site/app/templates/polls/NewPollPage.twig, site/cypress/integration/polls.spec.js
Currently, the release date field is blank for new polls
Now, the default release date will be the current date
=> [Bugfix:SubminiPolls] Add default release date to new poll

site/cypress.json
Cypress tests appear to fail at random on a limited number pull requests.  Most of the time the issue may be attributed to flakiness in the tests or testing environment and simply rerunning the tests often fixes the issue.  Cypress provides a configuration option to rerun tests a specified number of times on failure, succeeding if any of the attempts succeeds.
This PR enables Cypress test retries with an initial number of 2 retries per failed test.  If, after retrying twice, the test has not succeeded, Cypress concludes that the test has failed, otherwise the test passes.  This setting is only enabled when using `cypress run`, not using the graphical UI opened by the command `cypress open`.  `cypress run` is the command used in the CI to run all of the tests in sequence while `cypress …
=> [Bugfix:Developer] Enable Cypress test retries

site/app/templates/autograding/TAResults.twig
Overall comments/PDFs from graders will not display if there is no TA graded component present.
This causes issues on assignments where users with grading access peer grade a gradeable with no TA components, leading to comments not showing up.
Closes #7369
Overall comments/PDFs from graders will always show up if they exist, regardless of the presence of TA graded components.
=> [Bugfix:TAGrading] Always display comment/uploaded PDFs

site/phpunit.xml, site/tests/app/libraries/database/DatabaseUtilsTester.php, site/tests/phpstan/ModelClassExtensionTester.php
Closes #7375 
On moving the `phpunit.xml` file in #7303, it seems like I missed some paths, which meant that phpunit was no longer finding any tests to execute. This was reported as a warning within phpunit, but did not cause the CI to fail, and so I thought everything was working as expected.
This PR fixes the paths in the `phpunit.xml` file so that the tests are discovered properly again, as well as fixing some new failing tests that started due to us not running the test suite properly for a month or so. This also fixes codecov so that it reports stats properly again.
=> [Bugfix:Developer] Fix phpunit not finding any tests

site/app/templates/autograding/TAResults.twig
#7397 conflicted with changes from #7296, where `overall_comments` was removed in favor of `grader_info` array.
Replaces the undefined `overall_comments` with `grader_info` which took its place within the twig template.
=> [Bugfix:TAGrading] Fix undefined twig variable

site/app/controllers/admin/PlagiarismController.php
There are currently two small UI issues on the plagiarism interface:
1. The top match on the plagiarism main page does not currently display the percent match properly
2. Individual entries in the regex field on the configuration page are not re-rendered correctly when editing the page
Fixes bugs.
=> [Bugfix:Plagiarism] Fix minor UI bugs

.github/workflows/submitty_ci.yml
CI is currently failing when running the unit tests. This seems to be due to a bug in the recently released 2.2.0 composer.
Pins us to 2.1.14 of composer which worked previously. Will monitor composer releases and unpin us when a new bugfix release comes from them.
=> [Bugfix:Developer] Pin composer version for CI

.github/workflows/submitty_ci.yml
The release of composer 2.2.0 broke running phpunit as it began throwing an error about strict_types (see https://github.com/Submitty/Submitty/runs/4636839459?check_suite_focus=true as an example).
PHPUnit 8.5.22 fixed the problem, and that was merged into master in #7491, which allows unpinning the composer version in CI.
=> [Bugfix:Developer] Unpin composer version in CI

site/app/controllers/grading/ElectronicGraderController.php, site/app/templates/grading/electronic/Details.twig, site/app/views/grading/ElectronicGraderView.php
See https://github.com/Submitty/Submitty/issues/7112
This PR addresses the issue mentioned in https://github.com/Submitty/Submitty/issues/7112 by blocking the grading stats page for peer grading and removing the grading stats button from the UI.  If it is determined that this behavior is not ideal, it would also be possible to enable statistics for peer graders but that does not seem to be the intended behavior here so I have removed the button altogether.
Closes https://github.com/Submitty/Submitty/issues/7112
=> [Bugfix:TAGrading] Remove grading stats for peer graders

site/app/templates/polls/NewPollPage.twig, site/public/css/polls.css
See https://github.com/Submitty/Submitty/issues/7186
Before:
This PR increases the length of the poll title input field such that it extends all the way to the right side of the window.  Closes https://github.com/Submitty/Submitty/issues/7186
After:
=> [Refactor:SubminiPolls] Expand poll title input field

site/cypress/integration/grading_interface/files_panel.spec.js, site/cypress/integration/grading_interface/student_info_panel.spec.js
There are currently no tests which are run in the CI for much of the TA grading interface.
This PR adds a few basic tests for the student info and files panels on the TA grading interface.  These tests are not meant to be comprehensive and should be expanded as bugs are identified and fixed, but the basic structure is here to make it easy to add more tests in the future.  A future follow-up PR will introduce basic tests for the other TA grading interface panes.
=> [Testing:TAGrading] Add primitive TA grading cypress tests

bin/calculate_extensions.cpp
Fixes #7548
The `bin/calculate_extensions.cpp` script imports `boost/progress`, but never uses anything from it. This causes a deprecation warning as shown in #7548.
Removes the unused import.
This is not a breaking change, and `calculate_extensions` still compiles correctly.
=> [Bugfix:Autograding] Remove unused boost/progress import

site/app/libraries/CustomCodeBlockRenderer.php
The line numbers on code blocks do not line up properly with the code block.
The line numbers are properly aligned.
Another issue that was reported seemed to have duplicate/runaway line numbers like in the screenshot below but I have been unable to reproduce this aspect of the bug.
=> [Bugfix:Forum] Fix Markdown Line Number Positioning

.setup/install_system.sh
Debug for xdebug only accepts connections from 10.0.2.2.
Profiling for xdebug does not work out of the box since the folder where the profiler data would be put is missing.
Debug for xdebug accepts any connection.
Profiling for xdebug works properly.
=> [Bugfix:Developer] Update Xdebug config

site/app/templates/officeHoursQueue/NewQueue.twig
A lot of students this semester seem to be using links with`/join/` instead of `/meet/` -- I've tested this does indeed let me join their room so it should be valid. The regex we suggested previously for WebEx Personal Rooms used `/meet/` specifically.
This was causing a lot of students to be confused, since the error message is not very specific (and really, showing the students the regex in an intro course would probably not help them understand why the URL was rejected).
I've updated the suggestion to accept any string after `webex.com`
I didn't change the tail end of the regex from `.*` to `.+` (which would prevent things like `xxx.webex.com/meet/`), since the old pattern didn't enforce that either.
=> [Bugfix:HelpQueue] Generalize WebEx Personal Room link

site/app/templates/polls/PollPageStudent.twig, site/public/css/polls.css
fixes https://github.com/Submitty/Submitty/issues/7547
Long responses now wrap around such that the first line of the response stays to the right of the radio box.
=> [Bugfix:SubminiPolls] Fix wrapping of long responses

site/app/controllers/admin/UsersController.php
The `register_shutdown_function` uses a late binding closure to capture the values of `$csv_value` and `$xlsx_value`. However, they're not always defined in all cases, which phpstan doesn't fully like (#7606).
We make sure the two variables are always defined to something, and then overwrite them in the course of the `getUserDataFromUpload` execution.
=> [Bugfix:Developer] Fix undefined variable reference

site/app/templates/forum/searchResults.twig, site/app/views/forum/ForumThreadView.php
Currently, if you try to use the forum "search" feature, you get a twig error. While investigating this and trying to debug, I discovered multiple issues stacked on top of each other:
- Some invalid twig syntax causing the initial error I saw
- A call for a twig template has not been updated since we added the global markdown template everywhere on Submitty
- The forum search view had a logic bug where the threads and their responses that came up in the search were not being stored in the right hierarchical order in the array passed to the twig
Note: I think that right now on production (where errors are suppressed) the only output the search yields is only the first response for each post, however this should be fixed with this PR.
Feature works as expected.
=> [Bugfix:Forum] Fix using forum search

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20220206171041_drop_milliseconds.py
Milliseconds can get inserted into the database when `current_timestamp` is used on a SQL query.
Now that we are slowly moving to Doctrine, there is an issue where milliseconds and timezone are not supported in conjunction. To avoid this issue, this PR enforces that all of the timestamp types to not use any fractional seconds.
I identified all the places in DatabaseQueries where we use `current_timestamp` in the course database and targeted those columns in this PR.
An alternative fix could be to implement our own Doctrine database type but we also don't really need this level of precision for these fields.
=> [Bugfix:System] Drop milliseconds for DB timestamps

site/app/templates/course/CourseMaterials.twig, site/app/views/course/CourseMaterialsView.php, site/public/js/server.js
Empty folders will briefly appear when loading the course materials page before disappearing.
New tags on a file/folder only show up on the file/folder and direct parent folder.
Closes #7533 
Empty folders will not show up when loading the course materials page.
Closes #7372 
New tags on a file/folder extend all the way up to the root folder on the course materials page.
=> [Bugfix:CourseMaterials] Fix hiding empty folders and showing new tags

site/app/templates/grading/electronic/Details.twig
On the TA grading index, it will not show that a user has a grade inquiry if their grade is overridden or if they have no submission for the assignment.
Closes #7461 
It will always show if a user has a grade inquiry on the button in the grading index.
=> [Bugfix:TAGrading] Always show grade inquiry in index

site/.stylelintrc.json, site/public/css/docker_interface.css, site/public/css/server.css
https://github.com/Submitty/Submitty/pull/7630 is currently failing the `css-stylelint` test because there are a couple places in the codebase that use invalid CSS `filter` properties.  
This PR removes the offending properties.
=> [Refactor:Developer] Remove invalid CSS properties

site/app/controllers/admin/PlagiarismController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/plagiarism/Plagiarism.twig, site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
Various places in the plagiarism interface use the `g_grade_due_date` database column as the data source for gradeable due dates.  This is the wrong column and does not display the submission due date as seen by the students
Fixes the bug.  In addition, the behavior when dealing with gradeables with no due dates has been improved such that no due date is displayed on the interface.
New interface:
=> [Bugfix:Plagiarism] Fix dates

site/composer.json
Some upcoming version of Composer 2 requires plugins to be added to an `allow-plugins` list to run. We currently do not have the `dealerdirect/phpcodesniffer-composer-installer` plugin we use on that list.
Adds the `dealerdirect/phpcodesniffer-composer-installer` to the `allow-plugins` list so that it'll continue working with newer versions of composer.
=> [Bugfix:Developer] Add phpcs plugin to allowed-plugins

Vagrantfile
Right now, the Vagrantfile only officially supports VirtualBox, however the latter does not support (and will never support) macos M1, meaning we need an alternative supported vendor.
This adds support for [Parallels](https://www.parallels.com/) to the Vagrantfile to add support for M1. An unfortunate side effect of this is that we need to use the Pro version of the software which is $99 / yr compared to VirtualBox which is free. I did try to see if I could get VMWare to work, but I could not get their website to even let me download the software, so I gave up on it. Additionally, unfortunately bento project does not yet offer arm64 images (though support to the repo was added in https://github.com/chef/bento/pull/1374), we use a comparable image that does support arm64 for now. I hope to …
=> [Feature:Developer] Make Vagrantfile parallels compatible

.github/workflows/submitty_ci.yml
Fixes #7678 .
`Set up sample course` faults because `ldapadd` (part of the open-ldap) is not present at the time of execution.
Reordered `Setup Idap` in front of the `Set up sample course`, so `ldapadd` will be available when setup sample course is invoked.
Do we need to refactor `setup_sample_courses.py` so that it fails when external calls fail?
=> [Bugfix:Developer] Reorder ldap setup in CI

site/package-lock.json, site/package.json
jQuery-UI and jQuery-are-you-sure types for TypeScript are not added.
jQuery-UI and jQuery-are-you-sure types for TypeScript are added.
=> [Refactor:Developer] Add more jQuery types for TypeScript

.setup/install_system.sh
We install haskell to help developing analysis tools within Vagrant. Unfortunately, this is only available on x86_64 architecture, and not yet available on running on other architectures like arm64 (necessary for M1).
This disables downloading and installing haskell / stack on non-x86_64 machines, fixing running `install_system.sh` on M1 vagrant (or any other architecture). While an alternative might be to migrate to GHCup to get this to work, as we look to migrate off AnalysisTools anyway, I don't think it's worth spending the time trying to get the toolchain to work as we look to remove it altogether soon anyway.
=> [Bugfix:Developer] Do not install haskell on non-x86_64

.setup/distro_setup/ubuntu/20.04/setup_distro.sh
Right now, we only fetch sources for `amd64` for the docker apt repository. This prevents installing it on arm64 (M1).
Adds fetching `arm64` to the docker repository we're fetching from, so that the same line works on both amd64 or arm64. By specifying both, there's a few kb more download on fetching the repository, but we avoid doing any sort of complicated logic to make sure we're fetching the right arch name using flags.
=> [Bugfix:System] Get arm64 sources for docker

autograder/autograder/autograding_utils.py
If you make a submission to an assignment with autograding, the first access timestamp will be the current timestamp. #7673 shows screenshots of this behaviour.
Closes #7673
The first access timestamp will now be correct for all submissions going forward.
All past submissions will still have this bug on the UI but it doesn't necessarily cause any technical or grading issues that I can see. A migration could be written to fix all old cases but I don't think its necessary.
=> [Bugfix:Autograding] Fix File Path of Access JSON

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/distro_setup/ubuntu/18.04/setup_distro.sh, .setup/distro_setup/ubuntu/20.04/setup_distro.sh
A few errors that were found when upgrading a worker machine from Ubuntu 18.04-> Ubuntu 20.04.  This was not a fresh install of a new server, but rather a patch upgrade.  After the upgrade was complete, ran:  `bash ./.setup/install_system.sh --worker`
The two errors:
* missing definition of SUPERVISOR_USER variable
* permissions error on NodeJS installation
=> [Bugfix:System] upgrade worker machine 18.04->20.04

site/app/controllers/forum/ForumController.php
Closes #7677 
When trying to view the history of a post, an exception is thrown about `render_markdown` not being defined within the `ForumPost.twig` template. This is because we're not passing in a value for this variable when rendering the template.
A value for `render_markdown` is provided when rendering the `ForumPost.twig` template. The modal shows up as expected that shows the post history. It always shows these posts in plain text as we do not capture in the history if a given post was in markdown or not. I'm not sure if anyone wants the markdown in the history, so I think fine just leaving it as plain text for now.
=> [Bugfix:Forum] Fix exception on viewing post history

site/app/libraries/CodeMirrorUtils.php, site/app/views/MiscView.php, site/public/css/code-mirror-utils.css
Closes #7694 
The color used for highlighting text in codemirror on the submission page under dark mode provides little to no contrast against the text, making it hard to see what's currently highlighted. It's a darkish yellow color, but it does not show up well.
I've modified it to be a bluish color that's a bit more prominent. It shows up better against the backgrounds, but I still think the contrast could be improved, but it might involve tweaking the input background which I'm not prepared to tackle at this time. I didn't want to go too bright with the blue (like the default chrome color) as then it ruins being able to read the highlighted code that's been highlighted.
=> [Bugfix:Submission] Fix dark mode CM highlight contrast

site/app/controllers/grading/ElectronicGraderController.php
Closes #7780
The broken header link goes to http://localhost:1511/courses/s22/sample/gradeable/grading_only_peer_team_homework/grading/status 
The header link now goes to 
http://localhost:1511/courses/s22/sample/gradeable/grading_only_peer_team_homework/grading/details
=> [Bugfix:Submission] Fix bad breadcrumb link for peer grading

site/app/libraries/database/DatabaseQueries.php
If you click "See who got this mark" on a rubric item where no students have received that mark, you will receive a SQL error as shown.
Now the button will open the menu with no students listed. This PR fixes it by making sure the SQL statement is never executed with an empty list.
=> [Bugfix:TAGrading] Fix See Who Got This Mark

site/app/libraries/CodeMirrorUtils.php, site/app/templates/grading/electronic/NotebookPanel.twig, site/app/templates/misc/SourceSettings.twig, site/public/js/forum.js, site/public/js/plagiarism.js, site/public/js/ta-grading.js
* #7734 
Closes #7734 
Fixes TA grading notebook autoscroll by adding a brief transition period to the scroll.
Attempted to fix issue with empty notebook boxes by adding and enabling the CodeMirror autoreload addon (https://codemirror.net/doc/manual.html#addon_autorefresh) where CodeMirror boxes are enabled.
Was unable to reproduce empty notebook boxes on Chrome/Edge/Firefox on Windows 10; needs testing on Chrome on macOS.
=> [Bugfix:TAGrading] Fix TA grading notebook bugs

site/app/views/grading/ElectronicGraderView.php
* #7581 
Closes #7581 
Shows `Late Submission` in orange when selected submission is late but has enough late days/extensions to cover it.
Shows `Bad Submission (submitter has valid submission - Version #X)` in red when selected submission is late and does not have enough late days/extensions to cover it, but has a previous submission that is valid.
Shows `Bad Submission (no valid submission available)` in red when selected submission is late and does not have enough late days/extensions to cover it, and does not have a previous submission that is valid.
=> [Bugfix:TAGrading] Improve late day banner visuals

.setup/INSTALL_SUBMITTY_HELPER.sh
The `INSTALL_SUBMITTY_HELPER.sh` script defines `SUPERVISOR_USER` twice, once on line 35 (added in #7729) and a second time on line 145 (added in #7668). Nothing between those lines uses the `SUPERVISOR_USER` variable. While the double assignment doesn't affect anything really, would be good to just have the one assignment just in case we ever need to update the line and don't need to update two lines (or worse, one line is missed).
Removes the assignment on line 35, and just leaves the one on line 145. We want the latter one in case the migrator modifies the value of that variable in some way, similar to the other variables that are defined there. The variable defines on line 35 are just the minimal set required to run the stuff between 35 and 145, which isn't much.
=> [Refactor:System] Remove duplicate SUPERVISOR_USER define

site/public/css/plagiarism.css, site/public/js/plagiarism.js
The dark borders between matching blocks on the plagiarism interface can be distracting when there are many overlapping blocks.  At the same time, it must be clear where blocks begin and end so they can be effectively clicked on.  This PR changes the border style to be less distracting.  Red- and blue-highlighted text still retains the previous black borders since the emphasis is desired in such cases.
Before:
After:
https://github.com/Submitty/Lichen/pull/79 made modifications to the ranking output files which necessitated a few minor text changes which have been included in this PR.
=> [UI/UX:Plagiarism] Reduce plagiarism interface distractions

site/app/controllers/admin/PlagiarismController.php, tests/e2e/test_sidebar.py
The timestamp of the last plagiarism run is currently only set for the initial plagiarism run.  It should update it every time the re-run button is clicked.
This PR changes the behavior to properly reflect the last time the configuration was run.
=> [Bugfix:Plagiarism] Properly set last run timestamp

site/app/views/GlobalView.php, site/public/js/server.js
Currently, if you: visit a course homepage, visit a subpage of that course, close the sidebar, navigate back to the homepage of the course, open the sidebar, and reload the page, the sidebar will remain closed.
@KCony reported this issue with the sidebar via slack.  The following screen recording is from that bug report.
The sidebar is now able to be opened/closed from any page.  This means that it is no longer possible to have page-specific sidebar settings, but it makes the general UI more user-friendly.
Note: I was unable to reproduce the issue after making these changes but due to the finicky nature of cookies, it is possible that these changes are not enough and there may be edge cases where the sidebar still does not behave properly.
=> [Bugfix:System] Fix sidebar cookie bug

site/app/controllers/student/SubmissionController.php
Students can view a gradeable by the URL when viewing by students is set to `No`.
Students can no longer view a gradeable by the URL when viewing by students is set to `No`.
This can be tested by editing a gradeable and setting `View the gradeable on the course home page and download submitted files?` to `No` (`Edit Gradeable` -> `Submissions/Autograding` -> `What are students allowed to do?`) and going to the URL directly (it will not appear under `Gradeables`); this does not impact `When grades are released`.
=> [Bugfix:Submission] Gradeable access bugfix when view is no

site/app/controllers/admin/NotebookBuilderController.php, site/app/models/gradeable/Gradeable.php, site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig, site/public/js/admin-gradeable-updates.js, site/tests/app/controllers/student/SubmissionControllerTester.php, site/tests/app/models/gradeable/GradeableListTester.php
Right now there is no validation on the provided autograding config path except to check if it's blank.
This PR adds a check to validate the config path. It will check for the following conditions:
1. The path is a directory
2. The directory contains a config.json
3. The user requesting this build has valid read permissions of that directory
This also modifies the behavior of error handling on the build page to properly display the reason the path is invalid.
=> [SECURITY][Bugfix:InstructorUI] Validate Autograding Config Path

migration/migrator/migrations/system/20220417174632_patch_authentication_method.py
Running CONFIGURE_SUBMITTY.py on older systems may crash. (Specifically any system created before PR mentioned below that is running up to date code)
PR #7444 contained a migration which moved the authentication method into authentication.json and added an ldap_options field. This migration set the default value of ldap_options to [] when it should have been {} because CONFIGURE_SUBMITTY.py expects ldap_options to be a dictionary rather than a list.
CONFIGURE_SUBMITTY.py does not crash.
This PR adds a system migration to check if [] is the value of ldap_options in authentication.json and if so, changes it to {}. When CONFIGURE_SUBMITTY.py gets run, the url, uid, and bind values would get filled in.
Another option besides this migration could be to modify the CONFIGURE_SUBMITTY.py script …
=> [Bugfix:System] Patch authentication.json

site/app/templates/Authentication.twig, site/app/views/AuthenticationView.php, site/public/css/markdown.css
There is no way to customize the login screen right now.
A login.md file can be created inside /usr/local/submitty/config which will be rendered on the login screen. By default `# Login` is rendered but the system administrator can choose to customize this however they like.
Documentation PR: https://github.com/Submitty/submitty.github.io/pull/420
=> [Feature:System] Markdown Login Screen Customization

site/public/js/pdf/PDFAnnotateEmbedded.js, site/public/js/ta-grading-rubric.js
* #7735 
Closes #7735
Fixes error popup on edit gradeable page when the PDF page number is edited.
Fixes PDF page assignment scrolling (with submission browser + rubric in TA grading).
This can be tested by: 
0. Get a multi-page PDF.
1. Create a gradeable with the type `Students will submit one or more files by direct upload to the Submitty website`
2. Edit the gradeable and go to the rubric tab.
3. Under `And do you expect each specific problem/item/component to appear on a specific page number of the PDF document?`, select `Yes`.
4. Click on the component, and on the right side of the title line enter a valid page number for your multi-page PDF.
5. Add more components and set their page numbers as needed.
6. Submit the PDF to the gradeable and go to grade the PDF (gradeables -> grade -> …
=> [Bugfix:TAGrading] PDF page assignment bugfixes

site/app/models/notebook/Notebook.php, site/app/views/submission/HomeworkView.php
When going to a cancelled submission, the page will reload three times when trying to access "version 0".
Users cannot submit on "version 0" of a cancelled submission.
Cancelling a notebook submission throws errors when viewing "version 0".
Autograding results are not rendered on "version 0", fixing the page reload issue.
Users can now submit on "version 0".
Viewing "version 0" of a cancelled notebook submission no longer throws errors.
=> [Bugfix:Submission] Cancelled submission bugfixes

site/app/views/submission/HomeworkView.php, site/ts/grader-submission.ts, site/ts/ta-submission.ts
Full access graders / TAs are shown the option to make a submission for another student or bulk upload but choosing those options does not do anything. The code to make those functional is only sent to instructors.
The code is now also sent to full access graders. In SubmitBox.twig on line 67, it can be seen that being a full access grader controls whether or not you would receive the submission type buttons.
This PR also renames instructor-submission.ts to ta-submission.ts as the functionality is not limited to instructors only anymore.
=> [Bugfix:Submission] Fix TAs Submission Type Select

site/app/controllers/course/CourseMaterialsController.php, site/app/templates/course/UploadCourseMaterialsForm.twig, site/cypress/integration/courseMaterials.spec.js
Fixes #7765
In the front-end this generates an alert with message "Select at least one section" when restrict section is selected but no section is selected under it and the submit form button is clicked.
In the backend this sends error response with message "Select at least one section"
=> [Bugfix:CourseMaterials] Restrict course material for no section

site/app/templates/generic/Popup.twig, site/public/css/server.css, site/public/js/server.js
Currently the only way to close a pop up is to click the close button at the bottom. If the pop up is long you may have to scroll down to see the close button.
Closes #7637
This PR adds an X at the top right corner of all pop ups. It also adds the ability to click anywhere not in the pop up and it will get closed.
Light Mode:
Dark Mode:
=> [UI/UX:System] Add Close Features to Pop Up

site/app/controllers/admin/PlagiarismController.php
The "other gradeables" feature of the plagiarism detection interface currently displays an error when you attempt to add an "other gradeable" via the dropdown menus.  This is due to a faulty assumption about how PHP's `explode()` function works.  
Fixes the bug.  Other gradeables can now be added via either the dropdowns or the manual gradeable path entry field.
=> [Bugfix:Plagiarism] Fix other gradeables dropdown bug

site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
This PR changes the text on the "submit" button of the configuration form for plagiarism, to clarify that submitting will trigger a new run for the new or edited configuration.
=> [UI/UX:Plagiarism] Change text on config form button

site/app/views/NavigationView.php
When on the gradeables page as a grader, the grade button for an assignment without a release date will still show the database's release date value.
The button will only say grade if the gradeable has no release date.
=> [Bugfix:TAGrading] Fix Grade Button Without Release Date

.github/workflows/vagrant_up.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> [Testing:Developer] Set read permission on vagrant GH action

bin/build_homework_function.sh
`build_homework_function.sh` does not quote bash variables properly.  This can result in [unintended consequences](https://unix.stackexchange.com/a/171347/195445) if variables contain spaces, or other special characters.
Variables in `build_homework_function.sh` have been quoted.
=> [Refactor:System] Quote variables in `build_homework_function.sh`

site/app/libraries/socket/Server.php
Certain messages can be sent to the websocket server that can cause it to crash and restart.
Additional checks along with a try/catch have been added to prevent websocket crashes.
An example message that could cause a crash is sending a non-string page value.
=> [Bugfix:System] Prevent Websocket Crashes

site/app/templates/grading/electronic/Details.twig, site/app/views/grading/ElectronicGraderView.php
* #7732 
Closes #7732 
Grading index in anon mode changed to have columns in the same order as non-anon mode.
The `Grading` column in anon-mode now behaves identically to non-anon mode when a limited-access grader or above is viewing the grading index (students will only see their own grading score in peer grading).
=> [Bugfix:TAGrading] Improve grading index column order

site/app/templates/admin/Configuration.twig
Broken link on course settings page for rainbow grades
Fixes link to point to overview section of rainbow grades, changes wording since automatic configuration is an option 
N/A
=> [Bugfix:InstructorUI] Fix rainbow grades link

site/public/js/simple-grading.js
Fixes #7568  : Colors are hard coded  for numeric gradeables instead of using 'colors.css'. This mainly causes problems with the dark mode version of the site. 
Standard names for the colors are used as described in colors.css instead of hashcodes , also the color '#ff7777'(not available in colors.css) is replaced with '#ff9999'(available in colors.css).
=> [Bugfix:InstructorUI] Fixed Hard Coded colors

.setup/INSTALL_SUBMITTY_HELPER.sh, site/app/libraries/socket/Server.php
When an error or exceptions occurs during a websocket message, there is a try catch where the catch currently does not do anything.
Closes #7862
The catch now calls a logError function which logs errors in the same manner as regular site errors except it is stored in the socket_errors folder inside /var/local/submitty/logs.
Example exception/error:
Documentation PR: https://github.com/Submitty/submitty.github.io/pull/426
=> [Feature:System] Add Websocket Error Logging

.setup/install_submitty/install_site.sh
Currently the install site script will make a temporary index.html file inside of /tmp which can cause an issue if an index.html already exists inside of /tmp which is world writeable.
A temporary directory (with a random name) is created inside of /tmp first that only root can write to so that this issue can no longer occur.
=> [SECURITY][Bugfix:System] Site install temp directory

bin/generate_repos.py
Using os.system in the generate repos script with variable fill ins could lead to possible command injection.
subprocess.run is used instead with an array of parameters so command injection is not possible.
=> [SECURITY][Bugfix:System] Prevent generate_repos injection

site/public/js/simple-grading.js
Fixes #7761
If the user tries to navigate vertically with the arrow keys through the lab checkpoints, the selection will move 2 cells at once. The arrow keys also do not work in the null section.
The arrow keys now correctly move 1 cell at a time when the user wants to navigate vertically. They also function correctly in null sections.
https://user-images.githubusercontent.com/79226246/168719906-8704f0c1-415f-4a53-a6d1-2bb32955a3cc.mp4
=> [Bugfix:TAGrading] Lab navigation for checkpoint fix

site/app/templates/generic/Popup.twig
When pushing the top close button, the form may accidentally submit since the default type of button is usually submit.
This can be seen on the Mange Students / Manage Graders page.
The type of the button is now button and I also used the block for the close action rather than assuming it will always only just close the popup.
=> [Bugfix:System] Fix Popup Submit on Close

.github/workflows/submitty_ci.yml, site/composer.json, site/composer.lock, site/phpstan-baseline.neon, site/phpstan.neon
Right now if a PHP library were to get updated and deprecate something that we use, we would have no idea in without looking at the library updates carefully.
An example of this is: https://github.com/Submitty/Submitty/pull/7870
I plan to test this on that PR to make sure it reports a failure in the phpstan test.
A deprecated checker library was added that extends upon phpstan to look for any deprecations within our codebase. If there is a new deprecation the test will fail.
This PR does NOT update any current deprecations but it does update the baseline so that phpstan will continue to pass. Most of the current deprecations are from our MultiResponse but a few are from some dependencies. These can be fixed in future PRs and the baseline can be updated.
Also the phpstan command was …
=> [DevDependency] Add deprecation checker to phpstan

site/app/models/gradeable/LateDayInfo.php
Submitty runs into the error page as described in #7893 due to a null variable.
The error page no longer happens and the grading page is displayed.
This was tested by using the instructions described in #7893 to reproduce the error with a new course.
=> [Bugfix:TAGrading] Ta grading team bug

site/app/models/gradeable/AutoGradedGradeable.php
PR https://github.com/Submitty/Submitty/pull/7931 had changed the int type to float.
It should have been changed to `int|float` which this fixes.
=> [Bugfix:Developer] Fix type annotation for points

sbin/create_course.sh
There are many improperly-quoted variables in Submitty's installation scripts.  This can result in [unintended consequences](https://unix.stackexchange.com/a/171347/195445) if variables contain spaces, or other special characters.
This PR continues the work begun in #7874 to improve the robustness of Submitty's various shell scripts by properly quoting the variables in `create_course.sh`.
=> [Refactor:System] Quote variables in create_course.sh

site/app/views/submission/HomeworkView.php, site/app/views/submission/TeamView.php
The "Create and Manage Git Auth Tokens" button is currently broken.
This PR fixes the URL to point to the correct page.
=> [Bugfix:Submission] Fix Git authentication tokens URL

site/app/controllers/UserProfileController.php
Fixes #7959 
"Send Email to Secondary Address" can be set to true in the user profile even if secondary email address is empty, this is something that UI prevents from happening but a crafted request can lead to this unexpected behavior.
Doing so now results in error "Secondary email can't be empty if secondary email notify is true".
=> [Bugfix:Notifications] Secondary email notification fix

sbin/generate_grade_summaries.py, site/app/libraries/routers/WebRouter.php, site/tests/app/libraries/routers/WebRouterTester.php
If you try to run rainbow grades on the website you will get the following error:
The API endpoint URL was incorrect in the code which has been corrected and allows rainbow grades to be generated from the website.
This PR also removes a check from the POST size check that I believe to be unnecessary now. Without this change, the API request fails because it does not send along any POST data.
=> [Bugfix:RainbowGrades] Rainbow Grades Post Request Fix

site/public/css/electronic.css, site/public/css/global.css
Fixes #6859, Earlier on create/edit gradeable page the side navigation panel contained scroll and if the content on the page increased in the size then the footer went hidden under the content.
The scroll from the side navigation is removed and is made consistent with general user interface of the application.
Here is the screenshot for same
=> [Bugfix:InstructorUI] Fixed Edit Gradeables page

.setup/install_submitty/install_bin.sh, .setup/install_system.sh, .setup/update_system.sh
Currently, pip installation that is done in the initial Submitty installation or vagrant up are only ever done once via `install_system.sh`.
The pip install has been moved out and into their own file called `update_system.sh` which is now invoked with the `INSTALL_SUBMITTY` script 
Currently, I only moved over the pip installation, will look into OS dependencies next and then specific installs like DrMemory, Haskell Stack - etc.
=> [Bugfix:System] autoupdate Python dependencies

site/app/templates/admin/RainbowCustomization.twig
Closes #7985 
In instructor UI for a course,
Go to`  "Grade Reports"> "Web-Based Rainbow Grades Generation" > "Messages"'`
In the  section, there should be a form text box allowing you to enter messages, but it is not displayed in the message is currently empty. 
Empty TextBox is displayed allowing you to add and save the message.
Here is the screenshot for same.
=> [Bugfix:InstructorUI] Fixed Textbox not displaying

site/app/templates/polls/ViewPollPage.twig, site/public/css/polls.css
Closes #8020 
`ViewPollPage.twig` could not show the image attachment.
`ViewPollPage.twig` could show the image attachment.
=> [Bugfix:SubminiPolls] Fix Viewpoll Image

site/app/controllers/forum/ForumController.php, site/app/views/forum/ForumThreadView.php
- Fixes #7955 
- If a thread is queried in the Discussion Form using an invalid (a null or non-integer value) or non-existent thread id, a server error would be displayed prompting for the page to be refreshed.
Now, the thread id is checked when a thread is being retrieved to make sure that it and its corresponding thread exists.  If the thread id is invalid or the thread does not exist, a "fail" JSON response case will be rendered that says that the id is not valid.  
I had two pages opened to the discussion forum.  One of these pages had the Inspector Console panel opened and the other with with the Inspector Network panel  opened.  In the Console, the following commands were entered: 
- Commands that Rendered a "successful" JSON response case
- window.socketClient.send({type: …
=> [Bugfix:Forum] Validate Forum Thread IDs

AUTHORS.md, site/app/controllers/forum/ForumController.php, site/app/libraries/Output.php
Threads/posts could be deleted by a different user. Also it is possible to create links that could lead to XSS.
Threads/posts can only be deleted by the author or an authorized user. Links are checked in the markdown renderer so XSS is not possible.
Thanks Fu (@richcfno1) for pointing these out.
=> [SECURITY][Bugfix:Forum] Fix Forum Links and Deletion

.setup/INSTALL_SUBMITTY_HELPER.sh
If INSTALL_SUBMITTY_HELPER.sh is run on a worker it will look for a database.json file since https://github.com/Submitty/Submitty/pull/8031. The database.json file doesn't exist on worker machines so it will fail.
An if check was added to make sure that this code doesn't get executed on a worker.
=> [Bugfix:System] Fix database superuser check on workers

.setup/INSTALL_SUBMITTY_HELPER.sh, sbin/shipper_utils/update_and_install_workers.py
Worker installation fails on a `chown` command due to not having the group specified which is only used on the primary machine.
These issues were fixed and the installation was tested to complete successfully now.
Closes #8056
=> [Bugfix:Autograding] Fix for worker installation failure

site/app/libraries/database/DatabaseQueries.php, site/app/models/Course.php, site/app/templates/HomePage.twig, site/tests/app/models/CourseTester.php
The home page does not list registration sections.
Registration sections are now listed on the home page. Below are examples of how they appear:
On desktop:
On mobile:
The section information is not displayed for users in the NULL section (most likely the course staff).
Closes #7248
=> [Feature:InstructorUI] Added registration section to home page

site/app/controllers/admin/ReportController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/User.php
The grade summaries for rainbow grades do not include registration type.
Closes #7474
The JSON files used by rainbow grades now have the registration type included.
I tested by setting various registration types in the sample course. Then after generating the grade summaries, checking the JSON files to see that the correct "registration_type" property is set.
=> [Feature:RainbowGrades] Registration type in grade summaries

site/app/controllers/pdf/PDFController.php
Closes #8043
There is an unwanted stack trace in team PDF grading that should not be visible to the user.
Removes the stack trace in team PDF grading.
=> [Bugfix:TAGrading] Remove Stack Trace in Team PDF Grading

site/app/controllers/pdf/PDFController.php
If using anonymous IDs for finding PDF path, then the `getUserFromAnon` query function will be executed twice for each path part. The second query was added as part of the fix in #8061.
`getUserFromAnon` is only ever executed once per path part. Additionally, took advantage of using the string concat operator with equality to simplify the if branches down to a single line.
=> [Refactor:TAGrading] Simplify getAnonPath function

.setup/install_system.sh
If the install system script is run, the course database user password won't get set properly as the variable isn't defined.
The variable is now defined so the password gets set to the right value rather than just an empty string.
=> [Bugfix:System] Course Database Password Assignment

grading/python/submitty_router.py, site/app/templates/autograding/AutoChecks.twig
The mermaid sequence diagrams for network gradeables have messages overlapping with each other most likely due to broken y values for the elements in the SVG.
The messages in the mermaid sequence diagrams now have line breaks and other elements have correct y values.
This is a temporary fix by adding delays.
=> [Bugfix:Autograding] Mermaid Sequence Diagram Fix

site/app/libraries/Core.php, site/phpstan-baseline.neon
We use `(string) Lcobucci\JWT\Token` in a handful of places which is deprecated, and the suggestion is to use the `toString()` method instead.
Use the `toString()` method.
Should have no impact on behavior as `(string)` cast calls `toString()` under the hood.
=> [Refactor:Developer] Fix deprecation warnings for JWT lib

Vagrantfile
The Vagrantfile uses a random user's generated box image to support arm64 architectures, as at the time, bento project had not yet release their own official version of it.
Bento now releases `arm64` versions of their images, and so we can switch back to using those, and so should have image compatibility between the `x86_64` and `arm64` images and how they function.
I ran `vagrant up` on a M1 mac to validate that the image works on arm64 architectures. Running https://github.com/Submitty/Submitty/actions/runs/2607599868 to validate nothing broke with `x86_64` OSes.
GitHub does not offer an `arm64` compatible machine, so we cannot add to our vagrant up matrix nightly testing of the arm64 variant, and just have to rely on regular testing of end users.
=> [Refactor:Developer] Use official bento arm64 vagrant image

site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig, site/public/templates/grading/OverallComment.twig
In the grading interface, there are console errors related to already defined identifiers when trying to view multiple pdfs in a session. This prevents later pdfs from loading.
There are also warning related to undefined variables.
Removes the corresponding console errors and users can view multiple pdfs in a session.
=> [Refactor:TAGrading] PDF console errors

site/app/templates/grading/electronic/EditPeerComponentsForm.twig
Closes #8091
In peer gradeables, a grader will get a server error when trying to grade a student who has already been graded by other peers.
Removes the server error.
=> [Bugfix:TAGrading] Peer grading sever error

site/app/libraries/Core.php
If a course's `config.json` file is inaccessible then an error message is shown recommending to restart `php-fpm` using the command `sudo service php7.2-fpm restart`.
Support for `php7.2` was dropped, so the command has been changed to `sudo service php7.4-fpm restart`.
The old error message was misguiding at times because running the advised command would result in error `Failed to restart php7.2-fpm.service: Unit php7.2-fpm.service not found.`
=> [Bugfix:Developer] Update config.json error message

site/app/libraries/Core.php
Right now, we hardcode the version of `php-fpm` that should be restarted as part of the config.json error message. Anytime we move to a new version of Ubuntu, this version string would need to be updated, and it's easy for us to miss doing that (e.g. we've been using Ubuntu 20.04 for most people for well over year and half or so, and the message was only just updated to be `php7.4-fpm` today in #8145.
Instead of hardcoding the version, we can just leverage the `PHP_MAJOR_VERSION` and `PHP_MINOR_VERSION` constants instead, and so the error message will give the appropriate service restart command for the version of PHP that's on the OS, useful for when we start testing / moving to Ubuntu 22.04 which ships with PHP 8.1.
=> [Bugfix:Developer] Use version constants for config message

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/install_submitty/install_bin.sh, .setup/pip/system_requirements.txt, sbin/cleanup_old_email.py
Old emails, that have been successfully sent without error, are accumulating in the emails table of the main database.
This PR adds a sbin/cleanup_old_emails.py script that will purge the oldest emails that didn't have any error and were successfully sent.
This script takes 2 optional arguments:
- the number of days of sent email records to preserve (default 360)
- the maximum number of emails to delete per call to this script (default 10,000)
This script is called from the INSTALL_SUBMITTY.sh script.
Closes #3326
=> [Feature:System] cleanup old emails from Database

site/app/controllers/course/CourseMaterialsController.php, site/app/libraries/FileUtils.php
The folders that have no files in the course materials page are not shown in the frontend but they persist inside the filesystem.
Steps to reproduce:
1.) Create a folder by specifying an optional subdirectory such as "outer" in "Upload Course Materials" and upload a file inside it.
2.) Delete that file using the interface, the folder will no more be shown as it has no files.
3.) Go to the relevant course_materials folder in the system e.g. `/var/local/submitty/courses/s22/blank/uploads/course_materials`
4.) See that the folder that was invisible on the interface is still there in the system.
The redundant empty folders are removed from the file system and also removed using entity manager. This also applies to nested folders such as outer/inner/file.txt. This prevents long empty folder …
=> [Bugfix:CourseMaterials] Remove redundant folders 

grading/load_config_json.cpp
Closes #5712 
The issue was fixed in #6815.
This PR adds a new parser for stringified `max_submission_size`.
- Accepted format: `"\d+ ?([KMGT]i?)B?"`
- `SI` format (`KB, K`) will be converted using base 1000
- `IEC-i` format (`KiB, Ki`) will be converted using base 1024
- Testing
- Manually compile the `configure.out` using `g++`, follow `INSTALL_SUBMITTY_HELPER.sh#L522-568`
- Run the `configure.out`
- Use `grep` to parse the output (`jq` cannot deal with `uint64_t`)
- See details below
- Examples
- `2333` will not be parsed, and stays as numeric `2333`
- `"2333"` will be parsed as byte, to numeric `2333`
- `"233 kib"` will be parsed as IEC-i `Kibibyte`, `238592`
- `"233 mb"` will be parsed as SI `Megabyte`, `233000000`
- `"-233k"` will cause `invalid_argument("Wrong format")`
- …
=> [Feature:Autograding] Max Submission Size String

site/app/templates/course/UploadCourseMaterialsForm.twig
Text was left unchanged in upload course materials form in #8150.
It has been tweaked to be consistent with edit course material form and edit folder form.
=> [UI/UX:CourseMaterials] Text tweak in upload form

site/cypress/integration/courseMaterials.spec.js
#8122 just got merged, #8088 (merged a couple of days back) added cypress tests that assume an empty course materials page, therefore, the tests fail currently.
Newly added tests have been modified to work correctly in the presence of sample course materials.
=> [Testing:Developer] Modified course materials tests

site/cypress/integration/courseMaterials.spec.js
#8083 was recently merged, it added some tests that assumed course materials page to be empty but CI tests have sample course materials after #8122 was merged; therefore, Cypress tests fail currently.
Tests have been modified to work correctly in the presence of sample course materials.
Additional information:
To test locally, delete all the course materials in "sample" course and upload [sample_course_materials.zip](https://github.com/Submitty/Submitty/files/9122623/sample_course_materials.zip) with "Unzip" checked and remember to set the release date to a past date.
=> [Testing:Developer] Modified folder edit form tests

site/app/libraries/database/DatabaseQueries.php
There is no guaranteed order of proxy users on the SAML management page.
The list of users is now sorted by SAML ID then by Submitty ID.
Partially resolves #8166
=> [Bugfix:System] Fix ordering on SAML management page

.setup/untrusted_execute.c, autograder/autograder/execution_environments/jailed_sandbox.py
Untrusted execute will throw `SIGCHLD` if it encounters any internal errors.
`SIGCHLD` is also used in `waitpid` and will cause excessive unrelated error logs in student's submission result.  If the system load is high enough, this might fail the autograding process.
Untrusted execute will throw `SIGUSR2` if it encounters any internal errors.
`SIGUSR2`'s default behavior (without handling) is stopping the target process, which might be dangerous.
Tested with ~2000 sample submissions, and it probably should work...
This could be tested through 
```bash
trap "echo got sigusr2" SIGUSR2         # capture SIGUSR2
chmod 777 sbin/untrusted_execute        # force error for untrusted_execute
./untrusted_execute                     # should get SIGUSR2
sudo su submitty_daemon -c …
```
=> [Bugfix:System] Change Signal for untrusted_execute

.gitignore, .setup/install_submitty/install_site.sh, site/tsconfig.json
Right now tsc and esbuild are called for all typescript/mjs code. esbuild is pretty fast but tsc takes a lot of time since it has to typecheck all files from scratch.
Incremental building was added for tsc to speedup the typecheck time (Results listed below). This adds an `incremental_build` folder inside of `/usr/local/submitty/site` where any incremental build files get stored. This will help developers primarily so they don't have to wait as long for this script to finish.
This lists the time taken to run just a site install of Submitty:
- Before incremental: 21 seconds
- After incremental: 6 seconds
NOTE: You won't feel the effects of the speedup until you have run it at least once because it needs to create the first initial incremental build. After that all builds will be …
=> [Feature:System] Add incremental build for tsc

site/app/templates/autograding/TAResults.twig, site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig, site/app/views/AutoGradingView.php, site/public/js/pdf/PDFAnnotateEmbedded.js
The view/download functionality for annotated pdfs does not function correctly when in the view grade and grading interface. Annotations created by one user can only be downloaded by the same user. The bug is brought up by #8018. 
All annotations can be viewed/downloaded.
=> [Bugfix:TAGrading] View/Download Annotations

.setup/bin/update_repos.sh
Submitty installation message did not state how to solve the issue I had with a repo being out of date.
Added a helpful message to give a possible solution to the user.
When users have a repo cloned locally (or with history), the installation script skips updating them to be safe. This message makes it more clear what should be done so the installation can proceed.
=> [Feature:System] Helpful message for cloning repos

site/app/models/RainbowCustomization.php
It is possible for null values to end up in the generated customization.json file. This happens when a new gradeable is created and does not exist in the current customization.json. The page also throws a lot of errors in this case when in debug mode.
The errors on the page are now gone. The default override value is now set to the same value as the current max score which will prevent these null values.
=> [Bugfix:RainbowGrades] Fix Web Customization

site/app/libraries/Output.php
Max nesting level hasn't been enforced for Markdown. It was identified that this can make a discussion forum thread inaccessible for everyone. At the very least, this can make pages slow to load.
The issue has been fixed.
=> [SECURITY][Bugfix:Forum] Enforce max nesting level

.setup/worker_rsync_exclude.txt, sbin/shipper_utils/update_and_install_workers.py
All GIT_CHECKOUT folder is copied to workers.  If the vagrant is not carefully configured, `.vagrant` which contains VHD may also be copied.
When the primary machine syncs folders to the workers, it will read `.setup/worker_rsync_exclude.txt` and avoid copying these files/folders.
Tested with the procedure below:
1. Clear the worker's `/usr/local/submitty/GIT_CHECKOUT`
2. `INSTALL_SUBMITTY` on primary machine
3. Check the excluded files in the worker
=> [Feature:System] Worker Update Excluding List

site/public/js/forum.js
- If the scroll bar is at the upper end of the thread list, the up arrow on the scroll bar is not greyed out.
- If the scroll bar is at the upper end of the thread list, the up arrow on the scroll bar will now be greyed out.
**How did you test**
- Go to a "Discussion Forum" page (I tested in the Discussion Forum in "sample" course)
- Scroll to the top of the thread list and check if the up arrow on the scrollbar is greyed out. 
- Select a Forum Thread. Scroll to the top of the thread list and check if the up arrow on the scrollbar is greyed out.
=> [Bugfix:Forum] Grey Scrollbar Up Arrow at Top of Forum

grading/main_validator.cpp, tests/integrationTests/tests/minimal_code_editing/validation/noise_results.json, tests/integrationTests/tests/minimal_code_editing/validation/tabs_results.json, tests/integrationTests/tests/python_custom_validation/validation/results.json_correct, tests/integrationTests/tests/python_custom_validation/validation/results.json_not_random, tests/integrationTests/tests/python_custom_validation/validation/results.json_wrong_num
Fixes #5621 
Success and information messages shown when `show_messages: always` is set in config.json. Custom validator success and information messages shown.
=> [Bugfix:Autograding] Success, information messages not shown

.setup/install_submitty/install_site.sh
When installing the site, the permissions may not be correct on the incremental_build folder for typescript compilation. This causes the site JS files to not get properly built.
This PR ensures that the PHP user has proper permission to write to any file previous created.
Tested it locally and it fixed the problem for me.
=> [Bugfix:System] Fix Incremental Build Permissions

migration/migrator/migrations/course/20220612122726_gradeable_specific_anon_ids.py, site/app/models/Team.php, site/tests/app/controllers/student/TeamControllerTester.php, site/tests/app/models/TeamTester.php
#8002 was recently merged, `anon_id` column was removed from the users table and `setup_sample_courses.py` was modified to directly set `anon_id` in `gradeable_anon`. Accompanying migration extracted `anon_id` from users table to insert inside `gradeable_anon` but there may be users with null `anon_id` when migration runs, so running `submitty_install` currently throws an error.
A check has been added to move `anon_id` only if the column exists and is not null. An issue identified by Jerry (@Viyerelu23333) has also been fixed.
=> [Bugfix:Developer] Anon id migration fix

site/public/js/confetti.js
- Fixes #8213 
- When the user plays the confetti animation and switches off of the gradeable submission page's tab, the confetti bunches up and is dropped at once when the user returns to the submission page's tab.
- When the user switches off of the gradeable submission page, the confetti animation will be paused. Upon returning to the submission page, the confetti animation will be resumed.
**How did you test**
1. On a gradeable that received a perfect score on the auto-grading, select "Autograding Total" to play the confetti animation.
2. Change to a different tab and wait for a few seconds.
3. Return to the submission page's tab and see if the confetti does not bunch up and the animation resumes.
4. Play the confetti animation again.
5. Minimize the browser and wait for a few …
=> [Bugfix:Submission] Pause Confetti Animation

autograder/autograder/autograding_utils.py, autograder/autograder/execution_environments/container_network.py, autograder/autograder/execution_environments/jailed_sandbox.py, autograder/autograder/execution_environments/secure_execution_environment.py, autograder/autograder/testcase.py
Docker container info is logged to a file called `meta_log.txt`
The file is now named `container_log.txt` and the names of some functions and variables have been updated similarly.
=> [Feature:Autograding] Rename meta_log.txt to container_log.txt

site/composer.json
We had set the `config.platform.php` value in the `composer.json` file to 7.2 so that no matter what version of PHP the host system was using, it would only try to use packages that were 7.2 compatible. Given that we've dropped Ubuntu 18.04 and our new minimum version is 7.4, we can bump the value.
Set the value of `config.platform.php` to 7.4 to match our new minimum supported version. This will allow installing and updating packages to versions that did not support 7.2 (e.g. phpunit 9.x or twig 3.x). 
Vagrant up run: https://github.com/Submitty/Submitty/actions/runs/2611293412
=> [Bugfix:Developer] Update minimum PHP version for composer

site/public/js/ta-grading.js
In the file viewing page, the missing `gradeable_id` in the `iframe` source causes a permission error.
`gradeable_id` is added for TA grading page.
=> [Bugfix:TAGrading] Fix missing gradeable_id in display file

.github/workflows/submitty_ci.yml, site/app/views/forum/ForumThreadView.php
Recently, the minimum PHP version for composer was upgraded to `7.4`. Installing `PHP 7.4` dependencies now causes `php-lint` and `php-unit` to fail. Also, `php-lint` fails due to usage of deprecated flags.
See [this workflow run](https://github.com/Submitty/Submitty/runs/8003796747?check_suite_focus=true) and [this one](https://github.com/Submitty/Submitty/runs/8003849332?check_suite_focus=true) (for flags).
PHP version for CI has been updated to `7.4` and usage of deprecated `FILTER_FLAG_SCHEME_REQUIRED` and `FILTER_FLAG_HOST_REQUIRED` has been removed (see [https://stackoverflow.com/a/45240693](https://stackoverflow.com/a/45240693)).
=> [Testing:System] Update CI to use PHP 7.4

site/composer.lock
Somehow the platform version had gotten out of sync between `composer.json` and `composer.lock`. Even though the platform version is `7.4` in the `composer.json` it was `7.2` in the `composer.lock`. This caused dependencies to think an older version of PHP was installed when it was actually bumped up recently.
This is causing recent dependabot upgrade PRs for PHP dependencies to fail since it cannot no longer perform composer installs on CI
Manually edited composer.json to have matching platforms
For developers, the platform config might be convenient but for CI since we control the version everytime maybe we can just ignore platform dependent requirements in the future in the github workflow. Or maybe there isn't a need for the platform config anymore?
More information here …
=> [Dependency] Set composer.lock platform version to PHP version

autograder/submitty_autograding_shipper.py
Closes #8280 
When bulk regrading, there are `BadZipError`s from the worker, and `FileNotFoundError` from the shipper.
Workers read the queue file in `autograding_TODO` before starting the grading process.  
The shipper writes the queue file to the `TODO` folder directly if the worker is `localhost`.
Workers in the primary machine may start grading before the autograding/submission zip files are copied.
When autograding, there should be no `BadZipError` or `FileNotFoundError`.
Instead of dumping the queue file to the `TODO` folder, shipper will write the queue file to `/tmp` and copy it after the zip files are copied.
`copy_files()` of the shipper will append `_COPYING` to the file names when copying, after they are copied, they will be changed back to the original name.
=> [Bugfix:Autograding] Fix BadZipError

site/public/js/server.js
`openFrame()` in the `server.js` doesn't include `gradeable_id` in the route.
`openFrame()` in the `server.js` now includes `gradeable_id` in the route.
Thank @akshatbatra for pointing out this problem.
=> [Bugfix:TAGrading] Fix missing `gradeable_id`

migration/migrator/data/course_tables.sql, migration/migrator/data/submitty_db.sql, migration/migrator/migrations/course/20220828143054_add_user_anon_trigger.py, migration/migrator/migrations/master/20220827110746_trigger_update_delete_user.py, sbin/adduser_course.py, sbin/anonymize.py, site/app/libraries/database/DatabaseQueries.php
If a student is added to a course after one or more gradeables have been created, the student will not have an anon id for that gradeable, this causes several bugs.
Whenever a user is created, `gradeable_anon` is populated with anon ids for existing gradeables.
Another issue related to deleting a user was identified:
It is impossible to delete a user even though they didn't have any record of interactions; to fix this, a migration has been created, the function isn't new, a minor change in an already existing function has been done.
A migration has been added that adds the missing anon ids, the same migration also adds a trigger to automatically insert required rows in `gradeable_anon` table whenever insertion happens in `users` (course) table.
Running the migration is all that is needed, …
=> [Bugfix:Submission] Adding and deleting users

.setup/distro_setup/setup_distro.sh, .setup/distro_setup/ubuntu/20.04/setup_distro.sh, .setup/testing/setup_ldap.sh, .setup/vagrant/setup_ldap.sh
When the vagrant system is installed, LDAP doesn't get fully set up because it is missing a couple commands. So when the setup_sample_courses script tries to add the users it fails on them and there are then 0 ldap users. There was also a bash syntax error from #6815.
The testing LDAP and vagrant LDAP now use the same script and it works locally. This should also help us detect problems like this earlier for LDAP. The bash syntax issue has been fixed.
I tested locally with LDAP and SAML and they both worked.
=> [Bugfix:System] Fix LDAP install on vagrant

site/app/controllers/GlobalController.php
#8362 changed the style of the `fa-copy` icon as part of the addition of a new "sharp" family of icons.  The new copy icon looks like [this](https://fontawesome.com/icons/copy?s=solid&f=classic), which is a change from the "two documents" style which existed previously. 
The previous "two documents" look does not appear anywhere in the current set of FA free icons so I have replaced the course materials icon with a single "file" icon (see screenshot for the new look).  Other possibilities for the replacement icon are [`fa-folder`](https://fontawesome.com/icons/folder?f=classic&s=solid) and [`fa-folder-open`](https://fontawesome.com/icons/folder-open?f=classic&s=solid).
=> [UI/UX:CourseMaterials] Change course materials icon

.setup/install_submitty/install_site.sh, site/app/libraries/routers/WebRouter.php
Currently only the annotations get cached in WebRouter. This still leaves a huge performance bottleneck as it has to collect all the routes every request.
The annotation cache has been swapped out for a route cache. The annotations don't need to be cached since we only fetch them once per install when we need to update our route cache. This greatly improves performance per request which is noted below.
Note about debug mode: You'll see we don't rely upon debug mode for the cache anymore. I tried implementing this but it made the debug mode noticeably slower. Most developers use code watcher and will be running install_site each code change, thus clearing the route cache. This may effect PHPStorm users which I use but a quick run of install_site when editing routes is not an issue …
=> [Refactor:System] Cache Symfony routes

site/public/js/plagiarism.js
JSON parsing errors are a common symptom of issues with the plagiarism results interface, but are difficult to debug when the route and corresponding response data are not available.  These types of errors are often reported in the production environment, but are much more difficult to track down in the development environment.
This PR adds a few logging commands which print out the relevant route and response when a parsing issue occurs.  The exception is then re-thrown so it is visible in the console and will cause testing tools like Cypress to fail if it occurs.
=> [Refactor:Plagiarism] Improve JSON parse error logging

site/app/templates/forum/ForumBar.twig
When viewing a forum with merged threads in anything but the wide view, the Twig variable `is_full_threads_page` is left undefined, which results in a JS syntax error due to the ternary expression on line 18.
The `dropdownLabel` ID does not appear anywhere in the codebase except for this location, so I have removed all of the related logic, including the buggy line.
=> [Bugfix:Forum] Remove dead code causing JS syntax issue

grading/execute.cpp, tests/integrationTests/tests/python_simple_homework/validation/test01_execute_logfile.txt_infinite_loop_time_cutoff
Closes #3147 
- python out of memory
- c++ out of memory
- infinite loop
=> [Feature:Autograding] Descriptive kill,terminate message

site/public/js/gradeable.js
The TA grading rubric does not display the note to students, only the note to TAs.
Fixes #8382 
The TA grading rubric now displays both the student and TA notes when both are filled in.
Testing was done by filling in the student note only, TA note only, and both the student and TA notes and making sure the note(s) are displayed accordingly.
=> [Bugfix:TAGrading] Display "Note to Student" in TA grading

site/app/controllers/admin/UsersController.php
If a student is added manually through individual or classlist upload AND they don't have a Submitty account, they will not be added to the SAML mapping table.
Closes #8445
When new Submitty users are added, a SAML mapping is created for them allowing them to log in.
Tested locally with a new account and it works now.
=> [Bugfix:InstructorUI] Manually Added SAML

site/app/templates/plagiarism/PlagiarismConfigurationForm.twig
Code to disable the "Save and Run Configuration" button on the plagiarism interface when it is clicked to prevent double-clicking was broken some time ago, resulting in a persistent error in the console about an undefined variable.
The form has been given an id and the code to disable the button has been changed to work properly.
To test these changes, create a configuration and click the "Save and Run Configuration" button several times.  Observe that the button is disabled after the first click, preventing errors about duplicate runs from appearing.
=> [Bugfix:Plagiarism] Disable submit button on form submission

site/app/controllers/student/GradeInquiryController.php
Grade inquiries assume only a single user can make a grade inquery, the submitter_id was used to try and get the submitter which doesn't work when the 'submitter' is a team. In that case, the team_id would always return a bad submitter preventing any grade inquiry functionality  
Grade inquiry controller now uses the `getSubmitterById` function instead of `getUserById`, this allows grade inquiries to handle submissions by both teams and individuals. Also removed a duplicate check when seeing if there's a fast path to allowing a grade inquiry option, the `graded_gradeable->getSubmitter()->hasUser($user) ` was already checking if the given user's team or user id was part of the graded_gradeable submitter(s)
Tested opening and replying to grade inquiries and their websocket functionality.
=> [Bugfix:Submission] grade inqueries on team gradeables

site/app/controllers/admin/PlagiarismController.php, site/public/js/plagiarism.js
It is currently possible to try to switch to any version for a user as long as that user has at least one match on at least one version.  An error is currently displayed when a user attempts to navigate to a version which has no matches. 
It is now possible to view versions with no matches in the left panel without errors appearing.  A notice is displayed in the right panel indicating that there are no matches as seen in the following screenshot:
=> [Bugfix:Plagiarism] Support viewing versions with no matches

site/app/controllers/grading/ElectronicGraderController.php, site/app/controllers/grading/SimpleGraderController.php
If you create an electronic gradeable, you can visit the numeric grade view of that gradeable which does not make sense. You can also attempt to do the reverse where you view a numeric gradeable as an electronic gradeable but it creates a frog robot error.
Fixes #8509
If you attempt to go to the wrong route for grading a gradeable, it will redirect you to the correct one.
Tested locally and it redirected properly.
=> [Bugfix:TAGrading] Correct gradeable type on grading page

site/app/controllers/admin/UsersController.php, site/app/controllers/superuser/SamlManagerController.php, site/app/templates/superuser/NewProxyUser.twig
If you try to add a proxy user from the SAML management page, it will fail. Also it marks numeric ID as optional when it is required.
I made sure both IDs get checked for valid usernames in SAML before doing the check preventing new users from being added. I also marked numeric IDs as required on the page.
Tested locally and it now works.
=> [Bugfix:System] SAML Add Proxy User Fix

site/app/controllers/DockerInterfaceController.php
We rely on the Docker Hub API version 1 to check if an image is valid. The API has been marked as deprecated and thus does not work anymore.
The Docker interface page uses Docker Hub API version 2 now.
=> [Bugfix:System] Update Docker Hub API to v2

site/app/libraries/database/DatabaseQueries.php, site/app/models/gradeable/GradedComponent.php
Every time a GradedComponent is created, if a verifier_id exists it fetches the database for the verifier User. In a gradeable with a lot of verified marks this can get very expensive.
The verifier user was added to our GradedGradeable query so that info can get picked up there if it exists.
I tested this and I could still verify graders and see that marks were verified.
=> [Refactor:TAGrading] Fetch Verified Grader Eagerly

sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
Flake8 recently started failing on CI runs.
The Flake8 error has been resolved.
=> [Testing:Developer] Fix broken flake8 tests

migration/migrator/migrations/course/20221026040934_add_gradeable_component_indexes.py, site/app/libraries/database/DatabaseQueries.php
Query for retrieving graded gradeables is slow; a query run on the "Gradeables" view in "sample" course took 1.218 seconds
Query time for retrieving graded gradeables has been improved - changed the join for gradeable_component_data to be a lateral join to allow for filtering before joins with gradeable/gradeable_data - when tested, query performance on the same view improved to 19.1 ms.
Added index on gradeable_component_data for gd_id - when tested, query performance on the same view improved to 9.01 ms.
=> [Refactor:Submission] Improve graded gradeable query

site/app/templates/course/CourseMaterials.twig
Closes #8420
Currently there is a button "Open/Close All Folders" for teachers on the course materials page which expands all folders. However, this button is missing for students.
Adds the "Open/Close All Folders" button for students with the same functionality.
=> [Bugfix:CourseMaterials] Open/Close All Folders for Students

.setup/vagrant/setup_vagrant.sh, .shellcheckignore
Closes #8483 
Ubuntu server by default uses logical volume with ~31 GiB.  This applies to the vagrant VM.
When vagrant initializes Ubuntu server, it also expands the LV to ~62 GiB.
Tested with `vagrant destroy` and `NO_SUBMISSIONS=1 vagrant up`.
=> [Feature:System] Expand Logical Volume on Setup

migration/migrator/data/course_tables.sql, migration/migrator/data/submitty_db.sql, migration/migrator/migrations/master/20221028192745_registration_section_main_to_course.py
Edits to registration type used to be made in the course database and were not updated automatically in the main database. This left different data in both the main and course databases if the registration type was changed for any user.
This adds a migration that fires the trigger to copy the data from the main database into the course databases so that the data is consistent in both.
Tested by manually editing users' registration type in course databases and checking that the data in the main database gets copied to replace the changed values when running the migration.
=> [Bugfix:System] sync registration type, main->course db

site/app/views/AutoGradingView.php
The "Graded by" display name is now "Preferredfirstname Preferredlastname" instead of just "Preferredlastname."
Closes #8431
=> [Feature:TAGrading] "Graded by" display name change

site/app/libraries/Access.php
Limited access graders could access gradeables that they should not be able to.
Limited access graders now can only access gradeables they have access to.
=> [SECURITY][Bugfix:TAGrading] Fix Limited Access Grader Access

site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig, site/public/css/admin-gradeable.css
Closes #8403 
Added the following note under Grades Released Date on the Edit Gradeable page:
"Note: Released Grades for checkpoint and numeric gradeables are available to students only through Rainbow Grades."
=> [Feature:InstructorUI] Add note for Grades Released Date

site/app/libraries/Access.php, site/phpstan-baseline.neon, site/tests/app/libraries/AccessTester.php
Fixes #8303
Peer graders can grade unassigned students if anonymous id of the student to grade is known.
Peer graders can only grade students assigned to them; "you don't have access..." error page is shown if they try to grade unassigned students.
=> [SECURITY][Bugfix:TAGrading] Peer grading access control

migration/migrator/migrations/course/20221029145443_fix_permissions.py, sbin/create_course.sh
After a course is created, only the current tables and sequences get granted permission to the course database user. This creates issues for any new table or sequence.
Default permissions are now set for course databases. A migration was added to fix any potential new courses that don't have the correct permissions.
=> [Bugfix:System] Fix Course DB Permissions

site/app/libraries/database/DatabaseQueries.php
If a queue is empty, it will not get shown. This is due to a query having a WHERE clause that doesn't function when there is 0 students in a queue. This got added in #8585.
All queues are shown even if empty as expected. The WHERE clause has been removed.
Tested loading the page locally and hidden queues became visible.
=> [Bugfix:HelpQueue] Fix Empty Queues Not Showing

.setup/install_submitty/install_site.sh
The installation script deletes the cache annotation directory.
Closes #8404
The installation script no longer deletes that directory as it should definitely be gone now.
=> [Refactor:System] Remove Annotation Cache Removal

site/public/css/course-materials.css, site/public/js/server.js
The material name provided by an instructor may contain XSS payload which will get executed when a user tries to delete that particular course material.
The user provided file name is treated as text instead of HTML, thereby preventing execution.
Thanks @cjreed121 for finding this vulnerability.
=> [SECURITY][Bugfix:CourseMaterials] Treat name as text on delete form

migration/migrator/migrations/course/20221104203732_grading_registration_index.py
When creating a `User` model, the `user_registration` table is queried.  Since there is currently no index on the `user_id` column, this query is slow.  Since this query is run on nearly every page load, optimizations have the potential to make a significant impact.
An index was added to the `user_id` column of the `user_registration` table for more efficient lookup.
=> [Refactor:System] Add index to user_registration table

migration/migrator/migrations/course/20221104210520_notifications_index.py
Multiple queries currently select notifications by the person each notification was sent to.  In particular, the notifications badge on the sidebar makes this query every time a course page is loaded.  Since the notifications table is quite large (potentially on the order of tens of thousands of rows or more for large classes), this can easily create a significant slowdown.
This PR simply adds an index to the `to_user_id` column of the `notifications` table, to allow more efficient querying of notifications by user to which it was sent.
=> [Refactor:System] Add index to notifications table

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20221207220918_gradeable_allowed_minutes_index.py, migration/migrator/migrations/course/20221207223331_gradeable_component_mark_data_gcm_id_index.py, migration/migrator/migrations/course/20221208001513_grading_registration_user_id_index.py, site/app/controllers/grading/ElectronicGraderController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/Team.php, site/app/models/User.php, site/app/templates/grading/electronic/RubricPanel.twig, site/app/views/grading/ElectronicGraderView.php
The individual grading page currently makes in excess of 100 database queries for most gradeable+student combinations.  This causes the grading page to be one of the slowest pages across the entire Submitty website.  This slowness is detrimental to those who use this interface to grade hundreds of students per week.
This PR reduces the number of queries from more than 100 to roughly 60 queries on the grading page, with further improvements expected in future PRs.
Repetitive queries were simplified in several places.  Additionally, several new indices were added to improve query lookup time for some of the more important queries.  Since many of these changes affect queries which are run on other pages such as the gradeables page and grading index page, these changes should also benefit the …
=> [Refactor:TAGrading] Grading page performance

sbin/submitty_daemon_jobs/submitty_jobs/bulk_qr_split.py, sbin/submitty_daemon_jobs/submitty_jobs/bulk_upload_split.py
The splitted images for the uploaded pdfs in bulk submission currently take too much space.
The total size reduces to around 20% of the original total size.
=> [Refactor:Submission] Reducing splitted jpg sizes

migration/migrator/data/course_tables.sql
A database dump was forgotten for https://github.com/Submitty/Submitty/pull/8586 and https://github.com/Submitty/Submitty/pull/8587, which added two indices.
This PR updates the database dump to ensure that new courses can be created properly.
=> [Bugfix:System] Update database dumps

site/app/controllers/PollController.php
Currently students can be able to see closed polls using URL manipulation
Closes #8668 
When polls are closed, students will no longer be able to see it.
The wording for Submini Polls are kinda confusing. "Closed poll" means a poll that is not visible while "ended poll" means a poll that is no longer accepting submissions (but visible)
=> [Bugfix:SubminiPolls] Poll visibility

migration/migrator/migrations/course/20230111115942_create_missing_gradeable_team_anon_ids.py, site/app/libraries/database/DatabaseQueries.php
When creating a team for a gradeable, an anon_id is not automatically generated for it (generated when getAnonId).
When creating a team for a gradeable, an anon_id is automatically generated as part of the creation process.
A migration has been added to fix cases in the database where an anon_id was not generated for a team (when creating teams using the bulk-upload interface).
=> [Bugfix:Submission] Generate team anon id on creation

site/app/controllers/admin/ReportController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/User.php
The `user_numeric_id` column of the `users` table is not included in the grade summaries.
The `user_numeric_id` column is included in grade summaries data so it is written to the JSON files generated.
Closes #8552
=> [Feature:RainbowGrades] Add user_numeric_id to exported data

site/app/libraries/Utils.php, site/app/libraries/database/DatabaseUtils.php
`formatQuery` function in `site/app/libraries/database/DatabaseUtils.php` throws an error if `$param` is an array.
`formatQuery` function can now handle an array (`$param`) inside `$params`.
This issue was discovered while working on #8615 where the following query is generated:
`SELECT t0.id AS id_1, t0.path AS path_2, t0.type AS type_3, t0.release_date AS release_date_4, t0.hidden_from_students AS hidden_from_students_5, t0.priority AS priority_6, t0.url AS url_7, t0.url_title AS url_title_8, t9.id AS id_10, t9.user_id AS user_id_11, t9.timestamp AS timestamp_12, t9.course_material_id AS course_material_id_13, t14.section_id AS section_id_15, t14.course_material_id AS course_material_id_16 FROM course_materials t0 LEFT JOIN course_materials_access t9 ON t9.course_material_id = t0.id …
=> [Bugfix:System] Handle array while formatting query

site/app/controllers/student/SubmissionController.php
Regrading a Git gradeable through the web interface does not work.
The queue files are now created with the proper information to indicate it is a VCS gradeable so the web interface works.
Tested with a sample Git gradeable using one of the autograding example configs. Closes #8758.
=> [Bugfix:TAGrading] Fixed regrade button for Git gradeables

.setup/install_system.sh
The preferred_name_logging.php script was removed in PR:
https://github.com/Submitty/SysadminTools/pull/23
But the install_system.sh script was not updated at that time
NOTE:  I believe we did not catch this error because we did not name a release for the SysadminTools repo, so most people did not get the update.
This PR comments out the installation.  But we need to modify the installation to correctly install the newer version.   Just opened issue #8778
=> [Bugfix:System] SysadminTools preferred_name_logging

site/app/models/OfficeHoursQueueModel.php
https://github.com/Submitty/Submitty/pull/8786 missed one location where strings were not updated to use the given/family name convention.  This results in a PHP error when users are removed from the help queue.  The error does not affect the majority of the page rendering, and will not be displayed on production (although it will still show up in the log of course).
The strings have been updated to fix the PHP error.
Note: do not merge until tests pass.
=> [Bugfix:HelpQueue] Removing students causes PHP error

.github/workflows/submitty_ci.yml
Updated the Submitty CI Github Workflow, moving away from the use of `::set-output` and `::save-state`, which have been deprecated by GitHub since October 2022 and will no longer function starting in May 2023 as outlined in [this article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
* All usage of `::set-output` has been refactored to write to the new `$GITHUB_OUTPUT` file.
* The outdated dependency `actions/cache@v2` has been updated to `actions/cache@v3`.
=> [Testing:Developer] Update GH Workflow to use new env files

site/app/controllers/admin/ReportController.php, site/app/libraries/PollUtils.php, site/tests/app/libraries/PollUtilsTester.php
The poll export functionality during the Grade Reports generation process currently produces files which do not contain enough data to associate student responses with the polls the students responded to.
A missing `id` field was added to `poll_questions.json` and the numeric identifier for each response in `poll_responses.json` was switched to `order_id` from `option_id`.
Both of these changes fix bugs introduced by https://github.com/Submitty/Submitty/pull/6708.
=> [Bugfix:SubminiPolls] Broken poll export for rainbow grades

.setup/install_submitty/install_site.sh, sbin/doctrine.php, site/app/libraries/Core.php
Currently Doctrine proxy classes get generated while the code is running if we are in debug mode. If it's in production mode then it is expected the proxy classes are made which never happens. This leads to white screen errors on a couple pages after PR #6708.
* A new directory inside the cache directory is created for these proxy classes
* A doctrine php executable was added which will make the proxy classes
* The installation script will clear the proxy classes directory and regenerate the proxy classes during each install
Tested on a mock production server and it works as expected.
=> [Bugfix:System] Make doctrine proxy classes upon install

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20230131131716_add_index_gcmd_gd_id.py, site/app/libraries/database/DatabaseQueries.php
An index on gradeable_component_mark_data added for gd_id, avoiding a sequential scan of the table and reducing the average query cost directly related to that table from ~3 ms to ~0.12 ms (getGradedGradeablesUserOrTeam).
=> [Refactor:Submission] Gradeables query improvement

site/app/templates/forum/ThreadPostForm.twig, site/app/templates/misc/MarkdownArea.twig, site/public/templates/misc/MarkdownArea.twig
Currently, whenever I try to post an empty post, Submitty makes a network request to the server which rejects the post due to the lack of text.
Fixes #8696
Textareas are required so some text has to be in them. This means that checking the post is not empty is done client side and saves a full network request.
=> [Bugfix:Forum] Add required attribute to textareas

.github/dependabot.yml
https://github.com/Submitty/Submitty/pull/8788 mistakenly added invalid YAML to the `dependabot.yml` file, which has been causing intermittent errors on various PRs since https://github.com/Submitty/Submitty/pull/8788 was merged.  It is unclear why the tests on the PR did not pick up the failure.
`dependabot.yml` now passes [this](https://jsonformatter.org/yaml-validator) online validator, which is suggested by GitHub.
=> [Bugfix:Developer] Fix invalid YAML in dependabot file

.github/dependabot.yml
The `open-pull-requests-limit` key/value for the final block is incorrectly nested under `schedule`, and I'm seeing an error for some dependabot PRs due to it (e.g. https://github.com/Submitty/Submitty/pull/8839/checks?check_run_id=11226342389).
The `open-pull-requests-limit` has been moved to the appropriate level. I've also added the `labels` and `commit-message` block so that PRs opened for GH actions have the appropriate label and prefix.
=> [Bugfix:Developer] Fix incorrect dependabot config

.gitignore, Vagrantfile
Currently, the Vagrant file is set to override boxes based on virtual machine. This is redundant because both virtual machines used for Submitty are configured to use the same box.
Also, a global variable is used to indicate running on an M1 Mac, which appends the string '-arm64' to the box name. This is not a universal naming convention and only works with the current `bento/ubuntu-20.04` box which has a `bento/ubuntu-20.04-arm64` counterpart that serves as an alternative box for parallels desktop on arm64.
There is also no existing way to override the default box specified in the Vagrant file without manually updating the file itself. This makes for a poor development experience as changes made to the box name in the Vagrant file cannot be committed without affecting other users as the …
=> [Feature:System] Vagrant libvirt + remodel box selection

.setup/install_submitty/install_site.sh
There was a warning message:
Removed the warning message by removing the flag in the install_site.sh file:
Closes #8728
=> [Bugfix:System] Removed deprecated --no-suggest

site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
Fixes #8960 "TA/Instructor will (bulk) upload scanned .pdf for online manual grading." because the "no_discussion" field was being check despite forum_enabled disabled
Fixed this by adding a condition to check if forum_enabled is true.
This issue arise after the issue went unnoticed by me in my forum PR  #8832
=> [Bugfix:Submission] Fixes bulkUpload not working 

autograder/autograder/autograding_utils.py
If a symlink exists in the autograding directory, it will try to copy it when moving files around.
When copying files, symlinks will be ignored and left behind.
Autograding still works as expected with this change.
=> [SECURITY][Bugfix:Autograding] Prevent autograder from copying links

site/app/views/forum/ForumThreadView.php
Fixes #8990. Originally if new posts were added to a thread, the creator of that thread would see the thread color as being white instead of blue.
Now, for new posts that were added to a thread, the creator of that thread would see the thread color as being blue.
For an example to see how the change works. If an instructor makes a thread about "Homework Three" and students start to add new posts about this thread that the instructor has seen yet, "Homework Three" would originally be white but is now blue.
=> [Bugfix:Forum] "New" Color on Old Forum Threads

bin/json_schemas/complete_config_schema.json, grading/load_config_json.cpp
The validation schema for the autograding config.json was incorrect for graphics action mouse motion.
=> [Bugfix:Autograding] graphics schema for mouse motion

site/app/controllers/admin/AdminGradeableController.php, site/public/js/admin-gradeable-updates.js
Fixes #9037 The gradeable was not being re locked. it was though to be only limited to that but since the page change only sended depend_on or depend_on_points at a time the locking function wasn't working. 
Both the data values are send at the same time and the depend_on_point also get checked for null value in the controller.
Below is a gif of the implementation working
=> [Bugfix:Submission] Fixes gradeable relocking

site/app/controllers/admin/PlagiarismController.php
If no user exists in the system, even though that userid has submissions being analyzed, the plagiarism results page will fail to load because it can't query the user's name.
If the specified user's name is not available, simply show the user ID, just like we do for team gradeables.
=> [Bugfix:Plagiarism] Handle no user for matching user ID

site/app/templates/polls/PollForm.twig, site/cypress/e2e/polls.spec.js
In the edit poll screen, edit is listed as the title as well as the button to save the changes, which can be misleading.
Change the confirmation button to save changes.
Fixes #9090
=> [UI/UX:InstructorUI] Clarify poll edit confirmation

site/public/css/server.css
Fixes #9160 
The "limited access grader verified" item on the grading index page color key is round now.
=> [Bugfix:TAGrading] Fix color key

site/app/libraries/database/DatabaseQueries.php
The helper function `createParamaterList` in `DatabaseQueries.php` has a typo in the word "parameter".
Fixed the spelling error.
=> [Bugfix:Developer] Fix spelling of DB queries function

site/public/js/confetti.js
Confetti animation will stop based on cumulative animation time, which, however, is cumulated based on the screen's resolution. In that case, checking the time to determine whether to stop is inaccurate. 
More than that, the canvas's height currently will be initialized as a whole web page's size instead of the visible part's size. 
Change the canvas's height to the visible area's height.
Stop animation based on the piece list. When a piece is out of the visible area, it will be removed from the list. In that case, when every piece is out of the screen and no more visible piece, stop the animation. 
Modified the number of pieces based on the screen size so that it will not be too crowded
=> [Bugfix:Autograding] stop confetti automatically

site/public/js/calendar.js
HTML strings are used to create new elements for the calendar. This raises XSS security issues.
Instead of HTML strings, JS elements are created to properly escape any concerning values.
Tested locally and calendar still worked as expected.
=> [SECURITY][Bugfix:Calendar] Change HTML strings to JS elements

autograder/tests/data/submitty_config.json
This changes one of the test configs brought in by #8803 to remove a parameter made obsolete by #8921 
@shailpatels wrote this as a comment for whichever was merged first, to change this afterwards. 
https://github.com/Submitty/Submitty/pull/8803/files/e67fdfc56e927f713f0993c206c37c2f4351c8fe#r1155356109
This change doesn't break anything, and the tests don't have to be edited because it is removing a parameter that wasn't being used in the tests anyway, but it will keep the test configs consistent with the actual configs used. 
I am also unsure if there is a better type/module for this PR's title.
=> [Testing:Developer] Remove Unused Config Parameter

site/app/templates/course/EditCourseMaterialsFolderForm.twig, site/app/templates/course/EditCourseMaterialsForm.twig, site/app/templates/course/SetAllReleaseForm.twig, site/app/templates/course/SetFolderReleaseForm.twig, site/app/templates/course/UploadCourseMaterialsForm.twig
Although the problem of flatpickr elements not being closed properly and some related issues are resolved internally by the newest release, they would still only be scrollable through scrolling on the page directly under the pop-ups they're called in.
Flatpickr instances opened in modals or popups in the Course Materials page on Instructor's UI now will append to the parent elements or html input windows calling them.
Closes #9106 and #4712
This fix utilizes a combination of flatpickr's own configuration and some JavaScript for a temporary solution. In the long run, a replacement of the date-picker dependency or improvement on the pop-up forms across Submitty are expected.
Because flatpickr instances close and save the input only when clicked outside, I limited the trigger for pointer …
=> [Bugfix:CourseMaterials] Fix Datepicker Scrolling

site/public/js/server.js
According to [#issue9207](https://github.com/Submitty/Submitty/issues/9207), if a folder is opened and the close all folders button is clicked then the folder is closed but the image still shows an open folder image. 
A wrong jQuery selector causes the bug. By adding a for loop, every folder image would change after the user click the Open/Close All Folders button.
=> [Bugfix:CourseMaterials] Change image when Open/Close all folders

.setup/pip/system_requirements.txt
Vagrant installation fails due to a broken version of urllib3 crashing python docker.
Python dependency urllib3 has been locked to version 1.26.14.
=> [Bugfix:System] Fix urllib3 version crashing vagrant up

.setup/apache/submitty.conf
We used rewrite rules without re-encoding special characters like spaces which when passed to PHP FPM, caused 403 errors.
Rewrite rules now re-encode special characters using the B flag.
This became necessary after a security patch update for Apache.
See https://submitty.org/sysadmin/installation/version_notes/v23.03.01
=> [SYSADMIN ACTION][Bugfix:System] Add B flag to rewrite rule

sbin/auto_rainbow_grades.py, sbin/generate_grade_summaries.py
Currently the submitty admin API token is passed from `auto_rainbow_grades.py` to `generate_grade_summaries.py` by arguments.
The submitty admin API token is read directly in `generate_grade_summaries.py`.
Tested locally and rainbow grades still builds when calling the `auto_rainbow_grades.py` script manually.
=> [SECURITY][Bugfix:RainbowGrades] Read API token instead of passing

.github/workflows/vagrant_up.yaml
Current `Vagrant Up` CI operation runs on deprecated `macos-10.15`, see: https://github.com/actions/runner-images/issues/5583 .
This may explain why recent vagrant up actions are failing.
This pr replaces GitHub runner base image from `macos-10.15` to `macos-latest`.
This pr also clean up the file, since the matrix is no longer needed as we are no longer testing vagrant up against Ubuntu 18.04, which was updated on  #7925.
=> [Refactor:Developer] Update vagrant_up action

site/composer.json, site/composer.lock
Currently we have Doctrine ORM installed which relies on Doctrine DBAL. Doctrine DBAL is then left to install whatever version deemed by Composer and the composer.json of ORM. It's highly recommended to lock DBAL according to the [Doctrine ORM docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/tutorials/getting-started.html#project-setup).
DBAL is getting bumped a major version in #9213 which is why it's failing. So now we'll have fine grained control on both.
DBAL is now locked in our composer.json. No lock file changes except a hash change.
=> [Dependency] Lock Doctrine DBAL

site/app/libraries/database/DatabaseQueries.php, site/app/models/OfficeHoursQueueModel.php
When loading the office hours page the following error will show:
This is due to #8921. This issue did not impact production because it has debug mode off.
The error is now gone.
Tested locally and now works as expected.
=> [Bugfix:HelpQueue] Fix OH Error Message

migration/migrator/migrations/course/20230425130619_user_last_initial_format.py
Syntax error in the down for the course migration `20230425130619_user_last_initial_format.py` has been fixed.
=> [Bugfix:System] Fix error in down migration

.setup/CONFIGURE_SUBMITTY.py, .setup/install_system.sh, Vagrantfile
The instructions:
https://submitty.org/developer/getting_started/worker_vm
```
WORKER_PAIR=1 vagrant up
```
fail because the hardcoded ip address for the vagrant worker is out of allowed range (a restriction added sometime in the last year).
I've switched the hardcoded ip address from: "172.18.2.8" to "192.168.56.21"
=> [Bugfix:Developer] update vagrant worker ip address

Vagrantfile
Vagrant port forwards are hardcoded into the configuration, which poses an issue in cases where a developer has another application running on their machine that occupies one or more of the ports.
Host ports can be overriden through environment variables.
=> [Feature:System] Vagrant Port Overrides

site/public/js/simple-grading.js
fixes #8852 
When using arrow keys to navigate through the input boxes on the grading page, there will be a display error.
if press the right arrow key all the way to the right, then press the left arrow key to navigate back will cause a display error.
student information will block some of the input boxes.
If using arrow key navigation & reaches the first element in the table, the table will scroll to right, exposes the part that was been blocked
To test
Steps to test the behavior:
1. Open grading on a numeric/text input gradeable (which has enough columns to horizontally overflow the screen)
2. Select one of the boxes and use the arrow keys to navigate all the way to the right
3. Attempt to use the arrow keys to navigate all the way to the left
=> [UI/UX:InstructorUI] arrowkey navigation fixed

site/app/templates/forum/ForumBar.twig
The dropdown was a bit confusing and made users believe it was supposed to order the threads not just the posts.
The post ordering is specified. Also, the drop-down is aligned to the right.
=> [Feature:Forum] Make post order clear for dropdown

tests/e2e/test_grade_inquiry.py
In the PR [#9356](https://github.com/Submitty/Submitty/pull/9356), the course level grade inquiry setting was removed.
However, this setting was not removed from the testing in e2e.
Global course grade inquiry setting is no longer tested in e2e tests.
=> [Bugfix:Developer] Remove regrade enabled from e2e

.setup/pip/system_requirements.txt
`parso` is no longer used in Submitty.  Lichen uses it, but maintains a separate [dependency file](https://github.com/Submitty/Lichen/blob/595867e04de001f4a4ec575d6cdf1d5dcd04a5c6/requirements.txt#L5) and only uses it in a Docker container.
`parso` has been removed.
=> [Refactor:System] Remove unused `parso` dependency

site/cypress/e2e/late_days_allowed.spec.js
Before PR #9356 , the Grade Inquiries column in the LateDays table was only present if grade inquiries were enabled. When
grade inquiries became always enabled, the column was present even in the LateDaysAllowed cypress test, resulting in the indices in the test being off.
The appropriate indices have been incremented, causing the test to pass.
=> [Bugfix:Developer] Increased column Indices for clicking

Vagrantfile
Sets default SMB username for added convenience when starting vagrant VM on SMB setup (currently used for Apple Silicon Mac).
Example, where username is `your_username`:
```
You will be asked for the username and password to use for the SMB
folders shortly. Please use the proper username/password of your
account.
Username (your_username): ↲
Password: 
```
=> [Feature:System] Set default SMB username

autograder/autograder/packer_unpacker.py
A VCS gradeable created and built before installing v23.06.00 will not have the partial_path field in the form.json file.  This will cause an error upon upgrading unless the gradeable is rebuilt.
Backwards compatible logic allows grading of gradeables built before v23.06.00.
New gradeables, and old gradeables built after installation work as well.
=> [Bugfix:Autograding] backwards compatible vcs subdirectory

site/.stylelintrc.json, site/public/css/authentication.css, site/public/css/calendar.css, site/public/css/configuration.css, site/public/css/details.css, site/public/css/directory.css, site/public/css/docker_interface.css, site/public/css/electronic.css, site/public/css/exceptionforms.css, site/public/css/global.css, site/public/css/grade-report.css, site/public/css/gradeOverride.css, site/public/css/latedaystableplugin.css, site/public/css/menu.css, site/public/css/navigation.css, site/public/css/notifications.css, site/public/css/officeHoursQueue.css, site/public/css/plagiarism.css, site/public/css/server.css, site/public/css/sidebar.css, site/public/css/submitbox.css, site/public/css/table.css, site/public/css/user-profile.css, site/public/css/user-select.css
Stylelint v33 has enforced the use of the new range syntax for media queries. This syntax is relatively new and support is inadequate, which causes bugs on some browsers. Furthermore, the new syntax has no functional differences from the previous standard.
The media queries have been reverted back to the standard syntax, and stylelint has been configured to allow this.
=> [Refactor:InstructorUI] Revert back to standard media queries

.github/dependabot.yml
#9105 created a "composite" action which is used as a base for several different CI pipelines.  Dependabot doesn't know about anything outside `.github/workflows` by default, so a separate configuration is required.
Adds a new entry to the Dependabot configuration file to support the new composite action.
=> [Testing:Developer] Add Dependabot for composite action

site/app/views/submission/HomeworkView.php
#9399 was merged, and if the user selects 'do not grade this assignment', a site error would show with 'count must be used on an array'
This is now fixed
=> [Bugfix:Submission] Fix error message on do not grade

site/app/templates/forum/displayThreadList.twig
A broken `Mark as resolved` button appears on unresolved threads in the discussion forum's main page (Thread list).
The broken button is gone, rather than fixed as decided by myself and @bmcutler.
See issue #9426.
=> [Bugfix:Forum] Remove threadlist resolve button

README.md
In order to see if the vagrant up action is passing/failing you need to go to the actions tab and filter by the vagrant up action.
Another status badge, just like the regular CI badge, has been added to the README for the vagrant up nightly job. This just makes it quicker/easier to see if it's currently failing.
Here's a screenshot of what it would look like:
=> [Documentation:Developer] Add vagrant up status badge

site/app/templates/grading/electronic/Details.twig
On the gradeable details page, the button to enable anonymous mode says "Enable Anon Mode." While anon is the abbreviation for anonymous used throughout Submitty's source code, non-developers will not know this abbreviation.
Now the button reads, "Enable Anonymous Mode."
=> [UI/UX:TAGrading] Change enable anon to anonymous

site/cypress/e2e/gradeables/gradeable.spec.js
Cypress currently runs forever due to the download attempts in the gradeable cypress test
The download part of the tests has been commented out so the tests pass in CI, will create an issue to change/update the tests.
=> [Testing:System] Comment out download in test

autograder/autograder/packer_unpacker.py
#9423 introduced a new variable, using_subdirectory that packer_unpacker.py get_vcs_info returns.
I missed an instance of that function, so there are errors in the autograding of zip submissions.
The return variable has been added, so the errors should be fixed.
=> [Bugfix:Autograding] Fix get_vcs_info return value

tests/e2e/test_forum.py
The forum tests are flaky, some of them are consistantly erroring with 'cannot find element 'logout''
#9393 is refactoring the selenium tests to be cypress tests, so this PR is to make the selenium forum tests to not run in the CI.
=> [Testing:Developer] Make forum tests not run in CI

migration/migrator/migrations/course/20230601123230_change_regrade_to_grade_inquiry.py
Unfortunately the migration in PR #9398 assumed that a constraint exists, however, this constraint was added early in Fall 2019 without an appropriate migration, so courses created during and before Fall 2019 are missing this constraint.
The migration has been modified to add the constraint before running the rename operation.
=> [Bugfix:System] update migration for legacy courses

site/app/views/submission/HomeworkView.php
If a student makes multiple grade inquiries by component, the grading and submission page will crash.
Fixes #9467
Both pages now load fine.
The issue was caused by `[1=>'USER_ID']` being passed into a query when it expected some element at index 0. To fix this a simple `array_values` was used to reset the keys.
=> [Bugfix:TAGrading] Fix Grade Inquiry Components

site/app/templates/admin/users/RotatingSectionsForm.twig
Fixes part 3 of #8770 
Currently Manage Sections Page have table of sections w/o course section id
Updated Page includes course section id enclosed with parenthesis
=> [Feature:InstructorUI] Add course_ID to Manage section page

site/phpstan-baseline.neon, site/phpstan.neon
We currently rely upon manual code review to enforce our PHP type annotations guidelines.  PHPStan can do this automatically.
This PR bumps PHPStan to level 6, which adds a set of rules which require PHP type annotations.
Given that development is quite active at the moment, I have ignored all of the existing errors.  Many of these are easy to fix, but fixing them risks creating merge conflicts which make other PRs harder to merge.  I plan to make a set of future PRs to pare down the list of ignored errors during a time when development is less active.
=> [Testing:Developer] Bump PHPStan to level 6

site/phpstan-baseline.neon
A conflict with #9486 caused PHPStan to fail on `main`.
The new errors have been ignored.
=> [Bugfix:Developer] Fix failing PHPStan analysis

site/cypress/e2e/autograding_status_1.spec.js
Part of the cypress autograding status tests were removed in #9462
This PR adds part of them back, in hopes that it will fix the ubuntu 22 cypress tests failing. 
Related to #9459 and #9334
=> [Testing:Submission] Re-add part of cypress autograding test

.setup/install_system.sh
System installation fails due to missing argument to command in shell script.
Fixes #9529 
The error has been fixed.
=> [Bugfix:System] Error in install script

.setup/install_system.sh
When installing the site, the following error will get printed out for any development machine now on Ubuntu 22. Xdebug will not work with this as is.
The error won't get printed out anymore and xdebug will work.
=> [Bugfix:System] Fix xdebug.ini file during install

Vagrantfile
Trying to run vagrant using vmware on ARM does not work as it will always use the x86 image.
The ARM image gets specified when needed for the vmware provider. This will not effect any other provider and vmware would still work fine for anyone not on ARM.
I tested this since I needed this change to use the VM on my machine.
=> [Feature:Developer] Support ARM on vmware

grading/system_call_categories.cpp
statx system call is used by 'ls'
=> [Feature:Autograding] add statx syscall

.github/PULL_REQUEST_TEMPLATE.md
The current Git PR page does not have a requirement button for including a screenshot when there are visual changes.
New Git PR page have a requirement button for including a screenshot when there are visual changes.
=> [Feature:System] Add screenshot button Git PR Page

.setup/INSTALL_SUBMITTY_HELPER.sh
Installation errors on some machines/configurations due to filesystem errors from running setuptools build script within shared directory on developer virtual machine.
Build has been moved outside of the mounted directory.
=> [Bugfix:System] Build submitty utils not in shared mount

migration/migrator/migrations/course/20230728153210_repeat_grade_inquiry_migration.py
Repeats the course configuration edit from PR #9398 
(migration file 20230601123230_change_regrade_to_grade_inquiry.py) 
which failed to run successfully for a number of courses.
I'm not sure why the previous migration failed, 
but I have tested this on our production machine and this time the edit was successful on the broken courses.
I had to convert the error checking exception to just a print statement because the CI workflow didn't have the directory/config file and it was failing tests.  Good enough to help debugging.
=> [Bugfix:System] repeat migration to rename regrade

site/app/templates/grading/electronic/SubmissionPanel.twig
The student grader cannot see the results folder so the button "Open/Close Results" shouldn't be there.
Now the button is not visible to the student grader. Closes #9570
=> [UI/UX:System] Peer Grading Submission Browser 

.github/actions/e2e-Setup-Composite/action.yml
The Cypress and Integration tests occasionally fail on the setup phase of the github action, with the error 
Since we are no longer using Selenium for CI, and Cypress and Integration tests do not use the chrome driver, the setup has been removed, which should also remove the occasional errors in the setup phase.
=> [Bugfix:Developer] Remove chrome driver setup

.github/workflows/vagrant_up.yaml
The vagrant CI workflow references the `ubuntu-20.04` image to validate that it builds successfully. It's been failing for about 3 weeks since #9334 was merged.
It will use the `ubuntu-22.04` image which is specified in the Vagrantfile and I will stop getting emails every day about this workflow failing.
=> [Bugfix:Developer] Fix image name for vagrant CI workflow

.github/workflows/submitty_ci.yml
Python unit tests fail on main.
Python unit tests won't fail on main. Yay!
=> [Bugfix:Developer] Fix Python Unit Tests

site/app/views/NavigationView.php
Works with handling case for Null. 
https://stackoverflow.com/questions/70584290/php-8-0-method-exists-on-non-object-causes-fatal-typeerror
Moving up to PHP 8 caused this to happen. 
PHP 8 is going stricter with property_exists() function to raise a TypeError on invalid argument, in order to match the behavior of property_exists and method_exists function. 
fixes #9636
=> [Bugfix:Notifications] fix display special message

.setup/pip/system_requirements.txt
The `clang` dependency is currently unused.  Before Lichen started managing an independent list of dependencies, this was used to tokenize C/C++ files for Lichen.
The Python bindings for `clang` have been removed.
=> [Refactor:Developer] Remove unused `clang` Python bindings

.github/dependabot.yml
We currently get weekly dependency updates from Dependabot.  Unfortunately, we are often unable to keep up with the flood of dependency PRs.
Bumps the Dependabot frequency to monthly updates.
=> [Feature:Developer] Bump dependabot frequency to monthly

site/app/controllers/MiscController.php
Currently, if a test case is hidden, you are unable to download the student submission file
This fix allows the grader to download the student submission file, even if the test case is hidden
Closes #9668
=> [Bugfix:TAGrading] Download Files For Hidden Test Cases

site/app/controllers/GlobalController.php
Currently, there are two pages of Auto grading status: one that only gets displayed after displaying rainbow grades, which is a faulty and duplicate one, while the other correct page is always shown even outside of a course. 
Remove duplicate Autograding Page. 
Closes #9672
=> [Bugfix:Autograding] Remove duplicate Autograding Page

site/app/controllers/calendar/CalendarController.php
This bug occurs when a user has 0 courses (i.e. superuser), has the `calendar_show_all` cookie set to 0, and doesn't have a `calendar_course` cookie set. The code does two things wrong:
1. It will by default choose a course from your courses, and use its data for the `calendar_course` cookie. This will give an error if you don't have any courses.
2. It uses the index of 1 rather than 0 to find a course, so if you have only 1 course it will also give an issue as you will access a course that doesn't exist.
Now that bug should be patched!
=> [Bugfix:Calendar] Fixed Calendar for 0-1 Courses

site/.performance_warning_ignore.json
Currently, when creating a new gradeable, 712 queries are executed, which triggers a site error. This could be a problem when a new cypress test is written that requires creating a new gradeable, it would fail the check for site errors. 
Added the route of the excessive queries to the performance warning ignore list.
=> [Testing:Developer] Add new route to the ignore list

site/app/templates/admin/users/UserForm.twig, site/public/js/userform.js
Selecting a student from the list of options in the Add Student menu for a course would close the popup window. You had to either click another form option or press enter to stay in the window.
The window now does not close accidentally.
Closes #9681
=> [Bugfix:InstructorUI] 'Add Student' Popup Stays Open

site/public/index.php
Before adding the Cache-Control: private header, the current behavior involves the potential caching of the resource by both intermediaries, such as proxy servers, and the client's browser. Intermediary servers might cache the resource, which could lead to outdated content being served to subsequent users. Additionally, the client's browser might cache the resource to expedite subsequent visits.
However, after incorporating the Cache-Control: private header, the new behavior emerges. In this updated scenario, intermediaries are explicitly prevented from caching the resource, ensuring that subsequent users receive the most current content. Although the resource can still be cached by the client's browser for quicker loading during subsequent visits, the risk of serving outdated content due …
=> [SECURITY][Bugfix:System] Prevent caching the resource

site/app/templates/submission/homework/CurrentVersionBox.twig, site/app/views/submission/HomeworkView.php
In #9399 submission error messages were added, and intended for VCS gradeables. 
Now the error messages only show up on VCS gradeables as intended
=> [Bugfix:Submission] Remove error message from non VCS

site/public/index.php
Using the 'none' option in the frame-ancestors directive prevents any content from being displayed in iframes, including content from the same origin. However, this poses a problem for displaying submission files in iframes within the Grading Interface.
Now only pages from the same origin (same domain and protocol) are allowed to frame the content.
=> [Bugfix:System] Files in iframe Grading Interface

site/app/templates/course/EditCourseMaterialsFolderForm.twig, site/app/templates/course/EditCourseMaterialsForm.twig, site/app/templates/course/SetAllReleaseForm.twig, site/app/templates/course/SetFolderReleaseForm.twig, site/app/templates/course/UploadCourseMaterialsForm.twig
There is currently a bug on Submitty regarding course materials set to the distance past (See issue #9730). While course materials set to the distant past still do not work, this PR changes the "Beginning of Time" upload option to the year 1900 to circumvent the issue for now.
The "Beginning of Time" upload option works!
This PR closes issue #9733, a checkmark of issue #9730.
=> [Bugfix:CourseMaterials] Change the Beginning of Time

.setup/install_system.sh
We currently install npm again to get the latest version after installing node. This has an issue because it may try to fetch a version of npm that is incompatible with the current node version.
We no longer manually install npm again and instead rely on the version tied to the node version.
This does not resolve the deprecation issue. That will be fixed in a later PR.
A manual vagrant job has been kicked off to test here: https://github.com/Submitty/Submitty/actions/runs/6092760330
=> [Bugfix:System] Remove manual npm install

site/app/entities/email/EmailEntity.php
When an email is sent, the database column `sent` will be null. With the recent Doctrine changes, it is expected that the value isn't null and flags an error. When trying to load the email status page with an unsent email, a frog robot error will occur.
I modified the attribute and PHP type to tell Doctrine it is nullable. The error no longer occurs.
=> [Bugfix:InstructorUI] Email status page fix

site/public/index.php
Before this patch, no referrer policy is defined, and the browser's default behavior regarding the transmission of referrer information is in effect. This may lead to the browser potentially sending the complete URL as the referrer when navigating to different origins, which can have privacy and security implications.
After applying this patch, the HTTP response sets the referrer policy to "strict-origin-when-cross-origin." This ensures that the browser will send the full URL as the referrer only when navigating to a cross-origin resource, enhancing privacy and security by reducing unnecessary disclosure of information to external websites.
=> [SECURITY][Bugfix:System] Referrer Policy Update

site/public/index.php
Before applying the provided code, the HTTP response does not specify any Cross-Origin Embedder Policy (COEP) or Cross-Origin Opener Policy (COOP) headers. This lack of configuration means the page is not enforcing any restrictions on resource loading from other origins or state sharing with different origins, potentially exposing it to security risks related to cross-origin requests and interactions.
After applying the provided code, the HTTP response sets the Cross-Origin Embedder Policy (COEP) to "credentialless," ensuring that the page will only load resources from origins that do not require credentials, thus enhancing security. Additionally, the Cross-Origin Opener Policy (COOP) is set to "same-origin," limiting state sharing to pages from the same origin, further mitigating …
=> [SECURITY][Bugfix:System] CORS Security Headers

site/app/templates/grading/simple/Display.twig, site/cypress/e2e/Cypress-Gradeable/simple_grading.spec.js, site/public/js/simple-grading.js
Closes #9779 
The button undo/redo is buggy and is not being used often
The button undo/redo is removed
=> [UI/UX:TAGrading] Removed undo/redo button in lab grading

.github/workflows/vagrant_up.yaml
Currently the vagrant up github action is a cron job, so it is run on a schedule. Due to this, it only sends notifications to the last person to edit the workflow file. If this person is away for any significant period, the failing job can go unnoticed by other developers. This is a problem, as new developers won't be able to reliably run 'vagrant up', which will slow development. 
This adds a notification VIA a slack app that notifies all who are in the slack channel of the vagrant up failure. 
The first two messages were debugging, and the last one was a mock failure to show it works. 
Closes #9596
=> [Testing:Developer] Add slack message on vagrant up failure

site/app/templates/forum/EditPostForm.twig, site/public/js/forum.js
Fixes #4164
Also read comments in the original issue.
confirm() is added to the edit post pop-up form when an user is discarding their unsaved changes. 
Note: Close-when-clicked-outside feature is disabled for the same pop-up.
=> [Bugfix:Forum] Warning for Discard Changes in Post Edit

grading/TestCase.cpp, grading/execute_limits.cpp
Autograding compilation was failing for some student CGAL programs (that used multiple modules of CGAL libaries).
Both the virtual memory and the file size limits were execeeded during compilation.
Compilation test cases will now have a default higher memory limit.  (This was aleady adjustable by the instructor.)
Compilation test cases will now have a larger limit on the created file size.  (This adjustment allowed by the instructor previously had a lower cap that was insufficient.)
=> [Bugfix:Autograding] update autograding compilation limits

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/bin/versions.sh, .setup/install_system.sh, grading/TestCase.cpp, grading/system_call_categories.cpp, grading/system_call_check.cpp
https://drmemory.org/page_download.html
This update is necessary to use Ubuntu22 / g++11
=> [Dependency] update DrMemory 2.6.0

site/app/models/gradeable/Gradeable.php
If you try to load the checkpoint grading page with an empty section, a frog robot error will occur. This is due to the null coalesce being null rather than an empty array.
The page loads normally as expected. The null coalesce is now just an empty array as it should be.
Tested locally and it does fix the issue.
=> [Bugfix:TAGrading] Checkpoint Grading Empty Section

site/app/controllers/grading/ElectronicGraderController.php, site/app/libraries/database/DatabaseQueries.php, site/app/models/SimpleStat.php
Currently, in the grading stats page. the statistics available for each grader (count,average,stddev) are not correctly calculated:
Notice how the stats for the grader for a specific component differ from the overall stats per components.
Additionally, the stats for the grader per component don't interact with the newly added filters.
The stats for the grader per component are correctly calculated and interact with the filters 
Additionally, this PR reformats some queries related to the statistics for better code practise.
=> [Bugfix:TAGrading] Fix Incorrect Stats for Grader Scores

site/app/models/gradeable/LateDays.php, site/cypress/e2e/Cypress-Feature/late_days_cache.spec.js
There is an unnecessary call to generate the late day cache in LateDays.php. This is causing duplicate keys in the late day cache.
Remove unnecessary and redundant call
=> [Bugfix:Submission] Remove redundant late day cache call

site/app/libraries/database/DatabaseQueries.php, site/app/models/gradeable/Gradeable.php, site/tests/app/controllers/student/SubmissionControllerTester.php, site/tests/app/models/gradeable/GradeableListTester.php
The instructor gradeables page makes 108 queries each page load. A lot of these queries are repetitive and can be refactored to use significantly less queries.
The gradeables page now uses 82 queries per page load which is about a 20% improvement. The gradeable canDelete function can be pretty expensive so I made it collect some data earlier and only query team info if it is a team gradeable.
There is still more work to be done here. The most expensive thing on the page is loading all of the status bars for grading but it uses a lot of query and PHP logic.
=> [Refactor:InstructorUI] Refactor queries to collect data earlier

.github/workflows/vagrant_up.yaml
After I was testing the slack message on failure, I accidentally deleted the line to get the JOB ID on failure. This causes the vagrant up notification to not have the JOB ID, so the link is bad.
The line to run this on failure has been re-added, this will make the link accurate.
=> [Bugfix:Developer] Fix vagrant up slack message

site/app/libraries/database/DatabaseQueries.php, site/phpstan-baseline.neon
Bulk upload gradeables can't have submissions past their due date. Therefore there aren't any rows of these gradeables in the late day cache. When omitting the bad submissions from the statistic page (which is the default setting), the code adds a query to get the necessary data from the late day cache. However, if there are no entries in the table, it will mess up all statistics.
Check if there are any bad submissions before omitting them from the statistics.
=> [Bugfix:TAGrading] Check for bad submissions in statistics

site/app/authentication/SamlAuthentication.php
If a malformed SAML packet is passed in during login, a server error is created.
A try catch was added to handle the malformed packet errors and instruct the user to login again.
Unfortunately, this is quite difficult to test but it simply just adds a try catch and handle the error.
=> [Bugfix:System] Add more error handling to SAML

site/app/controllers/SelfRejoinController.php
When a student self readds themselves, the email does not say what term the course they rejoin is a part of.
The term is now specified.
Email subject:
=> [Feature:System] Add Term to Rejoin Email

site/app/controllers/SelfRejoinController.php
Students can "rejoin" courses they are already in if they specifically go to the null access page. They can also rejoin archived courses.
Students can only rejoin in the null section, and the course must be not archived.
=> [Bugfix:System] Stricter Course Rejoin Requirements

site/phpstan.neon
We currently require developers to list the files to check when running PHPStan.  PHPStan supports the ability to list these files in the configuration file.
It is no longer necessary to specify the files to check when running PHPStan.
=> [Testing:Developer] Add files to PHPStan config

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Our issue templates currently include placeholder text.  If the placeholder text is not removed manually prior to opening an issue, the placeholder text will remain visible once the issue is opened.
To reduce the amount of spam in our new issues, I have wrapped the placeholder text in HTML comments.  The placeholder text will now be hidden if it is not removed prior to opening an issue.
=> [Documentation:Developer] Wrap placeholder text in HTML comments

site/composer.json, site/composer.lock, site/phpstan-baseline.neon, site/phpstan.neon
The [phpstan-strict-rules](https://github.com/phpstan/phpstan-strict-rules) plugin has been enabled.  Amongst other things, PHPStan will now require strict type comparisons and disallow functions which perform loose type comparisons.  This change will automate a large portion of my manual code review work.
=> [Feature:Developer] Enable PHPStan strict rules plugin

site/app/libraries/DateUtils.php, site/app/templates/course/EditCourseMaterialsFolderForm.twig, site/app/templates/course/EditCourseMaterialsForm.twig, site/app/templates/course/SetAllReleaseForm.twig, site/app/templates/course/SetFolderReleaseForm.twig, site/app/templates/course/UploadCourseMaterialsForm.twig, site/app/views/course/CourseMaterialsView.php
The beginning of time feature is used in all date time picker in course materials. We recently changed the date from 1000 to 1900. 
In case we decide to change it again later, this refactor would allow the developer to change one variable in one file, instead of 5 different ones in 5 different files.
Closes #9762
=> [Refactor:CourseMaterials] Use one variable for beginning of time

site/phpstan-baseline.neon
A conflict between https://github.com/Submitty/Submitty/pull/9799 and https://github.com/Submitty/Submitty/pull/9901 caused PHPStan to begin failing on `main`.
The new PHPStan errors have been ignored.
=> [Bugfix:Developer] Fix PHPStan errors on main

site/app/libraries/NotificationFactory.php
If you make an announcement, a site error will occur due to the flattened email count being divided by the wrong number.
Making an announcement no longer creates an error and that count is now divided by the right number.
Tested locally and works as expected now.
=> [Bugfix:Notifications] Fix flattened email count

site/public/js/forum.js
* [] Screenshots are attached to Github PR if visual/UI changes were made (N/A)
If the forum backend sends an invalid JSON response the client-side code to handle it throws an exception due to invalid syntax this prevents the cypress test for forum pronoun changes to fail since it will abort on an exception thrown from our software
Removes the error allowing cypress to pass that part of the test and prevents the forum from silently putting exceptions in the console if this happens to a real user.
=> [Bugfix:Forum] Fix syntax error for error handling

site/app/libraries/Core.php, site/app/libraries/SessionManager.php, site/tests/app/libraries/SessionManagerTester.php
When the session gets closer to expiration it will update on the database but not the cookie. Thus the cookie will still expire and log the user out after the session expiration time.  The issue was introduced in https://github.com/Submitty/Submitty/pull/8620.
The cookie will now update when the session updates. The user will only get logged out after 2 weeks of inactivity.
=> [Bugfix:System] Fix session cookie not updating

site/app/templates/grading/simple/Display.twig, site/public/css/simple-grading.css
TA/admin color in lab's grading is exactly like other students in /courses/f23/sample/gradeable/grading_lab/grading?view=all
The blue checks were also not able to be removed for TA which is originally supposed be used to highlight TA. Possibly caused by duplicated blue.
TA/Admin's color now highlighted and matches the color shown in manage student. 
Here is TA/admin colors as reference
Tested in dark mode to verify if its color is still the same comparing to manage student.
=> [Bugfix:TAGrading] Modify TA/Admin's rows in lab grading

site/app/models/RainbowCustomizationJSON.php
fixes #9933 
There is problem with display benchmark button, removing the option so that GUI do not insert invalid argument to json file.
=> [Bugfix:RainbowGrades] Remove display benchmark

site/app/controllers/admin/LateController.php
Closes #9871
Currently, when uploading a CSV file on the excused absence extension page, an error is given due to invalid json being parsed.
This is due to a deprecated code warning in lateController.php for ini_set("auto_detect_line_endings", true);.
Deprecated code is replaced by manual newline parsing, removing the error.
=> [Bugfix:System] Fixes CSV Upload Error

README.md
When looking at the dark mode GitHub main repo page for Submitty, the logo is extremely difficult to see.
When using dark mode, the README will render the dark mode version instead.
This uses the picture tag to conditionally render the specific image. Nothing will change for light mode users.
=> [Feature:Developer] Add README Dark Mode Image

.github/workflows/notify_main_fail.yml
Currently the Notify Main on CI Failure workflow fails if the CI doesn't because of a syntax error in the echo statement.
This syntax error is no longer present.
=> [Bugfix:Developer] Fix Main CI success message

.github/workflows/notify_main_fail.yml
I tested this functionality on a fork, and forgot to bring a change that fixed this issue. The workflow_run event has an id, not a run_id. 
The URL used for the link now has the accurate information, so it will show the Main CI that failed.
=> [Bugfix:Developer] Use id for main notifications

site/public/js/forum.js
When changing between threads, markdown code would lose the highlights made by hljs.
The markdown code stays highlighted when flipping through threads and for new posts coming in from other users.
=> [Bugfix:Forum] Markdown Code stays highlighted

site/app/templates/course/CourseMaterials.twig, site/app/templates/course/EditCourseMaterialsFolderForm.twig, site/app/templates/course/EditCourseMaterialsForm.twig, site/app/templates/course/UploadCourseMaterialsForm.twig
Fixes #10039 
On clicking anywhere on the paragraph of text beneath the checkbox and to the right of the "hide from students" text toggles this checkbox.
=> On clicking anywhere on the paragraph of text beneath the checkbox and to the right of the "hide from students" text will not toggle this checkbox.
None.
=> [Bugfix:Submission] Moved the text outside the label tag.

site/app/libraries/database/DatabaseQueries.php
Right now a query function getFirstPostForThreads gets called to display the forum, and it requires a list of thread ids to serve as keys for the query. If the list is empty, sql throws an error.
If the array passed has no elements, the getFirstPostForThreads will return null. The function is called at ForumThreadView.php line 760. It then handles null/missing array indices at lines 767-772.
=> [Bugfix:Forum] Add check for empty thread list

site/phpstan-baseline.neon, site/phpstan.neon
This PR enables PHPStan's set of "Bleeding Edge" rules.  While these rules are technically experimental, and won't officially be added to the main rulesets until the next major version, they are well supported.  The most beneficial change is the addition of strict equality checking.  `==` and `!=` are prohibited, in favor of their strict equality counterparts.  I have initially ignored all of the new errors to prevent excessive merge conflicts with other PRs.
=> [Feature:Developer] Enable PHPStan "Bleeding Edge"

site/app/controllers/forum/ForumController.php
In my testing of PR #9906 I noticed that when I edited a post, other users viewing the post would see an error. This was due to some changes I had made in PR #9988.
This fixes the error and now posts dynamically update when somebody else edits them.
=> [Bugfix:Forum] Fix edit post websocket update

migration/migrator/migrations/course/20231213021032_clear_late_day_cache.py, site/app/models/gradeable/LateDays.php
If instructors try to generate grade report summaries for their class and they also have excused absences, it is likely that it will fail/error.
This will no longer error. The cache had some bad values that would cause issues so it has now been cleared. This PR also adds a missed case of event info that doesn't have the reason.
=> [Bugfix:InstructorUI] Fix Grade Report Summaries

site/app/controllers/admin/ReportController.php
This is related to /Submitty/Rainbowgrades/#69
This PR modifies the reportcontroller to add version_conflict boolean to json
Then it will be used in Rainbowgrades code to correctly generate border-outline of the gradeable.
=> [Feature:RainbowGrades] add version conflict

site/app/templates/grading/electronic/Details.twig
There are two class parameters in the HTML element for the grade button's on the TA grading page. The element only takes the first one, and omits the next. 
These have now been combined into one class parameter, and everything works as intended.
=> [Bugfix:InstructorUI] Fix grading button

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20240114160417_fix_duplicate_team_anon_id.py
https://github.com/Submitty/Submitty/pull/8733 had a bug in the migration where any gradeable missing anonymous IDs, would receive duplicate anonymous IDs. This causes some old courses to get duplicate anonymous IDs and then prevent loading the grading page.
This PR wipes any duplicate anonymous IDs and then regenerates them with the same code but with a bugfix. This also adds a unique constraint so that it is not an issue going forward.
I tested locally and confirmed that any duplicates do get fixed.
=> [Bugfix:Submission] Fix duplicate team anon IDs

site/app/views/submission/HomeworkView.php, site/phpstan-baseline.neon
When submitting an assignment to a VCS gradeable, it will always give out a warning that the repo is empty even if it's not.
If the repo isn't empty, the warning does not show anymore as expected. `in_array` was used when `array_key_exists` should have been used.
Tested locally and warning message gone.
=> [Bugfix:Submission] Fix Empty Repo Warning

.github/workflows/vagrant_up.yaml, Vagrantfile
The vagrant up workflow often fails right now, where VirtualBox is stuck in a "gurumeditation" state. There is https://github.com/actions/runner-images/issues/8730 which indicates others are running into the same problem, and while GH has closed the issue with it's fixed and sometimes the workflow does succeed, it's still often failing. My only guess is that per https://github.com/actions/runner-images/issues/8730#issuecomment-1834391700, there are different machines that run macOS-12 builds and certain ones just always fail :shrug:.
PR updates the vagrant up workflow to use macOS 13 which while in beta seems to provide a much more stable interface for vagrant/virtualbox, and that I was able to run the workflow 4 times in a row (with one disconnect failure, which I think is due to machine …
=> [Testing:Developer] Improve flakiness of vagrant up workflow

site/app/templates/submission/homework/CurrentVersionResults.twig
On VCS gradeables, when a student submits their repository, the info about autograding and submitted files does not show. Instructors or any member of the grading team do not have this problem.
The autograding info and submitted files now displays for students.
Tested locally and now works as expected.
This issue originated from https://github.com/Submitty/Submitty/pull/9087.
=> [Bugfix:Submission] Fix VCS Autograding Info

site/app/templates/forum/RenderPost.twig
First part of #10070 
Before:
After:
Barb on Zulip:
"...the indentation on the forum is looking a little squirrelly to me on some threads/some posts within the thread. See how each post in this screenshot has a little extra space at the start of the first line? But It doesn't happen on every post in every thread." 
When a forum post is created (including replies) without markdown option toggled, the text is indented automatically. The text with markdown appears to be normal. 
Forum post text is indented correctly regardless.
=> [Bugfix:Forum] Indentation w/ Markdown Disabled

.github/workflows/notify_main_fail.yml
When I added the workflow to notify Zulip if the main branch ever had a CI error, I didn't think about working for any branch named 'main' on any fork.
Now the CI failure notifcation only runs on the main Submitty repository
=> [Bugfix:System] Only notify from main repository

site/app/templates/admin/Report.twig
Currently, there is a superlink on the Grade Reports page, Rainbow Grades Section, suppose direct to the documentation page on submitty.org that helps instructor learn it works. But seems like it's not catch up some refactor of the submitty.org.
The superlink is now not direct to the right place. See screenshots attached.
The link is now works well.
This is a tiny change with just letters changed.
=> [Bugfix:InstructorUI] Fix link to Rainbow Grades documentation

.setup/pip/system_requirements.txt
This reverts commit c81f5e2eae22e2ff30d04664ce1a8e6746c2afbe.
The `xlsx2csv@0.8.2` only provides a source distribution which fails to install on Ubuntu 22.04 with the version of pip that comes from `python3-pip`:
```
ubuntu-22.04: Collecting xlsx2csv==0.8.2
ubuntu-22.04:   Downloading xlsx2csv-0.8.2.tar.gz (227 kB)
ubuntu-22.04:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 KB 18.4 MB/s eta 0:00:00
ubuntu-22.04:   Installing build dependencies: started
ubuntu-22.04:   Installing build dependencies: finished with status 'done'
ubuntu-22.04:   Getting requirements to build wheel: started
ubuntu-22.04:   Getting requirements to build wheel: finished with status 'done'
ubuntu-22.04:   Preparing metadata (pyproject.toml): started
ubuntu-22.04:   Preparing metadata (pyproject.toml): …
```
=> [Dependency] Revert "Bump xlsx2csv from 0.8.1 to 0.8.2 (#10155)"

site/public/css/calendar.css
Fixes issue [#10171](https://github.com/Submitty/Submitty/issues/10171) 
This PR fixes an almost identical bug as was fixed in PR [#10125](https://github.com/Submitty/Submitty/pull/10125), except this fixes it for notes, instead of announcements in the calendar.
As the cursor is moved over the edge of a Note entry in the calendar view, the cursor changes to a pointer for a split second, before switching back to the default arrow cursor.
The cursor stays as an arrow, and doesn't change when dragged over the edge of Notes.
Tested from student, grader, and ta logins.
=> [UI/UX:Calendar] Fix calendar Note cursor

site/app/templates/forum/CreatePost.twig, site/app/templates/forum/RenderPost.twig, site/public/css/forum.css
closes #10070 
#10118 fixes the first part of #10070 by containing the post text in a block, but this way it adds extra spacing on top and bottom of a post to match that of a markdown enabled post, causing there to be more wasted space.
This PR adds whitespace control to the non-markdown enabled text and removes the extra spacing for the posts w/ markdown.
A 5px top-margin is added to improve the look and feel.
Before:
Now:
=> [Bugfix:Forum] Fix Forum Post Spacing

site/app/templates/forum/ThreadPostForm.twig, site/public/css/forum.css
Fixes #10250.
Help icon is now vertically aligned with the Markdown button.
Please let me know if there are UI unit tests / snapshot tests that I missed. I did not find any.
=> [Bugfix:Forum] Fix alignment of help icon

.setup/install_submitty/install_site.sh
Doctrine proxies are installed before composer gets updated. This causes issues when we update Doctrine related code and could potentially be using old proxies or modify code that relies on the newer code.
Doctrine proxies are generated after composer install.
This should be merged before #10245
=> [Bugfix:System] Move Doctrine Proxy Install

site/app/templates/forum/ThreadPostForm.twig
Fixes #9794 [](https://github.com/Submitty/Submitty/issues/9794)
To reproduce the issue:
go to forum and click on reply thread or create new thread.
click upload attachment.
now the user need to select the item twice in the doc page, to upload the items. 
The doc page will no longer pop up twice since the user upload the attachment.
=> [Bugfix:Forum] fix attachment upload in forum

site/app/templates/generic/Popup.twig, site/cypress/e2e/Cypress-Gradeable/simple_grading.spec.js
Closes #10015 
* [✅] Screenshots are attached to Github PR
In the file `simple_grading.spec.js`, extremely long selectors are tied using multiple classes.
Usage of `data-` selector instead of class selectors.
This in turn improves testing stability.
Upon running `simple_grading.spec.js` in Cypress UI :
=> [Refactor:TAGrading] Use of data- selector instead of class's

site/app/models/gradeable/GradedComponentContainer.php
Fixes #10166 Currently, the peer grading completion status is only visible to the instructor. The status indicator does not change on the TA interface, regardless of whether a student has finished grading the component or not.
The status indicator is highlighted in purple on the TA interface if the student has graded their assigned peer component.
before change:
after change:
=> [Bugfix:TAGrading] Show Peer Grading Status on TA interface

site/.performance_warning_ignore.json, site/app/controllers/UserProfileController.php, site/app/controllers/grading/ElectronicGraderController.php, site/app/libraries/Core.php, site/app/libraries/database/AbstractDatabase.php, site/app/libraries/database/DatabaseQueries.php, site/app/libraries/database/DatabaseRowIterator.php, site/app/libraries/database/PostgresqlDatabase.php, site/app/libraries/database/QueryLogger.php, site/app/libraries/database/SqliteDatabase.php, site/app/models/User.php, site/app/repositories/email/EmailRepository.php, site/composer.json, site/composer.lock, site/phpstan-baseline.neon, site/tests/app/controllers/AuthenticationControllerTester.php, site/tests/app/controllers/MiscControllerTester.php, site/tests/app/controllers/course/CourseMaterialsControllerTester.php, site/tests/app/controllers/student/SubmissionControllerTester.php, site/tests/app/libraries/FileUtilsTester.php, site/tests/app/libraries/UtilsTester.php, site/tests/app/libraries/database/AbstractDatabaseTester.php, site/tests/app/libraries/database/PostgresqlDatabaseTester.php, site/tests/app/libraries/database/SqliteDatabaseTester.php, site/tests/app/libraries/response/MultiResponseTester.php, site/tests/app/libraries/response/RedirectResponseTester.php, site/tests/app/libraries/routers/WebRouterTester.php
We currently wrap our AbstractDatabase around PDO for both Postgres and SQLite. We should also be upgrading DBAL to 3 (and eventually 4 since that was just released) which has been an open PR for a while. Doctrine ORM requires DBAL because that is what it uses as it's database layer. We pass in our existing PDO instance to ORM/DBAL to avoid creating a new database connection.
We are using DBAL 2.13.9.
This PR changes AbstractDatabase to now wrap DBAL instead of PDO. DBAL wraps PDO so we essentially just have an extra layer in between AbstractDatabase and PDO. If we were to keep AbstractDatabase using PDO, we would need to double our database connections to support DBAL 3 and higher. This is because DBAL removed the ability to pass in a user provided PDO instance. So we either would need …
=> [Refactor:System] Switch PDO to DBAL

site/app/views/admin/DockerView.php
Currently the docker UI cypress test fails sometimes, even when PRs don't affect the page. After tracing the error message through the code, this occurs when the PHP app is unable to fully parse a system info file located in /var/local/submitty/logs/sysinfo, leaving specific array keys unset which results in twig throwing an error. I believe this occurs in Github Actions when the relevant file fails to fully generate before it tries to render the site.
By initializing the relevant array keys to null before parsing the file, we allow the twig template to render and tests to continue.
To reproduce: on main, comment out line 251 of DockerView.php `$machine_system_details[$current_machine]["disk"] = $matches[1];`, rebuild the site, and then reload the page. You should receive an error …
=> [Bugfix:Developer] Fix flaky docker ui cypress test

.github/workflows/notify_main_fail.yml
Any branch named "main" will notify Zulip if the tests fail
It will only notify if the head_repository (the requesting repository, not the repository where the workflow file is located) is Submitty/Submitty
=> [Bugfix:System] Fix main notifications

site/app/views/admin/DockerView.php
https://github.com/Submitty/Submitty/pull/10271 missed the "os" key, which is believed to be the cause of [this](https://github.com/Submitty/Submitty/actions/runs/8515492568/job/23323056920) CI failure.
The "os" key is initialized to null.
The original source of the Docker UI test flakiness is PR https://github.com/Submitty/Submitty/pull/7932.  Notably, the last comment on that PR discusses the flakiness of the tests, and the subsequent [commit](https://github.com/Submitty/Submitty/pull/7932/commits/5acb72fb030ac02cbd54195e786a62dbea96f386) comments out a test in an attempt to fix the flakiness.  In the future, it would be worthwhile to investigate the commented-out test to see if it is now reliable.
=> [Bugfix:Developer] Initialize "os" key in Docker UI

site/app/libraries/Core.php, site/app/libraries/database/AbstractDatabase.php
Currently in some cases, when deconstructing the database object, an error is thrown trying to disconnect from a null object, due to the database not being connected. 
Now it checks if the database is connected before attempting to close the connection. 
See https://github.com/Submitty/Submitty/pull/10281 for discovery
=> [Bugfix:System] Check DB connected before closing

site/composer.json, site/composer.lock, site/phpcs.xml
We are using `submitty/php-codesniffer` 2.5.0.
We now use `submitty/php-codesniffer` 3.0.1 which has some bug fixes. The bugs were associated with some PHP 8 syntax.
=> [Dependency] Bump submitty/php-codesniffer to 3.0.1

site/app/templates/admin/admin_gradeable/AdminGradeableUploadForm.twig, site/public/js/gradeable.js
If an upload gradeable via JSON configuration fails, the page redirects which prevents the user from seeing any error messages. The documentation link for the upload gradable model is broken
Page no longer redirects on error, allowing the alert to be shown. In the future this alert can be replaced with the usual red error message or with a modal that can display the errors better if the validation message is more complex
No
Easiest way to test the error message is to upload a gradable config for one that exists already
=> [Bugfix:InstructorUI] Doc link, display errors on upload

site/app/models/RainbowCustomization.php
In order to improve readability and simplify logic below changes has been made. 
Ternary operation has been simplified for both  $usedDisplayBenchmarks and $isUsed.
Type hinting - following php8 standard.
=> [Refactor:RainbowGrades] Refactor benchmark null operator

site/public/js/forum.js
When a user got a new post while he is in the forum page, user's browser will render it as a read message. But, it should be rendered as an unread message.
Now, if a user got a post while user is in the forum page, browser will render it as an unread message.
(Changed according to the request from @DarthNyan.)
Changes : Added a code line to add 'new_post' class when displaying a new post.
I tested this on my VM.
It works on dark mode as well (a white color transparent overlay). 
However, I was unable to find the logical error why the system treat new messages like this. Let's try to find a more sustainable method soon. Working on it :)
closes #10319 
Thank you.
=> [Bugfix:Forum] Highlight new posts in Forum

site/app/templates/calendar/Calendar.twig, site/public/css/calendar.css, site/public/js/calendar.js
The current behavior is that, to change the date to the current day, the user must press the arrow keys repeatedly.
The new behavior is that, there is now a blue button on the upper left-hand side of the calendar page that
sets the calendar date to the current day/month/year and also updates all cookies.
This should not be a breaking change and was tested on both student and instructor accounts. 
However, this pr could interfere with my other calendar pr #10249 which creates month/year dropdowns which may or may not update when the button is pressed.
=> [Feature:Calendar] Button to Set Calendar Date to Today

site/app/models/gradeable/Gradeable.php
Closes #9720 
* [✅] Screenshots are attached to Github PR if visual/UI changes were made
An instructor logs in and edits a gradeable
Instructor changes this setting "Make new submissions and access all prior versions?" to NO
Then due date validation stops working due to a bug.
Even if the  "Make new submissions and access all prior versions?" is set to NO
Due date validation works as intended.
[Due-date-validation.webm](https://github.com/Submitty/Submitty/assets/81346327/538d2544-0e46-4cb5-ada9-24c01542b7e6)
=> [Bugfix:InstructorUI] Due date validation for isStudentSubmit

site/app/views/grading/ElectronicGraderView.php
Closes #9682  
* [✅] Screenshots are attached to Github PR if visual/UI changes were made
Limited access graders are not able to view Team IDs if they are not anonymized by instructors
This is also applicable for peer graders.
Limited access and peer graders are now able to view Team IDs when they are not anonymized by instructors
and they are able to view Anonymized Team IDs when they are anonymized by instructors.
**Limited Access grader (Not anonymized)**
**Limited Access grader (Anonymized)**
**Peer grader  (Not anonymized)**
**Peer grader  (Anonymized)**
=> [Bugfix:TAGrading] Rendering Team IDs for Graders

site/public/css/calendar.css, site/public/js/calendar.js
Changed the calendar cells to be larger based on the viewing mode(month, two-week, week)
The current behavior is that if you change viewing modes from 'Month' to 'Two Week' or 'Week', it simply hides the extra weeks. The purpose of the other view modes is to make cells larger to fit more information and be less crammed for users who have many items on their calendar.
The new behavior is that the cells will expand based on the viewing mode as well as the number of items in each cell. 
This is not a breaking change and was tested on instructor and student accounts.
=> [Feature:Calendar] Changed Calendar Cells Based on View

site/app/controllers/grading/ElectronicGraderController.php, site/app/libraries/database/DatabaseQueries.php, site/cypress/e2e/Cypress-Gradeable/ta_grading.spec.js, site/phpstan-baseline.neon
As a grader, if you clear an overall comment, it will clear for all other graded submissions.
If you clear an overall comment, it will only clear that submission's overall comment. A Cypress test was added to confirm this behavior.
=> [Bugfix:TAGrading] Fix deleting all comments

grading/TestCase.cpp, grading/load_config_json.cpp
Fixes #10121 . Currently, the autograder only copies .out and .class files from the compiler to the runner. This means if the instructor creates a compilation testcase that compiles into anything other than .out or .class, the file will not be copied to the runner and other testcases will fail.
Now, in addition to copying all .out and .class files to the runner, any file that is listed in the "executable_name" field in the gradeable's config.json will also be copied to the runner. 
This needs more testing. I've been able to verify that it works when a single executable is produced, but I haven't been able to test whether it correctly handles an array of executable names. I'm currently working on a java example for this, and I'll upload it as a separate PR when it's done.
=> [Bugfix:Autograding] Copy all named executables to runner

site/app/controllers/student/SubmissionController.php
Closes #9566 
Instructor still has access to submission page for a team-gradeable even after team has been abandoned
Instructor or any other user gets booted out of submission page on reload, if not present in a team
- Open two browsers, login as same instructor in both
- In first browser, create a team and access a team-gradeable's submission page
- In second, go to manage teams and leave the team
- Come back to first and reload the page
- You can observe that the user gets redirected out of submission page with an alert saying "Must be on a team to access submission."
=> [Bugfix:Submission] Redirect out of submission if no team

site/app/controllers/forum/ForumController.php
If you are on the forum page and a new post is added through the websocket, an error will come up that it cannot parse new post. It will also frog robot on the backend.
New posts will dynamically load in without an issue. This was due to missing arguments in the createPost function when called by renderTemplate.
Tested locally and new forum posts load fine
=> [Bugfix:Forum] Fix forum socket update

site/app/views/NavigationView.php
When Exam Seating is misconfigured (files missing, named incorrectly, values incorrect) we get crashes (Frog Robot) instead of more helpful error messages.  
Here's one specific error that will be fixed with this PR change
```
TypeError (Code: 0) thrown in /usr/local/submitty/site/app/views/NavigationView.php (Line 152) by:
if (property_exists($user_seating_details, 'building') && property_exists($user_seating_details, 'room')) {
Message:
property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
```
=> [Bugfix:InstructorUI] error checking logic for exam seating

site/tests/app/entities/poll/PollTester.php
Fixes PHP unit test to remove errors with timezones.
=> [Bugfix:SubminiPolls] Fixing PHP Unit Test

site/public/js/ta-grading.js
Fixes #10379 
The silent regrade box is checked corresponded to the "silent_edit_enabled" cookies. Always keep updated.
I found the problem is due to the wrong type of variable "silent_edit_enabled" read from the cookies. Previously, it was read as a string, however it should be casted to boolean.
https://github.com/Submitty/Submitty/assets/60954116/2f0f9fca-0c14-48eb-b050-72ef19eaa0e3
=> [Bugfix:TAGrading] Keep Silent Regrade Box Checked

grading/CMakeLists.txt
The Submitty installation script currently prints a CMake deprecation error:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
This PR increases the minimum required CMake version to 3.20.  The current version of CMake installed in the VM is 3.22.
=> [Refactor:System] Update minimum CMake to 3.20

site/public/js/ta-grading-rubric.js, site/public/templates/grading/Functions.twig, site/public/templates/grading/TotalPeerScoreBox.twig, site/public/templates/grading/TotalScoreBox.twig
On the TA grading rubric page, toggling components (switching to the next question for grading) takes a long time to load. This slowdown occurs because:
toggleComponent() consists of two steps: closeAllComponents() and openComponent()
- Closing all components: Attempts to call closeComponent() on all components. Each call to closeComponent() waits for the server to save and then calls updateTotals() to update the total score. updateTotals() rerenders the entire gradeable component, which is time-consuming.
- Opening a component: It waits for closeAllComponents() to finish, then waits again for the server to retrieve the component.
With the implemented changes:
- Component information is now stored in a global list, so open component can render using info from the list
- …
=> [Refactor:TAGrading] speed up rubric grading page

grading/system_call_categories.cpp, grading/system_call_check.cpp, more_autograding_examples/c_failure_messages/config/config.json
The c_failure_messages example from more_autograding_examples does not work on M2.
It gets a zero grade due to a system call failure when running sort.
With these changes, now the submission runs and receives full credit.
Also the system_call_check utility had the wrong system call count.
=> [Bugfix:Autograding] system calls for c_failure_messages/M2

site/app/controllers/forum/ForumController.php
Changing
BEFORE
these implementations to have new PHP 8 syntax
ex)
AFTER
Refactors all of the @routes to the new PHP8 Syntax of #[Route()] for all route calls in forum controller file.
=> [Refactor:System] forum refactoring @routes

site/app/models/gradeable/Gradeable.php
When graders are assigned to grade by registration section and instruction did not assign any section, progress bar under the grade button is missing
show the progress bar
=> [Bugfix:TAGrading] progress bar

.setup/INSTALL_SUBMITTY_HELPER.sh, site/app/views/submission/HomeworkView.php
PR https://github.com/Submitty/Submitty/pull/10164 added a migration which changed the permissions of the vcs directory and subdirectories. In one of the install scripts it changes the permission back to the old value which breaks the website submission. Also it only uses the student ID for checking the repo path.
The install script was edited to set permissions correctly. Now it will use student ID or team ID for the repo path to support team gradeables too.
Tested locally and submission pages works correctly after install
=> [Bugfix:System] Fix VCS permission on install

.setup/pip/system_requirements.txt
Docker-py breaks with the current version of requests (2.32.0)
This PR pins requests version to 2.31.0, which will fix Docker until a hotfix is applied to docker-py.
=> [Dependency] Pin requests version to 2.31.0

site/app/controllers/student/SubmissionController.php, site/cypress/e2e/Cypress-Feature/student_api.spec.js
Currently, the student api only returns the total grade points, and doesn't include which of the tests the points came from. 
This adds the testcases the user can view to the return values, giving more information on what failed, and why. 
API tests will be converted to Jest in a future PR.
=> [Feature:API] Add testcases to student api

site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
This issue was introduced in https://github.com/Submitty/Submitty/pull/10339, it changed the default value to the Instructions URL instead of the title.
The default value has been reverted back to the title.
=> [Bugfix:InstructorUI] Fix displaying title

site/public/js/forum.js
Resolves #10466 
Liking a forum post fails due to incorrect AJAX call.
The path has been updated to reflect the change in #10373.
=> [Bugfix:Forum] Fix AJAX call for post likes

.setup/INSTALL_SUBMITTY_HELPER.sh, bin/generate_repos.py, migration/migrator/migrations/system/20240528015719_update_vcs_perms.py
You cannot clone submitty hosted vcs git repositories. This is due to a recent git security patch and our permission configuration.
The vcs git directories are now owned by submitty_cgi rather than root. This fixes the dubious ownership problem without requiring safe directories for every git repo on the system.
Verified locally that I can clone now
=> [Bugfix:Submission] Fix Git Vcs Permission Issue

site/public/js/forum.js
Currently, the reply buttons on the forum are disabled when no text or files have been added for a valid response to a post, but the respond and unresolve button is not accounted for.
The respond and unresolve button is now accounted for when viewing as a student or instructor after a given post has been marked as resolved. 
This is a small change that builds on the implementation in [#10129](https://github.com/Submitty/Submitty/pull/10129)
=> [Bugfix:Forum] Disable Unresolve Button

sbin/adduser_course.py
In https://github.com/Submitty/Submitty/pull/10133, a new group argument was added to the adduser script. However, it is not an optional argument since it is missing `--`. The create course script will error as is and not add the instructor to the course.
`--` has been added in front of the argument so this is now an optional argument. The create course script does not fail anymore.
Tested locally and it fixed it.
=> [Bugfix:System] Adduser group optional

site/app/templates/admin/RainbowCustomization.twig
HTML no longer has a blank span tag, which does not visibly change the site.
=> [Bugfix:RainbowGrades] Close span tag in RainbowCustomization

site/app/templates/admin/users/GraderList.twig
There is a typo closing tag in GraderList.twig,
```html
<th class="section-break" colspan="8">{{groups[grading_group].name}}</td>
```
In view-source mode, my browser complains about it.
Changes `</td>` to `</th>`.
=> [Bugfix:InstructorUI] Fix HTML typo in GraderList

site/app/templates/course/CourseMaterials.twig, site/app/templates/submission/homework/CurrentVersionResults.twig
Currently, students can access course materials in two ways: download or view in browser.
However, for files submitted to a gradeable, students can only download the file if they want to read it.
This can make it annoying for students trying to verify that the file they submitted is the correct one,
or verifying that their answer to a problem was correct.
Also, downloading the file across different versions clutters the user's downloads folder with multiple
different versions of the same file.
A "view" button has been added to the gradeable submission view, allowing students to view a pop up window displaying a submitted file in their browser, parallel to the current grader view functionality.
=> [Feature:Submission] View submitted file button

Vagrantfile
The `vagrant provision` command will now display a warning to the user if the system has already been provisioned.
Resolves #10286
=> [Feature:System] Add vagrant provision warning

site/public/css/forum.css
Fix #10485
Thread won't be able to view when exceed the width of post box, might stop student from viewing wider code blocks.
Added horizontal scroll as the issue mentioned
=> [Bugfix:Forum] Post not displaying when exceed width

site/app/templates/grading/electronic/NotebookPanel.twig, site/app/templates/notebook/Notebook.twig, site/public/js/ta-grading.js
Closes #10510
**No title for Notebook** 
Keyboard shortcut bug (Reflecting to same panel for both Key G and N)
https://github.com/Submitty/Submitty/assets/119070053/96419705-d32b-42bd-8caf-cfd32d165a07
**Fixed the Title**
**Fixed the Bug**
https://github.com/Submitty/Submitty/assets/119070053/b973e44c-8ac7-478c-90fb-f25dd6397b82
=> [Bugfix:TAGrading] Fixed title and Shortcut for Notebook

.setup/install_system.sh, migration/migrator/migrations/system/20240606141301_add_git_safe_dir_daemon.py
When submitting a vcs gradeable, submitty_daemon cannot clone the local repository due to how git handles permissions.
git `safe.directory = *` has been added so that submitty_daemon can clone the local repository.
Tested locally that it fixes the problem
=> [Bugfix:Submission] Add git safe dir * for daemon

site/public/js/userform.js
In manage graders,
When cancel edit graders immediatly after opening it, the confirm(Changes to the form will be lost!) pops up and ask for your action which is quite annouying. You can test it here. http://localhost:1511/courses/s24/sample/graders). See video below:
https://github.com/Submitty/Submitty/assets/122962727/f49701f9-3092-4a01-ac75-8566cd7846ee
Fix the isForumEdited function so it functions correctly
=> [Bugfix:InstructorUI] Fix manage grader save changes popup

.setup/CONFIGURE_SUBMITTY.py
Currently, when the CONFIGURE_SUBMITTY.py script is run, the system_message field located in /usr/local/submitty/config/submitty.json is not preserved. This can be annoying for sysadmins who don't want to have to rewrite their system_message everytime after they run CONFIGURE_SUBMITTY.py.
Closes #8151 
If the submitty.json file has defined a system_message, field, it is saved into the config of the new file.
You can test this by running the CONFIGURE_SUBMITTY.py script located in /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/CONFIGURE_SUBMITTY.py
Please try all sorts of edge cases. 
Examples:
Delete the submitty.json file and run
Change the field and run and make sure that it is preserved
leave the field empty
NOTE: we are assuming that the file is valid json, that is the user's …
=> [Bugfix:System] Preserve submitty config keys

.github/bin/label_abandoned_prs.py
Fixes #10449. The Github action that auto-tags abandoned PRs is bugged because it does not run on all PRs at once. This is because the script uses the command https://github.com/Submitty/Submitty/blob/54cc10dc7bcb385eabc95294382c65af9f9e8709/.github/bin/label_abandoned_prs.py#L6 By default, the Github CLI will return only 30 PRs (see the [documentation](https://cli.github.com/manual/gh_pr_list)), and obviously we have more than 30 open PRs. The CLI also returns the 30 *most recent* open PRs, so if a PR is old enough then it can just never get tagged, e.g. #8251.
The reason why this was causing #10449 is because if there were more than 30 open PRs, and the 31st most recent PR was abandoned, the action would not "see" this PR and not tag it as such until one of the 30 most recent was merged …
=> [Bugfix:Developer] Fix auto-tagger not running on all PRs

.github/bin/label_abandoned_prs.py
Currently, the auto-tag action attempts to remove the abandoned tag from all approved PRs, including those that don't actually have the abandoned tag. This is undesirable. 
The action now only removes the abandoned tag from *abandoned* PRs that have been approved.
=> [Bugfix:Developer] Fix auto-tagger spamming GH API

.github/bin/label_abandoned_prs.py
Currently, the auto-tag action crashes if any of the PRs it processes have neither been approved nor had changes requested, due to an undefined variable. This is related to #10449 and #10519.
This fixes the issue by setting `approved` to `False` when no approval or change requested exists.
=> [Bugfix:Developer] Fix auto-tag action crashing

site/app/templates/admin/RainbowCustomization.twig, site/cypress/e2e/Cypress-System/accessibility.spec.js, site/cypress/fixtures/accessibility_baseline.json
To view changes, login to Instructor, navigate to Grade Reports > Web-Based Rainbow Grades Generation
Resolves #10505
HTML validator does not catch issues with Rainbow Grades Customization.
HTML validator catches issues with Rainbow Grades Customization, with no visual UI changes (only those that affect accessibility).
(the alert stems from the navigation menu, not Rainbow Customization)
Cypress Accessibility tests pass for Rainbow Grades Customization, and the site is visually unchanged.
Site accessibility was tested with WAVE.
=> [Testing:RainbowGrades] Rainbow customization accessibility

site/app/templates/admin/users/StudentList.twig
There is a typo'd closing tag in StudentList.twig, https://github.com/Submitty/Submitty/blob/ce5cfa3836e1719bf502476da254234f881108b9/site/app/templates/admin/users/StudentList.twig#L93
In view-source mode, Firefox complains about it.
Changes `</td>` to `</th>`.
=> [Bugfix:InstructorUI] Fix HTML typo in StudentList

.setup/SUBMITTY_TEST.sh, .setup/install_system.sh
1) The test shortcut for PHP linting, submitty_test, does not show up to submitty_help. 
2) Composer installs whenever the command is ran.
1) Added text to show that submitty_test exists.
2) Moved composer to only install when a PHP lint is called.
=> [Refactor:System] Adding submitty_test to submitty_help

.github/bin/label_abandoned_prs.py
If a PR is abandoned, then picked up by a new owner, and then left inactive for 2 days, then the PR is re-tagged as abandoned. This is because the warning has already been issued the first time and the script checks if it exists at all before tagging as abandoned. 
This PR makes the script only check the latest comment for the inactivity warning before tagging so that this doesn't happen.
=> [Bugfix:Developer] Fix stale PR CI retagging after 2 days

site/app/templates/admin/RainbowCustomization.twig, site/public/css/rainbow-customization.css, site/public/js/rainbow-customization.js
Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.
The Rainbow Grades web customization includes collapsible_area items which are meant to reduce clutter, but they mostly get in the way. The toggle occurs when the title of each section is clicked.
Removes each collapsible_area without otherwise affecting the UI.
=> [UI/UX:RainbowGrades] Remove collapsibles from web config

.github/workflows/save_vm.yaml
Github's documentation showed a given way to send a single multi-line command, however it wasn't working, and the zulip message was failing to send.
The Zulip message for the Package Vagrant VM job now correctly sends the message
https://submitty.zulipchat.com/#narrow/stream/409362-Submitty-Developer-Studio/topic/Vagrant.20Up.20Failures/near/444330979
=> [Bugfix:Developer] Fix Package VM Zulip Message

site/app/templates/notebook/Notebook.twig
fixes #10543
**Screenshots**
This screenshot was supplied by @KCony 
The upload feature does not work for notebook gradeable.
The upload feature works as expected for notebook gradeable. 
Please test this in many methods. 
Few I can think of is creating your own notebook gradeable, and use given [config.json](https://github.com/user-attachments/files/15809028/config.json) and attempt to upload file. 
Another way is to go to sample course -> gradeable -> notebook_filesubmission
and test the upload functionality. (Please refer to my screenshot above)
The problem was addFile & fileExists function in drag-and-drop.js has array that needs to be initialized but was missing it. 
The fix is minimal.
=> [Bugfix:Submission] Notebook upload file fix

.setup/install_system.sh, Vagrantfile
When using libvirt as the Vagrant backend, the GIT_CHECKOUT folder in the vm has the wrong permissions, and other small problems that prevent usage. 
* Sets the permission of GIT_CHECKOUT to 0755 if the virtual machine is running in dev mode
* When running with libvirt, vagrant now uses libvirt's qemu/kvm user session instead of the system one 
* When running with libvirt, vagrant now explicitly uses rsync to keep the vm's files in sync with the host
* To sync files, the user must run `vagrant rsync-auto` on the host.
No
`vagrant up --provider=libvirt`
=> [Bugfix:System] Improve libvirt support

site/public/js/server.js
Fixes #10541
Currently, the 'preview' button for a post on the discussion forum does not get marked as active (highlighted in white) when it is clicked.
This bug was caused by #10203
The 'preview' button activity will get toggled on click.
=> [Bugfix:Forum] Fix toggle active on preview

site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js
If the tests in late_submission_warning_messages.spec.js fail, windows default extraction tool cannot extract the zip file because the file path is too long, since the it description becomes the name of the file.
The IT descriptions have been shortened to allow for the default extraction tool to be able to extract the zip file. 
This doesn't change the tests at all, just the descriptors.
=> [Testing:Developer] Change IT messages to be shorter

site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
Closes #10556
Issue #10556
While editing a peer grading gradeable, if new graders are assigned to the peer grading matrix, the error 'self_grading is not defined' will appear in the console.
https://github.com/Submitty/Submitty/assets/119070053/c0ca516b-61af-4d25-87d0-31634c5370f0
=> [Bugfix:TAGrading] define self_grading

.setup/data/courses/development.yml
Thank you to @RitaLei123 for starting on this in a PR (#10068), this reverts some of the extra changes in that PR which fell out of scope of the issue. 
Resolves #9485 by changing the PDF Exam gradable to actually being a PDF exam (bulk upload by graders) and not student-submitted as before.
Making an issue to follow up on the problems I think Rita noticed while working on this.
Screenshot showing the change:
=> [Bugfix:Autograding] Update PDF Dev Gradable

autograder/autograder/scheduler.py, autograder/tests/test_scheduler.py
With the scheduler refactor a number of years ago, we lost 2 important sorting criteria.
Interactive jobs must be prioritized over batch jobs.
VCS submissions that have not been checked out must be prioritized over autograding jobs
The sort criteria in the scheduler now reflects these priorities.
=> [Bugfix:Autograding] prioritize autograding jobs

site/app/templates/admin/RainbowCustomization.twig, site/public/css/rainbow-customization.css
To test functionality, login as Instructor, then navigate to Grade Reports -> Web-Based Rainbow Grades Generation.
Several input fields on the Web-Based Rainbow Grades Generation page are unaligned.
Consistently aligns input fields.
=> [UI/UX:RainbowGrades] Align customization fields

site/public/css/markdown.css
Fix #10606 
Makrdown buttons were exceeding the width of the container.
Buttons are wrapped now.
https://github.com/Submitty/Submitty/assets/122962727/6e96de80-6853-462f-9cd7-dfa151e4fd00
=> [Bugfix:TAGrading] Markdown buttons exceeding width

site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig
Part of the header for the New/Edit Gradeable page, which displayed the title and ID of the gradeable, was accidentally removed in PR #10100 (Ability to Upload JSON to make gradeable) by the commit titled 'better code, catch parse errors, change button location'.
The deleted element was reintroduced and the Javascript was improved slightly.
=> [Bugfix:InstructorUI] Fix New/Edit Gradeable Header

.github/FIRST_ISSUE_REPLY.md
The messages we post in response to comments from new contributors are currently ill-formatted, with excess newlines.  For example:
This PR removes the newlines to fix the formatting:
=> [Documentation:Developer] Fix formatting of first message reply

site/public/js/rainbow-customization.js
To test functionality, login as Instructor, then navigate to Grade Reports -> Web-Based Rainbow Grades Generation.
Currently, 'section',  'messages, and 'final_grade' should have a corresponding dropdown item.
The Web-Based Rainbow Grades Generation page is cluttered, and will become more so if new items are added to it in the future.
Simplifies the process of adding customization items as show/hide options via checkbox dropdowns. It also incorporates existing customization items into dropdowns.
https://github.com/Submitty/Submitty/assets/56311867/417766d1-61f5-4fae-91ee-d161d5a15e1e
=> [UI/UX:RainbowGrades] Expand Customization dropdowns

Vagrantfile
If you want to do a full vagrant up without using the prebuilt vagrant box, you use `BASE_BOX=1 vagrant up`
Also, there is no way to specify the version of the prebuilt box without editing the vagrant file. 
`BASE_BOX=1` variable name is somewhat confusing, so `FROM_SCRATCH=1` is the new method, and `BASE_BOX=1` will be deprecated, and removed sometime in the future. 
`PREBUILT_VERSION={version}` has been added as a supported ENV variable.
**NOTE** 
Use JUST the numbers and the decimals, NOT the leading V. 
An example :
`PREBUILT_VERSION=24.04.01.2405050238 vagrant up` for mac and linux or 
`SET PREBUILT_VERSION=24.04.01.2405050238`
`vagrant up` for windows
=> [Feature:Developer] Add FROM_SCRATCH and PREBUILT_VERSION

site/app/templates/notebook/Notebook.twig
The answer fields in the notebook panel of the TA grading interface are only disabled for submissions other than the active submission.  These fields should always be disabled in the TA grading interface.
All notebook fields are disabled in the TA grading interface.  In
In the future, it would be good to put together a set of comprehensive tests for the notebook panel of the TA grading interface.
=> [UI/UX:TAGrading] Disable notebook fields when grading

site/app/templates/notebook/Notebook.twig
The TA grading interface currently shows control buttons in the notebook panel.  These buttons serve no purpose in this context.
This PR removes the control buttons:
=> [UI/UX:TAGrading] Hide notebook control buttons

site/cypress/e2e/Cypress-Gradeable/peer_grading_component.spec.js
#10560 was merged without merging main into it before to get the most recent eslint changes, and when it was merged, the Cypress tests failed the linting tests
The JS lint tests have been fixed for the files added.
=> [Bugfix:Developer] Fix JS Lint

site/app/controllers/MiscController.php
Fix #9984
Instructor is unable to view previous pdf submission.
Viewing earlier pdf submission will result in error caused by the line below in function `encodePDF`
`$check_path = FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), $directory, $gradeable_id, $id, $active_version);`
https://github.com/Submitty/Submitty/assets/122962727/9c1ff290-b0f2-4a03-b2fb-292f4120cec2
=> [Bugfix:TAGrading] unable to view earlier pdf submission

site/cypress/e2e/Cypress-TAGrading/test_rubric_access.spec.js
Fixes the issue of CI failing on TAGrading because of a rubric spec using hard-coded spring24.
=> [Bugfix:TAGrading] Fix spec using S24 courses

site/public/js/rainbow-customization.js
Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.
The following error on the Rainbow Grades customization page was caused by a refactor in PR #10551 (Update ESLint style rules).
Final Cutoffs can once again be set using the Rainbow Grades customization page.
=> [Bugfix:RainbowGrades] Fix final cutoff customization

site/eslint.config.js
ESLint lints files in `site/vendor`
It ignores all files in any folder that is named "vendor".
=> [Bugfix:Developer] Fix ESLint ignores

.setup/bin/sample_courses/utils/__init__.py, .setup/bin/sample_courses/utils/dependent.py
A recent update to git now requires non-owners of shared repository directory to specify each directory as "safe".  This change broke our "vagrant up" scripts because 'git clone' and other git commands were run by the root user in the create sample courses script.   These directories are owned by the submitty_cgi user.
Now the git commands in create sample course script are run by the submitty_daemon user, which does have a global safe directory set.
=> [Bugfix:System] git clone in create sample courses

.github_actions_ci_flag, .gitignore, .setup/INSTALL_SUBMITTY_HELPER.sh
The CI flag works on CI, but not locally because of a formatting issue. 
The CI flag is now fixed, and accurately skipping the NTPD setup on CI, but allowing it to run on local machines. 
Also, the flag file was added, so all users who didn't delete the file were running it as if they were in the CI, so this file has been added to the .gitignore file, so if someone is testing the feature, it won't be committed and sent to all users who pull.
=> [Bugfix:Developer] Fix CI Flag and Ignore Flag File

site/app/models/RainbowCustomizationJSON.php
Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.
There is an unused checkbox for benchmark_percent under Display. Benchmark percents are toggled using Display Benchmarks.
Removed benchmark_percent checkbox.
Merge https://github.com/Submitty/RainbowGrades/pull/76 simultaneously so that behavior of Submitty and RainbowGrades repositories match.
=> [Feature:RainbowGrades] Remove benchmark_percent from display

site/app/models/RainbowCustomization.php
Currently, when web-based GUI customization page is rendered, users may get below screenshot image warning (screenshot credit to @zacharymnp) 
This is occurring because when we are loading json, it is looking for remove_lowest even when there is none.
In order to reproduce/test this issue, go to reports page -> customization page -> drag few gradeable to assigned bucket. Hit save changes. Refresh page, and will see the screenshot warning. 
With this change, it checks whether remove_lowest is specified or not, and if it is not, it would set it to zero, and only parse when it is specified.
=> [Bugfix:InstructorUI] Remove lowest null handling

site/app/templates/notebook/Notebook.twig, site/public/js/code-mirror-utils.js
Fix #10643
CodeMirror currently displays accessibility help text above all code boxes. This text is confusing in places where the code box is disabled and it is impossible to navigate to it.
This commit updates the `getLargeCodeMirror` function to conditionally display the accessibility help text only when the CodeMirror instance is enabled. This prevents confusion in scenarios where the code box is disabled and navigation is not possible.
=> [Feature:Submission] Hide Accessibility Text for Disabled

site/app/templates/grading/electronic/GradingPanelHeader.twig, site/cypress/e2e/Cypress-TAGrading/ta_grading_comments.spec.js, site/cypress/e2e/Cypress-TAGrading/test_rubric_access.spec.js, site/public/templates/grading/GradingComponentHeader.twig, site/public/templates/grading/OverallComment.twig, site/public/templates/grading/SavingTools.twig, site/public/templates/misc/MarkdownArea.twig
Elements in the TA grading interface are not referenced by data-testid in cypress tests.
Adds and uses test ids to refer to those elements.
=> [Refactor:TAGrading] Add test ids for elements used in tests

site/app/templates/grading/electronic/Details.twig
Closes #10120 
Too Many late days are not in the anonymous view of the TA Grading Interface
Add in "Too many late days" to the anonymous view of the TA Grading Interface.
https://www.diffchecker.com/oRToVozk/
Should we do anything about these two functions? They are practically the same.
In addition, the peer view of grading anonymous should never run.
=> [Bugfix:TAGrading] Anonymous Mode now shows too late

site/app/templates/grading/electronic/SubmissionPanel.twig
Currently, from a TA page, trying to download user_assignment_settings.json would result in a frog error as there is no access to a directory called "user_assignment_settings.json". 
Similar to #10429, we pass in the directory of submission_versions and its permissions as the file permissions.
Closes #10631 
Related to #10429
=> [Bugfix:TAGrading] Download user_assignment_settings.json

site/app/templates/officeHoursQueue/NewQueue.twig, site/app/templates/officeHoursQueue/QueueButtonBar.twig, site/app/templates/officeHoursQueue/QueueFilter.twig
Open New Queue and Edit Existing Queue buttons on the instructor view on the Office Hours Queue page are misnamed.
Buttons renamed to Create Queue and Edit Queue.
=> [UI/UX:InstructorUI] Rename Create and Edit Queue buttons

migration/migrator/migrations/course/20240707024127_sloc_for_barb.py
Current migration #10678 has some issue, it does not check if the constraint already exists.
This is a problem if system goes over some migration up & rollback, and fails with error "sloc_non_negative" constraint already exist. To prevent this happening we need to check if the constraint exists. 
Hoewever, PostgreSQL does not support ADD CONSTRAINT IF NOT EXISTS 
So one of the many option is to have DROP IF EXISTS before ADD regardless.
Yes it is expensive operation but we are OK with it.
You can find some reference in other migrations that we did (ex: user_last_initial_format.py)
=> [Bugfix:System]  sloc drop constraint fix

site/app/templates/admin/RainbowCustomization.twig
Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.
Initial reordering of items in Rainbow Web-Customization to the following scheme. Some of the following items have not yet been added.
1. display
2. messages
3. gradeables
4. benchmarks checkboxes
5. display %
6. section
7. final cutoffs
8. manual grades
9. notes
10. warning
11. plagiarism
=> [UI/UX:RainbowGrades] Reorder RainbowCustomization items

.github/workflows/submitty_ci.yml, site/public/css/colors.css
The `colors.css` file is prone to becoming bloated over time; there are many duplicate and unnecessary colors and the file has grown to be pointlessly large.
This PR adds a CI check to make sure that new PRs do not increase the size of `colors.css`.
In commit 570f9a1, the check fails because I added a couple lines to `colors.css`.
After reverting changes to `colors.css` in 4263c64, the check passes.
=> [Feature:Developer] Add colors.css check

site/app/controllers/forum/ForumController.php
When attempting to fetch a single post, ForumController will send a frog robot due to an incorrect argument error.
ForumController works as intended.
=> [Bugfix:Forum] Fix ForumController's incorrect argument

site/app/templates/admin/RainbowCustomization.twig, site/public/js/rainbow-customization.js
The _Penalties for Academic Dishonesty and Plagiarism_ was partially refactored when the _Manual Grading_ table was added. There were a few portions that were missed leading to a loss of functionality of the _Penalties for Academic Dishonesty and Plagiarism_ table
_Penalties for Academic Dishonesty and Plagiarism_ table works.
=> [Bugfix:RainbowGrades] Fix plagiarism table refactor

site/public/js/notebook_builder/widgets/markdown-widget.js, site/public/js/notebook_builder/widgets/widget.js
This typeError is after the merged of this PR #10554
as **NUM_MARKDOWN** is assigned `const `but  we are changing this variable value in markdown-widget.js 
https://github.com/Submitty/Submitty/blob/9ca03854abffa3cebea8420b25d88f8c2a4f6010/site/public/js/notebook_builder/widgets/markdown-widget.js#L58
https://github.com/user-attachments/assets/05bf071d-383d-418a-bd4f-1c9f67f583dc
fixed the typeerror
Head over to any notebook_builder (http://localhost:1511/courses/f24/sample/notebook_builder/open_homework/edit)
click on markdown button
=> [Bugfix:Submission] TypeError NUM_MARKDOWN variable

site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
PR https://github.com/Submitty/Submitty/pull/10557 (define self_grading) missed a relevant change.
The expected error message when a student is added as their own grader is "**Please note that student is not able to grade themselves**", but the following error is returned instead. This is because the value of self_grading is not updated properly.
After Zach request i tried all possible way to put valid student and grader i findthis issue (see the video)
https://github.com/user-attachments/assets/51372222-01a7-4626-a0c5-acfb989f5caf
The expected error message returned.
https://github.com/user-attachments/assets/8d47ec13-52e6-4d44-9990-bfdfb5da0ebf
=> [Bugfix:TAGrading] Fix self_grading always false

more_autograding_examples/notebook_time_limit/config/custom_validation_code/timelimit.py
#5286 introduced a `timelimit.py` script. However, it is not using some of the modules, `traceback`, `re`, `tzlocal`
Discovered during tzlocal reviewing process, and think we should clean up un-used imports for better searching results too. 
To test this PR, go to the file, and inspect if modules are used or not.
=> [Refactor:Autograding] rm unnecessary import

site/app/templates/officeHoursQueue/QueueFooter.twig
Fix #10729 
In office hour queue, when notification is turned on, it only triggers when student joins an empty queue.
In addition, the sound triggers when student leaves the queue which is pretty unnecessasry.
Now notification triggers whenever student joins a queue and not when they leave.
=> [Feature:HelpQueue] Fix queue notification trigger

site/public/css/forum.css
Fixes #10722 
In the case post content is around a line long, the rendering for preview is broken.
Added work break css.
=> [Bugfix:Forum] Fix forum post preview rendering problem

site/app/templates/NotificationSettings.twig, site/app/templates/admin/Report.twig, site/app/templates/admin/admin_gradeable/AdminGradeableBase.twig, site/app/templates/admin/late_day_cache/LateDayCacheBase.twig, site/app/templates/autograding/TAResults.twig, site/app/templates/forum/CreatePost.twig, site/app/templates/forum/ShowCategories.twig, site/app/templates/generic/Popup.twig, site/app/templates/grading/electronic/AutogradingPanel.twig, site/app/templates/grading/electronic/Details.twig, site/app/templates/grading/electronic/GradingPanelHeader.twig, site/app/templates/grading/electronic/NavigationBar.twig, site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig, site/app/templates/grading/electronic/SubmissionPanel.twig, site/app/templates/grading/popup_refactor/NavigationBar.twig, site/app/templates/grading/simple/Display.twig, site/app/templates/misc/MarkdownArea.twig, site/app/templates/submission/Team.twig, site/app/templates/submission/grade_inquiry/Discussion.twig, site/app/templates/submission/homework/BulkUploadBox.twig, site/app/templates/submission/homework/BulkUploadProgressBox.twig, site/app/templates/submission/homework/CurrentVersionResults.twig, site/app/templates/submission/homework/leaderboard/Leaderboard.twig, site/public/templates/grading/settings/HotkeyList.twig, site/public/templates/misc/MarkdownArea.twig
Per Shail from #7819, remove all uses of `key_to_click` on buttons, where this class is redundant and serves no purpose since the functionality that `key_to_click` implements is the default for buttons.
=> [Refactor:Developer] Remove key_to_click from buttons

site/app/controllers/admin/ReportController.php
#10433  is related issue. 
In order to add link to submission in Rainbowgrades, we need to know the base_url of the server.
However, generate grade summaries(ggs) does not load url info. 
With this change, ggs will create/store `base_url.json` in the reports directory. `({$SUBMITTY_DATA_DIR}/courses/{$SEMESTER}/{$COURSE}/reports)`
go to http://localhost:1511/courses/f24/sample/reports
click Generate Grade Summaries -> go to terminal and `cd /var/local/submitty/courses/f24/sample/reports`
see base_url.json -> see the content by `emacs base_url.json`
check base_url is `http://localhost:1511/`
=> [Feature:RainbowGrades] base_url for rainbowgrades

Vagrantfile
Vagrant currently attempts to forward to host port 7000 for SAML, which conflicts with the AirPlay receiver on macOS, which runs all the time by default.
Since we don't want new developers to have to deal with port conflicts on their first vagrant up, this PR changes the default port to 7001.
=> [Refactor:Developer] Update SAML port to 7001

site/public/css/diff-viewer.css
Fixes #10760 
Rows in autograding result not matching due to paddings between rows in expected output and empty rows having a smaller height.
Give a preset height for rows in autograding result that would fit paddings too.
=> [Bugfix:Autograding] Output rows not matching

site/app/templates/notebook/Notebook.twig, site/public/css/server.css
Notebooks are currently rendered with no space between cells. 
This PR adds subtle separators between cells in a notebook.  A side effect of this change is output cells becoming detached from the cell the output came from.  In a future PR, I plan to render output cells as children of a parent cell, rather than their own standalone cells.
=> [UI/UX:Submission] Add separators between notebook cells

site/cypress/e2e/Cypress-Feature/late_days_cache.spec.js
Currently some cypress tests are failing due to the page not waiting for reload. 
This PR aims to wait for the page changes.
=> [Bugfix:Submission] Fix Flaky Cypress Test - Late Day Cache

site/app/libraries/NotebookUtils.php, site/app/templates/notebook/Notebook.twig
#10648 added bare-bones support for viewing Jupyter notebooks in Submitty natively.  As of that PR, only text output is supported. 
This PR adds image output rendering to our Jupyter notebook support.  As per the [docs](https://jupyterlab.readthedocs.io/en/1.2.x/user/file_formats.html), we still need to implement several other types of output to be able to fully support Jupyter notebooks.  For now, the most common use cases have been covered.
=> [Feature:Submission] Render Jupyter output images

.github/workflows/sort_draft_prs.yml
Currently, PRs marked as draft retain their position in the project board.
This PR adds a Github Action that moves draft PRs to Work in Progress, and moves PRs marked as ready for review (i.e. PRs with the draft designation removed) to Seeking Reviewer.
=> [Feature:Developer] Auto move drafts to WIP

site/app/views/NavigationView.php
Version Conflict shows up too much on navigation, instead of View Grade/View Submission, because of a missing parenthesis in the conditional.
Fix the conditional
=> [Bugfix:Submission] Excessive Version Conflict on Navigation

bin/generate_repos.py
Fixes #10137 
First create 2 different gradeable to test the following three conditions.
Gradeable 1: Not a VCS gradeable
Gradeable 2: A VCS gradeable with vcs_type = " choose repository name (can be used for multiple gradeables)"
Case 1: It will exit directly and show warning messages. (use Gradeable 1)
Case 2: It will show different warning message, asking the user to create a gradeable in advance. (Random string to mock "gradeable id")
Case 3: It will show that the "repo_name" was found in at least one gradeable, and then ask the user whether to continue creating/update. (use Gradeable 2)
I am not sure whether this work flow is acceptable by users, please give me some suggestions! Thank you!
=> [Bugfix:InstructorUI] Different repo_name in generate_repos.py

.github/workflows/sort_draft_prs.yml
The auto draft mover fails.
Fixes a bug introduced in #10775. Variable `GITHUB_TOKEN` has been renamed to `GH_TOKEN` so that gh cli works correctly.
=> [Bugfix:Developer] Fix auto move drafts to WIP

.github/workflows/sort_draft_prs.yml
The auto draft mover fails.
Fixes another bug introduced in #10775. Secrets can't be passed between jobs, so I've converted this action to only use 1 job instead of 2.
=> [Bugfix:Developer] automate drafts on project board

.github/workflows/sort_draft_prs.yml
The auto draft mover fails.
Fixes one more bug introduced in #10775. By default, the github CLI only returns the most recent 30 PRs in queries, so this action would fail for any PR older than that due to not being able to find the PR ID. This PR changes the query to search the most recent 9999 PRs instead, which should be sufficient.
=> [Bugfix:Developer] Fix draft arranger for old PRs

Vagrantfile
It is currently difficult to test changes to Submitty docker images because the `DockerImages` and `DockerImagesRPI` repositories are not shared with the development VM if they are cloned locally.
This PR shares the `DockerImages` and `DockerImagesRPI` repositories with the development VM to make it easier to test changes to new images.
=> [Feature:Developer] Share DockerImages repo with dev VM

.github/workflows/sort_draft_prs.yml
Fixes a typo that breaks the "move non-drafts to Seeking Reviewer" functionality.
=> [Bugfix:Developer] Fix typo in draft PR arranger

site/public/css/navigation.css
fix #10816 
at 950px, the logic is break
I make the laptop view extend to 949 so 950 should still viewing what laptop size, and 949 will still behave as mobile UI
=> [UI/UX:Submission] Correct Collapse Gradeable's 950px

.github/dependabot.yml
Right now, there are two `package-ecosystem: "github-actions"` blocks in the Dependabot config. This is because the config predates the `directories:` feature.
This PR merges the two `github-actions` blocks into one using [`directories:`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories) to replace `directory:`.
=> [Refactor:Developer] Combine GH Actions Dependabot entries

.github/dependabot.yml
Dependabot does not check for updates in `/python_submitty_utils/requirements.txt`.
Dependabot does now checks for updates in `/python_submitty_utils/requirements.txt`.
=> [Bugfix:Developer] Add python_submitty_utils to Dependabot

.github/dependabot.yml
Currently, Dependabot fails to update Github Actions, with the following log error. This appears to have been an issue since it was added in #9431.
```
proxy | 2024/08/05 16:47:44 proxy starting, commit: f375444b32b70ee41e6084e7b6ffc09599dcc194
proxy | 2024/08/05 16:47:44 Listening (:1080)
updater | 2024-08-05T16:47:44.463490099 [865327624:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-08-05T16:47:46Z" level=info msg="guest starting" commit=10a56669fe8a0eaa1a40681e640fae7d411d58c1
updater | time="2024-08-05T16:47:46Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=865327624 updater_timeout=45m0s updater_version=5e17fc0ed2a028c94809836dd5e5b4495b1e3235-github-actions
updater | 2024/08/05 16:47:50 INFO …
```
=> [Bugfix:Developer] Fix Github Actions Dependabot

site/app/templates/grading/electronic/PDFAnnotationBar.twig, site/app/templates/notebook/Notebook.twig, site/public/js/drag-and-drop.js
Closes #10758
During testing for notebook view panel , when i add the notebook from notebook builder and move back to ta grading interface i am getting two uncaught syntaxerror
```js
Uncaught SyntaxError: Identifier 'showPopup' has already been declared
Uncaught SyntaxError: Identifier 'colorEvent' has already been declared
```
For `showPopup ` it is due to naming conflict, as we have variable and function with the same name 
For `colorEvent ` i did not get the possible reason for the syntax error
Fixes the both uncaught syntax error 
`colorEvent` is not used anywhere , so i wrap it inside the `emitEvent` function
And for `showPopup` its due to naming conflict, changed the variable name from `showPopup` to `show_popup`
=> [Bugfix:Submission] Uncaught SyntaxError

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20240816095713_late_days_constraint.py, site/app/controllers/admin/AdminGradeableController.php
You can enter a negative late days value, and although I don't think this impacts submission, it would not throw an error on the gradeable update screen.
You now cannot enter a negative value for values.
=> [Bugfix:InstructorUI] Force Late Days to be a positive number

site/app/libraries/database/DatabaseQueries.php
PR #10394 changed all rows[0] into row(), which might change the functionality of the code and therefore broke the office hour queue.
progress on #10895 but still needs cypress tests
Revert the changes so now it behaves as expected
Cypress tests might be needed in the future so that this doesn't break again (please I've been doing cypress too much lately can someone else do it 😭 )
=> [Bugfix:HelpQueue] Empty Codes for office hours queue

.github/workflows/notify_issues.yml
Zulip puts good first issues in the RPI devs channel
Zulip goes to Submitty Developer Studio (I think that was the agreed channel on during yesterdays meeting)
=> [Refactor:Developer] Change Zulip good first issue notifs

.setup/pip/dev_requirements.txt, site/app/models/gradeable/Gradeable.php
If we have an instructor user who is NOT in the linux group for the course.
And that instructor user uploads a config using the 'Edit Gradeable' -> 'Submissions/Autograding' -> 'Upload a custom autograding configuration' 
They unfortunately CANNOT select that config from the dropdown menu.
They get this error:
The step that verifies the user has linux permission to the selected directory is skipped if the path is a subdirectory of the courses config_upload directory.
=> [Bugfix:InstructorUI] skip perms check for config_upload

site/app/models/RainbowCustomization.php
After adding a gradeable to a bucket used in `customization.json`, the following error will appear after navigating to the Grade Reports > Web-Based GUI Customization.
Steps to Reproduce
1. Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.
2. Drag any item from **Available Buckets** to **Assigned Buckets**. 
3. Navigate to New Gradeable, and create a gradeable in the same bucket as used in the previous step.
4. Return to Web-Based Rainbow Grades Customization, and view error.
The new gradeable will no longer crash the customization page. If Per Gradeable Percents is enabled, the Per Gradeable Percent of the new gradeable will be the inverse of the number of gradeables in the bucket.
This error was introduced in PR #10763 (Add Gradeable Percents …
=> [Bugfix:RainbowGrades] Fix error when adding gradeable

site/app/controllers/PollController.php, site/app/templates/polls/AllPollsPageInstructor.twig, site/app/views/PollView.php
Fix #10897 
There is currently one array for both tomorrow's and future polls. 
Separate the tomorrow and future polls into two arrays.
=> [Bugfix:SubminiPolls] Separate Tomorrow and Future Polls

site/app/templates/forum/ForumBar.twig
unreleased forum categories shown in filter Fixes #10903
Its not showing now. 
I checked `threadpostform.twig` file, where the behavior was right. It was simply checking if the visible date is null or less than current time.
Therefore I added the same logic in `ForumBar.twig` file, I checked it worked fine, 
I have attached the screenshot
Unreleased Future category
Now its not present in filters inside forum.
=> [Bugfix:Forum] Hide future categories

.setup/INSTALL_SUBMITTY_HELPER.sh, autograder/autograder/execution_environments/container_network.py
All of our docker network names consist of the untrusted user ID plus a static string.
These docker network names now have a random ID appended to them to lower than chance of a network name collision.
Additional logging is added for network creation and deletion.
Docker is also restarted on every install.
Network name collision should not happen on most machines but it is happening on one of our production machines.
=> [Bugfix:Autograding] Docker Network Random ID

.github/workflows/vagrant_up.yaml
The Vagrant up github action is currently not working with the new VirtualBox 7.1 update. 
https://formulae.brew.sh/cask/virtualbox
https://forums.virtualbox.org/viewtopic.php?t=112320&sid=7ac5fd1e5fa51bd37e24ceede0fa6a1d&start=15
Restricts the version to 7.0.20
currently working on my [forked repo](https://github.com/williamschen23/Submitty/actions/workflows/vagrant_up.yaml)
=> [Bugfix:System] Temporary restrict Virtualbox to 7.0

site/app/templates/admin/RainbowCustomization.twig
Fixes #10881. The description of the "display_rank_to_individual" option in the Rainbow Grades Customization page was not spaced away properly due to formatting.
Increased the pixel width between options and descriptions, making it so display_rank_to_individual's description is formatted uniformly with the rest of the descriptions.
Before:
After:
Tested different website themes and resizes the browser via google chrome developer tools, looks fine from what I've seen.
=> [Bugfix:InstructorUI] Fix formatting in Rainbow Grade Page

site/app/models/gradeable/Gradeable.php, site/app/templates/Navigation.twig, site/cypress/e2e/Cypress-Gradeable/edit_gradeable.spec.js, site/public/css/bootstrap.css
Closes #10894 
When a gradeable is locked for a particular student, they do not know what prior gradeable they need to complete before being able to access the current one.
When a student hovers over the locked gradeable button, they see exactly what prior gradeable they need to complete and the score they need to receive on said gradeable.
To test, make a new gradeable with a prerequisite and required minimum score as an instructor. Then, as a student, hover over or click on that gradeable's "LOCKED" button.
=> [Bugfix:Submission] Fixing Alert to Explain Locked Gradeable

site/app/controllers/OfficeHoursQueueController.php, site/app/templates/officeHoursQueue/QueueFilter.twig, site/cypress/e2e/Cypress-Feature/office_hours_queue.spec.js
Attempting to modify a queue with an empty queue code will both fail at the html form validation level and at the server level.
Fixes #10895
Modifying a queue with an empty code will work as expected.
Tests have been updated to test both creation and modification of blank queue codes
=> [Bugfix:HelpQueue] Allow empty queue codes and add tests

site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
The current behavior is that the textbox that contains the total score doesn't update on delete.
Fix #10938 
Update the total score on delete
=> [Bugfix:InstructorUI] Numeric Gradeable total update on delete

site/app/models/QueueItem.php
Fixes #10952 
Currently there is a change when requesting https://submitty.cs.rpi.edu//autograding_status/get_update to trigger a fatal error when the list of Items in the queue to return has an item finish before the response is fully formulated.
Tested by submitting 1.5k gradables before and seeing the error occur multiple times while viewing the auto updating page, and then submitting 2k afterwards and not seeing the issue again.
=> [Bugfix:Autograding] autograding status race condition

site/public/js/ta-grading.js
Currently on different browsers, it either waits or doesn't wait for all the ajax calls to complete. This would result in a race condition where the code was getting components that weren't saved, and would not save it. From a graders standpoint, unless they had console open, they would not get an error.
Another aspect of this has to do with the different ways the browser deals with event loops, which chrome apparently just solves all async requests and then moves to the next page. However, Firefox and Safari casually just moves on while the async requests happen, which messes with the code as it is also looking for elements on the screen. At least this is my interpretation of the issue
partial(?) work for #10973 
Properly wait for all the ajax calls to complete. This is done through a …
=> [Bugfix:TAGrading] Wait for all Ajax calls to complete

site/app/libraries/NotebookUtils.php
Jupyter notebook rendering errors have been reported on production due to Jupyter notebooks using string values instead of array values for some fields.  For example:
```
TypeError (Code: 0) thrown in /usr/local/submitty/site/app/libraries/NotebookUtils.php (Line 26) by:
'markdown_data' => implode($cell['source']),
Message:
implode(): Argument #1 ($pieces) must be of type array, string given
.
.
.
```
This PR fixes the issue by handling an array if an array value is submitted, and casting to a string otherwise.
=> [Bugfix:Submission] Handle Jupyter string values properly

site/phpstan-baseline.neon, site/phpstan.neon
PHPstan wants to complain about generic types (specifically doctrine collections) being used in entities. As we expand the use of doctrine, these complaints will accumulate and will need to be added to the baseline.
Rather than adding "errors" that we know are correct and how we want to design/document our entities, it would be better to not check for this.
=> [Testing:Developer] Ignore PHPStan generic types error

site/cypress/e2e/Cypress-TAGrading/rubric_grading.spec.js, site/public/js/ta-grading-rubric.js
More partial (?) work for #10973
The promise chain would not be properly returned and therefore `closeAllComponents().then()` would not fire after components were saved. (This is potentially not as much of a problem as it seems since there is a check every 100ms to see if there are requests in progress and navigation would hold off for there to be 0)
All requests must finish before the navigation is started.
Had to change tests to wait for new component to open since it now properly waits for requests to be made
=> [Bugfix:TAGrading] Wait for promise before navigating

site/app/templates/polls/PollForm.twig, site/cypress/e2e/Cypress-Feature/polls.spec.js
Fixes #10941 
Not a Survey UI: 
Survey:
Even if the survey is a poll it displays an option where you can choose if students should be able to see the answer.
If it is a survey poll, it means there is no answer, therefore; that option should be omitted.
=> [Feature:SubminiPolls] Hide "Show Answer" if Poll is a Survey

site/app/templates/submission/homework/LateDayMessage.twig, site/app/views/submission/HomeworkView.php
Closes #10963 
The late day messages currently do not display a link to the "My Late Days / Extensions" page and says "You have 1 remaining late day for this assignment" instead of for future assignments.
The code fixes the above behavior:
In the image above, the instructor makes a gradeable that has a limit of 3 late days allowed. The student uses one late day, and the code now displays that the student has two more late days remaining for that same assignment. Also, it displays a link at the bottom to the 'My Late Days / Extensions' page.
To test, make or go to a late gradeable, and check if the above changes have been made correctly.
=> [Bugfix:Submission] Fixing Buggy Late Day Message Text

site/app/templates/polls/PollForm.twig, site/app/views/PollView.php
Fixes #10942 
Before:
After:
No shortcut button that would help quickly assign the date as today or tomorrow.
I added a today and tomorrow button to assign the poll release date to today or tomorrow quickly.
=> [Feature:SubminiPolls] Adding Poll Calendar Selector Shortcut

site/cypress/e2e/Cypress-TAGrading/rubric_grading.spec.js, site/public/templates/grading/GradingComponent.twig
Closes #10972 
Currently, TA's can only see what they checked:
TA's can now see everything that they did or did not check:
To test, make a gradeable or access an already existing one, and, as a grader of that assignment, check if you can see all components, checked or unchecked.
=> [UI/UX:TAGrading] Show Unchecked Blue Marks in Closed View

.github/dependabot.yml
Dependabot only opens five PRs per environment [by default](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit).  We have far more than 5 dependencies which need to be updated every month.
This PR increases the limit to allow all of our dependencies to be updated every month if updates are available.
=> [Bugfix:Developer] Increase max allowable Dependabot PRs

site/public/css/diff-viewer.css
Fixes #10977 
After scrolling horizontally in dark mode, a lot of areas are left as blank.
Now the dark mode color correctly applies to the whole container.
https://github.com/user-attachments/assets/51410f39-bfc6-4d5e-9c3f-bc46bbf569d5
=> [Bugfix:TAGrading] Fix dark mode horizontal scroll

site/cypress/e2e/Cypress-TAGrading/rubric_grading.spec.js, site/public/templates/grading/GradingComponent.twig
Closes #11028 
Currently, TAs are experiencing some confusion with the feature implemented in PR #11010. The confusion mainly lies with clicking components when the entire marks lists show and interface problems.
This PR introduces two separate changes. For one, when a component has no graded marks, it does not show the received-marks-list container at all (as shown below):
Secondly, when a graded component is clicked, it will always open the container regardless of which area the TA/grader clicks. It could be the center, on the check marks, the right/left hand corners, etc.
To test, create or go to an already existing gradeable and open the grading page. Then, verify that the above changes work as intended.
=> [Feature:TAGrading] Resolve Marks Confusion in Closed View

site/composer.json, site/composer.lock
We currently have symfony/polyfill-php80 which is not needed anymore since we are on PHP 8.
Closes https://github.com/Submitty/Submitty/pull/11042 since no need to update it anymore
symfony/polyfill-php80 is now removed from our dependencies. It is still installed due to being dependencies of our dependencies but that will eventually go away once we upgrade those dependencies. So no reason to continue to lock it ourselves.
=> [Dependency] Remove symfony polyfill

site/app/libraries/database/DatabaseQueries.php
When deleting a gradeable, three separate database queries are made, with the possibility of the later queries failing after the first query removes the data from the database.
The three queries are part of a transaction, so if one fails they will all be rolled back.
Tests are yet to be added.
=> [Bugfix:InstructorUI] Use transaction while deleting gradeable

site/app/controllers/admin/ReportController.php
According to Barb, 2 courses are reporting errors with generate grade summaries with similar frog robot stack trace:
Error (Code: 0) thrown in /usr/local/submitty/site/app/controllers/admin/ReportController.php (Line 262) by:
$graded_gradeable->setOverriddenGrades($this->all_overrides[$user->getId()][$graded_gradeable->getGradeableId()] ?? null);
Message:
Call to a member function setOverriddenGrades() on null
One course uses grade overrides. The other doesn't seem to have any data in the grade override table. Both said that grade summaries was working earlier in the term (not sure when it broke or what broke it.
PHP is trying to call the setOverriddenGrades method on a variable that is null rather than an GradedGradeable type object.
I was unable to reproduce this issue locally, but …
=> [Bugfix:InstructorUI] Add Null check / override grades

site/app/templates/polls/ViewPoll.twig, site/cypress/e2e/Cypress-Feature/polls.spec.js
Fixes #11037 
If the Poll timer didn't work in the student view, the Cypress test wouldn't have found out if there was an accessibility error in the student access view poll but would have caught the mistake if it messed up the instructor access page.
There are valid checks for both student and instructor to ensure it catches any issues with the poll timer.
=> [Bugfix:SubminiPolls] Poll Timer Cypress Student View

migration/migrator/migrations/course/20241108140232_fix_partially_deleted_gradeables.py
Broken gradeables can exist that will cause generating grade summaries to fail and cause certain other action (eg. submitting to them) to fail as well.
Fixes #11130 
This adds a migration that restores the gradeable_anon table.
Tested by deleting course and noticing crashes, running migration causes crashes to no longer occur.
=> [Bugfix:InstructorUI] Add migration to fix broken gradeables

site/app/controllers/admin/AdminGradeableController.php
Related to #10937 but doesn't close. 
#10100 added the ability to upload a JSON file to create a gradeable. However the `autograding_config_path` config variable was forgotten.
This variable has been added and now correctly takes the autograding_config_path variable from the JSON file.
=> [Bugfix:InstructorUI] Add missing config option to upload

site/app/controllers/PollController.php, site/app/repositories/poll/PollRepository.php, site/cypress/e2e/Cypress-Feature/polls.spec.js
Fix #11135 
Polls can be url-hacked per issue #11135. This PR removes the ability to see polls that are not yet visible.
Adds a check that specifies that polls must be visible.
=> [Bugfix:SubminiPolls] Fix url-hack for polls

site/app/libraries/database/DatabaseQueries.php
Closes #11131 
There can be two users trying to insert things into the late day cache at the same time. There will be a race condition, where one user sees the page and the other user sees a frog robot
If we have a conflict, we can essentially ignore the duplicate. Since they are calculating the cache at the exact same time, we don't need to update the one that is already in there, we can just ignore the duplicate one.
To produce the bug on main, the following steps are followed:
1. Find a gradeable that is past due
2. Have two users click the preview grading button
3. See that one of them will have an error
Used a python script to simulate clicking things at the same time, 
```py
import pyautogui
pyautogui.click((170, 900)) # chrome
pyautogui.click((1160, 560)) # focus tab …
```
=> [Bugfix:Submission] Fix Duplicate Keys on Late Day Cache

site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
Currently if a numeric gradeable has 0 items, it throws a lot of json_decode() errors.
Fix #10947 
We can use js to restrict the rubric to not have 0 items
=> [Bugfix:InstructorUI] Fix error: 0 items for Numeric gradeable

site/app/controllers/MiscController.php
Students can manually make requests to view the files from hidden tests using the `downloadTestCaseResult` endpoint.
The `downloadTestCaseResult` will now validate and ensure only users with permission to grade can download hidden test case results.
=> [SECURITY][Bugfix:Submission] Hide hidden tests from students

site/app/libraries/database/DatabaseQueries.php
If a user sends multiple requests to bookmark a specific thread (before the page reloads), the requests after the first will cause a keyerror in the database and throw an exception.
Ignore these duplicate requests; if the row to be inserted is in the database already, do nothing.
You can reproduce the error by commenting out the `window.location.replace` line at forum.js:1883 (function bookmarkThread). Clicking the bookmark button multiple times should cause subsequent clicks to return a frog robot on main, but they should succeed with this change.
=> [Bugfix:Forum] Fix error on duplicate bookmark request

site/app/libraries/NotebookUtils.php
Jupyter notebooks with single-line code boxes generated by some types of notebook editors currently cause frog robot errors.
This PR resolves the issues.
=> [Bugfix:Submission] Fix Jupyter notebooks with single lines

site/public/css/forum.css
Checkbox elements in the discussion forum don't have space in between the checkboxes and their labels.
They should have a little spacing in between now, as shown: 
To test, check to see if any checkbox elements in the forum look weird. The CSS rule modified should only effect checkboxes for involved in the creation of new threads and/or replies (I assume judging by the name ".new-thread-settings-wrapper")
=> [Bugfix:Forum] Space between textbox labels

site/public/css/forum.css
In discussion forum threads, the three dot menu next to a poster's name can appear out of line:
The three dot menu should now stay in line, no matter how scrunched the page is.
To test, go to any forum post and try to see if a user's name, the time they posted, and the three dot menu stay in the same line.
=> [Bugfix:Forum] Three dot menu wraps properly

bin/regrade.py
It's a common practice on CLI to show the recommended/default option as capitalized.
When running the regrade script, one doesn't know what's the default action.
It shows in capital letter that the default will be No.
There's no changes in the functionality, only in how the prompt is shown to the user.
=> [Feature:Autograding] Capitalize default option 

site/app/templates/polls/PollForm.twig
Fixes #11092 
If you enter 3000 seconds, it will convert the time after you make the poll and go to edit it. 
Made an onchange function where after you edit it would automatically do the conversion so you can tell how much time in hours/minutes/seconds the poll will last.
https://github.com/user-attachments/assets/df81ea5f-499e-4a8c-a7d5-22d373adcf11
To test:
See if the backend timer still works as intended and closes after the desired time, check if the UI change makes sense and works as intended.
=> [Feature:SubminiPolls] Polishing Timer Input Interface

site/app/templates/forum/ThreadPostForm.twig
The discussion forum button to upload an attachment is named "Upload Attachment" even though the uploader only accepts images.
Fixes #11170 
The button is now named "Attach Image"
Screenshot after changes:
=> [UI/UX:Forum] Update Upload Attachment button text

.github/workflows/notify_main_fail.yml
https://github.com/Submitty/Submitty/pull/10733 changed the name of our primary CI job, but failed to update the workflow name in our automation which sends failure notifications to Zulip.
This PR updates the workflow names so we continue to get failure notifications.
=> [Bugfix:Developer] Fix CI workflow name in Zulip notifier

site/app/libraries/database/DatabaseQueries.php, site/phpstan-baseline.neon
#11029 rendered a lot of queries in DatabaseQueries.php obsolete, as their usage was replaced by ORM repositories. 
This removes forum-related queries in DatabaseQueries.php that are now obsolete and are no longer referenced in the codebase. No functionality should change.
=> [Refactor:Forum] Remove unused forum queries

site/app/views/forum/ForumThreadView.php
A user's own posts are highlighted as if they're unread.
Removes special handling for a user's own posts. They now display read/unread like any other.
=> [Bugfix:Forum] Fix users' own posts read display

site/app/templates/forum/CreatePost.twig, site/public/css/forum.css
Currently, there is no indicator as to whether the pin or bookmark button in forum posts are clickable.
Both the buttons now move up and glow the color they would become upon clicking when the mouse is hovered over them.
How it looks in dark mode:
https://github.com/user-attachments/assets/09126169-89d5-428b-b88b-04d0aa34092c
How it looks in light mode:
https://github.com/user-attachments/assets/6b3d5b41-1f18-42ce-8dbf-73e296cc3ab8
To test, check the visuals of hovering over both buttons while they're both unselected and selected.
=> [UI/UX:Forum] Bookmark & Pin hover effects

site/app/libraries/database/DatabaseQueries.php
Fix #11234 and Fix #11223.
The old behavior was that every poll response counted as an answer for the student in the activity dashboard. This was added before the multi-select poll option, so for the same poll, the student could have answered it more than one time
This makes sure that we only have unique poll_id's being counted
=> [Bugfix:InstructorUI] Dupe Poll Responses count as one answer

site/app/controllers/GlobalController.php, site/app/views/admin/ReportView.php
The visibility of both the instructor's **Gradebook** and the student's **Rainbow Grades** depends on whether 'Display Rainbow Grades Summary' is toggled on the **Course Settings** page. This prevents instructors from downloading the CSV of grades without displaying Rainbow Grades to all students.
The **Gradebook** is visible to instructors without regard to whether 'Display Rainbow Grades Summary' is toggled.
https://github.com/user-attachments/assets/ed597507-118d-4923-adac-438934244b3c
=> [UI/UX:RainbowGrades] Always enable gradebook for instructors

site/app/controllers/admin/StudentActivityDashboardController.php, site/app/templates/admin/users/StudentActivityDashboard.twig, site/app/views/admin/StudentActivityDashboardView.php, site/cypress/e2e/Cypress-Feature/student_activity_download.spec.js
Looking at the activity link, `#[Route("/courses/{_semester}/{_course}/activity/download", methods: ["GET"])]`, it conflicts with another link that was added in #10188,
`#[Route("/courses/{_semester}/{_course}/{gradeable_id}/download", methods: ["GET"])]`.
Change the route to download_activity, and change the download link to download_activity.
Tested student activity, verifies that it downloads a CSV
Tested downloading JSON on the gradeable, verifies that it downloads the gradeable JSON
=> [Bugfix:InstructorUI] Fix Downloading Activity Link

site/public/js/ta-grading.js
I noticed that everytime a TA grades something, there are multiple console.log statements that are being logged in console, all of which were debug logging statements
removed the console.log statements that serves no purpose
=> [Bugfix:TAGrading] Remove Debug logging statements

site/app/templates/polls/ViewPoll.twig
Closes #11256  
If the x-labels of a Histogram contain strings of numbers, the quotes in the strings are being represented as `&quot;` instead of the expected `"` format.
This issue arises due to automatic escaping, which converts quotes to their HTML entity representation.
The x-labels of the Histogram now correctly display strings of numbers with quotes represented as `"` (double quotes)
instead of `&quot;`.
=> [Bugfix:SubminiPolls] Prevent Quote Escaping in Histogram

site/cypress/e2e/Cypress-TAGrading/rubric_editing.spec.js
During the creation of #11189, it was merged before the tests were finished (#11309). This means that currently on main the tests are failing and a proper fix will potentially take time to implement.
This is a stopgap measure, commenting out the failing parts of the tests with hope to fix them properly in the future.
=> [Testing:TAGrading] Temporarily disable failing tests

site/app/controllers/forum/ForumController.php
Fixes #11316. Requesting a deleted/invalid thread returns a JSON response.
It now redirects to the main forum page and adds an error message.
=> [Bugfix:Forum] Redirect with error for invalid thread

site/app/repositories/forum/ThreadRepository.php
Fixes #11321. sorting forum posts by 'Alpha by registration' doesn't work on production due to empty strings instead of nulls in database.
Alpha by registration sorting now works as it checks for empty strings as well as nulls.
=> [Bugfix:Forum] Fix sorting alpha by registration

site/phpunit.xml
* [N/A] Documentation has been updated/added if relevant
* [N/A] Screenshots are attached to Github PR if visual/UI changes were made
The current phpunit config (`site/phpunit.xml`) was using a deprecated schma
Updates the schema via running the migrate command : `vendor/bin/phpunit --migrate-configuration`
no
Ran unit tests locally after new schema
=> [Testing:System] Migrate phpunit config

site/app/controllers/DockerInterfaceController.php
Removing an image from the below `config`
```
{
"default": [
"grycap/cowsay:latest"
],
"cpp": [
"grycap/cowsay:latest"
],
"et-cetera": [
"grycap/cowsay:latest"
],
"python": [
"ubuntu/squid:latest",
"ubuntu/squid:edge"
]
}
```
results in
```
{
"default": [
"grycap\/cowsay:latest"
],
"cpp": [
"grycap\/cowsay:latest"
],
"et-cetera": [
"grycap\/cowsay:latest"
],
"python": [
"ubuntu\/squid:latest"
]
}
```
and further removing also results in
**array based json indexing**
```
{
"default": [
"grycap\/cowsay:latest"
],
"cpp": [
"grycap\/cowsay:latest",
"ubuntu\/squid:edge"
],
"et-cetera": [
"grycap\/cowsay:latest"
],
"python": {
"1": "ubuntu\/squid:edge"
}
```
This PR fixes both the above mentioned issues and Fixes #11308
- Fixes the encode and write to file process
- Fixes the repercussion of …
=> [Bugfix:Autograding] config file for remove docker

site/phpstan-baseline.neon, site/phpstan.neon
PHPStan trusts PHPDoc comments by default.  While this can be good if done carefully, the PHPDoc types in the Submitty codebase are not sufficiently thorough to take advantage of this.  Instead, our incorrect annotations can cause PHPStan to come to incorrect conclusions about the type constraints present.
This PR disables PHPStan's `treatPhpDocTypesAsCertain` rule, causing it to rely solely on types which are guaranteed to be correct based on the language itself.
=> [Refactor:Developer] PHPStan: ignore PHPDoc types

bin/set_allowed_mins.py
Fixes #10542. The issue will be outlined in the steps below.
1. Create a new gradeable
2.  In SQLToolbox, run this query, `select g_id, g_allowed_minutes from gradeable;`
3. Observe that `allowed_minutes` is set to `null`, which is correct
4.  Set autograding path to `/usr/local/submitty/more_autograding_examples/notebook_time_limit/config` 
5. run this query again and observe that `allowed_minutes` is set to `10`, which is correct (you can look at the config to see `allowed_minutes` is 10.
6. Change the config to something different, I chose upload but you can use any config, the one from the issue shows the point. Might need to wait a little bit for new config to build.
7. Rerun the query, notice the `allowed_minutes` is still set to `10`, which is incorrect now that we have a new …
=> [Bugfix:InstructorUI] Correctly set allowed minutes on config

site/public/js/simple-grading.js
Fixes #11269 
This PR Resolved Validation issue when maxClamp is zero .
Updated the condition to explicitly check for null to handle 0 correctly.
=> [Bugfix:TAGrading] Checkpoint validation when max is 0

site/app/models/RainbowCustomizationJSON.php, site/public/js/rainbow-customization.js
Login to Instructor, then navigate to _Grades Configuration_. Under **Display**, toggle **section**, then scroll down to **Section Labels**.
After clicking out of a label that has been left empty, an alert pops up immediately. Instructors have to close this alert before they proceed, which leads to bad behavior while the instructor tries to edit the section labels.
Any sections that are left without labels will be given their default values.
=> [Bugfix:RainbowGrades] Remove alert when section label blank

site/app/controllers/forum/ForumController.php, site/public/js/forum.js
When a user is on the same thread as another connected to the same WebSocket, after one of the users sends various new posts to the thread, once the other tries to click the thread on the left-hand thread list, an error is alerted with no further updates. 
I also realized the incorrect `reply_level` for new posts is being sent over the WebSocket, leading to an invalid tree structure and/or rendering errors for further modification of posts. The following displays the right-hand user receiving the invalid ordering from the WebSocket.
No alert is shown for the potential network issue caused by the WebSocket updates interfering with the AJAX request cycle. Ordering posts from the WebSocket matches the expected output on both sides.
Fixes #10933
=> [Bugfix:Forum] Forum Network and Reply Level Issues

site/app/controllers/student/SubmissionController.php
Graders, aka limited access graders, are not able to submit during beta. I believe that they should, since they can see the gradeable when it is in the "TA Beta".
Graders can submit
You can log in as grader and that would be a limited access grader.
Many student mentors complained about this, so we should make this more consistent.
=> [Bugfix:Submission] Grader submission during beta

site/app/libraries/database/DatabaseQueries.php
Currently if a self registration course has the same ID as course the user has previously taken, it will not show up as a possible course. 
Fixes #11325
Now self registration courses are selected based on course-id and term-id. 
When testing this, I realized that if you create a course with the create_course.sh script, and specify it to be self_registration, it joins with the null section as the default section, and an instructor has to go in and add a registration section, and specify it for the self_registration default section.
=> [Bugfix:InstructorUI] self-registration & reused course codes

site/app/templates/admin/RainbowCustomization.twig, site/public/css/rainbow-customization.css
Fixes issue [#11362](https://github.com/Submitty/Submitty/issues/11362)
Sidebar looks like this:
Sidebar should now look like this:
When testing, make sure it does not wrongfully change any other exclamation triangle icons in Grades Configuration.
=> [Bugfix:InstructorUI] Show Plagiarism Detection sidebar icon

site/app/templates/admin/RainbowCustomization.twig
Category/Gradeable Configuration wraps around the assigned buckets list:
Category/Gradeable Configuration is always below the assigned buckets list and available buckets:
Fixes issue #11369.
When testing, add different number of buckets between assigned and available. See instructions in linked issue.
=> [Bugfix:InstructorUI] Fix Gradeable Configuration format

site/public/css/bootstrap.css, site/public/css/forum.css
Category labels for the discussion forum thread list that are too long in terms of text for small viewports end up wrapping onto the next line, where the expected behavior is for each box to correspond to one category, which is displayed via the category, `long label to display`, below.
Longer labels remain in a single box, where if the container is too long for a small viewport, the user may scroll horizontally to view the thread content.
Fixes #10874
=> [UI/UX:Forum] Responsive Category Labels

site/public/css/electronic.css
fixes issue #11374
In the TA grading screen for a notebook gradeable, the selected radio button is hard to see due to low contrast in dark mode. This happens because the variable is overridden in dark mode, changing it to a lighter shade of gray.
Selected Radio Button has no contrast in dark mode.
**Light Mode:**
**Dark Mode:**
Selected Radio button now uses a variable that is visible in both light and dark mode.
**Light Mode:**
**Dark Mode:**
=> [UI/UX:TAGrading] Fixed Radio Button Contrast in Dark Mode

site/public/css/admin-gradeable.css
fixes issue #11386 
In the TA grading screen for a notebook gradeable, the contrast between the check and the box is low. This happens because the variable for the background is overridden in dark mode, changing it to a lighter shade of gray while the check remains white.
Checked box has low contrast in dark mode.
**Light Mode:**
**Dark Mode:**
I couldn't find any variables that would work well for both light and dark mode, so I added a dark mode version of the current css with a different variable.
**Light Mode:**
**Dark Mode:**
=> [UI/UX:TAGrading] Fixed Checkbox Contrast in Dark Mode

site/app/controllers/MiscController.php
Limited access grader sections are not properly checked when downloading submissions.
Limited access grader sections are properly checked when downloading submissions.
=> [Bugfix:TAGrading] Improve access control for downloads

site/public/css/colors.css
In colors.css, there were 14 colors not being used anywhere in the project. I deleted them and verified that Submitty's UI in light mode and dark mode remained unchanged.
=> [Refactor:System] Remove Unused Colors from colors.css

migration/migrator/data/submitty_db.sql, migration/migrator/migrations/master/20250121144600_make_empty_preferred_names_null.py, site/app/models/User.php, site/app/views/UserProfileView.php, site/phpstan-baseline.neon
Preferred names can both be empty strings or null to indicate the user does not have a desired preferred name
All existing empty preferred names will be set to null and constraints are added to the database to ensure that empty preferred names cannot be added to the database in the future.
This is part of a series of changes starting with https://github.com/Submitty/SysadminTools/pull/37 and will be followed up by more PRs to remove the handling of empty strings in the database to be able to further simplify the code to not have to handle 2 cases that both mean the user does not have a preferred name.
=> [Refactor:System] Set empty preferred names to NULL

site/app/controllers/grading/SimpleGraderController.php
We have a problem with checkpoint (e.g., cs1 & ds lab) gradeables. I've tested with both Mac Chrome and Mac Firefox.
When I click on 2 checkpoints for the same person, it displays both checkpoints, but when I reload the page, only the 2nd checkpoint is stored.
All checkpoints will persist the state that they should be in after reloading.
Issues caused by #11360
[Zulip discussion about this](https://submitty.zulipchat.com/#narrow/channel/409312-RPI-Developers/topic/URGENT.20LAB.20GRADABLE.20BUGFIX.20NEEDED)
=> [Bugfix:TAGrading] Set only updated scores in components

site/app/controllers/admin/UsersController.php
An instructor updating anything about a user (that has an empty preferred name) will cause a frog robot due to the new database constraints added in #11359. 
Preferred names are properly only passed when they are set and non empty when an instructor is updating a student.
=> [Bugfix:InstructorUI] Update users without preferred name 

.github/workflows/vagrant_up.yaml
When vagrant is installed in the workflow, the following is outputted:
```
Run brew install vagrant
Error: Failed to load formula: vagrant
hashicorp/tap/vagrant: formula requires at least a URL
Warning: Treating vagrant as a cask.
==> Downloading https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3_darwin_amd64.dmg
==> Installing Cask vagrant
==> Running installer for vagrant with sudo; the password may be necessary.
installer: Package name is Vagrant
installer: Installing at base path /
installer: The install was successful.
🍺  vagrant was successfully installed!
```
where both the error and warning are logged to the summary of the image.
That we install vagrant per the [docs](https://formulae.brew.sh/cask/vagrant), using the `--cask` flag, which should avoid the error/warning.
=> [Testing:Developer] Fix warning on installing vagrant

site/app/controllers/forum/ForumController.php, site/app/libraries/database/DatabaseQueries.php, site/cypress/e2e/Cypress-Feature/forums.spec.js
The current query to get all upduck is wrong. This could be simply observed by logging in as instructor and upducking a post not by instructor. This would cause the upduck count not go up
http://localhost:1511/courses/s25/sample/forum/stats
This is 1/2 of fixing the forums, the other one is below:
#11441 
Fixes the query and the related cypress tests
This is the first part of many changes to the forums and upduck tests.
=> [Bugfix:Forum] Fix Upduck Count Stat

site/app/libraries/FileUtils.php, site/tests/app/libraries/FileUtilsTester.php
Fixes #11380
When a file is uploaded to php with a size >= `upload_max_filesize`, the `$_FILES` array still exists, however most of the data is junk. As a result the `$_FILES[file_index]['tmp_name']` which normally points to the tmp area the uploaded file lives in is not guaranteed to exist, which caused the file mine check to fail because it was empty.
see steps to reproduce: https://github.com/Submitty/Submitty/issues/11380#issuecomment-2641893026
The validation logic will now check if the error flag is set and exit immediately if it is
=> [Bugfix:InstructorUI] check uploaded files near size limits

site/public/js/ta-grading-rubric.js
When clicking to discard changes the component will be closed and the changes will not be saved, but they are still reflected locally until refresh.
When discard is clicked the local data is also reset to show the component in the state it was before the grader opened it.
Fixes #10717
=> [Bugfix:TAGrading] Fully discard changes on click

site/public/js/ta-grading-rubric.js
Attempting to grade a gradeable with at least one peer component as part of the course staff will cause an alert and an error along with the peer panel failing to render.
The errors no longer occur and the peer panel works as intended.
This was likely broken back in #11008, hopefully this is one of the last required fixes.
=> [Bugfix:TAGrading] Fix peer panel

.github/actions/e2e-Setup-Composite/action.yml
Currently multiple CI are failing ([test1](https://github.com/Submitty/Submitty/actions/runs/13535792102/job/37827165110), [test2](https://github.com/Submitty/Submitty/actions/runs/13535563458/job/37826507269), [test3](https://github.com/Submitty/Submitty/actions/runs/13481272252/job/37814494803)). This is likely due to a recent update to the setuptools from v75.8.0 to v75.8.1 ([changes](https://github.com/pypa/setuptools/compare/v75.8.0...v75.8.1?diff=unified&w=)).
The issue is fixed by updating `packaging` when installing python dependencies (both locally and globally)
=> [Dependency] Fix CI failures due to python dependencies

.setup/bin/sample_courses/models/course/course_create.py, site/app/controllers/SelfRejoinController.php, site/app/controllers/course/CourseRegistrationController.php, site/app/templates/admin/Configuration.twig, site/app/templates/error/NoAccessCourse.twig, site/app/views/ErrorView.php, site/app/views/admin/ConfigurationView.php
The sample course 'testing' currently is supposed to allow for self registration, however in doing so it does not set the default section id, and breaks the functionality somewhat, as users who register are put in the null section. 
Related to https://github.com/Submitty/Submitty/issues/11471. This does not fix the issue as described, users who are set to the null section will not be able to register, but it gives the users a warning message, and displays a different default section to instructors. 
The sample course scripts now accurately set the default section, and if an instructor uses the create_course.sh script, and does not set a default section, it will now display a different message to the students, and not allow them to register. Also, the place to set the default section now …
=> [Bugfix:InstructorUI] Fix When Default Section is Null

site/app/controllers/forum/ForumController.php, site/app/libraries/database/DatabaseQueries.php, site/app/templates/forum/ThreadPostForm.twig, site/cypress/e2e/Cypress-Feature/forums.spec.js
By default, discussion forum threads have a NULL thread lock date, and any user can post to the thread.
If the instructor specifies a thread lock date, students should not be able to post to the thread after that date.
However, it seems that if the thread lock date is non-NULL, students are blocked from posting to the thread. Even if the date is far in the future.
Also, it's not possible to edit a thread and remove a thread lock date -- e.g., set it back to NULL. You can change the thread lock date to another date.
Thread Lock Date Validation: If the thread lock date is set to a valid future date, students should are able to post before that date
Thread Lock Date Removal: Now can edit a thread and set the thread lock date back to NULL should be restored.
Fixes #11499
=> [Bugfix:Forum] Fix the Thread Lock Date error

migration/migrator/migrations/course/20240816095713_late_days_constraint.py
close #11536 Cannot run down migration for late day constraint because of missing down migration
drop the constraint during down migration
=> [Bugfix:Developer] Add Missing Down Migration to Late Days

site/app/controllers/forum/ForumController.php, site/app/templates/forum/StatPage.twig, site/app/views/forum/ForumThreadView.php
Currently, when a student upducks a post but have no posts themselves, the stats page crashes.
Temporarily set some fields and others to null, this entire page needs an overhaul as explain in the todo comment
=> [Bugfix:InstructorUI] Fix for stats page from robot

site/app/templates/forum/ShowCategories.twig, site/public/css/forum.css, site/public/js/forum.js
Currently, there is no dark mode implementation for customizing course categories in the discussion forum, causing it to stick out and making the delete icon invisible:
Implemented dark mode for customizing course categories:
Notice that the text color no longer matches the category color. This is intentional as the contrast against the background would only be good in light mode.
=> [UI/UX:InstructorUI] Dark Mode for Customizing Categories

site/app/controllers/admin/AdminGradeableController.php, site/app/templates/Navigation.twig, site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig, site/app/views/NavigationView.php, site/public/css/admin-gradeable.css
Many instructors have reported confusion regarding checkpoints and numeric gradables not being available to students. The current message on the dates page lacks clarity and visibility. A clearer message should be displayed for instructors who have yet to enable Rainbows Grades summaries.
A strong warning message displays for instructors who have yet to configure Rainbow Grade's summaries on the gradeables list and gradable dates configuration page, as shown below.
=> [UI/UX:InstructorUI] Released Grades Warning

site/app/libraries/socket/Server.php
Client-side broadcasting of WebSocket messages to others connected to the same page is allowed on the backend server, which is a security risk.
Any client-side attempts to broadcast a message to others through the backend WebSocket server will be ignored. An additional check for missing pages on a broadcast request has also been implemented to address the error below that I found within the logs (`sudo journalctl -u submitty_websocket_server -f`). All standard WebSocket behaviors (discussion forum, simple grading, etc.) should remain stable.
```bash
PHP Warning:  Undefined array key "s25-sample-discussion_forum" in /usr/local/submitty/site/app/libraries/socket/Server.php on line 131
```
This addresses the final issue on #10296. The updates will require the WebSocket server to restart with …
=> [Bugfix:System] Disable Client-Side WebSocket Broadcast

site/app/controllers/forum/ForumController.php, site/app/templates/forum/GeneratePostList.twig, site/app/templates/forum/ShowForumThreads.twig, site/app/views/forum/ForumThreadView.php, site/public/js/forum.js
If two people connect to the same thread page, and one toggles their like status, both pages will display the same status (like/unliked), regardless of the user's prior state.
The upduck status (like/unliked) will only update for the person submitting the request on the front end, but all users will still see other respective updates (like count, instructor-like status, etc.)
Fixes #11371
=> [Bugfix:Forum] Upduck Web Socket Bug Fix

site/app/templates/forum/ThreadPostForm.twig, site/public/css/forum.css, site/public/js/forum.js
Current UI for pinning thread / notifying students on creation is slightly confusing
Changed checkbox logic to be more clear (pin thread is independent, but notify students needs pin thread to be selected)
Fixed styling for the expiration date div so it looks nicer and doesn't shift elements slightly
Fixed a bug where after reloading, the pin thread box could be unchecked while leaving the notify box on
Closes #11169 
Expiration date div has been renamed from "expiration" to "pin-expiration-date"
Tested on chrome browser
=> [UI/UX:Forum] Fix forum pin thread

site/app/templates/admin/RainbowCustomization.twig, site/public/js/rainbow-customization.js
Placeholders for Per Gradeable Percents are assigned based on the number of items that are currently in the bucket.
Placeholders for Per Gradeable Percents are assigned based on the number of items that are expected.
https://github.com/user-attachments/assets/d5024686-9fad-4efa-9d74-864e71c7b765
=> [Bugfix:RainbowGrades] Set placeholders by expected items

site/app/libraries/socket/Server.php, site/phpstan-baseline.neon
As new users connect to the websocket server, every new page that gets connected to will be stored in memory until the server gets restarted which over time increases the memory usage of the websocket server process. 
When the last user of a page disconnects the page will also be removed from the clients array.
=> [Refactor:System] Fix websocket memory leak

.setup/install_system.sh, grading/Sample_CMakeLists.txt
Currently the version of llvm that Submitty uses requires an older version of cmake than what is supplied by apt. The version of llvm was from Jan. 2018 (7.1.0) and there were no breaking changes until a version released in Feb. 2022 (13.0.1), so that is what was chosen here.  Sample_CMakeLists.txt also had to updated to move `cmake_minimum_required ` from 2.8 to 3.5 so that the newer version of cmake would accept it.
- It is probably going to be a breaking change when cmake no longer supports 3.13.4, many of the directories will have to be moved around to support the new llvm directory structure.
- This PR will not pass the ansible install test since until #11585 is merged ansible will use the version of llvm specified by main.
=> [Dependency] Upgrade Clang source to version 15.0.7

site/app/libraries/socket/Server.php, site/phpstan-baseline.neon
There is no change in behavior with this PR, but a private member property was removed since it is no longer used. The original purpose was for preventing rebroadcasting discussion forum events to the user that caused them, but now that client-side websocket broadcast is disabled it has no purpose.
=> [Refactor:System] Remove unused user connection management

sbin/submitty_daemon_jobs/submitty_jobs/bulk_qr_split.py, sbin/submitty_daemon_jobs/submitty_jobs/bulk_upload_split.py, sbin/submitty_daemon_jobs/submitty_jobs/generate_pdf_images.py, sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
Pdf splitting and image generation is done in a single job
Pdf splitting now calls the GeneratePdfImages job to turn the split pdf into images.
This will be part of a series of PRs to eventually support redaction of tests for limited access graders, the job needs to be split to be able to rerun the image generation if the redaction list changes
=> [Refactor:Submission] Split pdf image generation into new job

site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig
The released checkpoint and numeric gradeables message reminding instructors that scores are strictly available on Rainbow Grades is displayed on all assignments, which can be confusing.
The released checkpoint and numeric gradeables message are now strictly displayed for those specific assignment types, as shown below.
Checkpoint/numeric gradeables:
All other gradeables:
=> [UI/UX:InstructorUI] Hide Numeric/Checkpoint Message

site/app/templates/submission/grade_inquiry/Discussion.twig, site/app/templates/submission/homework/SubmitBox.twig, site/app/views/submission/HomeworkView.php, site/public/js/grade-inquiry.js
When a user types into the text area within the grade inquiry section, the key is based on a component with the ID tied to the current gradable, which doesn't exist. Thus, the key is the same for all pages.
All draft content keys related to grade inquiry text areas are tied to the specific course and are gradable. This local storage instance is also cleared now for successful submissions.
Testing requires a gradable to have an open grade inquiry window, and any unsaved changes should not propagate to other locations now.
Fixes #11230
=> [Bugfix:Submission] Prevent Grade Inquiry Text Across Pages

site/app/libraries/Output.php, site/app/templates/misc/Markdown.twig, site/app/templates/notebook/Notebook.twig, site/composer.json, site/composer.lock
The previous Markdown handling relied on https://github.com/aptoma/twig-markdown extension, which is no longer maintained.
Updated to use https://github.com/twigphp/markdown-extra for improved Markdown processing in output and templates.
No breaking changes introduced.
=> [Dependency] Switch to maintained markdown provider

site/public/css/server.css, site/public/js/forum.js
Currently there is no dark mode for cat-buttons in places such as create thread.
Modify js to apply inline css for dark mode as well.
https://github.com/user-attachments/assets/b69ff6ec-18f7-4263-9b4a-558b1a660f6f
=> [UI/UX:Forum] Dark mode for cat-buttons

site/app/templates/submission/homework/SubmitBox.twig
Inside of the submit box, if the instructor does not select anything it automatically goes to a normal instructor submission. However, this button is not checked
button is checked
=> [UI/UX:Submission] Default Instructor Submission Type

Vagrantfile
Currently, Vagrantfile mounts the following optional companion repositories to a shared directory in the VM: AnalysisTools, AnalysisToolsTS, Lichen, RainbowGrades, Tutorial, CrashCourseCPPSyntax, LichenTestData, DockerImages, DockerImagesRPI.
The file mounts an additional companion repository, IntroQuantumComputing, if found in the same directory.
I reloaded the VM to apply the changes in the Vagrantfile and changed a folder name locally to ensure the changes were applied in the mirrored directory.
=> [Feature:System] Add IntroQuantumComputing to Vagrantfile

site/app/models/gradeable/Gradeable.php, site/app/templates/navigation/DeleteGradeableForm.twig, site/cypress/e2e/Cypress-Gradeable/deletion.spec.js
There is no test coverage for any of the gradeable deletion code.
Gradeable deletion has tests for both deleting successfully and making sure gradeables that should not be able to be deleted cannot be deleted. 
related PRs:
remove delete gradeable https://github.com/Submitty/Submitty/pull/11124/
add transaction for delete gradeable https://github.com/Submitty/Submitty/pull/11125/
migration to repair broken gradeables https://github.com/Submitty/Submitty/pull/11133/
fix delete gradeable https://github.com/Submitty/Submitty/pull/11133/
open issue to add even more tests: 
https://github.com/Submitty/Submitty/issues/11625
**This also re-enables greadeable deletion** (it needs to otherwise it is impossible to test)
=> [Testing:InstructorUI] Add tests for deleting gradeables

site/.performance_warning_ignore.json, site/cypress/e2e/Cypress-Feature/upduck_forums.spec.js
Upducks are currently failing as the request is not fully sent
Adds a timeout for the request
=> [Testing:Forum] Fix Upduck Cypress Inconsistency

.setup/install_submitty/install_site.sh
Vite has updated the esbuild binary once again (first one was #11241) and now uses it from `node_modules/esbuild/bin/esbuild` rather than `node_modules/vite/node_modules/esbuild/bin/esbuild` and therefore every run of install_site produces the error `chmod: cannot access '/usr/local/submitty/site/node_modules/vite/node_modules/esbuild/bin/esbuild': No such file or directory`
Only the correct esbuild binary is chmod-ed
=> [Bugfix:Developer] Update install_site for vite

site/public/css/email-status.css
Addresses a UI bug from bumping the Stylelint version.
When resolving Stylelint errors, I changed the styling of the buttons on the email status page from inline-flexbox (which doesn't exist), to inline-flex. This caused the buttons to no longer be right-aligned:
By removing the rule, it is now fixed:
=> [Bugfix:InstructorUI] Fixed Email Status Button Alignment

autograder/autograder/execution_environments/container_network.py, site/app/templates/submission/homework/AutogradingResultsBox.twig
Fixes #11645
Currently, if there is a required docker image for an gradeable is missing, autograding submissions notify both students and instructors in the autograding results box. However, if multiple images are required and are missing, the subsequent errors overwrite the details of the previous error. 
The subsequent errors are appended to a list of errors and looped through to display each image error.
Current behavior
New behavior
=> [Bugfix:Autograding] Multiple docker debugging errors

site/app/templates/NotificationSettings.twig, site/public/css/notifications.css
The column headers on the notification settings page are misaligned:
- This is not a breaking change
- Had to include an instance of !important due to a style overriding the header spacing in server.css. Fixing the chain of specificity is beyond the scope of this PR.
=> [Bugfix:InstructorUI] Aligned Notification Headers

.setup/data/users/instructor.yml
Tutorial was not added to instructor.yml files
Tutorial is now added back to instructor
=> [Bugfix:Developer] Add Instructor back to tutorial

site/app/templates/autograding/AutoResults.twig, site/app/templates/submission/homework/AutogradingResultsBox.twig, site/app/views/AutoGradingView.php, site/app/views/submission/HomeworkView.php
Currently, having a missing docker image error only displays this error for students on the homework submission side and does not display on the page for TAGrading.
I reverted the changes to display the error in AutogradingResultsBox.twig and only added it to AutoResults.twig. The docker error now successfully shows for both TA grading and for student submissions.
Before:
After:
To test, I used the Docker Choice of Language gradeable in the development course. I removed necessary docker images and submitted to the gradeable.
=> [Bugfix:Autograding] Extend docker error to TAGrading

.setup/install_system.sh
Vagrant up fails because a PR added a new parameter to CONFIGURE_SUBMITTY.py, but didn't add the parameter to all the required install scripts. 
[Vagrant up](https://github.com/Submitty/Submitty/actions/runs/15522688862/job/43698042151) passes.
=> [Bugfix:Developer] Fix Dev Install Script

site/app/models/Email.php, site/tests/app/models/EmailTester.php
fixes #11731
When Submitty sends an email, it assumes a course is defined and associated with the sender. If no course is defined, an extra space appears in the email subject line where the course label would normally go:
```
reply-to: do-not-reply@vagrant
Subject: [Submitty ]: Submitty Email Verification
```
Email header logic now checks if the course is defined to prevent the unnecessary space:
```
reply-to: do-not-reply@vagrant
Subject: [Submitty]: Submitty Email Verification
```
=> [Bugfix:System] Handle Undefined Course in Email Subject

autograder/autograder/execution_environments/container_network.py
Fixes #11725
Currently, the value for the machine incorrectly displays the container as the machine. We want users/instructors to know which exact machine is missing the images.
Before
After
Submit example submissions to a course where you don't have a docker image for. For example, Docker Choice Of Language uses rust:latest, clang:latest, gcc:latest.
Cypress tests have not been created yet for autograding, it is in progress.
=> [Bugfix:InstructorUI] Correct machine on docker error

site/app/controllers/MiscController.php
Currently when a TA attempts to view a pdf from the results or results_public folder they see an error and have to download it instead.
Fixes #11750
PDFs in all folders are viewable
- Use a gradeable config that will place a pdf in results or results_public
- Observe on main that the pdf is downloadable but not viewable.
- Switch to PR
- Observe that it is viewable now
=> [Bugfix:TAGrading] Update pdf viewing permissions

site/app/models/Config.php, site/app/models/DateTimeFormat.php, site/app/templates/LateDaysTablePlugin.twig, site/app/templates/superuser/Gradeables.twig, site/cypress/e2e/Cypress-Feature/grade_inquiries.spec.js, site/cypress/e2e/Cypress-Feature/late_days_allowed.spec.js, site/public/js/calendar.js, site/tests/app/models/NotificationTester.php, site/tests/app/models/SimpleLateUserTester.php
fixes #11104 supersedes #11182
Dates are inconsistently formatted throughout the site.
Added ISO formatting (the global standard) for all dates.
**Before:**
**After:**
Navigate around the site, ensuring all pages and features that have dates/times still properly load, and now have consistent formatting.
New date formatting may interfere with Cypress, will update the PR to resolve if necessary.
=> [Refactor:System] Change to Y-M-D Date Formatting

.setup/ansible/playbooks/submitty_course_creation.yml
Currently in the Ansible playbook for course creation, there are two tasks with names "Add instructor". This change is important because our CI test for Ansible Lint fails as a result of the task names not being unique.
The tasks now have unique names and CI Ansible Lint should pass.
You can test the bug by viewing CI tests in previous merged PRs.
=> [Bugfix:System] Duplicate task name in course creation

.vscode/settings.json, site/public/sw.js
Interminitenly both locally for some developers and on ci Cypress would give the error [`Cannot read properties of undefined (reading 'claim')`](https://github.com/Submitty/Submitty/actions/runs/15688170023/job/44196516776?pr=11675#step:8:281). This seems to be a known bug online that can occur when a service worker is registered but does not listen to the activate event.
The service worker now waits for the activate event as well as its existing behavior.
=> [Bugfix:Developer] Fix cypress service worker flake

site/app/controllers/admin/AdminGradeableController.php, site/app/templates/admin/admin_gradeable/rubric/ElectronicFileRubric.twig, site/public/js/simple-grading.js, site/public/templates/grading/Gradeable.twig, site/ts/ta-grading.ts
The edit gradable page displays numerous console errors during the initial load and when the window is resized. While functionality remains mostly intact, some users, particularly on Chrome, have reported issues with broken sidebar rendering, which is caused by TA grading parameters being applied to this specific page as well.
The following errors are the ones I was able to capture and address within this patch, which display occasionally on the main branch and shouldn't be shown anymore when the editable page is initially loaded or resized. Many type errors and deprecated warnings have been addressed, such as moving away from `DOMSubtreeModified` and `window.onunload`. Additionally, the full-screen mode should no longer be applied within this page.
```
[Error]
[Deprecation] Listener …
```
=> [Bugfix:InstructorUI] Fix Edit Gradeable Page Errors

site/app/templates/admin/Docker.twig, site/public/js/docker_interface.js
Sorting columns by `Image Name` in the DockerUI does not have any tiebreakers when the names are the same. Additionally, the ordering of the columns is not intuitive. This affect the user experience, especially when there are many images present on the page.
Sorting columns by `Image Name` now uses the `Tag` column for tiebreakers. The `Tag` column is always sorted in descending order, so that the latest version is at the top.
Column Ordering Refactor:
**Before:**  Image Name | Owner | Id | Size | Tag | Created | Alias | Capabilities | Remove
**After:** Image Name | Tag | Alias | Id | Size | Capabilities | Owner | Remove
Add duplicate images with different tag names to the Docker UI, ensure sorting uses tags as the tiebreaker.
This is not a breaking change
_Both images here use the same …
=> [Refactor:InstructorUI] Improve Docker Sorting & Column Order

site/app/models/gradeable/Component.php
Due to setting `Component::modified` inside:
https://github.com/Submitty/Submitty/blob/bcdd81478559d0c66552e2d494e91878b5c8a79a/site/app/models/AbstractModel.php#L131-L207
As we are removing the magic methods we have to make sure that we also set `modified` in all of the setters.
All of the setters that did not update `Component::modified` now do.
There is no way to currently produce incorrect behavior, since all code paths that lead to `saveComponent` either call it without the possibility of the component being edited or they call an existing `Component` setter as well as the new ones so `Component::modified` is already set to true.
=> [Bugfix:TAGrading] Mark component as modified

site/cypress/support/e2e.js
This change is necessary because it logs the reason why we added an uncaught exception handler for the specific error in the code.
There is a comment on the cypress exception handler that highlights the reason for the code.
=> [Documentation:Developer] Mermaid exception handler comments

site/app/controllers/EmailStatusController.php, site/app/repositories/email/EmailRepository.php, site/phpstan-baseline.neon, site/public/js/email-status.js
The email status page only displays the first page, regardless of the currently selected page. I believe this was never caught or documented, as most instructors or administrators would usually visit this page to verify recent, but not old, email details. Fixes #11799.
The email status page now displays the correct page. The error stemmed from the invalid controller logic, where the page was determined by the POST request object, which was empty or undefined, as the pagination request is a GET request. Additionally, the repository code was refactored for clarity measures.
Old (all pages are the same)
New (expected last page)
You can test the expected pages (10 emails or 5000 recipients per page) through the following commands, which are based on emails, not recipient limits. The following …
=> [Bugfix:Notifications] Fix Invalid Email Status Pagination

site/app/templates/grading/simple/Display.twig, site/public/css/simple-grading.css
When an update is received for a simple gradeable with checkpoint components, the 'Show Grader/Date Graded' text content does not display correctly. The text color will match the component background color, but when you refresh the page, the text content is visible. Fixes #11819.
The original background color for the components is applied in the Twig file with a literal background color instead of using the existing CSS color or class, such as `simple-full-credit`. Additionally, the existing CSS class applies to the container color, but not the background color, which causes the existing error. Now, all checkpoint containers will have their respective CSS class applied based on the score to ensure consistency across page load and updates with the correct styling logic.
Before
After
1. Go …
=> [UI/UX:TAGrading] Fix Grader Display for Checkpoint Update

site/ts/ta-grading-rubric.ts
The function to reorder component was not called correctly. This caused the function to not run at all, which instructors are unable to update/reorder component. Once they refresh, the ordering will be the same
Before:
https://github.com/user-attachments/assets/dd97df3d-97fa-42df-a2d5-ba91b52cca16
Instructors will now be reorder components that saves to the database after changes
After:
https://github.com/user-attachments/assets/c337e3f6-80cf-44eb-b1a0-56477ea6d3cc
I believe we have trouble in cypress to drag stuff, so I don't know if the testing can be achieved.
=> [Bugfix:InstructorUI] rubric reorder component function

site/cypress/e2e/Cypress-Feature/registration.spec.js
The registration test fails when within two weeks of the start of a new term (Jan 1, and July 1) because the "recently dropped" course detects the user is in the null section, and so it shows the "recently dropped" course on the course list.
The test has been changed to select the correct buttons to press.
It may be good to refactor the "recently dropped courses" to see if they are self registration, and not show them, as it is kind of redundant, but that is a slightly bigger refactor than this.
=> [Bugfix:Developer] Fix Registration Test

.setup/INSTALL_SUBMITTY_HELPER.sh, .setup/INSTALL_SUBMITTY_HELPER_BIN.sh, .setup/INSTALL_SUBMITTY_HELPER_SITE.sh, .setup/install_submitty/install_site.sh
After the merging of #10645 the install_site script broke due to a config file requirement that is supplied by install_submitty_helper but not by install_site_helper. 
The submitty_install_site script should run without issue on VMs
There isn't testing for submitty_install_site it seems, this is an area which should probably be looked into.
=> [Bugfix:System] Fix install_site Script for Vagrant VMs

site/app/controllers/GlobalController.php, site/app/controllers/admin/UsersController.php, site/app/controllers/student/RainbowGradesController.php, site/app/templates/submission/RainbowGrades.twig, site/app/views/admin/ReportView.php, site/app/views/submission/RainbowGradesView.php, site/cypress/e2e/Cypress-Gradeable/rainbow_grading.spec.js, site/phpstan-baseline.neon, site/public/css/admin-gradeable.css, site/public/css/server.css
1. Refactors viewing students grades to the rainbowgrades controller, instead of the user controller. This mimics late days being in the latecontroller instead of the user controller
2. Added additional types to everything involved, refactoring from `$this->getOutput()->renderOutput()` to `WebResponse`.
3. moved access control from view to controller, in addition to making sure that instructors can see rainbowgrades when it is disabled
This removes all of the phpstan warnings about rainbowGrades
1. viewing student grades from instructor is now in rainbowgrades controller
2. Improve rainbowgrades handling
When viewing rainbow grades for a user, the behavior should not change.
When rainbowgrades summary is disabled but instructors set up rainbowgrades, instructors should be able to see user …
=> [Refactor:RainbowGrades] Improve RainbowGrades handling

.setup/ansible/roles/submitty_course_add_user/tasks/main.yml, .setup/ansible/roles/submitty_course_creation/tasks/main.yml, .setup/ansible/roles/submitty_install/tasks/main.yml, .setup/ansible/roles/submitty_term_creation/tasks/main.yml
This change is necessary because it fixes Ansible linting errors as a result of Ansible Lint reinforcing role prefixes for "global" variables: https://github.com/ansible/ansible-lint/commit/249cd4cc07444f5900ec23e3c16103798edb07af.
Registers now have their respective role prefixes and Ansible Lint tests should pass now.
You can test the bug by viewing CI tests in previous merged PRs.
=> [Bugfix:System] Fix Ansible No Role Prefix

site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig, site/public/js/admin-gradeable-updates.js
In #10325 a helper function was added that reloaded the page immediately when an instructor picked a different autograding configuration, so the gradeable-config editor would show the new files.
However, the AJAX request that actually saves the new `autograding_config_path` is fired from a separate delegated `change` listener. In some browsers (notably Firefox) the instant reload could occur before that request left the page, so the rebuild job wasn’t queued and the editor still showed the old config.
The reload call has been moved inside the existing delegated `change` listener, after the AJAX update returns successfully. Now every browser waits until the payload is sent (and acknowledged) before reloading, guaranteeing the gradeable configuration is updated correctly.
In Firefox and …
=> [Bugfix:InstructorUI] Fixed Config Selector Refresh

site/phpstan-baseline.neon, site/phpstan.neon
https://github.com/Submitty/Submitty/pull/11847#discussion_r2211966348 was not fully addressed. This causes future code not to be checked with useful PHPStan checks.
The ignores were removed and baseline regenerated. As errors are fixed over time, they can be removed from the baseline and any new code will still be enforced.
=> [Bugfix:Developer] Update baseline with removed ignores

.github/actions/e2e-Setup-Composite/action.yml, .github/workflows/ci.yml, .setup/INSTALL_SUBMITTY_HELPER.sh, .setup/install_submitty/get_globals.sh
The change is necessary as every time you want to copy a file, you would have to add it to ci, in addition to adding an rsync to the directory. This refactor aims to combine the two elements by putting it directly into `install_submitty.sh`, which both ci and developers run
Whenever we are in the ci, we should copy the files. whenever we are a developer vm, we should rsync the files.
=> [Refactor:Developer] Refactor Autograding setup scripts

site/ts/resizable-panels.ts, site/ts/ta-grading-panels.ts
You currently cannot resize the panels on firefox. This is because TouchEvent on firefox does not exist on systems that do not have touch, like macs. Therefore, it will throw an error whenever we try to see if it is an instance of TouchEvent.
Instead of explicitly checking for touchevent, we can just check if it has certain properties that we would like to strip out
We do not test firefox
=> [Bugfix:TAGrading] Fix browser specific panel resizing

site/public/js/forum.js
Whenever the sidebar is updated while using the discussion forum, a new onclick handler is added to all posts in the sidebar, causing many requests to be made if many posts are updated before refreshing.
All stale click event handlers are cleared before adding the correct one after the sidebar is updated.
1. View the discussion forum on main
2. Like/unlike a few posts
3. Notice that 1 + likes * 2 requests are made when changing threads
4. Switch to the branch and see that there is only ever one request
=> [Bugfix:Forum] Prevent multiple onclick handlers

site/app/models/gradeable/Gradeable.php
#11702 Magic Methods PR stated that team_lock_date is ?DateTime, which is true, but getting the value actually returns a DateTime, casuing a frog robot crash 
```
Oh no! Something irrecoverable has happened...
app\exceptions\OutputException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/Output.php (Line 412) by:
throw new OutputException("{$e->getMessage()} in {$e->getFile()}:{$e->getLine()}");
Message:
An exception has been thrown during the rendering of a template ("app\models\gradeable\Gradeable::getTeamLockDate(): Return value must be of type DateTime, null returned") in "admin/admin_gradeable/AdminGradeableDates.twig" at line 14. in /usr/local/submitty/site/app/templates/admin/admin_gradeable/AdminGradeableDates.twig:14
Stack Trace:
#0 …
```
=> [Bugfix:InstructorUI] Fix Admin Gradeable's Team Lock Date

.setup/bin/sample_courses/models/course/course_create_gradeables.py
Currently we pass floats to `random.randint` when setting up sample courses, and this currently is supported but will not be when our python version upgrades along with ubuntu 24.04.
Floats are casted to ints before being passed to `random.randint`
Verify that the sample courses are created and function normally.
Almost all of our tests are based on the sample data, so this change is thoroughly covered.
=> [Refactor:System] Fix randint types in sample course data

migration/migrator/data/course_tables.sql, migration/migrator/migrations/course/20250804212849_default_thread_ids_value.py, site/app/models/gradeable/Gradeable.php
From #11702,
On production, we have gradeables that have already been created. When the gradeable gets created, we `json_encode('{}')` as the default value. This means that when it gets inserted into the database, instead of `{}` being inserted, we actually insert `"{}"` instead, which is a string. This means that the new code, which decodes it once, will not work as it will be decoded to `"{}"` instead of `[]`, which throws of frog robot.  
We can either:
1. Decoding it twice would allow for us to get `[]` instead of string `"{}"`.
2. Make a database migration for this situation where we specifically patch this one instance
Make a database migration for this situation where we specifically patch this one instance. I feel like this is better and the other way is a little hacky
Make a …
=> [Bugfix:InstructorUI] Fix decoding of eg_thread_ids

.setup/distro_setup/ubuntu/22.04/setup_distro.sh, migration/migrator/migrations/system/20250807110111_add_venvs.py
As part of the upgrade to ubuntu 24.04, we want to move all of our python dependencies to virtual environments, but currently the `python3-venv` package is not installed so they cannot be created.
This PR installs the python3-venv package so we can manage our venvs. No venvs are created in this PR since the first will likely be the migrator itself.
1. Run `migrator -e system migrate`
2. Verify `python3 -m venv /path/to/venv` creates venv successfully
1. There is no automated testing of this PR, but as venvs are added those will need testing.
=> [Dependency] Add python3-venv installation to setup

site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig, site/public/css/admin-gradeable.css, site/public/js/admin-gradeable-updates.js
The current Submissions/Autograding tab in edit gradeable has a messy UI.
Made many small changes to the page and gradeable config editor to improve UI/UX:
1. Added spacing and improved readability of student permissions at the top.
2. Added spacing and rephrased autograding config selector to be more readable.
3. Swapped notebook builder and config editor so that it is right below the config upload.
4. Made notebook builder buttons the same size and increased their right margins.
**In the gradeable config editor:**
1. Selected file now has a different color so the user knows what is in the editor.
2. Smoothened out the transition between files by matching Code Mirror and underlying textarea styling (before it would shrink to the unstyled textarea which was jarring for the user).
3. Added …
=> [Bugfix:InstructorUI] Improve Autograding Config UI/UX

site/cypress/support/commands.js
DockerUI has been failing rarely now. I cannot debug the issue successfully, but I did notice that there was some discrency in the tests. This is because the dockerui checks the docker status, but that could fail in the previous test. When we use `cy.waitAndReloadUntil`, we do not really fail if the condition fails to be met. This causes the CI to fail in general.
This explicitly fails if our condition is never met. Otherwise, the test runs as usual.
```js
describe('123', () => {
it('Test Case', () => {
cy.login();
cy.visit('/admin/docker');
// eslint-disable-next-line no-restricted-syntax
cy.waitAndReloadUntil(() => {
return cy.get('[data-testid="docker-status"]')
.invoke('text')
.then((text) => {
return text.includes('Text does not exist');
});
}, 10000, 500);
});
});
```
This grabs …
=> [Testing:Developer] Explicit fail on cypress unmet condition

site/app/templates/grading/electronic/RubricPanel.twig, site/app/views/grading/ElectronicGraderView.php
There is currently no way for a TA to distinguish who is a withdrawn student or not. If they navigate using the navigating button, they might accidentally grade a withdrawn student, who doesn't actually need grading.
This PR aims to add banners to distinguish the withdrawn status. In addition, this slightly fixes a bug where a overridden student submits to a gradeable and the text not appearing on the rubric panel.
#11882 will add withdrawn students, then it would be easier to test
=> [Feature:TAGrading] Withdrawn Student Banner

site/app/libraries/NotebookUtils.php
This change is necessary because it fixes a TypeError that occurs when trying to render a Jupyter Notebook with a cell source that is only a string and not a list.
Rendering the notebook should now successfully account for a string source, as it did prior to #11891. 
Before
After
Notebook successfully renders.
1. Reviewer can modify an existing notebook example metadata such that a cell's source attribute is a string.
2. Create any gradeable.
3. Submit the modified notebook example.
4. View rendered example via popup.
No tests needed for UI.
=> [Bugfix:Autograding] Render Jupyter Notebook TypeError

autograder/autograder/autograding_utils.py, autograder/submitty_autograding_shipper.py, autograder/tests/test_write_grade_history.py, bin/regrade.py, site/app/controllers/student/SubmissionController.php
Whenever we click regrade, we have no idea who the submission has been graded by. If we want to include students regrading, we should have an idea of who regraded the submission. Therefore, we should add this in the queue file, which adds it to the history file.
Adds the user who regrades into the queue and history file
Make sure that autograding does not break. I have tested team, vcs, and notebook submissions. I have also verified that the history with regrade_by is written to the file.
Unit tests are included. E2E tests would still have to be written.
=> [Feature:Autograding] Add regrade_by to autograding history

site/app/templates/grading/simple/Display.twig, site/public/css/details.css, site/public/css/server.css, site/public/css/simple-grading.css
Currently, the details table for simple gradeables is messy, with labels and keys overlaying on top of each other.
Labels and keys are now neatly spaced:
Go to the sample course --> gradeables --> scroll all the way down to `Grading Grades Released Lab` --> ensure the details table is now evenly spaced
This PR may affect other tables. However, I couldn't find any issues with the ones I found on other pages.
=> [Bugfix:InstructorUI] Fix Simple Gradeable Key

site/public/js/gradeable.js
When using the edit page on firefox, the rubric sometimes fails to render. This might be because `loadTemplates()` is both called for the rubric and for rendering the redactions page. Fixing the double rendering fixes the issue.
There are two solutions, one is to prevent it from double rendering, which can be inconsistent as firefox event loop issues keep popping up. The other solution, which is the new behavior, forces the rendering to only be once, making it more reliable in the future.
Load firefox before PR. Refresh constantly and watch rubric constantly break. Load firefox after PR, should not be breaking rubric.
Editing to add image of reported issue
Left is Firefox, right is Chrome.
=> [Bugfix:InstructorUI] Fix Rubric Rendering on Firefox

site/app/templates/grading/simple/Display.twig, site/public/css/simple-grading.css
#12062 fixed the key, but broke simple gradeable checkpoints since they shared the same CSS classes.
Separated the CSS classes of the key and the checkpoint buttons.
Go to sample --> Grades Released Lab --> Make sure the page looks normal
=> [Bugfix:InstructorUI] Simple Gradeable Checkpoint Fix

site/cypress/e2e/Cypress-UI/sidebar.spec.js
Currently, the sidebar cypress test fails on main due to a cypress version mismatch with an external plugin.
Before, in this situation we were using 'attachFile' which is from an external plugin.
Now, we are using the built-in function 'selectFile' which uses a different location, but it's easily changed. 
Mainly, just review the code, and check that the tests are now passing in CI. 
This will fix one of the many failing tests in Main.
=> [Bugfix:Developer] Fix Sidebar Cypress Test

site/app/controllers/grading/ElectronicGraderController.php, site/phpstan-baseline.neon
Currently if a gradeable has autograding but no tagrading or autograding with unfinished tagrading, student that do not have tagrading data will not be included in autograding statistics.
Any student with autograding outside of the null section will be included in autograding statistics.
1. Submit to a gradeable with autograding on main (I used tutorial 01)
2. Notice that the autograding statistics do not change
3. View on branch
=> [Bugfix:TAGrading] Show autograding stats before TAGrading

site/ts/ta-grading-rubric.ts
Before this nothing in submissions_processed would be considered for auto open and pdfs would be opened by default
Files in submissions_processed are considered for auto open and pngs would be opened by default.
1. Create a bulk upload for an exam
2. Create components assigned to specific pages
3. Open the components and see what gets opened on main vs this pr
=> [Bugfix:TAGrading] Fix component auto-open

site/app/templates/submission/homework/CurrentVersionResults.twig
Currently there is a frog robot error whenever a student a student downloads a file from submissions_processed as described in #12082
Fixes #12082 and all other downloads from submissions_processed
1. Have a file in submissions processed and attempt to download it as a student on main
2. See frog robot
3. Re-attempt on branch
4. See downloaded file
=> [Bugfix:Submission] Fix download from submissions_processed

more_autograding_examples/test_notes_upload/config/config.json, more_autograding_examples/test_notes_upload_3page/config/config.json
The list of allowed systems calls for pdflatex on the notes page gradeables needs to be updated.
Before the change, the pdf in testcase #2 containing the instructor 'exam' with the student notes attached was not viewable.
The pdf was not produced/was corrupted because a system call was failing during one of the pdf processing steps.
After the change, the pdf is viewable.
We should continue to add more automated testing of these gradeables.
=> [Bugfix:Autograding] system calls on pdf_notes_page gradeables
